### ISSUE TITLE
能否提供更详细的文档，尝试移植Android

### ISSUE THREAD

**Issue by Freedom0925** [mamoe/mirai#1]
能否提供详细文档，或者协议层能否单独打包成jar，想移植到Android客户端。

**Comment by landall** [comment]
好像现在用安卓QQ协议的比较多？

**Comment by Him188** [comment]
@Freedom0925  感谢你的支持, 我们还正在努力开发中, 后续会写文档.
登录协议来自一个易语言写的软件, 我们相当于是翻译了一遍.
而且这登录协议比较老, 大概是TIM1.0.4的版本, 几乎只有登录可以用, 而且现在都没TIM客户端可以配合抓包研究了. 
消息解析是我们自己写的, MessageChain模式也还有待提高, 现在在某些情况下还会解析错误.

TIM协议还更换了加密方式, 我没有如此硬核的技术破解加密.....
现在正在尝试解决这个问题...

**Comment by Freedom0925** [comment]
@Him188  期待后续版本

**Comment by landall** [comment]
> @Freedom0925 感谢你的支持, 我们还正在努力开发中, 后续会写文档.
> 登录协议来自一个易语言写的软件, 我们相当于是翻译了一遍.
> 而且这登录协议比较老, 大概是TIM1.0.4的版本, 几乎只有登录可以用, 而且现在都没TIM客户端可以配合抓包研究了.
> 消息解析是我们自己写的, MessageChain模式也还有待提高, 现在在某些情况下还会解析错误.
> 
> TIM协议还更换了加密方式, 我没有如此硬核的技术破解加密.....
> 现在正在尝试解决这个问题...

那建议低调点，哈哈，在写完之前别被腾讯官方盯上。现在一份登录协议价钱可不便宜。想免费搞到不容易。

**Comment by myucxy** [comment]
最近看到了一个 IOTQQ 的 robot 程序,不过不是开源的,看登录状态是基于MAC QQ 的协议去写的,不知道MACQQ 的协议是否好解析 IOTQQ用的是GO语言的

**Comment by Him188** [comment]
@myucxy 
其实tim和qq在各平台上的协议都是差不多的
现在已经解决了加密问题, 差时间分析了.

**Comment by landall** [comment]
> @myucxy
> 其实tim和qq在各平台上的协议都是差不多的
> 现在已经解决了加密问题, 差时间分析了.

加密基本是靠反编译分析，不是靠抓包，抓包分析不出来的。腾讯干过把某个加密算法的8轮循环变4轮这种类型的做法来反猜协议的。

**Comment by Him188** [comment]
2019年10月8日 22:50，landall <notifications@github.com>写道：

@myucxy

其实tim和qq在各平台上的协议都是差不多的

现在已经解决了加密问题, 差时间分析了.



加密基本是靠反编译分析，不是靠抓包，抓包分析不出来的。腾讯干过把某个加密算法的8轮循环变4轮这种类型的做法来反猜协议的。



—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.

是的，我的意思是分析包解析和发送。

**Comment by PeratX** [comment]
目前移植Android应该没太大问题，纯Java/Kotlin实现

**Comment by Him188** [comment]
@Freedom0925 Mirai 是跨平台的, 如果你有意愿的话, 可以来帮助实现 Android 平台部分

**Comment by Freedom0925** [comment]
对于将mirai移植到android平台我是非常愿意的，但是由于近期工作繁忙，短时间内恐怕无法不能进行移植。如果您愿意，可以降整体流程图发给我，我会利用空闲时间进行移植工作

**Comment by Him188** [comment]
其实只需要实现15个左右函数。MD5，CRC32，图片读取等。
可能还需要对Android做特定的扩展。
现在我在添加注释，过几天我会添加Android分支但我对Android不熟悉，有时间的话您可以帮助我们实现这些方法，感谢。

**Comment by Freedom0925** [comment]
留下联系方式吧，方便交流

**Comment by Him188** [comment]
QQ 1040400290
微信 Him188

QQ 会更好, 我会更快回复你

**Comment by Him188** [comment]
已完成 Android 支持
