### ISSUE TITLE
mirai 的首字母究竟是大写还是小写?

### ISSUE THREAD

**Issue by Cyl18** [mamoe/mirai#1006]
项目里 mirai 和 Mirai 混用
是否有统一标准?

![image](https://user-images.githubusercontent.com/14993992/107322168-e740ce00-6ade-11eb-9a0c-1a41c6f0bea8.png)

![image](https://user-images.githubusercontent.com/14993992/107322210-faec3480-6ade-11eb-958e-405904eac8d7.png)

![image](https://user-images.githubusercontent.com/14993992/107322238-093a5080-6adf-11eb-9540-4c5bd3087836.png)

**Comment by Him188** [comment]
大小写均可我觉得

**Comment by Karlatemp** [comment]
`Mirai` 和 `mirai` 均可我认为

**Comment by Karlatemp** [comment]
看语法情况吧，比如纯英文句子位于开头的单词首字母大写

只是个习惯问题，大小写均可

**Comment by Cyl18** [comment]
![image](https://user-images.githubusercontent.com/14993992/107328393-9bdfed00-6ae9-11eb-8078-6ddf0af410b5.png)

我主要会觉得混用会让强迫症不爽（
比如这里 Http HTTP
那我先 close 了 要是有兴趣统一可以统一一下某些地方
