### ISSUE TITLE
处理来自客户端的 CR (\r) 与 CRLF (\r\n) 换行

### ISSUE THREAD

**Issue by xzFB16A74EFFF04AF1006F040BE86D6262** [mamoe/mirai#1010]
↓↓↓↓↓↓↓↓这是bot日志打印的信息↓↓↓↓↓↓↓↓
```
2021-02-10 20:28:37 V/Bot 14*******5: [金****库(5*******6)] 哟哟sama(7*****6) -> 原来这样关系的两人，，倒最后到了这一步
```

↓↓↓↓↓↓↓↓这是通过以下代码
```java
bot.getEventChannel().subscribeAlways(GroupMessageEvent.class,event -> {
            System.out.println(event.getMessage());
            System.out.println("");
        });
```
打印的信息↓↓↓↓↓↓↓↓
```
倒最后到了这一步)
```

```

```

#### 复现

1.在群里发送换行信息，如：
原来这样关系的两人，，
倒最后到了这一步
2.在mirai里打印群信息

> 留言: 无法根据源消息文本判断此区域的正确格式, 请自行编辑为正确格式
> 请正确描述复现步骤
> ---- Karlatemp

#### 版本
- mirai-core: `2.3.2`

**Comment by sandtechnology** [comment]
信息不应该换行 否则将破坏日志的格式（

**Comment by Him188** [comment]
请重新描述问题，说明期望的结果和实际结果

**Comment by xzFB16A74EFFF04AF1006F040BE86D6262** [comment]
期望结果：原来这样关系的两人，，倒最后到了这一步
实际结果：倒最后到了这一步)
简单来说就是在pc端的qq上发送一个多行信息，结果通过getMessage只能得到该信息的最后一行信息

**Comment by Karlatemp** [comment]
GitHub 使用 Markdown 语法，请使用 `代码区域` 将日志和代码片段 包括起来以保留 换行和空格 等

并正确描述期望的结果和实际结果

`@see` https://www.runoob.com/markdown/md-code.html

**Comment by Karlatemp** [comment]
这个问题很有意思，最终确定的原因是 `\r`, `\n` 的问题

在 Windows QQ 中发送换行时实际发送的换行符为 `\r`, 并非通用的 `\n`
在 Android QQ 中发送的换行是 `\n`

Mirai 目前并没有处理 `\r`, `\r` 在控制台的意思为重置光标(`将输出位置移动至行首`), 也就是 `println(message)` 会有如此奇怪的输出的原因

For mamoe:
`\r` 在控制台中意味着重置光标, 但是在客户端中的意思为换行 (`\n`), 可以将收到的 `CR (\r)`,`CRLF (\r\n)` 全部换成 `LF (\n)`

已经确定 `CR (\r)`, `CRLF (\r\n)` 的显示效果与 `LF (\n)` 一样

**Comment by sandtechnology** [comment]
> 
> 
> 这个问题很有意思，最终确定的原因是 `\r`, `\n` 的问题
> 
> 在 Windows QQ 中发送换行时实际发送的换行符为 `\r`, 并非通用的 `\n`
> 在 Android QQ 中发送的换行是 `\n`
> 
> Mirai 目前并没有处理 `\r`, `\r` 在控制台的意思为重置光标(`将输出位置移动至行首`), 也就是 `println(message)` 会有如此奇怪的输出的原因
> 
> For mamoe:
> `\r` 在控制台中意味着重置光标, 但是在客户端中的意思为换行 (`\n`), 可以将收到的 `CR (\r)`,`CRLF (\r\n)` 全部换成 `LF (\n)`
> 
> 已经确定 `CR (\r)`, `CRLF (\r\n)` 的显示效果与 `LF (\n)` 一样

这个应该可以在打印时或者处理PlainText时处理 但是可能会因为处理点不一样影响性能（
