### ISSUE TITLE
好友消息无法接收

### ISSUE THREAD

**Issue by Minepig** [mamoe/mirai#1016]
更新`2.4-M1`版本后，机器人失去了好友相关的功能。
具体表现为：1、无法接收任何好友消息；2、使用mirai-http-api的`friendList`API获取不到好友列表

#### 复现

使用mcl自动更新`2.4-M1`版本，向机器人发送一条好友消息，观察console，应该没有好友消息事件的log

#### 版本
- mirai-core: `2.4-M1` 
- mirai-console: `2.4-M1`
- mirai-http-api: `1.9.8`
- 操作系统: win10
- 使用mirai-console-loader自动更新与启动

#### 补充信息

已经证实是`2.4-M1`版本的问题——手动切换回`2.3.2`版本后功能恢复正常

**Comment by sandtechnology** [comment]
1.你是如何获取好友消息的？
2.你是如何获知好友消息功能异常的？
3.网络日志？

**Comment by Him188** [comment]
可能是好友列表缓存问题，因此已经在2.4-RC（即将发布）默认关闭缓存

**Comment by Minepig** [comment]
> 1.你是如何获取好友消息的？
> 2.你是如何获知好友消息功能异常的？
> 3.网络日志？

1. 使用`mirai-http-api`
2. 简单点说就是更新以后发现机器人坏了，翻了翻`mirai-console`的消息记录压根就没有好友消息
3. 日志里面似乎没有查到有相关的信息（就是压根没有好友消息的记录），可能是我没开debug

我在0:17:27和0:18:03（根据Tim的消息记录）给机器人发送了两条好友消息，以下为log：
```
[0m2021-02-12 00:14:56 V/Net 3461119188: Recv: MessageSvcPbSendMsg.Response.SUCCESS[0m
[0m2021-02-12 00:15:02 V/Net 3461119188: Send: OnlinePush.RespPush[0m
[0m2021-02-12 00:15:04 V/Net 3461119188: Send: OnlinePush.RespPush[0m
[0m2021-02-12 00:15:09 V/Net 3461119188: Send: OnlinePush.RespPush[0m
[0m2021-02-12 00:15:11 V/Net 3461119188: Send: OnlinePush.RespPush[0m
[96m2021-02-12 00:15:16 D/Net 3461119188: Unknown server messages [0m
[0m2021-02-12 00:15:16 V/Net 3461119188: Send: OnlinePush.RespPush[0m
[0m2021-02-12 00:15:17 V/Net 3461119188: Send: OnlinePush.RespPush[0m
[0m2021-02-12 00:15:24 V/Net 3461119188: Send: OnlinePush.RespPush[0m
[0m2021-02-12 00:15:47 V/Net 3461119188: Send: Heartbeat.Alive[0m
[0m2021-02-12 00:15:47 V/Net 3461119188: Recv: Heartbeat.Alive.Response[0m
[0m2021-02-12 00:17:26 V/Net 3461119188: Recv: RequestPushNotify(uin=3461119188, ctype=1, strService=MessageSvc, strCmd=PushNotify, usMsgType=166, stMsgInfo=net.mamoe.mirai.internal.network.protocol.data.jce.MsgInfo@296021fa)[0m
[0m2021-02-12 00:17:26 V/Net 3461119188: Send: MessageSvc.PbGetMsg[0m
[0m2021-02-12 00:17:26 V/Net 3461119188: Send: MessageSvc.PbDeleteMsg[0m
[0m2021-02-12 00:17:26 V/Net 3461119188: Send: MessageSvc.PbGetMsg[0m
[0m2021-02-12 00:17:26 V/Net 3461119188: Send: MessageSvc.PbDeleteMsg[0m
[0m2021-02-12 00:17:26 V/Net 3461119188: Send: MessageSvc.PbGetMsg[0m
[0m2021-02-12 00:17:26 V/Net 3461119188: Send: MessageSvc.PbDeleteMsg[0m
[0m2021-02-12 00:17:26 V/Net 3461119188: Send: MessageSvc.PbGetMsg[0m
[0m2021-02-12 00:17:26 V/Net 3461119188: Send: MessageSvc.PbDeleteMsg[0m
[0m2021-02-12 00:17:26 V/Net 3461119188: Send: MessageSvc.PbGetMsg[0m
[0m2021-02-12 00:17:26 V/Net 3461119188: Send: MessageSvc.PbDeleteMsg[0m
[0m2021-02-12 00:17:26 V/Net 3461119188: Send: MessageSvc.PbGetMsg[0m
[0m2021-02-12 00:17:26 V/Net 3461119188: Send: MessageSvc.PbDeleteMsg[0m
[0m2021-02-12 00:17:26 V/Net 3461119188: Send: MessageSvc.PbGetMsg[0m
[0m2021-02-12 00:17:27 V/Net 3461119188: Send: MessageSvc.PbDeleteMsg[0m
[0m2021-02-12 00:17:27 V/Net 3461119188: Send: MessageSvc.PbGetMsg[0m
[0m2021-02-12 00:17:27 V/Net 3461119188: Send: MessageSvc.PbDeleteMsg[0m
[0m2021-02-12 00:17:27 V/Net 3461119188: Send: MessageSvc.PbGetMsg[0m
[0m2021-02-12 00:17:27 V/Net 3461119188: Send: MessageSvc.PbDeleteMsg[0m
[0m2021-02-12 00:17:27 V/Net 3461119188: Send: MessageSvc.PbGetMsg[0m
[0m2021-02-12 00:17:27 V/Net 3461119188: Send: MessageSvc.PbDeleteMsg[0m
[0m2021-02-12 00:17:27 V/Net 3461119188: Send: MessageSvc.PbGetMsg[0m
[0m2021-02-12 00:17:27 V/Net 3461119188: Send: MessageSvc.PbDeleteMsg[0m
[0m2021-02-12 00:17:27 V/Net 3461119188: Send: MessageSvc.PbGetMsg[0m
[0m2021-02-12 00:17:27 V/Net 3461119188: Send: MessageSvc.PbDeleteMsg[0m
[0m2021-02-12 00:18:01 V/Net 3461119188: Recv: RequestPushNotify(uin=3461119188, ctype=1, strService=MessageSvc, strCmd=PushNotify, usMsgType=166, stMsgInfo=net.mamoe.mirai.internal.network.protocol.data.jce.MsgInfo@10e4def2)[0m
[0m2021-02-12 00:18:01 V/Net 3461119188: Send: MessageSvc.PbGetMsg[0m
[0m2021-02-12 00:18:01 V/Net 3461119188: Send: MessageSvc.PbDeleteMsg[0m
[0m2021-02-12 00:18:01 V/Net 3461119188: Send: MessageSvc.PbGetMsg[0m
[0m2021-02-12 00:18:01 V/Net 3461119188: Send: MessageSvc.PbDeleteMsg[0m
[0m2021-02-12 00:18:01 V/Net 3461119188: Send: MessageSvc.PbGetMsg[0m
[0m2021-02-12 00:18:01 V/Net 3461119188: Send: MessageSvc.PbDeleteMsg[0m
[0m2021-02-12 00:18:01 V/Net 3461119188: Send: MessageSvc.PbGetMsg[0m
[0m2021-02-12 00:18:01 V/Net 3461119188: Send: MessageSvc.PbDeleteMsg[0m
[0m2021-02-12 00:18:01 V/Net 3461119188: Send: MessageSvc.PbGetMsg[0m
[0m2021-02-12 00:18:01 V/Net 3461119188: Send: MessageSvc.PbDeleteMsg[0m
[0m2021-02-12 00:18:01 V/Net 3461119188: Send: MessageSvc.PbGetMsg[0m
[0m2021-02-12 00:18:01 V/Net 3461119188: Send: MessageSvc.PbDeleteMsg[0m
[0m2021-02-12 00:18:01 V/Net 3461119188: Send: MessageSvc.PbGetMsg[0m
[0m2021-02-12 00:18:02 V/Net 3461119188: Send: MessageSvc.PbDeleteMsg[0m
[0m2021-02-12 00:18:02 V/Net 3461119188: Send: MessageSvc.PbGetMsg[0m
[0m2021-02-12 00:18:02 V/Net 3461119188: Send: MessageSvc.PbDeleteMsg[0m
[0m2021-02-12 00:18:02 V/Net 3461119188: Send: MessageSvc.PbGetMsg[0m
[0m2021-02-12 00:18:02 V/Net 3461119188: Send: MessageSvc.PbDeleteMsg[0m
[0m2021-02-12 00:18:02 V/Net 3461119188: Send: MessageSvc.PbGetMsg[0m
[0m2021-02-12 00:18:02 V/Net 3461119188: Send: MessageSvc.PbDeleteMsg[0m
[0m2021-02-12 00:18:02 V/Net 3461119188: Send: MessageSvc.PbGetMsg[0m
[0m2021-02-12 00:18:02 V/Net 3461119188: Send: MessageSvc.PbDeleteMsg[0m
[0m2021-02-12 00:18:02 V/Net 3461119188: Send: MessageSvc.PbGetMsg[0m
[0m2021-02-12 00:18:02 V/Net 3461119188: Send: MessageSvc.PbDeleteMsg[0m
[0m2021-02-12 00:18:06 V/Net 3461119188: Send: OnlinePush.RespPush[0m
[0m2021-02-12 00:18:15 V/Net 3461119188: Send: OnlinePush.RespPush[0m
[92m2021-02-12 00:19:09 I/Net 3461119188: Connected to server 114.221.144.89:80[0m
[0m2021-02-12 00:19:09 V/Net 3461119188: Send: wtlogin.login[0m
[0m2021-02-12 00:19:09 V/Net 3461119188: Recv: WtLogin.Login.LoginPacketResponse.DeviceLockLogin[0m
[0m2021-02-12 00:19:09 V/Net 3461119188: Send: wtlogin.login[0m
[0m2021-02-12 00:19:10 V/Net 3461119188: Recv: LoginPacketResponse.Success[0m
[92m2021-02-12 00:19:10 I/Net 3461119188: Login successful[0m
[0m2021-02-12 00:19:10 V/Net 3461119188: Send: StatSvc.register[0m
[0m2021-02-12 00:19:10 V/Net 3461119188: Recv: Response(StatSvc.register)[0m
[92m2021-02-12 00:19:10 I/Net 3461119188: Scheduled key refresh in 5h 55min 0.0s.[0m
[0m2021-02-12 00:19:10 V/Net 3461119188: Send: StatSvc.register[0m
[0m2021-02-12 00:19:10 V/Net 3461119188: Recv: Response(StatSvc.register)[0m
```

**Comment by Him188** [comment]
> > 1.你是如何获取好友消息的？
> > 2.你是如何获知好友消息功能异常的？
> > 3.网络日志？
> 
> 1. 使用`mirai-http-api`
> 2. 简单点说就是更新以后发现机器人坏了，翻了翻`mirai-console`的消息记录压根就没有好友消息
> 3. 日志里面似乎没有查到有相关的信息（就是压根没有好友消息的记录），可能是我没开debug
> 
> 我在0:17:27和0:18:03（根据Tim的消息记录）给机器人发送了两条好友消息，以下为log：
> 
> ```
> �[0m2021-02-12 00:14:56 V/Net 3461119188: Recv: MessageSvcPbSendMsg.Response.SUCCESS�[0m
> �[0m2021-02-12 00:15:02 V/Net 3461119188: Send: OnlinePush.RespPush�[0m
> �[0m2021-02-12 00:15:04 V/Net 3461119188: Send: OnlinePush.RespPush�[0m
> �[0m2021-02-12 00:15:09 V/Net 3461119188: Send: OnlinePush.RespPush�[0m
> �[0m2021-02-12 00:15:11 V/Net 3461119188: Send: OnlinePush.RespPush�[0m
> �[96m2021-02-12 00:15:16 D/Net 3461119188: Unknown server messages �[0m
> �[0m2021-02-12 00:15:16 V/Net 3461119188: Send: OnlinePush.RespPush�[0m
> �[0m2021-02-12 00:15:17 V/Net 3461119188: Send: OnlinePush.RespPush�[0m
> �[0m2021-02-12 00:15:24 V/Net 3461119188: Send: OnlinePush.RespPush�[0m
> �[0m2021-02-12 00:15:47 V/Net 3461119188: Send: Heartbeat.Alive�[0m
> �[0m2021-02-12 00:15:47 V/Net 3461119188: Recv: Heartbeat.Alive.Response�[0m
> �[0m2021-02-12 00:17:26 V/Net 3461119188: Recv: RequestPushNotify(uin=3461119188, ctype=1, strService=MessageSvc, strCmd=PushNotify, usMsgType=166, stMsgInfo=net.mamoe.mirai.internal.network.protocol.data.jce.MsgInfo@296021fa)�[0m
> �[0m2021-02-12 00:17:26 V/Net 3461119188: Send: MessageSvc.PbGetMsg�[0m
> �[0m2021-02-12 00:17:26 V/Net 3461119188: Send: MessageSvc.PbDeleteMsg�[0m
> �[0m2021-02-12 00:17:26 V/Net 3461119188: Send: MessageSvc.PbGetMsg�[0m
> �[0m2021-02-12 00:17:26 V/Net 3461119188: Send: MessageSvc.PbDeleteMsg�[0m
> �[0m2021-02-12 00:17:26 V/Net 3461119188: Send: MessageSvc.PbGetMsg�[0m
> �[0m2021-02-12 00:17:26 V/Net 3461119188: Send: MessageSvc.PbDeleteMsg�[0m
> �[0m2021-02-12 00:17:26 V/Net 3461119188: Send: MessageSvc.PbGetMsg�[0m
> �[0m2021-02-12 00:17:26 V/Net 3461119188: Send: MessageSvc.PbDeleteMsg�[0m
> �[0m2021-02-12 00:17:26 V/Net 3461119188: Send: MessageSvc.PbGetMsg�[0m
> �[0m2021-02-12 00:17:26 V/Net 3461119188: Send: MessageSvc.PbDeleteMsg�[0m
> �[0m2021-02-12 00:17:26 V/Net 3461119188: Send: MessageSvc.PbGetMsg�[0m
> �[0m2021-02-12 00:17:26 V/Net 3461119188: Send: MessageSvc.PbDeleteMsg�[0m
> �[0m2021-02-12 00:17:26 V/Net 3461119188: Send: MessageSvc.PbGetMsg�[0m
> �[0m2021-02-12 00:17:27 V/Net 3461119188: Send: MessageSvc.PbDeleteMsg�[0m
> �[0m2021-02-12 00:17:27 V/Net 3461119188: Send: MessageSvc.PbGetMsg�[0m
> �[0m2021-02-12 00:17:27 V/Net 3461119188: Send: MessageSvc.PbDeleteMsg�[0m
> �[0m2021-02-12 00:17:27 V/Net 3461119188: Send: MessageSvc.PbGetMsg�[0m
> �[0m2021-02-12 00:17:27 V/Net 3461119188: Send: MessageSvc.PbDeleteMsg�[0m
> �[0m2021-02-12 00:17:27 V/Net 3461119188: Send: MessageSvc.PbGetMsg�[0m
> �[0m2021-02-12 00:17:27 V/Net 3461119188: Send: MessageSvc.PbDeleteMsg�[0m
> �[0m2021-02-12 00:17:27 V/Net 3461119188: Send: MessageSvc.PbGetMsg�[0m
> �[0m2021-02-12 00:17:27 V/Net 3461119188: Send: MessageSvc.PbDeleteMsg�[0m
> �[0m2021-02-12 00:17:27 V/Net 3461119188: Send: MessageSvc.PbGetMsg�[0m
> �[0m2021-02-12 00:17:27 V/Net 3461119188: Send: MessageSvc.PbDeleteMsg�[0m
> �[0m2021-02-12 00:18:01 V/Net 3461119188: Recv: RequestPushNotify(uin=3461119188, ctype=1, strService=MessageSvc, strCmd=PushNotify, usMsgType=166, stMsgInfo=net.mamoe.mirai.internal.network.protocol.data.jce.MsgInfo@10e4def2)�[0m
> �[0m2021-02-12 00:18:01 V/Net 3461119188: Send: MessageSvc.PbGetMsg�[0m
> �[0m2021-02-12 00:18:01 V/Net 3461119188: Send: MessageSvc.PbDeleteMsg�[0m
> �[0m2021-02-12 00:18:01 V/Net 3461119188: Send: MessageSvc.PbGetMsg�[0m
> �[0m2021-02-12 00:18:01 V/Net 3461119188: Send: MessageSvc.PbDeleteMsg�[0m
> �[0m2021-02-12 00:18:01 V/Net 3461119188: Send: MessageSvc.PbGetMsg�[0m
> �[0m2021-02-12 00:18:01 V/Net 3461119188: Send: MessageSvc.PbDeleteMsg�[0m
> �[0m2021-02-12 00:18:01 V/Net 3461119188: Send: MessageSvc.PbGetMsg�[0m
> �[0m2021-02-12 00:18:01 V/Net 3461119188: Send: MessageSvc.PbDeleteMsg�[0m
> �[0m2021-02-12 00:18:01 V/Net 3461119188: Send: MessageSvc.PbGetMsg�[0m
> �[0m2021-02-12 00:18:01 V/Net 3461119188: Send: MessageSvc.PbDeleteMsg�[0m
> �[0m2021-02-12 00:18:01 V/Net 3461119188: Send: MessageSvc.PbGetMsg�[0m
> �[0m2021-02-12 00:18:01 V/Net 3461119188: Send: MessageSvc.PbDeleteMsg�[0m
> �[0m2021-02-12 00:18:01 V/Net 3461119188: Send: MessageSvc.PbGetMsg�[0m
> �[0m2021-02-12 00:18:02 V/Net 3461119188: Send: MessageSvc.PbDeleteMsg�[0m
> �[0m2021-02-12 00:18:02 V/Net 3461119188: Send: MessageSvc.PbGetMsg�[0m
> �[0m2021-02-12 00:18:02 V/Net 3461119188: Send: MessageSvc.PbDeleteMsg�[0m
> �[0m2021-02-12 00:18:02 V/Net 3461119188: Send: MessageSvc.PbGetMsg�[0m
> �[0m2021-02-12 00:18:02 V/Net 3461119188: Send: MessageSvc.PbDeleteMsg�[0m
> �[0m2021-02-12 00:18:02 V/Net 3461119188: Send: MessageSvc.PbGetMsg�[0m
> �[0m2021-02-12 00:18:02 V/Net 3461119188: Send: MessageSvc.PbDeleteMsg�[0m
> �[0m2021-02-12 00:18:02 V/Net 3461119188: Send: MessageSvc.PbGetMsg�[0m
> �[0m2021-02-12 00:18:02 V/Net 3461119188: Send: MessageSvc.PbDeleteMsg�[0m
> �[0m2021-02-12 00:18:02 V/Net 3461119188: Send: MessageSvc.PbGetMsg�[0m
> �[0m2021-02-12 00:18:02 V/Net 3461119188: Send: MessageSvc.PbDeleteMsg�[0m
> �[0m2021-02-12 00:18:06 V/Net 3461119188: Send: OnlinePush.RespPush�[0m
> �[0m2021-02-12 00:18:15 V/Net 3461119188: Send: OnlinePush.RespPush�[0m
> �[92m2021-02-12 00:19:09 I/Net 3461119188: Connected to server 114.221.144.89:80�[0m
> �[0m2021-02-12 00:19:09 V/Net 3461119188: Send: wtlogin.login�[0m
> �[0m2021-02-12 00:19:09 V/Net 3461119188: Recv: WtLogin.Login.LoginPacketResponse.DeviceLockLogin�[0m
> �[0m2021-02-12 00:19:09 V/Net 3461119188: Send: wtlogin.login�[0m
> �[0m2021-02-12 00:19:10 V/Net 3461119188: Recv: LoginPacketResponse.Success�[0m
> �[92m2021-02-12 00:19:10 I/Net 3461119188: Login successful�[0m
> �[0m2021-02-12 00:19:10 V/Net 3461119188: Send: StatSvc.register�[0m
> �[0m2021-02-12 00:19:10 V/Net 3461119188: Recv: Response(StatSvc.register)�[0m
> �[92m2021-02-12 00:19:10 I/Net 3461119188: Scheduled key refresh in 5h 55min 0.0s.�[0m
> �[0m2021-02-12 00:19:10 V/Net 3461119188: Send: StatSvc.register�[0m
> �[0m2021-02-12 00:19:10 V/Net 3461119188: Recv: Response(StatSvc.register)�[0m
> ```

尝试删除cache/friends.json
