### ISSUE TITLE
对QQ新增的自带表情进行解析

### ISSUE THREAD

**Issue by I-love-study** [mamoe/mirai#1022]
Mirai版本：2.4-RC
在以下表情被接收的时候接收到的并不是表情的mirai码而是"/xxx"这种格式的文本消息
(QQ自带表情更新真快OMO)
![image](https://user-images.githubusercontent.com/39652142/107871232-ada30500-6eda-11eb-9496-2258d5e6b4e7.png)
/左拜年/右拜年/好闪/胖三斤/牛啊/元宝/拜谢/真好/拿到红包/期待/睁眼/请/哦/魔鬼笑/摸鱼/面无表情/狂笑/敬礼/无眼笑/牛气冲天/牛转钱坤/汪汪/呵呵哒/吃瓜/emm/暗中观察/问号脸/哦哟/辣眼睛/捂脸/沧桑/脑阔疼/忙到飞起/搬砖中/口罩护体/加油抱抱/加油必胜/红包包
![image](https://user-images.githubusercontent.com/39652142/107871183-5a30b700-6eda-11eb-839f-f6e2bf27bc95.png)
/求红包/谢红包/新年烟花/敲开心/震惊/让我康康/汗/打脸/击掌/头撞击/甩头/扔狗/糊脸/偷看/拍桌/啵啵/扯一扯/喷脸/拍头/舔一舔/干杯/扇脸/蹭一蹭/撩一撩/哼/掐一掐/顶呱呱/抱抱/原谅/佛系/拽炸天/颤抖/生日快乐/嘲讽/开枪/啃头/恭喜/惊呆/暴击/拍手

**Comment by sandtechnology** [comment]
这些表情早已被解析并更新 请提供复现方式

**Comment by sandtechnology** [comment]
Edit：无法进行复现 请确认mirai-core版本为最新版本

**Comment by I-love-study** [comment]
本人使用的是Mirai-core-all 2.4-RC
在https://github.com/mamoe/mirai/blob/dev/mirai-core-api/src/commonMain/kotlin/message/data/Face.kt 中确实有部分表情没有支持(图1的/左拜年/右拜年/好闪/胖三斤/牛啊/元宝/拜谢/真好/拿到红包/期待与图2的/求红包/谢红包/新年烟花/敲开心/震惊/让我康康)

然后似乎写在Face.kt里但没有成功解析的表情是[mirai:face:212]之后的表情
而Face.kt中并没有编号为213的表情，我猜测可能是因为这个原因导致的
https://github.com/mamoe/mirai/blob/9d20d281480e59e1df1db622e7cff922c1a9e947/mirai-core-api/src/commonMain/kotlin/message/data/Face.kt#L358-L361

下面是相关截图：
![image](https://user-images.githubusercontent.com/39652142/107872099-a253d780-6ee2-11eb-916e-5a52f48e6a0f.png)
![image](https://user-images.githubusercontent.com/39652142/107872179-49d10a00-6ee3-11eb-8cf0-662c05d158d1.png)

**Comment by sandtechnology** [comment]
你是否在使用pad协议？这可能是QQ服务器自动兼容的结果，请检查协议类型

**Comment by sandtechnology** [comment]
经过测试确实是QQ服务器自动兼容的结果 请切换为phone协议

**Comment by I-love-study** [comment]
在测试的时候确实是用的是PAD协议

**Comment by I-love-study** [comment]
在测试的时候确实使用的是PAD协议
在更换为PHONE协议后解析成功
