### ISSUE TITLE
添加image对象图片大小和长宽属性

### ISSUE THREAD

**Issue by Keyezi** [mamoe/mirai#1032]
【很少写issue报告，文中有问题麻烦谅解】

我制作并且开源了一个鉴黄、聊天内容审查的应用：https://github.com/YmggDEV/cc.ymgg.de-aphrodisiac
使用了百度的审核API，可以将image对象中queryUrl()获取到的链接直接传入其URL中。

但是他们要求对图片大小、长宽进行限制（以下是其API文档中内容）：https://cloud.baidu.com/doc/ANTIPORN/s/jk42xep4e

参数名称 | 数据类型 | 是否必须 | 备注
-- | -- | -- | -- 
image | String | N（和imgUrl二选一） | 待审核图像Base64编码字符串，以图像文件形式请求时必填，图像要求base64后大于等于5kb，小于等于4M，最短边大于等于128像素，小于等于4096像素，支持的图片格式：PNG、JPG、JPEG、BMP、GIF（仅对首帧进行审核）、Webp、TIFF 
imgUrl | String | N（和image二选一） | 图像URL地址，以URL形式请求，图像Url需要做UrlEncode，图像要求base64后大于等于5kb，小于等于4M，最短边大于等于128像素，小于等于4096像素支持的图片格式：PNG、JPG、JPEG、BMP、GIF（仅对首帧进行审核）、Webp、TIFF

但我不能在本地完成对其大小和长宽的判断，只能直接传入，不符合的图片传入的结果就是导致百度云返回审核失败信息：
![162009D267FE6C7F52F3F5C4389D0B43](https://user-images.githubusercontent.com/38462592/108370788-fc80cf80-7237-11eb-8032-b613ba35a44d.jpg)

目前对于我来说可行的方法就是下载图片下来对其属性进行判断，但这样子过于耗费时间、资源。
我记得以前CQ是支持获取这些信息的，不知道mirai能不能获取到，希望能在Image对象中添加相应常量。

**Comment by Karlatemp** [comment]
目前，如果你正在运行于 JVM 平台, [`ImageReader.getWidth(int)`](https://docs.oracle.com/javase/10/docs/api/javax/imageio/ImageReader.html#getWidth(int)) 可以在不读取整个图片的情况下读取其长宽信息. 如果为其他语言请自行搜索相关资料

**Comment by Keyezi** [comment]
> 目前，如果你正在运行于 JVM 平台, [`ImageReader.getWidth(int)`](https://docs.oracle.com/javase/10/docs/api/javax/imageio/ImageReader.html#getWidth(int)) 可以在不读取整个图片的情况下读取其长宽信息. 如果为其他语言请自行搜索相关资料

感谢，但是如果mirai能直接从tx服务器中获取到信息就更好了（如果可以实现的话

**Comment by Him188** [comment]
> > 目前，如果你正在运行于 JVM 平台, [`ImageReader.getWidth(int)`](https://docs.oracle.com/javase/10/docs/api/javax/imageio/ImageReader.html#getWidth(int)) 可以在不读取整个图片的情况下读取其长宽信息. 如果为其他语言请自行搜索相关资料
> 
> 感谢，但是如果mirai能直接从tx服务器中获取到信息就更好了（如果可以实现的话

服务器不一定会提供准确信息，测试中就发现有时候没有长宽数据。可以尽可能提供这些信息

**Comment by sandtechnology** [comment]
其实关于这个 服务器上传的时候也应该提供对应的长宽 所以应该用一个支持多平台的图像库来进行处理

**Comment by callng** [comment]
服务器是会返回图片的长宽信息的，如果没有返回，可能是QQ版本过低的原因。
