### ISSUE TITLE
2.4.0 java无法调用NormalMember.isMuted

### ISSUE THREAD

**Issue by RrrrLin** [mamoe/mirai#1037]
判断群员是否处于被禁言状态，查看源码时发现NormalMember有isMuted 可以用来判断，但是java不知为何无法调用这个。虽然可以通过getMuteTimeRemaining()进行判断，但还是希望修复。

#### 复现

开发中获取一个群员后尝试调用isMuted。

#### 版本
- mirai-core: `2.4.0`

**Comment by Him188** [comment]
没记错的话 isMuted 是个扩展函数，Kotlin 可以直接调用，Java 需要使用 NormalMemberKt （也可能是 MemberKt）中的静态方法 isMuted

**Comment by RrrrLin** [comment]
> 没记错的话 isMuted 是个扩展函数，Kotlin 可以直接调用，Java 需要使用 NormalMemberKt （也可能是 MemberKt）中的静态方法 isMuted

尝试后可以调用了。
`NormalMemberKt.isMuted(NormalMember)`

**Comment by Him188** [comment]
但这确实造成了不方便，可以考虑把isMuted移动到NormalMember成员？

**Comment by RrrrLin** [comment]
最近更换了2.5-M2的版本。
但是发现`NormalMemberKt.isMuted(NormalMember)`好像没有正确的判断群员是否被禁言。
具体操作为：
1.在禁言一名群员后。
2.通过命令触发调用具有以下部分代码的方法。尝试让机器人（具有管理权限）进行解除禁言操作。但是并没有正常解除禁言。
```
 if (groupMember.getPermission().equals(MemberPermission.MEMBER))
                    {
                        if (NormalMemberKt.isMuted(groupMember))
                        {
                            groupMember.unmute();
                        }
                    }
```

**Comment by Him188** [comment]
> 最近更换了2.5-M2的版本。
> 但是发现`NormalMemberKt.isMuted(NormalMember)`好像没有正确的判断群员是否被禁言。
> 具体操作为：
> 1.在禁言一名群员后。
> 2.通过命令触发调用具有以下部分代码的方法。尝试让机器人（具有管理权限）进行解除禁言操作。但是并没有正常解除禁言。
> 
> ```
>  if (groupMember.getPermission().equals(MemberPermission.MEMBER))
>                     {
>                         if (NormalMemberKt.isMuted(groupMember))
>                         {
>                             groupMember.unmute();
>                         }
>                     }
> ```

请提供相关日志

**Comment by RrrrLin** [comment]
> > 最近更换了2.5-M2的版本。
> > 但是发现`NormalMemberKt.isMuted(NormalMember)`好像没有正确的判断群员是否被禁言。
> > 具体操作为：
> > 1.在禁言一名群员后。
> > 2.通过命令触发调用具有以下部分代码的方法。尝试让机器人（具有管理权限）进行解除禁言操作。但是并没有正常解除禁言。
> > ```
> >  if (groupMember.getPermission().equals(MemberPermission.MEMBER))
> >                     {
> >                         if (NormalMemberKt.isMuted(groupMember))
> >                         {
> >                             groupMember.unmute();
> >                         }
> >                     }
> > ```
> 
> 请提供相关日志


相关日志如下。
根据仔细的测试后，发现只有通过命令bot禁言的群员，不会被NormalMemberKt.isMuted(groupMember)识别为已经禁言，其他管理员操作的禁言，可以正常识别到并进行操作解除禁言。
2021-03-11 16:52:00 I/Net : Successfully loaded group list: 2 in total.
2021-03-11 16:52:00 I/Bot : Login successful
2021-03-11 16:52:02 D/Net : Received unknown commandName: ConfigPushSvc.PushDomain
2021-03-11 16:52:02 V/Net : Recv: ConfigPushSvc.PushReq.PushReqResponse.ConfigPush
2021-03-11 16:52:02 V/Net : Saving bdh session to cache
2021-03-11 16:52:02 V/Net : Send: ConfigPushSvc.PushResp
2021-03-11 16:52:02 I/Net : ConfigPushSvc.PushReq: Config updated.
2021-03-11 16:52:07 V/Bot : [] 若凌() -> .开 权限
2021-03-11 16:52:08 V/Net : Send: MessageSvc.PbSendMsg
2021-03-11 16:52:08 V/Net : Recv: MessageSvcPbSendMsg.Response.SUCCESS
2021-03-11 16:52:08 V/Bot : Group() <- [权限]开启成功。
//此处通过命令让机器人禁言一名群员
2021-03-11 16:52:19 V/Net : Send: OidbSvc.0x570_8
2021-03-11 16:52:19 V/Net : Send: OnlinePush.RespPush
2021-03-11 16:52:19 V/Net : Recv: Response(Mute)
2021-03-11 16:52:19 V/Net : Send: MessageSvc.PbSendMsg
2021-03-11 16:52:19 V/Net : Recv: MessageSvcPbSendMsg.Response.SUCCESS
2021-03-11 16:52:19 V/Bot : Group() <- 禁言操作完成。
2021-03-11 16:52:27 V/Net : Send: OnlinePush.RespPush
//此处通过命令让机器人循环群成员并解除被禁言的人员
2021-03-11 16:52:44 V/Net : Send: MessageSvc.PbSendMsg
2021-03-11 16:52:44 V/Net : Recv: MessageSvcPbSendMsg.Response.SUCCESS
2021-03-11 16:52:44 V/Bot : Group() <- 禁言解除完毕。

**Comment by Him188** [comment]
> > > 最近更换了2.5-M2的版本。
> > > 但是发现`NormalMemberKt.isMuted(NormalMember)`好像没有正确的判断群员是否被禁言。
> > > 具体操作为：
> > > 1.在禁言一名群员后。
> > > 2.通过命令触发调用具有以下部分代码的方法。尝试让机器人（具有管理权限）进行解除禁言操作。但是并没有正常解除禁言。
> > > ```
> > >  if (groupMember.getPermission().equals(MemberPermission.MEMBER))
> > >                     {
> > >                         if (NormalMemberKt.isMuted(groupMember))
> > >                         {
> > >                             groupMember.unmute();
> > >                         }
> > >                     }
> > > ```
> > 
> > 
> > 请提供相关日志
> 
> 相关日志如下。
> 根据仔细的测试后，发现只有通过命令bot禁言的群员，不会被NormalMemberKt.isMuted(groupMember)识别为已经禁言，其他管理员操作的禁言，可以正常识别到并进行操作解除禁言。
> 2021-03-11 16:52:00 I/Net : Successfully loaded group list: 2 in total.
> 2021-03-11 16:52:00 I/Bot : Login successful
> 2021-03-11 16:52:02 D/Net : Received unknown commandName: ConfigPushSvc.PushDomain
> 2021-03-11 16:52:02 V/Net : Recv: ConfigPushSvc.PushReq.PushReqResponse.ConfigPush
> 2021-03-11 16:52:02 V/Net : Saving bdh session to cache
> 2021-03-11 16:52:02 V/Net : Send: ConfigPushSvc.PushResp
> 2021-03-11 16:52:02 I/Net : ConfigPushSvc.PushReq: Config updated.
> 2021-03-11 16:52:07 V/Bot : [] 若凌() -> .开 权限
> 2021-03-11 16:52:08 V/Net : Send: MessageSvc.PbSendMsg
> 2021-03-11 16:52:08 V/Net : Recv: MessageSvcPbSendMsg.Response.SUCCESS
> 2021-03-11 16:52:08 V/Bot : Group() <- [权限]开启成功。
> //此处通过命令让机器人禁言一名群员
> 2021-03-11 16:52:19 V/Net : Send: OidbSvc.0x570_8
> 2021-03-11 16:52:19 V/Net : Send: OnlinePush.RespPush
> 2021-03-11 16:52:19 V/Net : Recv: Response(Mute)
> 2021-03-11 16:52:19 V/Net : Send: MessageSvc.PbSendMsg
> 2021-03-11 16:52:19 V/Net : Recv: MessageSvcPbSendMsg.Response.SUCCESS
> 2021-03-11 16:52:19 V/Bot : Group() <- 禁言操作完成。
> 2021-03-11 16:52:27 V/Net : Send: OnlinePush.RespPush
> //此处通过命令让机器人循环群成员并解除被禁言的人员
> 2021-03-11 16:52:44 V/Net : Send: MessageSvc.PbSendMsg
> 2021-03-11 16:52:44 V/Net : Recv: MessageSvcPbSendMsg.Response.SUCCESS
> 2021-03-11 16:52:44 V/Bot : Group() <- 禁言解除完毕。

经检查这是另一个问题, 会在 #1155 解决
