### ISSUE TITLE
发现下载mirai-core-2.4.0.jar就是个空的

### ISSUE THREAD

**Issue by beanflame** [mamoe/mirai#1042]
发现下载mirai-core-2.4.0.jar就是个空的。
下载地址https://jcenter.bintray.com/net/mamoe/mirai-core/2.4.0/mirai-core-2.4.0.jar

```
下载地址https://jcenter.bintray.com/net/mamoe/mirai-core/2.4.0/mirai-core-2.4.0.jar
```

#### 版本
- mirai-core: `2.4.0`

**Comment by Him188** [comment]
尝试在 Maven Central 下载

**Comment by Karlatemp** [comment]
replace('mirai-core', 'mirai-core-jvm')
