### ISSUE TITLE
2.4.0 java长时间运行通过ExternalResource.create(InputStream)上传图片会生成大量临时文件

### ISSUE THREAD

**Issue by RrrrLin** [mamoe/mirai#1045]
使用ExternalResource.create(InputStream)上传图片并发送。
长时间运行后，发现在磁盘产生了大量的临时文件，导致磁盘被占用。
待磁盘被占满时再通过该方式上传图片时，会报io错误，磁盘空间已满。导致图片无法正常上传与发送。

#### 复现

1.长时间运行mirai
2.运行过程中使用ExternalResource.create(InputStream)上传不同的图片

#### 版本
- mirai-core: `2.4.0`

**Comment by Him188** [comment]
`ExternalResource` 类似 `InputStream`，请问是否有 `close` 操作?

**Comment by Him188** [comment]
若每个 `InputStream` 都只使用一次，可以使用静态方法 `Contact.uploadImage(contact, inputStream);` 上传图片, 会自动关闭创建的 `ExternalResource` 和缓存文件, 但注意 `InputStream` 还是需要手动关闭

**Comment by RrrrLin** [comment]
> 若每个 `InputStream` 都只使用一次，可以使用静态方法 `Contact.uploadImage(contact, inputStream);` 上传图片, 会自动关闭创建的 `ExternalResource` 和缓存文件, 但注意 `InputStream` 还是需要手动关闭

好的，代码中改用这个方法进行上传。运行一段时间后再观察。

**Comment by Karlatemp** [comment]
external resource设计遵守java资源类规范，需要关闭(执行 close())

TempCache策略中生成的临时文件会在close时删除


kotlin可使用 .use 扩展函数，java可使用 try-with-resource 语法


严格来说这属于调用者问题并非mirai本体问题

**Comment by RrrrLin** [comment]
> external resource设计遵守java资源类规范，需要关闭(执行 close()) TempCache策略中生成的临时文件会在close时删除 kotlin可使用 .use 扩展函数，java可使用 try-with-resource 语法 严格来说这属于调用者问题并非mirai本体问题

是我的使用错误了，因为一直以来都是直接通过`group.uploadImage(ExternalResource.create(InputStream))`使用，并未注意到ExternalResource.create()生成的实体类需要进行close。
