### ISSUE TITLE
按照错误的日志要求来反馈QQ权限问题

### ISSUE THREAD

**Issue by dragon0629** [mamoe/mirai#1050]
![image](https://user-images.githubusercontent.com/29683336/108953877-e09d8380-76a6-11eb-847c-122aa0be836d.png)

看到红字提示说让报告开发者，并确认了以下关系

1. 机器人Q与对面号有好友关系
2. 机器人在这个群里屏蔽了对面号的消息
3. 对面号在其他群里说话，该机器人可以正常接收到

于是按要求反馈完毕。

```

```

#### 复现
只要这个人在这个群说话，就会报这个，100%

#### 版本
- mirai-core: `2.2`

**Comment by Him188** [comment]
@Karlatemp 我记得在2.4解决了？

**Comment by Karlatemp** [comment]
这个是 2， 2.4的commit提交的是 64



---原始邮件---
发件人: "Him188"<notifications@github.com&gt;
发送时间: 2021年2月25日(周四) 上午7:22
收件人: "mamoe/mirai"<mirai@noreply.github.com&gt;;
抄送: "Mention"<mention@noreply.github.com&gt;;"Karlatemp"<karlatemp@vip.qq.com&gt;;
主题: Re: [mamoe/mirai] 按照错误的日志要求来反馈QQ权限问题 (#1050)




 
@Karlatemp 我记得在2.4解决了？

**Comment by Him188** [comment]
我觉得去掉这个权限判断, 采用 `member.permission` 属性

**Comment by sandtechnology** [comment]
看样子是屏蔽的flag无法正常判断导致的，不过直接采用member.permission应该就能规避掉

**Comment by dragon0629** [comment]
啊。更換了2.4，依然存在，必現的
![image](https://user-images.githubusercontent.com/29683336/109103384-c37bba00-7765-11eb-9119-576187b14e54.png)
