### ISSUE TITLE
BotOnlineEvent 事件在程序运行后好一会才会推送

### ISSUE THREAD

**Issue by jax-yu** [mamoe/mirai#1051]
1. BotOnlineEvent 事件执行的时机似乎不太对，或者说是我理解错了。理论上应该是登录成功后就会推送这个事件，但是往往程序运行后好一会才会推送
2. 2.4.0 中开启缓存会存在获取不到好友的情况

```

```

#### 版本
- mirai-core: `2.4.0`

**Comment by Him188** [comment]
1. 日志提示 `login successful` 只是登录成功, 消息会话等还没初始化完成. `BotOnlineEvent` 是在一切准备就绪 (`Bot.login` 结束) 时广播
2. 这是已知问题, 缓存不稳定, 因此默认关闭

**Comment by jax-yu** [comment]
在我测试时发现Login successful 之后。已经能和机器人正常交互了这个事件还没推送
