### ISSUE TITLE
登录异常bug，禁止登录，当前上网环境异常，如何解决？

### ISSUE THREAD

**Issue by Andy-shi001** [mamoe/mirai#1055]
登录提示信息：
11:07:21 [INFO] [NETWORK] Recv: Error(title=禁止登录, message=当前上网环境异常
，请更换网络环境或在常用设备上登录或稍后再试。, errorInfo=)

![image](https://user-images.githubusercontent.com/68884928/109373752-cd2f2a00-78eb-11eb-84de-054083d1d9ba.png)
 
[11:06:55.4938] I MiraiOK 20200629.160938 running at windows-386
[11:06:55.4947] I 此程序以Affero GPL3.0协议发布，使用时请遵守协议
[11:06:55.4947] I 代码库: github.com/LXY1226/MiraiOK gitee.com/LXY1226/MiraiOK
[11:06:55.7193] I JRE: openjdk version "1.8.0_252"
[11:06:55.7193] I JRE: OpenJDK Runtime Environment (AdoptOpenJDK)(build 1.8.0_2
2-b09)
[11:06:55.7193] I JRE: OpenJDK Client VM (AdoptOpenJDK)(build 25.252-b09, mixed
mode)
[11:06:55.7193] I 开始检查Mirai更新... 也可以通过创建.noupdate文件来禁用更新
[11:06:56.0123] I 初始化远程存储成功
[11:06:56.2369] W 下载失败 mirai/MiraiOK/.version
[11:06:56.2378] E 无法下载MiraiOK版本信息
[11:06:56.2691] W 下载失败 mirai-repo/shadow/release.json
[11:06:56.2701] E 无法下载Mirai版本信息
[11:06:56.2701] I 启动Mirai...
Using proxy: null
You are running Mirai-Console-Wrapper under E:\批处理\mirai-robot
All additional libraries are located at E:\批处理\mirai-robot\libraries
Starting Mirai Console Pure, reset by clear /content/
Starting version check...
Fetching Newest Core Version ..
Stay on current version.
Fetching Newest Console Version of Pure
Stay on current version.
Version check complete, starting Mirai
shadow-Protocol:E:\批处理\mirai-robot\content\mirai-core-qqandroid-1.0.3.jar
Console        :E:\批处理\mirai-robot\content\mirai-console-0.5.2.jar
Root           :E:\批处理\mirai-robot/
 11:06:57 [INFO] [Mirai 0.5.2 Pkmon] Mirai-console now running under E:\批处理\
irai-robot
 11:06:57 [INFO] [Mirai 0.5.2 Pkmon] Get news in github: https://github.com/mam
e/mirai
 11:06:57 [INFO] [Mirai 0.5.2 Pkmon] Mirai为开源项目，请自觉遵守开源项目协议
 11:06:57 [INFO] [Mirai 0.5.2 Pkmon] Powered by Mamoe Technologies and contribu
ors
 11:06:57 [INFO] [Plugin Manager] 开始加载E:\批处理\mirai-robot/plugins/下的插件

 11:06:57 [INFO] [Plugin Manager] loading plugin MiraiAPIHTTP
 11:06:57 [INFO] [Plugin Manager] successfully loaded plugin MiraiAPIHTTP versi
n v1.7.3 by ryoii
 11:06:57 [INFO] [Plugin Manager] Mirai HTTP API Server Plugin
 11:06:57 [INFO] [MiraiAPIHTTP] Loading Mirai HTTP API plugin
 11:06:57 [INFO] [MiraiAPIHTTP] Trying to Start Mirai HTTP Server in 0.0.0.0:80
3
 11:06:57 [INFO] [MiraiAPIHTTP] Starting Mirai HTTP Server in 172.25.1.216:8063
2021-02-27 11:06:57 I/Mirai HTTP API: Http api server is running with authKey:
295267390
 11:06:57 [INFO] [MiraiAPIHTTP] 心跳模块启用状态: false
 11:06:57 [INFO] [MiraiAPIHTTP] 上报模块启用状态: false
 11:06:57 [INFO] [Plugin Manager] 加载了1个插件
 11:06:57 [INFO] [Mirai 0.5.2 Pkmon] Mirai-console 启动完成
 11:06:57 [INFO] [Mirai 0.5.2 Pkmon] "login qqnumber qqpassword " to login a bo

 11:06:57 [INFO] [Mirai 0.5.2 Pkmon] "login qq号 qq密码 " 来登录一个BOT

**Comment by Karlatemp** [comment]
版本过旧，记得删除device.json

**Comment by Andy-shi001** [comment]
如何更新，更新哪些？请告知一下，谢谢

**Comment by Him188** [comment]
重新阅读文档开头几个章节就能知道如何更新，注意由于你的版本过于旧（差 2 个主版本），更新时会有不兼容变更。

**Comment by Andy-shi001** [comment]
> 重新阅读文档开头几个章节就能知道如何更新，注意由于你的版本过于旧（差 2 个主版本），更新时会有不兼容变更。

更新哪些？请告知一下，谢谢
mirai-console-1.0-M3-1.jar  可以更新成2.4.0、2.4-RC、2.4-M1 版本吗？ 是需要自己下载源码，然后编译打包吗？
有编译好的jar包吗？
Mirai\miraiok_windows_386\plugins 文件目录下的mirai-api-http-v1.7.3.jar  是不需要更新的吧？

**Comment by Him188** [comment]
> > 重新阅读文档开头几个章节就能知道如何更新，注意由于你的版本过于旧（差 2 个主版本），更新时会有不兼容变更。
> 
> 更新哪些？请告知一下，谢谢
> mirai-console-1.0-M3-1.jar 可以更新成2.4.0、2.4-RC、2.4-M1 版本吗？ 是需要自己下载源码，然后编译打包吗？
> 有编译好的jar包吗？
> Mirai\miraiok_windows_386\plugins 文件目录下的mirai-api-http-v1.7.3.jar 是不需要更新的吧？

https://github.com/mamoe/mirai-console/blob/master/docs/Run.md#%E4%BD%BF%E7%94%A8%E5%B7%A5%E5%85%B7%E8%87%AA%E5%8A%A8%E7%8B%AC%E7%AB%8B%E5%90%AF%E5%8A%A8

**Comment by Andy-shi001** [comment]
> > > 重新阅读文档开头几个章节就能知道如何更新，注意由于你的版本过于旧（差 2 个主版本），更新时会有不兼容变更。
> > 
> > 
> > 更新哪些？请告知一下，谢谢
> > mirai-console-1.0-M3-1.jar 可以更新成2.4.0、2.4-RC、2.4-M1 版本吗？ 是需要自己下载源码，然后编译打包吗？
> > 有编译好的jar包吗？
> > Mirai\miraiok_windows_386\plugins 文件目录下的mirai-api-http-v1.7.3.jar 是不需要更新的吧？
> 
> https://github.com/mamoe/mirai-console/blob/master/docs/Run.md#%E4%BD%BF%E7%94%A8%E5%B7%A5%E5%85%B7%E8%87%AA%E5%8A%A8%E7%8B%AC%E7%AB%8B%E5%90%AF%E5%8A%A8

使用工具自动独立启动
独立启动 Mirai Console 作为一个应用程序，由 Console 扫描 plugins 目录加载插件。
官方: https://github.com/iTXTech/mirai-console-loader     **我之前用的不是这个，这个是写死一个QQ号的，不能命令进行**
第三方: https://github.com/LXY1226/MiraiOK                     **之前用的**

**可是下载不下来，老是访问不了，还有其他方式下载吗？**
我使用第三方MiraiOK  下载
Windows-386 | mirai-native用
Windows-amd64 | 不用native的话

提示信息：无法访问此网站t.imlxy.net 的响应时间过长。

**Comment by Andy-shi001** [comment]
> > > 重新阅读文档开头几个章节就能知道如何更新，注意由于你的版本过于旧（差 2 个主版本），更新时会有不兼容变更。
> > 
> > 
> > 更新哪些？请告知一下，谢谢
> > mirai-console-1.0-M3-1.jar 可以更新成2.4.0、2.4-RC、2.4-M1 版本吗？ 是需要自己下载源码，然后编译打包吗？
> > 有编译好的jar包吗？
> > Mirai\miraiok_windows_386\plugins 文件目录下的mirai-api-http-v1.7.3.jar 是不需要更新的吧？
> 
> https://github.com/mamoe/mirai-console/blob/master/docs/Run.md#%E4%BD%BF%E7%94%A8%E5%B7%A5%E5%85%B7%E8%87%AA%E5%8A%A8%E7%8B%AC%E7%AB%8B%E5%90%AF%E5%8A%A8

**请问一下**
**MiraiOK 的miraiOK_windows-386.exe这个方式，目前是停用了吗？  现在只能用/mirai-console-loader才可以是吗？**
