### ISSUE TITLE
关于 Mirai 第三方社区

### ISSUE THREAD

**Issue by sakurayun** [mamoe/mirai#1057]
亲爱的开发者您好，
      我是 Mirai 第三方社区的站长。
      Mirai 第三方社区的建设初衷仅为提供一个让用户和开发者沟通更加方便的交流平台，本社区与Mirai官方无任何关联，本社区发生的任何争议均与 Mirai 无关！
      非常抱歉因为我最初考虑不周，在没有征得您的同意的情况下擅自为您创建了社区账户并将您的作品搬运到了社区（如果您的 Github 主页有填写邮箱的话相信您一定收到了验证邮件）~ 
       最后 Mirai 第三方社区欢迎您的加入~
      

社区管理章程：https://mirai-bot.com/d/39-mirai
您的帖子：https://mirai-bot.com/d/40-mirai-qq-high-performance-bot-framework-for-tencent-qq
您的个人主页：https://mirai-bot.com/u/mirai

账户认领流程：
如果您收到过激活邮件，那您可以直接使用邮箱重置密码，若您未收到激活邮件、作品挂靠与Team、或者您的 Github 主页没有提供邮件地址，那么请您私信提交能证明您的Bot开发者身份的凭证！
（自动发送无需回复）

**Comment by purofle** [comment]
欢迎来到[mirai官方社区](https://mirai.mamoe.net/)

**Comment by Him188** [comment]
感谢你的帮助，但 mirai 昨日建立了官方社区

**Comment by sakurayun** [comment]
关于 Mirai 第三方社区
虽然我不清楚官方社区在本社区复出后第二天创建目的为何，不论官方态度如何，我都会选择把社区做下去。
本社区建设于CQ官网停运后的第二天。
用时两天遍历了所有与mirai相关的项目。
建站第四天，社区遭受不明Ddos攻击，流量损失约530G。
第四天下午遭受CC攻击。
随后因本人准备不够充分无法进行有效的防护，选择关站避风头并沉淀技术，优化社区体验。
...
于官方社区建站前一天，也就是正月十五选择重新开放社区。
为避免社区出现管理混乱等情况，特联系了任职公司的法务，由其代笔拟定了社区用户协议，社区管理制度等。
为保障开发者的创作归属及用户的正常使用，社区抛弃了之前数个月积攒的数据，选择从头开始，人工创建开发者账户，收集插件项目，并发送邮件及在开发者项目中开issues提醒尽快修改账户密码，并坚持插件发布贴是否有问题等。

本人创办社区不是为了盈利也不是为了名誉，仅仅为了提供一个供用户更加方便的寻找插件并使用插件的场所（某些开发者，WIKI都写不清楚），为开发者创造一个能够便捷的收到用户反馈的地方。

PS:
无论官方社区如何，官方对本社区态度如何，本社区都会坚持走下去，不为利不为名，只为我心中的执着。
既然我做了，那就要做到底，不求做到最好，但我将力求满足用户及开发者合理的需求。
社区地址: https://mirai-bot.com
