### ISSUE TITLE
在TIM加入一个新群，不会触发BotJoinGroupEvent，也不会收到新群的消息。

### ISSUE THREAD

**Issue by RrrrLin** [mamoe/mirai#1058]
查阅issues发现这个问题以前出现过，但是目前版本（2.4.0）又遇到了。
在Mirai正常登录的情况下，登录TIM添加一个新的群。新群设置的加群方式为管理员验证消息后加入。
加入新群后，Mirai没有触发BotJoinGroupEvent方法，也不能收到新群里的消息。
在重启Mirai程序后，可以正常收到新群的消息。

触发代码如下。
`@EventHandler
    public void joinNewGroup(BotJoinGroupEvent event) {
      //do something...
    }`
因为重启了miria，暂时没有当时的日志

#### 复现

1.正常登录mirai
2.通过TIM加入一个新群
3.问题出现

#### 版本
- mirai-core: `2.4.0`

**Comment by RrrrLin** [comment]
2.5-M2版本的新成员入群事件会触发BotJoinGroupEvent？
在成员成功加入群后，会意外触发BotJoinGroupEvent事件，入群同意操作非bot同意，bot为管理员。
另外 bot在通过正常回答问题加入一个群后，会触发两次BotJoinGroupEvent事件。

**Comment by KadokawaR** [comment]
在 2.7-M1 (从2.6开始便也已经遇到) bot入群之后 BotJoinGroupEvent 会被触发两次。
