### ISSUE TITLE
无法发送语音消息

### ISSUE THREAD

**Issue by 14Kay** [mamoe/mirai#1075]
mirai-api-http版本: v1.9.8
mirai-console-terminal版本: 2.5.0-dev-1
mirai-core-all版本: 2.5.0-dev-1
![image](https://user-images.githubusercontent.com/34759162/110077299-d83cfb00-7dc0-11eb-8feb-3fc77d385661.png)

**Comment by 14Kay** [comment]
> 请提供日志, 报错, 语音源文件

看了下，没有报错 就是上传语音后url 返回空
![image](https://user-images.githubusercontent.com/34759162/110080506-834fb380-7dc5-11eb-8723-83d48d37c4e2.png)

**Comment by Him188** [comment]
@ryoii

**Comment by Karlatemp** [comment]
请提供语音源文件，源文件

**Comment by 14kk** [comment]
> 请提供语音源文件，源文件

**Comment by 14Kay** [comment]
> 请提供语音源文件，源文件

[1614926218.zip](https://github.com/mamoe/mirai/files/6088873/1614926218.zip)

**Comment by 14Kay** [comment]
> 请提供语音源文件，源文件

.amr .mp3 都试过 都不行

**Comment by mzdluo123** [comment]
尝试减小文件大小，过大的文件可能会导致无法播放

**Comment by 14Kay** [comment]
> 尝试减小文件大小，过大的文件可能会导致无法播放

已尝试过减小大小，结果一样

**Comment by 14Kay** [comment]
之前在2.3.0版本的时候是正常的

**Comment by Karlatemp** [comment]
Same as #946

**Comment by Karlatemp** [comment]
```
[滤镜使用列表]
  (1) Built-in MP3 Source
  (2) Built-in Audio Codec/Transform
  (3) DirectSound Audio Renderer

[音频信息]
  音频编码： MPEG Audio Layer 3(0x55) - 内置 FFmpeg 解码器(mp3float)
  采样率： 44100 -> 44100 Hz
  位率： 0 -> 16 位
  声道数： 2 -> 2 声道
  Bitrate: 128 kbps


General
Complete name                  : F:\Temp\1614926218.mp3
Format                         : MPEG Audio
File size                      : 1 000 KiB
Duration                       : 4 min 57 s
Overall bit rate mode          : Constant
Overall bit rate               : 128 kb/s
Writing library                : Lavf57.83.100

Audio
Format                         : MPEG Audio
Format version                 : Version 1
Format profile                 : Layer 3
Format settings                : Joint stereo
Duration                       : 4 min 57 s
Bit rate mode                  : Constant
Bit rate                       : 128 kb/s
Channel(s)                     : 2 channels
Sampling rate                  : 44.1 kHz
Frame rate                     : 38.281 FPS (1152 SPF)
Compression mode               : Lossy
Stream size                    : 4.54 MiB
```

**Comment by 14Kay** [comment]
换回2.3.0 就可以正常发送了  2.3.0以后都不行
![image](https://user-images.githubusercontent.com/34759162/110266067-02c4c900-7ff8-11eb-88ba-1b0c8f4d7de8.png)

**Comment by sandtechnology** [comment]
你使用的是amr格式吗？应该是强制为silk格式上传导致的结果，revert掉这个commit应该就正常了

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by Him188** [comment]
@sandtechnology 经上面 @Karlatemp 分析他之前传的是 MP3 格式

**Comment by 14Kay** [comment]
> @sandtechnology 经上面 @Karlatemp 分析他之前传的是 MP3 格式

关键是MP3 它也行的呀

**Comment by sandtechnology** [comment]
不官方支持MP3格式 请自行转换

**Comment by 14Kay** [comment]
> 不官方支持MP3格式 请自行转换

上传的MP3 官方会转换的

![image](https://user-images.githubusercontent.com/34759162/110268948-90ef7e00-7ffd-11eb-8189-e53669467e19.png)
