### ISSUE TITLE
使用cglib动态代理生成Handlers时被@EventHandler标记的方法不会生效

### ISSUE THREAD

**Issue by MengYan89** [mamoe/mirai#1076]
使用JDK或cglib进行动态代理生成的对象在mirai中无法使用，推测是由于@EventHandler无法被继承所以导致mirai识别不到对应的方法。

**Comment by MengYan89** [comment]
补充版本mirai-core-jvm:2.3.2

**Comment by sandtechnology** [comment]
请提供无法使用时的错误日志 以及复现方式

**Comment by MengYan89** [comment]
> 请提供无法使用时的错误日志 以及复现方式

首先为我的结论进行道歉，让EventHandler变得可继承并不能解决这个问题。
以cglib为例
```
Enhancer enhancer = new Enhancer();  

enhancer.setSuperclass(TestHandlers.class);  

enhancer.setCallback(new HandlerProxy());  

TestHandlersImpl testHandlers2 = (TestHandlersImpl) enhancer.create();  
```
这样生成的代理类通过bot.getEventChannel().registerListenerHost()注册进bot后并不会生效
cglib的版本为3.2.7

**Comment by Karlatemp** [comment]
请问为什么要给监听器再套一层代理呢，感觉意义不大

**Comment by MengYan89** [comment]
> 请问为什么要给监听器再套一层代理呢，感觉意义不大

在二次开发时想要统一管理项目中的消息日志,虽然提供了LoggerAdapters.asMiraiLogger()将Log4j转换为MiraiLogeer与继承MiraiLoggerPlatformBase进行实现等方式，但由于其中提供的都是String在java环境下的表现差强人意,会直接使用对象的toString输出
2021-03-07 16:15:01.187 [DefaultDispatcher-worker-12] INFO  com.mengyan.mirai.listener.group.GroupMessageEventHandlers - [mirai:source:[555],[996753225]]3223
而不能去获取到更多Event中的信息。
这时想到了可以通过给监听器添加一层代理获取Event信息打印日志进行统一的管理,然后发现了这个问题。

**Comment by Karlatemp** [comment]
你可以另外注册新的监听器，继承原监听器我认为不是一个很好的设计

**Comment by MengYan89** [comment]
> 你可以另外注册新的监听器，继承原监听器我认为不是一个很好的设计
好的，明白了
