### ISSUE TITLE
对未支持的消息的解析实现不佳

### ISSUE THREAD

**Issue by sandtechnology** [mamoe/mirai#1081]
最近在做一个复读（直接重新发送发来的MessageChain）功能时遇见了一个问题：

对不支持的消息，mirai 只会在 `MessageChain` 内留下 `MessageSource`，导致消息重新发出时会报错 `Message is empty` ，导致发送失败，而直接用`isEmpty`方法判断是否为空也不行，因为还存在 `MessageSource`，所以并不是空的，希望开发者能解决此问题。

我目前的Workaround是手动实现一个方法来判断是否为空，然后再进行发送：
```
    public boolean isEmpty(MessageChain messageChain){
        return messageChain.contentEquals("",false);
    }
```

**Comment by Him188** [comment]
I suggest:

```kotlin
public interface UnsupportedMessage : MessageContent
```

```kotlin
internal class UnsupportedMessageImpl(
    val struct: Msg
) : UnsupportedMessage
```

在这基础上考虑:
- 序列化支持
- 实现 `toString`, `equals`

### 序列化
- `struct` 可以直接通过反射获取 `serializer` 来序列化, 但这会不会有将来不兼容性? 将协议内部数据暴露给用户有没有好处? (是否需要换用其他方式如以 hex string 保存(加一层 refine))

- 兼容性也可以这样: 反序列化这个内容失败就跳过这个消息. 但这就需要 refine 层才能处理

### toString
不能直接 `struct.toString()`, 而又没有办法获取到有关这个消息的用户可读的信息

@Karlatemp

**Comment by Karlatemp** [comment]
struct我个人认为使用Element更好而不是整个完整msg，序列化的话我认为应该套一层 hex string(或者 bytearray？) 避免其他序列化器的错误序列化，使用内部序列化基本不会出现兼容性错误？

toString我趋向于返回 Unsupported 或者直接空字符串
contentToString我趋向于直接空字符串

Message.isEmpty()的逻辑届时可能需要修改

**Comment by Him188** [comment]
toString 和 content 都可以返回 "[未支持的消息 #$hashcode]"

**Comment by Him188** [comment]
```kotlin
public interface UnsupportedMessage : MessageContent
```

```kotlin
internal data class UnsupportedMessageImpl(
    val struct: Elem
) : UnsupportedMessage

@Serializable
internal class UnsupportedMessageSerialized(
    val struct: String // Hex
) : RefinableMessage
```

- 反序列化内容失败就跳过这个消息
- `toString`: 返回 `"[未支持的消息 #$hashcode]"`
