### ISSUE TITLE
MemberJoinRequestEvent能接收到邀请进群信号，但是不能接受申请进群信号

### ISSUE THREAD

**Issue by a55509432** [mamoe/mirai#1085]
QQ群邀请权限已开，普通群员邀请好友，机器人能收到事件，用另外一个QQ搜索群号手动申请，机器人收不到任何事件。

```
Event: MemberJoinRequestEvent(bot=Bot(38xx), eventId=161527xxx, message=来自：群成员xbwnrz的邀请, fromId=17xx, groupId=87xx, groupName=凹凸世x, fromNick=裁判球1号, invitorId=1790xx7)
```

#### 版本
- mirai-core: `2.4.0`

**Comment by Karlatemp** [comment]
1.x 已经不在支持范围内，请参阅 https://github.com/mamoe/mirai/blob/dev/docs/MigrationFrom1x.md 并尝试 2.5-M2

**Comment by Karlatemp** [comment]
修改: 邮件原文显示为 1.x, 已经有相关issue

**Comment by a55509432** [comment]
> 修改: 邮件原文显示为 1.x, 已经有相关issue

你好，我一开始选错版本为1.x已经更改为实际使用的2.4.0,请问标记重复是跟哪一个issue重复了

**Comment by Karlatemp** [comment]
与 BotJoinRequest等 收不到属于同类问题，请尝试 2.5-M2 确认还有没有该问题



---原始邮件---
发件人: "python lda"<notifications@github.com&gt;
发送时间: 2021年3月9日(周二) 下午3:36
收件人: "mamoe/mirai"<mirai@noreply.github.com&gt;;
抄送: "State change"<state_change@noreply.github.com&gt;;"Karlatemp"<karlatemp@vip.qq.com&gt;;
主题: Re: [mamoe/mirai] MemberJoinRequestEvent能接收到邀请进群信号，但是不能接受申请进群信号 (#1085)




  
修改: 邮件原文显示为 1.x, 已经有相关issue
  
你好，我一开始选错版本为1.x已经更改为实际使用的2.4.0,请问标记重复是跟哪一个issue重复了

**Comment by a55509432** [comment]
> 与 BotJoinRequest等 收不到属于同类问题，请尝试 2.5-M2 确认还有没有该问题
> […](#)
> ---原始邮件--- 发件人: "python lda"<notifications@github.com&gt; 发送时间: 2021年3月9日(周二) 下午3:36 收件人: "mamoe/mirai"<mirai@noreply.github.com&gt;; 抄送: "State change"<state_change@noreply.github.com&gt;;"Karlatemp"<karlatemp@vip.qq.com&gt;; 主题: Re: [mamoe/mirai] MemberJoinRequestEvent能接收到邀请进群信号，但是不能接受申请进群信号 (#1085) 修改: 邮件原文显示为 1.x, 已经有相关issue 你好，我一开始选错版本为1.x已经更改为实际使用的2.4.0,请问标记重复是跟哪一个issue重复了 — You are receiving this because you modified the open/close state. Reply to this email directly, view it on GitHub, or unsubscribe.

我用kotlin1.4.31 运行2.5-M2同样的问题发生了，QQ群设置为邀请和申请都要审核，如果邀请能收到memberjoinrequest,但是搜索群号申请，电脑登录的QQ能收到申请，但是机器人没有收到memberjoinrequest事件

**Comment by Karlatemp** [comment]
提供网络日志，如为 mirai-console 则位于 logs 文件内



---原始邮件---
发件人: "python lda"<notifications@github.com&gt;
发送时间: 2021年3月10日(周三) 下午2:24
收件人: "mamoe/mirai"<mirai@noreply.github.com&gt;;
抄送: "State change"<state_change@noreply.github.com&gt;;"Karlatemp"<karlatemp@vip.qq.com&gt;;
主题: Re: [mamoe/mirai] MemberJoinRequestEvent能接收到邀请进群信号，但是不能接受申请进群信号 (#1085)




  
与 BotJoinRequest等 收不到属于同类问题，请尝试 2.5-M2 确认还有没有该问题
 …
 ---原始邮件--- 发件人: "python lda"<notifications@github.com&gt; 发送时间: 2021年3月9日(周二) 下午3:36 收件人: "mamoe/mirai"<mirai@noreply.github.com&gt;; 抄送: "State change"<state_change@noreply.github.com&gt;;"Karlatemp"<karlatemp@vip.qq.com&gt;; 主题: Re: [mamoe/mirai] MemberJoinRequestEvent能接收到邀请进群信号，但是不能接受申请进群信号 (#1085) 修改: 邮件原文显示为 1.x, 已经有相关issue 你好，我一开始选错版本为1.x已经更改为实际使用的2.4.0,请问标记重复是跟哪一个issue重复了 — You are receiving this because you modified the open/close state. Reply to this email directly, view it on GitHub, or unsubscribe.
  
我用kotlin1.4.31 运行2.5-M2同样的问题发生了，QQ群设置为邀请和申请都要审核，如果邀请能收到memberjoinrequest,但是搜索群号申请，电脑登录的QQ能收到申请，但是机器人没有收到memberjoinrequest事件

**Comment by a55509432** [comment]
> 提供网络日志，如为 mirai-console 则位于 logs 文件内
> […](#)
> ---原始邮件--- 发件人: "python lda"<notifications@github.com&gt; 发送时间: 2021年3月10日(周三) 下午2:24 收件人: "mamoe/mirai"<mirai@noreply.github.com&gt;; 抄送: "State change"<state_change@noreply.github.com&gt;;"Karlatemp"<karlatemp@vip.qq.com&gt;; 主题: Re: [mamoe/mirai] MemberJoinRequestEvent能接收到邀请进群信号，但是不能接受申请进群信号 (#1085) 与 BotJoinRequest等 收不到属于同类问题，请尝试 2.5-M2 确认还有没有该问题 … ---原始邮件--- 发件人: "python lda"<notifications@github.com&gt; 发送时间: 2021年3月9日(周二) 下午3:36 收件人: "mamoe/mirai"<mirai@noreply.github.com&gt;; 抄送: "State change"<state_change@noreply.github.com&gt;;"Karlatemp"<karlatemp@vip.qq.com&gt;; 主题: Re: [mamoe/mirai] MemberJoinRequestEvent能接收到邀请进群信号，但是不能接受申请进群信号 (#1085) 修改: 邮件原文显示为 1.x, 已经有相关issue 你好，我一开始选错版本为1.x已经更改为实际使用的2.4.0,请问标记重复是跟哪一个issue重复了 — You are receiving this because you modified the open/close state. Reply to this email directly, view it on GitHub, or unsubscribe. 我用kotlin1.4.31 运行2.5-M2同样的问题发生了，QQ群设置为邀请和申请都要审核，如果邀请能收到memberjoinrequest,但是搜索群号申请，电脑登录的QQ能收到申请，但是机器人没有收到memberjoinrequest事件 — You are receiving this because you modified the open/close state. Reply to this email directly, view it on GitHub, or unsubscribe.

2021-03-10 14:15:46 I/main: Starting mirai-console...
2021-03-10 14:15:46 I/main: Backend: version 2.5-M2, built on 2021-03-09 09:15:58.
2021-03-10 14:15:46 I/main: Frontend Terminal: version 2.5-M2, provided by Mamoe Technologies
2021-03-10 14:15:46 I/main: Prepared built-in commands: autoLogin, help, login, permission, status, stop
2021-03-10 14:15:46 I/main: 0 plugin(s) enabled.
2021-03-10 14:15:46 I/main: mirai-console started successfully.
2021-03-10 14:15:46 I/ExamplePlugin: Plugin loaded
2021-03-10 14:15:46 I/Mirai: Mirai ����ʹ�����滷��. ��������֤�뽫�ᵯ���Ի���. ����� JVM ���� `mirai.no-desktop` �Թر�.
2021-03-10 14:15:46 I/Mirai: Mirai is using desktop. Captcha will be thrown by window popup. You can add `mirai.no-desktop` to JVM properties (-Dmirai.no-desktop) to disable it.
2021-03-10 14:15:47 I/Bot.2447478442: Logging in...
2021-03-10 14:15:48 I/Bot.2447478442: Online OtherClients: GIH-D-13115(WINDOWS)
2021-03-10 14:15:50 I/Bot.2447478442: Login successful
2021-03-10 14:15:51 I/Bot.2447478442: Server list: 157.148.36.215:14000, 153.3.50.239:14000, 157.255.13.124:8080, 221.198.69.96:80, 153.3.149.175:14000, 157.148.34.63:443, 60.28.172.94:80, 153.3.50.20:80, msfwifi.3g.qq.com:8080, 61.181.203.29:80.
2021-03-10 14:17:48 V/Bot.2447478442: Event: MemberJoinEvent.Active(member=76617138)

这个MemberJoinEvent是电脑手动同意了，机器人没有收到request事件
