### ISSUE TITLE
优化 Message 文档

### ISSUE THREAD

**Issue by Him188** [mamoe/mirai#1088]
添加 Java 相关 reference

Java 没有扩展函数（方法），目前各种方法 Kotlin 不难找到，但对于刚刚接触 mirai 的 Java 使用者有一定难度。

**Comment by Him188** [comment]
应该要添加一些示例用法，最直接解决

**Comment by Nambers** [comment]
欸 有没有试过用manifold项目去在java内扩展，如这篇博文 <https://blog.csdn.net/diluan6799/article/details/106826927>，manifold是github的一个开源库 <https://github.com/manifold-systems/manifold>

**Comment by Him188** [comment]
> 欸 有没有试过用manifold项目去在java内扩展，如这篇博文 https://blog.csdn.net/diluan6799/article/details/106826927，manifold是github的一个开源库 https://github.com/manifold-systems/manifold

没有，让使用者再去学习这个库是不太好的

我们应该首先保证简单易用，再可以考虑额外支持

**Comment by Nambers** [comment]
> > 欸 有没有试过用manifold项目去在java内扩展，如这篇博文 [https://blog.csdn.net/diluan6799/article/details/106826927，manifold是github的一个开源库](https://blog.csdn.net/diluan6799/article/details/106826927%EF%BC%8Cmanifold%E6%98%AFgithub%E7%9A%84%E4%B8%80%E4%B8%AA%E5%BC%80%E6%BA%90%E5%BA%93) https://github.com/manifold-systems/manifold
> 
> 没有，让使用者再去学习这个库是不太好的

看起来并不需要使用者学习？只需要用就好了？
上面链接好像掉了，补一下
https://blog.csdn.net/diluan6799/article/details/106826927

**Comment by Him188** [comment]
> 欸 有没有试过用manifold项目去在java内扩展，如这篇博文 https://blog.csdn.net/diluan6799/article/details/106826927，manifold是github的一个开源库 https://github.com/manifold-systems/manifold

那这个确实不错，有空会去看看

**Comment by Him188** [comment]
https://github.com/mamoe/mirai/discussions/848#discussioncomment-523632
