### ISSUE TITLE
新成员入群事件会触发三次（使用了Mirai-Native）

### ISSUE THREAD

**Issue by jiajiaxd** [mamoe/mirai#1090]
**描述这个Bug**
新成员入群事件会被触发三次

**复现步骤**
添加新成员进入群聊
**期望的行为**
使新成员入群只被触发一次

**截图和日志**
![image](https://user-images.githubusercontent.com/51043917/110654710-59e5bc00-81f9-11eb-86e0-ed48e5988d61.png)
![image](https://user-images.githubusercontent.com/51043917/110654762-636f2400-81f9-11eb-8237-54cb0c2894e8.png)

**运行环境**
 - 操作系统：Windows Server 2019
 - `mirai core` 版本：2.5.0-dev-1
 - `mirai console` 版本：2.4.0
 - `mirai native` 版本：2.0.0-beta.1
 - `Java` 运行时版本：OpenJDK Runtime Environment AdoptOpenJDK (build 15.0.2+7) x86

**更多信息**
无

**Comment by Karlatemp** [comment]
For mamoe: bot同意入群时有主动广播MemberJoinEvent的代码，没计入日志

**Comment by Him188** [comment]
@Karlatemp 如果有办法修复就修复, 没有办法就推 Backlog
