### ISSUE TITLE
ForwardMessage 聊天记录时间错误

### ISSUE THREAD

**Issue by Nambers** [mamoe/mirai#1097]
在buildforwardmessage时把time也就是时间戳设置成-1和-100分别得到了`2106/2/7 14:28:15`和`2106/2/7 14:26:36`，理论上如果是时间戳的话应该是1970之前，而我把time传入1也得到了`1970/1/1 8:00:01`

构造代码

```
        val a = ForwardMessageBuilder(c)
        t.content.value.forEach {
            a.add(ForwardMessage.Node(it.id, it.time, it.name, MiraiCode.deserializeMiraiCode(it.message)))
        }
        a.build().sendTo(c1)
```

#### 版本
- mirai-core: `2.4.0`

**Comment by Yun-Shan** [comment]
应该是正常的，看起来tx处理时间用的是unsigned int
```kotlin
print((-1).toUInt()) // 4294967295
```
而4294967295的unix时间戳即为`2106/2/7 14:28:15`

**Comment by Nambers** [comment]
> 应该是正常的，看起来tx处理时间用的是unsigned int
> 
> ```kotlin
> print((-1).toUInt()) // 4294967295
> ```
> 
> 而4294967295的unix时间戳即为`2106/2/7 14:28:15`

 那也是
