### ISSUE TITLE
自己用机器人账号回复消息也会触发自动回复

### ISSUE THREAD

**Issue by infooer** [mamoe/mirai#1106]
bot.globalEventChannel().subscribeAlways(MessageEvent::class) {
        when (subject) {
            is Friend -> {
                when {
                        Regex(".*你好.*).matches(message.contentToString()) ->
                            subject.sendMessage("您好！欢迎光临")
                }
            }
         }
     }

好友发送：“你好”，机器人会正常回复"您好！欢迎光临"；
我自己用机器人账号跟别人聊天发送：“你好”，也会触发机器人自动回复："您好！欢迎光临"，导致发两遍消息。
请问这个是什么原因呢？

**Comment by sandtechnology** [comment]
因为存在同步其他客户端的消息事件 详情可见MessageSyncEvent

**Comment by Him188** [comment]
这是正常情况, 机器人账号在其他客户端发送消息会触发 `MessageSyncEvent`, 可以手动排除
