### ISSUE TITLE
MemberJoinRequestEvent 中, message 字段的相关问题

### ISSUE THREAD

**Issue by GreyElaina** [mamoe/mirai#1108]
我发现当一第三方账号向机器人管理的群组申请入群, 填写了入群问题的答案(答案不为空), 且该群组入群方式为: "需要回答问题并由管理员进行审核"时, mirai 获取到的 MemberJoinRequestEvent 中, message 字段出现了 "问题：<入群问题>\n答案：<答案>" 这样的, 而我希望能直接返回答案.

```
2021-03-20 23:22:29 I/stdout: {"type":"MemberJoinRequestEvent","eventId": <eventId>,"message":"问题：<入群问题>\n答案：<答案>","fromId":<fromId>,"groupId": <groupId>,"groupName":"<groupId>","nick":"<nickname>"}
```

我修改了 mirai-api-http, 使其可以打印出监听到的所有事件.

#### 复现
在 PCQQ 不在线时(事实证明这会让 mirai 获取不到事件, 可能需要另外提一个 ISSUE), 一第三方账号向机器人管理的群组申请入群, 填写了入群问题的答案(答案不为空), 且该群组入群方式为: "需要回答问题并由管理员进行审核".

#### 版本

- mirai-core: `2.4.0`
- mirai-console-terminal: `2.4.0`
- mirai-api-http: `1.9.8`, 做了一些修复与修改.

#### 补充信息

我修改了 `mirai-api-http`, 修复了关于获取 Friend 时, nickname 字段为空字符串的问题.

**Comment by GreyElaina** [comment]
mirai 可否通过获取群组的入群方式, 进行内部的一些处理, 进而做出更 friendly 的接口?

**Comment by Him188** [comment]
这个 `message` 是服务器提供的, 由于服务器随时可能更新, mirai 无法提供解析

**Comment by Him188** [comment]
群员入群时 `MemberJoinEvent` 有 `Invite`, `Active`, `Retrieve` 三种入群方式已经提供
