### ISSUE TITLE
getGroupMemberList 获取群成员列表 无法获取最新的群成员信息

### ISSUE THREAD

**Issue by ljnForLove1314** [mamoe/mirai#1114]
![image](https://user-images.githubusercontent.com/29368775/112594787-66e2ec00-8e44-11eb-98fd-0f55d50d82dc.png)

**官方文档里说有缓存，但是我现在已经设置为false了，获取的群成员信息还是旧的，已退群的用户仍然在返回的信息里，有解决的办法吗？**

**Comment by sandtechnology** [comment]
1.你使用的框架是？
2.mirai自身存在缓存功能，需要单独设置，请提供启动机器人的代码或者配置

**Comment by Karlatemp** [comment]
mirai-api-http / mirai-core 均无此字眼，你应该发错仓库了

**Comment by ForteScarlet** [comment]
抱歉，是我这边的。他应该参考一下 [simpler-robot #84](https://github.com/ForteScarlet/simpler-robot/issues/84)

给这边造成困扰很抱歉😔。
