### ISSUE TITLE
其他管理员同意他人加入群会时，会触发bot入群的事件

### ISSUE THREAD

**Issue by RrrrLin** [mamoe/mirai#1120]
其他管理员同意成员入群MemberJoinEvent时，机器人会同时触发BotJoinGroupEvent的事件。

#### 复现

新成员被其他管理员同意申请，加入一个机器人存在的群，机器人存在管理权限。
机器人 触发BotJoinGroupEvent事件

#### 版本
- mirai-core: `2.5.0`

**Comment by Karlatemp** [comment]
请提供对应时间段网络日志
