### ISSUE TITLE
希望能够提供更加方便的群公告接口

### ISSUE THREAD

**Issue by sonder-joker** [mamoe/mirai#1138]
目前的群公告相关的接口都属于lowlevel接口，我希望能够提供更加方便的接口来对群公告进行操作，同时想提供发送含有图片的群公告的接口。
我该如何提升lowlevel的接口？

我大致阅读后认为这些接口可以在[GroupImpl.kt](https://github.com/mamoe/mirai/blob/dev/mirai-core/src/commonMain/kotlin/contact/GroupImpl.kt)中实现
如果不应该在这里实现，应该在何处实现？
如果可以，有什么需要注意的地方？

**Comment by Him188** [comment]
#140
