### ISSUE TITLE
发消息的时候出现了CancellationException: network is dead therefore can't send any packet

### ISSUE THREAD

**Issue by ljnForLove1314** [mamoe/mirai#1139]
![image](https://user-images.githubusercontent.com/29368775/113267414-e838f380-9308-11eb-889a-3c05ec4bc78c.png)

**Comment by Him188** [comment]
这个是一个巧合, 在正在重连的时候调用了发消息. 

这个概率较低, 目前无法完全解决它, 会在 2.6 改善

**Comment by Him188** [comment]
在 2.6 之后这个出现的概率就会非常低了
