### ISSUE TITLE
登录几分钟后掉线重连后无法正常处理消息

### ISSUE THREAD

**Issue by zhzRedstone** [mamoe/mirai#117]
root@localhost/ $java -jar mirai-console-wrapper-0.1.1.jar
You are running Mirai-Console-Wrapper under /home/app/qqbot
Starting Mirai Console Pure, reset by clear /content/
Starting version check...
Fetching Newest Core Version ..
Fetching Newest Console Version of Pure
Local Console-Pure Version: 0.3.2 | Newest Console-Pure Version: 0.3.2
Local Core Version: 0.25.0 | Newest Core Version: 0.25.0
Version check complete, starting Mirai
Core    :/home/app/qqbot/content/mirai-core-jvm-0.25.0.jar
Protocol:/home/app/qqbot/content/mirai-core-qqandroid-jvm-0.25.0.jar
Console :/home/app/qqbot/content/mirai-console-0.3.2.jar
Root    :/home/app/qqbot/
[Mirai 0.3.2 Pkmon]: Mirai-console now running under /home/app/qqbot
[Mirai 0.3.2 Pkmon]: Get news in github: https://github.com/mamoe/mirai
[Mirai 0.3.2 Pkmon]: Mirai为开源项目，请自觉遵守开源项目协议
[Mirai 0.3.2 Pkmon]: Powered by Mamoe Technologies and contributors
[Plugin Manager]: 开始加载/home/app/qqbot/plugins/下的插件
[Plugin Manager]: 加载了0个插件
[Mirai 0.3.2 Pkmon]: Mirai-console 启动完成
[Mirai 0.3.2 Pkmon]: "/login qqnumber qqpassword " to login a bot
[Mirai 0.3.2 Pkmon]: "/login qq号 qq密码 " 来登录一个BOT
login account password
[Bot Login]: login...
[BOT 3173857429]: Logging in...
[BOT 3173857429]: Initializing BotNetworkHandler
[NETWORK]: Connected to server 113.96.13.208:8080
[NETWORK]: Send done: wtlogin.login
[NETWORK]: Received: WtLogin.Login.LoginPacketResponse.DeviceLockLogin
[NETWORK]: Send done: wtlogin.login
[NETWORK]: Received: LoginPacketResponse.Success
[NETWORK]: Login successful
[NETWORK]: Send done: StatSvc.register
[NETWORK]: Received: Response(StatSvc.register)
[NETWORK]: 开始加载群组列表与群成员列表
[NETWORK]: 开始加载好友信息
[NETWORK]: Send done: friendlist.GetTroopListReqV2
[NETWORK]: Send done: friendlist.getFriendGroupList
[NETWORK]: Received: FriendList.GetFriendGroupList.Response
[NETWORK]: 正在加载好友列表 6/6
[NETWORK]: 好友列表加载完成, 共 6个
[NETWORK]: Received: FriendList.GetFriendGroupList.Response
[NETWORK]: 群组列表与群成员加载完成, 共 8个
[NETWORK]: Send done: OidbSvc.0x88d_7
[NETWORK]: Send done: OidbSvc.0x88d_7
[NETWORK]: Send done: OidbSvc.0x88d_7
[NETWORK]: Send done: OidbSvc.0x88d_7
[NETWORK]: Send done: OidbSvc.0x88d_7
[NETWORK]: Send done: OidbSvc.0x88d_7
[NETWORK]: Send done: OidbSvc.0x88d_7
[NETWORK]: Send done: OidbSvc.0x88d_7
[NETWORK]: Received: GroupInfoImpl(delegate=net.mamoe.mirai.qqandroid.network.protocol.data.proto.Oidb0x88d$GroupInfo@58e9134)
[NETWORK]: Send done: friendlist.GetTroopMemberListReq
[NETWORK]: Received: GroupInfoImpl(delegate=net.mamoe.mirai.qqandroid.network.protocol.data.proto.Oidb0x88d$GroupInfo@62f4ae41)
[NETWORK]: Send done: friendlist.GetTroopMemberListReq
[NETWORK]: Received: GroupInfoImpl(delegate=net.mamoe.mirai.qqandroid.network.protocol.data.proto.Oidb0x88d$GroupInfo@5b34dbc2)
[NETWORK]: Received: GroupInfoImpl(delegate=net.mamoe.mirai.qqandroid.network.protocol.data.proto.Oidb0x88d$GroupInfo@11205021)
[NETWORK]: Send done: friendlist.GetTroopMemberListReq
[NETWORK]: Received: GroupInfoImpl(delegate=net.mamoe.mirai.qqandroid.network.protocol.data.proto.Oidb0x88d$GroupInfo@185d7f3)
[NETWORK]: Send done: friendlist.GetTroopMemberListReq
[NETWORK]: Received: GroupInfoImpl(delegate=net.mamoe.mirai.qqandroid.network.protocol.data.proto.Oidb0x88d$GroupInfo@2cec2fc)
[NETWORK]: Send done: friendlist.GetTroopMemberListReq
[NETWORK]: Received: GroupInfoImpl(delegate=net.mamoe.mirai.qqandroid.network.protocol.data.proto.Oidb0x88d$GroupInfo@2c61e905)
[NETWORK]: Send done: friendlist.GetTroopMemberListReq
[NETWORK]: Received: GroupInfoImpl(delegate=net.mamoe.mirai.qqandroid.network.protocol.data.proto.Oidb0x88d$GroupInfo@3f5305f0)
[NETWORK]: Send done: friendlist.GetTroopMemberListReq
[NETWORK]: Send done: friendlist.GetTroopMemberListReq
[NETWORK]: Received: FriendList.GetTroopMemberList.Response
[NETWORK]: Received: FriendList.GetTroopMemberList.Response
[NETWORK]: Send done: friendlist.GetTroopMemberListReq
[NETWORK]: Received: FriendList.GetTroopMemberList.Response
[NETWORK]: Send done: friendlist.GetTroopMemberListReq
[NETWORK]: Received: FriendList.GetTroopMemberList.Response
[NETWORK]: Received: FriendList.GetTroopMemberList.Response
[NETWORK]: Received: FriendList.GetTroopMemberList.Response
[NETWORK]: Received: FriendList.GetTroopMemberList.Response
[NETWORK]: Received: FriendList.GetTroopMemberList.Response
[NETWORK]: Send done: friendlist.GetTroopMemberListReq
[NETWORK]: Received: FriendList.GetTroopMemberList.Response
[NETWORK]: Received: FriendList.GetTroopMemberList.Response
[NETWORK]: Received: FriendList.GetTroopMemberList.Response
[NETWORK]: Send: MessageSvc.PbGetMsg
[NETWORK]: Received: MessageSvc.PbGetMsg.GetMsgSuccess(messages=<Iterable>))
[BOT 3173857429]: Login successful
[Command]: 3173857429 login successes
[NETWORK]: Received: PushReq(type=1, jcebuf=[一大堆数组], seq=1018944115)
[NETWORK]: Send: ConfigPushSvc.PushResp
[NETWORK]: Received commandName: ConfigPushSvc.PushDomain
[NETWORK]: Received: PushReq(type=2, jcebuf=[一大堆数组], seq=1018944519)
[NETWORK]: Send: ConfigPushSvc.PushResp
[BOT 3173857429]: Received: GroupMessage(group=330986863, senderName=炸毛, sender=623722580, permission=MEMBER, message=咖啡内种苦和药粉一样)
[BOT 3173857429]: Received: GroupMessage(group=330986863, senderName=zhzhongshi, sender=3365615175, permission=MEMBER, message=...)
[BOT 3173857429]: Received: GroupMessage(group=330986863, senderName=‮~喵‭ÿ轻雨, sender=1701717336, permission=MEMBER, message=怎么啦qwq)
......
以上正常log
[BOT 3173857429]: Received: GroupMessage(group=330986863, senderName=啊→啊↗ 啊↘↗啊↘君は, sender=515580323, permission=MEMBER, message=你们有没有老王加速器啊啊啊啊啊啊啊啊啊啊啊)
[BOT 3173857429]: Received: GroupMessage(group=330986863, senderName=\n\n\&ÿÇý\nしょうよう, sender=2821430542, permission=ADMINISTRATOR, message=..)
[BOT 3173857429]: Connection dropped by server or lost, retrying login
[NETWORK]: Send done: StatSvc.register
[NETWORK]: Cannot do fast relogin. Trying slow relogin
[NETWORK]: Connected to server 113.96.13.208:8080

**Comment by zhzRedstone** [comment]
当我结束进程时有如下报错
[Command]: 未知指令 /                                                                                                                                                                           ^C[BOT 3173857429]: An exception was thrown under a coroutine of Bot
[NETWORK ERROR]: java.lang.IllegalArgumentException: Self-suppression not permitted
java.lang.IllegalArgumentException: Self-suppression not permitted
        at java.lang.Throwable.addSuppressed(Throwable.java:1072)
        at net.mamoe.mirai.BotImpl$offlineListener$1.invokeSuspend(BotImpl.kt:207)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:55)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:561)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:727)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:667)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:655)
Caused by: kotlinx.coroutines.JobCancellationException: Job was cancelled; job=SupervisorJobImpl{Cancelling}@49514575

**Comment by Him188** [comment]
问题原因与 #115  相同, 将在下一个版本修复
