### ISSUE TITLE
希望能支持接受群主授予群成员头衔的事件

### ISSUE THREAD

**Issue by xszqxszq** [mamoe/mirai#1173]
目前（mirai: 2.6-M2）群主修改群成员头衔后日志如下：
```
2021-04-07 20:09:59 D/Net ********: Unknown server messages 恭喜<{"cmd":5,"data":"QQ号","text":"QQ昵称"}>获得群主授予的<{"cmd":1,"data":"https://qun.qq.com/qqweb/m/qun/medal/detail.html?_wv=16777223&bid=2504&gc=QQ群号&isnew=1&medal=302&uin=QQ号","text":"变更后头衔","url":"https://qun.qq.com/qqweb/m/qun/medal/detail.html?_wv=16777223&bid=2504&gc=QQ群号&isnew=1&medal=302&uin=QQ号"}>头衔
```

**Comment by sandtechnology** [comment]
能否提供相关的网络日志以及有关的debug信息？

**Comment by xszqxszq** [comment]
> 能否提供相关的网络日志以及有关的debug信息？

上面的就是控制台输出的唯一亮蓝色debug信息

**Comment by sonder-joker** [comment]
> > 能否提供相关的网络日志以及有关的debug信息？
> 
> 上面的就是控制台输出的唯一亮蓝色debug信息

在bots/qq号/logs文件夹下有相应的网络日志

**Comment by xszqxszq** [comment]
> > > 能否提供相关的网络日志以及有关的debug信息？
> > 
> > 
> > 上面的就是控制台输出的唯一亮蓝色debug信息
> 
> 在bots/qq号/logs文件夹下有相应的网络日志

请问这个文件夹在哪里，我直接使用的`mirai-core`，没有使用`mirai-console`

**Comment by xszqxszq** [comment]
> > > 能否提供相关的网络日志以及有关的debug信息？
> > 
> > 
> > 上面的就是控制台输出的唯一亮蓝色debug信息
> 
> 在bots/qq号/logs文件夹下有相应的网络日志

顺便请教一下上面的是否是网络日志，如果不是那应该称之为什么比较准确

**Comment by xszqxszq** [comment]
> > > 能否提供相关的网络日志以及有关的debug信息？
> > 
> > 
> > 上面的就是控制台输出的唯一亮蓝色debug信息
> 
> 在bots/qq号/logs文件夹下有相应的网络日志

经过阅读`BotConfiguration.kt`已基本了解网络日志，应该是包含“Net”前缀的日志。但其他对于本项目不熟悉的人很可能会一头雾水，建议在issue模板中添加对于网络日志特征的描述，这样给双方都能带来方便。

**Comment by xszqxszq** [comment]
> 能否提供相关的网络日志以及有关的debug信息？

```
2021-04-12 20:49:28 D/Net *******: Unknown server messages 恭喜<{"cmd":5,"data":"被授予者QQ号*******","text":"被授予者QQ昵称"}>获得群主授予的<{"cmd":1,"data":"https://qun.qq.com/qqweb/m/qun/medal/detail.html?_wv=16777223&bid=2504&gc=群号*******&isnew=1&medal=302&uin=被授予者QQ号*******","text":"头衔名称","url":"https://qun.qq.com/qqweb/m/qun/medal/detail.html?_wv=16777223&bid=2504&gc=群号*******&isnew=1&medal=302&uin=被授予者QQ号*******"}>头衔
2021-04-12 20:49:28 V/Net *******: Send: OnlinePush.RespPush
```

**Comment by sandtechnology** [comment]
> 
> 
> > > > 能否提供相关的网络日志以及有关的debug信息？
> > > 
> > > 
> > > 上面的就是控制台输出的唯一亮蓝色debug信息
> > 
> > 
> > 在bots/qq号/logs文件夹下有相应的网络日志
> 
> 经过阅读`BotConfiguration.kt`已基本了解网络日志，应该是包含“Net”前缀的日志。但其他对于本项目不熟悉的人很可能会一头雾水，建议在issue模板中添加对于网络日志特征的描述，这样给双方都能带来方便。

确实 我会提交到https://github.com/mamoe/mirai/discussions/848

**Comment by sandtechnology** [comment]
> 
> 
> > 能否提供相关的网络日志以及有关的debug信息？
> 
> ```
> 2021-04-12 20:49:28 D/Net *******: Unknown server messages 恭喜<{"cmd":5,"data":"被授予者QQ号*******","text":"被授予者QQ昵称"}>获得群主授予的<{"cmd":1,"data":"https://qun.qq.com/qqweb/m/qun/medal/detail.html?_wv=16777223&bid=2504&gc=群号*******&isnew=1&medal=302&uin=被授予者QQ号*******","text":"头衔名称","url":"https://qun.qq.com/qqweb/m/qun/medal/detail.html?_wv=16777223&bid=2504&gc=群号*******&isnew=1&medal=302&uin=被授予者QQ号*******"}>头衔
> 2021-04-12 20:49:28 V/Net *******: Send: OnlinePush.RespPush
> ```

往上没有其他内容了？ 那看样子我得自己看看有没有其他消息了 可能被忽略了

**Comment by xszqxszq** [comment]
> > > 能否提供相关的网络日志以及有关的debug信息？
> > 
> > 
> > ```
> > 2021-04-12 20:49:28 D/Net *******: Unknown server messages 恭喜<{"cmd":5,"data":"被授予者QQ号*******","text":"被授予者QQ昵称"}>获得群主授予的<{"cmd":1,"data":"https://qun.qq.com/qqweb/m/qun/medal/detail.html?_wv=16777223&bid=2504&gc=群号*******&isnew=1&medal=302&uin=被授予者QQ号*******","text":"头衔名称","url":"https://qun.qq.com/qqweb/m/qun/medal/detail.html?_wv=16777223&bid=2504&gc=群号*******&isnew=1&medal=302&uin=被授予者QQ号*******"}>头衔
> > 2021-04-12 20:49:28 V/Net *******: Send: OnlinePush.RespPush
> > ```
> 
> 往上没有其他内容了？ 那看样子我得自己看看有没有其他消息了 可能被忽略了

没有了，就这两条
