### ISSUE TITLE
开启群全体禁言后部分设备没有显示全体禁言开启，仍然可以发言

### ISSUE THREAD

**Issue by Keyezi** [mamoe/mirai#1181]
```kotlin
    val group = bot.getGroup(1018524314)
    if (group != null) {
        group.settings.isMuteAll = true
    }
```

1、运行如上代码，仅部分设备有显示全体禁言开启，但是退出去重进后依旧可以发言
![image](https://user-images.githubusercontent.com/38462592/114161679-f0251300-995a-11eb-8e86-3e461cd6082e.png)
![image](https://user-images.githubusercontent.com/38462592/114161740-00d58900-995b-11eb-9b26-17ad86a5903d.png)

2、禁言后，部分设备没有显示全体禁言开启，依旧可以发言
其他设备可以通过+1 模块等方式强行发言（退出客户端重进也可）
![image](https://user-images.githubusercontent.com/38462592/114162379-a12bad80-995b-11eb-9355-eeae717b04c8.png)

3、对比
我使用官方客户端测试后，发现并未出现如上禁言无效的情况

![image](https://user-images.githubusercontent.com/38462592/114162267-8822fc80-995b-11eb-8ffe-33ac73ebe2ec.png)

#### 版本
- mirai-core: 2.6-M2

**Comment by yzqd9527** [comment]
苹果设备具体表现为 刚看到bot开启禁言时有禁言效果 返回再点进群聊 禁言状态就无了（关于看不到管理员开启禁言那行字是苹果的问题 可以忽略）

**Comment by Keyezi** [comment]
补充个视频


https://user-images.githubusercontent.com/38462592/114165878-9ecb5280-995f-11eb-810d-c3f0f905ecc6.mp4

**Comment by YmggDEV** [comment]
他人重发

**Comment by yzqd9527** [comment]
群员视角录屏

https://user-images.githubusercontent.com/67503218/114168216-890b5c80-9962-11eb-9e7d-9c5253771af6.mp4

**Comment by yzqd9527** [comment]
> 群员视角录屏
> 
>  2021-04-09_18-31-15.mp4

禁言后发送的消息由ios客户端发出
