### ISSUE TITLE
支持嵌套的合并转发

### ISSUE THREAD

**Issue by mengpp-0001** [mamoe/mirai#1183]
嵌套的转发消息获取不到内容

![QQ截图20210411125159](https://user-images.githubusercontent.com/56571510/114292937-bcfe9300-9ac4-11eb-9384-800d9ec78d20.png)
![image](https://user-images.githubusercontent.com/56571510/114292963-eddec800-9ac4-11eb-96e1-726d370c0055.png)

**Comment by mengpp-0001** [comment]
@Him188 这个问题会在短时间内解决吗

**Comment by Him188** [comment]
@mengpp-0001 不一定，有影响到一些重要功能吗，比如说？

**Comment by mengpp-0001** [comment]
整个程序核心就一个功能
功能：获取转发里的全部内容，按顺序生成PDF文件后存档。

**Comment by mengpp-0001** [comment]
@Him188 要写的程序就一个功能，获取转发里的全部内容，生成PDF文件。

**Comment by mengpp-0001** [comment]
@Him188 这个功能是，获取转发消息里的全部内容，然后生成PDF文件
