### ISSUE TITLE
支持获取离线消息

### ISSUE THREAD

**Issue by Him188** [mamoe/mirai#1184]
`MessageSvc.PbGetMsg` (差不多)

可能可以通过 id 获取到历史消息内容, 这样可以获取撤回事件里的原消息内容而不需要缓存. 可能也会帮助 HTTP 插件

**Comment by zhaodice** [comment]
我印象里没记错的话，撤回消息，TX那边也会屏蔽掉对应的离线消息，也就是说客户端根本收不到被撤回的离线消息

——这就是为什么防撤回插件无法防撤回还没收到的消息

**Comment by zhaodice** [comment]
也就是说想获取被撤回的消息，必须客户端收到在线消息缓存起来才可以，离线消息是指望不上的（至少QQ客户端是如此体现）。

**Comment by Schezuk** [comment]
请问该获得离线消息API支持15天以外的历史消息吗？
miniQQ和老版QQLite（已失效）似乎可以获取无限远的消息，亲测超过一年以上。
