### ISSUE TITLE
如果账号异地登录被踢下线，继续使用同一个account.secrets 文件会登录失败

### ISSUE THREAD

**Issue by zhaodice** [mamoe/mirai#1199]
错误症状大概是，如果账号被异地登陆踢下线了，而且 account.secrets 还是上次的，那么登陆会失败，而且会有Notice: 你的账号异地登陆balabala，会有重试连接，三次后报错

network is dead before...
忘记错误信息了，等我复现一下

**Comment by zhaodice** [comment]
错误信息是：
network is dead therefore can‘t init

**Comment by zhaodice** [comment]
必须删除 account.secrets 才能解决问题

**Comment by zhaodice** [comment]
新发现：似乎是不同的protocol不能使用同一个account.secrets？

**Comment by Him188** [comment]
For mamoe:
- 在 account.secrets 保存登录时使用的协议，协议不同则不使用
- 登录失败一次后就删除 account.secrets

**Comment by AllGetHub** [comment]
这个现象我通过清除app数据解决了，希望能在下一次更新可以自动清除上边所述的文件，并在输出结果内提示重新进行登录验证。目前安卓版本的 Mirai可以和QQ HD这个版本的App同时在线，tim和QQ都会挤掉Mirai的登录。

**Comment by AllGetHub** [comment]
在MiraiAndroid的输出结果内，QQ HD 的登录状态为IOS，可能是iPad在线。

**Comment by Him188** [comment]
如果急用可以待 <https://github.com/mamoe/mirai/runs/2372988258?check_suite_focus=true> 完成后使用 `2.7-M1-dev-1`
