### ISSUE TITLE
申请特性：先使用缓存，后加载特性

### ISSUE THREAD

**Issue by zhaodice** [mamoe/mirai#1206]
当启用缓存时，mirai启动会率先使用缓存，然后可以提前登陆成功，减少登陆耗时
这时再开启一个线程，重新获取相关群列表等数据，用于更新缓存。

**Comment by zhaodice** [comment]
一定程度平衡了信息的时效性和登陆花费的时间。

**Comment by Him188** [comment]
这可能会造成时效问题----在 `bot.login()` 后的获取群列表等操作都变得不可靠

**Comment by zhaodice** [comment]
> 
> 
> 这可能会造成时效问题----在 `bot.login()` 后的获取群列表等操作都变得不可靠

如果缓存迟迟不更新的话，也会造成时效问题，给缓存做个失效时间？

**Comment by zhaodice** [comment]
我的意思是...bot.login()之后，群列表，好友列表，全部暂时使用缓存，然后开一个线程偷偷地做新的数据收集工作（可以放进临时变量里），一旦新的数据收集完毕，立即写出缓存覆盖并覆盖内存里的群列表等数据，相当于更新完成。

**Comment by zhaodice** [comment]
当然如果担心不可靠的问题的话，可以给一个api？允许检测mirai当前是否正在同步数据

**Comment by Him188** [comment]
> 我的意思是...bot.login()之后，群列表，好友列表，全部暂时使用缓存，然后开一个线程偷偷地做新的数据收集工作（可以放进临时变量里），一旦新的数据收集完毕，立即写出缓存覆盖并覆盖内存里的群列表等数据，相当于更新完成。

```kotlin
bot.login()
bot.getGroup(123) // (1)
```

这会导致 `(1)` 有可能获取到过期的数据

**Comment by Him188** [comment]
> 当然如果担心不可靠的问题的话，可以给一个api？允许检测mirai当前是否正在同步数据

这会导致现在已有的代码工作可能出现异常

**Comment by zhaodice** [comment]
> 
> 
> > 我的意思是...bot.login()之后，群列表，好友列表，全部暂时使用缓存，然后开一个线程偷偷地做新的数据收集工作（可以放进临时变量里），一旦新的数据收集完毕，立即写出缓存覆盖并覆盖内存里的群列表等数据，相当于更新完成。
> 
> ```kotlin
> bot.login()
> bot.getGroup(123) // (1)
> ```
> 
> 这会导致 `(1)` 有可能获取到过期的数据

也就是说使用缓存这个特性，必须承担数据过期无法更新的缺点吗，有没有获取在线更新数据的API呢
或者...给 Group 等对象加一个 var isExpired:Boolean ，告知此对象是否已过期，或者给一个到期时间 var expiredTime:Long

以上新特性可能造成已有的代码异常，所以可以加一个可选开关，显式启用特性，一旦显式启用，代表开发者已经知悉并适配了相关代码

**Comment by Him188** [comment]
我觉得这没有很大必要。加载列表只需要在启动时进行一次，而且一般只花费几秒。让这些状态可变之后不仅会增加 mirai-core 的维护难度，还会让用户的开发变得不便。

**Comment by zhaodice** [comment]
> 
> 
> 我觉得这没有很大必要。加载列表只需要在启动时进行一次，而且一般只花费几秒。让这些状态可变之后不仅会增加 mirai-core 的维护难度，还会让用户的开发变得不便。

我测试过，当群很多的时候，加载时间长达1分钟...虽然也在接受范围内，就是重启起来有点不太方便而已。
说起来之前启动加载挺快的，最近更新后慢了很多，是更新了什么东西吗（也许是我的错觉）

**Comment by Him188** [comment]
目前的缓存功能适合在自己日常测试时使用，这种时候不需要很精确的数据，在发现缓存意外过期时也可以手动删除缓存解决问题（我自己自支持缓存后就一直开着来运行测试，还没有出现问题）。

**Comment by Him188** [comment]
> > 我觉得这没有很大必要。加载列表只需要在启动时进行一次，而且一般只花费几秒。让这些状态可变之后不仅会增加 mirai-core 的维护难度，还会让用户的开发变得不便。
> 
> 我测试过，当群很多的时候，加载时间长达1分钟...虽然也在接受范围内，就是重启起来有点不太方便而已。
> 说起来之前启动加载挺快的，最近更新后慢了很多，是更新了什么东西吗（也许是我的错觉）

之前由于发包太快一些人被服务器断开连接了，所以就刻意限制了速度
