### ISSUE TITLE
发送群消息时显示发送成功，但实际上并没有正常显示

### ISSUE THREAD

**Issue by CNXudiandian** [mamoe/mirai#1209]
发送群消息时，HTTP接口调用返回成功（msg: "success"），控制台会显示发送的消息，但是messageId为0，且群内不显示该条消息。发送个人消息时，无此问题。

没有相关的日志，控制台并不会因此报错，其他功能正常使用（用到的功能：好友消息发送、好友消息接收、群消息接收、获取好友列表、获取群列表和获取群成员列表。）

#### 复现

不知道该如何复现，当时没有什么特别的，发现无法发送消息的前几分钟还可以正常发送消息。

尝试重启无果，特来求助。

#### 版本
- mirai-core: `2.6.2` 
- mirai-console:`2.6.2`
- iTXTech Mirai Console Loader:`1.0.5-9b6cf6d`
- mirai-api-http:`1.11.0`

**Comment by Him188** [comment]
~重启次数过多，一段时间后就会恢复正常~

请提供日志 (复制控制台的输出**和** logs 目录中的 `.log` 文件)

**Comment by CNXudiandian** [comment]
[2021-04-22.log](https://github.com/mamoe/mirai/files/6358972/2021-04-22.log)
这个是从\bots\269370395\logs复制出的发作当天的log
（找了找mirai运行目录下带log字样的就这个了似乎...不知道是不是这个呢？）
[console.log](https://github.com/mamoe/mirai/files/6358973/console.log)
这个是当时发作重启后的控制台输出

**Comment by CNXudiandian** [comment]
[2021-04-22.log](https://github.com/mamoe/mirai/files/6358972/2021-04-22.log)
这个是从\bots\269370395\logs复制出的发作当天的log
（找了找mirai运行目录下带log字样的就这个了似乎...不知道是不是这个呢？）
[console.log](https://github.com/mamoe/mirai/files/6358973/console.log)
这个是当时发作重启后的控制台输出

**Comment by elysiawen** [comment]
我也有同样的问题，版本是2.6.1，挂一段时间之后消息就发不出去，换回2.5就没这个问题。我是mirai和小栗子双开的，mirai控制台显示发出去消息，实际群里还有小栗子框架的日志里没有这条消息。

**Comment by BH3GEG** [comment]
我也出现了同样的问题，群聊消息无法发送，私聊可以，版本是2.6.2。
试了以前1.x版，可以发送。

**Comment by langyo** [comment]
也是同样的问题
[这是出问题的代码](https://github.com/langyo/chino-mirai-bot/tree/main/packages/entry/index.ts)

------

问题可能出在 mirai-api-http 与 mirai-core 的版本不兼容：
```
[WARNING] Package "net.mamoe:mirai-api-http" requires "net.mamoe:mirai-console" version 2.5.0. Current version is 2.6.2
```

------

当 websocket 服务端主动发送信息出去时的 log：
```
2021-04-24 05:56:36 V/Net 1931838621: Send: MessageSvc.PbSendMsg
2021-04-24 05:56:36 V/Net 1931838621: Recv: MessageSvcPbSendMsg.Response.SUCCESS
```
不论从日志还是从控制台输出来看都提示成功

------

额外补充，在出现该问题之前，我还发现了另一个不知是否与此问题有关的 bug，当群机器人尝试向某群员回复消息时，部分版本的 QQ 会莫名吞掉第一个字：

![image.png](https://i.loli.net/2021/04/24/3EO27JHKkBl6SF9.png)

![QQ图片20210424060709.jpg](https://i.loli.net/2021/04/24/tp2QyPJcHnxGMVm.jpg)

紧接着重启后就出现这个 Issue 提及的问题了

**Comment by langyo** [comment]
感谢 @SakuraXiaoWen 与 @li14300 给的一些提示，经过一阵紧急调试，确认当 mirai 的一批依赖包降级至 2.5.X 版本时是可用的

如果你是使用 mcl 的开发者，这些信息可能会帮到你

首先更改 config.json，将其中的三个 mirai 核心库的版本更改为 2.6-M1，通道改为 beta

（@sandtechnology 在[这个 issue ](https://github.com/mamoe/mirai/issues/1081)提到了 2.5.X 出现的空消息抛错问题，所以也同样不建议使用 2.5.X 版本）

![image](https://user-images.githubusercontent.com/23103705/115936823-db9f5980-a4c8-11eb-9abd-4bc7e74350a4.png)

然后为 mcl 的启动指令添加 ```-u``` 参数，以禁用更新

![image](https://user-images.githubusercontent.com/23103705/115936830-e1953a80-a4c8-11eb-9d9a-eff71d60a36c.png)

重新运行，此时固定版本 2.5.2 的 mirai 便可以使用了

请注意，这仅仅是一个临时补救方案，在未来 mirai 核心升级后，仍应当使用新版核心

**Comment by Him188** [comment]
@sandtechnology any idea?

**Comment by sandtechnology** [comment]
请问你们使用的协议类型是？
我觉得应该与这个有关联，另外一方面是腾讯服务器的风控问题

**Comment by sandtechnology** [comment]
另外一方面 请问你们发送的消息内容是？

**Comment by elysiawen** [comment]
使用的协议是Watch，在2.5.0使用时没有问题，升到2.6.x之后只有刚登上前几分钟没问题，等了一会后就出现无法发送的问题。消息内容为图片。

**Comment by sandtechnology** [comment]
将协议类型切换为安卓后，是否仍然有此问题？

**Comment by langyo** [comment]
直接在鱼塘里捕捉到了 @sandtechnology ，经过测试，2.6-M1 版本可以正常收发信息，2.6-M2 版本开始不能正常收发

现在正在准备 2.6-M1 和 2.6-M2 两份不同版本的日志

**Comment by langyo** [comment]
[mirai 2.6-M1 log](https://gist.github.com/langyo/a5c7aa99e8e2729f6504eef0b5fe8504)

[mirai 2.6-M2 log](https://gist.github.com/langyo/401ddab8e9c2e11bda2f41bc60fbf9b0)

@sandtechnology

**Comment by langyo** [comment]
再次测试后，2.6-M2 突然能用

下面交给史蒂夫新闻联播吧，大概是找到问题了（

希望特供补丁版能今天就 release

**Comment by sandtechnology** [comment]
@Him188 在登录中短时间register了两次，应该会造成暂时的风控，从而导致消息发送失败：

https://github.com/mamoe/mirai/blob/d3dc756a5047aa9e6026ad9d867b37c8e31698d7/mirai-core/src/commonMain/kotlin/network/handler/QQAndroidBotNetworkHandler.kt#L205
https://github.com/mamoe/mirai/blob/d3dc756a5047aa9e6026ad9d867b37c8e31698d7/mirai-core/src/commonMain/kotlin/network/handler/QQAndroidBotNetworkHandler.kt#L413

应该是这个原因

**Comment by Him188** [comment]
请尝试 `2.7-M1-dev-2`

**Comment by langyo** [comment]
> 请尝试 `2.7-M1-dev-2`

出现了新的问题，当收到所谓的空消息时，mirai-api-http 会抛出 500 错误——尽管 mirai-core 仍然在正常运行，但它抛的错误很莫名其妙

我不能确定这个问题是否与此 issue 报告的 bug 有关，如果能确定此问题与风控无关，我将再开一个 issue

下面是日志：

[mirai 空消息无法正确处理的 mirai-core 日志](https://gist.github.com/langyo/c156f83e2c05275bbbd0fe5a64b09598)

[mirai 空消息无法正确处理的 mirai-ts 日志（axios 客户端报错）](https://gist.github.com/langyo/c0338f798fbad6f455bfa45824f4a958)

（顺便一提，我的测试图片是野兽先辈![U 2(@C0FYW@WJ%AX7D@_03Y](https://user-images.githubusercontent.com/23103705/116002309-bf67fd80-a62b-11eb-894c-f4e8ef26f110.jpg)）

**Comment by langyo** [comment]
> 请尝试 `2.7-M1-dev-2`

![image](https://user-images.githubusercontent.com/23103705/116002678-731dbd00-a62d-11eb-8871-46084330ce57.png)

而且问题好像没有得到解决……

新的 stderr 日志：

```
2021-04-26 01:18:01 W/stderr: SLF4J: Failed to load class "org.slf4j.impl.StaticMDCBinder".
2021-04-26 01:18:01 W/stderr: SLF4J: Defaulting to no-operation MDCAdapter implementation.
2021-04-26 01:18:01 W/stderr: SLF4J: See http://www.slf4j.org/codes.html#no_static_mdc_binder for further details.
```

@sandtechnology

**Comment by sandtechnology** [comment]
事实上我有尝试复现过这个问题，但是仍然没有复现成功，所有功能一切正常
（建议在手机QQ上查看群消息以确认，我测试的时候存在电脑QQ吞消息的情况）

**Comment by Him188** [comment]
@langyo 试试在 Android 客户端能不能看到消息?

**Comment by langyo** [comment]
> @langyo 试试在 Android 客户端能不能看到消息?

再次尝试后，电脑版和手机版都能正常接收消息了，也许之前憋不出话的问题仍然出在短时间的风控

但仍然出现 message is empty 的问题

而且定位到出错的场景了，当 mirai-core 连续接收到两次单独的图片消息时，就会发生这个错误，而且很容易复现——只要随便发两个不同的图片就行了（使用电脑版 QQ，手机版 QQ 没有问题）

[这是日志](https://gist.github.com/langyo/ebbcb384e92628d728d2dd66425db42f)

**Comment by sandtechnology** [comment]
> 
> 
> > @langyo 试试在 Android 客户端能不能看到消息?
> 
> 再次尝试后，电脑版和手机版都能正常接收消息了，也许之前憋不出话的问题仍然出在短时间的风控
> 
> 但仍然出现 message is empty 的问题
> 
> 而且定位到出错的场景了，当 mirai-core 连续接收到两次单独的图片消息时，就会发生这个错误，而且很容易复现——只要随便发两个不同的图片就行了（使用电脑版 QQ）
> 
> [这是日志](https://gist.github.com/langyo/ebbcb384e92628d728d2dd66425db42f)

这个应该是HTTP-API的问题，去那边反馈吧，风控问题无法解决（

**Comment by wangzheooo** [comment]
我也是,从2.6.1开始,之前版本还没出现过,用了2.6.1和2.6.2都有这个问题,以前是pc不显示,手机显示,现在手机也收不到消息,过大约半分钟不到,手机就显示机器人发的消息了

**Comment by Him188** [comment]
> 我也是,从2.6.1开始,之前版本还没出现过,用了2.6.1和2.6.2都有这个问题,以前是pc不显示,手机显示,现在手机也收不到消息,过大约半分钟不到,手机就显示机器人发的消息了

试试使用 2.7-M1-dev-2 会不会出现手机收不到消息的情况？

**Comment by wangzheooo** [comment]
> > 我也是,从2.6.1开始,之前版本还没出现过,用了2.6.1和2.6.2都有这个问题,以前是pc不显示,手机显示,现在手机也收不到消息,过大约半分钟不到,手机就显示机器人发的消息了
> 
> 试试使用 2.7-M1-dev-2 会不会出现手机收不到消息的情况？

好的,我试一下,还出现问题的话再来反馈

**Comment by Him188** [comment]
> > > 我也是,从2.6.1开始,之前版本还没出现过,用了2.6.1和2.6.2都有这个问题,以前是pc不显示,手机显示,现在手机也收不到消息,过大约半分钟不到,手机就显示机器人发的消息了
> > 
> > 
> > 试试使用 2.7-M1-dev-2 会不会出现手机收不到消息的情况？
> 
> 好的,我试一下,还出现问题的话再来反馈

另外你使用的协议是什么？试试 ANDROID_PHONE

**Comment by langyo** [comment]
进一步测试过了，当出现可能的风控问题时，电脑版 QQ 大概率无法收到消息，手机版 QQ 小概率无法收到消息

我有些怀疑这其实是腾讯那边服务端的问题了……

**Comment by wangzheooo** [comment]
> > > > 我也是,从2.6.1开始,之前版本还没出现过,用了2.6.1和2.6.2都有这个问题,以前是pc不显示,手机显示,现在手机也收不到消息,过大约半分钟不到,手机就显示机器人发的消息了
> > > 
> > > 
> > > 试试使用 2.7-M1-dev-2 会不会出现手机收不到消息的情况？
> > 
> > 
> > 好的,我试一下,还出现问题的话再来反馈
> 
> 另外你使用的协议是什么？试试 ANDROID_PHONE

用的ANDROID_WATCH

**Comment by Xiaolangs** [comment]
2.7-M1-dev-2 提示成功　但是收不到消息

2021-04-28 12:00:01 V/Net 869692041: Send: MessageSvc.PbSendMsg
2021-04-28 12:00:01 V/Net 869692041: Recv: MessageSvcPbSendMsg.Response.SUCCESS
2021-04-28 12:00:04 V/Bot 869692041: Group(894349248) <- 注意文明用语

**Comment by sandtechnology** [comment]
试试 ANDROID_PHONE 协议？

**Comment by Him188** [comment]
@wangzheooo @Enough1998 @CNXudiandian 请使用 ANDROID_PHONE 测试

**Comment by Him188** [comment]
For mamoe: 

临时解决方案: 加一个设置调整心跳策略为 `SimpleGet` / `Register` / 无

**Comment by CNXudiandian** [comment]
_(:3」∠)_我怀疑是我小号Q龄太低，被盯上了，可能是我小号QQ自身的问题。
因为那个出问题的QQ号在mirai上挂了一段时间之后已经被封禁且无法解封了。（表现为解封就提示超时，已经放弃尝试了...）
换了另一个小号后可以正常发出去消息，而且使用了几天，也没有再次出现此情况了。
个人认为，这个问题大概率和风控有关。
不过，在此问题出现时，该账号使用任意官方QQ客户端（测试了安卓QQ、PCQQ、TIM）依然可以发出消息，并不会被吞消息。

**Comment by portwatcher** [comment]
mamoe/mirai#1209
