### ISSUE TITLE
iPhone设备向mirai发送纯文本的长消息，收到后，会在开头加入 UnsupportedMessage 类的数据

### ISSUE THREAD

**Issue by zhaodice** [mamoe/mirai#1210]
群聊，用户发送“xxxxx”，程序收到了“[不支持的消息#1]xxxxx”
我搜索了源码，找不到它的痕迹，它属于哪里？
消息接收代码（content为收到的文本消息） ：
var isAtMe = false
val contentBuilder = StringBuilder()
for (s in message) {
    if (s is At) {
        contentBuilder.append(s.target)
    } else if (s is MessageSource) {
        if (s.targetId == bot.id) {
            isAtMe = true
        }
    } else {
        contentBuilder.append(s.toString())
    }
}
var content = contentBuilder.toString()

**Comment by zhaodice** [comment]
找到了，是UnsupportedMessage

**Comment by Karlatemp** [comment]
确定只有纯文本？如果是这是一个有效的issue，请提供复现方式，以及登入协议

**Comment by zhaodice** [comment]
> 
> 
> 确定只有纯文本？如果是这是一个有效的issue，请提供复现方式，以及登入协议

我确定是纯文本，而且这个问题似乎只在很长的文本才会出现，以下是示例文本（因为是用户提供的截图，所以我用了OCR识别，可能有出入）：
.st力量70str70敏捷55dex55意志80pow80体质55con55外貌45app45教育60edu60体型70siz70智力75灵感
75int75san80san值80理智80理智值80幸运50运气mp16魔法16hp12体力12会计5人类学1估价5考古学1魅惑15攀爬20计算机5计算机使用5电脑5信用10信誉10信用评级10克苏鲁0克苏鲁神话0 cm0乔装5闪避27汽车50驾驶50汽车驾驶50电气维修10电子学1话术5斗殴60手枪75急救50历史5恐吓15跳跃20母语60法律50图书馆65图书馆使用65聆听50开锁1撬锁1锁匠1机械维修10医学1博物学10自然学10领航10导航10神秘学5重型操作1重型机械1操作重型机械1重型1说服60精神分析1心理学50骑术5妙手10侦查75潜行20生存10游泳20投掷20追踪10驯兽5潜水1爆破1读唇1催眠1炮术1

然后收到的消息就变成了（也就是说最前面多了个 UnsupportedMessage 类的数据，我已经拦截它了）：
[不支持的消息#1].st力量70str70敏捷55dex55意志80pow80体质55con55外貌45app45教育60edu60体型70siz70智力75灵感
75int75san80san值80理智80理智值80幸运50运气mp16魔法16hp12体力12会计5人类学1估价5考古学1魅惑15攀爬20计算机5计算机使用5电脑5信用10信誉10信用评级10克苏鲁0克苏鲁神话0 cm0乔装5闪避27汽车50驾驶50汽车驾驶50电气维修10电子学1话术5斗殴60手枪75急救50历史5恐吓15跳跃20母语60法律50图书馆65图书馆使用65聆听50开锁1撬锁1锁匠1机械维修10医学1博物学10自然学10领航10导航10神秘学5重型操作1重型机械1操作重型机械1重型1说服60精神分析1心理学50骑术5妙手10侦查75潜行20生存10游泳20投掷20追踪10驯兽5潜水1爆破1读唇1催眠1炮术1

协议是WATCH
以下是现象截图（由用户提供，已对群号和QQ做马赛克处理）
【上传失败，在下一个评论里】

**Comment by zhaodice** [comment]
![_4{IMFRX%MGXSH5L(2(0SRU](https://user-images.githubusercontent.com/63996691/115803852-4f335f00-a414-11eb-9745-506fd7134b2d.png)

**Comment by zhaodice** [comment]
其实我也不是非常确定那个人是WATCH 还是 ANDROID PHONE，因为我设定了 ANDROID PHONE 只有第一次登陆才会使用（确保登陆成功率），重启程序后默认WATCH 协议，我后面去问一下

**Comment by zhaodice** [comment]
我问了，应该是WATCH

**Comment by zhaodice** [comment]
新发现：这个现象不是每个人都可以复现，当时只有他一个人复现了，在询问那个人的环境情况（询问结果：可以复现的三个人都是iPhone）

**Comment by zhaodice** [comment]
所以这个问题可以总结为，iPhone设备向mirai发送长消息，会在开头加入 UnsupportedMessage 类的数据
