### ISSUE TITLE
接收的消息包含引用回复时只包含一个 `At` 时 `At` 也被过滤

### ISSUE THREAD

**Issue by jinghailun** [mamoe/mirai#1211]
```

```

#### 复现

QQ群回复机器人消息，机器人收到的消息没有包含@消息。
[mirai:source:[1938],[1529637633]][mirai:quote:[1925],[1843660686]]我喜欢你
![image](https://user-images.githubusercontent.com/50389806/115858478-95fb7600-a461-11eb-974c-e0e42982ca0c.png)

#### 版本
- mirai-core: `2.6.2`

**Comment by Him188** [comment]
For mamoe:

解决方案可能是当合并转发只包含一个 At 时不过滤
