### ISSUE TITLE
BotJoinGroupEvent 触发多次

### ISSUE THREAD

**Issue by zhaodice** [mamoe/mirai#1213]
版本：2.6.2
现象：触发 BotInvitedJoinGroupRequestEvent 后，执行 accept() ，当bot入群后，BotJoinGroupEvent 触发了2次。
协议：WATCH

**Comment by sandtechnology** [comment]
请问是否正在使用mirai-native？

**Comment by zhaodice** [comment]
> 请问是否正在使用mirai-native？

没有使用，目前使用是jar插件形式。

**Comment by sandtechnology** [comment]
那请问使用的协议类型是？
另外请给出相关的网络日志 其位于bots/qq号/logs下

**Comment by zhaodice** [comment]
> 那请问使用的协议类型是？
> 另外请给出相关的网络日志 其位于bots/qq号/logs下

WATCH协议
日志需要代码显式开启吗?我这里默认并没有生成相关文件(Android mirai console,dalvik环境)

**Comment by zhaodice** [comment]
我回头可以试试看jvm环境能否复现

**Comment by Him188** [comment]
试试使用 ANDROID_PHONE 协议?

**Comment by zhaodice** [comment]
> 
> 
> 试试使用 ANDROID_PHONE 协议?

我这边为了防止顶号默认是WATCH协议，毕竟这个问题我暂时用了有点卑鄙的方法解决了
不过后续我会用 ANDROID_PHONE 协议试试看能不能复现的
private val botJoinGroupEventQueue = HashMap<Long,Long>()
...
globalEventChannel().subscribeAlways(BotJoinGroupEvent::class, EmptyCoroutineContext) {
            val currentTime = System.currentTimeMillis()
            val lastTime = botJoinGroupEventQueue[group.id]
            if(lastTime!=null) {
                if (currentTime - lastTime < 5000) {// BotJoinGroupEvent 在5s内再次执行，拦截掉，这是mirai的BUG
                    return@subscribeAlways
                }
            }
            botJoinGroupEventQueue[group.id] = currentTime
            //...开始处理
        }

**Comment by zhaodice** [comment]
测试结果：
dalvik环境（android）复现成功，但jvm环境（windows）复现失败

dalvik:
![J( 23Q`)EF~EMLE$R8NNYB](https://user-images.githubusercontent.com/63996691/115951785-3d85b080-a515-11eb-8f11-12afec1fb2be.png)

jvm:
![Capture](https://user-images.githubusercontent.com/63996691/115951811-5ee69c80-a515-11eb-829a-939433b353a0.PNG)

复现时使用的代码：
![Capture2](https://user-images.githubusercontent.com/63996691/115951834-7aea3e00-a515-11eb-94bd-daebc4e0d550.PNG)

**Comment by zhaodice** [comment]
推测：dalvik 使用的mirai-console较旧（2.5.0），而且当时好像就是git clone 下来就直接编译了,做成了jar包作为APP的lib，会是这个原因吗？（这个验证起来有点困难...因为要重新编译console...暂时不确定是否和console有关）

**Comment by sandtechnology** [comment]
> 
> 
> 推测：dalvik 使用的mirai-console较旧（2.5.0），而且当时好像就是git clone 下来就直接编译了,做成了jar包作为APP的lib，会是这个原因吗？（这个验证起来有点困难...因为要重新编译console...暂时不确定是否和console有关）

请确认你填写的版本是否正确 你填写的版本为2.6.2，而该问题之前在2.6.0被修复一次：https://github.com/mamoe/mirai/pull/1123

**Comment by zhaodice** [comment]
> > 推测：dalvik 使用的mirai-console较旧（2.5.0），而且当时好像就是git clone 下来就直接编译了,做成了jar包作为APP的lib，会是这个原因吗？（这个验证起来有点困难...因为要重新编译console...暂时不确定是否和console有关）
> 
> 请确认你填写的版本是否正确 你填写的版本为2.6.2，而该问题之前在2.6.0被修复一次：#1123

你这个修复的是"其他管理员同意他人加入群会时，会触发bot入群的事件 "
而我的现象是拉了一个小群，小群只有我和bot，我邀请bot，bot同意，会【连续性】触发了2次BotJoinGroupEvent(当然小群有其他人，但我觉得不影响，没有其他人加群)

而且我确定我用的是2.6.2

**Comment by sandtechnology** [comment]
可以看看这个https://github.com/mamoe/mirai/issues/1203#issuecomment-823322144

**Comment by zhaodice** [comment]
> 可以看看这个[#1203 (comment)](https://github.com/mamoe/mirai/issues/1203#issuecomment-823322144)

安卓端，我应该用的是推荐的D8编译器，而且没有配置任何混淆

**Comment by Him188** [comment]
2.8.0-M1 成功复现
