### ISSUE TITLE
JavaApiTests 这个类在idea里怎么调试

### ISSUE THREAD

**Issue by ppx-build-code** [mamoe/mirai#1219]
```

```

#### 版本
- mirai-core: `1.3.0`

**Comment by Him188** [comment]
不能运行 
![image](https://user-images.githubusercontent.com/12100985/116175896-bff3b780-a743-11eb-80c6-ca7f6a1526ca.png)

**Comment by Karlatemp** [comment]
`JavaApiTests` 只是用来告知 `Java` 用户有这些 api 写法的

**Comment by ppx-build-code** [comment]
over.
