### ISSUE TITLE
接收不到好友语音消息

### ISSUE THREAD

**Issue by Xiaolangs** [mamoe/mirai#1221]
接收不到语音消息

```

```

#### 版本
- mirai-core: `2.6.2`

**Comment by Him188** [comment]
请提供日志；是好友消息还是群消息

**Comment by Xiaolangs** [comment]
> 请提供日志；是好友消息还是群消息

好友消息 群消息没有问题

**Comment by Him188** [comment]
请问有没有开启 `enableContactCache()` ? (在构造 Bot 时)

**Comment by Xiaolangs** [comment]
> 请问有没有开启 `enableContactCache()` ? (在构造 Bot 时)

没有

**Comment by Him188** [comment]
#931
