### ISSUE TITLE
android上有java的demo吗 android studio的还是只有kotlin呀

### ISSUE THREAD

**Issue by tghjnjvg** [mamoe/mirai#124]

**Comment by Him188** [comment]
可以使用 Kotlin 也可以使用 Java
可以使用任意编辑器，推荐使用 Gradle 构建
Java 的 demo: [mirai-demos](https://github.com/mamoe/mirai-demos/blob/master/mirai-demo-java/src/main/java/demo/BlockingTest.java)

**Comment by Him188** [comment]
要有最好的性能和最高的开发效率，请使用 Kotlin, [demo](https://github.com/mamoe/mirai-demos/blob/master/mirai-demo-kotlin/src/main/java/demo/subscribe/SubscribeSamples.kt)

**Comment by Him188** [comment]
若还有其他疑问, 请便 reopen issue
