### ISSUE TITLE
添加 MP3 到 silkv3 转码支持

### ISSUE THREAD

**Issue by Him188** [mamoe/mirai#1249]
https://github.com/mzdluo123/silk4j

添加一个外部模块, 如果发现 silk4j 存在就允许在 `uploadVoice` 时转换. 通过 `ExternalResource.formatName` 识别文件类型.

**Comment by dragon0629** [comment]
这个添加之后还需要ffmpeg嘛，现在弄了个30M大小的ffmpeg在根目录里，自己写的转码发送。否则PC听不到，手机可以。0_0
