### ISSUE TITLE
超过一段时间不发送信息导致bot无法发送信息

### ISSUE THREAD

**Issue by RimuruChan** [mamoe/mirai#1261]
睡了一觉起来发现bot发不了信息
控制台正常没有特殊日志
并且会有发送消息的日志
重启不能解决问题，需要关闭后
删除bot/qq号/cache文件夹
在打开之后才恢复正常

经常复现

**Comment by Him188** [comment]
试试切换心跳策略:

```kotlin
val bot = BotFactory.newBot() {
    heartbeatStrategy = HeartbeatStrategy.REGISTER
}
```

**Comment by xszqxszq** [comment]
> 试试切换心跳策略:
> 
> ```kotlin
> val bot = BotFactory.newBot() {
>     heartbeatStrategy = HeartbeatStrategy.REGISTER
> }
> ```

同2.6.4，好像不管什么心跳策略都会导致闲置一段时间发不出来任何消息，不过PHONE协议比PAD协议更容易出现该状况

**Comment by Him188** [comment]
> > 试试切换心跳策略:
> > ```kotlin
> > val bot = BotFactory.newBot() {
> >     heartbeatStrategy = HeartbeatStrategy.REGISTER
> > }
> > ```
> 
> 同2.6.4，好像不管什么心跳策略都会导致闲置一段时间发不出来任何消息，不过PHONE协议比PAD协议更容易出现该状况

切换到 NONE 理论上是不会有的

**Comment by Him188** [comment]
@RimuruChan 切换心跳策略后是否还有问题？https://github.com/mamoe/mirai/issues/1261#issuecomment-839414785

**Comment by RimuruChan** [comment]
2.6.7已经没有这个问题了
