### ISSUE TITLE
增加查询聊天漫游记录功能

### ISSUE THREAD

**Issue by sxzz** [mamoe/mirai#1265]
之前有一个 #726 不知为何被删除了，希望能够添加这个功能。

用途：想写一个聊天记录批量下载器。

**Comment by Nambers** [comment]
看看v2.8.0-M1
https://github.com/mamoe/mirai/releases#:~:text=%E8%B5%84%E6%BA%90%20(%231377%2C%20%231392)-,%E6%94%AF%E6%8C%81%E8%8E%B7%E5%8F%96%E6%BC%AB%E6%B8%B8%E6%B6%88%E6%81%AF%E8%AE%B0%E5%BD%95,-(%231184%2C%20%231520)

**Comment by sxzz** [comment]
Added in https://github.com/mamoe/mirai/pull/1520
