### ISSUE TITLE
奇怪的回复失效

### ISSUE THREAD

**Issue by wsvg14** [mamoe/mirai#1268]
使用efb+mirai转发qq消息
如果使用/chat方式进行群聊（一般的情况下），则在服务器端可以接收到我发送的消息，但是在qq群里并没有显示
但如果是通过将某个群聊单独link到tg群中直接进行交流则可以直接将消息发送
log上面看不出异常

```
已上传log文件
[2021-05-18.log](https://github.com/mamoe/mirai/files/6502657/2021-05-18.log)


```

#### 复现

使用/chat 方式向群聊发送消息：qq端无法看到消息，但是消息到达了服务器上并且正常提示发送
使用/link方式向群聊发送消息：正常在qq上看到

#### 版本
- mirai-core: `2.6.4` 
- mirai-api-http:'1.10.0'
- EHB: '2.1.0'
- EHB-telegram-master : '2.2.3'
- EHB-QQ-slave: '2.0.0b3'

#### 补充信息

似乎在较长时间以后连正常回复都出现困难

**Comment by sandtechnology** [comment]
看起来是新账号 这是腾讯的风控所致 请在挂机器人的服务器上登录电脑QQ 挂几天就会恢复正常

**Comment by sandtechnology** [comment]
如果是linux系服务器的话 可以试试纯挂几天机器人看看

**Comment by wsvg14** [comment]
> 如果是linux系服务器的话 可以试试纯挂几天机器人看看

似乎我被tx检测不安全让我改密码才能用了，可能是我在图形界面验证获得device.json是在虚拟机上跑的被检测了？

**Comment by Karlatemp** [comment]
可能是服务器风控导致, 或者频繁重启导致, 目前也没有稳定的解决方法, 以及请提供发送的内容

以及问题中的 `/chat`, `/link` 分别是什么东西, 对应实现代码是什么

**Comment by wsvg14** [comment]
> 可能是服务器风控导致, 或者频繁重启导致, 目前也没有稳定的解决方法, 以及请提供发送的内容
> 
> 以及问题中的 `/chat`, `/link` 分别是什么东西, 对应实现代码是什么

服务器上挂了几天，现在正常了,估计就是风控问题
/chat和/link是efb那边的bot控制命令，在tg端使用
