### ISSUE TITLE
多个账号登录问题

### ISSUE THREAD

**Issue by nanxia990105** [mamoe/mirai#1274]
就是多个账号登录该如何操作呢,我登陆了两个账号就一个账号回复了两条 共四条 预期是一人一条 

![image](https://user-images.githubusercontent.com/64909808/119221486-3fe22700-bb22-11eb-9fc0-bfbaf21e6193.png)

#### 版本
- mirai-core: `2.6.2` 

api('net.mamoe:mirai-core-api:2.6.2')

#### 补充信息

想知道该如何做多个账户登录 是需要我这边做个线程池 还是marai本身就有

**Comment by Karlatemp** [comment]
请更详细描述你所遇到的问题
- `两个账号就一个账号回复了两条 共四条` -> 提供发送的消息发送点代码, 并添加相关 debug 信息

**Comment by Karlatemp** [comment]
`多个账户登录` 只需要登录多个 bot 就行了, 线程池方面由 kotlin 协程控制

**Comment by nanxia990105** [comment]
> 请更详细描述你所遇到的问题
> 
> * `两个账号就一个账号回复了两条 共四条` -> 提供发送的消息发送点代码, 并添加相关 debug 信息

![image](https://user-images.githubusercontent.com/64909808/119222031-f34c1b00-bb24-11eb-96dd-e36f50fe07da.png)
目前是登录了两个
![image](https://user-images.githubusercontent.com/64909808/119222110-50e06780-bb25-11eb-9a52-ed3640482fc2.png)
![image](https://user-images.githubusercontent.com/64909808/119222121-5e95ed00-bb25-11eb-87c1-5bc726135a20.png)
在return的时候 又发送了一次

**Comment by Karlatemp** [comment]
你是不是在bot登入之后又注册了一次监听

**Comment by nanxia990105** [comment]
> 你是不是在bot登入之后又注册了一次监听

是的 是的 我的监听类是login的时候 新建了一个 登陆了两次确实注册了两次

**Comment by Karlatemp** [comment]
#514
