### ISSUE TITLE
登录时出现提示：当前上网环境异常，请更换网络环境或在常用设备上登录或稍后再试

### ISSUE THREAD

**Issue by nyancatda** [mamoe/mirai#1277]
版本:2.6.4
使用[Mirai Console Loader](https://github.com/iTXTech/mirai-console-loader)构建

尝试了多个账号，从等级到等级高均有，也确实是在常用地区，常用设备登录(有两个账号在同IP下的电脑和手机挂了两天)，所有账号均开启了设备锁，在所有协议下都会出现以下提示造成无法登录
```
2021-05-24 15:03:34 E/console: net.mamoe.mirai.network.WrongPasswordException: Error(bot=Bot(**********), code=237, title=禁止登录, message=当前上网环境异常，请更换网络环境或在常用设备上登录或稍后再试。, errorInfo=), tips=若频繁出现, 请尝试开启设备锁
net.mamoe.mirai.network.WrongPasswordException: Error(bot=Bot(1517805246), code=237, title=禁止登录, message=当前上网环 境异常，请更换网络环境或在常用设备上登录或稍后再试。, errorInfo=), tips=若频繁出现, 请尝试开启设备锁
        at net.mamoe.mirai.internal.network.handler.QQAndroidBotNetworkHandler.doSlowLogin(QQAndroidBotNetworkHandler.kt:335)
        at net.mamoe.mirai.internal.network.handler.QQAndroidBotNetworkHandler$doSlowLogin$1.invokeSuspend(QQAndroidBotNetworkHandler.kt)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:32)
        at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:113)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
```
在使用ANDROID_PHONE协议时使用了滑块登录，情况依旧

Good Luck

**Comment by ryoii** [comment]
看起来是密码错了哦，QQ只要是登录错误都会显示这段话，找找其他原因

**Comment by nyancatda** [comment]
> 看起来是密码错了哦，QQ只要是登录错误都会显示这段话，找找其他原因

确认过密码没有错误，从官网修改密码时直接复制的明文密码粘贴进去也是提示这样

**Comment by ryoii** [comment]
那尝试切换协议

**Comment by nyancatda** [comment]
> 那尝试切换协议

ANDROID_PHONE，ANDROID_PAD，ANDROID_WATCH我都试过了，都是弹出这个提示

**Comment by Karlatemp** [comment]
请手动完成滑块登录

https://docs.mirai.mamoe.net/mirai-login-solver-selenium/

https://github.com/project-mirai/mirai-login-solver-selenium

**Comment by nyancatda** [comment]
> 请手动完成滑块登录
> 
> https://docs.mirai.mamoe.net/mirai-login-solver-selenium/
> 
> https://github.com/project-mirai/mirai-login-solver-selenium

在使用ANDROID_PHONE协议时使用了滑块登录，情况依旧

**Comment by Karlatemp** [comment]
你是否使用了 `mirai-login-solver-selenium`, 请删除 `mirai-login-solver-selenium`

**Comment by Karlatemp** [comment]
如果急着登录请删除设备信息 (`mirai-console 位于 bots/**/device.json`)，不急的话等几天再次尝试

**Comment by nyancatda** [comment]
> 你是否使用了 `mirai-login-solver-selenium`, 请删除 `mirai-login-solver-selenium`

我在其他设备(同一内网环境)重新部署mirai，不包含任何插件的情况下也是出现这样的提示，在PAD和WATCH协议下

**Comment by Karlatemp** [comment]
你的ip域被风控了, 你可以在手机下一个 `devcheck` 并使用 https://ryoii.github.io/mirai-devicejs-generator/ 生成一个带有你手机信息的 `device.json` 替换掉 `bots/**/device.json` ( 先在手机登一次 bot 号 )

**Comment by nyancatda** [comment]
> 你的ip域被风控了, 你可以在手机下一个 `devcheck` 并使用 https://ryoii.github.io/mirai-devicejs-generator/ 生成一个带有你手机信息的 `device.json` 替换掉 `bots/**/device.json`

我使用我在阿里云和腾讯云的主机上都了进行尝试，均是相同的问题

**Comment by dragon0629** [comment]
> 你的ip域被风控了, 你可以在手机下一个 `devcheck` 并使用 https://ryoii.github.io/mirai-devicejs-generator/ 生成一个带有你手机信息的 `device.json` 替换掉 `bots/**/device.json` ( 先在手机登一次 bot 号 )

我用了DevCHeck Pro 3.32，但很多参数和这个生成器里的范例不太一样
我自己这边UUID、系统版和设备参数 这3个值，不知道对应devcheck pro里的哪个参数0-0，其他也有好几个是猜的
这个有没有推荐的apk版本或者对比参数图 -0-

然后其他反馈： 
测试使用其他PC协议的机器人框架可以正常登录新号，不知道是不是安卓这边还是有一些协议更改。

然后额外测试了GOCQHTTP，有2个办法可以登录

1.同样环境下，GO过滑块后会提示需要向密保手机号发送验证码，验证后即可登录。（我感觉MIRAI这边是不是就是这一步，过滑块后需要向密保手机号发送验证码没有处理，所以无法直接滑块登录）
2.此外GO那边还可以通过手机QQ扫码直接信任并登录

期望有更方便的解决方案

对了，就算是用新设备真机的手机QQ登录之前没登陆过的QQ，过完滑块都需要向密保手机发送验证码，才可以登录的。

**Comment by nyancatda** [comment]
> > 你的ip域被风控了, 你可以在手机下一个 `devcheck` 并使用 https://ryoii.github.io/mirai-devicejs-generator/ 生成一个带有你手机信息的 `device.json` 替换掉 `bots/**/device.json` ( 先在手机登一次 bot 号 )
> 
> 
> 
> 测试使用其他PC协议的机器人框架可以正常登录新号，不知道是不是安卓这边还是有一些协议更改。

我尝试过所有协议都不行

**Comment by lllbbbyyy** [comment]
> > 你的ip域被风控了, 你可以在手机下一个 `devcheck` 并使用 https://ryoii.github.io/mirai-devicejs-generator/ 生成一个带有你手机信息的 `device.json` 替换掉 `bots/**/device.json` ( 先在手机登一次 bot 号 )
> 
> 我用了DevCHeck Pro 3.32，但很多参数和这个生成器里的范例不太一样
> 我自己这边UUID、系统版和设备参数 这3个值，不知道对应devcheck pro里的哪个参数0-0，其他也有好几个是猜的
> 这个有没有推荐的apk版本或者对比参数图 -0-
> 
> 然后其他反馈：
> 测试使用其他PC协议的机器人框架可以正常登录新号，不知道是不是安卓这边还是有一些协议更改。
> 
> 然后额外测试了GOCQHTTP，有2个办法可以登录
> 
> 1.同样环境下，GO过滑块后会提示需要向密保手机号发送验证码，验证后即可登录。（我感觉MIRAI这边是不是就是这一步，过滑块后需要向密保手机号发送验证码没有处理，所以无法直接滑块登录）
> 2.此外GO那边还可以通过手机QQ扫码直接信任并登录
> 
> 期望有更方便的解决方案
> 
> 对了，就算是用新设备真机的手机QQ登录之前没登陆过的QQ，过完滑块都需要向密保手机发送验证码，才可以登录的。

那如果先使用GOCQHTTP登录，生成device.json后，再将参数填入网站，生成mirai这边需要的device.json，然后再去登录，这种方式可行么，我尝试了一下好像不行

**Comment by dragon0629** [comment]
> 那如果先使用GOCQHTTP登录，生成device.json后，再将参数填入网站，生成mirai这边需要的device.json，然后再去登录，这种方式可行么，我尝试了一下好像不行

我也尝试了不行，感觉主要原因还是因为生成网站的那几个参数写的还是有点模糊，我不确定我填的对不对应……
今天打算对比一下mirai本身的device.json，把ascii码转义一下看看，到底哪个对应哪个再试试0_0，也就临时方案

**Comment by lllbbbyyy** [comment]
> > 那如果先使用GOCQHTTP登录，生成device.json后，再将参数填入网站，生成mirai这边需要的device.json，然后再去登录，这种方式可行么，我尝试了一下好像不行
> 
> 我也尝试了不行，感觉主要原因还是因为生成网站的那几个参数写的还是有点模糊，我不确定我填的对不对应……
> 今天打算对比一下mirai本身的device.json，把ascii码转义一下看看，到底哪个对应哪个再试试0_0，也就临时方案

我之前是对应着mirai本身的device.json填的，它生成出来的各项顺序和网站上要填写的各项顺序好像是一致的，但是貌似还是不行

**Comment by dragon0629** [comment]
> > > 那如果先使用GOCQHTTP登录，生成device.json后，再将参数填入网站，生成mirai这边需要的device.json，然后再去登录，这种方式可行么，我尝试了一下好像不行
> > 
> > 
> > 我也尝试了不行，感觉主要原因还是因为生成网站的那几个参数写的还是有点模糊，我不确定我填的对不对应……
> > 今天打算对比一下mirai本身的device.json，把ascii码转义一下看看，到底哪个对应哪个再试试0_0，也就临时方案
> 
> 我之前是对应着mirai本身的device.json填的，它生成出来的各项顺序和网站上要填写的各项顺序好像是一致的，但是貌似还是不行
你imsiMd5那个值怎么填的，miria要求16位，GO是32位

**Comment by lllbbbyyy** [comment]
> > > > 那如果先使用GOCQHTTP登录，生成device.json后，再将参数填入网站，生成mirai这边需要的device.json，然后再去登录，这种方式可行么，我尝试了一下好像不行
> > > 
> > > 
> > > 我也尝试了不行，感觉主要原因还是因为生成网站的那几个参数写的还是有点模糊，我不确定我填的对不对应……
> > > 今天打算对比一下mirai本身的device.json，把ascii码转义一下看看，到底哪个对应哪个再试试0_0，也就临时方案
> > 
> > 
> > 我之前是对应着mirai本身的device.json填的，它生成出来的各项顺序和网站上要填写的各项顺序好像是一致的，但是貌似还是不行
> > 你imsiMd5那个值怎么填的，miria要求16位，GO是32位

貌似都是16位吧，直接放进去转换就可以，你如果少放，转换以后mirai读取反而会报错

**Comment by dragon0629** [comment]
> 貌似都是16位吧，直接放进去转换就可以，你如果少放，转换以后mirai读取反而会报错

{
    "display":"MIRAI.282259.001",
    "product":"mirai",
    "device":"mirai",
    "board":"mirai",
    "model":"mirai",
    "finger_print":"mamoe/mirai/mirai:10/MIRAI.200122.001/4631027:user/release-keys",
    "boot_id":"c9451e66-5d14-8aa1-9547-9a4741dd62d9",
    "proc_version":"Linux version 3.0.31-LH524vPa (android-build@xxx.xxx.xxx.xxx.com)",
    "protocol":0,
    "imei":"840249077859322",
    "brand":"mamoe",
    "bootloader":"unknown",
    "base_band":"",
    "version":{
        "incremental":"5891938",
        "release":"10",
        "codename":"REL",
        "sdk":29
    },
    "sim_info":"T-Mobile",
    "os_type":"android",
    "mac_address":"00:50:56:C0:00:08",
    "ip_address":[
        10,
        0,
        1,
        3
    ],
    "wifi_bssid":"00:50:56:C0:00:08",
    "wifi_ssid":"<unknown ssid>",
    "imsi_md5":"d920e12fb90f105b3d157e584b92dc73",
    "android_id":"b8bbd352a9b4a716",
    "apn":"wifi",
    "vendor_name":"MIUI",
    "vendor_os_name":"mirai"
}
GO的，根据这个改了好像还是不行 
wifi mac对应的是wifi_ssid吗？

**Comment by dragon0629** [comment]
话说mirai的设备信息device.json 看着没GO的直观，不知道能不能调整成标准json = .=bb

**Comment by Him188** [comment]
内存里存的是 ByteArray, 直接自动序列化就是现在这个格式了. 要 hex 表示就是手动处理一下, 这是一个不兼容变更因此会比较难修改

**Comment by dragon0629** [comment]
感谢解答，那还是暂时另外写个转码转出来看 -0-

**Comment by dragon0629** [comment]
https://mirai.mamoe.net/topic/223/%E6%97%A0%E6%B3%95%E7%99%BB%E5%BD%95%E7%9A%84%E4%B8%B4%E6%97%B6%E5%A4%84%E7%90%86%E6%96%B9%E6%A1%88

临时方案，确认可用，就等集成自带扫码登陆了，感恩

**Comment by dragon0629** [comment]
发现2.7M2的新号设备验证存在所有选项确定都填对了但验证不通过的
曾经登录的设备名、WIFI名、头像全部认识，并且选对，但提交后一样提示 提交资料有误，验证不通过

且有一个号过程中出现了以下哪个是曾经用过的头像，但列出的头像没有一个是之前用过的。是不是存在枚举错位的可能性呀？

以上问题不知道如何截图，感觉就算截图了也不能代表是否正确，毕竟用过哪些头像登录过哪些WIFI名只有自己知道……别人也没法验证。。。

版本是 2.7M2

**Comment by Him188** [comment]
@dragon0629 这应该属于服务器问题

**Comment by nyancatda** [comment]
> @dragon0629 这应该属于服务器问题

主要是在多个服务器都出现此问题，而且到目前为止问题依然存在

**Comment by Karlatemp** [comment]
请问你目前通过滑块验证码的方式是什么

**Comment by nyancatda** [comment]
> 请问你目前通过滑块验证码的方式是什么

是的，滑块验证

**Comment by Karlatemp** [comment]
手机 / 电脑? 具体方式

**Comment by dragon0629** [comment]
我目前还在使用这个
https://mirai.mamoe.net/topic/223/%E6%97%A0%E6%B3%95%E7%99%BB%E5%BD%95%E7%9A%84%E4%B8%B4%E6%97%B6%E5%A4%84%E7%90%86%E6%96%B9%E6%A1%88
这个可以使用。囧

2.7M2自带的能验证就是验证资料提交不对，本地电脑试过，腾讯云上也试过。不过我也就只有3个QQ号。没有更多号来验证，现在好像qq注册也开始限制了。

**Comment by dragon0629** [comment]
> 手机 / 电脑? 具体方式
话说真的不能增加一个码让手机qq直接扫码验证么，在命令行输出这个二维码，直接手机qq扫码可以不？
