### ISSUE TITLE
有可以添加定时消息的接口吗

### ISSUE THREAD

**Issue by jackatls** [mamoe/mirai#1278]

**Comment by 493505110** [comment]
你需要timer------------------&nbsp;Original&nbsp;------------------
***@***.***&gt;
Date:&nbsp;Mon, May 24, 2021 07:13 PM
***@***.***&gt;;
***@***.***&gt;;
Subject:&nbsp;[mamoe/mirai] 有可以添加定时消息的接口吗 (#1278)

**Comment by jackatls** [comment]
> 你需要timer------------------&nbsp;Original&nbsp;------------------ ***@***.***&gt; Date:&nbsp;Mon, May 24, 2021 07:13 PM ***@***.***&gt;; ***@***.***&gt;; Subject:&nbsp;[mamoe/mirai] 有可以添加定时消息的接口吗 (#1278)

我开另一个计时线程计时正常但运行类的sendgroup函数报错了，所以想知道有没有直接的计时触发接口

**Comment by Him188** [comment]
> > 你需要timer------------------ Original ------------------ _**@**_._**> Date: Mon, May 24, 2021 07:13 PM _**@**_.**_>; _**@**_.***>; Subject: [mamoe/mirai] 有可以添加定时消息的接口吗 (#1278)
> 
> 我开另一个计时线程计时正常但运行类的sendgroup函数报错了，所以想知道有没有直接的计时触发接口

没有这样的接口. 发送消息报错是什么?

**Comment by jackatls** [comment]
> > > 你需要timer------------------ Original ------------------ _**@**_._**> Date: Mon, May 24, 2021 07:13 PM _**@**_.**_>; _**@**_.***>; Subject: [mamoe/mirai] 有可以添加定时消息的接口吗 (#1278)
> > 
> > 
> > 我开另一个计时线程计时正常但运行类的sendgroup函数报错了，所以想知道有没有直接的计时触发接口
> 
> 没有这样的接口. 发送消息报错是什么?

感谢回复，已解决，我用的是python的接口，最后一行报错是：
RuntimeError: Timeout context manager should be used inside a task
参考了一下
https://stackoverflow.com/questions/52232177/runtimeerror-timeout-context-manager-should-be-used-inside-a-task
这篇文章
我一开始新建了一个时间循环，但实际应该用监听事件的那个loop来运行。

async def clock():
    #code
asyncio.run_coroutine_threadsafe(clock(),loop) 
app.launch_blocking()

就这样就可以写计时函数了
害，线程协程方面理解的不到位

**Comment by Karlatemp** [comment]
根据你使用的是 `python`, 所以此 `issue` 与 `mirai-core` 本体没有直接关系, 你可以到你使用的 Python 框架申请此 feature
