### ISSUE TITLE
JAVA JVM的Face表情列表获取

### ISSUE THREAD

**Issue by Coloryr** [mamoe/mirai#1279]
在KT可以通过
```kt
Face.Companion::class.memberProperties.forEach
```
拿出所有表情
但是JAVA无法获得

PokeMessage可以用`PokeMessage.values`，Face也能加一个这个就好了

**Comment by Karlatemp** [comment]
https://github.com/mamoe/mirai/blob/2e1fcfce7ce311163345f98cb10191c07473f954/mirai-core-api/src/commonMain/kotlin/message/data/Face.kt#L490

**Comment by Karlatemp** [comment]
可通过这个字段判断mirai已支持识别的全部表情

**Comment by Coloryr** [comment]
多谢，但是这样感觉拿不到key
能直接拿到<Int, String>就好了

**Comment by Him188** [comment]
> 多谢，但是这样感觉拿不到key
> 能直接拿到<Int, String>就好了

array 的 index 就是 key
