### ISSUE TITLE
支持扫码登录

### ISSUE THREAD

**Issue by Him188** [mamoe/mirai#1281]
有很多人没法通过密码登录, 此时扫码可能解决问题

**Comment by lllbbbyyy** [comment]
确实，好像有时候会在密码登录，滑块验证之后再跳转到扫码登录（最近用新的账号通过电脑登录时遇到过这种情况

**Comment by dragon0629** [comment]
+1，主要症状为过滑块后到不了设备锁那一步被直接拒绝

不过同环境同Q号，测试发现GO那边过完滑块，手动输入TICKET后，会提示发送验证码到密保手机号，但mirai这边是直接提示禁止登陆。并不是设备锁。

然后就是真机下手机QQ登陆，过完滑块一样需要点发送验证码到密保手机号，之后输入验证码后才可以登录。

然后GO有扫码模式，所以可以暂时无视这个登陆问题。等待MIRAI

**Comment by AdoptOSS** [comment]
@dragon0629  
验证码登录的话大概要等 #717 
看起来是TX的限制，这种情况下没法用正常方式登录了

**Comment by NekoWs** [comment]
+1 非常需要这个功能！
一直过不了设备锁那一步，老是说上网环境异常

**Comment by dragon0629** [comment]
![image](https://user-images.githubusercontent.com/29683336/130183326-3cccbc87-fc93-4798-b2fe-17d26178650e.png)
版本 2.7 RC DEV3
真的是无奈，手机号中间八位认识，用过的WIFI认识，加入的群认识，用过的头像认识，全部选对，依旧提交返回信息错误
是不是上报资料哪里错位了啊……我感觉都可以拍个视频了 = =b

话说这个扫码还打算支持嘛0_0

**Comment by dragon0629** [comment]
换了个别人的qq号，登录多了个这
![image](https://user-images.githubusercontent.com/29683336/130183978-8bc5c293-1bda-40d7-b633-6805aafc1968.png)

但是自己的号登录没有下面那个 TxCaptcharHelper,只有个设备锁验证

![image](https://user-images.githubusercontent.com/29683336/130184054-2d263f02-05f4-44ac-8f13-382ca42f6764.png)

**Comment by Him188** [comment]
@dragon0629 这是两种不同的验证

**Comment by Xiaojiuc** [comment]
俺想问一下老板，啥时候出这个扫码的功能啊，俺都已经等得迫不及待了

**Comment by dragon0629** [comment]
阿诺，俺也想问一问，现在新号登录真的是太痛苦了，上手门槛极高……

**Comment by Mantou1233** [comment]
为啥都困在登录这方面

**Comment by kingyangcn** [comment]
@Him188 希望尽快解决下登录这个世纪难题，非常感谢
