### ISSUE TITLE
[DSL]startsWith不按预期工作

### ISSUE THREAD

**Issue by fj233** [mamoe/mirai#1282]
如题，在GlobalEventChannel.subscribeMessages中的startsWith("")中会忽略掉空格，例如我的代码是
```
startsWith("tr ") { cmd ->
            translate(cmd, subject, message)
        }
```
但实际使用中会识别一切以tr开头的消息，而不是tr+空格开头的消息。

#### 版本
- mirai-core: `2.6.4`

**Comment by Him188** [comment]
值得注意的是 `containsAll` 似乎也有这个问题
