### ISSUE TITLE
优化 SwingSolver UI

### ISSUE THREAD

**Issue by Karlatemp** [mamoe/mirai#1283]
因为selenium的插件没有用了，所以配置的时候就换成了TxCaptchHelper, 可是在其弹出之后没有找到ticket可以返回的地方。想要来求助。
![198B234A1C566A71D5D0C9820F0CB8EA](https://user-images.githubusercontent.com/58930956/119501847-d2d9c600-bd9b-11eb-8ed0-904057c45940.png)

_Originally posted by @Robin-sys in https://github.com/mamoe/mirai-console/discussions/355_

**Comment by zhaodice** [comment]
看起来好像密码泄漏了...记得修改密码（是不是提醒的有点晚

**Comment by Karlatemp** [comment]
@Robin-sys
