### ISSUE TITLE
文档迁移到GitHub Wiki

### ISSUE THREAD

**Issue by lz1998** [mamoe/mirai#1284]
现在的文档放在代码中，没有总目录（只能一层一层点进去），内层才有目录，不方便搜索（只能和代码一起搜）

使用GitHub Wiki（参考 [drogon wiki](https://github.com/an-tao/drogon/wiki)）或Vuepress可以利用自带的搜索功能和目录功能，优化阅读体验

预期效果：
- Mirai
    - 社区SDK
        - 原生接口
        - HTTP接口
    - JVM平台Mirai开发
        - mirai core api文档
            - 机器人
                - ....
                - ....
            - 联系人
            - 事件
            - 消息

![image](https://user-images.githubusercontent.com/9082086/119669743-e0aa4c80-be6a-11eb-989a-1ec906b508c2.png)

**Comment by Karlatemp** [comment]
目前有 vuepress https://docs.mirai.mamoe.net

**Comment by Karlatemp** [comment]
目前已经部署了 `vuepress` 在 `github pages` (https://docs.mirai.mamoe.net, https://github.com/project-mirai/docs) 上, 再迁移到 `github wiki` 显得没有必要,
如果文档缺少了什么内容可以在 #848 提出建议,
或者发出 `Pull Request` 来帮助优化文档
