### ISSUE TITLE
Mirai是否可以获取正在登陆过程中的bots？（判断某个qq是否处于登陆过程也行）

### ISSUE THREAD

**Issue by zhaodice** [mamoe/mirai#1286]
用途：因为存在两个解耦的项目同时用一个mirai框架，A项目在登陆账号时，B项目也可能登同一个账号，这时我希望可以检测到mirai正在登陆这个账号从而取消登陆过程

**Comment by Karlatemp** [comment]
无，而且判断是否正在登录同一个账号应该由 A, B 自行协商, 或者移除登录逻辑让 C 登录

**Comment by sandtechnology** [comment]
关于这个问题，可以使用在登录过程中创建一个标识文件：QQ号.lck的方式实现

**Comment by zhaodice** [comment]
> 
> 
> 无，而且判断是否正在登录同一个账号应该由 A, B 自行协商, 或者移除登录逻辑让 C 登录

我留意到了
Bot.getInstance
似乎只要newBot就可以get到？这个是否具有全局性（比如直接在miraiAPI里登陆的bot能否在console 插件里使用“Bot.getInstance”获取到）

**Comment by zhaodice** [comment]
例如我在每次初始化bot之前，都执行一次

        try{
            val bot=Bot.getInstance(longQQ)
            if(bot.isOnline) {
                return null
            }else {
                bot.close()
            }
        }catch (e:Throwable){

        }

**Comment by zhaodice** [comment]
嗯...感觉还是上锁比较好
