### ISSUE TITLE
在同一个框架下，登录两个协议不同但qq相同的bot实列，close其中一个，另一个的有些好友就无法以 `bot.getFriend` 获取了

### ISSUE THREAD

**Issue by zhaodice** [mamoe/mirai#1287]
在同一个框架下，登陆两个协议不同但qq相同的bot实列，close其中一个，另一个就没办法取群/好友等信息了（被清了？）

**Comment by Karlatemp** [comment]
版本号和对应复现代码

**Comment by zhaodice** [comment]
> 
> 
> 版本号和对应复现代码

版本2.6.3
复现很简单，就是newBot两个同一个qq，不同协议的实例，再登陆，登陆成功后close其中一个，另一个实列的好友信息就丢了，（一个是在mirai API直接调用登陆，一个是在console 插件内登陆）

**Comment by Him188** [comment]
需要真实环境复现代码

**Comment by zhaodice** [comment]
@Him188 
插件内的登陆操作：
![Capture](https://user-images.githubusercontent.com/63996691/119984973-a53b8980-bff4-11eb-8f98-8e6138f936fa.PNG)

    fun createBot(qq:String,password:String): BotWithOptions {
        //val qq = accountInfo[0].trim()
        //val password = accountInfo[1].trim()
        //if(password.length<=16) {
        val longQQ = qq.toLong()
        val deviceFile = File("$zhaoDiceDeviceInfo/$qq.json")
        var loginDeviceFilePathFile = deviceFile//默认尝试私有设备文件
        if (!loginDeviceFilePathFile.exists())//如果不存在私有设备文件
            loginDeviceFilePathFile = miraiDeviceFile//尝试公有设备文件
        logPrint("赵骰正在试图自动登陆${qq},请稍等...\n使用设备文件信息\n${loginDeviceFilePathFile}")
        if (captchaImagePath.exists())
            captchaImagePath.delete()
        if (captchaTXTPath.exists())
            captchaTXTPath.delete()
        val protocolSet = BotConfiguration.MiraiProtocol.ANDROID_WATCH
        val cacheDirSet = dataFolder.resolve(".MiraiCache_$protocolSet/$qq").apply { mkdirs() }
        val aliveFile = cacheDirSet.resolve("aliveTime.txt")
        val cacheResettingTime = 30000L//在多少秒的时间内（30秒）重启系统，缓存是有效的
        return BotWithOptions(loginDeviceFilePathFile,cacheResettingTime,cacheDirSet,aliveFile,BotFactory.newBot(longQQ, password) {
            workingDir = dataFolder.resolve(".MiraiWorking")
            protocol = protocolSet
            try {
                cacheDir = cacheDirSet
                val currentTime = System.currentTimeMillis()
                val contactsDir = cacheDir.resolve("contacts")
                if (aliveFile.exists()) {
                    val aliveTime = aliveFile.readText().toLong()
                    if (currentTime - aliveTime > cacheResettingTime) {
                        //在 cacheResettingTime 秒后重新启动 ,缓存无效
                        logPrint("联系缓存：过期，已删除", infoColor)
                        contactsDir.deleteRecursively()//删除缓存
                    } else {
                        logPrint("联系缓存：生效，启用快速登陆", infoColor)
                    }
                } else {
                    logPrint("联系缓存：无效，已删除", infoColor)
                    contactsDir.deleteRecursively()//删除缓存
                }
                //enableContactCache()
            } catch (e: Throwable) {
                println("赵骰APP版本低了一级哦，还请即时加群获取最新版APP")
                errorPrint(e)
            }
            fileBasedDeviceInfo(loginDeviceFilePathFile.absolutePath)
            loginSolver = object : LoginSolver() {
                fun notice(bot: Bot) {
                    logger.warning("登陆${qq}失败，请重新删除已登陆的骰娘账号，重新登陆进行验证即可。")
                    bot.close()
                }

                fun waitCaptcha(bot: Bot): String {//循环检测captcha.txt直到存在为止
                    return if (isAndroid) {//安卓不解决此问题，由APP提供账号登陆服务
                        notice(bot)
                        ""
                    } else {
                        while (!captchaTXTPath.exists()) {
                            Thread.sleep(1000)
                        }
                        val result = TextFileOperator.read(captchaTXTPath)
                        if (captchaImagePath.exists())
                            captchaImagePath.delete()
                        if (captchaTXTPath.exists())
                            captchaTXTPath.delete()
                        result
                    }
                }

                override suspend fun onSolvePicCaptcha(bot: Bot, data: ByteArray): String {
                    logger.info("!UnSafeDeviceIMAGE(${captchaImagePath})")
                    FileService.writeBytes(captchaImagePath, data)
                    return waitCaptcha(bot)
                }

                override suspend fun onSolveSliderCaptcha(bot: Bot, url: String): String {
                    logger.info("!UnSafeDeviceVURL(${url})")
                    return waitCaptcha(bot)
                }

                override suspend fun onSolveUnsafeDeviceLoginVerify(bot: Bot, url: String): String {
                    logger.info("!UnSafeDeviceVURL(${url})")
                    return waitCaptcha(bot)
                }
            }
        })
    }


APP内的登陆操作：
![Capture1](https://user-images.githubusercontent.com/63996691/119985068-c308ee80-bff4-11eb-97d8-59de21035d5b.PNG)


当我在事件BotOnlineEvent里执行代码（2021/5/31更新）
//当有重复BOT上线时，关闭之前的BOT，留住新的
botsList[bot.id].apply {
    if(botsList[bot.id]==null){
        botsList[bot.id] = bot
    }else if(botsList[bot.id]!=bot) {
        //this.close() 这里屏蔽的原因是，close了所有同qq的bot实例都不能获取好友信息了。
        logPrint("发现重复的qq登陆，旧的bot实例被强制下线！（这不是错误，只是提示，建议重启APP）",errorColor)
        botsList[bot.id] = bot
    }
}

**Comment by zhaodice** [comment]
生产环境代码太屎了都不知道怎么贴XD，所以优先简述了....

**Comment by Him188** [comment]
"好友信息就丢了" 是有新消息时控制台没显示? 要如何复现? 并提供你遇到问题时的控制台日志 @zhaodice

**Comment by zhaodice** [comment]
> 
> 
> "好友信息就丢了" 是有新消息时控制台没显示? 要如何复现? 并提供你遇到问题时的控制台日志 @zhaodice

怎么说呢，假如我要往id 这个QQ号发消息：
if(currentBot.containsFriend(id.toLong())) {
    contact = currentBot.getFriend(id.toLong())
    if (isAndroid) {
        logPrint("[发][BOT:${currentBot.id}],往好友[$id] \n $s", messageSentColor)
    }
}else {
    contact = currentBot.getStranger(id.toLong())
    if (isAndroid) {
        logPrint("[发][BOT:${currentBot.id}],往陌生人[$id] \n $s", messageSentColor)
    }
}
我会先判断是否是Friend，如果是Friend，就往好友发消息，否则就往陌生人发消息
”好友信息丢了“就是指，本应该是好友，bot.containsFriend(id.toLong())期望值为true，但它为false

**Comment by Him188** [comment]
感觉不太可能是 mirai 问题, 先搁置等 2.7-M1 再试试

**Comment by Karlatemp** [comment]
感觉像是你自己的 bot 管理出错了，core内部代码并没有问题

**Comment by zhaodice** [comment]
> 
> 
> 感觉像是你自己的 bot 管理出错了，core内部代码并没有问题

显然不是，大概步骤是这样的

1.我登陆一个以Android Phone协议的Bot
2.BotOnlineEvent 收到请求，记录这个Bot实例（Android Phone）
3.我再登陆一个以Watch协议的Bot（同一个QQ）
4.BotOnlineEvent 收到请求，发现已经有同QQ下的Bot实例（Android Phone）了，于是把该Bot实例（Android Phone）调用了.close()，并替换掉原本的Bot实例（Android Phone）为新Bot实例（Watch）
5.我现在发现，新Bot实例（Watch）的getFriend没法用了，containsFriend本该期望值是true的，现在变false了，消息还是可以收（在我这里的表现就是识别成了陌生人）

**Comment by zhaodice** [comment]
我现在的猜测是，.close()是不是回收了什么东西

**Comment by zhaodice** [comment]
反过来，上面步骤一致，如果没有对Android Phone协议的Bot进行close()，那么（Watch）的getFriend就不受影响，代价是Event会收到2次。

**Comment by zhaodice** [comment]
不知复现遇到了什么困难，我愿意提供帮助

**Comment by Him188** [comment]
能否提供完整项目源代码？如果不方便公开，可以发至 support@mamoe.net

**Comment by zhaodice** [comment]
> 
> 
> 能否提供完整项目源代码？如果不方便公开，可以发至 [support@mamoe.net](mailto:support@mamoe.net)

项目比较杂乱，编译环境很难配，而且我构造了一个最简环境发现没能复现问题，打算再进一步检查，后面会详细报告一下
顺便问一下，我定义了一个
val currentBot get() = botsList[bot.id] as Bot
我每一次调用currentBot都等价于botsList[bot.id]吗？还是kotlin给我缓存了，如果存在缓存那么问题就好解释了

**Comment by zhaodice** [comment]
哎，神奇了，更新到2.6.6之后问题就没能复现，完全正常了（主项目），难道修复了什么吗，不管怎么说还是麻烦你们了，谢谢x
