### ISSUE TITLE
踢人时设置不再接受此人加群申请

### ISSUE THREAD

**Issue by mill413** [mamoe/mirai#1288]
踢人的时候QQ会有个选项设置不再接受此人加群申请，希望在调用member.kick的时候也可以设置一个参数实现这个功能
另，想知道member.kick有一个message参数有何用处

**Comment by Him188** [comment]
> 踢人的时候QQ会有个选项设置不再接受此人加群申请，希望在调用member.kick的时候也可以设置一个参数实现这个功能
> 另，想知道member.kick有一个message参数有何用处

现在官方客户端已经没有这个选项了

**Comment by Karlatemp** [comment]
#1457
