### ISSUE TITLE
重复收到(解析到)好友消息

### ISSUE THREAD

**Issue by tom8zds** [mamoe/mirai#129]
根据教程简单的设置了一个自动回复，每次回复都会变多

![image](https://user-images.githubusercontent.com/20534594/76429993-c19cd780-63ea-11ea-96fe-dd86f7c17330.png)

**Comment by Him188** [comment]
好友消息？

**Comment by tom8zds** [comment]
> 好友消息？

群消息和好友都会出现这种情况

**Comment by Him188** [comment]
群消息不应该，好友消息倒是会

**Comment by tom8zds** [comment]
> 群消息不应该，好友消息倒是会

debug显示每次恢复suspend fun <E : Packet> OutgoingPacket.sendAndExpect接收到的retry都会+1

**Comment by Him188** [comment]
不是包接收问题，是查询问题。

**Comment by Him188** [comment]
查询好友消息时服务器会返回多条
