### ISSUE TITLE
撤回好友消息在 PC TIM 端无效

### ISSUE THREAD

**Issue by Xuwznln** [mamoe/mirai#1293]
请见复现

```
无非正常日志
```

#### 复现
监听好友聊天事件，发送回复消息并跟.recallIn()方法，分别设置14秒（14000）与16秒（16000）
14秒的消息会被撤回，而16秒的不会
本地测试时比较激进，14999与15000也会发生上述问题。

#### 版本
- mirai-core: `2.6.5`

**Comment by Him188** [comment]
这很有趣，方便提供真实代码吗？撤回不成功是不是日志正常输出但客户端内没有变化

**Comment by Xuwznln** [comment]
后来测试过程中发现这个分界的秒数不固定，较长时间的消息目前还没有成功撤回的。
举例1：当15秒以内，日志没有撤回提示，消息正常撤回
![8@0U~1M9MP1YZ FEVF1(_U](https://user-images.githubusercontent.com/18435084/120215620-85ac9700-c268-11eb-969a-99929dd696d5.png)
![F07DY)7UNQ1_MAV TU F`YV](https://user-images.githubusercontent.com/18435084/120216227-521e3c80-c269-11eb-8321-c7bd954b2b21.png)
![image](https://user-images.githubusercontent.com/18435084/120217547-12f0eb00-c26b-11eb-8a05-7f3e17eea9d5.png)


举例2：重启，设定60秒，2次，重启，设定10秒
![image](https://user-images.githubusercontent.com/18435084/120217428-e89f2d80-c26a-11eb-937f-a58e9c153914.png)

```
class EHelperService {
    var registered = true
    val listener: CompletableJob = GlobalEventChannel.subscribeAlways<MessageEvent> { e ->
        when(e){
            is GroupTempMessageEvent,is StrangerMessageEvent,is FriendMessageEvent -> {
                if(e.sender.id in ehelperService) func(e.message)?.let {
                    MessageChainBuilder().append(QuoteReply(e.message)).append(it.build()).build().sendTo(e.sender).recallIn(10000)
                }
            }
        }
    }
    fun func(m:MessageChain):MessageChainBuilder?{
        return MessageChainBuilder().append("奇葩").append(System.currentTimeMillis().toString())
    }
}
```

**Comment by Him188** [comment]
使用 2.7-M1 是否还能复现？

**Comment by Xuwznln** [comment]
使用2.7-M1-dev6 2.7-M2-dev7 分别进行2s和60s的撤回测试，代码同上次回复。
控制台在到达撤回时间时均提示：
```
2021-06-28 22:21:58 I/stdout: 2021-06-28 22:21:58 V/Net QQ: Send: PbMessageSvc.PbMsgWithDraw(PbMessageSvc.PbMsgWithDraw)
2021-06-28 22:21:58 I/stdout: 2021-06-28 22:21:58 D/Net QQ: unknown group 528 type 0x000000000000008B, data: 0A 38 08 D7 93 F8 8B 05 10 A5 C4 E8 E7 03 18 D0 E5 CA 81 05 20 AD F3 DC D8 82 80 80 80 01 28 CA B5 E7 86 06 30 AD F3 DC D8 02 38 00 40 00 48 00 50 00 60 01 6A 04 08 00 12 00 10 E9 07 18 89 D8 8B 80 02 20 00 2A 02 08 00
2021-06-28 22:21:58 I/stdout: 2021-06-28 22:21:58 V/Net QQ: Recv: PbMessageSvc.PbMsgWithDraw
```
2s的均撤回成功，60s的均不成功

**Comment by sandtechnology** [comment]
请问是只有好友聊天才会出现此情况吗？

**Comment by Him188** [comment]
For mamoe: 

2.7-M2:
为 PbMessageSvc.PbMsgWithDraw 的 toString 添加目标 id 等信息

**Comment by Him188** [comment]
经测试, Bot 撤回自己发送的好友消息, 对方 PC TIM 端无反馈, 对方 Android QQ 正常撤回
