### ISSUE TITLE
使设备信息 device.json 更易读易修改

### ISSUE THREAD

**Issue by Him188** [mamoe/mirai#1295]
- 增加一个版本号属性来实现兼容
- Hex 字符串表示字节数组

待解决问题:
- [x] 是否自动迁移旧文件到新文件?

**Comment by AdoptOSS** [comment]
> * Hex 字符串表示字节数组

考虑到`DeviceInfo`里的信息大部分其实都算字符串，只是被`toByteArray`后存储。
考虑易读性的话应该弃用Bytes直接以原始字符串形式存储，而不是hex形式存储

https://github.com/mamoe/mirai/blob/a5e85f443e450a13b24c955823ab783fd36aa602/mirai-core-api/src/commonMain/kotlin/utils/DeviceInfo.kt#L83-L105

**Comment by Him188** [comment]
@AdoptOSS 谢谢，不过我的意思是把 imsiMd5 这些属性以 hex 存储
