### ISSUE TITLE
QQ登陆出现”资料辅助验证“，并成为唯一方式，无法验证。

### ISSUE THREAD

**Issue by zhaodice** [mamoe/mirai#1297]
试了打开设备锁，”资料辅助验证“依然是唯一方式，猜测可能是账号问题，因为是别人的账号，我没办法在我的机器上复现（会直接因为网络异常禁止登陆）。
点击资料辅助验证是没有任何反应的（我不知道是不是我的浏览器的问题）
版本：2.6.3
![QQ图片20210601182659](https://user-images.githubusercontent.com/63996691/120310005-7b41da00-c308-11eb-915f-bc8669ae7a5f.png)

**Comment by zhaodice** [comment]
集中大量用户（5人）在今天出现了这个情况，在考虑使用真实设备登陆以解决问题

**Comment by shenjackyuanjie** [comment]
+1 我这边也出现了单一“资料辅助验证”的问题

**Comment by zhaodice** [comment]
因大范围出现这个问题，可以定性为TX的更新，目前把链接复制粘贴到手机qq可以正常显示二维码

**Comment by zhaodice** [comment]
目前在寻求，让普通浏览器也可以正常加载登陆验证二维码的方法

**Comment by shenjackyuanjie** [comment]
我测试了一下
用F12打开之后（Edge Beta “元素”）
网页后台没有找到隐藏的验证二维码的链接（根据我的能力没有找到）
所以可以确认是TX的后台更新
对不同浏览器的显示不同，也许可以尝试修改浏览器的识别信息？

**Comment by zhaodice** [comment]
> 我测试了一下
> 用F12打开之后（Edge Beta “元素”）
> 网页后台没有找到隐藏的验证二维码的链接（根据我的能力没有找到）
> 所以可以确认是TX的后台更新
> 对不同浏览器的显示不同，也许可以尝试修改浏览器的识别信息？

我改过，没用……主要是我安卓那个webview直接就没内容了，连那个资料辅助验证都他妈的显示不出来，麻了

**Comment by shenjackyuanjie** [comment]
> > 我测试了一下
> > 用F12打开之后（Edge Beta “元素”）
> > 网页后台没有找到隐藏的验证二维码的链接（根据我的能力没有找到）
> > 所以可以确认是TX的后台更新
> > 对不同浏览器的显示不同，也许可以尝试修改浏览器的识别信息？
> 
> 我改过，没用……主要是我安卓那个webview直接就没内容了，连那个资料辅助验证都他妈的显示不出来，麻了

够TMD离谱

**Comment by zhaodice** [comment]
我感觉它调用了qq浏览器的什么狗屁api……毕竟控制台那么多报错不是虚的

**Comment by shenjackyuanjie** [comment]
hmmmmmmmmm
确实，毕竟谁知道QQ魔改了什么呢

**Comment by zhaodice** [comment]
> hmmmmmmmmm
> 确实，毕竟谁知道QQ魔改了什么呢

经测试，qq可以打开链接，tim也能，并且可以正常加载验证码……所以临时解决方案就是拿qq当浏览器顶一下了……

**Comment by shenjackyuanjie** [comment]
> 临时
离谱.gif啊

**Comment by zhaodice** [comment]
来个大佬，把qq给逆了，把这个验证界面用的qq内置浏览器的内部api都找出来也许就解决了

**Comment by shenjackyuanjie** [comment]
可还行（（（

**Comment by Him188** [comment]
那么解决方法就是用 QQ 内置的浏览器访问了. mirai 也没办法绕过这个验证

**Comment by Cloud370** [comment]
把验证url`https://ti.qq.com/safe/verify`的verify替换成qrcode就行了
甚至还能直接跳过点击的那步

![image](https://user-images.githubusercontent.com/46866207/120883903-7e8fdb00-c612-11eb-9cbf-a14eb643cb06.png)
![image](https://user-images.githubusercontent.com/46866207/120883909-8bacca00-c612-11eb-9e8d-b302abdc8c38.png)

**Comment by AdoptOSS** [comment]
根据OICQ Library的实现，似乎可以通过修改URL绕过网页直接获取二维码
> ```js
>         const url = String(t[0x204]).replace("verify", "qrcode");
> ```
> Origin: https://github.com/takayama-lily/oicq/blob/30701075734ffca8aabdcb04bf00641c14c70347/lib/wtlogin/wt.js#L579

注：需要确定这样做的风控情况
