### ISSUE TITLE
私聊发送图片数量超限后bot无法正常发出消息

### ISSUE THREAD

**Issue by Pika-Lee** [mamoe/mirai#1300]
如题，QQ私聊每日最多可发送2000张图片。超过此限制后，bot将无法发送**带图片的消息内容**。

建议遇到此情况后，能够让bot正常发出不带图片的文字消息，而不是无法发出整条消息。

![QQ截图20210603172527](https://user-images.githubusercontent.com/23114990/120626788-97bf4d00-c495-11eb-82e6-aac573dfc6d2.png)

#### 复现
1.让Bot一天内私聊发送2000张图片
2.下一条带图片的私聊消息，bot无法正常发出

#### 版本
- mirai-core: `2.2.2` 

- mirai-native: `2.0.0`

**Comment by Him188** [comment]
这是服务器的限制

**Comment by Pika-Lee** [comment]
之前用其它机器人的时候，遇到这种情况可以过滤掉图片，只将图文消息中的文字部分发出，而不是整条消息都无法发出。不知道Mirai是否也能实现？

**Comment by sandtechnology** [comment]
这种情况下应该交由方法调用者进行处理 直接在uploadImage方法捕获异常处理即可
不过我发现你用的是mirai-native，那应该需要去那边提一个feature request了
