### ISSUE TITLE
请求加一个被禁言成员列表功能

### ISSUE THREAD

**Issue by LittleTurtle2333** [mamoe/mirai#1319]
![](https://i.imgur.com/vmRc5JQ.jpg)
获取这里面所有人的QQ号批量解禁

**Comment by Him188** [comment]
现在可以遍历成员列表筛选处于禁言状态的成员

**Comment by LittleTurtle2333** [comment]
@Him188 可是这样会不会很没有效率，我有12个群（3个3000人，9个2000人），几万人遍历:disappointed_relieved:

**Comment by Him188** [comment]
> @Him188 可是这样会不会很没有效率，我有12个群（3个3000人，9个2000人），几万人遍历😥

实际上远比进行一次网络请求快的

**Comment by LittleTurtle2333** [comment]
@Him188 马克，明天试试
