### ISSUE TITLE
[建议]建议在readme中maven版本号旁边加上JDK版本或者JAVA版本

### ISSUE THREAD

**Issue by 2926295173** [mamoe/mirai#1321]

**Comment by Him188** [comment]
![image](https://user-images.githubusercontent.com/12100985/121633966-5e4e9900-cab6-11eb-8d74-99ff6ea483cb.png)
https://github.com/mamoe/mirai/blob/dev/docs/Preparations.md#mirai---preparations

第一步里面是有 JDK 版本的
