### ISSUE TITLE
Windows纯控制台版本无法安装

### ISSUE THREAD

**Issue by zuochao44** [mamoe/mirai#1329]
Windows纯控制台版本下载后安装进度总会进行一段时间后卡住，三台电脑，重试24次都没有用

**Comment by Karlatemp** [comment]
?

**Comment by Him188** [comment]
是网络问题

**Comment by Him188** [comment]
可试试 https://mirai.mamoe.net/assets/uploads/files/1618372079496-install-20210412.cmd
