### ISSUE TITLE
Quote message sent by iOS TIM cannot be parsed successfully

### ISSUE THREAD

**Issue by jqqqqqqqqqq** [mamoe/mirai#133]
Problem: 
<img width="1034" alt="image" src="https://user-images.githubusercontent.com/12872927/76233723-03692a80-61ff-11ea-96db-72950830f538.png">

Message do not have a valid source

Solution:
Use a forged source id instead (e.g. -1)

**Comment by Him188** [comment]
Planned to rewrite `MessageSource`

**Comment by Him188** [comment]
0.33.0
