### ISSUE TITLE
机器人拒绝另一个账号的加群申请后，另一个账号没有收到拒绝时附带的消息

### ISSUE THREAD

**Issue by wzxinchen** [mamoe/mirai#1333]
19:15:49 [INFO] iTXTech Mirai Console Loader version 1.0.5-9b6cf6d
............................... 
14:45:59 [INFO] Verifying "net.mamoe:mirai-console" version 2.6.6
 14:46:00 [INFO] Verifying "net.mamoe:mirai-console-terminal" version 2.6.6
 14:46:00 [INFO] Verifying "net.mamoe:mirai-core-all" version 2.6.6
 14:46:00 [INFO] Verifying "net.mamoe:mirai-api-http" version 1.10.0
 14:46:00 [INFO] Verifying "net.mamoe:chat-command" version 0.5.1

```
{
	"sessionKey": "Ooji3mUn",
	"eventId": "1623582498443830",
	"fromId": "399016112",
	"groupId": "749042893",
	"operate": 1,
	"message": "test"
}
```

399016112这个账号没有收到test这个附加消息，如果手动操作拒绝入群，是可以收到的

**Comment by Karlatemp** [comment]
![7UUV](https://user-images.githubusercontent.com/30070303/121806084-f39d8900-cc80-11eb-856c-8d439f812c21.png)

**Comment by Karlatemp** [comment]
https://github.com/project-mirai/mirai-api-http/issues/362
