### ISSUE TITLE
好友聊天上传图片概率出现上传时间非常长的情况？

### ISSUE THREAD

**Issue by Karlatemp** [mamoe/mirai#1334]
如下图所示，4次上传图片都是向好友的，但是很怪的是概率出现上传时间超长的情况，而在群聊似乎不会出现这种情况。

![img](https://mirai.mamoe.net/assets/uploads/files/1623582766541-010400ad-3421-4585-9099-c3efe2a558af-pqhec-ag6ic9-xyo8oey5u.png) 
再来张群聊和好友对比的图（
![639ccc8d-e771-4102-9160-11dab2330e23-image.png](https://mirai.mamoe.net/assets/uploads/files/1623583020790-639ccc8d-e771-4102-9160-11dab2330e23-image.png) 
计时代码如下：
![3384fc38-96f5-471b-a5cd-f451220fbda0-image.png](https://mirai.mamoe.net/assets/uploads/files/1623583111592-3384fc38-96f5-471b-a5cd-f451220fbda0-image.png) 
`uploadImage`调用的是`Contact`的`uploadImage`

Mirai版本2.6.6

**Originally posted by @Rosemoe on https://mirai.mamoe.net/topic/299/**

**Comment by sandtechnology** [comment]
我怎么觉得是图片已有缓存的原因 建议上网络日志

**Comment by Rosemoe** [comment]
> 我怎么觉得是图片已有缓存的原因 建议上网络日志

~~我不知道如何获取网路日志~~

**Comment by Him188** [comment]
> > 我怎么觉得是图片已有缓存的原因 建议上网络日志
> 
> ~我不知道如何获取网路日志~

logs 目录

**Comment by Karlatemp** [comment]
如果是 `mirai-console`, 位于 `bots/**/logs`

**Comment by Rosemoe** [comment]
控制台的输出：[console-output.txt](https://github.com/mamoe/mirai/files/6643888/console-output.txt)
Logs文件：[logs.log](https://github.com/mamoe/mirai/files/6643889/logs.log)
只保留了这一次起动的logs

**Comment by Karlatemp** [comment]
> For mamoe:
> `[Highway] Uploading private image to [Any Server], size=[-] failed: java.lang.IllegalStateException: highway transfer failed, error 70`
