### ISSUE TITLE
有时出现消息无法发送的现象

### ISSUE THREAD

**Issue by DearAhri520** [mamoe/mirai#1341]
QQ机器人运行一段时间后，会出现消息无法发送的情况，而日志显示已发送。

#### 版本
2.6.6

**Comment by DearAhri520** [comment]
重启仍然无效，删除cache文件之后，重启能发送消息。

**Comment by Him188** [comment]
试试 https://github.com/mamoe/mirai/blob/dev/docs/Bots.md#%E5%88%87%E6%8D%A2%E5%BF%83%E8%B7%B3%E7%AD%96%E7%95%A5

**Comment by DearAhri520** [comment]
谢谢大佬
