### ISSUE TITLE
服务器Tmcat 验证码怎么输入

### ISSUE THREAD

**Issue by Xiaolangs** [mamoe/mirai#1342]
本地开发登录可以正常。 但是不知道怎么在服务器上输入验证码

```

```

#### 版本
- mirai-core: `2.6.5`

**Comment by Karlatemp** [comment]
取决于你设置的login solver

**Comment by Xiaolangs** [comment]
> 取决于你设置的login solver

那应该怎么设置

**Comment by zhaodice** [comment]
可以本地登陆然后把device.json传上去。

**Comment by Him188** [comment]
https://github.com/mamoe/mirai/blob/dev/docs/Bots.md#%E8%A6%86%E7%9B%96%E7%99%BB%E5%BD%95%E8%A7%A3%E5%86%B3%E5%99%A8

**Comment by Him188** [comment]
默认是走标准输入。可以覆盖 LoginSolver （上面链接）来修改行为。
将在 #1344 增加对默认行为的描述
