### ISSUE TITLE
android studio的java demo有没有呢看到都是kotlin

### ISSUE THREAD

**Issue by tghjnjvg** [mamoe/mirai#135]
android studio的java demo有没有呢 看到的都是kotlin

**Comment by Him188** [comment]
[mirai-demos](https://github.com/mamoe/mirai-demos)

mirai-demo-java

**Comment by tghjnjvg** [comment]
是那个mirai-demo-java吗 mirai-demo-android是kotlin的

**Comment by Him188** [comment]
看java的demo是一样的，在Android上面一样的用法

**Comment by tghjnjvg** [comment]
好的 谢谢大佬 我去试试

**Comment by Him188** [comment]
没有问题我就先关闭 issue 了
