### ISSUE TITLE
bot 入群之后 BotJoinGroupEvent 会被触发两次

### ISSUE THREAD

**Issue by Him188** [mamoe/mirai#1354]
在 2.7-M1 (从2.6开始便也已经遇到) bot入群之后 BotJoinGroupEvent 会被触发两次。

_Originally posted by @yhluk in https://github.com/mamoe/mirai/issues/1058#issuecomment-864887543_

**Comment by sandtechnology** [comment]
没有环境信息 怀疑和之前相关的 native 的问题 @yhluk

**Comment by sandtechnology** [comment]
此问题未复现（dev分支）

**Comment by Him188** [comment]
有可能是 #1369 修复了
