### ISSUE TITLE
FriendNickChangedEvent 内容异常

### ISSUE THREAD

**Issue by ryoii** [mamoe/mirai#1356]
FriendNickChangedEvent 事件内容异常

```
{
  "type": "FriendNickChangedEvent",
  "friend": {
    "id": xxx,
    "nickname": "破晓",
    "remark": "破晓"
  },
  "from": "破晓1",
  "to": "破晓1"
}
```

实现代码：

```
is FriendNickChangedEvent -> FriendNickChangedEventDTO(QQDTO(friend), from, to)
```

可见 contact 的昵称已经变化，但 `from` 和 `to` 的值是相同的

**Comment by Karlatemp** [comment]
Caused by `OnlinePushReqPush`

**Comment by sandtechnology** [comment]
Bug位置
https://github.com/mamoe/mirai/blob/103dad3f6999974593a7c4c3de9e8389f114844c/mirai-core/src/commonMain/kotlin/network/notice/priv/FriendNoticeProcessor.kt#L202-L206
