### ISSUE TITLE
bot账号为svip的情况下 无法发送超过2分10秒的语音且音质奇差无比

### ISSUE THREAD

**Issue by djkcyl** [mamoe/mirai#1367]
https://github.com/project-mirai/mirai-api-http/issues/376

详细信息在这个issues里有了。

mirai各组件的版本是2.6.6

发送消息的sdk是[Graia](https://github.com/GraiaProject/Application)链接1.10.1版本的http api

目前遇到的问题是发送长语音直接会失效。
其次就是短语音不管通过什么办法发出来的音质都很差

**Comment by sandtechnology** [comment]
不清楚你压制语音文件的方式 请提供源文件

**Comment by AdoptOSS** [comment]
按照腾讯规则，长语音需要走VIP的专用通道，发出来的语音消息有长语音标识（至少老版本的QQ有）

**Comment by djkcyl** [comment]
> 不清楚你压制语音文件的方式 请提供源文件

压制语音用的是python的一个库https://github.com/I-love-study/graiax-silkcoder
原音频就是从网易云音乐下载的音频文件，192kbps，用FFmpeg转换成wav的
这里是代码部分
![image](https://user-images.githubusercontent.com/59153990/123413911-e1f3a400-d5e5-11eb-9558-a6c67c9a0c46.png)

**Comment by djkcyl** [comment]
> 按照腾讯规则，长语音需要走VIP的专用通道，发出来的语音消息有长语音标识（至少老版本的QQ有）

如果是2分钟的语音发出来是有长语音标识的，但3分钟就直接变成叹号了
![image](https://user-images.githubusercontent.com/59153990/123414175-254e1280-d5e6-11eb-9af7-32512ec1ad13.png)

**Comment by djkcyl** [comment]
> 不清楚你压制语音文件的方式 请提供源文件

因为我不太清楚python要怎么直接吧mp3或者wav压成高质量的silk，所以就用了这个库

**Comment by sandtechnology** [comment]
很可能是因为压制过程导致的 建议自行试试用 https://github.com/kn007/silk-v3-decoder 提供的encoder 输入单声道24000Hz的pcm文件并指名兼容腾讯格式后直接发送看看情况

**Comment by djkcyl** [comment]
![image](https://user-images.githubusercontent.com/59153990/123422774-423c1300-d5f1-11eb-8c15-d6bfea5ea117.png)
![image](https://user-images.githubusercontent.com/59153990/123422872-67c91c80-d5f1-11eb-8cc7-548ef420bd69.png)

![image](https://user-images.githubusercontent.com/59153990/123422897-6e579400-d5f1-11eb-8e4f-ba6fb41e0fba.png)
![image](https://user-images.githubusercontent.com/59153990/123423017-97782480-d5f1-11eb-8320-79a720bccda1.png)

**Comment by AdoptOSS** [comment]
请用WAV、MP3等正常格式，这个转换工具不需要输入PCM数据

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by djkcyl** [comment]
> 请用WAV、MP3等正常格式，这个转换工具不需要输入PCM数据 Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

草，原来如此，我怎么说我转成PCM反而用不了了

**Comment by djkcyl** [comment]
仍然音质很差
![image](https://user-images.githubusercontent.com/59153990/123424842-f6d73400-d5f3-11eb-855d-a97db5172954.png)
度盘链接https://pan.baidu.com/s/1FlcbX813Gsw2XPot53Xd0Q 
提取码 u4dr
不知道那个环节出问题了

**Comment by djkcyl** [comment]
使用那个python的库 https://github.com/I-love-study/graiax-silkcoder 转出来的效果和上面的 https://github.com/kn007/silk-v3-decoder 出来的效果是一模一样的，一旦用graia通过http api发到群里音质就裂了

**Comment by Karlatemp** [comment]
![image](https://user-images.githubusercontent.com/30070303/123499687-0f366580-d66b-11eb-8d3e-7d296853fd08.png)

分别测试了普通账户和svip账户，都是正常的

**Comment by Karlatemp** [comment]
请问你是如何发送语音的（发送语音的详细步骤，调用了什么API）

**Comment by AdoptOSS** [comment]
mirai-api-http中并没有什么设置语音上传方式的奇技淫巧，理论上只要能发出来，上传都没什么问题

**Comment by Karlatemp** [comment]
经检查，确定为 mirai-http-api 处理语音相关消息的时候有问题，请前往 mirai-http-api 发起 issue
