### ISSUE TITLE
机器人启动后，如果机器人账号被加到新群，机器人不能更新群信息

### ISSUE THREAD

**Issue by xiaowang123** [mamoe/mirai#1375]
使用场景：拉机器人账号到新群，但是机器人不会更新群信息（reloadGroupList）
只能通过重启才能更新

**Comment by Karlatemp** [comment]
请使用 GitHub 模板并且发起错误报告的时候不要选择 *特性申请* 模板

**Comment by xiaowang123** [comment]
用bug模板？

**Comment by sandtechnology** [comment]
> 
> 
> 用bug模板？

请使用bug模板修改本issue

**Comment by xiaowang123** [comment]
好的，感谢~
