### ISSUE TITLE
机器人启动后，如果机器人账号被加到新群，机器人不能更新群信息

### ISSUE THREAD

**Issue by xiaowang123** [mamoe/mirai#1376]
使用场景：拉机器人账号到新群，但是机器人不会更新群信息（reloadGroupList）
只能通过重启才能更新
java.util.NoSuchElementException: group 431450712 at net.mamoe.mirai.Bot.getGroupOrFail(Bot.kt:152)

```

```

#### 版本
- mirai-core: `2.6.7` 

#### 网络日志

```

```

**Comment by Him188** [comment]
请提供完整日志

**Comment by sandtechnology** [comment]
此问题未复现 请确保使用的是2.7.0

**Comment by Him188** [comment]
应该是uin/code的问题
