### ISSUE TITLE
考虑设计增加使用一次后就自动 `close` 的 `ExternalResource`

### ISSUE THREAD

**Issue by Him188** [mamoe/mirai#1377]
ER 很多时候只会使用一次, 而用户很容易忘记关闭, 虽然即使增加了自动关闭也需要用户指定参数 `autoClose = true`.

可能的方案: 为现有 `ER` 构造函数添加参数 `autoClose: Boolean = false`

**Comment by AdoptOSS** [comment]
建议修改`toExternalResource`名称，这个名字实在不像是要`close`的那种

**Comment by sandtechnology** [comment]
>toReusableExternalResource
>toTempExternalResource

可以分成这两个？

**Comment by AdoptOSS** [comment]
其实我更偏向于引入`useAsExternalResource(...lambda)`，让kotlin变量作用域和资源实际生命周期保持一致

**Comment by Karlatemp** [comment]
> 其实我更偏向于引入`useAsExternalResource(...lambda)`，让kotlin变量作用域和资源实际生命周期保持一致

`ExternalResource` 实现 `Closeable`, 是能直接 `res.use {}` 的
