### ISSUE TITLE
关于mirai形象图的询问

### ISSUE THREAD

**Issue by 2wFv** [mamoe/mirai#1379]
根据贵项目首页

> 在未经过允许的情况下，任何人都不可以使用形象图和图标

我想询问一下，对着mirai娘手冲是否属于“使用形象图”的范畴？

如果属于该范畴，我该如何取得使用形象图的允许？

**Comment by aimerneige** [comment]
好耶，冲他妈的

**Comment by nidbCN** [comment]
我不知道mirai娘，但是你可以对gc酱冲

**Comment by Miuzarte** [comment]
> 我不知道mirai娘，但是你可以对gc酱冲

我单推有村路美

**Comment by cardinalsystem256** [comment]
我不知道mirai娘，但是你可以对群友女装冲
