### ISSUE TITLE
请问一下最新的编译好的jar仓库在哪里

### ISSUE THREAD

**Issue by dragon0629** [mamoe/mirai#1394]
RT之前的仓库地址好像失效了，
https://dl.bintray.com/him188moe/mirai/net/mamoe/ 
forbidden了
几个群里问了半天也没人知道。
请问目前最新的官方编译好的jar仓库地址在哪里呢？

**Comment by Him188** [comment]
maven central

**Comment by Him188** [comment]
https://repo.maven.apache.org/maven2/net/mamoe/

**Comment by dragon0629** [comment]
谢谢！
