### ISSUE TITLE
支持好友/群成员点赞功能

### ISSUE THREAD

**Issue by Erisu0014** [mamoe/mirai#1402]
mirai目前是否已经支持好友/群成员点赞功能呢？惭愧参考文档和message相关内容后没有找到。
用途：自动对已绑定点赞功能的好友/群成员每日自动点赞~

**Comment by sandtechnology** [comment]
RTFM, README.MD:
> 不会支持的协议
>     金钱相关，如点赞、收付款
>     敏感操作，如主动添加好友、主动加入群、主动邀请好友加群
>     安全相关，获取账号登录凭证(token，cookie等)
