### ISSUE TITLE
2.7-M2 群机器人权限获取错误

### ISSUE THREAD

**Issue by KadokawaR** [mamoe/mirai#1411]
一些依赖于检测机器人的群内权限的功能在升级至2.7-M2之后不能使用。在2.7-M1时一切正常。

使用`event.getGroup().getBotPermission()` 获得群内权限时，均返回MEMBER。已在多个群中使用不同的QQ号测试。

> 2021-07-12 13:08:52 V/Bot.(机器人ID): Event: GroupMessagePreSendEvent(target=Group(群ID), message=MEMBER)
> 2021-07-12 13:08:53 V/Bot.(机器人ID): Group(群ID) <- MEMBER
> 2021-07-12 13:08:53 V/Bot.(机器人ID): Event: GroupMessagePostSendEvent(target=Group(群ID), message=MEMBER, exception=null, receipt=net.mamoe.mirai.message.MessageReceipt@39a1977a)

插件运行期间授予机器人管理员权限，读取一切正常。但是重启之后依旧返回MEMBER。和#1192 不同的是，这个问题与年代无关。

- mirai-core: `2.7-M2` 
- bot-protocol: `ANDROID_PHONE`

**Comment by Karlatemp** [comment]
#1400
