### ISSUE TITLE
群消息被撤回时不会触发MessageRecallEvent

### ISSUE THREAD

**Issue by Hpero4** [mamoe/mirai#1418]
当群消息被撤回时不会触发MessageRecallEvent

#### 复现

1. bot在群内
2. 使用事件监听器尝试捕获
```
bot.eventChannel.subscribeAlways<Event>  // ...
// 或
GlobalEventChannel.subscribeAlways<Event>  // ...
```
3. 其他成员撤回消息, 发现事件未被捕获并且无日志输出.

#### 版本及相关选项选择

- mirai-core: `2.6.7` 
- bot-protocol: `ANDROID_PHONE` 及 `ANDROID_WATCH`均尝试

#### 网络日志

```
使用mirai-core且未输出相关日志.
```

#### 补充信息

- 当前版本在与bot私聊时MessageRecallEvent事件的工作一切正常.
- 该设计是有意为之吗? 我翻阅了releases但没有发现相关信息.
- 我曾在1.x的mirai中像我所说的一样使用它并且能够像预期工作.

**Comment by ReanRelay** [comment]
不可能不会触发，你自己有问题，我都触发的好好的！，此贴可以删了

**Comment by sandtechnology** [comment]
在2.7-M2中正常输出显示且使用ANDROID_PHONE协议，请检查

**Comment by Hpero4** [comment]
> 在2.7-M2中正常输出显示且使用ANDROID_PHONE协议，请检查

感谢您杰出的工作! 
经测试, 2.7-M2中使用ANDROID_PHONE协议不存在该问题. 54c3754
已解决. Issue close.
