### ISSUE TITLE
关于Bot的Logger的一些改进建议

### ISSUE THREAD

**Issue by khjxiaogu** [mamoe/mirai#1426]
1.、Bot在后台接收消息、事件和特殊数据包用的同一个logger，这就导致了无法单独设置出现哪种信息。   比如说有时候会只想看到机器人接收消息的记录，不想看到后台事件报告和一些数据包错误的信息，但是无法单独控制。是否可以做到配置部分消息是否输出来选择性的输出信息？
2、部分事件的输出过长。比如说消息发送事件会包含被发送的消息，当消息比较长的时候，会出现后台刷两次的情况（第一次是发送消息的提示，第二次是发送事件里面的消息内容），一些数据包接收事件会出现非常长的信息。是否可以做到比如控制一些log信息的最大长度来避免疯狂刷后台。

**Comment by AdoptOSS** [comment]
`logging`部分可以改进的东西非常多
比如基于`level`的筛选
比如`tag`和`filter`的支持（避免手动引入各种`property`来控制日志输出，采用统一的方式控制）
比如`lazy message`的优化
比如避免奇奇怪怪的`following`字段

**Comment by Him188** [comment]
@AdoptOSS Mirai 为了减少对 JVM 平台的依赖, 优先使用 Kotlin 多平台库并独立实现一套内置的 `MiraiLogger` 以支持基础日志功能. `MiraiLogger` 可对接到 log4j 等成熟日志框架来实现过滤等高级功能. 
`net.mamoe.mirai.utils.LoggerAdapters` 提供这样的转换, 也可以自行实现 `MiraiLogger` 并使用 `MiraiLogger.setDefaultLoggerCreator` 替代默认.

> 减少对 JVM 平台的依赖是为了将来能够借*稳定的* Kotlin MPP 支持 native, Node.js, 浏览器 JS 等目标平台

**Comment by Him188** [comment]
现在的计划:
- [ ] 2.7-RC 检查所有日志操作并考虑对接其他日志框架的支持
- [ ] 2.7.0 增加使用 slf4j, log4j 或 `java.util.logging.Logger` 接管日志系统的文档

**Comment by AdoptOSS** [comment]
> 可对接到 log4j 等成熟日志框架来实现过滤等高级功能.

主要是目前的`logging`缺少`tag`之类的语义，也没有把不同的子模块产生的日志输出到不同的`logging`（区分模块的方式很多时候是看string里的`XXX: `/`[YYY]`），很难方便地分类过滤

**Comment by Him188** [comment]
@AdoptOSS 你想要的可能是 `MiraiLogger.identity`

**Comment by AdoptOSS** [comment]
`identity`的分类根本不够，新网络层中引入了`subLogger`，理论上可以提供更详尽的分类，但目前的`subLogger`只具备添加`[xxx]`前缀的能力，并不能传递给最终的`logger`
我希望的是SLF4J里的`Marker`之类的类似物来提供更准确的分类

**Comment by Him188** [comment]
现在的日志架构确实有设计问题, 正考虑通过某种方式更换为 SLF4J

**Comment by AdoptOSS** [comment]
建议优化 packet send 的 log

```diff
- Send: friendlist.GetTroopMemberListReq(friendlist.GetTroopMemberListReq)
+ Send: friendlist.GetTroopMemberListReq
```

**Comment by Him188** [comment]
@AdoptOSS 这是需要一个 systemProp 才会打开的详细信息，属于期望情况。如果它默认就有则是一个 bug

**Comment by AdoptOSS** [comment]
@Him188 在没有 systemProp 的情况下也会这么输出
相关代码
https://github.com/mamoe/mirai/blob/490055042602baa3c7a2f4eb595da9c93190d21d/mirai-core/src/commonMain/kotlin/network/components/PacketLoggingStrategy.kt#L42-L45

https://github.com/mamoe/mirai/blob/5aae46218f05237862ac3e3adfed7b8d28d03a01/mirai-core/src/commonMain/kotlin/network/protocol/packet/OutgoingPacketAndroid.kt#L46

`commandName`和`name`常常具有相同的内容，所以输出时会出现两遍
