### ISSUE TITLE
希望MessageChainBuilder增加insert接口

### ISSUE THREAD

**Issue by SugarFatFree** [mamoe/mirai#1430]
希望能够仿照StringBuilder接口增加一个指定位置插入的方法，即便无法总中间插入，也希望能够增加从最前方位置增加，而不是只能从最后面增加

**Comment by Karlatemp** [comment]
`MessageChainBuilder` 实现 `java.util.List`, 可以直接 `add(0, elem)`

**Comment by SugarFatFree** [comment]
> `MessageChainBuilder` 实现 `java.util.List`, 可以直接 `add(0, elem)`

但是这样返回的就不是this了，不方便继续调用，还是希望可以增加一个函数

**Comment by Karlatemp** [comment]
> > `MessageChainBuilder` 实现 `java.util.List`, 可以直接 `add(0, elem)`
> 
> 但是这样返回的就不是this了，不方便继续调用，还是希望可以增加一个函数

根据你的描述得你在使用链式调用，
既然是链式调用为什么要往前加入内容，你可以直接在前面加append

**Comment by SugarFatFree** [comment]
> > > `MessageChainBuilder` 实现 `java.util.List`, 可以直接 `add(0, elem)`
> > 
> > 
> > 但是这样返回的就不是this了，不方便继续调用，还是希望可以增加一个函数
> 
> 根据你的描述得你在使用链式调用，
> 既然是链式调用为什么要往前加入内容，你可以直接在前面加append

因为我向前插入的有文本和表情，想要链式插入

**Comment by Karlatemp** [comment]
你可以在需要insert的地方直接append为什么必须要insert

**Comment by Karlatemp** [comment]
关闭此 issue, 因为以下原因

1. 你完全可以使用 `java.util.List.add(int index, )` 来达到目的
2. 按照 `想要链式插入`, 你完全可以在需要插入的地方写 `append` 而不是 `insert`, 链式调用中使用 `insert` 是不正确的
3. 你没有回答为什么必须要使用 `add` 而不是 `insert`, 我们认为已经有 `add` 了添加 `insert` 完全没有必要
