### ISSUE TITLE
无法接受到临时消息

### ISSUE THREAD

**Issue by LinHui88** [mamoe/mirai#1434]
未加好友的成员在群里向机器人发送临时消息时,mirai无法接受到
可以正常识别出好友信息,群信息,以及其他事件
无报错

#### 版本及相关选项选择

- mirai-core: `2.7.M2` 
- bot-protocol: `ANDROID_PHONE` 
- api:2.7.M2

#### 网络日志

```
[2021-07-27.log](https://github.com/mamoe/mirai/files/6882639/2021-07-27.log)

```

**Comment by Karlatemp** [comment]
#1410
