### ISSUE TITLE
登录失败，bot.isOnline()返回true

### ISSUE THREAD

**Issue by SugarFatFree** [mamoe/mirai#1438]
登录时，通过滑块验证码，然后返回“禁止登录，更换网络环境或者常用设备”这个提示后，跳过异常，执行bot.isOnline()，执行的结果为true。

mirai-core: 2.7-M2
bot-protocol: ANDROID_PHONE

**Comment by Karlatemp** [comment]
能添加 JVM 参数 `-Dmirai.debug.network.packet.logger=true -Dmirai.debug.network.state.observer.logging=true` 后提供一下日志吗
