### ISSUE TITLE
希望Bot的Logger能够显示到毫秒级时间

### ISSUE THREAD

**Issue by SugarFatFree** [mamoe/mirai#1440]
现在打印出来的是秒，输出毫秒能够更精确的查看自身程序对消息的处理时间，以便更直观的知道功能的执行效率

**Comment by Karlatemp** [comment]
可以自行实现 `MiraiLogger` 并应用

**Comment by Him188** [comment]
参考 https://github.com/mamoe/mirai/tree/dev/logging ，问题是否可以解决？

**Comment by Karlatemp** [comment]
long time no reply
