### ISSUE TITLE
2.7-M2版本发送图片后，手机端能看到图片而电脑端发出来后却看不到图片

### ISSUE THREAD

**Issue by Nekoer** [mamoe/mirai#1441]
2.7-M2版本发送图片后，手机端能看到图片而电脑端发出来后却看不到图片

#### 复现

 
- ImageUtil.getImageFromPixiv(large)?.toByteArray()?.toExternalResource()?.let { event.subject.sendImage(it) }
- Image(id)
- ImageUtil.getImageFromPixiv(large)?.toByteArray()?.toExternalResource()!!.sendAsImageTo(event.group)
好几种图片发送方式都试了

#### 版本及相关选项选择

- mirai-core: `2.7-M2` 
- bot-protocol: `ANDROID_PHONE` 

#### 网络日志

```
[0m2021-07-29 12:29:58 V/Net 3123930141: Send: ImgStore.GroupPicUp(ImgStore.GroupPicUp)[0m
[0m2021-07-29 12:29:58 V/Net 3123930141: Recv: ImgStore.GroupPicUp[0m
[0m2021-07-29 12:29:58 V/Net 3123930141: [Highway] Uploading group image to 203.205.234.15:443, size=120.74 KiB[0m
[0m2021-07-29 12:29:59 V/Net 3123930141: [Highway] Uploading group image: succeed at 210 KiB/s[0m
[0m2021-07-29 12:29:59 V/Net 3123930141: Send: MessageSvc.PbSendMsg(MessageSvc.PbSendMsg)[0m
[0m2021-07-29 12:29:59 V/Net 3123930141: Recv: MessageSvc.PbSendMsg[0m
[0m2021-07-29 12:29:59 V/Net 3123930141: Send: MessageSvc.PbSendMsg(MessageSvc.PbSendMsg)[0m
[0m2021-07-29 12:29:59 V/Net 3123930141: Recv: MessageSvc.PbSendMsg[0m
```

##### PC端
![~5Z4DSXHL09(GVUCV0GYVAF](https://user-images.githubusercontent.com/32485369/127432590-adeb1800-64d3-4883-910f-56b4acf92f62.png)

##### 手机端
![IMG_20210729_123835](https://user-images.githubusercontent.com/32485369/127432607-3dcce5a5-562c-4537-87ca-ab304730c1c5.jpg)

**Comment by Karlatemp** [comment]
提供图片源文件

**Comment by Nekoer** [comment]
> 提供图片源文件
那张要社死了，这张也是一样发不出去，不如说好多从pixiv读取下来的图片pc端都看不到

![59580629_p0](https://user-images.githubusercontent.com/32485369/127433237-7dfc12cf-d40a-4bd6-824a-f4493f4f3610.jpg)

**Comment by Karlatemp** [comment]
It is ok for sending. Please verify file data.
```
General
Complete name                  : F:\Temp\mirai\127433237-7dfc12cf-d40a-4bd6-824a-f4493f4f3610.jpg
Format                         : JPEG
File size                      : 702 KiB

Image
Format                         : JPEG
Width                          : 1 200 pixels
Height                         : 854 pixels
Color space                    : YUV
Chroma subsampling             : 4:4:4
Bit depth                      : 8 bits
Compression mode               : Lossy
Stream size                    : 702 KiB (100%)


```

**Comment by Karlatemp** [comment]
请使用 zip 等包装一下图片以确保图片不会被github服务器二次处理
