### ISSUE TITLE
QQ滑动验证码在电脑浏览器验证后输入ticket无法登录

### ISSUE THREAD

**Issue by willhuo** [mamoe/mirai#1444]
用mcl-installer-1.0.3-windows-amd64.exe进行初始化
运行mcl.cmd启动程序
输入账号密码后，提示滑动验证码，复制滑动验证码连接到浏览器，然后进行验证
验证后，复制得到的ticket，提示无法登录

![登录出现滑动验证码](https://user-images.githubusercontent.com/15681218/127617188-07824a46-2d00-4462-9afd-dae424359052.png)
![ticket](https://user-images.githubusercontent.com/15681218/127617201-f603e815-8731-40d9-9c7d-c361475824dd.png)
![登录失败](https://user-images.githubusercontent.com/15681218/127617394-2b30d6fc-3931-49e2-8277-8b3cb4a19e10.png)

```

```

#### 版本及相关选项选择

- mirai-core: `2.7` 
- bot-protocol: `ANDROID_PHONE` 
协议没有填写，应该是默认的安卓协议

#### 网络日志

```

```

**Comment by Karlatemp** [comment]
手机验证?

**Comment by willhuo** [comment]
> 手机验证?

用的电脑

**Comment by Karlatemp** [comment]
使用手机

**Comment by willhuo** [comment]
> 使用手机

在大佬的带领下，我终于搞定了登录。
