### ISSUE TITLE
机器人管理员权限获取错误

### ISSUE THREAD

**Issue by SugarFatFree** [mamoe/mirai#1449]
机器人确定为管理员，但是权限获取是普通用户

<img width="1103" alt="F392C288-B0A4-4BCC-9085-6909AFC8E8E8" src="https://user-images.githubusercontent.com/30424828/127726117-a794ca61-d73d-4f61-8713-9f1bf7757471.png">

- mirai-core: `2.7-M2` 
- bot-protocol: `ANDROID_PHONE`

**Comment by Karlatemp** [comment]
Duplicated with #1400
