### ISSUE TITLE
JCE序列化: 所有元素均 optional 的嵌套 JceStruct 没有被正确认为是 optional

### ISSUE THREAD

**Issue by pyg2007** [mamoe/mirai#145]
## 问题

报错如下：原因未知
[anbug.log](https://github.com/mamoe/mirai/files/4343426/anbug.log)

## 如何复现

一.启动mirai无头客户端Pure并登陆
二.开始重复获取某信息(bug点)

**Comment by LinHeLurking** [comment]
出现类似问题, log:  
https://gist.github.com/LinHeLurking/d33430c829bfee6fb82b0322bc14c724
