### ISSUE TITLE
读取部分取文件的时间过久，且没有时间标识

### ISSUE THREAD

**Issue by vikieow** [mamoe/mirai#1460]
读取部分群的群文件的接口时长长达5分钟左右，能否优化呢，可用性有点低，提供limit筛选
同时群文件接口没有文件上传的时间标识

**Comment by Him188** [comment]
受服务器查询接口限制，现在的速度已经很快了。 计划在 #1328 进一步提升速度

**Comment by vikieow** [comment]
> 受服务器查询接口限制，现在的速度已经很快了。 计划在 #1328 进一步提升速度

有些群确实非常快，
因为现在的接口是一次拿完所有的群文件，对于一些文件比较多的群来说，你依次遍历接口的时间成本就太高了
建议提供翻页接口，提供页数或者是limit字段，这样就能快速拿到最新的群文件
同时也希望群文件提取的时候，带上文件上传的时间戳
还有这个文件上传者的id

**Comment by Him188** [comment]
@vikieow RemoteFile 里有个 stream 就是翻页地拿的

**Comment by vikieow** [comment]
> @vikieow RemoteFile 里有个 stream 就是翻页地拿的

在用户手册的API里面好像没看到RemoteFile

**Comment by Him188** [comment]
@vikieow 具体是哪一个文档?

**Comment by vikieow** [comment]
> @vikieow 具体是哪一个文档?

https://github.com/project-mirai/mirai-api-http/blob/master/docs/adapter/HttpAdapter.md
我是用的http格式的插件获取信息
里面没看到remoteFile这个接口

**Comment by Him188** [comment]
@vikieow 请在 https://github.com/project-mirai/mirai-api-http/issues 发起 issue, mirai 仓库仅管理 mirai-core 的问题
