### ISSUE TITLE
无法完成滑块验证怎么办？

### ISSUE THREAD

**Issue by Keafmd** [mamoe/mirai#1463]
irai 无法完成滑块验证. 使用协议 ANDROID_PHONE 强制要求滑块验证,

**Comment by AdoptOSS** [comment]
Typo: `Mirai` not `irai`

Mirai 支持进行滑块验证，请具体描述您在尝试进行滑块验证的过程中遇到的问题

**Comment by Him188** [comment]
尝试 2.7-M2

**Comment by Keafmd** [comment]
> Typo: `Mirai` not `irai`
> 
> Mirai 支持进行滑块验证，请具体描述您在尝试进行滑块验证的过程中遇到的问题

我使用的是mirai-hello-world这个测试项目

**Comment by Keafmd** [comment]
> 尝试 2.7-M2

我使用的是mirai-hello-world这个测试项目，在使用时出现的情况

**Comment by Keafmd** [comment]
ok，已经解决了
