### ISSUE TITLE
docs.mirai.mamoe.net页面的一个适配问题

### ISSUE THREAD

**Issue by Alceatraz** [mamoe/mirai#1478]
这也太学姐了吧喂(划掉

![QQ截图20210816093949](https://user-images.githubusercontent.com/8266702/129500651-8c76b806-f3fc-4636-b184-08748204b234.png)
![QQ截图20210816094133](https://user-images.githubusercontent.com/8266702/129500760-33a07754-1994-4761-8f5a-814899fa8071.png)

**Comment by Karlatemp** [comment]
~~好耶是学姐~~
