### ISSUE TITLE
groupUin和groupCode互转函数的问题

### ISSUE THREAD

**Issue by takayama-lily** [mamoe/mirai#1479]
大多数场合互转都是正确的，但是我这有个群互转失败了groupUin=2613834107，groupCode=348834107(群号)
似乎中间缺了一个区间，但不知道具体范围是如何确定的，求函数作者指点
https://github.com/mamoe/mirai/blob/a34c11f2394952c770f2d3be2778cfd4f37a139c/mirai-core-api/src/commonMain/kotlin/IMirai.kt#L120-L154

**Comment by takayama-lily** [comment]
不PR了，说一下吧，经高人(@TheSnowfield )指点研究下来中间少了一个范围
```kotlin
in 335..386 -> left += 2600 - 335
```
另外335和336不确定，因为没找到这两个号码开头的群

**Comment by TheSnowfield** [comment]
> 不PR了，说一下吧，经高人(@TheSnowfield )指点研究下来中间少了一个范围
> 
> ```kotlin
> in 335..386 -> left += 2600 - 335
> ```
> 
> 另外335和336不确定，因为没找到这两个号码开头的群

可以做一个`Map<code, uin>` 需要的时候取出
用code2uin有几率出现很迷惑问题, 不如趁早向石山妥协 \_(:3)z)\_

**Comment by Him188** [comment]
这个算法是 mirai 早期一个群友贡献的, 他的昵称好像是 kar98k. 我也不清楚这个算法是什么原理

> @TheSnowfield 可以做一个Map<code, uin> 需要的时候取出

确实, 但这有可能会导致一些不稳定, 之后会考虑实现, 实现时也会考虑在内部维护这个 map 而不在 `IMirai.calculate...` 实现.
