### ISSUE TITLE
考虑制作Mirai-Core的JavaDocs吗？

### ISSUE THREAD

**Issue by jiajiaxd** [mamoe/mirai#1482]
Mirai 的开发文档内容实在过少。即使存在想要找的内容，也无法在短时间内找到。
如果可以制作一个像[https://hub.spigotmc.org/javadocs/bukkit/index.html](https://hub.spigotmc.org/javadocs/bukkit/index.html)此地址的javadocs，对每一个类、方法进行解释，就更方便开发者了。

**Comment by Itsusinn** [comment]
https://project-mirai.github.io/mirai-doc/mirai-core-api/
But outdated.

**Comment by bingling-sama** [comment]
实际上 Mirai 源码中的注释远比开发文档详细

**Comment by Him188** [comment]
当时是因为 Kotlin 的文档生成器没适配新编译器或有某个 bug 导致一直无法生成, 就关掉了自动文档部署. 之后会恢复
