### ISSUE TITLE
电脑端回复消息无法正常识别

### ISSUE THREAD

**Issue by Maklith** [mamoe/mirai#1485]
在电脑端回复一条消息得到的Code为
[mirai:source:[45525],[-847997792]][mirai:quote:[45516],[1491920016]]<消息内容>
此时mirai无法识别消息为引用消息，但如果仅仅引用而不输入内容得到的code
[mirai:source:[45580],[63524598]][mirai:quote:[45576],[1893774035]][mirai:at:******]
此时可以正常识别
但如果是手机端的引用消息无论有没有内容都能识别(结尾有AT消息)
[mirai:source:[45526],[199084057]][mirai:quote:[45516],[1491920016]][mirai:at:*****]
使用的代码为：QuoteReply quote = event.getMessage().get(QuoteReply.Key);

```

```

#### 版本及相关选项选择

- mirai-core: `2.6.7和2.7-RC-dev-3` 
- bot-protocol: `ANDROID_PHONE` 

#### 网络日志

```

```

**Comment by Karlatemp** [comment]
请清晰描述你的问题，包括（无法识别为引用消息）具体为如何无法识别

**Comment by Maklith** [comment]
如果电脑引用，输入内容之后，QQ自动添加的at是无法识别的，导致引用无法识别？，但如果在QQ自动添加的at后面再添加一个at ，mirai就能识别这个引用消息

**Comment by Maklith** [comment]
手机回复的效果，能够正常识别
![-7f2568fd1e9af9b5.png](https://user-images.githubusercontent.com/42534870/129996118-ad222a7d-9b04-44fe-a744-1489a0a47385.png)
电脑TIM回复的效果，用的手机截屏而已
![Screenshot_20210819_100752_com.tencent.mobileqq.png](https://user-images.githubusercontent.com/42534870/129996274-17085bc3-5e7f-4a40-ac4d-c94e7e78f75d.png)
![fa3dcf66390c361.png](https://user-images.githubusercontent.com/42534870/129996285-abf0b527-c84a-4bc5-b7fa-bfe42ba6e78c.png)
但如果手动给一个at，mirai又能正常识别
![Screenshot_20210819_100925_com.tencent.mobileqq.png](https://user-images.githubusercontent.com/42534870/129996366-babe3c19-c847-49cb-a637-e18a870317b6.png)
![19d259e1deac39aa.png](https://user-images.githubusercontent.com/42534870/129996375-fbda6fa9-31aa-4cd6-b38a-c04c030618e9.png)

**Comment by Maklith** [comment]
> 请清晰描述你的问题，包括（无法识别为引用消息）具体为如何无法识别

麻烦看一下谢了

**Comment by Karlatemp** [comment]
无法复现请提供你的完整处理代码

**Comment by Karlatemp** [comment]
to long no reply
