### ISSUE TITLE
新特性申请：获取QQ用户头像

### ISSUE THREAD

**Issue by qiu-noname** [mamoe/mirai#1488]
获取QQ用户头像，用于生成群内活动图片

**Comment by Karlatemp** [comment]
https://github.com/mamoe/mirai/blob/fc8fd7001494b6c9f0afcad3efdff8c3f9d5334a/mirai-core-api/src/commonMain/kotlin/contact/ContactOrBot.kt#L37-L41

**Comment by qiu-noname** [comment]
好的，请把这个特性添加到文档吧
