### ISSUE TITLE
有考虑为mirai也开放获取群成员 性别/年龄 的API吗

### ISSUE THREAD

**Issue by azmiao** [mamoe/mirai#1489]
看了readme，里面说mirai不支持获取群成员性别年龄等，但在写插件的时候我需要用到，现在就很痛苦23333，又不想再换gocq了，所以希望可以支持下

**Comment by Him188** [comment]
![image](https://user-images.githubusercontent.com/12100985/130345600-899fe98d-54a0-4f3b-97f6-66e91864cd7d.png)

```kotlin

/**
 * 用户详细资料
 *
 * @see User.queryProfile
 * @suppress 使用这个接口是稳定的，但继承不稳定。将来可能会有新的属性添加。
 * @since 2.1
 */
@NotStableForInheritance
public interface UserProfile {
    public val nickname: String
    public val email: String
    public val age: Int
    public val qLevel: Int
    public val sex: Sex

    /**
     * 个性签名
     */
    public val sign: String

    public enum class Sex {
        MALE,
        FEMALE,

        /** 保密 */
        UNKNOWN;
    }
}

```

**Comment by Him188** [comment]
> 看了readme，里面说mirai不支持获取群成员性别年龄等

不过这个是在哪看到的? 文档可能需要更新

**Comment by azmiao** [comment]
> > 看了readme，里面说mirai不支持获取群成员性别年龄等
> 
> 不过这个是在哪看到的? 文档可能需要更新

这个，https://github.com/yyuueexxiinngg/onebot-kotlin
额，懂了，所以是他那边没有跟进这里的更新是嘛。昨晚有群友跟我说Mirai本身就不支持这几个，然后就来提issue了2333
