### ISSUE TITLE
bot部分群没有加载

### ISSUE THREAD

**Issue by JustOneSummer** [mamoe/mirai#1496]
bot有部分群无法加载，在PC和iPad上是可以看到那个群的。但是我用bot发送消息时缺说那个群不存在，而且也收不到那个群的消息

![image](https://user-images.githubusercontent.com/28168503/130984038-59ae6f58-ccb8-4f21-a153-c07580545e6f.png)

![image](https://user-images.githubusercontent.com/28168503/130984112-115fdbd8-4647-4687-9701-707db4e7fc06.png)

![image](https://user-images.githubusercontent.com/28168503/130984241-839722ef-af9f-4eb6-97a8-ffcf54e97179.png)
好友和群列表缓存是禁用的
我这边有时候重启是可以解决这个问题,重启解决不行那就是退群然后重新加才会恢复这个问题
控制台没有任何相关日志 启动时的日志没有记录 抛出的消息链太长了

```

```

#### 版本及相关选项选择

- mirai-core: `2.7.0-RC` 
- bot-protocol: `ANDROID_PHONE` 

#### 网络日志

```

```

**Comment by Karlatemp** [comment]
Duplicate of #578
