### ISSUE TITLE
StatSvc.ReqMSFOffline 问题

### ISSUE THREAD

**Issue by Sincky** [mamoe/mirai#150]
## 问题

StatSvc.ReqMSFOffline 出现后，收不到消息，但是心跳还在

![image](https://user-images.githubusercontent.com/30948192/77086665-094fde80-6a3d-11ea-9f61-e2f45fdbc12c.png)

**Comment by Him188** [comment]
是在什么情况下会收到 `StatSvc.ReqMSFOffline`?
