### ISSUE TITLE
新入群群员的消息接收不到

### ISSUE THREAD

**Issue by 4o4E** [mamoe/mirai#1501]
1. 有个新加进群的成员
2. 加群申请接收到了,并且是bot同意的
3. 但是没有接收到加群event,后续发的消息也没有接收到
4. 重启之后能正常接收消息

```
只收到了MemberJoinRequestEvent的trace日志
没有收到MemberJoinEvent的trace日志
其他都是不相关的日志（其他群的消息）
```

#### 复现
1. 有个新加进群的成员
2. 加群申请接收到了,并且是bot同意的
3. 但是没有接收到MemberJoinEvent,后续发的消息也没有接收到
4. 重启之后能正常接收消息
5. 之后遇到其他加群的成员是正常的,能接收到消息

#### 版本及相关选项选择

- net.mamoe:mirai-core-api: `2.7-RC`
- net.mamoe:mirai-core: `2.7-RC`
- bot-protocol: `ANDROID_PAD`

#### 网络日志

```
抱歉，我设置了noNetworkLog();
所以没有网络日志
```

**Comment by sandtechnology** [comment]
For Dev: 已知 `syncMessageSvc` 有概率无法正常同步历史信息，这应该与成员信息未及时同步有关

**Comment by Him188** [comment]
试试 2.8.0-M1?

**Comment by 4o4E** [comment]
> 试试 2.8.0-M1?

之前出现过，用的就是2.8.0-M1
#1582

**Comment by Him188** [comment]
经测试, 2.9.0-RC 可以接收

这相关代码应该在 2.8.0-M1 起就没有修改过
