### ISSUE TITLE
MessageChainBuilder使用add方法直接添加string之后size没有变化

### ISSUE THREAD

**Issue by Samarium150** [mamoe/mirai#1511]
版本：`2.7.0`
复现代码：
```kotlin
object Command: SimpleCommand(
    Plugin, "test"
) {
    @Suppress("unused")
    @Handler
    suspend fun CommandSender.test() {
        val builder = MessageChainBuilder()
        for (i in 0..3)
            builder.add(i.toString())
        Plugin.logger.info("builder size: " + builder.size.toString())
        sendMessage(builder.asMessageChain())
    }
}
```
在命令行测试的结果：
```
> test
2021-08-30 19:13:09 I/org.example.plugin: builder size: 0
0123
```
若改为`builder.add(PlainText(i.toString()))`，则size正常

**Comment by Karlatemp** [comment]
`fun add(String)` 会将 String 放入内部缓冲区，还未放入内部的元素数组中

**Comment by Samarium150** [comment]
也就是说应该用append而不是add吗

**Comment by Him188** [comment]
为什么要在意 size？有缓存是更好的行为

**Comment by Samarium150** [comment]
也不是那么在意，只是在实际使用的时候加了几个string后，想用removeAt和lastIndex去掉几个的时候报了错

**Comment by Him188** [comment]
> 也不是那么在意，只是在实际使用的时候加了几个string后，想用removeAt和lastIndex去掉几个的时候报了错

那样的话就先手动包装 `PlainText` 再添加吧

在发送消息时还是会将连续的 `PlainText` 合并

**Comment by Samarium150** [comment]
> > 也不是那么在意，只是在实际使用的时候加了几个string后，想用removeAt和lastIndex去掉几个的时候报了错
> 
> 那样的话就先手动包装 `PlainText` 再添加吧
> 
> 在发送消息时还是会将连续的 `PlainText` 合并

Ok，感谢
