### ISSUE TITLE
获取一个陌生人对象一直为null

### ISSUE THREAD

**Issue by SugarFatFree** [mamoe/mirai#1513]
无法获取到陌生人对象了，一直都是null

- mirai-core: `2.7.0` 
- bot-protocol: `ANDROID_PHONE`

**Comment by Him188** [comment]
提供相关代码以及环境

**Comment by Karlatemp** [comment]
使用手机QQ登录

设置 / 隐私 / 单向好友管理

确认尝试获取到陌生人存在

**Comment by SugarFatFree** [comment]
<img width="996" alt="35D9DEFD-AB4B-4277-8805-75C66528A2A0" src="https://user-images.githubusercontent.com/30424828/131595495-128bf3ed-89c7-45cb-92a3-e1d7818b5395.png">
`String msg = event.getMessage().get(1).toString();
            if (msg.startsWith("取人昵称")) {
                long fromQQ = Long.parseLong(msg.substring(4));
                Stranger stranger = event.getBot().getStranger(fromQQ);
                String nick;
                if (stranger != null) {
                    nick = stranger.getNick();
                } else {
                    nick = "[" + fromQQ + "]";
                }
            }`

**Comment by Him188** [comment]
不支持发起陌生人会话，仅支持已有的会话和对方发起的。

**Comment by SugarFatFree** [comment]
> 不支持发起陌生人会话，仅支持已有的会话和对方发起的。

那miria有提供获取陌生人信息的接口吗？我并不需要发起会话，只需要获取他的性别或昵称

**Comment by Him188** [comment]
@hu1240050829 `Mirai.getInstance().getUserInfo()`

也有可能是别的名字

**Comment by Him188** [comment]
@hu1240050829 `queryProfile`
![image](https://user-images.githubusercontent.com/12100985/131618255-900b68b6-2f13-4d4c-b8fa-a86bb647d0f0.png)
