### ISSUE TITLE
mirai的事件是多线程吗

### ISSUE THREAD

**Issue by zimoyin** [mamoe/mirai#1516]
在开发中我声明了两个事件监听 ，他们都是`MessageEvent`类型，我把其中一个用sleep方法将线程睡眠后，另一个事件监听需要等着这个事件睡醒后才能执行。  
但我在以前打印过在监听里面执行的线程名称 ，他们都是以`DefaultDispatcher-worker-数字`命名的所以我认为事件是多线程，但是又与上面的问题不符，因为上面看起来像是单线程   
所以我想知道事件是不是多线程  
用来声明事件的代码  
```java
Listener listener1 = GlobalEventChannel.INSTANCE.subscribeAlways(MessageEvent.class, event -> {
    //睡眠代码     另一个没有睡眠代码，两个代码片段有先后顺序（这是上）
})
```

```

```

#### 版本及相关选项选择

- mirai-core: ` 2.7` 
- bot-protocol: `ANDROID_PHONE` 

#### 网络日志

```

```

**Comment by zimoyin** [comment]
离谱，好像在用网络io时候表现的又好似是多线程

**Comment by sandtechnology** [comment]
RTFM:
https://github.com/mamoe/mirai/blob/c3b6342d34b9fd84ea8358f96b326896f0ef2ae3/mirai-core-api/src/commonMain/kotlin/event/EventChannelKotlinExtensions.kt#L101-L118

https://github.com/mamoe/mirai/blob/8271fa9a82e90edab88e159d35e70f7fc013cc1b/mirai-core-api/src/commonMain/kotlin/event/EventChannel.kt#L289-L376

**Comment by zimoyin** [comment]
看的不是太明白....额
