### ISSUE TITLE
群成员列表 API 的问题

### ISSUE THREAD

**Issue by Mister-Hope** [mamoe/mirai#1527]
同 #563 .

相关 API 不能支持我的需求。我同意目前列表可以被缓存，但是这个缓存列表应该有更新。

目前是这个缓存列表会保持 bot 登陆时的状态。我理解群成员自己改昵称这种mirai无法知晓。但是其他有广播的内容，我觉得应该根据广播内容更新已经缓存好的列表。比如：

- 新成员入群
- 成员被禁言或解禁
- 成员被授予、更改、撤回头衔
- 成员退群
- 成员更改群昵称后在发言时，触发的群昵称变更事件

至少我本地使用最新的 2.7.0 的时候，任何bot登陆后的新成员，以及现有成员被授予头衔，退群等操作，都不会触发列表的更新。

---

我的场景是：

- 每日定期并可以手动触发检查，检查时自动移除加群超过一定时间且群昵称不符合的成员。
- 群聊实名验证，群管理确定此人可以留在群后设置群头衔作为认证标识，并定期移除没有头衔的人。

我觉得这是一个很常规的场景，而且mirai也有实现的具体思路，在这里做这个增强。

我的个人建议是（以下二选一)：

- 联动上述列出的事件并直接根据事件更新缓存列表
- 仍然像 #563 要求的，做一个可以保持bot登陆的手动刷新群成员列表接口 (就如同手机QQ点进群成员列表后慢慢等着加载)

目前无论是一个一个获取群成员信息，还是每小时都重登一次bot，我认为都不是一个很优雅的方案。希望能够支持，致敬！

**Comment by Him188** [comment]
有事件时相关信息都会更新, 缓存会在一段时间后自动保存. 缓存有 id, 该 id 由服务器维护, 如果 id 未变化则不会查询变更.

缓存仅适合在测试中使用, 很难做得很稳定, 不适合其他环境

**Comment by Mister-Hope** [comment]
我通过日志确定，我不重新登录bot之后，我正常用该api获得列表，我踢出了一些有群头衔的人。。。。。。（列表里没有）而且日志里，并未检测到部分新入群的人，我的bot一直在挂着。

这个接口就这么设计没有关系。

#### 我想问的是，我有没有其他workaround，去获得一个准确的群成员列表或者成员信息。（最起码一个准确的群里有谁的列表，然后一个配套的获取他禁言时间、头衔，入群时间的借口）

我看那个单独查群成员信息的接口似乎只是查这个成员的个人信息而不是在群的情况。（除了重新登录整个bot）然后原issue支持刷新群成员列表的功能还被毙掉了。

而且有人也类似有提出查看禁言列表的需求，在mirai没有一个api可以返回准确结果的情况下我们都没法实现此类功能。

**Comment by sandtechnology** [comment]
1.你使用的是什么api？能否贴出代码？
2.目前mirai未支持对群头衔的实时更新，这是正常现象
3.什么叫"未检测到部分新入群的人"？有无日志？用什么方式检的？可能日志输出被过滤而未输出入群事件
4.你使用的协议类型？

Get Outlook for Android<https://aka.ms/AAb9ysg>

________________________________

**Comment by sandtechnology** [comment]
另：通过你其他的issue了解了你目前的需求，可以使用该插件的功能或者实现类似功能解决：https://mirai.mamoe.net/topic/475/simplegroupauth-%E7%AE%80%E5%8D%95%E7%9A%84%E8%BF%9B%E7%BE%A4%E9%AA%8C%E8%AF%81%E6%8F%92%E4%BB%B6/9

**Comment by Mister-Hope** [comment]
感谢回复!😄

1. 我的意思是，在我的机器人登陆后，部分后入群的人，是不能出现在群成员列表api的返回结果中，而且返回结果中，存在部分已经退群的人，这会导致我可能遗漏掉一些人，并且可能对不存在的人尝试进行处理引发其他干扰我日志整洁性的错误记录。

2. 我的场景是多个3千人的学生群，需要对这个人是不是应该加群根据自身的逻辑进行判断，并通过授予头衔来标记已鉴别。(我觉得你们应该可以想象出来有多少外校的或者社会的牛马就尝试加群，然后发广告，找女朋友，问约不约还有发生内裤照的，我目前是有一个女生占比70%的师范新生群)
   所以我目前的需求就是能够需要定时或者手动触发检测群里所有成员的头衔、入群时间和当前群昵称。然后自己的逻辑是踢出入群多长时间没有改群昵称或者没有获得头衔的成员。

目前我似乎找不到一个可以用mirai实现这么一个功能的机会，在手机QQ点击全部群成员的呢时候，会有一个很长的卡顿，慢慢读取群成员列表，我是最终可以刷出来正确的群成员列表，但是在这里目前不能。而且我的bot的其他服务不能频繁中断，所以说目前如果一定要重新登陆bot才能拉更新的列表的话，很难满足现有场景。(所以我才想要问，mirai可否提供一个刷新接口，就如 #563 最初建议的那样。）

**Comment by Mister-Hope** [comment]
我个人认为我的场景和需求，应该还算合理....😅应该不属于Edge Case或者 Rare Case

**Comment by sandtechnology** [comment]
需要澄清的是，mirai自身（指使用JVM语言直接调用其API）是会实时更新群列表以及成员列表中的信息的，否则新成员发言将会报warning，你说的其他信息在拥有相应事件的情况下一般也是会自动更新的，你一开始没有提供你调用API的方式，导致了开发者的误解，这应该是中间件（mirai-ts和mirai-http-api）导致的问题，你也可以试试关闭缓存看看是否能解决
关于群头衔实时更新的问题我看了一下，如果是由bot主动授予的将会广播事件并进行更新，后续我会通过发送PR的方式添加群主或群员自身改变群头衔的解析支持

**Comment by Mister-Hope** [comment]
感谢回复，那我看一下mirai-http-api那边有没有什么我可以改的！比心。

**Comment by Him188** [comment]
还是，你只要关闭缓存就可以了。缓存的同步是不可控的，而实时更新是可以的。

**Comment by yoonching** [comment]
分享下我是如何做的防止外校牛马加群。
1、纯通过名片去判断，不可行。除非投入人工审核挨个问。
2、要求输入正确的验证问题才能加群，我设置的问题有“14位高考考生号”、“学号加四位数生日”（例如20210987+1231），这些都是很难猜到的信息。然后从学校统一认证数据库或其他权威的数据源找这个人。
3、维护了一个表，存储通过“2”步骤成功加群的人员，用来将加群信息和qq号绑定，不允许多人（号）用一个验证信息进来。
4、实名制群必须得到学校方面数据的支持。否则将非常费力。

**Comment by dellbeat** [comment]
群成员API列表的问题我今天在MAH的已有issue[2.3.2版本：群成员列表依然存在缓存数据](https://github.com/project-mirai/mirai-api-http/issues/487#issuecomment-950504654)内做了询问并得到了开发者回复

```
没有，我仔细看了一下 core 的文档，没有强制刷新列表的api，issue里也表示没有
开启/关闭缓存只有在 Bot 登录时传入的 Configuration 进行修改，或者后续通过 bot 实例的 Configuration 动态修改，然而 MAH 不接管登录，也没有理由修改 Configuration

看了下 core 的源码，好友列表和群列表缓存也只是指为登录初始化时进行缓存
```

关于`实时更新`群列表 有啥建议能给到MAH的开发者吗
作为使用者也想让这个问题尽早解决 盼回复
