### ISSUE TITLE
MessageChainBuilder.clear() 无法完全清空

### ISSUE THREAD

**Issue by SugarFatFree** [mamoe/mirai#1538]
在2.7.0正式版发布之前是可以清除所有内容的，但是2.7.0正式版及2.7.1-dev-1中均无法完全清除字符串内容！

```
        MessageChainBuilder builder = new MessageChainBuilder();
        builder.append("abc");
        builder.clear();
        System.out.println(builder.build());
```
其结果仍然为abc，2.7.0正式版之前的版本是可以清空的

- mirai-core: `2.7.1-dev-1` 
- bot-protocol: `ANDROID_PHONE`

**Comment by sandtechnology** [comment]
看样子是缓存导致的问题 尝试PlainText("abc")作为workaround?

**Comment by SugarFatFree** [comment]
> 看样子是缓存导致的问题 尝试PlainText("abc")作为workaround?

这个当然是可以的，但是我代码中几十处都是直接写的String，还都是长文本，既然提供了直接添加String，清空应该也要能够正常清空吧

**Comment by sandtechnology** [comment]
看样子已经修复了 workaround的意思是作为临时的解决方案 如果不想做修改可以考虑使用快照版本：https://github.com/mamoe/mirai/blob/dev/docs/UsingSnapshots.md
