### ISSUE TITLE
建议出短信验证码登陆方式功能

### ISSUE THREAD

**Issue by zhaodice** [mamoe/mirai#1541]
理由是如今的登陆扫码验证越来越不方便，首先是无法电脑浏览器打开，其次有时候又出现二维码无法加载的情况（包括把链接复制到qq客户端打开也是这样无法显示二维码）
![1](https://user-images.githubusercontent.com/63996691/132850862-6a9890e9-5a24-4b50-b78a-b39425897afb.png)

**Comment by zhaodice** [comment]
好吧经过测试关掉设备锁就好了，不过还是想问一下关于短信验证码登陆方式的支持计划（

**Comment by Him188** [comment]
#717
