### ISSUE TITLE
当机器人账号设置为允许任何人添加好友时，mirai的联系人缓存机制会导致Bot.getFriends()抛出异常无法找到新添加的好友。

### ISSUE THREAD

**Issue by FlyRenxing** [mamoe/mirai#1546]
当机器人账号设置为允许任何人添加好友时，mirai的联系人缓存机制会导致Bot.getFriends()抛出异常无法找到新添加的好友。重启项目后再次运行Bot.getFriends()又可以找到好友了。

因生产环境...并没有详细的日志。希望能提供好友申请事件时自动刷新缓存的功能

```

```

#### 复现

1. 设置允许任何人添加好友后登录机器人。
2. 任意账号添加机器人为好友。
3. 调用getFriend方法会抛出无法找到联系人的异常

#### 版本及相关选项选择

- mirai-core: `2.7` 
- bot-protocol: `ANDROID_PHONE` 

#### 网络日志

```

```

**Comment by sandtechnology** [comment]
当机器人账号设置为允许任何人添加好友时，你得到的并不是好友，而是**陌生人**，关于好友申请事件的bug已提交PR修复
