### ISSUE TITLE
收不到群名片更改的事件

### ISSUE THREAD

**Issue by djkcyl** [mamoe/mirai#1547]
在从2.6.7升级到图片发送修复的最新版之后出现该问题，群名片被修改时无法收到事件，mah也不会上报

控制台无任何日志

#### 复现

任何人修改群名片之后均可复现

#### 版本及相关选项选择

- mirai-core: `2.7.1-dev-1` 
- bot-protocol: `ANDROID_PHONE`
- mah: `1.12.0`

#### 网络日志

[2021-09-11.log_FetdSm.tar.gz](https://github.com/mamoe/mirai/files/7147790/2021-09-11.log_FetdSm.tar.gz)

**Comment by sandtechnology** [comment]
请更新mah后再试：https://github.com/project-mirai/mirai-api-http/releases/tag/v2.3.0

**Comment by djkcyl** [comment]
> 请更新mah后再试：https://github.com/project-mirai/mirai-api-http/releases/tag/v2.3.0

麻了，graia不支持mah2（
