### ISSUE TITLE
mirai-logging-log4j2 好多maven仓库找不到这个jar

### ISSUE THREAD

**Issue by alanfans** [mamoe/mirai#1552]
![image](https://user-images.githubusercontent.com/8871739/132973773-53e01f37-6227-408f-85a8-6ac8b2265bf1.png)
![image](https://user-images.githubusercontent.com/8871739/132973779-26f67af8-b6fd-423f-a625-b6796e77d4f0.png)
![image](https://user-images.githubusercontent.com/8871739/132973787-c833907d-d0d3-4b79-83e3-4426b1df7de9.png)

**Comment by Him188** [comment]
好像确实忘了发布
