### ISSUE TITLE
群成员头像为gif时获取的头像链接是错误的

### ISSUE THREAD

**Issue by 4o4E** [mamoe/mirai#1557]
当头像为gif格式时User.getAvatarUrl()会返回错误的头像链接，显示为
![image](https://user-images.githubusercontent.com/58851040/133594042-13b844e0-bcfe-4560-90fe-238a366cef63.png)

#### 复现

1. 将头像换为gif格式
2. 让bot获取头像链接

#### 版本及相关选项选择

- mirai-core: `2.7.1-dev-1` 
- bot-protocol: `ANDROID_PAD`

**Comment by Kazusa1412** [comment]
`http://q1.qlogo.cn/g?b=qq&nk=uin&s=640`  这个地址拿不到 gif 图
`http://q.qlogo.cn/g?b=qq&k=???&s=640`  这里能正确的拿到 gif，不过这个参数 k 不知道怎么算。 但是可以通过其他 api 比如 `https://ptlogin2.qq.com/getface?imgtype=1&uin=uin` 拿到 k
除非知道 **k**  怎么算，不然获取头像链接需要先进行一次网络请求，可以加个 suspend 函数(kt 怎么还不支持 suspend 属性)， 或者在 `ContactOrBot ` 初始化的时候拿

**Comment by 4o4E** [comment]
> `http://q1.qlogo.cn/g?b=qq&nk=uin&s=640` 这个地址拿不到 gif 图 `http://q.qlogo.cn/g?b=qq&k=???&s=640` 这里能正确的拿到 gif，不过这个参数 k 不知道怎么算。 但是可以通过其他 api 比如 `https://ptlogin2.qq.com/getface?imgtype=1&uin=uin` 拿到 k 除非知道 **k** 怎么算，不然获取头像链接需要先进行一次网络请求，可以加个 suspend 函数(kt 怎么还不支持 suspend 属性)， 或者在 `ContactOrBot ` 初始化的时候拿

这个方法拿到的图片并不是gif，只是个预览图

**Comment by Kazusa1412** [comment]
> 这个方法拿到的图片并不是gif，只是个预览图

还是能拿到的，不过这个 s 的值有点迷，不同的值结果都不一样，我这样有个例子

 `http://q1.qlogo.cn/g?b=qq&k=JulcCUMH2XMwb8JFvtcBEg&s=0`    默认企鹅
 `http://q1.qlogo.cn/g?b=qq&k=JulcCUMH2XMwb8JFvtcBEg&s=1`    预览图
 `http://q1.qlogo.cn/g?b=qq&k=JulcCUMH2XMwb8JFvtcBEg&s=4`    gif
 `http://q1.qlogo.cn/g?b=qq&k=JulcCUMH2XMwb8JFvtcBEg&s=14`  请求错误 400
 `http://q1.qlogo.cn/g?b=qq&k=JulcCUMH2XMwb8JFvtcBEg&s=40`  预览图
 `http://q1.qlogo.cn/g?b=qq&k=JulcCUMH2XMwb8JFvtcBEg&s=140` gif

**Comment by 4o4E** [comment]
> http://q1.qlogo.cn/g?b=qq&k=JulcCUMH2XMwb8JFvtcBEg&s=140

ok了，感谢

**Comment by Kazusa1412** [comment]
> 
> ok了，感谢

我发现原来的s用140也能拿到了

`http://q1.qlogo.cn/g?b=qq&nk=uin&s=140`

**Comment by cssxsh** [comment]
`q.qlogo.cn`
`q1.qlogo.cn`
`q2.qlogo.cn`
这些域名应该是等价的
除了 `q.qlogo.cn/g` 接口
还有接口 `q.qlogo.cn/headimg_dl` 

`https://q.qlogo.cn/headimg_dl?dst_uin=${qq}&spec=${level}` 
`spec` 是图片规格(大小)等级 `0, 40, 41, 100, 140, 640`, 0是原图
gif 在等级比较高的情况下可能会失效，需要尝试较低的等级
`spec=640`
![spec_5](https://q.qlogo.cn/headimg_dl?dst_uin=869951226&spec=640)
`spec=140`
![spec_4](https://q.qlogo.cn/headimg_dl?dst_uin=869951226&spec=140)
`spec=100`
![spec_3](https://q.qlogo.cn/headimg_dl?dst_uin=869951226&spec=100)
`spec=41`
![spec_2](https://q.qlogo.cn/headimg_dl?dst_uin=869951226&spec=41)
`spec=40`
![spec_1](https://q.qlogo.cn/headimg_dl?dst_uin=869951226&spec=40)
很奇怪的是原图也会失效，但目前没有对更多的gif头像做测试
`spec=0`
![spec_0](https://q.qlogo.cn/headimg_dl?dst_uin=869951226&spec=0)


with <https://blog.csdn.net/COCO56/article/details/101563707>
