### ISSUE TITLE
群内 QQ 号大于 2^32-1 的人发消息无法被接收

### ISSUE THREAD

**Issue by dousha** [mamoe/mirai#1564]
在 QQ 群内，来自 QQ 号大于 2^32-1 的成员消息不会触发消息接收事件。
这些消息似乎会被静默丢弃。它们也不在 `mirai-console` 的控制台中显示。

#### 复现

1. 使用任意足够大 QQ 号的账户
2. 发送任何消息，包括纯文字消息

#### 版本及相关选项选择

- mirai-core: `2.7.0` 
- bot-protocol: `ANDROID_PHONE` 
- mirai-console: `2.7.0`
- mirai-console-terminal: `2.7.0`
- mirai-addon: `1.2.2`
- mirai-api-http: `1.12.0`

#### 网络日志

见 Pastebin: [https://paste.ubuntu.com/p/kZQBNmZrfx/](https://paste.ubuntu.com/p/kZQBNmZrfx/)

**Comment by Karlatemp** [comment]
重启后是否依然存在此现象？

**Comment by dousha** [comment]
重启之后该现象消失；暂时未测试重启后有新成员加入后的行为

**Comment by sandtechnology** [comment]
从日志来看貌似是没有及时对新成员进行同步导致的 也存在小于 2^32-1 的QQ号无法接收信息的情况 （`Failed to find member xxx in group xxx`），而临时会话的问题已知且已经在dev分支修复 建议继续进行观察

**Comment by Karlatemp** [comment]
Duplicate of #1501
