### ISSUE TITLE
有时候发送群临时消息实际上没有成功 接受不到群临时消息

### ISSUE THREAD

**Issue by hjb1998** [mamoe/mirai#1567]
1.有时候发送群临时消息 能在mirai控制台看到消息已经发送成功 实际上并没有发送（QQ客户端看不到，对方也没有收到）
2.接受不到群临时消息 向bot发送的群临时消息在mirai控制台都没有任何信息

- mirai-core: 2.7.1-dev-1
- bot-protocol: `ANDROID_PHONE`

**Comment by Him188** [comment]
试试2.8.0-M1

**Comment by hjb1998** [comment]
谢谢，试了2.8.0 M1可以了
