### ISSUE TITLE
群名片修改事件无法触发

### ISSUE THREAD

**Issue by Moyulingjiu** [mamoe/mirai#1570]
版本：
![image](https://user-images.githubusercontent.com/40913925/134124871-c49ce937-4261-43a1-93fd-05d34882b4d1.png)

日志：
[2021-09-21.log](https://github.com/mamoe/mirai/files/7200875/2021-09-21.log)

使用的框架：YiriMirai

无论群成员修改多少次群名片，该事件都无法触发。
![image](https://user-images.githubusercontent.com/40913925/134125201-1d5ffca1-8325-4c67-82d5-7e5bf9f573d1.png)

**Comment by Karlatemp** [comment]
提供系统日志

**Comment by Moyulingjiu** [comment]
![image](https://user-images.githubusercontent.com/40913925/134127907-bb86d032-4d3e-478d-9d1d-c3f5b1ca842a.png)
请问一下系统日志在哪里。我有点不确定开日志了。之前都是在基于YiriMirai开发，没怎么看core的文档

**Comment by Karlatemp** [comment]
目前 console-terminal 还没记录系统日志到文件

**Comment by Karlatemp** [comment]
群成员修改名片后是否有发言

**Comment by Moyulingjiu** [comment]
没有发言

**Comment by Karlatemp** [comment]
群成员修改群名片服务器不会有任何广播，只能由 mirai 主动发现该群成员名片已经修改了

**Comment by Karlatemp** [comment]
也就是要知道该群成员修改群名片，该群成员必须再发言一次

**Comment by Moyulingjiu** [comment]
明白了

**Comment by Moyulingjiu** [comment]
> 也就是要知道该群成员修改群名片，该群成员必须再发言一次

可不可以支持一下只要有人发言，就能触发。因为发言的人很多，但是有人进群只是更改了一下名片没有发言。我想做一个群名片约束的功能。

**Comment by Karlatemp** [comment]
发言是只有发言的那个人的相关信息的, 如果每次有人发言都检查一次全群的群名片, 对于网络的占用是极其巨大的, 各种综合考虑这不值得

**Comment by Moyulingjiu** [comment]
那我自己做定时检查吧
