### ISSUE TITLE
发送群消息的时候只能发送1-2位数字，发送其他的显示发送成功，但是返回的messageId为 -1

### ISSUE THREAD

**Issue by asok00000** [mamoe/mirai#1572]
![image](https://user-images.githubusercontent.com/5980497/134249316-e9121ccb-4200-441d-a217-0506273510c8.png)
![image](https://user-images.githubusercontent.com/5980497/134249394-6cc6faf6-3f6c-4cba-b752-29e5de0aa174.png)
![image](https://user-images.githubusercontent.com/5980497/134249419-7e39861b-7b25-41f1-be4d-4f273e9e16f7.png)

```

```

#### 版本及相关选项选择

- mirai-core: `2.7.1` 
- bot-protocol: `ANDROID_PHONE` 

mirai-api-http: `2.2.0`
#### 网络日志

```
[0m2021-09-22 01:54:47 V/Net 1444599220: Send: MessageSvc.PbSendMsg(MessageSvc.PbSendMsg)[0m
[0m2021-09-22 01:54:48 V/Net 1444599220: Recv: MessageSvc.PbSendMsg[0m

```

#### 补充信息

这个和运行mcl所在时区不是中国会有关系么？
__发送好友消息可以成功__

**Comment by asok00000** [comment]
……多次重启mcl后又可以发了……

**Comment by 0f-0b** [comment]
出现过同样的问题，但不清楚触发条件。时区是中国。

* mirai-core：2.7.1
* bot-protocol: ANDROID_PAD
* mirai-api-http：2.3.1

**Comment by ryuujo1573** [comment]
同样问题，只能发送2byte字符
