### ISSUE TITLE
监听不到主动踢人事件，只能监听到其他管理员的操作的退群

### ISSUE THREAD

**Issue by Yu-Jie1669** [mamoe/mirai#1576]
```

```

#### 版本及相关选项选择

- mirai-core: `2.6.7` 
- bot-protocol: `ANDROID_PHONE` 

#### 网络日志

```

```

**Comment by Yu-Jie1669** [comment]
监听不到自己操作的，只能监听到其他管理员的操作的退群

**Comment by Nambers** [comment]
你是指无法监听到自己提出的群成员的退群消息 只能监听其他管理员踢的? 还是指监听不到他自己退出的消息
然后更新最新版确保没有已经被解决 (稳定版2.7.1或更新)

**Comment by Him188** [comment]
试试 2.8.0-M1

**Comment by Yu-Jie1669** [comment]
> 你是指无法监听到自己提出的群成员的退群消息 只能监听其他管理员踢的? 还是指监听不到他自己退出的消息
> 然后更新最新版确保没有已经被解决 (稳定版2.7.1或更新)

是别的管理员踢出可以监听到，自己踢出无法监听到，已经更新到最新版了

**Comment by Yu-Jie1669** [comment]
> 试试 2.8.0-M1

已经更新到最新了

**Comment by Nambers** [comment]
> > 你是指无法监听到自己提出的群成员的退群消息 只能监听其他管理员踢的? 还是指监听不到他自己退出的消息
> > 然后更新最新版确保没有已经被解决 (稳定版2.7.1或更新)
> 
> 是别的管理员踢出可以监听到，自己踢出无法监听到，已经更新到最新版了

自己踢的为什么还要监听? 直接处理?
还是有什么特殊情况吗(

**Comment by zhaodice** [comment]
> 
> 
> > > 你是指无法监听到自己提出的群成员的退群消息 只能监听其他管理员踢的? 还是指监听不到他自己退出的消息
> > > 然后更新最新版确保没有已经被解决 (稳定版2.7.1或更新)
> > 
> > 
> > 是别的管理员踢出可以监听到，自己踢出无法监听到，已经更新到最新版了
> 
> 自己踢的为什么还要监听? 直接处理? 还是有什么特殊情况吗(

比如其他插件调用了踢人API，你是另一个插件，自然无权得知（

**Comment by Karlatemp** [comment]
请提供复现代码
