### ISSUE TITLE
移除群成员报错

### ISSUE THREAD

**Issue by asok00000** [mamoe/mirai#1579]
![image](https://user-images.githubusercontent.com/5980497/134536267-12265bb6-5e58-44f8-a9d1-dc4633703169.png)

```

```

#### 版本及相关选项选择

- mirai-core: `2.7.1` 
- bot-protocol: `ANDROID_PHONE` 

#### 网络日志

```

```

**Comment by Karlatemp** [comment]
#659, #1486

**Comment by asok00000** [comment]
确实是自动移除导致的···😂现在从网页上手工点移除都无效了。。。不知道这个过24h后会不会恢复

> #659, #1486
