### ISSUE TITLE
发送文件

### ISSUE THREAD

**Issue by SunYihao555** [mamoe/mirai#1581]
请问 miral-core里面哪个api可以用来发送文件啊

**Comment by Nambers** [comment]
`group.uploadFile(path, File)`

**Comment by SunYihao555** [comment]
> `group.uploadFile(path, File)`
这是上传到群文件吧，有没有发给个人的呢

**Comment by Nambers** [comment]
> > `group.uploadFile(path, File)`
> > 这是上传到群文件吧，有没有发给个人的呢

https://github.com/mamoe/mirai/issues/1416
