### ISSUE TITLE
语音无声

### ISSUE THREAD

**Issue by cyear** [mamoe/mirai#1587]
尝试过base64  path  url上传音频，都没有声音(mp3) silk也试过了，上传之后不能播放

```

```

#### 版本及相关选项选择

- mirai-core: `2.6.7` 
- bot-protocol: `ANDROID_PHONE` 

#### 网络日志

```

```

**Comment by Nambers** [comment]
更新到2.8.0-M1或2.7.1看看

**Comment by JustOneSummer** [comment]
你手机端看看 我发的电脑端是看不了的

**Comment by cyear** [comment]
> 你手机端看看 我发的电脑端是看不了的

用的就是手机播放

**Comment by nian0** [comment]
> 更新到2.8.0-M1或2.7.1看看

**Comment by cyear** [comment]
> 更新到2.8.0-M1或2.7.1看看

版本就是2.8.0-M1

**Comment by Karlatemp** [comment]
提供源文件

**Comment by cyear** [comment]
> 提供源文件

[]()http://www.wlwmz.top:2/download

**Comment by cyear** [comment]
> 提供源文件

请问如何解决

**Comment by Karlatemp** [comment]
The `silk` file?

**Comment by cyear** [comment]
> The `silk` file?

silk我也转过了你看一下这个是吗，我试过发送也不能播放
[]()http://www.wlwmz.top:2/download

**Comment by Karlatemp** [comment]
![image](https://user-images.githubusercontent.com/30070303/135439248-92d06ad7-fadf-4158-86f9-49365b7828ca.png)
where

**Comment by AdoptOSS** [comment]
@Karlatemp 缓存问题？我这里可以正常下载到silk。
[分享(nian).zip](https://github.com/mamoe/mirai/files/7258819/nian.zip)

**Comment by Karlatemp** [comment]
判断为你使用的 silk encoder 有问题, 请使用其他 coder

**Comment by cyear** [comment]
> 判断为你使用的 silk encoder 有问题, 请使用其他 coder

有推荐的silk encode吗

**Comment by Karlatemp** [comment]
https://github.com/mzdluo123/silk4j

**Comment by cyear** [comment]
> https://github.com/mzdluo123/silk4j

除了silk别的格式不能用吗，我之前用mp3格式还可以的，代码都没变，现在更新几个版本之后就不行了

**Comment by cyear** [comment]
> https://github.com/mzdluo123/silk4j

我使用编译的ffmpeg转amr可以播放，但是音质感觉有损音频

**Comment by Karlatemp** [comment]
> > https://github.com/mzdluo123/silk4j
> 
> 除了silk别的格式不能用吗，我之前用mp3格式还可以的，代码都没变，现在更新几个版本之后就不行了

一直都是只能 slik, amr 两种格式
