### ISSUE TITLE
ForwardMessageInternal 的长度检查

### ISSUE THREAD

**Issue by cssxsh** [mamoe/mirai#1590]
```
2021-10-02 16:13:38 W/pixiv-helper: Exception in executing command `[mirai:source:[92335],[-744223730]]play recommended`
net.mamoe.mirai.contact.MessageTooLargeException: message(ForwardMessageInternal(...origin=ForwardMessage(p
```
ForwardMessage 在发送时会转化为 ForwardMessageInternal XML卡片消息，
但是在 SingleMessage.estimateLength 会按 this.toString().chineseLength(upTo) 去计算长度，
toString 时会 按照 data class 的默认格式，而不是是 XML卡片消息 的内容，因为包含 origin: ForwardMessage  ，总的消息长度很容易爆炸
https://github.com/mamoe/mirai/blob/b7869888f00ce43199e8f95f133486087bc611fd/mirai-core/src/commonMain/kotlin/utils/type.kt#L60-L70

https://github.com/mamoe/mirai/blob/6079cbb6e0ad0e76dccf84599b740ddbeefa84fe/mirai-core/src/commonMain/kotlin/message/LongMessageInternal.kt#L39-L53

#### 复现

```
    // 随机一点长文本
    val rand: (Int) -> String = { length -> CharArray(length) { (' '..'~').random() }.concatToString() }

    // 队列
    val list = List(30) {
        ForwardMessage.Node(
            senderId = bot.id,
            time = (System.currentTimeMillis() / 1000L).toInt(),
            senderName = bot.nameCardOrNick,
            message = rand(500).toPlainText()
        )
    }

    // 合成 ForwardMessage
    val forward = RawForwardMessage(list).render(object : ForwardMessage.DisplayStrategy {
        override fun generatePreview(forward: RawForwardMessage): List<String> = emptyList()
    })

    // 发送
    bot.getGroup(12345).sendMessage(forward)
```
断点
![21-10-02_idea64_Qt6ik426WK](https://user-images.githubusercontent.com/32539286/135712923-ef812e3c-c8e3-45e6-bc6e-debab9908e08.png)
ForwardMessageInternal.toString()
![21-10-02_0lDgRshcWu](https://user-images.githubusercontent.com/32539286/135712931-110a8c43-1e7b-4d4f-9b4f-189de05a90c5.png)
ForwardMessageInternal.content
![21-10-02_5t9NHWUdJt](https://user-images.githubusercontent.com/32539286/135712935-5def5541-57d7-4b72-aa91-20061ba4c306.png)

#### 版本及相关选项选择

- mirai-core: `2.6.7` 
- bot-protocol: `ANDROID_PHONE` 

#### 网络日志

```

```

**Comment by Nambers** [comment]
论坛也有人出现了这种问题
https://mirai.mamoe.net/topic/647/forwardmessagebuilder%E5%A6%82%E4%BD%95%E5%88%A4%E6%96%AD%E6%98%AF%E5%90%A6%E8%B6%85%E5%87%BA%E5%A4%A7%E5%B0%8F%E9%99%90%E5%88%B6
可以参考他是发了什么来判断有没有影响正常操作吧

**Comment by cssxsh** [comment]
> 论坛也有人出现了这种问题 https://mirai.mamoe.net/topic/647/forwardmessagebuilder%E5%A6%82%E4%BD%95%E5%88%A4%E6%96%AD%E6%98%AF%E5%90%A6%E8%B6%85%E5%87%BA%E5%A4%A7%E5%B0%8F%E9%99%90%E5%88%B6 可以参考他是发了什么来判断有没有影响正常操作吧

按照我打断点的结果来看，是 ForwardMessageInternal 的长度检查 不正确
