### ISSUE TITLE
ForwardMessage 内的 Image url地址不正确

### ISSUE THREAD

**Issue by Deficuet** [mamoe/mirai#1600]
群友发送，让bot直接接收到合并转发后，试图获取其包含的图片的url，得到了如下格式的url：（图片id为例子）
```
http://c2cpicdw.qpic.cn/offpic_new/0/{3C729FD6-8FB5-741B-461E-BF4D3F1C3523}.png/0?term=2
```
其中直接包含大括号的字面量"{"而不是其转义"%7B"，导致尝试下载时得到了报错：
```
java.net.URISyntaxException: Illegal character in path at index 37: http://c2cpicdw.qpic.cn/offpic_new/0/{3C729FD6-8FB5-741B-461E-BF4D3F1C3523}.png/0?term=2
```
如果转义俩大括号后访问该链接，从这个链接下载到的图片还极有可能是空的

```

```
#### 复现

一个群友发了一个合并转发，bot接收到并尝试下载其中的图片
不确定是否 是从特定设备发送合并转发才会引发该问题

#### 版本及相关选项选择

- mirai-core: `2.7.1` 
- bot-protocol: `ANDROID_WATCH` 

#### 补充信息

queryUrl的问题有点多啊（

**Comment by zhaodice** [comment]
是这个图吗
http://gchat.qpic.cn/gchatpic_new/0/0-0-3C729FD68FB5741B461EBF4D3F1C3523/0?term=2
```
你把{3C729FD6-8FB5-741B-461E-BF4D3F1C3523}.png变成 3C729FD68FB5741B461EBF4D3F1C3523
再 http://gchat.qpic.cn/gchatpic_new/0/0-0-替换这里/0?term=2 就行了
```

**Comment by Deficuet** [comment]
> 是这个图吗 http://gchat.qpic.cn/gchatpic_new/0/0-0-3C729FD68FB5741B461EBF4D3F1C3523/0?term=2
> 
> ```
> 你把{3C729FD6-8FB5-741B-461E-BF4D3F1C3523}.png变成 3C729FD68FB5741B461EBF4D3F1C3523
> 再 http://gchat.qpic.cn/gchatpic_new/0/0-0-替换这里/0?term=2 就行了
> ```

我知道怎么解决（）
只是觉得直接获取还要后续处理一定有哪里不对

**Comment by zhaodice** [comment]
> 
> 
> > 是这个图吗 http://gchat.qpic.cn/gchatpic_new/0/0-0-3C729FD68FB5741B461EBF4D3F1C3523/0?term=2
> > ```
> > 你把{3C729FD6-8FB5-741B-461E-BF4D3F1C3523}.png变成 3C729FD68FB5741B461EBF4D3F1C3523
> > 再 http://gchat.qpic.cn/gchatpic_new/0/0-0-替换这里/0?term=2 就行了
> > ```
> 
> 我知道怎么解决（） 只是觉得直接获取还要后续处理一定有哪里不对

能写一下你的代码，你咋获取的图url吗

**Comment by zhaodice** [comment]
我感觉这可能是mirai把群图片误识别成好友图片了，导致url生成的结果错误。

**Comment by Deficuet** [comment]
一个方法是你说的直接替换
另一个是可以根据拿到的图片id再构造一个Image实例然后queryUrl（
Kotlin：
```
Image.fromId(imageId).queryUrl()
```

**Comment by Karlatemp** [comment]
消息来源为 群内消息转发  还是  私聊消息转发

**Comment by Deficuet** [comment]
> 消息来源为 群内消息转发 还是 私聊消息转发

群内。发送者显示移动设备在线

**Comment by Karlatemp** [comment]
未复现，提供完整复现流程，包括使用的客户端

**Comment by Deficuet** [comment]
在群内接收到了一个合并转发。里面包含七个合并转发并且每个里面都有很多图片
对每张图片尝试获取url并下载。得到的url就如问题所述。

我所使用的libs有 console，console-terminal，core-all，手动bat启动mirai-console。由插件登录账号而不是console
登录协议似乎搞混了，因为登了俩账号。协议为 ANDROID_WATCH

关于发送者的环境我这不知道

**Comment by Karlatemp** [comment]
未复现

**Comment by Deficuet** [comment]
累计收到过一百多个合并转发，这个问题我也只遇到过四五次。
如果还要补充的话，群是被收进群助手且不提醒的。之前没想到这一点，不知道跟这个问题有没有关系
我这的环境已经都说了，我也不知道该咋复现←_←

**Comment by Karlatemp** [comment]
提供触发时的消息日志

```
2021-10-11 13:13:04 V/Bot .....: [OpenTestGroup(.........)] ................. -> [mirai:origin:FORWARD,..........]ForwardMessage(preview=..................)
```

**Comment by Deficuet** [comment]
呃，日志没了。由于是插件启动所以没有设置把日志写入到磁盘。
因为把verbose打开了，消息太多日志太长，往上翻也找不到了
只记得日志里打印出来的与通常接收到的合并转发无异

**Comment by Deficuet** [comment]
又在群内收到了一个出现该问题的合并转发，不过只有一小部分图片有该问题。嵌套多且深。实在太长了就记在文件里了。
稍微抹掉了零星几处个人信息
[FwdMsgLog.txt](https://github.com/mamoe/mirai/files/7357168/FwdMsgLog.txt)
在下载图片时把步骤基本都打印到日志内了。以下是所有出现该问题的图片的相关log
[ImageURLLog.txt](https://github.com/mamoe/mirai/files/7357169/ImageURLLog.txt)
除了群不一样，其他环境条件均相同，都收在群助手内
