### ISSUE TITLE
发送消息失败错误码121 MessageSvcPbSendMsg.Response.Failed(resultType=121, errorCode=0, errorMessage=)

### ISSUE THREAD

**Issue by TihPct** [mamoe/mirai#1602]
异常信息:
![QQ图片20211012172937](https://user-images.githubusercontent.com/51705716/136930419-34b769f5-98ca-436b-93c6-2cdc3ce58174.png)

版本: mirai-core 2.8.0-M1
平台:JVM
协议:ANDROID_PAD
心跳策略:NONE

在尝试协议与心跳策略分别切换无果后,不知原因,发送群消息失败

**Comment by TihPct** [comment]
不知道是mirai本身原因还是腾讯风控的原因

**Comment by Karlatemp** [comment]
消息内容，bot是否被禁言 bot是否为管理员

**Comment by TihPct** [comment]
> 消息内容，bot是否被禁言 bot是否为管理员

BOT未被禁言,但是机器人是管理员

**Comment by Karlatemp** [comment]
long time no reply
