### ISSUE TITLE
关于内存泄露问题

### ISSUE THREAD

**Issue by iceBear67** [mamoe/mirai#1608]
我不会 JVM Profiling，只是好奇为什么堆里会有 1,393,417 个 `net.mamoe.mirai.internal.network.protocol.data.proto.ImMsgBody$Elem`。。  
而且似乎他们大多都和 RichMsg 相关，我觉得不应该会有这么多个对象，即使是缓存

Heap File: https://cowtransfer.com/s/e5aeaa9807a043

#### 复现
挂着 Mirai 运行

#### 版本及相关选项选择

- mirai-core: `2.7.1-dev-1` 
- mirai-api-http: 2.1.0
- bot-protocol: `ANDROID_PHONE`

**Comment by Him188** [comment]
mirai-api-http 缓存 `MessageChain` 或 `MessageSource` 而不释放导致的

**Comment by ryoii** [comment]
目前解决了cache的问题，session的问题待定，考虑要不要先发一版
