### ISSUE TITLE
amr 发送至 `好友会话` 无法播放

### ISSUE THREAD

**Issue by whiterasbk** [mamoe/mirai#1617]
在使用Audio发送消息时发现能将mp3转换成的amr文件发送到sender中去，但是在qq客户端显示红色叹号并且语音消息不能播放，之后改为上传qq数据文件下的amr文件，结果能正常显示语音消息且正常播放；使用win10自带播放器播放数据目录下的amr文件提示格式错误。原因推测为tencent在某个时间段之后改为使用加密过后的amr格式，正常的amr格式反而不能正常播放。希望后续修复这个bug（也许称得上是bug的话）

```

```

#### 版本及相关选项选择

- mirai-core: `2.8.0-M1` 
- bot-protocol: `ANDROID_PHONE` 

mirai-console 2.8.0-M1

#### 网络日志

```

```

**Comment by Karlatemp** [comment]
提供转码后的amr文件

**Comment by whiterasbk** [comment]
> 提供转码后的amr文件

https://cowtransfer.com/s/8875d0788de646

**Comment by Karlatemp** [comment]
send to group or private chat?

**Comment by whiterasbk** [comment]
> send to group or private chat?

to group is fine, while to private chat is not

**Comment by Karlatemp** [comment]
report to tencent not mamoe
