### ISSUE TITLE
希望能增加自定义实现serverlist功能

### ISSUE THREAD

**Issue by mcdoeswhat** [mamoe/mirai#1618]
我发现Mirai有时候启动会选择一些根本无法连接的服务器或者延迟高的服务器进行登录(导致登录缓慢,甚至加载群列表20分钟还没加载完),而且必须重启整个程序才会选择其他服务器,
连接超时报错: https://pastebin.com/4ixrArH0 明明有其他的低延迟服务器,却选择连接这个连不上的
直到超时才会自动切换其他服务器,而且bot重新登录也依然会从这个服务器开始试,然后重复这个过程,除非重启
上次提交的问题我才发现也是这个导致的: https://github.com/mamoe/mirai/issues/1555
希望能增加api自定义serverlist,以及serverlist缓存

**Comment by mcdoeswhat** [comment]
或者可以优先连msfwifi.3g.qq.com这个服务器,失败后再尝试其他的,这个域名我看多地ping 解析出来大概24个IP
而且就算连接失败用户也可以修改hosts文件重定向延迟低的ip

**Comment by sandtechnology** [comment]
你想说的是不是服务器优选功能？

**Comment by sandtechnology** [comment]
另：服务器会推送更新的服务器列表 所以这个问题其实并不严重

**Comment by mcdoeswhat** [comment]
机器人已经用了几个月了,而且server.json里面也都是延迟低的服务器列表
但是mirai有时候启动还是会用默认的服务器列表里面的服务器,已经测试多次,并且在完全新开的阿里云服务器上复现
登录十几次大概就会出现直接用默认的列表里的ip,而不是缓存的优选ip

**Comment by mcdoeswhat** [comment]
server.json: https://pastebin.com/XrurseL4
我全部ping过了都是不超过100ms的
但是mirai启动的时候用的是默认的ip,日志里面也显示了loaded server list from cache

**Comment by sandtechnology** [comment]
> 
> 
> 机器人已经用了几个月了,而且server.json里面也都是延迟低的服务器列表 但是mirai有时候启动还是会用默认的服务器列表里面的服务器,已经测试多次,并且在完全新开的阿里云服务器上复现 登录十几次大概就会出现直接用默认的列表里的ip,而不是缓存的优选ip

这个问题建议你新开一个issue 这个issue是提了服务器优选功能和获取功能的的

**Comment by mcdoeswhat** [comment]
https://github.com/mamoe/mirai/pull/1634
