### ISSUE TITLE
发送LightApp消息时显示"发送者版本过低，无法展示内容"

### ISSUE THREAD

**Issue by CyanBillows** [mamoe/mirai#1621]
版本: 2.8.0-M Mirai-Core
采用的json构建LightApp，无论是群发还是私聊都会存在这个问题
望解决

**Comment by Karlatemp** [comment]
Please follow the issue template

where is app content

**Comment by CyanBillows** [comment]
> Please follow the issue template
> 
> where is app content

```kotlin
val json = "{\n" +
                        "    \"app\": \"com.tencent.miniapp\", \n" +
                        "    \"desc\": \"\", \n" +
                        "    \"view\": \"notification\", \n" +
                        "    \"ver\": \"0.0.0.1\", \n" +
                        "    \"prompt\": \"${senderName}的今日人品\", \n" +
                        "    \"meta\": {\n" +
                        "        \"notification\": {\n" +
                        "            \"appInfo\": {\n" +
                        "                \"appName\": \"${senderName}的今日人品\", \n" +
                        "                \"appType\": 4, \n" +
                        "                \"appid\": 1109659848, \n" +
                        "                \"iconUrl\": \"http://q1.qlogo.cn/g?b=qq&nk=${sender.id}&s=640\"\n" +
                        "            }, \n" +
                        "            \"data\": [\n" +
                        "                {\n" +
                        "                    \"title\": \"今日人品\", \n" +
                        "                    \"value\": \"${luck}\"\n" +
                        "                }, \n" +
                        "                {\n" +
                        "                    \"title\": \"今日适宜\", \n" +
                        "                    \"value\": \"${thing}\"\n" +
                        "                },\n" +
                        "                {\n" + //诗词，游戏，动漫名言
                        "                    \"title\": \"一言\", \n" +
                        "                    \"value\": \"${saying.hitokoto} --${saying.from}\"\n" +
                        "                }\n" +
                        "            ], \n" +
                        "            \"title\": \"\", \n" +
                        "            \"emphasis_keyword\": \"今日人品\"\n" +
                        "        }\n" +
                        "    }\n" +
                        "}"
                val lightapp = LightApp(json)
                subject.sendMessage(lightapp)
```

**Comment by Karlatemp** [comment]
protocol of bot

**Comment by CyanBillows** [comment]
> protocol of bot

Android phone,有劳了

**Comment by Karlatemp** [comment]
根据 `代码存在字符串直接拼接` 请提供最终发送的 json 文本

**Comment by Karlatemp** [comment]
Test ok with

```json
{
    "app": "com.tencent.miniapp", 
    "desc": "", 
    "view": "notification", 
    "ver": "0.0.0.1", 
    "prompt": "Test的今日人品", 
    "meta": {
        "notification": {
            "appInfo": {
                "appName": "Test的今日人品", 
                "appType": 4, 
                "appid": 1234567890, 
                "iconUrl": "http://q1.qlogo.cn/g?b=qq&nk=1234567890&s=640"
            }, 
            "data": [
                {
                    "title": "今日人品", 
                    "value": "Test"
                }, 
                {
                    "title": "今日适宜", 
                    "value": "Test"
                },
                {
                    "title": "一言", 
                    "value": "Test --Test"
                }
            ], 
            "title": "", 
            "emphasis_keyword": "今日人品"
        }
    }
}
```

**Comment by CyanBillows** [comment]
> Test ok with
> 
> ```json
> {
>     "app": "com.tencent.miniapp", 
>     "desc": "", 
>     "view": "notification", 
>     "ver": "0.0.0.1", 
>     "prompt": "Test的今日人品", 
>     "meta": {
>         "notification": {
>             "appInfo": {
>                 "appName": "Test的今日人品", 
>                 "appType": 4, 
>                 "appid": 1234567890, 
>                 "iconUrl": "http://q1.qlogo.cn/g?b=qq&nk=1234567890&s=640"
>             }, 
>             "data": [
>                 {
>                     "title": "今日人品", 
>                     "value": "Test"
>                 }, 
>                 {
>                     "title": "今日适宜", 
>                     "value": "Test"
>                 },
>                 {
>                     "title": "一言", 
>                     "value": "Test --Test"
>                 }
>             ], 
>             "title": "", 
>             "emphasis_keyword": "今日人品"
>         }
>     }
> }
> ```

[mirai:app:{\n    "app"\: "com.tencent.miniapp"\, \n    "desc"\: ""\, \n    "view"\: "notification"\, \n    "ver"\: "0.0.0.1"\, \n    "prompt"\: "Test的今日人品"\, \n    "meta"\: {\n        "notification"\: {\n            "appInfo"\: {\n                "appName"\: "Test的今日人品"\, \n                "appType"\: 4\, \n                "appid"\: 1234567890\, \n                "iconUrl"\: "http\://q1.qlogo.cn/g?b=qq&nk=1234567890&s=640"\n            }\, \n            "data"\: \[\n                {\n                    "title"\: "今日人品"\, \n                    "value"\: "Test"\n                }\, \n                {\n                    "title"\: "今日适宜"\, \n                    "value"\: "Test"\n                }\,\n                {\n                    "title"\: "一言"\, \n                    "value"\: "Test --Test"\n                }\n            \]\, \n            "title"\: ""\, \n            "emphasis_keyword"\: "今日人品"\n        }\n    }\n}]

**Comment by CyanBillows** [comment]
> 根据 `代码存在字符串直接拼接` 请提供最终发送的 json 文本

[mirai:app:{\n    "app"\: "com.tencent.miniapp"\, \n    "desc"\: ""\, \n    "view"\: "notification"\, \n    "ver"\: "0.0.0.1"\, \n    "prompt"\: "000的今日人品"\, \n    "meta"\: {\n        "notification"\: {\n            "appInfo"\: {\n                "appName"\: "000的今日人品"\, \n                "appType"\: 4\, \n                "appid"\: 1109659848\, \n                "iconUrl"\: "http\://q1.qlogo.cn/g?b=qq&nk=2875262998&s=640"\n            }\, \n            "data"\: \[\n                {\n                    "title"\: "今日人品"\, \n                    "value"\: "43"\n                }\, \n                {\n                    "title"\: "今日适宜"\, \n                    "value"\: "家务"\n                }\,\n                {\n                    "title"\: "一言"\, \n                    "value"\: "我该用什么来回应你的不义。 --明日方舟"\n                }\n            \]\, \n            "title"\: ""\, \n            "emphasis_keyword"\: "今日人品"\n        }\n    }\n}]


Still not work..qwq

**Comment by Karlatemp** [comment]
![image](https://user-images.githubusercontent.com/30070303/138909822-7f461070-9dd0-4f44-bdb8-91e9b6f54f4c.png)

You may try log in to another account, check information on other devices, etc...

**Comment by Karlatemp** [comment]
lightapp可正常发送，属于发送内容有问题
