### ISSUE TITLE
FowardMessage无法直接添加由mirai码解析出的Image

### ISSUE THREAD

**Issue by mcdoeswhat** [mamoe/mirai#1629]
fowardmessage机器人发送正常
尝试从本地发送图片,如果图片已经上传过qq服务器
mirai会显示Send: ImgStore.GroupPicUp(ImgStore.GroupPicUp)直接发送图片
这时将图片添加到forwardmessage结构中也可正常显示图片

这时将图片删除,保存mirai码到文件,直接从mirai码中解析图片
java代码:
```
 Image imageTest = (Image) MiraiCode.deserializeMiraiCode("[mirai:image:{9AB1EE67-D85E-F832-15CF-763DA1384E0B}.gif]").get(0);
group.sendMessage(imageTest);
```
测试可以直接发送，但是如果把Mirai码解析出的图片(imageTest)添加到forwardmessage结构中
java代码:
```
mage imageTest = (Image) MiraiCode.deserializeMiraiCode("[mirai:image:{9AB1EE67-D85E-F832-15CF-763DA1384E0B}.gif]").get(0);

 ForwardMessageBuilder builder = new ForwardMessageBuilder(User, 1);
                builder.add(User, imageTest);
```
forwardmessage将无法显示,机器人后台显示forwardmessage发送成功,但是并没有显示任何消息

测试使用： Image.fromId方法也不行

```

```

#### 版本及相关选项选择

- mirai-core: `2.8.0-M1` 
- bot-protocol: `ANDROID_PAD` 

#### 网络日志

```

```

**Comment by Karlatemp** [comment]
#1507
