### ISSUE TITLE
Mirai 默认日志系统应该使用系统时区

### ISSUE THREAD

**Issue by Xiaomckedou233** [mamoe/mirai#1639]
系统为Ubuntu20.04LTS
时区改为上海的UTC+8
但是每次改完之后在打开就发现Mirai用的还是UTC，完全改不回来
![image](https://user-images.githubusercontent.com/90455346/139769722-df901743-e7c6-454a-9141-13ebc7b689e9.png)

![image](https://user-images.githubusercontent.com/90455346/139769728-626f2db3-45c1-4b27-a54f-cdb5b582b4df.png)
有没有大佬能救救

**Comment by cssxsh** [comment]
百度或谷歌 `linux时间和win10差8小时`

**Comment by Xiaomckedou233** [comment]
谢谢大佬

**Comment by Xiaomckedou233** [comment]
> 百度或谷歌 `linux时间和win10差8小时`

不行，改了机子物理时间也不行。依旧UTC

**Comment by cssxsh** [comment]
那就调整系统时区

**Comment by Karlatemp** [comment]
目前默认日志系统写死为 `中国` 时区, 更可能的为你系统的实际时间错误
