### ISSUE TITLE
找不到mirai-console-compiler-annotations:2.8.0-RC

### ISSUE THREAD

**Issue by Nambers** [mamoe/mirai#1644]
![MCCU@@%V7CBZYIY@}ZW) V6](https://user-images.githubusercontent.com/35139537/139792451-fabd461a-dab7-4c6e-a727-5dfc22a97658.jpg)

我去maven仓库看了下https://repo.maven.apache.org/maven2/net/mamoe/mirai-console-compiler-annotations/2.8.0-RC/
有2.8.0-RC, 就是没有pom文件，有pom文件的md5等校验文件

#### 复现

在gradle使用mirai-console:2.8.0-RC
对core好像没有影响

#### 版本及相关选项选择

- mirai-console: `2.8.0-RC` 
- bot-protocol: `ANDROID_PHONE`

**Comment by Karlatemp** [comment]
https://issues.sonatype.org/browse/OSSRH-74686

**Comment by Karlatemp** [comment]
Missing artifact published. Waiting MvnCenter CDN cache refresh
