### ISSUE TITLE
群名称（非群名片）被修改无法触发事件

### ISSUE THREAD

**Issue by dellbeat** [mamoe/mirai#1648]
在BOT所在群内修改群名称（非群名片），无法在console上显示事件，也无法在BOT对应log文件夹的log.txt内获得任何相关日志信息（指时间相关，修改群名后一段时间内该log内无任何内容增加）

```
无
```

#### 复现

在BOT所在群内修改群名称即可
#### 版本及相关选项选择

- mirai-core: `2.7.0` 
- bot-protocol: `ANDROID_PAD` 
- mirai-api-http: `2.3.0`

#### 网络日志

```

```

**Comment by Karlatemp** [comment]
#1570 #1547

**Comment by dellbeat** [comment]
> #1570 #1547

修改了一下描述 出现问题的是修改群的名称 并非修改群名片
修改群名片时出现的问题早些时间查阅到了相关issue

**Comment by Karlatemp** [comment]
2.8.0-RC是否仍然存在此问题

**Comment by dellbeat** [comment]
由于MAH当前依赖的core是2.7.0
不确定能否直接更改依赖为2.8.0-RC
如果能直接升级依赖我会尝试验证

**Comment by Karlatemp** [comment]
2.8.0-RC测试无问题，请更新至2.8.0-RC后再次验证

**Comment by dellbeat** [comment]
好的 后续如果能升级到`2.8.0-RC`会再次进行验证

**Comment by Karlatemp** [comment]
尝试使用其他协议

**Comment by dellbeat** [comment]
我试一下用ANDROID_PHONE可不可以

**Comment by dellbeat** [comment]
试了一下`2.7.0`的`ANDROID_PHONE`协议也不行 和上述描述一样
可能得等依赖升级到`2.8.0-RC`才可以验证了

**Comment by dellbeat** [comment]
问了一下`MAH`那边 没有`不兼容更改`就可以升级
现在已经下载了`2.8.0-RC`的源码包
但由于自己是.NET开发者 对Java和Kotlin不是很了解
所以想问下如何将源码包编译成格式为jar的包 还望指教 非常感谢

**Comment by Him188** [comment]
一般情况下不需要打包 JAR

**Comment by dellbeat** [comment]
> 一般情况下不需要打包 JAR

因为我是通过MAH来的 然后MAH里的core是以jar包的形式来的 所以还是需要打jar包

**Comment by dellbeat** [comment]
> 2.8.0-RC测试无问题，请更新至2.8.0-RC后再次验证

通过升级插件进行了验证 确认无该问题
