### ISSUE TITLE
好友语音发送无效

### ISSUE THREAD

**Issue by SugarFatFree** [mamoe/mirai#1653]
用ffmpeg将mp3转码成amr格式，群里发送语音没有问题，好友语音会出现语音裂痕图片，手机QQ上会出现红色感叹号。

- mirai-core: `2.8.0-RC` 
- bot-protocol: `ANDROID_PHONE`

**Comment by Karlatemp** [comment]
好友语音不支持amr, silk only, see https://github.com/project-mirai/mirai-silk-converter
