### ISSUE TITLE
填写ticket，登陆失败

### ISSUE THREAD

**Issue by 2662419405** [mamoe/mirai#1654]
系统centos7.6

滑动验证码获取到ticket失败

Exception in thread "DefaultDispatcher-worker-1" net.mamoe.mirai.network.WrongPasswordException: Err
or(bot=Bot(2373767280), code=237, title=禁止登录, message=当前上网环境异常，请更换网络环境或在常用设
备上登录或稍后再试。, errorInfo=), tips=若频繁出现, 请尝试开启设备锁

**Comment by Karlatemp** [comment]
https://cn.pornhub.com/view_video.php?viewkey=ph60402e38f18d9

**Comment by Karlatemp** [comment]
https://mirai.mamoe.net/topic/223/%E6%97%A0%E6%B3%95%E7%99%BB%E5%BD%95%E7%9A%84%E4%B8%B4%E6%97%B6%E5%A4%84%E7%90%86%E6%96%B9%E6%A1%88

**Comment by Karlatemp** [comment]
Long time no reply
