### ISSUE TITLE
支持 QQ 频道消息

### ISSUE THREAD

**Issue by yujincheng08** [mamoe/mirai#1656]
8.8.11 以后版本的手Q（也包括 IOS 和 ipad）和PC内测版（http://dldir1.qq.com/qqfile/qq/PCQQ9.5.2/QQ9.5.2.27899.exe ）已经支持频道。希望支持频道消息。
频道是 GUILD，并且每个频道有一个 ID。频道内有子频道，相当于一个小群。可以设置部分人发言、发言频率等。界面上跟 discord 很相似。

可以通过以下链接加入频道：
https://qun.qq.com/qqweb/qunpro/share?_wv=3&_wwv=128&inviteCode=1nL0F4&from=114514&biz=ka

**Comment by yujincheng08** [comment]
似乎可以参考这个 https://blog.hoshi.tech/archives/89/

**Comment by yujincheng08** [comment]
研究了一下，频道相关的通讯跟其他消息**不是同一个协议**。这个协议在手机QQ上都是通过一个 `com.tencent.gprosdk.IGProSdkWrapper` 接口实现，而安装包中唯一实现这个接口的类是 `com.tencent.gprosdk.IGProSdkWrapper$CppProxy`。故名思意，都是在 native 代码中实现的。
以下是相关文件
[IGProSdkWrapper$CppProxy.zip](https://github.com/mamoe/mirai/files/7490990/IGProSdkWrapper.CppProxy.zip)
[libgpro.zip](https://github.com/mamoe/mirai/files/7490991/libgpro.zip)


在 PC 端，则是通过 gpro.win32.node 这个 dll 进行通讯，所以也是在 native 进行通讯。

**Comment by LittleTurtle2333** [comment]
活捉西大师，同求此功能

**Comment by Xuwznln** [comment]
已经看有人实现了，强烈希望mirai支持更新

**Comment by yujincheng08** [comment]
> 已经看有人实现了，强烈希望mirai支持更新

有实现了？在哪？

**Comment by Xuwznln** [comment]
他们频道内机器人的tag叫冰玉bot，具体的就不知道怎么实现的了

**Comment by Karlatemp** [comment]
目前没有计划去整一个还在处于dev的东西

**Comment by Xuwznln** [comment]
QQ手机入口，PC上的入口都有了，而且和联系人并列，看来是个重要功能，另外内测(半公测)，为了兼容各个版本不太会改消息推送方式了。还是很希望有的

**Comment by LittleTurtle2333** [comment]
单个QQ频道人数可达10w。比群聊机器人好用多了![image](https://user-images.githubusercontent.com/32336368/141603679-f16941e5-2b74-4f6f-962f-b217c10d5a1e.png)

**Comment by LittleTurtle2333** [comment]
> 他们频道内机器人的tag叫冰玉bot，具体的就不知道怎么实现的了

go-cqhttp已经支持频道功能了

**Comment by LittleTurtle2333** [comment]
> 目前没有计划去整一个还在处于dev的东西

隔壁go-cqhttp已经上线了

**Comment by Kloping** [comment]
我擦?

**Comment by KinomotoKi** [comment]
同求此功能

**Comment by yoonching** [comment]
频道这块，官方自己出了一些API呀。
看这里---> https://bot.q.qq.com/wiki/develop/api/
在我评论的时候，有了nodejs和go的 sdk，官方还会出python的sdk。

**Comment by Xuwznln** [comment]
> 频道这块，官方自己出了一些API呀。 看这里---> https://bot.q.qq.com/wiki/develop/api/ 在我评论的时候，有了nodejs和go的 sdk，官方还会出python的sdk。

官方的API就好比微信公众号，实在是太实在了。

**Comment by LittleTurtle2333** [comment]
> 频道这块，官方自己出了一些API呀。
> 
> 看这里---> https://bot.q.qq.com/wiki/develop/api/
> 
> 在我评论的时候，有了nodejs和go的 sdk，官方还会出python的sdk。

主要是他只开放给企业开发者使用，不允许个人开发者申请

**Comment by NoMathExpectation** [comment]
这个功能有生之年还能上线吗

**Comment by Moyulingjiu** [comment]
同希望支持

**Comment by Pika-Lee** [comment]
目前已经有多款机器人框架支持了QQ频道，希望mirai也能早日支持~

**Comment by Pika-Lee** [comment]
> > 频道这块，官方自己出了一些API呀。
> > 看这里---> https://bot.q.qq.com/wiki/develop/api/
> > 在我评论的时候，有了nodejs和go的 sdk，官方还会出python的sdk。
> 
> 主要是他只开放给企业开发者使用，不允许个人开发者申请

刚才看了下已经开放给个人了，不过需要填问卷申请~

**Comment by Moyulingjiu** [comment]
> 

那个个人开发问卷审核很严格，很多东西都不能做。基本等于没用。如果官方真的好用的话，甚至像微信小程序那样的审核机制都不至于来用第三方的东西

**Comment by KinomotoKi** [comment]
> > 
> 
> 那个个人开发问卷审核很严格，很多东西都不能做。基本等于没用。如果官方真的好用的话，甚至像微信小程序那样的审核机制都不至于来用第三方的东西

完全同意……

**Comment by Pika-Lee** [comment]
> > 
> 
> 那个个人开发问卷审核很严格，很多东西都不能做。基本等于没用。如果官方真的好用的话，甚至像微信小程序那样的审核机制都不至于来用第三方的东西

上周提交了QQ频道机器人的个人开发者申请，今天收到审核通过的通知。
![JCD~}F}7ZV}GN5$8 {L`BXG](https://user-images.githubusercontent.com/23114990/157197581-3e022e40-dbb0-4044-b2b7-829df8a7747a.png)
看了下QQ频道官方给的API文档，接口还是蛮丰富的。

https://bot.q.qq.com/wiki/develop/api/#%E6%8E%A5%E5%8F%A3%E8%AF%B4%E6%98%8E

大家感兴趣的话也可以研究研究哈，也希望mirai也能早日支持QQ频道~

**Comment by b3601993** [comment]
到现在2023年了，mriai还不支持频道吗？我今天就想用

**Comment by Pika-Lee** [comment]
> 到现在2023年了，mriai还不支持频道吗？我今天就想用

因为到现在频道都还在内测~~

**Comment by char-46** [comment]
> > 到现在2023年了，mriai还不支持频道吗？我今天就想用
> 
> 因为到现在频道都还在内测~~

甚至有人在频道被骗了钱了都还在内测，，QQ不知道在想什么……
