### ISSUE TITLE
支持监听群打卡事件

### ISSUE THREAD

**Issue by b3758163** [mamoe/mirai#1663]
我想要统计群中成员的打卡记录，没有找到相应方法，但是控制台输出了蓝色的 Unknown Transformers528消息

**Comment by sandtechnology** [comment]
请问事件的具体设计？

**Comment by b3758163** [comment]
我的业务需求是：群组中 手机qq左上角有个打卡功能，群成员点击打卡之后，我希望能监听到用户的打卡事件，事件中包含群号，用户id。目前java版 mirai 控制台能够监听到打卡事件，但是并未区分这个事件， 希望你能能够提供区别这个事件的方法，或者是能够实现对打卡时间的监听事件 
以下是打卡事件发生时，机器人监听到的内容
`2021-11-08 20:41:06 D/Net 3144427172: Unknown Transformers528 0x14 template
templId=10036
PermList=[TemplParam#1563686114 {
            name=6D 71 71 5F 75 69 6E
            value=38 36 31 35 33 38 38 30 33
    }, TemplParam#1563686114 {
            name=6D 71 71 5F 6E 69 63 6B
            value=E7 92 83 E9 B1 BC E6 B5 85 E6 88 88
    }, TemplParam#1563686114 {
            name=75 73 65 72 5F 73 69 67 6E
            value=E4 BB 8A E6 97 A5 E7 AC AC 31 E4 B8 AA E6 89 93 E5 8D A1 20
    }, TemplParam#1563686114 {
            name=72 61 6E 6B 5F 69 6D 67
            value=68 74 74 70 73 3A 2F 2F 71 7A 6F 6E 65 73 74 79 6C 65 2E 67 74 69 6D 67 2E 63 6E 2F 71 7A 6F 6E 65 2F 73 70 61 63 65 5F 69 74 65 6D 2F 6D 61 74 65 72 69 61 6C 2F 51 51 50 75 6E 63 68 49 6E 2F 6F 72 67 2F 34 2F 32 30 36 36 31 32 2F 31 5F 32 78 5F 63 70 79 2E 70 6E 67
    }, TemplParam#1563686114 {
            name=6A 75 6D 70 5F 75 72 6C
            value=6D 71 71 61 70 69 3A 2F 2F 74 72 6F 6F 70 74 6F 67 65 74 68 65 72 2F 6F 70 65 6E 3F 73 72 63 5F 74 79 70 65 3D 69 6E 74 65 72 6E 61 6C 26 61 6D 70 3B 76 65 72 73 69 6F 6E 3D 31
    }, TemplParam#1563686114 {
            name=73 69 67 6E 5F 77 6F 72 64
            value=20 E6 88 91 E4 B9 9F E8 A6 81 E6 89 93 E5 8D A1
    }]`

**Comment by sandtechnology** [comment]
~~我的意思是 事件需要包括什么内容~~
打卡是有第一名 第二名 第三名和其他的 需要包括吗 如果包括 你希望的访问方式是？

**Comment by b3758163** [comment]
目前我的需求只有打卡的 groupId 以及打卡的memberId即可

**Comment by b3758163** [comment]
在隔壁群听到你们讨论打卡的命名问题了 非常非常感谢 o(*￣︶￣*)o
