### ISSUE TITLE
这是Bug吗  whileSelectMessages无法使用Message的参数

### ISSUE THREAD

**Issue by MOldtime** [mamoe/mirai#1665]
>  whileSelectMessages {
                                "stop" {
                                    sender.sendMessage("已取消")
                                    false // 停止循环
                                }
                                "Finish" {
                                    swit = true
                                    false
                                }
                                default {
                                    this.message
                                    true // 继续循环
                                }
                                timeout(60000) {
                                    sender.sendMessage("已超时")
                                    false
                                }
                            }

![image](https://user-images.githubusercontent.com/38435967/140929143-901c9001-f753-498c-b2eb-b4115d5baf6e.png)
太迷惑了
版本是 `2.7.1`

**Comment by Karlatemp** [comment]
ask buglin

**Comment by MOldtime** [comment]
> ask buglin

不懂

**Comment by Him188** [comment]
是 Kotlin 的 bug

**Comment by MOldtime** [comment]
> 是 Kotlin 的 bug

好的 谢谢大佬
