### ISSUE TITLE
添加 `nextEventAndIntercept`

### ISSUE THREAD

**Issue by Nambers** [mamoe/mirai#1668]
在GroupMessageEvent中注册的nextEvent<GroupMessage>无法处于高优先级

测试代码:
```kotlin
eventChannel.subscribeAlways<GroupMessageEvent> {
            logger.info("1" + this.message.contentToString())
            nextEvent<GroupMessageEvent>(-1, EventPriority.HIGHEST) {
                it.bot.id == this.bot.id && it.group.id == this.group.id && it.sender.id == this.sender.id
            }.let{
                it.intercept()
                logger.info("2" + it.message.contentToString())
            }
}
```
日志:
```
2021-11-14 21:10:10 I/MiraiCP: 1a
2021-11-14 21:10:10 V/Bot 692928873: [Test(788189105)] Eritque arcus(1930893235) -> a
2021-11-14 21:10:12 I/MiraiCP: 1b
2021-11-14 21:10:12 V/Bot 692928873: [Test(788189105)] Eritque arcus(1930893235) -> b
2021-11-14 21:10:12 I/MiraiCP: 2b
```
日志里 `b` 信息触发了1和2，然后顺序是 1 -> 2，推测是没有处于高优先级导致这个顺序然后没有拦截

#### 复现

任意群消息

#### 版本及相关选项选择

- mirai-core: `2.8.0-RC` 
- bot-protocol: `ANDROID_PHONE`

**Comment by Karlatemp** [comment]
执行 `it.intercept()` 时已经退出事件总栈， as-designed

**Comment by Nambers** [comment]
> 执行 `it.intercept()` 时已经退出事件总栈， as-designed

主要是为什么`b`会触发1

**Comment by Karlatemp** [comment]
执行 `it.intercept()` 的时候上下文不在事件总栈, 后续监听器已经被触发了, 你应该在 filter 那执行 intercept

**Comment by Nambers** [comment]
> 执行 `it.intercept()` 的时候上下文不在事件总栈, 后续监听器已经被触发了, 你应该在 filter 那执行 intercept

在filter里面 if(state){intercept(); return true;} 这样子? 行吧不太直观看起来
