### ISSUE TITLE
初始化项目拉包404

### ISSUE THREAD

**Issue by CharlieJ0hn** [mamoe/mirai#167]
初始化项目拉包404
无论代理还是镜像
![image](https://user-images.githubusercontent.com/9925064/77783901-9b3a9580-7094-11ea-9f9d-d3a28030e728.png)

**Comment by ZeshawnXiao** [comment]
将idea kotlin插件的Update Channel切换到Early Access Preview 1.4.x 
![image](https://user-images.githubusercontent.com/30542443/77786681-2d449d00-7099-11ea-9ba2-c3d9d1e133f6.png)
 并在repositories中添加
maven { url 'https://dl.bintray.com/kotlin/kotlin-eap' }

**Comment by Him188** [comment]
在考虑换回1.3.71

**Comment by Him188** [comment]
https://gist.github.com/Him188/9f395d058b89226d412a200bdd0595be
