### ISSUE TITLE
MessageEvent中的MessageChain可以更改，可能造成问题或者误解

### ISSUE THREAD

**Issue by khjxiaogu** [mamoe/mirai#1676]
对MessageEvent等地方获取的信息进行更改并不会产生任何异常，可能造成问题。

```
```

#### 复现

在MessageEvent中更改getMessage()

#### 版本及相关选项选择

- mirai-core: `2.8.0` 
- bot-protocol: `ANDROID_PHONE` 

#### 网络日志

```

```

**Comment by khjxiaogu** [comment]
经过检查此事件获取的MessageChain并不存在MessageSource对象

**Comment by Karlatemp** [comment]
What the meaning of `更改getMessage()`? Provide the minimum reproducible code please.

**Comment by khjxiaogu** [comment]
> What the meaning of `更改getMessage()`? Provide the minimum reproducible code please.

Like getMessage().removeIf(xxx) or something else.
