### ISSUE TITLE
获取QuoteReply中MessageSource的originalMessage时似乎错误地调用了消息元素的contentToString

### ISSUE THREAD

**Issue by Deficuet** [mamoe/mirai#1684]
Forum里没人理我（
如题；我在pc客户端可见被回复的包含一张图片/表情，但是获取到的originalMessage对应的部分是纯文本"[图片]"或者"[动画表情]"
推测是调用过对应消息元素的contentToString
![image](https://user-images.githubusercontent.com/36525579/142357013-c4e3e5a0-343d-4760-be45-6df53f87717b.png)
![image](https://user-images.githubusercontent.com/36525579/142357026-403456de-0160-41cc-abc6-fe74c79ce75a.png)

```

```

#### 复现

一个ForwardMessage，包含一条回复其他消息的消息，接收后尝试获取被回复的消息链即可

#### 版本及相关选项选择

- mirai-core: `2.8.0` 
- bot-protocol: `ANDROID_PHONE`,`ANDROID_WATCH`

**Comment by sandtechnology** [comment]
works as intended, 显示的本来就是客户端实现，如果本地没有这条被引用的消息也会显示这种文字

**Comment by Him188** [comment]
这是服务器提供的信息
