### ISSUE TITLE
无法发送群消息，可以发送好友消息

### ISSUE THREAD

**Issue by a2362168** [mamoe/mirai#1690]
11/18 号开始出现的问题，之前运行了几个月状况良好。
机器人无法在群里发送消息，好友消息可以正常发送，
使用官方QQ登录账号可以正常发送群消息。

我开始怀疑是风控，把我一直用的QQ号给机器人登录。登录后几小时之内
是正常的，然后再次出现相同情况

这个机器人运行在搬瓦工VPS上面，不确定是否是IP导致的风控问题

```
这里还可以正常发送消息：
[0m2021-11-19 17:43:20 V/Bot 879112070: [ventre测试群(867206822)] ventre(3279994851) -> [mirai:at:879112070] 切克闹[0m
[0m2021-11-19 17:43:24 V/Net 879112070: Send: MessageSvc.PbSendMsg(MessageSvc.PbSendMsg)[0m
[0m2021-11-19 17:43:24 V/Net 879112070: Recv: MessageSvc.PbSendMsg[0m
[0m2021-11-19 17:43:24 V/Bot 879112070: Group(867206822) <- [mirai:at:3279994851] 药药~切克闹~[0m

到这里就失败了：
[0m2021-11-19 19:17:37 V/Bot 879112070: Group(556208166) <- [mirai:image:{0AF0E2CA-3309-2D91-5918-1A5984DB2620}.jpg][0m

这里有3条消息，第一条消息正常发送了，后面2条看不见。
ChatHandler.handleMessage
[0m2021-11-19 20:11:46 V/Bot 879112070: [ventre测试群(867206822)] ventre(3279994851) -> [mirai:at:879112070] [0m
[0m2021-11-19 20:11:50 V/Net 879112070: Send: MessageSvc.PbSendMsg(MessageSvc.PbSendMsg)[0m
[0m2021-11-19 20:11:50 V/Net 879112070: Recv: MessageSvc.PbSendMsg[0m
[0m2021-11-19 20:11:50 V/Bot 879112070: Group(867206822) <- [mirai:at:3279994851] 未获取到相关信息[0m
ChatHandler.handleMessage
[0m2021-11-19 20:14:31 V/Bot 879112070: [ventre测试群(867206822)] ventre(3279994851) -> [mirai:at:879112070] 来点饼干[0m
[0m2021-11-19 20:14:35 V/Net 879112070: Send: MessageSvc.PbSendMsg(MessageSvc.PbSendMsg)[0m
[0m2021-11-19 20:14:36 V/Net 879112070: Recv: MessageSvc.PbSendMsg[0m
[0m2021-11-19 20:14:38 V/Bot 879112070: Group(867206822) <- [mirai:at:3279994851] 笑容很电很可爱啊啊，x)[0m
ChatHandler.handleMessage
[0m2021-11-19 20:15:38 V/Bot 879112070: [ventre测试群(867206822)] ventre(3279994851) -> [mirai:at:879112070] 咕咕咕咕[0m
[0m2021-11-19 20:15:42 V/Net 879112070: Send: MessageSvc.PbSendMsg(MessageSvc.PbSendMsg)[0m
[0m2021-11-19 20:15:42 V/Net 879112070: Recv: MessageSvc.PbSendMsg[0m
[0m2021-11-19 20:15:45 V/Bot 879112070: Group(867206822) <- [mirai:at:3279994851] 饿了么[0m

完整log：
[https://github.com/a2362168/qqrobot/blob/main/taskfile-result-1637295183-8883.log](url)
```

#### 复现

在搬瓦工VPS上面登录，正常使用大概8小时后出现。

#### 版本及相关选项选择

- mirai-core: `2.8.1` 
- bot-protocol: `ANDROID_PHONE` 

#### 网络日志

```
我不太清楚在哪里找网络日志，不过从现象上来看，不是网络导致的问题。
因为好友消息一直是正常的。
```

#### 补充信息

目前我实验一下，在家里登录机器人，不在搬瓦工VPS，是否还有问题。

**Comment by Him188** [comment]
尝试 https://github.com/mamoe/mirai/blob/dev/docs/Bots.md#%E5%88%87%E6%8D%A2%E5%BF%83%E8%B7%B3%E7%AD%96%E7%95%A5

**Comment by a2362168** [comment]
感谢，我去实验下

**Comment by a2362168** [comment]
> 尝试 https://github.com/mamoe/mirai/blob/dev/docs/Bots.md#%E5%88%87%E6%8D%A2%E5%BF%83%E8%B7%B3%E7%AD%96%E7%95%A5

我试验了3种心跳策略，都是一样的情况。 Bot 闲置一段时间后，发消息返回成功但群内收不到。
出现这种情况之后有时重登录mirai也还是不行，需要用QQ官方客户端登录一下，才可以重新发群消息。

register log：
[https://github.com/a2362168/qqrobot/blob/main/taskfile-result-1637335305-3884.log](url)

从这里开始没收到：
[0m2021-11-20 08:26:44 V/Bot 879112070: [ventre测试群(867206822)] ventre(3279994851) -> [mirai:at:879112070] [0m
[0m2021-11-20 08:26:48 V/Net 879112070: Send: MessageSvc.PbSendMsg(MessageSvc.PbSendMsg)[0m
[0m2021-11-20 08:26:49 V/Net 879112070: Recv: MessageSvc.PbSendMsg[0m
[0m2021-11-20 08:26:51 V/Bot 879112070: Group(867206822) <- [mirai:at:3279994851] 未获取到相关信息[0m

none log：
[https://github.com/a2362168/qqrobot/blob/main/taskfile-result-1637395372-7337.log](url)

从这里开始没收到：
[0m2021-11-20 19:10:46 V/Bot 879112070: [ventre测试群(867206822)] ventre(3279994851) -> [mirai:at:879112070][0m
[0m2021-11-20 19:10:46 V/Net 879112070: Recv: MessageSvc.PbSendMsg[0m
[0m2021-11-20 19:10:49 V/Bot 879112070: Group(867206822) <- 欢迎使用涩图机器人，基本使用方法：\n@Ventre 关键字  目前已有的关键字：\n1. 涩图\n2. 色图\n3. 聊天\n如果要查看具体功能，请输入 @Ventre 关键字 help\n例子  @Ventre 涩图 help[0m

我感觉和IP还是有点关系，之后我再试一下。

**Comment by a2362168** [comment]
前面3次失败之后，我又把心跳策略修改回默认的STAT_HB。 然后在家电脑挂了几个小时正常，接着又放到服务器上，目前运行3，40个小时，没啥问题。
我没做过什么特殊的操作，不知道为啥突然就好了。 中间有使用几次官方QQ登录过，不过之前失败的时候也有这个操作。
device.json也没更新。总之目前是恢复正常了。

**Comment by AlanFangchang** [comment]
我也是类似的问题，然后修改心跳策略+删除cache目录+重新登录解决了，目前稳定运行了五天了

**Comment by landuo** [comment]
> 我也是类似的问题，然后修改心跳策略+删除cache目录+重新登录解决了，目前稳定运行了五天了

我删除了cache目录之后重启也正常了

**Comment by changjingzhi** [comment]
cache目录是删除里面的文件保留文件cache 吗？

**Comment by EidenRitto** [comment]
我也有同样的问题

**Comment by EidenRitto** [comment]
> 我也有同样的问题

 过了一晚上第二天自动好了
