### ISSUE TITLE
日志出现 logger name 为 `null` 的情况

### ISSUE THREAD

**Issue by Karlatemp** [mamoe/mirai#1691]
还有这两个日志内容少了logger的identity也看看吧
![image](https://user-images.githubusercontent.com/35139537/142601353-c05342cc-84ce-4f07-9066-a59b7cf1addd.png)

_Originally posted by @Nambers in https://github.com/mamoe/mirai/issues/1687#issuecomment-973912913_

**Comment by Karlatemp** [comment]
似乎dev没出现这个问题

**Comment by Nambers** [comment]
> 

是mirai-core v2.8.0

**Comment by Karlatemp** [comment]
For mamoe:

Caused by console not core
