### ISSUE TITLE
调用mirai的一些涉及CoroutineScope的API报错：Cannot access 'kotlinx.coroutines.CoroutineScope' 

### ISSUE THREAD

**Issue by zhaodice** [mamoe/mirai#1697]
引入
implementation "net.mamoe:mirai-core:2.9.0-M1"
implementation "net.mamoe:mirai-console:2.9.0-M1"
的时候，使用继承CoroutineScope的mirai API代码编译器会提示：
”Cannot access 'kotlinx.coroutines.CoroutineScope' which is a supertype of 'net.mamoe.mirai.console.plugin.jvm.JvmPlugin'. Check your module classpath for missing or conflicting dependencies“

这个不是mirai的问题，我重装完一次系统就这样了，怎么调都调不好，想问一下问题可能出在哪里

**Comment by zhaodice** [comment]
似乎仅仅引入
”implementation "net.mamoe:mirai-core:2.9.0-M1"“
kotlinx.coroutines.CoroutineScope() 就会报这个错误...

**Comment by zhaodice** [comment]
好吧最后我全部换成jar解决了

**Comment by Him188** [comment]
这个是 Kotlin 的 bug，挺久了
