### ISSUE TITLE
无法从 static 上下文引用非 static 方法 'sendMessage(net.mamoe.mirai.message.data.Message)' 

### ISSUE THREAD

**Issue by WutzuBert** [mamoe/mirai#1700]
### 问题描述

如题

### 复现

当我打出Contact.sendMessage(message);时，IDEA提示无法从 static 上下文引用非 static 方法 'sendMessage(net.mamoe.mirai.message.data.Message)' 
据说要实例化对象，但是要实例化哪个？

### mirai-core 版本

2.8.2

### bot-protocol

ANDROID_PAD

### 其他组件版本

mirai-console-2.8.2

### 系统日志

```text
无
```

### 网络日志

```text
无
```

**Comment by Karlatemp** [comment]
https://www.runoob.com/java/java-tutorial.html
https://www.kotlincn.net/docs/reference/
https://github.com/mamoe/mirai/blob/dev/docs/Messages.md

**Comment by Him188** [comment]
你需要从 bot 或事件获取到 contact 对象
