### ISSUE TITLE
机器人无法获取其他端的同步消息(2.8.0开始引入的bug)

### ISSUE THREAD

**Issue by ChanFeei** [mamoe/mirai#1702]
### 问题描述

【注：该BUG从2.8.0后引入，在2.7.1之前没问题。】

用机器人的qq号给好友发消息，机器人无法同步这个消息，也无法捕获到MessageSyncEvent，代码：
			@EventHandler
			public ListeningStatus onSyncMessage(MessageSyncEvent event) {
				System.out.println("Event: "+event.toString());
				return ListeningStatus.LISTENING;
			}

### 复现

1，用ANDROID_PAD启动机器人
2，用这个机器人的账密登陆手机QQ
3，用手机qq给其他好友发送一条消息
4，问题出现：机器人无法抛出MessageSyncEvent

### mirai-core 版本

2.8.0

### bot-protocol

ANDROID_PAD

### 其他组件版本

无

### 系统日志

```text
[0m2021-11-28 15:24:48 V/Net 3625884478: Recv: OnlinePush.PbC2CMsgSync[0m
[0m2021-11-28 15:24:57 V/Net 3625884478: Recv: OnlinePush.PbC2CMsgSync[0m
```

### 网络日志

```text
无
```

**Comment by Him188** [comment]
已在 dev 2.9.0-RC 5b16414e9ec04b5a9e27dd0cdceb899b8964ed3e 复现

**Comment by Him188** [comment]
Target: 2.8.3, 2.9.0-RC

**Comment by Him188** [comment]
Note:
![image](https://user-images.githubusercontent.com/12100985/143781433-bf5b53d6-911f-43a7-bd77-319867d37e57.png)

network/notice/priv/PrivateMessageProcessor.kt:75

**Comment by Him188** [comment]
和 #1624 相同
