### ISSUE TITLE
接收不到戳一戳消息

### ISSUE THREAD

**Issue by wyapx** [mamoe/mirai#1706]
### 问题描述

如题，core升级到2.8.2后收不到NudgeEvent

### 复现

core升级至2.8.2

### mirai-core 版本

2.8.2

### bot-protocol

ANDROID_WATCH

### 其他组件版本

mah 2.3.3

### 系统日志

```text
ignore
```

### 网络日志

```text
ignore
```

**Comment by Karlatemp** [comment]
服务器不会在 `ANDROID_WATCH` 下发戳一戳相关的信息

**Comment by wyapx** [comment]
切换到Android pad协议同样无法接收

**Comment by 250king** [comment]
mirai-core 版本
2.9.0-M

同样没有收到被戳事件，控制台也没有输出相关记录
![Screenshot_2021-12-12-00-58-34-94](https://user-images.githubusercontent.com/61256966/145685055-977be403-26dd-4a52-82ee-7f82515f8f42.jpg)
![image](https://user-images.githubusercontent.com/61256966/145685074-7faa5641-f26d-4188-a51c-71960aa8caf1.png)
