### ISSUE TITLE
这是一个 自动通过加群申请并自动迎新 的实例监听器。   失败

### ISSUE THREAD

**Issue by jianxtop** [mamoe/mirai#1709]
java.lang.IllegalStateException: 在 解析 NewContact.SystemMsgNewGroup, subType=5, groupMsgType=6 时遇到了意料之中的问题. 请完整复制此日志提交给 mirai: https://github.com/mamoe/mirai/issues/new   并描述此时机器人是否被踢出群等 调试信息: SystemMsg#1096121498 {

未被踢出群

**Comment by jianxtop** [comment]
打扰了，机器人不是管理员...

**Comment by 70687547** [comment]
是群管理员呢

**Comment by jianxtop** [comment]
是群管理员呢。。。
![image](https://user-images.githubusercontent.com/46195426/144755308-ce911597-4e6f-47b6-a78a-6651e9d9b2ef.png)

**Comment by MrXiaoM** [comment]
建议把调试信息完整发出

~~虽然我解决不了你的问题但是我觉得至少要把解决问题需要的资料提供出来~~

**Comment by Him188** [comment]
请使用 https://github.com/mamoe/mirai/issues/new?assignees=&labels=question&template=bug.yml 提交问题
