### ISSUE TITLE
为什么语音上传不行的？请教一下

### ISSUE THREAD

**Issue by ltiaw** [mamoe/mirai#1710]
### 问题描述

python 用http api
代码：
headers = {
                        'content-type': "multipart/form-data; boundary=--312312321ndary7MA4YWxkTrZu0gW--",
                        'cache-control': "no-cache",
                    }

                    files = {
                              "sessionKey": sessionKey,
                              "type": "group",
                              "voice": "http://m7.music.126.net/20211206154123/6910e5b544f1cf4c50134556389cc449/ymusic/555d/0208/0e53/b7ebcc77925bade91332995f1c4ed042.mp3"
                            }

                    r = requests.post("http://192.168.1.225:8080/uploadVoice", headers=headers, files=files)
                    print("上传语音返回结果：", r.text)

然后返回的结果是：
{"code":3,"msg":"Session失效或不存在"}

或者是把voice：改为本机文件夹也是一样结果
files = {
                              "sessionKey": sessionKey,
                              "type": "group",
                              "voice": "C:\\Users\\Administrator\\Downloads\\123dd.mp3"
                            }

{"code":3,"msg":"Session失效或不存在"}

### 复现

python 用http api
代码：
headers = {
                        'content-type': "multipart/form-data; boundary=--312312321ndary7MA4YWxkTrZu0gW--",
                        'cache-control': "no-cache",
                    }

                    files = {
                              "sessionKey": sessionKey,
                              "type": "group",
                              "voice": "http://m7.music.126.net/20211206154123/6910e5b544f1cf4c50134556389cc449/ymusic/555d/0208/0e53/b7ebcc77925bade91332995f1c4ed042.mp3"
                            }

                    r = requests.post("http://192.168.1.225:8080/uploadVoice", headers=headers, files=files)
                    print("上传语音返回结果：", r.text)

然后返回的结果是：
{"code":3,"msg":"Session失效或不存在"}

或者是把voice：改为本机文件夹也是一样结果
files = {
                              "sessionKey": sessionKey,
                              "type": "group",
                              "voice": "C:\\Users\\Administrator\\Downloads\\123dd.mp3"
                            }

{"code":3,"msg":"Session失效或不存在"}

### mirai-core 版本

2.8.2

### bot-protocol

ANDROID_PHONE

### 其他组件版本

mirai-http-api.2.3.3

### 系统日志

```text
{"code":3,"msg":"Session失效或不存在"}
```

### 网络日志

```text
{"code":3,"msg":"Session失效或不存在"}
```

**Comment by Karlatemp** [comment]
please report to mah not mirai-core

**Comment by Him188** [comment]
@ryoii any ideas?

**Comment by Him188** [comment]
该问题属于 MAH, 请反馈到 https://github.com/project-mirai/mirai-api-http

**Comment by ryoii** [comment]
参考 [project/mirai-api-http#493](https://github.com/project-mirai/mirai-api-http/issues/493)
