### ISSUE TITLE
AudioToSilkService 中的 convert 不会自动关闭,导致资源泄露

### ISSUE THREAD

**Issue by zhaodice** [mamoe/mirai#1714]
```
override suspend fun convert(source: ExternalResource): ExternalResource {
  ... 
  return ***.toExternalResource("silk").toAutoCloseable()
}
```
其中若是在return 新的ExternalResource 之前没有 source.close() ，则会报内存泄漏错误
所以可以考虑加一个，如果没有 `return source;` 这种情况则自动`source.close()`

**Comment by Karlatemp** [comment]
在 AudioToSilkService 的实现中已经注明了如果是经过了转换需要在 service 层执行这一步骤， 这是预期的, 因为但靠 convert 无法分辨资源是否经过处理

**Comment by zhaodice** [comment]
> 

可以判断，如果 source == convert(source) （指针相同），说明它肯定是直接return source;的，否则，肯定是toExternalResource的新资源而丢弃了source，那么此时的旧source就必须close()

**Comment by zhaodice** [comment]
> 在 AudioToSilkService 的实现中已经注明了如果是经过了转换需要在 service 层执行这一步骤， 这是预期的, 因为但靠 convert 无法分辨资源是否经过处理

可以判断，如果 source == convert(source) （指针相同），说明它肯定是直接return source;的，否则，肯定是return了toExternalResource的新资源而丢弃了参数传递的source，那么此时参数所传递的source就必须close()

**Comment by zhaodice** [comment]
当然，考虑到`.toAutoCloseable()`可能会改变原有的指针，导致判断失效，可以再判断一下.toAutoCloseable()之前的对象的指针（如果有持有）？

**Comment by Karlatemp** [comment]
目前设计已经确定再次修改将会导致全部自行实现此接口的实现同步进行修改，这不太好

**Comment by zhaodice** [comment]
> 目前设计已经确定再次修改将会导致全部自行实现此接口的实现同步进行修改，这不太好

这样啊，那就不用改了吧，也不是什么大问题
