### ISSUE TITLE
bot.close()时不会通知到BotOfflineEvent

### ISSUE THREAD

**Issue by xhzq233** [mamoe/mirai#1717]
能否添加进`bot.close()`里

**Comment by Him188** [comment]
经研究, 这个问题的真正原因是名为 "BotOfflineEventBroadcaster" 的 `StateChangedObserver` (1) 在监听到 OK -> CLOSED 变化时尝试调用 `EventDispatcherImpl#broadcastAsync` (2) 广播 `BotOfflineEvent.Active`, 但由于 `EventDispatcher` 的 `CoroutineScope` 已经关闭, job 不会启动.

----
References:
- (1): [QQAndroidBot.kt:123](https://github.com/mamoe/mirai/blob/033a10daaf6eb2158e111ba90adee07a336494d6/mirai-core/src/commonMain/kotlin/QQAndroidBot.kt#L123)
- (2): net.mamoe.mirai.internal.network.components.EventDispatcherImpl#broadcastAsync(net.mamoe.mirai.event.Event, kotlin.coroutines.CoroutineContext)
