### ISSUE TITLE
mirai是否使用log4j2

### ISSUE THREAD

**Issue by xmxmxmmmm** [mamoe/mirai#1726]
### 问题描述

百度log4j2远控漏洞

### 复现

百度log4j2远控漏洞

### mirai-core 版本

2.8.2

### bot-protocol

ANDROID_PHONE

### 其他组件版本

/

### 系统日志

```text
/
```

### 网络日志

```text
/
```

### 补充信息

/

**Comment by uebian** [comment]
此问题已修复 #1724

**Comment by 250king** [comment]
我已经做了测试，的确是可以操控
https://www.bilibili.com/video/BV1d3411s762

**Comment by wyapx** [comment]
> 此问题已修复 #1724

没修复哦，因为压根不存在
~~除非闲着没事塞个log4j-core.jar进去~~

**Comment by Samarium150** [comment]
Mirai默认使用自己内建的logger [MiraiLogger](https://github.com/mamoe/mirai/blob/dev/mirai-core-api/src/commonMain/kotlin/utils/MiraiLogger.kt)

**Comment by Him188** [comment]
mirai 默认用自己实现的日志库, 不受漏洞影响. 如果你使用了 mirai-logging-log4j, 那就会有影响
在 2.9.0-RC 会更新 log4j 版本

**Comment by xmxmxmmmm** [comment]
用dnslog试了下 抓到一堆ip

> 我已经做了测试，的确是可以操控 https://www.bilibili.com/video/BV1d3411s762

看了下 是腾讯云的解析服务器吧那个ip 倒是我抓到一个别的机器人的ip
