### ISSUE TITLE
群撤回消息事件会触发两次

### ISSUE THREAD

**Issue by Sincky** [mamoe/mirai#173]
## 问题

订阅群撤回消息事件会触发两次

![image](https://user-images.githubusercontent.com/30948192/77902455-cb13b400-72b3-11ea-8b70-a714083cf3de.png)
logger输出信息最后面为messageID

## 如何复现

![image](https://user-images.githubusercontent.com/30948192/77902629-14fc9a00-72b4-11ea-9c32-9566e906ceee.png)

**Comment by Him188** [comment]
是否使用的是 0.31.1?

**Comment by Sincky** [comment]
> 是否使用的是 0.31.1?

是的

![image](https://user-images.githubusercontent.com/30948192/77912800-cce67300-72c5-11ea-8daf-fef436fffba7.png)
