### ISSUE TITLE
2.9.0-RC插件数据目录迁移有残留

### ISSUE THREAD

**Issue by Samarium150** [mamoe/mirai#1737]
```
2021-12-13 21:32:56 I/JvmPluginLoader: 移动 Lolicon v5.0.0-beta.2 的配置目录(**\mirai-console-lolicon\run\data\Lolicon)到 **\mirai-console-lolicon\run\data\io.github.samarium150.mirai.plugin.mirai-console-lolicon
2021-12-13 21:32:56 I/JvmPluginLoader: 移动 Lolicon v5.0.0-beta.2 的配置目录(**\mirai-console-lolicon\run\data\Lolicon)到 **\mirai-console-lolicon\run\data\io.github.samarium150.mirai.plugin.mirai-console-lolicon 完成
2021-12-13 21:32:56 I/Lolicon: Plugin loaded
```
数据目录迁移成功了，但原来目录以及yaml文件还留着
左图为迁移前，右图为迁移后
<img src=https://user-images.githubusercontent.com/28302241/145821297-82ae2d69-fe07-4054-a3d8-90940f798c71.png alt="before" width="200" align="left"/><img src=https://user-images.githubusercontent.com/28302241/145821938-d16a9e79-09ae-4d98-8d7f-d87ddc16f07b.png alt="after" width="200" align="center"/>

~~以及为什么配置文件目录不也改用id作为文件夹名呢~~

**Comment by Him188** [comment]
删除文件可能比较危险，因此没有做

**Comment by LaoLittle** [comment]
想知道是不是为了防止中文文件夹

**Comment by Samarium150** [comment]
> 想知道是不是为了防止中文文件夹

https://github.com/mamoe/mirai-console/issues/276

**Comment by Nambers** [comment]
> ```
> 2021-12-13 21:32:56 I/JvmPluginLoader: 移动 Lolicon v5.0.0-beta.2 的配置目录(**\mirai-console-lolicon\run\data\Lolicon)到 **\mirai-console-lolicon\run\data\io.github.samarium150.mirai.plugin.mirai-console-lolicon
> 2021-12-13 21:32:56 I/JvmPluginLoader: 移动 Lolicon v5.0.0-beta.2 的配置目录(**\mirai-console-lolicon\run\data\Lolicon)到 **\mirai-console-lolicon\run\data\io.github.samarium150.mirai.plugin.mirai-console-lolicon 完成
> 2021-12-13 21:32:56 I/Lolicon: Plugin loaded
> ```
> 
> 数据目录迁移成功了，但原来目录以及yaml文件还留着 左图为迁移前，右图为迁移后 <img alt="before" width="200" src="https://user-images.githubusercontent.com/28302241/145821297-82ae2d69-fe07-4054-a3d8-90940f798c71.png"><img alt="after" width="200" src="https://user-images.githubusercontent.com/28302241/145821938-d16a9e79-09ae-4d98-8d7f-d87ddc16f07b.png">
> 
> ~以及为什么配置文件目录不也改用id作为文件夹名呢~

我本地mcl看好像没什么问题(
在pr里也是直接rename的<https://github.com/mamoe/mirai-console/pull/418/files#diff-1acbc1cabfaa439a4693a654460aa8d2890edd3c718df1c9a6e7129c9e85c178R130>

**Comment by SekiBetu** [comment]
> 删除文件可能比较危险，因此没有做

换个思路，不是删除，而是文件夹改名
