### ISSUE TITLE
命令参数不支持空格

### ISSUE THREAD

**Issue by kinhirozane** [mamoe/mirai#1744]
示例代码：
```kotlin
object SimpleHelpCommand : SimpleCommand(
    AobaChan, "helps",
    description = "帮助信息"
) {
    @Handler
    suspend fun CommandSenderOnMessage<*>.help(vararg message: MessageContent) {
        sendMessage(At(fromEvent) + message.toMessageChain())
    }
}
```
这段代码，示例命令运行结果：
QQ Group：/helps test test      as           [/斜眼笑]
-> Group：testtestas[/斜眼笑]

意思就是，所有的空格，换行等等符号都没了，在调用某些 API 的时候是需要空格的，导致不能正常使用，有解决办法吗？

**Comment by cssxsh** [comment]
你既然已经指定上下文 `CommandSenderOnMessage<*>` , 就可以使用 `CommandSenderOnMessage<*>.fromEvent.message` 获取原消息，不需要从指令参数中再重组

**Comment by Kloping** [comment]
粗暴方法
![image](https://user-images.githubusercontent.com/87743020/146344982-d2e9ab2d-3eb0-4c2c-876a-cb3ddb90ad1c.png)
![image](https://user-images.githubusercontent.com/87743020/146345017-91e11b9c-a87a-4517-85ce-ff7f8e3a445e.png)

**Comment by Samarium150** [comment]
> 粗暴方法 ![image](https://user-images.githubusercontent.com/87743020/146344982-d2e9ab2d-3eb0-4c2c-876a-cb3ddb90ad1c.png) ![image](https://user-images.githubusercontent.com/87743020/146345017-91e11b9c-a87a-4517-85ce-ff7f8e3a445e.png)

你这直接简化成`args.joinToString(" ")`就完事儿了

**Comment by jie65535** [comment]
然而中间的空白符号未必是单个空格，还可能是换行和制表等

**Comment by LaoLittle** [comment]
我觉得你可以试着不使用`命令`

**Comment by kinhirozane** [comment]
> 然而中间的空白符号未必是单个空格，还可能是换行和制表等

对，如果可以直接支持MessageChain就好了

**Comment by jie65535** [comment]
> 对，如果可以直接支持MessageChain就好了

就像cssxsh说的，你可以直接获取消息原文，然后去除命令前缀。
或者，自定义指令处理方式`CommandCallParser`

**Comment by LaoLittle** [comment]
> > 然而中间的空白符号未必是单个空格，还可能是换行和制表等
> 
> 对，如果可以直接支持MessageChain就好了

this.fromEvent.message

**Comment by kinhirozane** [comment]
> 我觉得你可以试着不使用`命令`

其实最初的办法就是

```kotlin
GlobalEventChannel.subscribeMessages {
    always {
        if (message.contentToString().contains("取码") {
            subject.sendMessage("请在一分钟内发送要取码的内容。")
            val nextMessage: MessageChain? = subject.nextMessageOrNull(60000L)
            if (nextMessage == null) subject.sendMessage("已超时")
            else subejct.sendMessage(nextMessage.serializeToMiraiCode())
        }
    }
}
```

**Comment by jie65535** [comment]
你说巧不巧，我也是这么干的。（指用下一条消息作为命令的参数）

**Comment by LaoLittle** [comment]
> > 我觉得你可以试着不使用`命令`
> 
> 其实最初的办法就是
> 
> ```kotlin
> GlobalEventChannel.subscribeMessages {
>     always {
>         if (message.contentToString().contains("取码") {
>             subject.sendMessage("请在一分钟内发送要取码的内容。")
>             val nextMessage: MessageChain? = subject.nextMessageOrNull(60000L)
>             if (nextMessage == null) subject.sendMessage("已超时")
>             else subejct.sendMessage(nextMessage.serializeToMiraiCode())
>         }
>     }
> }
> ```

啊这

**Comment by jie65535** [comment]
你可以像这样来得到参数原文（应该
```kotlin
val arg = fromEvent.message.serializeToMiraiCode().substringAfter(' ')
```

**Comment by kinhirozane** [comment]
> > 对，如果可以直接支持MessageChain就好了
> 
> 就像cssxsh说的，你可以直接获取消息原文，然后去除命令前缀。 或者，自定义指令处理方式`CommandCallParser`

尝试过 `CommandArgumentParser` ，但是似乎没生效

**Comment by cssxsh** [comment]
> ```kotlin
> subject.nextMessageOrNull(60000L)
> ```

虽然无关紧要，但是我觉得你这段应该简化一下
```
GlobalEventChannel.subscribeMessages {
    contains("取码") {
        subject.sendMessage("")
        val reply = nextMessageOrNull(6_000) ?: "已超时".toPlainText()
        subject.sendMessage(reply)
    }
}
```

**Comment by kinhirozane** [comment]
> > ```kotlin
> > subject.nextMessageOrNull(60000L)
> > ```
> 
> 虽然无关紧要，但是我觉得你这段应该简化一下
> 
> ```
> GlobalEventChannel.subscribeMessages {
>     contains("取码") {
>         subject.sendMessage("")
>         val reply = nextMessageOrNull(6_000) ?: "已超时".toPlainText()
>         subject.sendMessage(reply)
>     }
> }
> ```

对 `Kotlin` 不是很熟，只是凭借会一些 `Java` 写的，尝到了 `Kotlin` 的甜头，而且 `Mirai` 本身也是科特林写的，文档更加全面。

**Comment by Him188** [comment]
可以考虑如下解决方案：

1. 直接或通过某种设置允许将带空格消息内容匹配给单个 String  参数
2. 添加一个注解，标记在指令的最后一个参数，那么它就接受带空格内容直到消息结束

我倾向于后者

**Comment by kinhirozane** [comment]
咳咳，大佬能给一点小小的示例吗，我没实现:bowtie:

**Comment by jie65535** [comment]
> 咳咳，大佬能给一点小小的示例吗，我没实现:bowtie:

这样试过了吗

> 你可以像这样来得到参数原文（应该
> 
> ```kotlin
> val arg = fromEvent.message.serializeToMiraiCode().substringAfter(' ')
> ```

**Comment by kinhirozane** [comment]
这个方法只能解燃眉之急，不然我也不会纠结要命令参数支持消息链的，毕竟消息链是真正可以包含任意内容的:pensive:

**Comment by kinhirozane** [comment]
> 可以考虑如下解决方案：
> 
> 1. 直接或通过参数允许将带空格消息内容匹配给单个 String  参数
> 2. 添加一个注解，标记在指令的最后一个参数，那么它就接受带空格内容直到消息结束

 [Him188](https://github.com/him188)大佬提供的两个解决方案可以给一个简单的示例吗

**Comment by Him188** [comment]
@novacoo 这是我给我们和 PR 人留的实现方案备注

**Comment by Him188** [comment]
@karlepus 根据 #1897，2.11 已经增加了 [文本参数转义](https://github.com/mamoe/mirai/blob/dev/mirai-console/docs/Commands.md#%E6%96%87%E6%9C%AC%E5%8F%82%E6%95%B0%E7%9A%84%E8%BD%AC%E4%B9%89) 功能，是否解决了问题？

**Comment by Him188** [comment]
另外 vararg 支持也将会由 #1760 在 2.12 支持（如果顺利）

**Comment by cssxsh** [comment]
> @karlepus 根据 #1897，2.11 已经增加了 [文本参数转义](https://github.com/mamoe/mirai/blob/dev/mirai-console/docs/Commands.md#%E6%96%87%E6%9C%AC%E5%8F%82%E6%95%B0%E7%9A%84%E8%BD%AC%E4%B9%89) 功能，是否解决了问题？

我的 admin 插件有用到 `"x x x x"` 工作状态良好

**Comment by kinhirozane** [comment]
很抱歉，没怎么注意github的通知，该问题得到解决，感谢所有 Mirai 的维护者、PR和其他提供帮助的开发者！
