### ISSUE TITLE
2.9.0 M1 在使用IPAD模式登录 会自动掉线

### ISSUE THREAD

**Issue by killerprojecte** [mamoe/mirai#1749]
### 问题描述

IPAD模式下机器人 过几分钟就会自动掉线

### 复现

使用IPAD模式

### mirai-core 版本

2.9.0-M1

### bot-protocol

IPAD

### 系统日志

```text
无报错 只有现象
```

### 网络日志

```text
所使用的启动器无此日志
```

**Comment by Him188** [comment]
请提供日志
