### ISSUE TITLE
上传图片失败

### ISSUE THREAD

**Issue by Jack4936** [mamoe/mirai#1775]
传错了,传输链接错误

**Comment by Karlatemp** [comment]
![Screenshot_2021-12-30-13-57-45-07.png](https://user-images.githubusercontent.com/30070303/147725723-16ecf43d-a8ce-48d4-8406-771316481064.png)

**Comment by Jack4936** [comment]
尴尬,这个图片上传到图床之后可以上传了, 但是http://42.192.131.197/?webtype=mmqch&oty=newcode_tx&oty2=jpg_ghzongdamage_xi&qi=11640787004  这个图片的上传不了.
