### ISSUE TITLE
如何提升图片上传速度？

### ISSUE THREAD

**Issue by BobH233** [mamoe/mirai#1789]
通过mirai-http的addImageUrl是如何处理，是否是先从这个url下载图片二进制数据，再上传到腾讯服务器，最后直接发送图片id？

这个过程如何可以提升上传速度？我听说可以通过自己的oss服务来优化速度，不知道是如何实现的？

**Comment by Him188** [comment]
@ryoii

**Comment by ryoii** [comment]
因为图片需要上传到tx的服务器，任何方法都绕不开`下载图片到本地`，`上传图片服务器`两个步骤。

OSS服务可以提升下载的速度。

**Comment by BobH233** [comment]
明白了，谢谢！
