### ISSUE TITLE
Why `noinline`?

### ISSUE THREAD

**Issue by ice1000** [mamoe/mirai#18]
https://github.com/mamoe/mirai/blob/8948eb204307d361566626614817525e515eed9c/mirai-core/src/commonMain/kotlin/net.mamoe.mirai/BotHelper.kt#L93-L100

This looks inlineable to me.

**Comment by Him188** [comment]
Indeed, it should be inline.

**Comment by Him188** [comment]
resolved

**Comment by ice1000** [comment]
@Him188 You can add `fix #18` in your commit message to automatically close this issue when you push

**Comment by ice1000** [comment]
.. and people can see in which commit you fixed the issue

**Comment by Him188** [comment]
thank you2019年12月13日 13:34，Tesla Ice Zhang‮ <notifications@github.com>写道：.. and people can see in which commit you fixed the issue

**Comment by ice1000** [comment]
![image](https://user-images.githubusercontent.com/16398479/70777064-c949d300-1d4c-11ea-8d17-7368534308b1.png)

Oh, what a mess 😅
