### ISSUE TITLE
貌似说阿里云的maven没法找到2.9.2的依赖？

### ISSUE THREAD

**Issue by LaoLittle** [mamoe/mirai#1828]
### 问题描述

![image](https://user-images.githubusercontent.com/93422095/148324578-cb708761-d2b7-49c4-9d1c-afeed8a79854.png)
![image](https://user-images.githubusercontent.com/93422095/148324606-3b60459f-b840-422f-a4c9-abb572737e3d.png)
![image](https://user-images.githubusercontent.com/93422095/148324613-95d5918f-28d5-45a7-961f-89cdfbc11e74.png)

删去`maven("https://maven.aliyun.com/repository/public")`后可正常下载

手动使用浏览器前往`https://maven.aliyun.com/repository/public/net/mamoe/mirai-core-jvm/2.9.2/mirai-core-jvm-2.9.2.jar`也可正常下载

是我的问题么

### 复现

使用阿里云maven

### mirai-core 版本

2.9.2

### bot-protocol

ANDROID_PHONE

### 系统日志

```text
NaN
```

### 网络日志

```text
NaN
```

**Comment by Him188** [comment]
不知道, 可能阿里云同步比较慢

**Comment by LaoLittle** [comment]
> 不知道, 可能阿里云同步比较慢

浏览器访问链接也能下载

怪

**Comment by Karlatemp** [comment]
非 mirai 问题，中央仓库是有的
