### ISSUE TITLE
QQ频道的兼容

### ISSUE THREAD

**Issue by LittleChiu** [mamoe/mirai#1830]
QQ频道现在正在内测当中, 但是Mirai目前还未对此领域进行开发,
所以我想请求你们进行相关模块的开发? 比较在形似Discord上的频道,
机器人的效率会更高

**Comment by 4o4E** [comment]
+1

**Comment by Pmaru-top** [comment]
“目前没有计划去整一个还在处于dev的东西”--作者原话

[#1656](https://github.com/mamoe/mirai/issues/1656)

**Comment by Karlatemp** [comment]
Duplicate of #1656
