### ISSUE TITLE
SpringBoot打包

### ISSUE THREAD

**Issue by HJHY** [mamoe/mirai#1839]
### 问题描述

构建springBoot项目然后引入mirai依赖可以运行但是打包会出现问题.
参考issue中的答案后打包会出现成功,但是mirai依赖似乎没有打包进去

### 复现

以下是构建文件
plugins {
    id 'org.springframework.boot' version '2.6.2'
    id 'io.spring.dependency-management' version '1.0.11.RELEASE'
    id 'java'
    id 'org.jetbrains.kotlin.jvm' version '1.5.30'
}

group = 'com.example'
version = '0.0.1-SNAPSHOT'
sourceCompatibility = '11'

configurations {
    compileOnly {
        extendsFrom annotationProcessor
    }
}

repositories {
    mavenCentral()
}

dependencies {
    implementation 'org.springframework.boot:spring-boot-starter-web'
    compileOnly 'org.projectlombok:lombok'
    annotationProcessor 'org.projectlombok:lombok'
    testImplementation 'org.springframework.boot:spring-boot-starter-test'

//    implementation 'net.mamoe:mirai-core:2.8.2'

    implementation("net.mamoe:mirai-core-jvm:2.8.2") {
        exclude group: 'net.mamoe', module: 'mirai-core-api'
        exclude group: 'net.mamoe', module: 'mirai-core-utils'
    }
    implementation("net.mamoe:mirai-core-api-jvm:2.8.2") {
        exclude group: 'net.mamoe', module: 'mirai-core-utils'
    }
    implementation("net.mamoe:mirai-core-utils-jvm:2.8.2")

}

test {
    useJUnitPlatform()
}

### mirai-core 版本

2.8.2

### bot-protocol

ANDROID_PAD

### 系统日志

```text
15:51:29: Executing 'jar'...

> Task :compileKotlin UP-TO-DATE
> Task :compileJava UP-TO-DATE
> Task :processResources UP-TO-DATE
> Task :classes UP-TO-DATE
> Task :inspectClassesForKotlinIC UP-TO-DATE
> Task :jar UP-TO-DATE

BUILD SUCCESSFUL in 696ms
5 actionable tasks: 5 up-to-date
```

### 网络日志

```text
无
```

### 补充信息

 
![Snipaste_2022-01-16_15-52-25](https://user-images.githubusercontent.com/62489863/149651884-b2c4de9f-792c-457b-a87a-4f939fcf7395.png)

**Comment by Karlatemp** [comment]
你应该去问spring和搜索引擎，而不是来问mamoe
