### ISSUE TITLE
将控制台的消息日志保存到文件里

### ISSUE THREAD

**Issue by NoMathExpectation** [mamoe/mirai#1844]
翻Mirai console的文件夹并没有看见控制台的消息日志，只有一个好像和网络有关的日志。希望能把控制台的日志也写进文件里，这样遇到紧急的bug需要立即关闭机器人，也可以之后看文件里的日志，分析发生了什么问题了

**Comment by NoMathExpectation** [comment]
我把版本更新了，还是没看到什么日志文件啊，放在哪里了

**Comment by Him188** [comment]
@NoMathExpectation  logs/log-0.log

**Comment by NoMathExpectation** [comment]
为什么会有乱码呢
![image](https://user-images.githubusercontent.com/85624722/157681458-d92af8db-dfc4-49d5-b29e-eadd16549c1b.png)

**Comment by Him188** [comment]
那是颜色控制符

**Comment by NoMathExpectation** [comment]
emmm感觉可以写进文件时把这些控制符什么的过滤掉，美观一些
