### ISSUE TITLE
语音无法发送: NoSuchMethodError: net.mamoe.mirai.utils.ExternalResource$Companion.createAutoCloseable

### ISSUE THREAD

**Issue by SugarFatFree** [mamoe/mirai#1856]
### 问题描述

发送语音异常，已安装ffmpeg和mirai-silk-converter；日志文件中没有报错信息，但是打断点可以看到
`
java.lang.NoSuchMethodError: 'net.mamoe.mirai.utils.ExternalResource net.mamoe.mirai.utils.ExternalResource$Companion.createAutoCloseable(net.mamoe.mirai.utils.ExternalResource)'
`

### 复现

            ExternalResource resource = ExternalResource.create(new File("/Users/apple/Desktop/1.wav"));
            OfflineAudio audio = event.getGroup().uploadAudio(resource);
            event.getGroup().sendMessage(audio);

### mirai-core 版本

2.10.0-RC2

### bot-protocol

ANDROID_PHONE

### 系统日志

```text
java.lang.NoSuchMethodError: 'net.mamoe.mirai.utils.ExternalResource net.mamoe.mirai.utils.ExternalResource$Companion.createAutoCloseable(net.mamoe.mirai.utils.ExternalResource)'
```

### 网络日志

```text
无
```

**Comment by SugarFatFree** [comment]
刚刚试了2.9.2，可以正常发送

**Comment by Him188** [comment]
决定还是在2.10加回 createAutoClosable
