### ISSUE TITLE
重复使用Bot登录几次后PC端无法接收到消息

### ISSUE THREAD

**Issue by xiaoyicomic** [mamoe/mirai#186]
## 问题

重复使用Bot登录几次后PC端无法接收到消息，但是手机端可以接收到消息，日志也显示发送成功了。

## 如何复现

可能的触发条件：
关闭bot不久后多次(有时候再次就会触发)使用bot登录。

使用的库:
![image](https://user-images.githubusercontent.com/30972246/78122661-a8160b00-743f-11ea-914c-c96075d7d88d.png)

**Comment by Him188** [comment]
重复登录是掉线自动重连还是手动 login()

**Comment by Him188** [comment]
这个实际上是PC客户端问题，无法解决

**Comment by Him188** [comment]
你可以登录，然后马上重启 mirai，尝试发消息，PC端会看不到。这个问题在协议上没有涉及，因此无法解决。

一般等待几秒钟就恢复正常了。

**Comment by xiaoyicomic** [comment]
> 你可以登录，然后马上重启 mirai，尝试发消息，PC端会看不到。这个问题在协议上没有涉及，因此无法解决。
> 
> 一般等待几秒钟就恢复正常了。

我这里是直接关闭了控制台然后重复开启了，感谢解答。

**Comment by Him188** [comment]
一个好的解决方案应该是 #119

**Comment by wangzheooo** [comment]
这个是pc端问题,bot一直正常,,,pc端过一段时间连天记录就自己出来了
