### ISSUE TITLE
contributeCommandCallParser() 对CommandCallParser的扩展不运作

### ISSUE THREAD

**Issue by 18111398** [mamoe/mirai#1860]
### 问题描述

即使使用`contributeCommandCallParser()`用自己的`CommandCallParser`扩展，实际编译后插件依然使用`SpaceSeparatedCommandCallParser`解析语句。即扩展方法完全没起到作用。

（此外实测`contributeCommandCallResolver()`可以如期运作，因此合理猜测只有`CommandCallParser`相关部分出了问题。）

### 复现

不想透露现在的project，因此使用没有实际作用但更能反应问题的例子。
```
object MyCommandCallParser: CommandCallParser {
    override fun parse(caller: CommandSender, message: MessageChain): CommandCall? {
        return CommandCallImpl(caller, "stop", listOf())
    }
}
```

```
object MyPlugin: KotlinPlugin(/*...*/) {
    /*...*/
    override fun PluginComponentStorage.onLoad() {
        contributeCommandCallParser { MyCommandCallParser }
    }
}
```
预期结果：`MyCommandCallParser.parse()`甚至未使用`message`参数，因此无论输入如何都会被解析为stop指令。
实际结果：语句正常解析。

### mirai-core 版本

生产环境2.9.2，运行环境2.10.0-RC2

### bot-protocol

ANDROID_PHONE

### 其他组件版本

无。

### 系统日志

```text
无关。
```

### 网络日志

```text
无关。
```

**Comment by Him188** [comment]
经检查, 问题原因是内嵌的 `SpaceSeparatedCommandCallParser` 优先级比插件添加的高, 导致总是使用内嵌的.

**Comment by Him188** [comment]
已修复，现在可以使用预览版本 `2.11.0-RC-dev-77e2a5c3` 测试。

不知道为什么 GitHub 这个编辑框不能粘贴，预览版本用法可以在 开发文档-配置依赖-选择版本-预览版本 找到。
