### ISSUE TITLE
为群实现 RoamingSupported

### ISSUE THREAD

**Issue by iceBear67** [mamoe/mirai#1866]
支持获取群聊的历史记录  
~~之前在某群问过一遍，但是回复是不支持（ ）于是我去看了一下友商的库，发现~~貌似是可以拉取到历史消息的  
 
https://github.com/takayama-lily/oicq/blob/b95a05fc5b8b88437bf56325894ba66fd9efb5a5/lib/group.ts#L522-L544

而且这个功能已经被验证过[有效](https://github.com/Akalrin/Icalingua_folk/blob/6b5fa770799565c8e007ca0b4c84ff5efbba6e7d/icalingua/src/main/adapters/oicqAdapter.ts#L1200)了（某现已尘封的聊天客户端）希望 Mirai 能够添加这个功能

**Comment by Him188** [comment]
看了一下, 按目前 mirai API 设计很好实现, 不需要 breaking change

**Comment by iceBear67** [comment]
苦等.jpg

**Comment by Him188** [comment]
等的时候其实可以 PR 的

**Comment by AdoptOSS** [comment]
> 看了一下, 按目前 mirai API 设计很好实现, 不需要 breaking change

目前的 RoamingMessages 是 timestamp-based 的
这里似乎需要引入 seq-based 的 RoamingMessages 接口

**Comment by iceBear67** [comment]
> > 看了一下, 按目前 mirai API 设计很好实现, 不需要 breaking change
> 
> 目前的 RoamingMessages 是 timestamp-based 的 这里似乎需要引入 seq-based 的 RoamingMessages 接口

我打算拆分成 `TimeBasedRoamingMessages` 和 `SeqBasedRoamingMessages`

但是我不太会 kotlin ,现在那个 PR 挺乱的, 而且缺一个 `PbGetGroupMsg`
