### ISSUE TITLE
在插件描述的`dependsOn`内的参数`isOptinal`有问题

### ISSUE THREAD

**Issue by LaoLittle** [mamoe/mirai#1869]
### 问题描述

![d](https://user-images.githubusercontent.com/93422095/152787831-747a6136-ffba-4df2-ba04-02df7ff246ae.png)

`isOptinal`的含义是可选，那么应为`true`时也能正常加载

不知道是文档问题还是整个的逻辑有问题

### mirai-core 版本

2.10.0

**Comment by Him188** [comment]
文档写反了，应该是 true
