### ISSUE TITLE
MessageChainBuilder类plusAssign方法无效

### ISSUE THREAD

**Issue by HandsomeXi** [mamoe/mirai#187]
代码
```
MessageChainBuilder() += "content".toMessage()
```
报错
Type mismatch.
Required:
MessageChainBuilder
Found:
List<Message>

**Comment by Him188** [comment]
好问题，但这应该是 Kotlin 问题，会尝试解决

**Comment by Him188** [comment]
目前可以使用  `buildMessageChain`

**Comment by Him188** [comment]
![image](https://user-images.githubusercontent.com/12100985/78420656-a2106c00-7683-11ea-8eb2-74448faf83ed.png)
