### ISSUE TITLE
支持二维码扫码登录

### ISSUE THREAD

**Issue by SugarFatFree** [mamoe/mirai#1875]
目前登录实在有些繁琐，首次登录时必须要在手机上过滑块，还要使用mirai android，然后再使用手机扫码，能不能直接提供一个可用的二维码扫码登录呢？或者过滑块后像短信验证码登录那样

**Comment by SugarFatFree** [comment]
mirai现在的登录逻辑太复杂而且有悖论，在不借助mirai android的情况下（借助了也比较麻烦），需要先过滑块验证码，然后会弹出一个设备锁验证链接，然后需要登录账号的手机点开设备锁链接，截图上面的二维码，然后再返回，扫码那个二维码，登录完成，这些步骤实在太多了，我想能不能直接缩短1-2步呢？直接过滑块，然后短信验证。

**Comment by Him188** [comment]
PR welcome

**Comment by dragon0629** [comment]
@[Karlatemp](https://github.com/Karlatemp) Karlatemp linked a pull request [yesterday](https://github.com/mamoe/mirai/issues/1875#event-8527785161) that will close this issue

啊这，可以QRLOGIN了吗？
