### ISSUE TITLE
无法获取陌生人信息

### ISSUE THREAD

**Issue by SugarFatFree** [mamoe/mirai#1883]
### 问题描述

getStranger 一直为null

### 复现

        bot.login();
        System.out.println("登录状态：" + bot.isOnline());
        Stranger stranger = bot.getStranger(1240050829);
        System.out.println(stranger);
        Stranger stranger2 = bot.getStranger(2184196007L);
        System.out.println(stranger2);
        Stranger stranger3 = bot.getStranger(936588810);
        System.out.println(stranger3);

### mirai-core 版本

2.10.0

### bot-protocol

ANDROID_PHONE

### 系统日志

```text
无
```

### 网络日志

```text
无
```

**Comment by 4o4E** [comment]
会不会是因为与bot的关系为好友，可以试试getFriend
