### ISSUE TITLE
希望可以获取红包的基本信息以及领取红包的人

### ISSUE THREAD

**Issue by 493505110** [mamoe/mirai#1885]
群里总是有很多红包挂，有时发红包总是被挂狗抢
希望可以获取领取了红包的人，但是不希望添加领取红包的接口
用途是自动踢出领取了指定红包的人，望采纳

**Comment by sandtechnology** [comment]
#1014 另 外挂的抢红包方式可以做到近似真人 这个应用场景不成立

**Comment by 493505110** [comment]
好吧

**Comment by 493505110** [comment]
![image](https://user-images.githubusercontent.com/29498336/153862817-93f3de06-c5b2-479d-a96b-0d239c303d8b.png)

**Comment by 493505110** [comment]
> #1014 另 外挂的抢红包方式可以做到近似真人 这个应用场景不成立

但是发了红包之后撤回还能秒领就离谱
