### ISSUE TITLE
想询问一下mirai的自动重新连接策略

### ISSUE THREAD

**Issue by SugarFatFree** [mamoe/mirai#1887]
我的机器人之前被冻结了，过了两天后解冻，但是当时并不可用，机器人也无法使用，但是在今天早晨，也就是解除冻结一天后，机器人突然可以用了，应该是程序自动重新登录了，所以我想问问自动重连的策略是怎么样的？整个过程中未关闭程序。

**Comment by Him188** [comment]
冻结之后应该是会停止重连 (bot 死亡) 的, 这可能是个 bug. 遇到网络不好这种一般错误时会不断尝试重连, 间隔数秒. 可在 BotConfiguration 设置. 也有部分设置可通过 JVM system prop 设置.

详细重连逻辑可查看 `net.mamoe.mirai.internal.network.handler.selector.AbstractKeepAliveNetworkHandlerSelector`
> 要阅读所有网络层逻辑, 可从 `net.mamoe.mirai.internal.network.handler.NetworkHandler` 开始

**Comment by SugarFatFree** [comment]
> 

能否增加一个被冻结之后，程序可以自动检测的功能，当人工解冻之后，就可以自动登录上去的功能呢？

**Comment by Him188** [comment]
不能知道是否解冻, 只能不断尝试登录, 也就是目前的行为

**Comment by landall** [comment]
> 不能知道是否解冻, 只能不断尝试登录, 也就是目前的行为

这个行为会不会导致bot更容易被冻结？
我是今天上午被冻结了一个Bot，然后手机解冻后，重新启动mcl，然后登录输入完验证码后，当场又被冻结。

**Comment by landall** [comment]
另外重连时有个很不友好的设置，我感觉应该是console部分的问题。

在被冻结后重连，或者重连要求输入验证码时，mcl这里会卡在一个显示LOGIN >的界面里出不来。
这时候输入所有东西，都会继续来一行LOGIN >，没有其他提示。

然后因为通常用screen挂后台，mcl自己的提示早就被刷掉了，所以不立即重新打印刚才的信息的话，根本不知道LOGIN这行之前，打印了什么东西（特别是那个图形验证码相关的提示）

**Comment by Him188** [comment]
新 terminal 好像改了 CC @Karlatemp

**Comment by Karlatemp** [comment]
确实改了，新 terminal 到时候直接 Ctrl+C 应该就能中断登录 (会抛一个 UserInterruptedException), 如果没意外的话应该是可以中断的

**Comment by landall** [comment]
> 确实改了，新 terminal 到时候直接 Ctrl+C 应该就能中断登录 (会抛一个 UserInterruptedException), 如果没意外的话应该是可以中断的

在控制台上处理登录，好像跟mirai偏向于Server端无人值守，冲突还是有一些的。
如果能实现Mirai Core跟Mirai Console通过进程间通信就好了。
Core直接用Service常驻，Mirai Console没事时退出进程就行了。
遇到登录阻断这种事情，Core直接blocking掉相关的事情，等Console下指令Resume
