### ISSUE TITLE
为事件处理增加优先级, 允许拦截, 允许按优先级处理而不并发

### ISSUE THREAD

**Issue by zhangshikj** [mamoe/mirai#189]
假设有2个mirai插件，我想让插件1处理某个消息，不想让插件2处理，所以mirai插件有没有消息劫持呢？劫持后其它插件无法处理！设置插件处理消息优先级！

**Comment by Him188** [comment]
这会导致事件框架发生较大改变，请问这种拦截的实际用例有哪些？

**Comment by zhangshikj** [comment]
插件A禁止(劫持消息)插件B的消息处理，酷Q就有------------------ 原始邮件 ------------------
发件人: "Him188"<notifications@github.com>
发送时间: 2020年4月11日(星期六) 凌晨1:54
收件人: "mamoe/mirai"<mirai@noreply.github.com>;
抄送: "伏秋洛"<1372362033@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [mamoe/mirai] 为事件处理增加优先级, 允许拦截, 允许按优先级处理而不并发 (#189)




 
这会导致事&#x4EF6;框架发生较大改变，请问这种拦截的实际用例有哪些？
 
&mdash;

**Comment by Him188** [comment]
酷Q有没有没有任何影响，mirai已经有了很多酷Q没有的功能。

目前事件是并发处理（单个监听器也可以有锁），对于协程来说这是最好的。
若改为优先级处理，将会产生新的问题：如协程内调用 `nextMessage`,  `selectMessages` 等函数时可能会挂起协程很长一段时间，这将会影响后续插件处理。

因此我们需要根据拦截事件的实际作用来考虑是否支持。

**Comment by zhangshikj** [comment]
比如一个独立的违禁词插件，插件A判断这个消息是违禁词后禁止其它插件处理这个消息

**Comment by Him188** [comment]
计划实现：带优先级的监听器会按顺序执行，不带优先级的监听器在最后并发执行。

**Comment by zhangshikj** [comment]
好的，可以------------------ 原始邮件 ------------------
发件人: "Him188"<notifications@github.com>
发送时间: 2020年4月12日(星期天) 中午11:46
收件人: "mamoe/mirai"<mirai@noreply.github.com>;
抄送: "伏秋洛"<1372362033@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [mamoe/mirai] 为事件处理增加优先级, 允许拦截, 允许按优先级处理而不并发 (#189)




 
计划实现：带优先级的监听器会按顺序执行，不带优先级的监听器在最后并发执行。
 
&mdash;
