### ISSUE TITLE
陌生人消息有时候收不到

### ISSUE THREAD

**Issue by Coloryr** [mamoe/mirai#1890]
### 问题描述

陌生人私聊账户时，有的触发消息事件，有的不能。
但是删掉好友，再重新添加就行。

### 复现

陌生人发消息给bot

### mirai-core 版本

2.10.0

### bot-protocol

ANDROID_PAD

### 系统日志

```text
无
```

### 网络日志

```text
无
```

**Comment by Him188** [comment]
提供日志

**Comment by Coloryr** [comment]
日志啥都没有，别人发的消息都不显示

**Comment by Him188** [comment]
@Coloryr 你觉得啥都没有, 但有可能我会觉得它有很重要的信息, 所以请提供网络日志, 没有日志无法解决任何问题
