### ISSUE TITLE
提议加入用户变量功能

### ISSUE THREAD

**Issue by SyuueenN** [mamoe/mirai#1894]
一些常用的群号、企鹅号没有特别记录的话每次找起来会比较麻烦。
如果加入用户变量并存储起来的话，可以通过字符串简单调取变量出来，运行时自动替换。
算是一个锦上添花的痒点功能。

**Comment by Him188** [comment]
可以通过一个插件完成，其他插件依赖这个插件就可以了

倒是没有必要集成到 console 里面
