### ISSUE TITLE
希望有一个全局的消息源过滤器

### ISSUE THREAD

**Issue by zhaodice** [mamoe/mirai#1898]
可否通过环境变量，类似
System.setProperty("mirai.message.group", "0")
System.setProperty("mirai.message.temporary", "0")
System.setProperty("mirai.message.friend", "0")
System.setProperty("mirai.message.strange", "0")
来全局禁收、禁发特定消息来源的消息？隔壁gocq做了个配置文件，可以禁用临时会话
或者说，允许一些插件来拦截消息？

事实上插件本身可以简单的if做到过滤消息，但不是所有插件都支持，而且也难以做到统一开关

**Comment by Karlatemp** [comment]
你可以专门写个插件拦截相关事件的处理

**Comment by Him188** [comment]
你一是可以写插件以最高优先级拦截，二是可以在EventChannel加前置 filter。这种“全局”功能只会让系统越来越复杂。
