### ISSUE TITLE
Mirai启动一段时间后无响应

### ISSUE THREAD

**Issue by Cnzw** [mamoe/mirai#1900]
### 问题描述

Mirai在启动一段时间后在命令行无响应(三分钟左右), 但是进程仍然存在.
不对任何命令反应, 只能 ^C 强制结束进程.

CentOS7
Java11:
openjdk version "11" 2018-09-25
OpenJDK Runtime Environment 18.9 (build 11+28)
OpenJDK 64-Bit Server VM 18.9 (build 11+28, mixed mode)

### 复现

1. 使用```./mcl```启动
2. 等待几分钟
3. 尝试输入任何命令
4. mirai无响应

### mirai-core 版本

2.10.0

### bot-protocol

ANDROID_PHONE

### 其他组件版本

mcl-1.2.1
直接通过命令行操作

### 系统日志/网络日志
[paste.gg](https://paste.gg/p/Cnzw/ab2bc49be82c4d81b89aed9a324377d3)

**Comment by Him188** [comment]
#1899
