### ISSUE TITLE
Bot电脑端手动踢人，被踢者再加入，踢出事件和加入事件均不触发

### ISSUE THREAD

**Issue by Liu-Zhiying** [mamoe/mirai#1905]
### 问题描述

使用Mirai登陆Bot，再使用QQ电脑版登陆Bot相同账号，使用Bot电脑端踢人，再让被踢者加入，被踢和加入事件均未触发

### 复现

使用Mirai登陆Bot
使用QQ电脑版登陆Bot相同账号
使用Bot电脑端踢人
让被踢者加入

### mirai-core 版本

2.10.0

### bot-protocol

ANDROID_PHONE

### 其他组件版本

mirai-api-http 2.5.0
Mirai.NET 2.3.9

### 补充信息

[2022-03-02.log](https://github.com/mamoe/mirai/files/8163848/2022-03-02.log)

**Comment by Liu-Zhiying** [comment]
补充一下，代码踢人没问题，我在写一个验证新群员的机器人，让新群员在指定时间内发送验证码，目前超时被踢再加入，一切正常

**Comment by Colerar** [comment]
同样有这个问题，不过实际影响不大。正常使用中应当没有登录 bot 帐号手动踢人的场景。

**Comment by Liu-Zhiying** [comment]
确实，但是测试的时候因为这个BUG搞的我很懵逼

**Comment by Karlatemp** [comment]
> for mamoe: No any data received if kick on pc

**Comment by Him188** [comment]
确实没有任何通知，我在官方手机客户端踢出A，再尝试拉 A 进群，客户端会觉得成员还在群里不允许邀请
