### ISSUE TITLE
SLF4J报错

### ISSUE THREAD

**Issue by Testplayers** [mamoe/mirai#1927]
### 问题描述

SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.

### 复现

每次打开MCL都会提示

### mirai-core 版本

2.82

### bot-protocol

MACOS

**Comment by Nambers** [comment]
https://mirai.mamoe.net/topic/573/%E6%B1%82%E5%8A%A9%E5%B8%96-%E5%A6%82%E4%BD%95%E8%A7%A3%E5%86%B3mcl%E7%99%BB%E5%BD%95%E5%90%8Eclasspath%E4%B8%AD%E4%B8%A2%E5%A4%B1log4j-core%E7%9A%84%E9%97%AE%E9%A2%98/2
忽略

**Comment by CauchyDOOM** [comment]
其实还是希望能再后续版本（2.12+）变成INFO或者忽略。2.10.X中该报错被忽略了，但在2.11.0中再次出现了（对红字ptsd了
