### ISSUE TITLE
无法让机器人自动登入

### ISSUE THREAD

**Issue by Testplayers** [mamoe/mirai#1933]
### 问题描述

'autologin add qq号 密码 '显示已添加，没显示‘bots’文件夹，且无法自动登入，

### 复现

重启也是如此

### mirai-core 版本

2.8.2

### bot-protocol

MACOS

**Comment by Karlatemp** [comment]
你是如何关闭console的

**Comment by Testplayers** [comment]
> 

直接关窗口，重启服务器添加后，还是不显示bots文件夹，只有'add QQ号  QQ密码'才会显示文件夹，但是依旧不能自动登入

**Comment by Karlatemp** [comment]
你见过哪个控制台程序正常关闭是直接关窗口的
