### ISSUE TITLE
mirai-console无法添加bot

### ISSUE THREAD

**Issue by Testplayers** [mamoe/mirai#1934]
### 问题描述

安装成功启动后，输入‘autologin add‘显示添加成功，但是不显示bots文件夹

### 复现

关了mcl窗口还是不显示

### mirai-core 版本

2.8.2

### bot-protocol

MACOS

**Comment by Karlatemp** [comment]
1. 请不要重复开 issue
2. 请不要直接关闭控制台窗口，这和在任务管理器里强行杀死进程没有任何区别
3. console 的 autologin 启动时间为启动console 时而不是马上生效
4. 请不要另开 issue 而是在原 issue 回复
5. 有个命令叫 stop
6. Ctrl+C 有和 stop 一样的效果
