### ISSUE TITLE
内存泄漏+死循环

### ISSUE THREAD

**Issue by aleck099** [mamoe/mirai#1935]
### 问题描述

就卡死不动，内存疯涨

### 复现

```
export TERM=rxvt-unicode-256color
./mcl
```

### mirai-core 版本

2.11.0-M1

### bot-protocol

ANDROID_PHONE

### 其他组件版本

silk-converter 0.0.5

### 补充信息

装个rxvt-unicode运行./mcl也是一样的问题

**Comment by Karlatemp** [comment]
- 你的「卡死」的现象是什么，在什么时候卡死
- 没有 JVM Crashed 什么的字眼?
- 您有没有试过不用 rxvt 的情况
- 没有其他组件了?
- 您的日志呢

**Comment by aleck099** [comment]
当然是啥也没有啊
只有内存爆涨然后被我kill了
没有日志
运行./mcl输出组件列表后就没了

另外，你能不能复现
不能的话我再研究一下

**Comment by aleck099** [comment]
另外在以前的版本（2.10.0）遇到不支持的终端它顶多抛个异常，没有像这样炸内存的

**Comment by Him188** [comment]
不提供日志无法分析问题

**Comment by aleck099** [comment]
需要提供hs_err吗
我是不想让它占满我内存

**Comment by Karlatemp** [comment]
我们需要的就是 hs_err, 啥也没有最后退出时的输出的截图那也总得有吧。你啥也不提供我们没法解决任何问题
