### ISSUE TITLE
mirai-console 无限递归（对于#1935的研究）

### ISSUE THREAD

**Issue by aleck099** [mamoe/mirai#1936]
### 问题描述

`net.mamoe.mirai.console.terminal.MiraiConsoleImplementationTerminal::terminal` 属性
`MiraiConsoleImplementationTerminal.kt` 第146行
`build()` 永不返回

在`build()`里要创建`Terminal`
在创建`Terminal`时`jline`输出了一个警告
具体在`org.jline.terminal.impl.AbstractTerminal`第204行
`Unable to retrieve infocmp for type " + type, e`

本来吧一个警告而已，也没什么事
至少在mirai-console 2.10.0是没事的

然后这个警告要输出到stderr罢
然后在`MiraiConsoleTerminalLoader.kt`第190行你又把系统的stderr改掉了
要输出到自己的日志里

最后在`MiraiConsoleImplementationTerminal.kt`第100行
`lineReader.printAbove(text)`

然后这时候lineReader还没创建呢
又要创建lineReader

`MiraiConsoleImplementationTerminal.kt`第134行 创建lineReader
又会调用`TerminalBuilder.terminal()`
又要输出一个警告`Unable to retrieve infocmp for type`

输出这个警告需要lineReader
构造lineReader又要输出警告
就无限递归

### 复现

```
export TERM=rxvt-unicode-256color
./mcl
```

### mirai-core 版本

2.11.0-M1

### bot-protocol

ANDROID_PHONE

### 系统日志

```text
[91m2022-03-16 11:22:47 W/stderr: Mar 16, 2022 11:21:58 AM org.jline.utils.Log logrMar 16, 2022 11:22:00 AM org.jline.utils.Log logrMar 16, 2022 11:22:02 AM org.jline.utils.Log logrMar 16, 2022 11:22:03 AM org.jline.utils.Log logrMar 16, 2022 11:22:43 AM org.jline.utils.Log logrMar 16, 2022 11:22:44 AM org.jline.utils.Log logrMar 16, 2022 11:22:44 AM org.jline.utils.Log logrMar 16, 2022 11:22:45 AM org.jline.utils.Log logrMar 16, 2022 11:22:45 AM org.jline.utils.Log logrMar 16, 2022 11:22:45 AM org.jline.utils.Log logrMar 16, 2022 11:22:46 AM org.jline.utils.Log logrMar 16, 2022 11:22:46 AM org.jline.utils.Log logrMar 16, 2022 11:22:46 AM org.jline.utils.Log logrMar 16, 2022 11:22:47 AM org.jline.utils.Log logr[0mnull...

这是我用调试器在`lineReader.printAbove(text)`时截获的
`MiraiConsoleImplementationTerminal.kt` 第100行
如果放任它一直运行下去，它会越来越长，最后爆掉
```

### 补充信息

能复现吗
我听说复现是解决bug的最重要一步
不能复现的bug就不能解决

**Comment by aleck099** [comment]
还有我认为任何一个库发生错误都不应该往stdout或stderr写东西
jline的做法也有问题

**Comment by Him188** [comment]
Mirai Console 实际上不是库，是框架。Mirai Console Terminal 是一个控制台程序，因此会输出 stdlib。

**Comment by aleck099** [comment]
> Mirai Console 实际上不是库，是框架。Mirai Console Terminal 是一个控制台程序，因此会输出 stdlib。

我指jline
之前也遇到过出问题往stderr写东西的库
我认为这很不好

**Comment by Karlatemp** [comment]
我们没有相关的复现环境, 所以请下载 https://github.com/mamoe/mirai/actions/runs/2039796685 以帮助我们确认该问题是否已解决

**Comment by aleck099** [comment]
2.10.1没有这个问题了，怪

**Comment by Him188** [comment]
如果还有问题，可以 reopen
