### ISSUE TITLE
提示非官方客户端登录

### ISSUE THREAD

**Issue by SugarFatFree** [mamoe/mirai#1939]
### 问题描述

![Screenshot_2022-03-15-19-56-13-371_com tencent mo](https://user-images.githubusercontent.com/30424828/158717177-c994f620-92cd-4b64-8fd6-b74486b87450.jpg)

### 复现

暂无

### mirai-core 版本

2.10.0

### bot-protocol

ANDROID_PHONE

**Comment by zhaodice** [comment]
正常，我大号正常使用QQ没登框架也冻了，手机号死绑，至今没解封。
