### ISSUE TITLE
获取手机客户端的QuoteReply的source.originalMessage不完整

### ISSUE THREAD

**Issue by cssxsh** [mamoe/mirai#1942]
### 问题描述

获取安卓手机客户端的QuoteReply的source.originalMessage不完整，
只会有前面几个字符

但来自PC客户端的QuoteReply的source.originalMessage是完整的

### 复现

使用安卓手机客户端回复一条较长的消息（纯文本即可），
然后获取 QuoteReply的source.originalMessage 只有前面几个字符

### mirai-core 版本

2.10.1

### bot-protocol

ANDROID_PHONE

**Comment by Karlatemp** [comment]
https://github.com/mamoe/mirai/issues/355#issuecomment-636263284

mirai 收到的信息中 originalMessage 有什么就是什么, 该部分消息取决于发送者的 客户端/服务器

**Comment by Echoosx** [comment]
我也遇到类似的问题：
`message.firstIsInstanceOrNull<QuoteReply>().source.originalMessage`获取不到完整的引用内容
想问一下有没有其他方法能获取到完整的引用内容

**Comment by Michael1015198808** [comment]
> 

同问，不知道老哥问题解决了没

**Comment by Michael1015198808** [comment]
> 我也遇到类似的问题： `message.firstIsInstanceOrNull<QuoteReply>().source.originalMessage`获取不到完整的引用内容 想问一下有没有其他方法能获取到完整的引用内容


同问，不知道老哥问题解决了没

**Comment by Echoosx** [comment]
> 

上面说那个方法就是没办法获取完整引用内容的，所以只能是把message存储下来，后期再调用。
我是在项目里引用这个插件来存储message的：https://github.com/cssxsh/mirai-hibernate-plugin

**Comment by Echoosx** [comment]
> > 我也遇到类似的问题： `message.firstIsInstanceOrNull<QuoteReply>().source.originalMessage`获取不到完整的引用内容 想问一下有没有其他方法能获取到完整的引用内容
> 
> 同问，不知道老哥问题解决了没

上面说那个方法就是没办法获取完整引用内容的，所以只能是把message存储下来，后期再调用。
我是在项目里引用这个插件来存储message的：https://github.com/cssxsh/mirai-hibernate-plugin
