### ISSUE TITLE
serializeToMiraiCode无法正确处理自己回复自己的消息

### ISSUE THREAD

**Issue by jiajiaxd** [mamoe/mirai#1950]
### 问题描述

如图，我在一个群里自己回复了自己
![image](https://user-images.githubusercontent.com/51043917/160310793-edcbafe2-1b0b-4236-8686-3c91d768d324.png)
当我使用MessageChain.serializeToMiraiCode()方法，返回的内容仅有“撤回”二字，而不包含miraicode内容

### 复现

在群里自己回复自己，控制台内输出MessageChain.serializeToMiraiCode()返回的结果

### mirai-core 版本

2.10.1

### bot-protocol

ANDROID_PAD

### 其他组件版本

Mirai-Console-2.10.1

**Comment by Karlatemp** [comment]
https://github.com/mamoe/mirai/blob/dev/docs/Messages.md#%E7%94%B1-codablemessage-%E5%8F%96%E5%BE%97-mirai-%E7%A0%81%E5%AD%97%E7%AC%A6%E4%B8%B2

提问前请先看完文档
