### ISSUE TITLE
发送消息`0`，bot不会收到

### ISSUE THREAD

**Issue by 4o4E** [mamoe/mirai#1951]
### 问题描述

> 0

发送如上的一条消息，bot不会接收到此消息（或者说没有触发event）

### 复现

同上

### mirai-core 版本

2.10.0

### bot-protocol

IPAD

**Comment by Karlatemp** [comment]
提供网络日志

**Comment by 502milk** [comment]
啊...我也一样
是tx的锅
![@UH 0SM5(11F3~(MU689$76](https://user-images.githubusercontent.com/49502047/160375743-ea942ec4-5655-41ea-bed2-645a76b003b9.png)
![J5LM28 3K91R3MF3N{6_ZJ6](https://user-images.githubusercontent.com/49502047/160375751-77e7f25f-f448-4cfd-9e9e-1574b7387e85.jpg)
双端截图如上
![QQ截图20220328180731](https://user-images.githubusercontent.com/49502047/160376041-ac292c17-c99c-407b-ab2e-044158dea819.png)
这是日志截图

**Comment by LaoLittle** [comment]
你是`0`
