### ISSUE TITLE
用户手册缺少完整的对智能参数格式的描述

### ISSUE THREAD

**Issue by hundun000** [mamoe/mirai#1952]
当插件开发者为具体插件编写用户手册时，需要描述智能参数解析对应的参数，可以有哪些表达格式。例如：

> 参数1    类型: User    说明: 用mirai规定格式的UserID形式表达，详见下文
> 
> - `botId.groupId.memberId`
> - `botId.groupId.memberCard` (模糊搜索, 寻找最优匹配)
> - `~` (指代指令调用人自己. 仅聊天环境下)
> - `botId.groupId.$` (随机成员. )
> - `botId.friendId`
> 当处于一个群内时, `botId` 和 `groupId` 参数都可省略
>        当只登录了一个 [Bot] 时, `botId` 参数可省略

虽然插件开发者可以从CommandArgumentParserBuiltins.kt的注释里复制描述贴到插件用户手册里，但是可能错漏，也比较繁琐。如果官方用户手册补充相关说明，插件用户手册链接引用，应该更合适。

**Comment by hundun000** [comment]
move to #848

**Comment by Him188** [comment]
See https://github.com/mamoe/mirai/blob/dev/docs/ConsoleTerminal.md#%E6%8C%87%E4%BB%A4%E5%8F%82%E6%95%B0%E6%99%BA%E8%83%BD%E8%A7%A3%E6%9E%90
