### ISSUE TITLE
Bot发送私聊图片在电脑端无法显示

### ISSUE THREAD

**Issue by Simper16** [mamoe/mirai#196]
## 问题
Bot发送私聊图片在电脑端无法显示

## 如何复现

core:0.32.0
console:0.4.2
mirai-api-http:v1.4.1 ws:enabled
python-mirai:0.2.26
发送方法Image.fromFileSystem("./image.png")

**Comment by Him188** [comment]
无法复现问题. 经测试图片正常显示. 可能是偶然发生的上传失败
