### ISSUE TITLE
QQ号过大导致无法正常登录

### ISSUE THREAD

**Issue by black-zero358** [mamoe/mirai#1962]
### 问题描述

QQ号过大导致无法正常登录
![image](https://user-images.githubusercontent.com/53086059/161384770-4b36acdd-4e4c-4ec3-951c-7522748defd6.png)

### 复现

![image](https://user-images.githubusercontent.com/53086059/161385209-65b97d05-a923-4d01-8189-6fc195c9d724.png)

### mirai-core 版本

2.91

### bot-protocol

ANDROID_PAD

**Comment by 4o4E** [comment]
qq号应该是long而不是double

**Comment by 4o4E** [comment]
> qq号应该是long而不是double

从日志看只是密码错了登录失败

**Comment by black-zero358** [comment]
十分抱歉，double是我胡乱修改的，运行插件的时候是可以正常登录的，
但是尝试在idea里运行mirai-hello-world-master
24开头的qq号超过的最大整数，这种情况下该这么办？
![image](https://user-images.githubusercontent.com/53086059/161394583-a8848709-85a7-480a-9dcb-d5a9e4d19e77.png)

**Comment by 4o4E** [comment]
> 十分抱歉，double是我胡乱修改的，运行插件的时候是可以正常登录的，
> 但是尝试在idea里运行mirai-hello-world-master
> 24开头的qq号超过的最大整数，这种情况下该这么办？
> ![image](https://user-images.githubusercontent.com/53086059/161394583-a8848709-85a7-480a-9dcb-d5a9e4d19e77.png)
> 

定义long的时候不应该在后面加一个L吗

**Comment by jiajiaxd** [comment]
long yourQQNumber = 248...732**L**
