### ISSUE TITLE
[MiraiForum] 邮箱无法验证

### ISSUE THREAD

**Issue by aipiao-gh** [mamoe/mirai#1967]
我在 MiraiForum 上注册了账号 (MyUserName), 但是我始终无法收到验证邮箱, 我需要申请手动通过邮箱验证

**Comment by aipiao-gh** [comment]
我在 MiraiForum 上注册了账号 aipiao_, 但是我始终无法收到验证邮箱, 我需要申请手动通过邮箱验证

**Comment by Karlatemp** [comment]
请使用您注册时的邮箱向我(以下邮箱之一)发送邮件

- k@mamoe.net
- karlatemp@vip.qq.com
