### ISSUE TITLE
请考虑升级 log4j 版本到 2.17.2

### ISSUE THREAD

**Issue by shirok1** [mamoe/mirai#1969]
2.15.0 ~ 2.17.0 仍然有安全隐患。

<https://github.com/mamoe/mirai/blob/29ebf78a543ab830186bfc5d30059aaa4bd41f69/buildSrc/src/main/kotlin/Versions.kt#L51>

<https://mvnrepository.com/artifact/org.apache.logging.log4j/log4j-core>

**Comment by Him188** [comment]
mirai 使用 log4j 只是为了允许用其他日志系统替换内置。而且 mirai 默认只使用 SimpleMessage，应该没有安全问题。如果用户要用 log4j 接管日志，那么这就是用户的责任来解决安全问题（使用更好版本依赖覆盖 mirai 的）
