### ISSUE TITLE
特定群员权限没有继承任意群员权限

### ISSUE THREAD

**Issue by woruo27** [mamoe/mirai#1971]
### 问题描述

`t123.234`不会继承`t*`

`m123.234`及`m123.*`也不会继承`m*`和`g*`

### 复现

通过群123中的用户234发送临时会话消息时，使用以下代码调试：
```kotlin
eventChannel.subscribeAlways<GroupTempMessageEvent> {
	println(toCommandSender().permitteeId.asString())
	for (i in toCommandSender().permitteeId.directParents) {
		println(i.asString())
		for (j in i.directParents)
			println(j.asString())
	}
}
```
输出：
```
2022-04-10 04:04:46 I/stdout: t123.234
2022-04-10 04:04:46 I/stdout: m123.234
2022-04-10 04:04:46 I/stdout: m123.*
2022-04-10 04:04:46 I/stdout: u234
```

### mirai-core 版本

2.10.1

### bot-protocol

ANDROID_PHONE

### 其他组件版本

mirai-console: `2.10.1`

**Comment by Him188** [comment]
我记得应该是没有 `m*` 的，有 `m*.*`，而且 `m123.*` 应该是继承 `m*.*` 的。`t` 同理。

**Comment by Him188** [comment]
看了下文档和实现，有 `m*`，没有 `m*.*`。实现是正确的，`m123.234` 是继承 `m*` 的。你的示例只处理了两层 parent 关系而从 `t123.234` 到 `m*` 有三层，因此没有打印。

如我有遗漏可以 reopen。

----


文档：https://github.com/mamoe/mirai/blob/dev/mirai-console/docs/Permissions.md#%E5%AD%97%E7%AC%A6%E4%B8%B2%E8%A1%A8%E7%A4%BA
实现：https://github.com/mamoe/mirai/blob/15133c7902706dbdd9a2098b2d601b25636ce0fd/mirai-console/backend/mirai-console/src/permission/PermitteeId.kt#L223

**Comment by woruo27** [comment]
我仔细看了您给的源码上下文，`t123.234` 仅继承 `m123.234`，而 `t123.*` 和 `t*` 确实没有被继承。

`m*` 是有的，我疏忽了。

@Him188
