### ISSUE TITLE
IDEA 插件不支持 2022.1

### ISSUE THREAD

**Issue by Samarium150** [mamoe/mirai#1976]
### 问题描述

IDEA新建项目选项里没有mirai console插件的选项，论坛也有 [帖子](https://mirai.mamoe.net/topic/1128/idea%E6%8F%92%E4%BB%B6%E4%BC%BC%E4%B9%8E%E6%97%A0%E6%B3%95%E5%BF%AB%E6%8D%B7%E6%96%B0%E5%BB%BAmirai%E9%A1%B9%E7%9B%AE) 提到这个问题

### 复现

使用Intellij IDEA 2022.1安装mirai-console插件213-2.10.0-162-1并选择新建项目
![image](https://user-images.githubusercontent.com/28302241/163409085-4c9b5541-9458-4b2c-8344-2cbbafd45b69.png)

### mirai-core 版本

None

### bot-protocol

ANDROID_PHONE

### 其他组件版本

IDEA [mirai-console插件](https://plugins.jetbrains.com/plugin/15094-mirai-console) [213-2.10.0-162-1](https://plugins.jetbrains.com/plugin/15094-mirai-console/versions/stable/157901)

**Comment by Him188** [comment]
还不支持 2022.1，可先使用以前版本创建项目。
