### ISSUE TITLE
为什么要使用 Kotlin 1.4-M1 版本？

### ISSUE THREAD

**Issue by NanamiArihara** [mamoe/mirai#199]
https://github.com/mamoe/mirai/commit/eb7afb6cff98e90c78006a2c69c0275ab7f25649

我认为使用 1.4-M1 除了为开发环境，Gradle 依赖管理徒增负担以外没有任何理由。还需要 IDE 插件升级，还需要下载一堆新的编译插件，设置 pluginManagement，使用额外仓库，得不偿失。

目前的所有代码都能在 1.3.71 正常使用。

**Comment by Him188** [comment]
目前版本（0.33.0）使用的就是1.3.71，可以更换过来。在1.4编译的代码兼容现在的。

**Comment by Him188** [comment]
当时使用1.4是因为开发速度大幅提升（一次inspection在1.3要数分钟，1.4只需要一二十秒），编译耗时降低2/3，和一些重要的bug的修复。

而后发现只需要 Kotlin IDE 插件为 1.4 版即可体验以上改进，而不需要 stdlib 和 gradle 插件的更新。
