### ISSUE TITLE
统一 java Property 在布尔值状态下的判定条件

### ISSUE THREAD

**Issue by zhaodice** [mamoe/mirai#1990]
现在我有两行代码
```
        System.setProperty("mirai.slider.captcha.supported", "1")
        System.setProperty("mirai.jce.deserializer.debug", "true")
```
就很纳闷，一会要用1一会要用true，能不能统一一下，很晕欸

**Comment by zhaodice** [comment]
这边看了一下代码，`mirai.slider.captcha.supported`在非null时视为真，但`mirai.jce.deserializer.debug`是强制要求字符串为`true`，我的建议是尽可能把判定条件统一一下，以免以后造成混乱

**Comment by Karlatemp** [comment]
只有captcha这个特别的字段有特别的判断方式(因为这算是给普通用户使用的参数，直接判断空的jvm参数较为简短)，其他的全部都有统一的判断方法的（位于 core utils），而由于一些历史原因 captcha 这个参数实际上已经被弃用了

**Comment by zhaodice** [comment]
> captcha

哦那没事了
