### ISSUE TITLE
在插件的`onEnable`方法里使用`CoroutineScope`会导致堵塞

### ISSUE THREAD

**Issue by NoMathExpectation** [mamoe/mirai#1996]
### 问题描述

我在写一个订阅系统，写了以下方法：
```
fun subscribeChatRank() = runBlocking {
        launch {
            while (isActive) {
                val time = LocalDateTime.now()
                if (time.hour == 23 && time.minute == 59) {
                    //...
                    delay(60000L)
                }
                delay(10000L)
            }
        }
    }
```
然后在插件的`onEnable`方法里调用这个方法，结果插件加载到这里就堵塞了
把`runBlocking`换成`coroutineScope`也不行，不知道是怎么回事

### 复现

按上面的方法复现

### mirai-core 版本

2.11.0-M2.2

### bot-protocol

IPAD

**Comment by Him188** [comment]
不应该使用 runBlocking, 应该让该函数为 suspend fun

**Comment by Karlatemp** [comment]
```kotlin
internal fun startDaemonService() {
    MyPluginInstance.launch {
        // do something
    }
}
```

**Comment by Samarium150** [comment]
都`runBlocking`了当然会阻塞

**Comment by NoMathExpectation** [comment]
> 不应该使用 runBlocking, 应该让该函数为 suspend fun

然而我主类用的是java语言，用`@jvmBlockingBridge`注解方法还是不行



> ```kotlin
> internal fun startDaemonService() {
>     MyPluginInstance.launch {
>         // do something
>     }
> }
> ```

用了这个方法后就可以了，谢谢
