### ISSUE TITLE
mira的意思是未来么？

### ISSUE THREAD

**Issue by landall** [mamoe/mirai#2]
还是美玲？

**Comment by liujiahua123123** [comment]
感谢你的支持, 

正如你所更改的issue名字
Mirai是 日文中 未来的意思

**Comment by Him188** [comment]
你可以看我俩头像, 
栗山未来和初音未来

**Comment by landall** [comment]
> 你可以看我俩头像,
> 栗山未来和初音未来

没有未来的未来不是我想要的未来，wwwww

**Comment by liujiahua123123** [comment]
wwwww

**Comment by landall** [comment]
设计接口的话，我推荐参考一下CoolQ和MyPCQQ的接口，这样可以很方便地从CoolQ和MPQ那边迁移插件过来。另一个小朋友也在关注这个项目，他写了一个CoolQ Plugin的Pascal SDK。

**Comment by liujiahua123123** [comment]
我们会提供一个模块用来做这个方面的事情
mirai-core只是核心
- mirai-console是console驱动mirai
- mirai-web是web驱动mirai
我们在计划中提供类似的东西来作为中间件加载CoolQ和MPQ, 但目前还不是第一要务
