### ISSUE TITLE
Constructor-like functions

### ISSUE THREAD

**Issue by ice1000** [mamoe/mirai#20]
https://github.com/mamoe/mirai/blob/8948eb204307d361566626614817525e515eed9c/mirai-core/src/commonMain/kotlin/net.mamoe.mirai/Bot.kt#L37-L38

I understand why you need these. A better solution will be to overload the `invoke` operator for the companion object of `Bot`, which will give you identical invocation syntax and Kotlin will be happy with that (no function name warning anymore 😉)

**Comment by ice1000** [comment]
... and you can inline them.

**Comment by Him188** [comment]
Thank you!
I decided to write as top-level functions because in kotlin stdlib, they do so..
Seems your solution is better.

I'll consider to move them into companion objects.

**Comment by ice1000** [comment]
> I decided to write as top-level functions because in kotlin stdlib, they do so..


Woo, are they? I didn't know of any, can you show me some? 😉😉😉😉

**Comment by Him188** [comment]
Hmm..Probably not from stdlib.

`Job()` from coroutines(maybe stdlib)
`ByteReadPacket()` from coroutines.io

And I've found some use of invoke overloads in kclock(A time and date lib)

**Comment by ice1000** [comment]
Uuughh
