### ISSUE TITLE
机器人登陆后一段时间会掉线

### ISSUE THREAD

**Issue by ForthTurn** [mamoe/mirai#200]
## 问题

机器人登录后，一段时间会掉线（刚开始心跳检测是正常的）。并给出以下信息：
![GBWUSg.png](https://s1.ax1x.com/2020/04/05/GBWUSg.png)

## 如何复现

使用screen命令新建窗口，以
`java -jar mirai-console-warpper-0.2.0-all.jar`
运行
登录机器人后`ctrl+a`,`d`后在后台运行，一段时间后出现上述信息并离线。

版本信息：
You are running Mirai-Console-Wrapper under /root/qqbot
Starting Mirai Console Pure, reset by clear /content/
Local Core Version: 0.33.0 | Newest Core Version: 0.33.0
Local Console-Pure Version: 0.4.2 | Newest Console-Pure Version: 0.4.2

系统信息：
OS: Debian 9.12 stretch
Kernel: x86_64 Linux 4.9.0-12-amd64
Uptime: 4d 2h 7m
Packages: 702
Shell: bash 4.4.12
CPU: Intel Xeon Platinum 8163 CPU @ 2.5GHz
RAM: 1765MiB / 3955MiB

**Comment by Him188** [comment]
这是现阶段正常情况，服务器就是会不定时断开连接（或因为你的网络问题），需要客户端重连。解决方法为 #119
