### ISSUE TITLE
Image（net.mamoe.mirai.message.data.Image）实例能否转换成Base64 String

### ISSUE THREAD

**Issue by WutzuBert** [mamoe/mirai#2005]
我需要对接百度官方的图文审核接口，其中图片审核参数需要图片的Base64编码
请问Mirai是否有这方面的api，或者可以转换成其他能转换成Base64的类型的方法

**Comment by Him188** [comment]
你说的可能是下载图片，阅读文档

**Comment by WutzuBert** [comment]
> 你说的可能是下载图片，阅读文档

我指的是从MessageChain实例中筛选出来的Image实例（）

**Comment by cssxsh** [comment]
百度官方的图文审核接口 不必须提交 字节内容（base64），也可以直接提交 图片下载 url
![image](https://user-images.githubusercontent.com/32539286/166343083-15f0118f-2449-4c7d-9c4c-1d60fcc44f63.png)

**Comment by Karlatemp** [comment]
`其中图片审核参数需要图片的Base64编码` 您指的应该是图片内容, 请参考 [`下载图片`](https://github.com/mamoe/mirai/blob/dev/mirai-core-api/src/commonMain/kotlin/message/data/Image.kt)
如果您指的是 `序列化图片`, 请参考 [Doc#序列化图片](https://github.com/mamoe/mirai/blob/dev/docs/Messages.md#%E5%BA%8F%E5%88%97%E5%8C%96)

**Comment by Samarium150** [comment]
```kotlin
val buffer = withContext(Dispatchers.IO) {                        
    ImageIO.read(URL(image.queryUrl()))
}
val output = ByteArrayOutputStream()
withContext(Dispatchers.IO) {
    ImageIO.write(buffer, image.imageType.name, output)
}
val base64 = Base64.getEncoder().encodeToString(output.toByteArray())
```

**Comment by landall** [comment]
> ```kotlin
> val buffer = withContext(Dispatchers.IO) {                        
>     ImageIO.read(URL(image.queryUrl()))
> }
> val output = ByteArrayOutputStream()
> withContext(Dispatchers.IO) {
>     ImageIO.write(buffer, image.imageType.name, output)
> }
> val base64 = Base64.getEncoder().encodeToString(output.toByteArray())
> ```

我实际跑起来时，感觉下载图片还挺慢的（超过30秒），Webhook需要保证不超时，同步执行要特殊处理卡住不响应的情况。这个地方可能工程化代码需要更完善。

**Comment by Keyezi** [comment]
我写了这个API的实现，可以看看我的https://github.com/Keyezi/cc.ymgg.de-aphrodisiac
