### ISSUE TITLE
希望增加rpm发布方式

### ISSUE THREAD

**Issue by landall** [mamoe/mirai#2008]
CentOS 7可以只依赖一个包：java-latest-openjdk（属于epel仓库）
我是手动wget了wget https://maven.aliyun.com/repository/public/org/itxtech/mcl/2.0.1/mcl-2.0.1.zip
这个打rpm包应该并不难。

unzip mcl-2.0.1.zip
chmod +x mcl

这样应该就能跑起来了。

**Comment by landall** [comment]
等等，我是不是应该把这个需求提给mcl项目，而不是mirai项目。
似乎mirai和mirai-console只是个library，并不是application？

**Comment by Him188** [comment]
你确实应该给 mcl 提交

**Comment by landall** [comment]
> 你确实应该给 mcl 提交

抱歉，2019年来看过这个项目之后，中间一直没太有时间关注这块。这几天才有时间看，感觉你们的生态已经跟那会你们两个人刚写完协议时完全不一样了 T_T
你头像都不是未来了，哈哈。

然后就是，如果希望mcl启动时打印的login信息里输出登录参数（比如使用了哪个协议），这个在现在的体系下是属于mirai-console的还是mcl的？
我刚简单看完mcl和mirai-console后端的代码，还没搞清楚这三个部分的职能区别 = =

2022-05-05 00:50:32 I/Bot.4114147: Saved account secrets to local cache for fast login.
2022-05-05 00:50:32 I/Bot.4114147: Login successful.

大概就是这里希望增加更多的Log信息。这是属于哪边管的？

**Comment by Him188** [comment]
mirai-core 提供协议实现，是一个 library，依赖它就能获得 Bot 功能。登录和你正在考虑的日志问题是 mirai-core 实现的。

mirai-console 依赖 mirai-core，是一个 application（与前端组合），一个插件平台。

mcl 全名是 mirai-console-loader 即 mirai-console 启动器。只负责启动 mirai-console（和 terminal 前端），以及提供自动下载和更新 console 和插件的功能。

**Comment by landall** [comment]
> mirai-core 提供协议实现，是一个 library，依赖它就能获得 Bot 功能。登录和你正在考虑的日志问题是 mirai-core 实现的。
> 
> mirai-console 依赖 mirai-core，是一个 application（与前端组合），一个插件平台。
> 
> mcl 全名是 mirai-console-loader 即 mirai-console 启动器。只负责启动 mirai-console（和 terminal 前端），以及提供自动下载和更新 console 和插件的功能。

mcl负责给mirai-console指定启动的配置文件和环境变量么？
我感觉如果mcl在启动这件事上没特别的作用的话，其实rpm这个需求是可以提给mirai-console的。

现在mirai-console、mcl、mcl installer三个的职能其实挺奇怪的。

我的理解是，mirai-console就应该提供目前./mcl启动的职能。
然后mcl的作用相当于yum和maven，负责更新插件。如果使用mcl启动，那么mcl会自动检查下插件是否有更新。如果不想升级插件，直接mirai-console启动就可以了。
感觉这个启动上的耦合不是很有必要的样子，反而会阻止mirai-console在未来进一步service化。

mirai-console自己使用rpm等标准渠道发布，其实是一件跟mcl没关系的事情。

**Comment by Him188** [comment]
> > mirai-core 提供协议实现，是一个 library，依赖它就能获得 Bot 功能。登录和你正在考虑的日志问题是 mirai-core 实现的。
> > mirai-console 依赖 mirai-core，是一个 application（与前端组合），一个插件平台。
> > mcl 全名是 mirai-console-loader 即 mirai-console 启动器。只负责启动 mirai-console（和 terminal 前端），以及提供自动下载和更新 console 和插件的功能。
> 
> mcl负责给mirai-console指定启动的配置文件和环境变量么？ 我感觉如果mcl在启动这件事上没特别的作用的话，其实rpm这个需求是可以提给mirai-console的。
> 
> 现在mirai-console、mcl、mcl installer三个的职能其实挺奇怪的。
> 
> 我的理解是，mirai-console就应该提供目前./mcl启动的职能。 然后mcl的作用相当于yum和maven，负责更新插件。如果使用mcl启动，那么mcl会自动检查下插件是否有更新。如果不想升级插件，直接mirai-console启动就可以了。 感觉这个启动上的耦合不是很有必要的样子，反而会阻止mirai-console在未来进一步service化。
> 
> mirai-console自己使用rpm等标准渠道发布，其实是一件跟mcl没关系的事情。

console 目前其实是可以独立启动的, terminal 前端有提供 main, 也可以在测试中通过 terminal 前端启动测试实例. 可能我之前没有表述清楚
目前 mcl 的作用确实是符合你的理解的

**Comment by landall** [comment]
> > > mirai-core 提供协议实现，是一个 library，依赖它就能获得 Bot 功能。登录和你正在考虑的日志问题是 mirai-core 实现的。
> > > mirai-console 依赖 mirai-core，是一个 application（与前端组合），一个插件平台。
> > > mcl 全名是 mirai-console-loader 即 mirai-console 启动器。只负责启动 mirai-console（和 terminal 前端），以及提供自动下载和更新 console 和插件的功能。
> > 
> > 
> > mcl负责给mirai-console指定启动的配置文件和环境变量么？ 我感觉如果mcl在启动这件事上没特别的作用的话，其实rpm这个需求是可以提给mirai-console的。
> > 现在mirai-console、mcl、mcl installer三个的职能其实挺奇怪的。
> > 我的理解是，mirai-console就应该提供目前./mcl启动的职能。 然后mcl的作用相当于yum和maven，负责更新插件。如果使用mcl启动，那么mcl会自动检查下插件是否有更新。如果不想升级插件，直接mirai-console启动就可以了。 感觉这个启动上的耦合不是很有必要的样子，反而会阻止mirai-console在未来进一步service化。
> > mirai-console自己使用rpm等标准渠道发布，其实是一件跟mcl没关系的事情。
> 
> console 目前其实是可以独立启动的, terminal 前端有提供 main, 也可以在测试中通过 terminal 前端启动测试实例. 可能我之前没有表述清楚 目前 mcl 的作用确实是符合你的理解的

那为什么现在doc里还是推荐大家用mcl启动console？我感觉console自己作为最前端是更合理的release模式。没必要把console绑定到plugin市场的生态里去。这样也容易理解每一块的具体使命。
