### ISSUE TITLE
支持根据MessageId进行撤回或引用

### ISSUE THREAD

**Issue by Logiase** [mamoe/mirai#201]
### 建议增加使用MessageSource.id进行引用及回复的功能

**Comment by Him188** [comment]
使用 MessageSource.id 进行回复是不可能的。但可以想其他办法

**Comment by Chenwe-i-lin** [comment]
mirai-api-http 不是有个缓存吗, 抄过来呗

**Comment by Him188** [comment]
缓存消耗内存太大，并且效果有限

**Comment by Him188** [comment]
撤回群消息需要 int id, int sequence, int sender, int target，撤回好友消息时还额外需要 int time。
目前打算将他们用 ProtoBuf 等途径序列化后以便保存，见#219

**Comment by takayama-lily** [comment]
还是建议搞个数据库保存消息

**Comment by 1523789353** [comment]
啊这,难怪CQhttp没法用messag_id撤回

**Comment by Him188** [comment]
将在 #219 一并解决
