### ISSUE TITLE
支持视频短片类型

### ISSUE THREAD

**Issue by landall** [mamoe/mirai#2011]
{"type":"Plain","text":"你的QQ暂不支持查看视频短片，请期待后续版本。"}
这是转发NodeList里的一行记录。
应该是视频短片类型没有被支持。

另外我发现直接转发视频给个人QQ，会被视为发送文件，HTTP插件模块不会产生任何webhook事件。

**Comment by Him188** [comment]
有可能和 #1664 指的是一个事情, 不太确认

**Comment by landall** [comment]
应该是两件事。
#1664 跟我说的那个【另外】是一件事的可能性更大。

另外我有个问题，怎么查看自己当前生效的是哪个QQ协议？我用mcl启动bot后，在QQ PC端看不到移动端是哪个设备在登录，然后console的输出里也没打印过登录用协议类型。
我自己拿iphone登录，不管哪个协议都会跟iphone互相挤下线，包括IPAD协议，我就没办法搞清楚，是其中一套协议不支持【视频短片】和【发送视频文件】，还是四套协议都不支持。

**Comment by Him188** [comment]
所有都不支持视频

**Comment by landall** [comment]
> 所有都不支持视频

是因为现在协议解析的进度问题，还是你们对视频没开发兴趣，哈哈。
我看Mirai这边好多指令还没解包。（虽然我觉得最好别碰支付和红包相关的协议，容易进入灰产圈子）

**Comment by Him188** [comment]
没有足够时间，不过欢迎PR

**Comment by Him188** [comment]
目前的主要发展方向是提升代码质量，让 mirai 更容易维护，让 PR 更容易。这就包括了重构掉自 1.0 时期（我刚学 Kotlin 时）的代码，修复系统性问题（如 2.11 解决插件类隔离这个多系统的复杂问题）。可以发现大概从 mirai 2.7 我们就在做这些事情了。

新增一个新功能是要花费很多精力。要设计可靠易用的 API，要覆盖测试，要考虑未来扩展，反而协议是最简单的内容。

我认为 mirai 发展到现在已经有不小规模，需要优先保证各方面的稳定性。不但功能要稳定，代码要有一定质量，还要使项目能够在未来由其他人接手。所以没有一味地增加更多功能。

**Comment by landall** [comment]
> 目前的主要发展方向是提升代码质量，让 mirai 更容易维护，让 PR 更容易。这就包括了重构掉自 1.0 时期（我刚学 Kotlin 时）的代码，修复系统性问题（如 2.11 解决插件类隔离这个多系统的复杂问题）。
> 
> 新增一个新功能是要花费很多精力。要设计可靠易用的 API，要覆盖测试，要考虑未来扩展，反而协议是最简单的内容。
> 
> 我认为 mirai 发展到现在已经有不小规模，需要优先保证各方面的稳定性。不但功能要稳定，代码要有一定质量，还要使项目能够在未来由其他人接手。所以没有一味地增加更多功能。

说到这个问题，我个人觉得你们的代码分层分得有点多了，我不确定是不是Kotlin的语言特性导致的。但我感觉纯抽象层有点过多了，导致从console一直穿到一个具体的事情的实现代码，中间需要穿过好多层封装才能追踪到。

**Comment by landall** [comment]
> 没有足够时间，不过欢迎PR

等我在仔细读一下代码吧，你也看到了，我上次看你们代码至少是在18个月前了，我整体读代码还是在2019年那会，那次我基本把项目80%以上的代码看了一遍。现在定位一个功能在哪里实现的，都有点小障碍。

**Comment by lngex** [comment]
> 没有足够时间，不过欢迎PR

请问这个议题目前有日程没
