### ISSUE TITLE
fork后运行CI失败

### ISSUE THREAD

**Issue by landall** [mamoe/mirai#2013]
### 问题描述

跟upstream sync后，Actions运行失败，导致无法merge代码。

Starting a Gradle Daemon (subsequent builds will be faster)
> Task :buildSrc:compileKotlin
> Task :buildSrc:compileKotlin FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':buildSrc:compileKotlin'.
> Could not resolve all files for configuration ':buildSrc:kotlinCompilerPluginClasspath'.
   > Could not resolve org.jetbrains.kotlin:kotlin-sam-with-receiver:1.4.20.
     Required by:
         project :buildSrc
      > Could not resolve org.jetbrains.kotlin:kotlin-sam-with-receiver:1.4.20.
         > Could not get resource 'https://jcenter.bintray.com/org/jetbrains/kotlin/kotlin-sam-with-receiver/1.4.20/kotlin-sam-with-receiver-1.4.20.pom'.
            > Could not HEAD 'https://jcenter.bintray.com/org/jetbrains/kotlin/kotlin-sam-with-receiver/1.4.20/kotlin-sam-with-receiver-1.4.20.pom'.
               > Read timed out
   > Could not resolve org.jetbrains.kotlin:kotlin-scripting-compiler-impl-embeddable:1.4.20.
     Required by:
         project :buildSrc > org.jetbrains.kotlin:kotlin-scripting-compiler-embeddable:1.4.20
      > Skipped due to earlier error

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 2m [22](https://github.com/landall/mirai/runs/6292731437?check_suite_focus=true#step:5:22)s
Error: Process completed with exit code 1.

### 复现

之前fork的旧版本，从upstream同步。

### mirai-core 版本

-

### bot-protocol

ANDROID_PHONE

**Comment by Him188** [comment]
看起来是你操作不当导致的，你的仓库代码最后修改时间是 18 个月前。合并上游时推荐使用 rebase。

**Comment by Nambers** [comment]
你可能需要把jcenter去掉 https://github.com/landall/mirai/blob/master/build.gradle.kts#:~:text=mavenCentral()-,jcenter(),-google()
而现在的mirai是没有这个的，看看是不是merge操作有问题?
https://github.com/mamoe/mirai/blob/dev/build.gradle.kts

**Comment by landall** [comment]
> 你可能需要把jcenter去掉 https://github.com/landall/mirai/blob/master/build.gradle.kts#:~:text=mavenCentral()-,jcenter(),-google() 而现在的mirai是没有这个的，看看是不是merge操作有问题? https://github.com/mamoe/mirai/blob/dev/build.gradle.kts

这个是合并失败的，还是18个月前的版本。
我是直接在Github网页上点的fetch upstream，然后会触发CI，不知道为啥……
以前没Github Actions时是可以这么做的，我可能需要研究下Github的Help了。

**Comment by Nambers** [comment]
CI失败也不会阻止merge吧? 我没用过网页，我都是本地CLI的(
如果有conflict可能merge会出现奇奇怪怪的问题

**Comment by Karlatemp** [comment]
您的 fork 的代码过于久远, 而且只有一个分支, 如果您想向我们提交 pr 我们建议您重新 fork 一次, 并且我们现在的默认分支是 `dev`.

由于您的 issue 严格意义上来讲与 mirai 无关, 我将会关闭此 issue

**Comment by landall** [comment]
> 您的 fork 的代码过于久远, 而且只有一个分支, 如果您想向我们提交 pr 我们建议您重新 fork 一次, 并且我们现在的默认分支是 `dev`.
> 
> 由于您的 issue 严格意义上来讲与 mirai 无关, 我将会关闭此 issue

好的，大概率应该是我自己的问题了。

**Comment by landall** [comment]
> CI失败也不会阻止merge吧? 我没用过网页，我都是本地CLI的( 如果有conflict可能merge会出现奇奇怪怪的问题

于是我重新删除项目，重新fork了 T_T
