### ISSUE TITLE
Handle注解改进

### ISSUE THREAD

**Issue by soundofautumn** [mamoe/mirai#2020]
建议在@Handle注解里加上@SuppressWarnings("unused")来抑制报错

**Comment by Him188** [comment]
应该是可以忽略使用了 `@Handle` 的注解的方法的 unused 的

**Comment by soundofautumn** [comment]
但是好像idea里我鼠标放到用@handle修饰的方法上面还是会显示方法未使用，加了@SuppressWarnings("unused")才解除

**Comment by Him188** [comment]
按 Alt + Enter, 'Suppress unused warnings with `@Handle`', 应该有这个

**Comment by Alceatraz** [comment]
ideal里可以“忽略被XXX注解的unused”，对着unused的比如class的名字点灯泡
![Dingtalk_20220509135337](https://user-images.githubusercontent.com/8266702/167348671-8afaff61-d2fc-43dd-9aa1-b1d0480bce3c.jpg)

**Comment by soundofautumn** [comment]
哦哦好的，那能在插件里实现这一功能吗？

**Comment by Him188** [comment]
应该是能的但是不太有必要, 因为 IDE 已经实现了
