### ISSUE TITLE
console 2.11.0-RC2没有加载插件所导入的包

### ISSUE THREAD

**Issue by myot233** [mamoe/mirai#2026]
### 问题描述

mirai console 2.11.0-RC2 在加载了一个通过implementation 导入的sqlite的包的插件时无法找到类java.sql.Driver
该插件也是通过2.11.0-RC2构建的
该问题在2.11.0-M1 并没有出现
导入的包：org.xerial.sqlite-jdbc:3.36.0.3

### 复现

[XXYan-0.0.1.mirai2.jar.zip](https://github.com/mamoe/mirai/files/8665639/XXYan-0.0.1.mirai2.jar.zip)
通过该插件可以复现

### mirai-core 版本

2.11.0 RC2

### bot-protocol

ANDROID_PHONE

### 其他组件版本

无

### 补充信息

![0B9O{6(NPB_YF010ER97JJ3](https://user-images.githubusercontent.com/66019007/167744356-8ef18855-7c56-4835-8754-bca21ffcbffc.png)

**Comment by NoMathExpectation** [comment]
是 #2009 吧

**Comment by Him188** [comment]
> 是 #2009 吧

是的, CC @Karlatemp
