### ISSUE TITLE
子项目间依赖，buildPlugin未把被依赖的源码一起打包

### ISSUE THREAD

**Issue by hundun000** [mamoe/mirai#2038]
### 问题描述

如下bot-plugin依赖bot-core，未使用asNormalDep，预期bot-core源码被打包。实际bot-core源码未打包。

```
project(":bot-plugin") {

    dependencies {
        implementation project(":bot-core")
    }

}

project(":bot-core") {

    dependencies {
        api "com.zaxxer:SparseBitSet:1.2"
    }
}
```

![image](https://user-images.githubusercontent.com/22592888/168791410-10b50a36-2f12-41c0-afd0-60b6669f8028.png)

### 复现

[上述项目仓库](https://github.com/hundun000/multi-subproject-mirai-plugin-template)

### mirai-core 版本

2.11.0-RC2

### bot-protocol

ANDROID_PHONE

**Comment by Him188** [comment]
好像已经修复了, @Karlatemp

**Comment by hundun000** [comment]
#1973 修复前，第三方依赖（"com.zaxxer:SparseBitSet:1.2"）也会被打包。现在，第三方依赖正确出现在dependencies-private.txt了，但是bot-core源码也不打包了。
