### ISSUE TITLE
发送好友消息报错

### ISSUE THREAD

**Issue by cheerryio** [mamoe/mirai#205]
## 问题

调用http-api sendFriendMessage报错，,返回code 500，消息无法发送

## 日志
![QQ图片20200407111936](https://user-images.githubusercontent.com/50071687/78626552-b04bcb80-78c1-11ea-82d3-f9676c92f7c4.png)
### http-api返回信息
![QQ图片20200407112052](https://user-images.githubusercontent.com/50071687/78626621-dc674c80-78c1-11ea-8a69-f639e8d06c5e.png)

## 环境
root@VM-0-13-ubuntu:/home/ubuntu# java -version
openjdk version "11.0.6" 2020-01-14
OpenJDK Runtime Environment (build 11.0.6+10-post-Ubuntu-1ubuntu118.04.1)
OpenJDK 64-Bit Server VM (build 11.0.6+10-post-Ubuntu-1ubuntu118.04.1, mixed mode, sharing)

mirai-console-wrapper-0.2.0-all.jar  mirai-console-wrapper-0.1.3-all.jar均出现问题

## 如何复现

关于如何复现就有点难。记得第一次出现这个bug是在腾讯风控识别我发送了太多消息，涉及传播什么什么信息。（但是也不严重，就改了一个密码就能够重新登录）
这个操作完了以后有立马改了一下http-api plugin的settings.yml,更改了cache-size=10000,和authKey
然后启动console就出现了问题。

期间有一次启动尽管仍然抱这个错误，但是sendFriendMessage仍然能发送出去消息

**Comment by cheerryio** [comment]
刚才尝试启动 console-0.2.0报错, 0.1.3能够正常启动

![QQ图片20200407112945](https://user-images.githubusercontent.com/50071687/78627100-37e60a00-78c3-11ea-8182-2b6912a03539.png)

**Comment by Him188** [comment]
core 更新时未考虑编译器在编译带默认参数的构造器时会创建一个 synthetic 构造器来实现默认值。需要 mirai-api-http 重新编译即可解决问题

**Comment by cheerryio** [comment]
重载下载最新版 mirai-http-api jar包解决问题，感谢
