### ISSUE TITLE
如何在android studio上运行该项目？ 

### ISSUE THREAD

**Issue by cwuom** [mamoe/mirai#2050]
del

**Comment by Karlatemp** [comment]
`android.permission.INTERNET` & `android.permission.ACCESS_NETWORK_STATE`?

**Comment by cwuom** [comment]
del

**Comment by cwuom** [comment]
> `android.permission.INTERNET` & `android.permission.ACCESS_NETWORK_STATE`?

在IDEA下可以使用，但是到as就报版本过低了怎么办

**Comment by xtexChooser** [comment]
没给权限吧，AndroidManifests定义INTERNET权限试试？

**Comment by cwuom** [comment]
> 没给权限吧，AndroidManifests定义INTERNET权限试试？

给了已经

**Comment by MrXiaoM** [comment]
> > 
> 又报错这个怎么办
> E/AndroidRuntime: FATAL EXCEPTION: main
>     Process: com.cwuom.tread, PID: 9094
>     java.lang.RuntimeException: Unable to start activity ComponentInfo{com.cwuom.tread/com.cwuom.tread.MainActivity}: net.mamoe.mirai.network.WrongPasswordException: Error(bot=Bot(1523363419), code=235, title=温馨提示, message=当前版本过低，请升级到QQ最新版本。, errorInfo=��)
>         at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3270)
>         at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3409)
>         at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
>         at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
>         at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
>         at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016)
>         at android.os.Handler.dispatchMessage(Handler.java:107)
>         at android.os.Looper.loop(Looper.java:214)
>         at android.app.ActivityThread.main(ActivityThread.java:7356)
>         at java.lang.reflect.Method.invoke(Native Method)
>         at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
>         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
>      Caused by: net.mamoe.mirai.network.WrongPasswordException: Error(bot=Bot(1523363419), code=235, title=温馨提示, message=当前版本过低，请升级到QQ最新版本。, errorInfo=��)
>         at net.mamoe.mirai.internal.network.components.SsoProcessorImpl$SlowLoginImpl.doLogin(SsoProcessor.kt:282)
>         at net.mamoe.mirai.internal.network.components.SsoProcessorImpl$SlowLoginImpl$doLogin$1.invokeSuspend(Unknown Source:14)
>         at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
>         at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:33)
>         at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102)
>         at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
>         at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
>         at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
>         at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:749)
>         at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
>         at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
> I/Bot 1523363419: Bot cancelled: Bot closed
> 
https://github.com/mamoe/mirai/blob/dev/docs/Bots.md#%E5%B8%B8%E8%A7%81%E7%99%BB%E5%BD%95%E5%A4%B1%E8%B4%A5%E5%8E%9F%E5%9B%A0

当前版本过低  
可能原因：密码错误	  
可能的解决方法：检查密码或修改密码到 16 位以内

**Comment by cwuom** [comment]
> > > 
> > 
> > 
> > 又报错这个怎么办
> > E/AndroidRuntime: FATAL EXCEPTION: main
> > Process: com.cwuom.tread, PID: 9094
> > java.lang.RuntimeException: Unable to start activity ComponentInfo{com.cwuom.tread/com.cwuom.tread.MainActivity}: net.mamoe.mirai.network.WrongPasswordException: Error(bot=Bot(1523363419), code=235, title=温馨提示, message=当前版本过低，请升级到QQ最新版本。, errorInfo=��)
> > at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3270)
> > at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3409)
> > at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
> > at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
> > at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
> > at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016)
> > at android.os.Handler.dispatchMessage(Handler.java:107)
> > at android.os.Looper.loop(Looper.java:214)
> > at android.app.ActivityThread.main(ActivityThread.java:7356)
> > at java.lang.reflect.Method.invoke(Native Method)
> > at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
> > at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
> > Caused by: net.mamoe.mirai.network.WrongPasswordException: Error(bot=Bot(1523363419), code=235, title=温馨提示, message=当前版本过低，请升级到QQ最新版本。, errorInfo=��)
> > at net.mamoe.mirai.internal.network.components.SsoProcessorImpl$SlowLoginImpl.doLogin(SsoProcessor.kt:282)
> > at net.mamoe.mirai.internal.network.components.SsoProcessorImpl$SlowLoginImpl$doLogin$1.invokeSuspend(Unknown Source:14)
> > at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
> > at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:33)
> > at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102)
> > at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
> > at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
> > at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
> > at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:749)
> > at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
> > at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
> > I/Bot 1523363419: Bot cancelled: Bot closed
> 
> https://github.com/mamoe/mirai/blob/dev/docs/Bots.md#%E5%B8%B8%E8%A7%81%E7%99%BB%E5%BD%95%E5%A4%B1%E8%B4%A5%E5%8E%9F%E5%9B%A0
> 
> 当前版本过低 可能原因：密码错误 可能的解决方法：检查密码或修改密码到 16 位以内

密码是正确的，因为我在IDEA上是可以编译成功的
而且我也验证过了

**Comment by StageGuard** [comment]
把idea上登陆成功的device信息放到as里试试

**Comment by cwuom** [comment]
> 把idea上登陆成功的device信息放到as里试试

这个办法确实可行
但是有没有办法在android上加载验证码之类的，不用复制验证信息

**Comment by StageGuard** [comment]
> > 把idea上登陆成功的device信息放到as里试试
> 
> 这个办法确实可行 但是有没有办法在android上加载验证码之类的，不用复制验证信息

既然都android了那自己实现一个LoginSolver不就好了

**Comment by cwuom** [comment]
> > > 把idea上登陆成功的device信息放到as里试试
> > 
> > 
> > 这个办法确实可行 但是有没有办法在android上加载验证码之类的，不用复制验证信息
> 
> 既然都android了那自己实现一个LoginSolver不就好了

具体如何实现呢？ 我没找到相关文档....

**Comment by StageGuard** [comment]
> > > > 把idea上登陆成功的device信息放到as里试试
> > > 
> > > 
> > > 这个办法确实可行 但是有没有办法在android上加载验证码之类的，不用复制验证信息
> > 
> > 
> > 既然都android了那自己实现一个LoginSolver不就好了
> 
> 具体如何实现呢？ 我没找到相关文档....

参考 [MiraiAndroid](https://github.com/mzdluo123/MiraiAndroid)：[AndroidLoginSolver.kt](https://github.com/mzdluo123/MiraiAndroid/blob/master/app/src/main/java/io/github/mzdluo123/mirai/android/miraiconsole/AndroidLoginSolver.kt) 和 [CaptchaActivity.kt](https://github.com/mzdluo123/MiraiAndroid/blob/master/app/src/main/java/io/github/mzdluo123/mirai/android/activity/CaptchaActivity.kt)

**Comment by cwuom** [comment]
del

**Comment by xtexx** [comment]
> build.gradle

你倒是添加一个Run Configuration然后运行啊你

**Comment by StageGuard** [comment]
> > > > > > 把idea上登陆成功的device信息放到as里试试
> > > > > 
> > > > > 
> > > > > 这个办法确实可行 但是有没有办法在android上加载验证码之类的，不用复制验证信息
> > > > 
> > > > 
> > > > 既然都android了那自己实现一个LoginSolver不就好了
> > > 
> > > 
> > > 具体如何实现呢？ 我没找到相关文档....
> > 
> > 
> > 参考 [MiraiAndroid](https://github.com/mzdluo123/MiraiAndroid)：[AndroidLoginSolver.kt](https://github.com/mzdluo123/MiraiAndroid/blob/master/app/src/main/java/io/github/mzdluo123/mirai/android/miraiconsole/AndroidLoginSolver.kt) 和 [CaptchaActivity.kt](https://github.com/mzdluo123/MiraiAndroid/blob/master/app/src/main/java/io/github/mzdluo123/mirai/android/activity/CaptchaActivity.kt)
> 
> [MiraiAndroid](https://github.com/mzdluo123/MiraiAndroid) 克隆下来以后一直无法编译 也不爆红 ![image](https://user-images.githubusercontent.com/74239856/169637648-39a39ccd-92e6-484f-bf69-5476a80e377c.png)
> 
> 是不是AS版本的问题，我前几天刚下的新版，build.gradle可能不兼容 不知道怎么办

你不用跑他的代码啊，只需要明白怎么创建 LoginSolver 不就行了。。

**Comment by cwuom** [comment]
del

**Comment by Karlatemp** [comment]
> 温馨提示, message=当前版本过低，请升级到QQ最新版本。

此信息来自服务器的某种安全策略，这并不是我们目前能够解决的。目前我们已知的就是密码错误，LoginSolver 错误。

> 问题是我想要他代码里的 LoginSolver效果 我自己不知道怎么写

您需要的可能是 [`Search: Android dynamic create activity`](https://www.google.com/search?q=Android+dynamic+create+activity&oq=Android+dynamic+create+activity). 我们建议您多参考 StackOverflow 等站点的回答, 您可以在这些站点找到大部分您需要的东西. 如果有需要的话, 您还可以使用[此工具](https://translate.google.cn)
