### ISSUE TITLE
idea中正常运行，插件打包之后在mcl环境中乱码

### ISSUE THREAD

**Issue by black-zero358** [mamoe/mirai#2057]
### 问题描述

操作为读取一个csv并输出，在idea中可以正常运行，但是打包成jar后在mcl中运行会出现乱码

idea中版本为
plugins {
    val kotlinVersion = "1.5.10"
    kotlin("jvm") version kotlinVersion
    kotlin("plugin.serialization") version kotlinVersion

    id("net.mamoe.mirai-console") version "2.10.3"
}
mcl版本为2.11.0

### 复现

操作为读取一个csv并输出，在idea中可以正常运行，但是打包成jar后在mcl中运行会出现乱码

idea中版本为
plugins {
    val kotlinVersion = "1.5.10"
    kotlin("jvm") version kotlinVersion
    kotlin("plugin.serialization") version kotlinVersion

    id("net.mamoe.mirai-console") version "2.10.3"
}
mcl版本为2.11.0

### mirai-core 版本

2.10.3

### bot-protocol

ANDROID_PAD

**Comment by cssxsh** [comment]
你应该检查一下 csv文件的编码 和 mcl 启动终端的编码 是否一致

**Comment by Karlatemp** [comment]
关于乱码你应该在读取的时候指定使用 UTF8 而不是依靠系统默认编码, 很明显这不属于 mirai 的错误

**Comment by bin-tenkuu** [comment]
老问题了，excel默认的csv编码是gbk
