### ISSUE TITLE
打包插件时嵌入远程仓库信息

### ISSUE THREAD

**Issue by minoism** [mamoe/mirai#2060]
感觉比起内置 [默认的远程仓库列表](https://github.com/mamoe/mirai/blob/dev/mirai-console/docs/plugin/JVMPlugin.md#%E9%BB%98%E8%AE%A4%E7%9A%84%E8%BF%9C%E7%A8%8B%E4%BB%93%E5%BA%93%E5%88%97%E8%A1%A8), 似乎在打包阶段包含 `pom.xml` 或 **包含远程仓库信息的文件** 会更好？有时候我使用的一些依赖是存在于 maven snapshot 或者 jitpack 的，因此这些依赖必须要声明一个 `shadowLink` 或者引用 `shadowJar` 之类的东西来将其打包进去，这貌似破坏了共享依赖？而且也挺麻烦的。

所以我认为与其再次手动配置远程仓库信息还不如在打包时就将信息同时加进去，可能是 `resources / META-INF` 之类的文件夹？同时这应该也不会破坏目前的打包机制

**Comment by cssxsh** [comment]
maven snapshot 或者 jitpack 无法保证持久可用性的吧

**Comment by minoism** [comment]
有道理，但应该不存在也不是很需要考虑这样的问题？snapshot 确实有可能会丢失，~~但 jitpack 应该不会~~

**Comment by Karlatemp** [comment]
如果要支持直接在插件携带远程仓库的话会有以下问题

- 网络，大部分用户都没法直接访问一些远程仓库，这会造成初次启动极其缓慢甚至无法启动
- 更新，如你所说可能会有 -SNAPSHOT, 如果 plugin dev 使用了 snapshot 的话，用户可能无法及时收到更新，必须手动清除本地缓存才能完整得到最新更新.
- 可用性，目前我们已知能长期提供稳定服务并且可靠的就只有 Maven Central, 她的仓库更新的严格性保证了每个用户得到的依赖链是一样的，如果使用 sonatype snapshot 等其他仓库很有可能因为 snapshot 可动态更新导致 plugin dev 没法复现问题
- (for mamoe) gradle 插件开发困难, 最新的插件打包模式在编写时就没有看到 gradle api 提供了很友好的判断 dependency 来自哪个仓库的 api. 如果 gradle api 的确没有提供此方法的话我们就需要花费大量的时间去分析 gradle internal, 并且极其不稳定, 很有可能因为 plugin dev 的 gradle 版本和我们使用的 gradle 版本不一致就导致 console-gradle 报错

**Comment by Him188** [comment]
其实能把依赖jar和插件jar打包成zip，然后运行时解压了直接加载那些jars

**Comment by Him188** [comment]
更建议在无法保持高可用的情况下把依赖打包, 用 21 世纪的储存空间换稳定性应该是值的
