### ISSUE TITLE
MiraiConsole.createLogger 独立于 MiraiLogger.Factory 

### ISSUE THREAD

**Issue by cssxsh** [mamoe/mirai#2061]
### 问题描述

MiraiConsoleImplementationTerminal.createLogger 没有接入 MiraiLogger.Factory.create

### 复现

MiraiConsole.createLogger 固定只产生 PlatformLogger

https://github.com/mamoe/mirai/blob/167a29e0d8b20ebd7125dc0e96c4a935a0697425/mirai-console/frontend/mirai-console-terminal/src/MiraiConsoleImplementationTerminal.kt#L97-L103

### mirai-core 版本

2.11.0

### bot-protocol

ANDROID_PHONE

**Comment by Him188** [comment]
备注: 这不是 console 核心的问题, 是 terminal 的
