### ISSUE TITLE
替换 `@Volatile` `synchronized` 等 JVM 特定实现以支持多平台

### ISSUE THREAD

**Issue by Colerar** [mamoe/mirai#2062]
Related: #2048

`@Volatile` 由 Kotlin 直接映射到 JVM 中的 volatile 关键字，并由 Java Memory Model 保证可见性。在 native 也存在 volatile (如 C)，但不存在可见性语义，仅保证编译器和 CPU 不对该变量操作重排序，自然 Kotlin/Native 也无法直接粗暴映射两者。

Atomic 在 Read / Write 操作上提供同样的性能。（Kotlin 多平台 Atomic 的唯一选择 KotlinX AtomicFU 库在 JVM 上的 R/W 操作就是套了一层 `@Volatile` 封装, [source](https://github.com/Kotlin/kotlinx.atomicfu/blob/450b056efa4c8e4f922f2a3f8d1958404513b1f7/atomicfu/src/jvmMain/kotlin/kotlinx/atomicfu/AtomicFU.kt#L80-L89)）

通过委托也能完全二进制兼容先前的代码:

```kotlin
public object Clazz {
  // legacy code
  // @Volatile
  // public val foo = 1;

  public val foo by _foo

  private val _foo = atomic(1)

  fun read() {
    println(foo)
  }

  fun write() {
    foo = 123
  }
}

```

更多细节请参考 [KotlinX AtomicFU README](https://github.com/Kotlin/kotlinx.atomicfu)

----

同时，也应该将 `synchronized` 等方法替换为 coroutine 提供的 Mutex

ReentrantLock 的 Coroutine 等价实现可以参考 Kotlin Coroutines 设计者 Elizarov [给出的代码](https://elizarov.medium.com/phantom-of-the-coroutine-afc63b03a131):

```kotlin
import kotlinx.coroutines.*
import kotlinx.coroutines.sync.*
import kotlin.coroutines.*

val mutex = Mutex()

suspend fun foo() {
    mutex.withReentrantLock {
        doSomeWork()
    }
}

suspend fun doSomeWork() {
    mutex.withReentrantLock {
        println("Working!")
    }
}

suspend fun main() {
    foo()
}

suspend fun <T> Mutex.withReentrantLock(block: suspend () -> T): T {
    val key = ReentrantMutexContextKey(this)
    // call block directly when this mutex is already locked in the context
    if (coroutineContext[key] != null) return block()
    // otherwise add it to the context and lock the mutex
    return withContext(ReentrantMutexContextElement(key)) {
        withLock { block() }
    }
}

class ReentrantMutexContextElement(
    override val key: ReentrantMutexContextKey
) : CoroutineContext.Element

data class ReentrantMutexContextKey(
    val mutex: Mutex
) : CoroutineContext.Key<ReentrantMutexContextElement>
```

**Comment by Him188** [comment]
synchronized 用于非 suspend 环境，无法替换为 suspend 的 Mutex. atomicfu 似乎也有 synchronized 的 native 实现

**Comment by Colerar** [comment]
Java synchronized 应该是用 JVM monitorenter 和 moniterexit 指令实现的。如果要新增 Native Target 应该没有简单的等价非协程实现。

**Comment by LaoLittle** [comment]
> Java synchronized 应该是用 JVM monitorenter 和 moniterexit 指令实现的。如果要新增 Native Target 应该没有简单的等价非协程实现。

我觉得是不是可以用`kotlinx.atomicfu.locks`里的`synchronized`函数实现

函数定义如下
```kotlin
public actual inline fun <T> synchronized(lock: SynchronizedObject, block: () -> T): T {
    lock.lock()
    try {
        return block()
    } finally {
        lock.unlock()
    }
}
```

**Comment by Colerar** [comment]
应该可行，我看 common 包下提供了对应的构造器和加锁函数。

Edit: 由于 native 没有 JVM 帮忙优化（底层替换成自旋 偏向锁等），可能会导致性能下降。

**Comment by LaoLittle** [comment]
> Edit: 由于 native 没有 JVM 帮忙优化（底层替换成自旋 偏向锁等），可能会导致性能下降。

也是一种妥协了

Ps: 要说性能下降，K/N读取外部ByteArray是一个个复制（）

**Comment by Him188** [comment]
> atomicfu 似乎也有 synchronized 的 native 实现

我所说的就是指的 @LaoLittle 发的那个。

----

使用 synchronized 的情况都是性能不敏感的，不然会优先考虑 lock-free （如果适合）。

**Comment by AdoptOSS** [comment]
> Atomic 在 Read / Write 操作上提供同样的性能。（Kotlin 多平台 Atomic 的唯一选择 KotlinX AtomicFU 库在 JVM 上的 R/W 操作就是套了一层 `@Volatile` 封装, [source](https://github.com/Kotlin/kotlinx.atomicfu/blob/450b056efa4c8e4f922f2a3f8d1958404513b1f7/atomicfu/src/jvmMain/kotlin/kotlinx/atomicfu/AtomicFU.kt#L80-L89)）
> 
> 通过委托也能完全二进制兼容先前的代码:

由于Kotlin/kotlinx.atomicfu#186，public属性暂时不要使用委托（Kotlin Metadata 编辑错误）

**Comment by WetABQ** [comment]
使用 `currentCoroutineContext()` 而非使用 `coroutineContext`（已经被标记为 Delicate API）

```kotlin
suspend fun <T> Mutex.withReentrantLock(block: suspend () -> T): T {
    val key = ReentrantMutexContextKey(this)
    // call block directly when this mutex is already locked in the context
    if (currentCoroutineContext()[key] != null) return block() // 更换这里的实现
    // otherwise add it to the context and lock the mutex
    return withContext(ReentrantMutexContextElement(key)) {
        withLock { block() }
    }
}
```
