### ISSUE TITLE
shadowLink 打包依赖，在其他依赖也引用时无效

### ISSUE THREAD

**Issue by cssxsh** [mamoe/mirai#2070]
### 问题描述

```
    implementation("cn.hutool:hutool-extra:5.8.2")
    shadowLink("cn.hutool:hutool-core")
```
和
```
    implementation("cn.hutool:hutool-extra:5.8.2")
    implementation("cn.hutool:hutool-core:5.8.2")
    shadowLink("cn.hutool:hutool-core")
```
`cn.hutool:hutool-core` 都没有打包到 `mirai2.jar`

https://github.com/mamoe/mirai/blob/7a6c7a89c0d844ae85b7913cc24d9fe1fddd93b8/mirai-console/tools/gradle-plugin/README.md?plain=1#L65-L78

### 复现

要使 `cn.hutool:hutool-core`, 被打包，需要先 exclude 再 implementation
```
    implementation("cn.hutool:hutool-extra:5.8.2") {
        exclude("cn.hutool", "hutool-core")
    }
    implementation("cn.hutool:hutool-core:5.8.2")
    shadowLink("cn.hutool:hutool-core")
```

### mirai-core 版本

2.11.0

### bot-protocol

ANDROID_PHONE

**Comment by Karlatemp** [comment]
`gradle buildPlugin --info`
