### ISSUE TITLE
登录验证过不去

### ISSUE THREAD

**Issue by 1024191579** [mamoe/mirai#2073]
### 问题描述

![验证过不去](https://user-images.githubusercontent.com/17799883/171084582-d0132cf4-6d65-483c-b28e-3c9b0d6b98eb.png)
扫码成功后关了那个弹出长条，然后还会蹦出来。过不去

### 复现

1

### mirai-core 版本

2

### bot-protocol

ANDROID_WATCH

### 其他组件版本

1

**Comment by Him188** [comment]
https://mirai.mamoe.net/topic/223/
