### ISSUE TITLE
将 Ktor 依赖嵌入 mirai-core 并不公开

### ISSUE THREAD

**Issue by Him188** [mamoe/mirai#2084]
将会使用 Ktor 2.0, 并 shadow 进 mirai-core, 即包名会变为 `net.mamoe.mirai.internal.io.ktor`. 

所有曾经借由 mirai-core-api 获得 Ktor 依赖的用户都将需要显式定义 Ktor 依赖. 但是这将会解决版本兼容问题. 用户可以任选 Ktor 1 或者 Ktor 2.

----

备注: 还有一个目的是使用 Ktor 2.0 提供的全平台 (不包含 mingw) CIO 引擎, 以供 native 目标使用.

**Comment by Him188** [comment]
Fixed by fd67ba92044d7e21f4403afa203ebf106c47ea73

**Comment by aaacde** [comment]
嵌入之后，ktor源码不在 mirai-core-jvm-2.13.0-RC2-sources.jar 中，不方便在IDEA中查看源码与debug

**Comment by Him188** [comment]
这是没办法的
