### ISSUE TITLE
验证不通过

### ISSUE THREAD

**Issue by wangyijin209** [mamoe/mirai#2092]
### 问题描述

在本地登录机器人显示当前登录环境不安全，进行验证，也显示验证成功

![](https://wueba.coding.net/p/image/d/image/git/raw/master/20220612125400.png)

但是验证过后，还是不能正常登录

![](https://wueba.coding.net/p/image/d/image/git/raw/master/20220612125429.png)

### 复现

尝试登录了不下十次、

不能登录

### mirai-core 版本

2.8.2

### bot-protocol

ANDROID_PHONE

### 其他组件版本

xiaomingminecraft-4.8.3

**Comment by Karlatemp** [comment]
手机 QQ

**Comment by wangyijin209** [comment]
> 手机 QQ

？

**Comment by Karlatemp** [comment]
用手机 QQ 打开验证url

**Comment by wangyijin209** [comment]
> 用手机 QQ 打开验证url

试过了，还是不行

**Comment by wangyijin209** [comment]
开启设备验证锁就行了
