### ISSUE TITLE
Less `!!`

### ISSUE THREAD

**Issue by ice1000** [mamoe/mirai#21]
https://github.com/mamoe/mirai/blob/8948eb204307d361566626614817525e515eed9c/mirai-core/src/commonMain/kotlin/net.mamoe.mirai/Bot.kt#L187-L190

You can use `_qqs[id] ?: qqsLock.withLock { _qqs.getOrPut(id) { QQ(bot, id, coroutineContext) }  }`

**Comment by Him188** [comment]
Thank you.
I'm planning to replace the ContactList with a lock-free one, because `suspend get` shouldn't be there and currently the iterating is pretty unsafe

**Comment by ice1000** [comment]
Ok. I'm just talking about some purely syntactical improvements

**Comment by Him188** [comment]
> https://github.com/mamoe/mirai/blob/8948eb204307d361566626614817525e515eed9c/mirai-core/src/commonMain/kotlin/net.mamoe.mirai/Bot.kt#L187-L190
> 
> You can use `_qqs[id] ?: qqsLock.withLock { _qqs.getOrPut(id) { QQ(bot, id, coroutineContext) } }`

`withLock` is suspend, which is expensive(Continuation creation), and this `getQQ` function is frequently used.

I was trying to reduce that cost.

LockFreeLinkedList is under development. coz I haven't found any libraries providing that

**Comment by ice1000** [comment]
`?:` is lazily evaluated.

See https://pl.kotl.in/M2RGjwvOp

**Comment by ice1000** [comment]
```kotlin
fun main() {
    1 ?: println("Hello, world!!!")
    println("Done.")
}
```

prints only `Done.`

**Comment by Him188** [comment]
Ohhh, I just missed ?: 😂 Thank you

**Comment by ice1000** [comment]
:trollface:

**Comment by Him188** [comment]
ContactList is now delegating a LockFreeLinkedList in 0.8.0
