### ISSUE TITLE
支持上传有时效的文件

### ISSUE THREAD

**Issue by NoMathExpectation** [mamoe/mirai#2101]
在qq群文件里看到了一些有失效时间的文件，但是在使用代码上传的时候并没有看到有可以附加失效时间的方法，希望可以添加相关的方法

**Comment by mckuhei** [comment]
有失效时间的文件就是文件过大或者剩余空间不足才会这样，最多说给个api检查失效时间

**Comment by Him188** [comment]
在官方客户端上传也确实不知道如何上传有/无时效文件，是直接上传没有给选项的
