### ISSUE TITLE
更新 MacOS 版本

### ISSUE THREAD

**Issue by lz1998** [mamoe/mirai#2106]
frida handler：print *NSString
```javascript
	  var data = new ObjC.Object(args[2]);
	  log(data);
```

使用 frida 进行 Hook
```bash
frida-trace -m "-[QRCodeTlv_22 *]" QQ
```

版本：[version.rs](https://github.com/lz1998/ricq/blob/a1215097b818fd276fb7b7da72d85827ba824ab2/ricq-core/src/protocol/version.rs#L97)

**Comment by Him188** [comment]
旧版本有遇到什么问题吗

**Comment by lz1998** [comment]
> 旧版本有遇到什么问题吗

旧版本没法扫码登录（apk_sign有问题）

**Comment by AdoptOSS** [comment]
登录全新device info的新账号，经常会出现类似“错误，请更新QQ版本”的情况
似乎 `ANDROID_PAD` / `IPAD` 也存在同样问题

但 `ANDROID_PHONE` 很正常
