### ISSUE TITLE
修改群名片事件没有触发

### ISSUE THREAD

**Issue by cxy654849388** [mamoe/mirai#211]
环境：win10、mirai-console-wrapper-0.2.0-all.jar、Pure
修改群成员名片，在cmd界面没有看到群成员修改名片事件

**Comment by cxy654849388** [comment]
> bot主动还是被动？

刚试了一下，主动的也不行

**Comment by Him188** [comment]
修改时服务器没有发送事件, 故 mirai 也无法触发事件.
主动修改时仅新名片和旧名片不同时会触发事件.
在群员发送消息时将会检查名片并触发名片修改事件.

**Comment by cxy654849388** [comment]
6
