### ISSUE TITLE
将Mirai-core作为依赖开发后事件监听无效

### ISSUE THREAD

**Issue by WutzuBert** [mamoe/mirai#2111]
### 问题描述

Mirai-core作为依赖引入应用程序后，事件监听失效

### 复现

我在一个Minecraft Bukkit插件中想要引用Mirai-core实现Bot功能
Bukkit加载插件后，Bot登录流程都没有问题
但是当我向Bot发送消息时，我没有得到Bot的回复
GlobalEventChannel和Bot.getEventChannel都尝试了，并且我反复确认了代码没有问题

### mirai-core 版本

2.11.1

### bot-protocol

ANDROID_PHONE

### 其他组件版本

Bukkit 1.12

**Comment by Karlatemp** [comment]
您检查了您的环境的类搜索路径了吗，您确定运行 bot 的 core 的 ClassLoader 与您尝试访问的类(`GlobalEventChannel`, `BotEvent` 等) 的 ClassLoader 是同一个 ClassLoader 吗

**Comment by Karlatemp** [comment]
我们建议您通过以下方式检查
```java
public static void dumpClassInfo(Class<?> klass) {
    var stdout = System.out;
    synchronized (stdout) {
        stdout.append("Class: ").println(klass);
        var cl = klass.getClassLoader();
        stdout.append("  `- ClassLoader: ").append(cl).append(" <").append(System.identityHashCode(cl)).println(">");
        stdout.append("  `- Declared module: ").println(klass.getModule());
   }
}
```

**Comment by WutzuBert** [comment]
> 我们建议您通过以下方式检查
> 
> ```java
> public static void dumpClassInfo(Class<?> klass) {
>     var stdout = System.out;
>     synchronized (stdout) {
>         stdout.append("Class: ").println(klass);
>         var cl = klass.getClassLoader();
>         stdout.append("  `- ClassLoader: ").append(cl).append(" <").append(System.identityHashCode(cl)).println(">");
>         stdout.append("  `- Declared module: ").println(klass.getModule());
>    }
> }
> ```

我想我已经找到问题来源了
检查发现ClassLoader没有问题，但是我忽略了shadowJar编译时发生的编码问题，应该是编码不一致导致的不能正确识别消息
