### ISSUE TITLE
账户安全认证功能失效

### ISSUE THREAD

**Issue by Maplefsnow** [mamoe/mirai#2118]
### 问题描述

登录 QQ 账户时弹出 Mirai UnsafeDeviceLoginVerify 窗口提示进行设备锁验证：

![image](https://user-images.githubusercontent.com/45029436/175761672-3fc1138f-3634-4d0c-8663-af34675f7554.png)

按照操作验证成功后关闭了此对话框，对话框会再次弹出提示验证，查阅QQ安全中心得知并未进行任何登录操作。并且该对话框关闭后会反复弹出，只有结束进程才能彻底关闭。

如果此为 bug 请尽快修复，如果不是请告知我解决方案，谢谢！

### 复现

登录 QQ 账户，并触发 Mirai UnsafeDeviceLoginVerify 窗口提示，按照要求进行验证并关闭此窗口。

### mirai-core 版本

2.11.1

### bot-protocol

ANDROID_PHONE

**Comment by Maplefsnow** [comment]
或为网络波动原因所致，此问题已解决

**Comment by yuanbolin** [comment]
我也有此问题,必现
