### ISSUE TITLE
文档的两处错误

### ISSUE THREAD

**Issue by Keyezi** [mamoe/mirai#2119]
### 问题描述

链接定向出现错误
https://docs.mirai.mamoe.net/console/Commands.html#%E5%8F%82%E6%95%B0%E6%99%BA%E8%83%BD%E8%A7%A3%E6%9E%90
![image](https://user-images.githubusercontent.com/38462592/175794333-2b72a02b-8693-41e9-bafd-a3426eb6dc31.png)
示例参数错误
https://docs.mirai.mamoe.net/console/Commands.html#%E8%87%AA%E5%AE%9A%E4%B9%89%E6%99%BA%E8%83%BD%E8%A7%A3%E6%9E%90
![image](https://user-images.githubusercontent.com/38462592/175794349-9c468796-3ed8-4002-98ab-8bd663c3aa76.png)

### 复现

0

### mirai-core 版本

dev分支

### bot-protocol

ANDROID_PHONE

**Comment by Him188** [comment]
第一个问题, MD 文件没问题, 应该是部署问题 @Karlatemp

**Comment by Karlatemp** [comment]
第一个我很早前就修了

**Comment by Him188** [comment]
> 

它2022年08月15日16:56:30是坏的

**Comment by Him188** [comment]
@Karlatemp 说第一个问题是要自行清除浏览器缓存
