### ISSUE TITLE
无法登录，滑块验证助手报错“Oops! This project isn't running.”

### ISSUE THREAD

**Issue by dragon0629** [mamoe/mirai#2120]
### 问题描述

无法完成初次登录，点login qq password 后出现
已测试在2.9 2.11 均一样
[http://106.75.240.93:8080/loginerror.png](http://106.75.240.93:8080/loginerror.png)

小框里的具体内容文字如下：
io.ktor.client.features.ClientRequestException: Client request(https://txhelper.glitch.me/template/wireless_mqq_captcha.html?style=simple&aid=16&uin=2362539360&sid=2177186105877145925&cap_cd=VQMVb9myycjsYv7qf9vaeuiu9o-dis0dlsL14TDFwswKkRdh7UcROA%2A%2A&clientype=1&apptype=2) invalid: 403 . Text: "<!DOCTYPE html> <html lang="en">   <head>     <meta charset="utf-8">     <title>Oops! This project isn't running.</title>     <meta name="viewport" content="initial-scale=1, width=device-width">     <link rel="stylesheet" type="text/css" href="https://cloud.webtype.com/css/3a8e55c6-b1f3-4659-99eb-125ae72bd084.css">     <style>       * {         box-sizing: border-box;       }        html, body {         margin: 0;         padding: 0;         font-family: "Benton Sans", Helvetica, Sans-serif;         font-size: 16px;         line-height: 160%;         width: 100%;         height: 100%;       }        .container {         width: 100%;         height: 100%;         display: flex;         padding: 100px;       }        .info {         max-width: 370px;         z-index: 1;         position: relative;       }        h1 {         margin: 0;         font-size: 40px;         line-height: 130%;         font-weight: bold;       }        a {         color: #000;       }        .decorative-image {         position: absolute;         right: 80px;         bottom: 80px;         width: 50vw;         max-width: 1000px;       }        @media(max-width: 620px) {         .container {           padding: 40px;         }          .decorative-image {           right: 20px;           bottom: 20px;           width: 80vw;         }       }     </style>   </head>   <body>     <div class="container">       <div class="info">         <h1>Oops! This project isn't running.</h1>         <p>           If this is your project, check out the <a href="//glitch.com/edit/#!/">Glitch Editor</a>,           or head over to the Help Center to <a href="https://glitch.com/help/kb/article/72">learn more</a>.         </p>       </div>       <img src="https://cdn.glitch.com/d7f4f279-e13b-4330-8422-00b2d9211424%2FGlitch-Error-Rainbow-Mug-hires.png?v=1595481653593" class="decorative-image">     </div>   </body> </html> "

### 复现

尝试登录新号即出

### mirai-core 版本

2.11.0

### bot-protocol

ANDROID_PHONE

### 系统日志

```text
无
```

### 网络日志

```text
无
```

### 补充信息

现在官方比较推荐的新号登录是哪个方案 0_0

**Comment by wyapx** [comment]
请将输入框内的URL复制到TxCaptchaHelpers里面进行验证

~~有人把后端玩炸了，我不说是谁~~

**Comment by dragon0629** [comment]
啊这……笑死。这个还有后端验证的啊，我以为是本地模拟。

**Comment by StageGuard** [comment]
这个..你应该去滑块验证助手的项目反馈

**Comment by dragon0629** [comment]
> 这个..你应该去滑块验证助手的项目反馈

我哪想得到是滑块验证助手的问题
因为是mirai自己输入login qq password 之后拉起来的报错
都还没到手机上滑块验证助手那一步呢。
233，顺带现在mirai官方里推荐应该是怎么样完成初次登录滑块验证呢？

看了好多文档，什么办法五花八门的都有，但好像都是自己摸索的。

官方这边内置的打开貌似就这一个滑块验证助手啊，因为初次点击登录必然会弹出来这个东东。

**Comment by Him188** [comment]
@mzdluo123 已经修复了吗

**Comment by mzdluo123** [comment]
> @mzdluo123 已经修复了吗

已修复
