### ISSUE TITLE
MessageSyncEvent 的 source 的 target 为机器人，而不是 实际上 的消息发送对象

### ISSUE THREAD

**Issue by cssxsh** [mamoe/mirai#2122]
### 问题描述

MessageSyncEvent 的 source  中
其 target 固定是 bot , 应该是群/好友或其他消息接收者

原来的消息 接收方（群/好友）在 source 丢失了

### 复现

```
public object MiraiRecorder : SimpleListenerHost() {
    fun MessageSyncEvent.record() {
        check(subject.id == source.targetId)
    }
}
```

### mirai-core 版本

2.11.1

### bot-protocol

ANDROID_PHONE

**Comment by Karlatemp** [comment]
https://github.com/mamoe/mirai/blob/bec756e0bfec327304b2551475e9d8853327f744/mirai-core-api/src/commonMain/kotlin/message/data/OnlineMessageSource.kt#L157-L170

很难确定应该怎么修改 target

**Comment by sandtechnology** [comment]
> https://github.com/mamoe/mirai/blob/bec756e0bfec327304b2551475e9d8853327f744/mirai-core-api/src/commonMain/kotlin/message/data/OnlineMessageSource.kt#L157-L170
> 
> 很难确定应该怎么修改 target

这指的应该是MessageChain里面的MessageSource的targetId需要修正
在同步信息时，服务器的~~发送者~~目标当然是Bot本身，而这对使用者来说应该是不合逻辑的
应该可以通过在toMessageChain时传入contact信息修正

**Comment by Karlatemp** [comment]
我意思是, 这部分的 api 可能需要重新设计, 或者将其对接到 Outgoing (但是这样就不符合 doc 的描述了)
我比较纠结最终修改应该是什么样的


> 应该可以通过在toMessageChain时传入contact信息修正

在不修改公开 api 的情况下无法修正, 因为被写死了 `val targeet: Bot` 了

**Comment by sandtechnology** [comment]
确实 这应该对接到 Outgoing ，属于 breaking changes
不知道是哪部分不符合 doc 的描述，我看了看代码内的doc 修改为outgoing应该才是符合描述的：
```
/**
     * 消息源. 来自 [message]. 相当于对 [message] 以 [MessageSource] 参数调用 [MessageChain.get].
     */
    public val source: OnlineMessageSource.Incoming get() = message.source as OnlineMessageSource.Incoming
```
但是这里的source也是Incoming的，应该把 MessageSyncEvent 直接分离？

**Comment by Karlatemp** [comment]
https://github.com/mamoe/mirai/blob/bec756e0bfec327304b2551475e9d8853327f744/mirai-core-api/src/commonMain/kotlin/message/data/OnlineMessageSource.kt#L36-L38

https://github.com/mamoe/mirai/blob/bec756e0bfec327304b2551475e9d8853327f744/mirai-core-api/src/commonMain/kotlin/message/data/OnlineMessageSource.kt#L84-L87

https://github.com/mamoe/mirai/blob/bec756e0bfec327304b2551475e9d8853327f744/mirai-core-api/src/commonMain/kotlin/message/data/OnlineMessageSource.kt#L148-L151

**Comment by sandtechnology** [comment]
我有一个想法 在 Incoming 下造一个 FromOtherClient 然后下面 有 InFriend InStranger InGroup
这样是不是就解决问题了（

**Comment by sandtechnology** [comment]
当然 这需要修改公开API 但是也是不可避免的

**Comment by Him188** [comment]
可以改返回值类型, 用 Kotlin 魔法提供 ABI 兼容:
```kotlin
@JvmName("getTarget") 
@Deprecated("For ABI compatibility", level = HIDDEN)
public fun getTargetLegacy(): Bot = ssender.bot
```

这只会导致新的源码编译失败, 而它必须要精确使用 `FromFriend` 这个类型才会, 所以影响比较小
