### ISSUE TITLE
图片代码字符串无法使用 deserializeMiraiCode() 使之反序列化

### ISSUE THREAD

**Issue by zhaodice** [mamoe/mirai#2135]
### 问题描述

形如
`[mirai:image:{16120387-4BB4-1E28-C561-53A64AF0C298}.jpg, width=2480, height=3507, size=573041, type=UNKNOWN, isEmoji=false]`
这种格式的mirai码，无法被反序列化

### 复现

mirai图片码无法使用deserializeMiraiCode()得到实例对象
`"文字文字文字文字[mirai:image:{16120387-4BB4-1E28-C561-53A64AF0C298}.jpg, width=2480, height=3507, size=573041, type=UNKNOWN, isEmoji=false]".deserializeMiraiCode()`
### mirai-core 版本

1.12.0

### bot-protocol

ANDROID_PHONE

**Comment by Him188** [comment]
这不是mirai码，mirai码需要通过 serializeToMiraiCode 获得

**Comment by zhaodice** [comment]
> serializeToMiraiCode

是哦，我直接toString()了。。待我serializeToMiraiCode 看看，主要是以前的版本都可以没注意到

**Comment by zhaodice** [comment]
问题解决...一两个月没搞mirai，和失忆了一样
