### ISSUE TITLE
基于mirai-core 2.12.0开发时监听事件出现问题

### ISSUE THREAD

**Issue by DreamVoid** [mamoe/mirai#2138]
### 问题描述

使用mirai-core 2.12.0开发时，监听事件时出现`Could not find an implementation for service class net.mamoe.mirai.event.InternalGlobalEventChannelProvider`问题，详细报错如下：
```
java.util.NoSuchElementException: Could not find an implementation for service class net.mamoe.mirai.event.InternalGlobalEventChannelProvider
        at net.mamoe.mirai.utils.ActualsKt.loadService(Actuals.kt:40) ~[?:?]
        at net.mamoe.mirai.utils.ActualsKt.loadService$default(Actuals.kt:35) ~[?:?]
        at net.mamoe.mirai.event.GlobalEventChannel$instance$2.invoke(GlobalEventChannel.kt:31) ~[?:?]
        at net.mamoe.mirai.event.GlobalEventChannel$instance$2.invoke(GlobalEventChannel.kt:30) ~[?:?]
        at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74) ~[?:?]
        at net.mamoe.mirai.event.GlobalEventChannel.getInstance(GlobalEventChannel.kt:30) ~[?:?]
        at net.mamoe.mirai.event.GlobalEventChannel.createListener(GlobalEventChannel.kt:44) ~[?:?]
        at net.mamoe.mirai.event.EventChannel.subscribeAlways(EventChannel.kt:630) ~[?:?]
        at net.mamoe.mirai.event.EventChannel.subscribeAlways$default(EventChannel.kt:622) ~[?:?]
        at net.mamoe.mirai.event.EventChannel.subscribeAlways(EventChannel.kt) ~[?:?]
        at me.dreamvoid.miraimc.bukkit.MiraiEvent.startListenEvent(MiraiEvent.java:103) ~[?:?]
        （省略别的不重要的trace）
```

### 复现

Java直接调用`GlobalEventChannel.INSTANCE.subscribeAlways(BotOnlineEvent.class, event -> {...} );`（BotOnlineEvent实际上可以是任何事件

### mirai-core 版本

2.12.0

### bot-protocol

ANDROID_PHONE

### 补充信息

出问题的源码：https://github.com/DreamVoid/MiraiMC/blob/6b2dcead398d419b33a3c10d024e2a6744e29c39/MiraiMC-Bukkit/src/main/java/me/dreamvoid/miraimc/bukkit/MiraiEvent.java#L92
相同的代码和环境换成2.11.1无此问题。

**Comment by Karlatemp** [comment]
[Search: Thread Context ClassLoader](https://www.google.com/search?q=thread+context+classloader)

**Comment by William-Shi** [comment]
我刚刚注意到 DreamVoid 在 MCBBS 发帖询问了这一问题。（https://www.mcbbs.net/thread-1360793-1-1.html）

我想起当年 Karlatemp 大佬解答我有关“找不到 Nashorn 引擎相关 Service Provider 问题”时的耐心仔细。她一步步地启沃于我，为我一环环分析相关方法的调用链条，替我一句句解释类加载器的联系和区别。为了证明两年前的我确实理解了这个问题，现在我尝试解答 DreamVoid 的相关问题，请您赐鑑。

首先，众所周知的是 Bukkit 有一个所谓的 Service Provider 系统，最为常见的用处，就是通过 Vault 插件来进行经济相关操作。比如 Vault 插件规定好一个经济相关的 Service 并注册进系统里，它只是接口而没有实际功能，各种经济插件去实现具体操作，把自己对 Vault 规定好的 Service 的实现（Service Provider）注册进系统里。这样在需要操作经济时，不需要直接把各种不同的经济插件本身当成依赖，只需要有 Vault 作为依赖，把 Vault 的接口提供给 Bukkit，让 Bukkit 查找其可用的实现类，这样就可以避免与经济插件打交道。所以服主只装 Vault 不装经济插件是行不通的。而 Bukkit 这一整套系统是模仿了 JDK 标准里的 Service 相关类。JDK 当中根据某个 Service 查找 Service Provider 的操作需要用到类加载器。按：

> Service providers are located in all named modules of the class loader or to any class loader reachable via parent delegation.

虽然我不会 Kotlin，但是我勉强能看懂 Actuals 中所写的这一方法调用了  java.util.ServiceLoader 的 load 方法，且只传入一个参数。因为在 java.util.ServiceLoader 中有：
```
    @CallerSensitive
    public static <S> ServiceLoader<S> load(Class<S> service) {
        ClassLoader cl = Thread.currentThread().getContextClassLoader();
        return new ServiceLoader<>(Reflection.getCallerClass(), service, cl);
    }
```
因此在调用该方法时自动获取了线程的 ContextClassLoader 去查找类。然而为了插件使用的需要，Bukkit 的 PluginClassLoader 并没有采用双亲委派机制。而这个 cl 里（指 AppClassLoader ）没有办法查找到 Mirai 的相关 Service Provider ，这些 Service Provider 是由插件的 PluginClassLoader 加载的。因此最后就查找不到相关实现类。

因此需要替换 ContextClassLoader 为插件的 PluginClassLoader。Karlatemp 在 2020.8.10 曾经御赐宸翰写下代码解决类似问题，按：

> 
>        // 就像下面这样
>        /*
>        ClassLoader old = Thread.currentThread().getContextClassLoader();
>        try {
>            Thread.currentThread().setContextClassLoader(Bootstrap.class.getClassLoader());
>            // Service loading.
>        } finally {
>            Thread.currentThread().setContextClassLoader(old);
>        }
>        */

只需稍加修订即可使用。此处假定你能解决。

上请大佬们雅正。诚惶诚恐，不知所言。顿首顿首。

**Comment by DreamVoid** [comment]
留个笔记，今天才算真正弄好了这玩意，Bukkit给的PluginClassLoader不能直接拿来加载，要getParent一下才行。

后记：思路错了，不是用parent，而是我也不知道Bukkit抽的什么风居然不把PluginClassLoader用到底
