### ISSUE TITLE
支持关闭群视频/QQ电话/一起xxx

### ISSUE THREAD

**Issue by sandtechnology** [mamoe/mirai#214]
在部分群宵禁时需要

**Comment by copydog** [comment]
欢迎PR

**Comment by Him188** [comment]
这些功能不能关吧，没找到关闭的入口

**Comment by sandtechnology** [comment]
群视频在群设置里面能关
QQ电话和一起xxx是要进行的时候管理员才能关闭（手机QQ）

Get Outlook for Android<https://aka.ms/ghei36>
________________________________

**Comment by Him188** [comment]
用例太少，不值得研究（实际上现在有的坦白说等开关都是因为其与全体禁言的 flag 相邻才做，且因 #286 正考虑取消支持）。
