### ISSUE TITLE
springboot(java)项目整合2.12.0版本,主动调用bot.close()方法会抛出DurationUnit找不到类加载类失败ERROR

### ISSUE THREAD

**Issue by h906478231** [mamoe/mirai#2150]
### 问题描述

2.12.0版本后在springboot(java)项目里主动调用bot.close()方法会抛出DurationUnit找不到类加载类失败ERROR
2.9.0版本则不会

### 复现

1.当机器人在线,通过Bot.getInstance()拿到机器人实例,后主动调用Bot.close()方法,就会抛出类加载找不到DurationUnit类的异常

### mirai-core 版本

2.12.0

### bot-protocol

ANDROID_PAD

**Comment by Karlatemp** [comment]
检查 kotlin 版本是否低于 mirai 所使用的版本

**Comment by Karlatemp** [comment]
Long time no reply
