### ISSUE TITLE
机器人突然无法发送消息，报错中显示不是插件问题

### ISSUE THREAD

**Issue by Enron233** [mamoe/mirai#2153]
### 问题描述

# 就在刚刚
发现机器人主动发消息功能突然失效，返回错误，报错截图如下：
<img src="https://s2.loli.net/2022/07/16/K8WYIypb5eL9mZz.png">

### 复现

用任意命令让机器人发送消息(调用SendMessage()方法)就会发生本问题

### mirai-core 版本

2.11.0

### bot-protocol

ANDROID_PHONE

**Comment by 4o4E** [comment]
你有试过切换账号吗？

**Comment by Enron233** [comment]
> 你有试过切换账号吗？

尝试过了，现在我这切换不了账号，因为无论切换哪个账号，都会卡在设备验证那一步，即使打开链接，扫码，授权，成功，关闭后仍然会再弹出验证（显示验证成功但不起作用）

**Comment by 4o4E** [comment]
> > 你有试过切换账号吗？
> 
> 尝试过了，现在我这切换不了账号，因为无论切换哪个账号，都会卡在设备验证那一步，即使打开链接，扫码，授权，成功，关闭后仍然会再弹出验证（显示验证成功但不起作用）

有没有尝试过修改device.json

**Comment by Enron233** [comment]
> > > 你有试过切换账号吗？
> > 
> > 
> > 尝试过了，现在我这切换不了账号，因为无论切换哪个账号，都会卡在设备验证那一步，即使打开链接，扫码，授权，成功，关闭后仍然会再弹出验证（显示验证成功但不起作用）
> 
> 有没有尝试过修改device.json

刚刚尝试了一下（也尝试过删除重新生成），问题仍然存在，就是进行账户安全验证这里，已经验证成功了，不起作用，一直会弹这个验证窗口
<img src="https://s2.loli.net/2022/07/16/KmOoS1zYexZkpAN.jpg">
<img src="https://s2.loli.net/2022/07/16/Xwnhmlv5x2BPCzY.jpg">

**Comment by 4o4E** [comment]
> > > > 你有试过切换账号吗？
> > > 
> > > 
> > > 尝试过了，现在我这切换不了账号，因为无论切换哪个账号，都会卡在设备验证那一步，即使打开链接，扫码，授权，成功，关闭后仍然会再弹出验证（显示验证成功但不起作用）
> > 
> > 
> > 有没有尝试过修改device.json
> 
> 刚刚尝试了一下（也尝试过删除重新生成），问题仍然存在，就是进行账户安全验证这里，已经验证成功了，不起作用，一直会弹这个验证窗口 ![](https://camo.githubusercontent.com/2270677b213f26e4c2b88d39a805f7781a2dc83f24598e3e29c78863b21f0cfb/68747470733a2f2f73322e6c6f6c692e6e65742f323032322f30372f31362f4b6d4f6f53317a5965785a6b70414e2e6a7067) ![](https://camo.githubusercontent.com/763b98f9a525e073fd27cd6e34cec585097622a3ca22d80c27ae5581ae7519ed/68747470733a2f2f73322e6c6f6c692e6e65742f323032322f30372f31362f58776e686d6c763578324250437a592e6a7067)

试试这个 https://github.com/cssxsh/mirai-device-generator

**Comment by 4o4E** [comment]
另外可以尝试换个ip，比如用手机热点

**Comment by Enron233** [comment]
> 另外可以尝试换个ip，比如用手机热点

机器人一开始挂在服务器上，问题发生后我就本地调试了，但是不奏效，我刚才又试了一下，还是不行，还是会卡在账户安全验证那一步骤，也许是我请求太频繁了

**Comment by 4o4E** [comment]
我这儿16个号，没有任何问题，多半是你那儿风控了

**Comment by Enron233** [comment]
> 我这儿16个号，没有任何问题，多半是你哪儿风控了

应该是， 我应该采取点啥措施呢？ 等明天或者后天再试试嘛？？

我去 16个号，厉害啊， 怎么避免的被风控吖

**Comment by 4o4E** [comment]
> > 我这儿16个号，没有任何问题，多半是你哪儿风控了
> 
> 应该是， 我应该采取点啥措施呢？ 等明天或者后天再试试嘛？？
> 
> 我去 16个号，厉害啊， 怎么避免的被风控吖

群友贡献的，防止风控就是文字都转图片

**Comment by mzdluo123** [comment]
似乎是一样的问题

https://github.com/mamoe/mirai/issues/2127

**Comment by Enron233** [comment]
> 似乎是一样的问题
> 
> #2127

对对对对对对对对对对对对对对！！！我也是被冻结一次后出现的这个问题

**Comment by Enron233** [comment]
> 似乎是一样的问题
> 
> #2127

感觉我这个成了那个的升级版，我现在框架里登不进QQ了，会一直卡在账户安全认证😭
