### ISSUE TITLE
使用buildPlugin打包插件无法通过反射扫描到包

### ISSUE THREAD

**Issue by xiaoyv404** [mamoe/mirai#2155]
### 问题描述

如果我使用新版的打包Task(buildPlugin)打包我的插件的话，就无法通过org.reflections这个库扫描到我的包，代码如下

```
        val f = Reflections("com.xiaoyv404.mirai.app") //这个是那个库的扫描方法，会发现f这个变量是空的
        val set: Set<Class<*>> = f.getTypesAnnotatedWith(App::class.java)
        set.forEach {
            val bean = it.getDeclaredConstructor().newInstance()
            NfApplicationManager.appInitialization(bean as NfApp)
        }
```

如果是通过旧版打包Task(buildPluginLegacy)就可以正常扫描到我的包
附件:
[buildPlugin](https://pan.chs.pub/s/7VC1)
[buildPluginLegacy](https://pan.chs.pub/s/AmSY)
[代码地址](https://github.com/xiaoyv404/mirai-comprehensivePlugin)
[反射代码具体位置](https://github.com/xiaoyv404/mirai-comprehensivePlugin/blob/main/src/main/kotlin/com/xiaoyv404/mirai/PluginMain.kt)
[反射需要获取代码位置](https://github.com/xiaoyv404/mirai-comprehensivePlugin/tree/main/src/main/kotlin/com/xiaoyv404/mirai/app)
[注解](https://github.com/xiaoyv404/mirai-comprehensivePlugin/blob/main/src/main/kotlin/com/xiaoyv404/mirai/core/App.kt)

### 复现

1. 使用org.reflections库进行扫描
2. 使用buildPluginLegacy打包插件

### mirai-core 版本

2.12.0

### bot-protocol

ANDROID_PAD

### 系统日志

```text
2022-07-18 10:32:24 I/stdout: 10:32:24.188 [main] INFO org.reflections.Reflections - Reflections took 67 ms to scan 93 urls, producing 0 keys and 0 values
```

**Comment by Karlatemp** [comment]
这种问题，我们需要的是底层实现代码，而不是这种经过封装的代码
我们没有额外的时间可以浪费在研究一个未知的第三方库中
你需要提供的是如何使用 jdk 的方法复现这个问题, 而不是让我们自己分析这个库干了什么

**Comment by xiaoyv404** [comment]
好的，我将尝试使用jdk复现此问题

**Comment by xiaoyv404** [comment]
折腾半天，哈哈不管啦又不是不能用（逃

**Comment by xiaoyv404** [comment]
这边推荐直接通过PluginMain.jvmPluginClasspath.pluginFile获取到plugin的.jar然后通过读.jar的方式获取
