### ISSUE TITLE
求大佬告知如何发送卡片消息

### ISSUE THREAD

**Issue by devzwy** [mamoe/mirai#2156]
感谢开源大佬们，请问Pc端也显示为白底卡片的那种消息怎么发送啊，没有看到相关文档。

**Comment by Nambers** [comment]
应该是lightApp或者ServiceMessage, 你可以输出接收到的mirai code 来确定并构造

**Comment by dingpanbao** [comment]
如果成功了能否贴下主要代码，我前面也按日志打印的构造小程序消息但是发送不成功

**Comment by Nambers** [comment]
> 如果成功了能否贴下主要代码，我前面也按日志打印的构造小程序消息但是发送不成功

MiraiCode:
```
[mirai:service:1,<?xml version="1.0" encoding="utf-8"?><msg templateID="12345" action="web" brief="简介 没点进来看见的样子" serviceID="1" url="目标url"><item layout="2"><picture cover="图标地址"/><title>标题</title><summary>描述文字</summary></item><source/></msg>]
```
然后
```
MiraiCode.deserializeMiraiCode(
```

**Comment by devzwy** [comment]
> > 如果成功了能否贴下主要代码，我前面也按日志打印的构造小程序消息但是发送不成功
> 
> MiraiCode:
> 
> ```
> [mirai:service:1,<?xml version="1.0" encoding="utf-8"?><msg templateID="12345" action="web" brief="简介 没点进来看见的样子" serviceID="1" url="目标url"><item layout="2"><picture cover="图标地址"/><title>标题</title><summary>描述文字</summary></item><source/></msg>]
> ```
> 
> 然后
> 
> ```
> MiraiCode.deserializeMiraiCode(
> ```

非常感谢，我试试
