### ISSUE TITLE
请问出现这种问题如何解决

### ISSUE THREAD

**Issue by smilecat2788** [mamoe/mirai#2158]
![屏幕截图 2022-07-20 002536](https://user-images.githubusercontent.com/109615952/179801386-a72cceb4-7cde-4187-ba30-83603a722481.png)
不管是手机端，windows，ubuntu上都是如此

**Comment by Karlatemp** [comment]
1. 确定出现提示前的滑块验证是在手机通过的
2. 确定解决滑块的手机和bot位于同一局域网内

**Comment by smilecat2788** [comment]
那如果是腾讯云的轻量服务器，无法在同一局域网应该怎么办呢

**Comment by Him188** [comment]
> 那如果是腾讯云的轻量服务器，无法在同一局域网应该怎么办呢

在本地登录，登录成功后把 device.json 复制上去

**Comment by WiseClock** [comment]
同出现这个问题 已经用同一个device.json运行快两年了突然出现这个问题 滑块可以过 后面设备锁/非常用地区登入那个扫码就一直循环……

**Comment by QwindF** [comment]
在自己的电脑上，先用手机扫码登入正常的机器人号，然后关掉。再在电脑上启动mcl，登入一下，应该不会出现这个问题，然后再把本机登入成功的 device.json 文件替换掉服务器上的文件。

**Comment by WiseClock** [comment]
> 在自己的电脑上，先用手机扫码登入正常的机器人号，然后关掉。再在电脑上启动mcl，登入一下，应该不会出现这个问题，然后再把本机登入成功的 device.json 文件替换掉服务器上的文件。

成功了！先开PCQQ 用手机扫码登入 然后开Mirai 甚至没弹验证码直接登入了。感谢！

**Comment by WiseClock** [comment]
结果今天又出现这个问题了……上述方法也不好使了😥

**Comment by QwindF** [comment]
请再仔细描述一下：在服务器上登入遇到什么问题，在本地登入又是什么问题。一般用手机扫描之后就没这个问题了。

**Comment by Onmiora** [comment]
> 

你其实可以试试搭建PPTP，间接性达成本机验证

**Comment by Him188** [comment]
#717 2.14 计划支持这个
