### ISSUE TITLE
mirai 默认的 maven 镜像库 应该更改了

### ISSUE THREAD

**Issue by cssxsh** [mamoe/mirai#2184]
### 问题描述

mirai 默认的 maven 镜像库 是不是该换一下了
https://maven.aliyun.com/repository/public 是 central仓和jcenter仓的聚合仓
jcenter 都已经没了好久了
直接 用 https://maven.aliyun.com/repository/central 更好吧

而且 https://maven.aliyun.com/repository/public 有时候 同步还会出问题（同步不完整缺文件，导致依赖拉取有问题）
同步速度也比比 https://maven.aliyun.com/repository/central 慢好多

### 复现

https://github.com/cssxsh/mirai-tts-plugin/issues/2

### mirai-core 版本

2.12.1

### bot-protocol

ANDROID_PHONE

**Comment by bin-tenkuu** [comment]
原来是仓库本身就有问题吗，我还以为是我的服务器连不上阿里云了，然后就换到中央仓库去了

**Comment by ConstantineQAQ** [comment]
怎么更改默认的镜像库啊，我找半天没找到配置文件

**Comment by bin-tenkuu** [comment]
> 怎么更改默认的镜像库啊，我找半天没找到配置文件

https://docs.mirai.mamoe.net/ConsoleTerminal.html#%E8%BF%9C%E7%A8%8B%E4%BB%93%E5%BA%93

**Comment by ConstantineQAQ** [comment]
> > 怎么更改默认的镜像库啊，我找半天没找到配置文件
> 
> https://docs.mirai.mamoe.net/ConsoleTerminal.html#%E8%BF%9C%E7%A8%8B%E4%BB%93%E5%BA%93

我还是没找到PluginDependencies.yml这个配置文件

**Comment by cssxsh** [comment]
> > > 怎么更改默认的镜像库啊，我找半天没找到配置文件
> > 
> > 
> > https://docs.mirai.mamoe.net/ConsoleTerminal.html#%E8%BF%9C%E7%A8%8B%E4%BB%93%E5%BA%93
> 
 > 我还是没找到PluginDependencies.yml这个配置文件 

这是 mirai-console 2.12.0+ 才有的配置文件, 他在 config/Console/PluginDependencies.yml

另外，如果你要找 mcl 的配置，他在 config.json

**Comment by ConstantineQAQ** [comment]
我的mirai项目里面没有config这个文件夹，是因为我项目还没有导入完全吗？但是我现在项目导入的巨慢，是因为什么原因呢？

**Comment by cssxsh** [comment]
> 我的mirai项目里面没有config这个文件夹，是因为我项目还没有导入完全吗？但是我现在项目导入的巨慢，是因为什么原因呢？

这个 issue 讨论的是 mirai-console 自动加载插件依赖的的问题

不是 开发插件时加载依赖的问题，你找错地方了
