### ISSUE TITLE
账户安全认证功能失效

### ISSUE THREAD

**Issue by yuanbolin** [mamoe/mirai#2190]
### 问题描述

登录 QQ 账户时弹出 Mirai UnsafeDeviceLoginVerify 窗口提示进行设备锁验证：

### 复现

登录 QQ 账户，并触发 Mirai UnsafeDeviceLoginVerify 窗口提示，按照要求进行验证并关闭此窗口。

### mirai-core 版本

2.11.1

### bot-protocol

ANDROID_PHONE

**Comment by yuanbolin** [comment]
![175761672-3fc1138f-3634-4d0c-8663-af34675f7554](https://user-images.githubusercontent.com/44077734/183616259-b6d40a12-e120-4b51-b809-ce762f683ceb.png)

**Comment by yang12163** [comment]
我也遇到了这个情况，好像是现在必须手机短信才行

**Comment by Him188** [comment]
我今天用了这个, 我的账号还可以用. 里面的验证是扫码通过的. 你可以尝试先在手机 QQ 登录机器人账号, 然后再登录 bot, 这个验证就可能会让你用手机 qq 扫码

**Comment by LookStars** [comment]
我今天也遇到了类似的问题，但是miraiandroid中验证之后会弹出非安全环境不让登录

**Comment by RealSeek** [comment]
> 我今天用了这个, 我的账号还可以用. 里面的验证是扫码通过的. 你可以尝试先在手机 QQ 登录机器人账号, 然后再登录 bot, 这个验证就可能会让你用手机 qq 扫码

已经尝试过了也不行,会无限提示验证,在手机QQ登陆时需要短信验证,电脑登录需要手机上确认才可以,之前issue的办法也都试过了,不知道是不是修改了这类验证的方式

**Comment by LookStars** [comment]
我的解决方法是过了一点时然后用服务器去登录 神奇的登录上了

**Comment by LookStars** [comment]
指miraiAndroid登录上了 json给到服务器，服务器无法登录，过了N小时，服务器尝试登录就莫名其妙得登录上了
miraiAndroid出现无限验证情况就清除缓存然后等几个小时 也就好像好了

**Comment by LookStars** [comment]
经供参考
