### ISSUE TITLE
为`PluginData`定义`serialize`和`deserialize`函数，开发者可以重写方法以达到不同格式数据输出的目的

### ISSUE THREAD

**Issue by LaoLittle** [mamoe/mirai#2192]
为确保兼容，可以默认为yaml，然后在PluginData内新增一个后缀属性（可以override，默认`yml`）

serialize和deserialize使用ByteArray作为数据传输，Console调用两个方法来序列化和反序列化插件数据

**Comment by LaoLittle** [comment]
有了（

**Comment by cssxsh** [comment]
其实可以自定义一个 PluginDataStorage 决定最终序列化行为

**Comment by LaoLittle** [comment]
可以使用`PluginData.onInit()`和自定义`PluginDataStorage`处理
