### ISSUE TITLE
regression: 上传文件不会触发消息发送

### ISSUE THREAD

**Issue by ryoii** [mamoe/mirai#2195]
### 问题描述

上传文件不会触发消息发送

### 复现

```
uploadFold.uploadNewFile(...)
```

### mirai-core 版本

2.12

### bot-protocol

ANDROID_PHONE

**Comment by Karlatemp** [comment]
具体代码，具体期望，真实情况是什么

**Comment by Him188** [comment]
确认用的 AbsoluteFile 么

**Comment by ryoii** [comment]
> 确认用的 AbsoluteFile 么

用的是 AbsoluteFolder，uploadNewFile, 只有一个 ExternalResouce 的重载

**Comment by ryoii** [comment]
文件是上传成功的，只是没有发送消息

手动发送 `AbsoluteFile .toMessage` 会触发阻拦，考虑应该是 bug

**Comment by Him188** [comment]
验证发现是被拦截了, 是 2.12 的 bug
