### ISSUE TITLE
发送群语音base64编码 ios端无法播放 安卓pc正常

### ISSUE THREAD

**Issue by fenglindubu** [mamoe/mirai#2197]
### 问题描述

Q1、发送群语音base64编码 ios端无法播放 安卓pc正常
Q2、以及请告知 自动登录如何设置登录设备 好像自动登录的都是 安卓手机的

### 复现

以下转json....  

Data.GroupMessageVoice.Rootobject rootobject = new Data.GroupMessageVoice.Rootobject();
rootobject.sessionKey = Program.sessionKey;
rootobject.group = group;
 var voice = new Data.GroupMessageVoice.Messagechain() { type= "Voice", base64=base64Data};

public class Rootobject
        {
            public string sessionKey { get; set; }
            public long group { get; set; }
            public Messagechain[] messageChain { get; set; }
        }

        public class Messagechain
        {
            public string type { get; set; }
            public string base64 { get; set; }
        }

### mirai-core 版本

2.12.1

### bot-protocol

ANDROID_PHONE

### 其他组件版本

[mirai-api-http]2.6.1

**Comment by cssxsh** [comment]
这取决于你原本 语音的格式 如果是 mp3 格式的语言，会因为 具体设备没有相关解码器无法播放

你可以添加下面这个 插件 解决
https://github.com/project-mirai/mirai-silk-converter

**Comment by fenglindubu** [comment]
> 这首歌的播放方式是什么格式的mp3格式，会因为具体设备没有相关解码器无法
> 
> 你可以在下面添加这个插件解决方案 https://github.com/project-mirai/mirai-silk-converter

我就是通过mp3格式的转码出silk的 basse64出现的问题

**Comment by fenglindubu** [comment]
> 这首歌的播放方式是什么格式的mp3格式，会因为具体设备没有相关解码器无法
> 
> 你可以在下面添加这个插件解决方案 https://github.com/project-mirai/mirai-silk-converter

我试试你提供的插件 谢谢

**Comment by Numendacil** [comment]
我也出过这个问题，可能是转换的时候bitrate没有设置正确

**Comment by fenglindubu** [comment]
> 我也出过这个问题，可能是转换的时候bitrate没有设置正确

咋解决的哇 有点迷

**Comment by fenglindubu** [comment]
解决了 比特率最大 24000
