### ISSUE TITLE
参数无效

### ISSUE THREAD

**Issue by Enderman-Teleporting** [mamoe/mirai#2202]
### 问题描述

在启动参数中添加-Dmirai.no-desktop无效

### 复现

1.在我的电脑上（Win11）cd至我的jar文件所在文件夹
2.启动参数java -jar QBot -Dfile.encoding=utf-8 -Dmirai.no-desktop
3.仍然出现绿字，提示桌面环境

### mirai-core 版本

不太清楚，使用的是使用mirai框架的simpler-robot框架

### bot-protocol

ANDROID_PHONE

**Comment by Enderman-Teleporting** [comment]
启动参数打错了哈那个是QBot.jar
将-Dmirai.no-desktop放在-jar前后都没用

**Comment by Enderman-Teleporting** [comment]
由于没有出错，我无法提供日志

**Comment by cssxsh** [comment]
`-Dxxx` 属于jvm 参数，肯定要放在 -jar 的前面，你最好重新测试一下

**Comment by cssxsh** [comment]
`-Dmirai.no-desktop=true`

或许你应该给这个参数赋一个值

**Comment by Enderman-Teleporting** [comment]
好
