### ISSUE TITLE
无法将设备信息保存至本地

### ISSUE THREAD

**Issue by MoraxMa** [mamoe/mirai#2206]
### 问题描述

我调用文档中的方法，本地cache文件夹中未生成device.json

文档描述:
![image](https://user-images.githubusercontent.com/44521439/186116640-442caef8-6352-45cf-b126-34eb64ace601.png)

### 复现
我的代码:
![image](https://user-images.githubusercontent.com/44521439/186117469-427c813c-1d0f-4e08-b42d-b2164b0a2e7a.png)

### mirai-core 版本

2.12.2

### bot-protocol

ANDROID_PHONE

**Comment by cssxsh** [comment]
有没有可能，你应该在登录之前设置

**Comment by MZHY08** [comment]
> 

看文档描述是将随机的配置保存到本地 device.json ，该不会是我理解错了吧…………

**Comment by MoraxMa** [comment]
> 有没有可能，你应该在登录之前设置

看文档描述是将随机的配置保存到本地 device.json ，该不会是我理解错了吧…………

**Comment by MrXiaoM** [comment]
> 看文档描述是将随机的配置保存到本地 device.json ，该不会是我理解错了吧…………

https://github.com/mamoe/mirai/blob/dev/mirai-core-api/src/commonMain/kotlin/utils/BotConfiguration.kt#L307-L316

KDoc  里说的是「使用文件储存设备信息」，并不是执行这个方法后立刻保存设备信息到本地，它只是机器人登录时的设置项

**Comment by MoraxMa** [comment]
> > 看文档描述是将随机的配置保存到本地 device.json ，该不会是我理解错了吧…………
> 
> https://github.com/mamoe/mirai/blob/dev/mirai-core-api/src/commonMain/kotlin/utils/BotConfiguration.kt#L307-L316
> 
> KDoc 里说的是「使用文件储存设备信息」，并不是执行这个方法后立刻保存设备信息到本地，它只是机器人登录时的设置项

原来是这个意思。。。如果我想把随机的设备信息保存到本地文件有什么方法吗？

**Comment by cssxsh** [comment]
> 原来是这个意思。。。如果我想把随机的设备信息保存到本地文件有什么方法吗？

就是用这个方法阿，只不过要在登录之前设置

**Comment by MoraxMa** [comment]
> > 原来是这个意思。。。如果我想把随机的设备信息保存到本地文件有什么方法吗？
> 
> 就是用这个方法阿，只不过要在登录之前设置

不是，我的意思是我想把Bot对象里的设备信息保存至本地文件，不是从本地文件读取设备信息

**Comment by cssxsh** [comment]
> > > 原来是这个意思。。。如果我想把随机的设备信息保存到本地文件有什么方法吗？
> > 
> > 
> > 就是用这个方法阿，只不过要在登录之前设置
> 
> 不是，我的意思是我想把Bot对象里的设备信息保存至本地文件，不是从本地文件读取设备信息

这个方法是指定一个文件作为缓存，没有就生成，有就读取，你到底在想什么

**Comment by Him188** [comment]
设备信息不是bot生成的，而是需要提供给bot的。在登录时如果不配置，那就是默认在内存随机一个然后提供给bot。所以你要在登录之前配置使用文件，才能将文件提供。而使用 fileBased... 的时候它会初始化一个设备信息，所以看起来像是导出设备信息。

**Comment by MoraxMa** [comment]
> 设备信息不是bot生成的，而是需要提供给bot的。在登录时如果不配置，那就是默认在内存随机一个然后提供给bot。所以你要在登录之前配置使用文件，才能将文件提供。而使用 fileBased... 的时候它会初始化一个设备信息，所以看起来像是导出设备信息。

我在本地创建了一个空的device.json文件，然后调用了fileBasedDeviceInfo 方法，重新登录后，device.json 还是空的，并没有写入设备信息

**Comment by cssxsh** [comment]
> 我在本地创建了一个空的device.json文件，然后调用了fileBasedDeviceInfo 方法，重新登录后，device.json 还是空的，并没有写入设备信息

？他会自动生成，多余的创建空文件干嘛

**Comment by MoraxMa** [comment]
> > 我在本地创建了一个空的device.json文件，然后调用了fileBasedDeviceInfo 方法，重新登录后，device.json 还是空的，并没有写入设备信息
> 
> ？他会自动生成，多余的创建空文件干嘛

我想本地生成好，传到服务器上面去用，因为服务跑在docker里

**Comment by cssxsh** [comment]
> 我想本地生成好，传到服务器上面去用，因为服务跑在docker里

我的意思是 文件 会自动创建。自己手动创建空文件是多余且错误的

**Comment by MoraxMa** [comment]
> > 我想本地生成好，传到服务器上面去用，因为服务跑在docker里
> 
> 我的意思是 文件 会自动创建。自己手动创建空文件是多余且错误的

ohhhhhhh!!!!!我到了，原来是我本地文件没刷新，一直没看到它
