### ISSUE TITLE
Command章节中介绍简单指令时类使用错误

### ISSUE THREAD

**Issue by WhitrayHB** [mamoe/mirai#2207]
### 问题描述

在[Command章节](https://github.com/mamoe/mirai/blob/dev/mirai-console/docs/Commands.md)中，简单指令的Java举例使用的是JCompositeCommand而非JSimpleCommand

### 复现

原文：
### 简单指令

简单指令与复合指令拥有一样的智能参数解析功能。简单指令没有子指令，使用 `@Handler` 标注一个函数可以让它处理指令：

*Kotlin*
- (Kotlin举例)

*Java*

```java
// MyComposite.java  (此处应使用MySimple.java)
public final class MyComposite extends JCompositeCommand /*(此处应使用JSimpleCommand)*/{
    public MyComposite() {
        super(MyPluginMain.INSTANCE, "main");
        // ...
    }

    // ...
    @Handler
    public void foo(CommandContext context, String arg, boolean b) {
        System.out.println(b);
    }
}
```

### mirai-core 版本

2.8.2

### bot-protocol

ANDROID_PHONE

**Comment by Him188** [comment]
实际上在下方477行还有一处相同错误……

https://github.com/mamoe/mirai/commit/de6bf17f0eefa65137d4635ffdd76728176064eb#commitcomment-82116432
