### ISSUE TITLE
SAGIRI no requirements.txt

### ISSUE THREAD

**Issue by yuheyuan** [mamoe/mirai#2212]
我按照流程 git clone SAGIRI。
但是没有requirements.txt文件，无法安装依赖

**Comment by Him188** [comment]
不知道你说的 SAGIRI 是什么，但它看起来与 mirai 仓库没有关系

**Comment by Nekoer** [comment]
你找错地方了，请去[sagiri-bot](https://github.com/SAGIRI-kawaii/sagiri-bot)

**Comment by Karlatemp** [comment]
你找错地方了
