### ISSUE TITLE
mirai-api-http收到的消息取不到发消息人的qq号

### ISSUE THREAD

**Issue by pinro3** [mamoe/mirai#2222]
需要的功能:
我在使用基于mirai-api-http的python插件alicebot的时候,
发现mcl控制台里有qq群号显示以及qq群消息发送者qq显示,
alicebot的消息就没有.
消息都是这个文档里https://docs.mirai.mamoe.net/mirai-api-http/api/MessageType.html 的source类型.
我需要获取到消息发送者的qq号.

实际用途:
根据对方qq发起对话.

**Comment by Him188** [comment]
提交到 https://github.com/project-mirai/mirai-api-http
