### ISSUE TITLE
使用mirai core进行群禁言提示没有权限

### ISSUE THREAD

**Issue by xungegeblue** [mamoe/mirai#2223]
### 问题描述

我这边是直接用的Java，集成mirai进行开发。
用的机器人账户是一个群的管理员
然后我调用group的禁言方法，确提示没有权限？
不知道为什么，明明我的bot用户是管理员用户，打印出来的确是Member。求大神指导一下。

### 复现

public static void main(String[] args) {
        Long qq = 326l;
        String password = "222";

        Bot bot = BotFactory.INSTANCE.newBot(qq, password, new BotConfiguration() {{
            fileBasedDeviceInfo("myDeviceInfo.json");
            /*
             * 心跳策略默认为最佳的 STAT_HB，但不适用于一些账号。
             * 如果遇到 Bot 闲置一段时间后，发消息返回成功但群内收不到的情况，请切换心跳策略，依次尝试 STAT_HB、REGISTER 和 NONE。
             * */
            setHeartbeatStrategy(HeartbeatStrategy.STAT_HB);

            /*
             * Mirai 支持多种登录协议：ANDROID_PHONE，ANDROID_PAD，ANDROID_WATCH，IPAD，MACOS 默认使用 ANDROID_PHONE。
             * */
            //setProtocol(MiraiProtocol.ANDROID_WATCH);
        }});

        bot.login();

        Group group = bot.getGroup(13242l);

        if(group!=null && group.getSettings()!=null){
            group.getSettings().setMuteAll(true);
        }

    }

### mirai-core 版本

2.13.0-M1

### bot-protocol

ANDROID_PHONE

### 系统日志

```text
Exception in thread "main" net.mamoe.mirai.contact.PermissionDeniedException: Permission denied: required ADMINISTRATOR, got actual MEMBER for Bot(3232) in group 432
	at net.mamoe.mirai.internal.contact.GroupSettingsImpl.setMuteAll(GroupSettingsImpl.kt:205)
	at App.main(App.java:48)
```

**Comment by xungegeblue** [comment]
https://mirai.mamoe.net/topic/1551/%E4%BD%BF%E7%94%A8mirai-core%E8%BF%9B%E8%A1%8C%E7%BE%A4%E7%A6%81%E8%A8%80%E6%8F%90%E7%A4%BA%E6%B2%A1%E6%9C%89%E6%9D%83%E9%99%90

**Comment by MrXiaoM** [comment]
那你在用的 mirai-core 版本到底是 2.13.0-M1 还是 2.7.0

issue 和帖子给出的版本不一致

**Comment by xungegeblue** [comment]
用到这个2.7.0版本。
不知道那个版本正常，可以给我一个建议升级的版本吗

**Comment by Him188** [comment]
一般人可以选择最新的稳定版本，即 x.y.z 格式的最新版，现在的最新稳定版是 2.12.2

**Comment by Him188** [comment]
由于你使用版本太旧而且新版本有修改过这方面代码，可能已修复问题。如果你在新版仍然遇到这个问题，可以 reopen
