### ISSUE TITLE
申请支持判断群成员当前佩戴的头衔类型（专属头衔、活跃头衔、职位头衔）

### ISSUE THREAD

**Issue by MrY-Cat** [mamoe/mirai#2233]
▪     ▪     ▪在使用机器人授予群成员专属头衔时，若群成员佩戴的是活跃头衔或管理员头衔，则专属头衔可能不会直接戴上，造成授予失败的假象，一些不知道需要手动切换的人可能产生疑惑，而机器人已经授予了专属头衔，由于不知道成员佩戴了何种头衔，从而无法提示他。
▪     ▪     ▪若添加此功能，便可以知道群成员正在佩戴的是何种类型的头衔，以便给予相应提示(如：专属头衔发放成功，但你现在佩戴的是活跃头衔，请手动切换哦)。

**Comment by MrY-Cat** [comment]
在使用机器人授予群成员专属头衔时，若群成员佩戴的是活跃头衔或管理员头衔，则专属头衔可能不会直接戴上，造成授予失败的假象，一些不知道需要手动切换的人可能产生疑惑，而机器人已经授予了专属头衔，由于不知道成员佩戴了何种头衔，从而无法提示他。
    若添加此功能，便可以知道群成员正在佩戴的是何种类型的头衔，以便给予相应提示(如：专属头衔发放成功，但你现在佩戴的是活跃头衔，请手动切换哦)。

**Comment by Him188** [comment]
@cssxsh #2115 可能解决了这个问题

**Comment by MrY-Cat** [comment]
测试显示，虽然能获取了活跃头衔，但仍然无法判断正在佩戴三种头衔的哪一个：

![1679644174086 png](https://user-images.githubusercontent.com/76583155/227458011-cdc6ef6b-caec-4e91-9d6c-9360280c7aa0.png)
![1679644197685 png](https://user-images.githubusercontent.com/76583155/227458031-559707e7-ba1a-4e05-96d2-5a0ac3b6a954.png)
![1679644221749 png](https://user-images.githubusercontent.com/76583155/227458045-4190a593-70f0-4ab8-b2fc-b3ce59f2c830.png)
![4E19197E7D2F57FC26AC437A72F9D276](https://user-images.githubusercontent.com/76583155/227458058-6a980f76-38e4-4ac2-99f4-1665574d2f72.jpg)
