### ISSUE TITLE
QQ版本过低，账号密码是正确得，也切换过登录协议。

### ISSUE THREAD

**Issue by icantever** [mamoe/mirai#2235]
### 问题描述

本地调试时候是没问题得。 放到服务器上就提醒版本过低了。  各种协议也切换过，都是在服务器上提示版本过低

### 复现

服务器上在9.4号上午是正常，下午就报QQ版本过低

### mirai-core 版本

2.9.2

### bot-protocol

ANDROID_PHONE

### 其他组件版本

kotlin-stdlib-jdk8  1.5.10

**Comment by Him188** [comment]
此问题已在 2.13.0-RC 解决

**Comment by icantever** [comment]
> 此问题已在 2.13.0-RC 解决

请问 2.13.0-RC什么时候发布

**Comment by icantever** [comment]
> > 此问题已在 2.13.0-RC 解决
> 
> 请问 2.13.0-RC什么时候发布
现在无法通过maven下载此版本

**Comment by Him188** [comment]
不能保证，可能本周内

**Comment by icantever** [comment]
> 

好的 谢谢了

**Comment by icantever** [comment]
您好，请问2.13.0-RC还没有发布么

**Comment by Him188** [comment]
还没有，最近比较忙

**Comment by icantever** [comment]
好的，等忙完这一段，请记得更新。 im wating
