### ISSUE TITLE
通过mid来实现撤回消息

### ISSUE THREAD

**Issue by Coloryr** [mamoe/mirai#2236]
目前消息撤回需要用`MessageSource`，是能否只通过`MessageSource`中的`internalIds`和`ids`来实现撤回消息
`MessageSourceBuilder`build出来是`OfflineMessageSource`，通过`OfflineMessageSource`也能实现撤回消息？

**Comment by Coloryr** [comment]
意思是只需要设置一个id就能撤回消息

**Comment by MrXiaoM** [comment]
~~我去，事颜色~~

目前在低级api中有用id撤回消息的方法

https://github.com/mamoe/mirai/blob/dev/mirai-core-api/src/commonMain/kotlin/LowLevelApiAccessor.kt#L71-L108

**Comment by Coloryr** [comment]
JAVA的lowlevel能取？

**Comment by Coloryr** [comment]
而且这个也要用IntArray而且还是2个

**Comment by sandtechnology** [comment]
由于协议底层实现原因，要撤回消息，需要internalIds、ids和时间来实现撤回消息 而且这个低级api是可以在java中调用的（@file:JvmBlockingBridge）
实例如下：
```
net.mamoe.mirai.Mirai.getInstance().recallFriendMessageRaw(bot,23333L,new int[]{123,123},new int[]{123,123},2333);
```
不过群消息看起来不需要提供时间，所以（
```
net.mamoe.mirai.Mirai.getInstance().recallGroupMessageRaw(bot,23333L,new int[]{123,123},new int[]{123,123});
```

**Comment by Coloryr** [comment]
我直接把ids全传了把
