### ISSUE TITLE
使用IDEA插件Mirai Console构建项目，kotlinVersion不正确导致项目构建失败

### ISSUE THREAD

**Issue by black-zero358** [mamoe/mirai#2240]
### 问题描述

![image](https://user-images.githubusercontent.com/53086059/189086689-005c896e-b887-4bb6-a2eb-85bb269abb9b.png)

plugins {

    val kotlinVersion = "1.7.20"

    kotlin("jvm") version kotlinVersion

    kotlin("plugin.serialization") version kotlinVersion

    id("net.mamoe.mirai-console") version "2.12.2"

}

1.7.20 改成 1.7.10，即可正常构建

### 复现

使用IDEA插件Mirai Console构建项目，kotlinVersion不正确导致项目构建失败

### mirai-core 版本

2.12.2

### bot-protocol

IPAD

### 其他组件版本

![image](https://user-images.githubusercontent.com/53086059/189087366-f6aca5a5-f353-4bac-b3fb-74eb95512b0f.png)

**Comment by black-zero358** [comment]
解决方法来自@cssxsh

**Comment by MrXiaoM** [comment]
https://github.com/mamoe/mirai/blob/dev/mirai-console/tools/intellij-plugin/src/wizard/MiraiModuleBuilder.kt#L80

获取 kotlin 版本的代码在这里，私认为要解决获取到 1.7.20 的问题或许只能换个获取方法了

**Comment by Him188** [comment]
确实

**Comment by Him188** [comment]
不过等这个 issue 会被处理的时候，Kotlin 1.7.20 也确实就要发布了，就没问题了

**Comment by cssxsh** [comment]
> 不过等这个 issue 会被处理的时候，Kotlin 1.7.20 也确实就要发布了，就没问题了


要是到时候那个值变成 1.7.30 怎么办

**Comment by Him188** [comment]
这个值是根据依赖的 Kotlin 标准插件来的，只要不改依赖就行。不过也可以研究一下获取运行时 Kotlin 插件版本
