### ISSUE TITLE
自己写的签到模块，图片无法上传，但其他功能可上传图片 报错（cannot upload group image, failed on all servers.）

### ISSUE THREAD

**Issue by fafa-junhe** [mamoe/mirai#2251]
### 问题描述

java.lang.IllegalStateException: cannot upload group image, failed on all servers.

### 复现

使用签到功能进行签到
样本
![image](https://user-images.githubusercontent.com/22996240/190084820-ee7ba471-7b9e-4448-bf4f-152c67718b61.png)

怀疑tx有图片识别 只有签到功能无法发图片，且其他机器人可发此图片

### mirai-core 版本

2.12.1

### bot-protocol

ANDROID_PHONE

### 其他组件版本

mirai-console 2.12.1
mirai-console-terminal 2.12.1

**Comment by fafa-junhe** [comment]
暂时解决 有问题再reopen

**Comment by Karlatemp** [comment]
报错呢? 图片样本呢?¿ (不知道github会不会对图片进行特别处理, 需要原始的)

**Comment by fafa-junhe** [comment]
报错就是标题的那个
原始样本等我下一次发生再发上来
