### ISSUE TITLE
因 ktor 被 relocate, ExternalResource 部分 API 无法使用

### ISSUE THREAD

**Issue by Him188** [mamoe/mirai#2254]
在 commonMain 依赖 mirai-core-api 时, 因为 mirai-core-api 没有依赖 ktor, 使用 ExternalResource.use 就会编译错误. 

![image](https://user-images.githubusercontent.com/12100985/191295266-04af8563-0408-438e-8a79-d80aaa6372dc.png)

----

在 JVM 实现 ExternalResource 时, 因为 Input 被 relocate 或一些其他原因, 用户看到的类型可能并不正确. 即使正确, 那也会是 `net.mamoe.mirai.internal.io.ktor.xxx`, 要考虑用户是否能正常使用各种补全 (例如 InputStream.asInput)

**Comment by Karlatemp** [comment]
定义一个 typealise 在 jvm 为 java.io.Closeable 在 native 为 ktor.Closeable?

**Comment by Him188** [comment]
@Karlatemp 我也是这样打算的, 但它会在 common 与 ktor 的 Closeable 是不相关的两个东西, 在非 common 造成 resolution ambiguity

**Comment by Him188** [comment]
Fixed in 9122dddfb7f8cc33f9e37450146e3b13a5d301e1

**Comment by Him188** [comment]
解决方案:
- `input()` 现在是 internal API
- 增加了多平台的 `net.mamoe.mirai.utils.Closeable`
