### ISSUE TITLE
DeviceInfo机制很奇怪，同一个DeviceInfo文件本地可以服务器不可以

### ISSUE THREAD

**Issue by SugarFatFree** [mamoe/mirai#2260]
### 问题描述

1.本地和服务器都是同一个device.json 文件，同时我尝试在本地登录，过验证码后登录成功，但是服务器上登录仍然不成功；
2.本地登录成功后，我删除了cache文件夹，再次登录发现仍然需要过验证码，不删除则不需要，使用的都是本地的DeviceInfo文件；
3.使用同一个DeviceInfo文件，在本地登录成功之后，直接在服务器无法登录，但是如果本地登录完成再 fileBasedDeviceInfo 生产 DeviceInfo 文件，放入服务器，则服务器可以登录，请问这是为什么？

- [ ] 

### 复现

1.生成一个DeviceInfo文件（其实是本地登录成功后 fileBasedDeviceInfo 生产，但是由于账号被冻结，再次登录后仍然需要过验证码）；
2. 本地使用 生成的 DeviceInfo 进行登录，过验证码登录成功，再服务器登录仍然不成功；
3. 本地使用原 DeviceInfo 文件登录成功后，再次 fileBasedDeviceInfo 随机生成一个，将生成的放入服务器，登录成功。

```
    val deviceFilePath =
        "D:\\Workspace\\Java\\xiaoxi_mirai\\src\\main\\resources\\devices\\other\\device_123456.json"
    val bot = BotFactory.newBot(123456, "xxxx"){
        protocol = BotConfiguration.MiraiProtocol.ANDROID_PAD
        deviceInfo = { _ -> File(deviceFilePath).loadAsDeviceInfo() }
//        fileBasedDeviceInfo()
    }
    bot.login()
```

### mirai-core 版本

2.12.3

### bot-protocol

ANDROID_PAD

**Comment by iceBear67** [comment]
和腾讯风控有关吧

**Comment by Him188** [comment]
本地和服务器是不同的网络环境

**Comment by SugarFatFree** [comment]
> device.json

那为什么重新生成一次 device.json  又可以了？用原来的就不行
