### ISSUE TITLE
2.13.0-RC 使用 http api 相关功能报错 java.lang.NoClassDefFoundError: okhttp3/Request$Builder

### ISSUE THREAD

**Issue by cssxsh** [mamoe/mirai#2263]
### 问题描述

使用 http api 相关的功能，例如 群公告api 会发生报错 `java.lang.NoClassDefFoundError: okhttp3/Request$Builder`

### 复现

在代码中使用 公告api
```
group.announcements.publish(OfflineAnnouncement(content = content))
```

### mirai-core 版本

2.13.0-RC

### bot-protocol

ANDROID_WATCH

**Comment by Him188** [comment]
是用 MCL 启动么

**Comment by cssxsh** [comment]
> 是用 MCL 启动么

不是, 是 mirai:runConsole  task 启动 的

**Comment by Him188** [comment]
那确实有可能会有问题, 不知道 MCL 怎么样

**Comment by Him188** [comment]
2小时后试试 `2.13.0-dev-394c0a5`?
