### ISSUE TITLE
mirai机器人运行一个月后OOM，怀疑是内存溢出

### ISSUE THREAD

**Issue by DADWDAEAWE01** [mamoe/mirai#2272]
### 问题描述

使用java开发的mirai机器人，在vps里运行一个月后，OOM。
使用Mat分析dump，内存泄漏分析结果为
``` 
17,572 instances of kotlinx.coroutines.ChildHandleNode, loaded by org.apache.catalina.loader.ParallelWebappClassLoader @ 0xc2f59548 occupy 956,589,160 (94.77%) bytes.

Keywords

kotlinx.coroutines.ChildHandleNode
org.apache.catalina.loader.ParallelWebappClassLoader @ 0xc2f59548
```
发现线程数量有56683个，其中io.netty.util.concurrent.FastThreadLocalThread有56580个。
展开其中一个线程，发现有循环引用的kotlinx.coroutines.ChildHandleNode
![image](https://user-images.githubusercontent.com/108279396/194756539-95729d3c-242a-437f-9ac7-f6e855943337.png)

### 复现

暂无复现

### mirai-core 版本

2.9.1

### bot-protocol

MACOS

**Comment by Him188** [comment]
2.9.1太旧了，换2.12.3或者2.13.0-RC试试？

**Comment by DADWDAEAWE01** [comment]
> 2.9.1太旧了，换2.12.3或者2.13.0-RC试试？

好，我试试2.12.3
