### ISSUE TITLE
Cannot access 'net.mamoe.mirai.utils.Closeable' which is a super type of 'net.mamoe.mirai.utils.ExternalResource'

### ISSUE THREAD

**Issue by Nambers** [mamoe/mirai#2275]
### 问题描述

![}X(W$}EV5 EDK%BD)R_S`7C](https://user-images.githubusercontent.com/35139537/195102971-505602b4-b37a-4579-a23b-62a81dfa7503.png)

只依赖了 `mirai-core-api` 需要进一步依赖 `net.mamoe.mirai:mirai-core-utils` 来暂时修复这个问题
解决 #2254 所带来的问题

### 复现

None

### mirai-core 版本

2.13.0-RC2-dev-7eac75bb

### bot-protocol

ANDROID_PHONE

**Comment by Him188** [comment]
JVM 源集没问题吧

**Comment by Him188** [comment]
问题是在 common 还是在 native

**Comment by Him188** [comment]
根据 #2270, `2.13.0-RC2-dev-7eac75bb` 又是怎么跑的呢

**Comment by Nambers** [comment]
> 问题是在 common 还是在 native

common

> 根据 #2270, `2.13.0-RC2-dev-7eac75bb` 又是怎么跑的呢

可能因为他是snapshot?

**Comment by Him188** [comment]
![image](https://user-images.githubusercontent.com/12100985/196737516-ed805ea6-f031-445d-9f02-84e442ee7bd2.png)

JVM 正常

**Comment by Him188** [comment]
不是很好解决, 先更新文档让用多平台的添加依赖了

**Comment by Him188** [comment]
#2698
