### ISSUE TITLE
`AtomicSeq*` 应当是特设的, 避免额外资源占用

### ISSUE THREAD

**Issue by Colerar** [mamoe/mirai#2287]
<img width="667" alt="image" src="https://user-images.githubusercontent.com/62297254/196597631-f74813f5-ab38-4932-9028-36651edee415.png">

<img width="669" alt="image" src="https://user-images.githubusercontent.com/62297254/196597752-e12585d7-751d-4991-b167-d614788bb7cd.png">

所谓特设，即避免每个实例都持有 `maxExclusive`，而是改写为 `value class` 并且单独写两个特设的实现，对于该属性，这能将原来 `O(n)` 的空间复杂度降低为 `O(1)`。这能避免 `AtomicIntSeq` 的占用。

codegen 或编译器插件能让此过程更优雅，然而这仅为锦上添花。Mirai 的用例中仅有两类，即：

```kotlin
@JvmStatic
fun forMessageSeq() = AtomicIntSeq(0, Int.MAX_VALUE)

@JvmStatic
fun forPrivateSync() = AtomicIntSeq(getRandomUnsignedInt(), 65535)
```

同时根据 [`kotlinx.atomicfu` 文档](https://github.com/Kotlin/kotlinx-atomicfu)，任何工具方法都应当是内联的：

> You can define you own extension functions on `AtomicXxx` types but they must be inline and they cannot be public and be used outside of the module they are defined in.

因此，实现应该类似这样：

```kotlin
@JvmInline
@Suppress("NOTHING_TO_INLINE")
internal value class AtomicIntSeq(
  private val value: AtomicInt = atomic(0)
) {
  /**
   * Increment [value] within the range from 0 (inclusive) to [Int.MAX_VALUE] (exclusive).
   */
  inline fun next(): Int = value.incrementAndGet().mod(Int.MAX_VALUE)

  /**
   * Atomically update [value] if it is smaller than [new].
   *
   * @param new should be positive
   */
  inline fun updateIfSmallerThan(new: Int): Boolean {
    value.update { instant ->
      if (instant < new) new else return false
    }
    return true
  }

  /**
   * Atomically update [value] if it different with [new].
   *
   * @param new should be positive
   */
  inline fun updateIfDifferentWith(new: Int): Boolean {
    value.update { instant ->
      if (instant == new) return false
      new
    }
    return true
  }
}

@JvmInline
@Suppress("NOTHING_TO_INLINE")
internal value class Atomic65535Seq(
  private val value: AtomicInt = atomic(0)
) {
  /**
   * Increment [value] within the range from 0 (inclusive) to [Int.MAX_VALUE] (exclusive).
   */
  inline fun next(): Int = value.incrementAndGet().mod(65535)

  /**
   * Atomically update [value] if it is smaller than [new].
   *
   * @param new should be positive
   */
  inline fun updateIfSmallerThan(new: Int): Boolean {
    value.update { instant ->
      if (instant < new) new else return false
    }
    return true
  }

  /**
   * Atomically update [value] if it different with [new].
   *
   * @param new should be positive
   */
  inline fun updateIfDifferentWith(new: Int): Boolean {
    value.update { instant ->
      if (instant == new) return false
      new
    }
    return true
  }
}
```

遗憾的是，`kotlinx.atomicfu` 没有 `UShortAtomic` 原语，针对 `Atomic65535Seq` 进一步的优化是不可行的。

**Comment by Him188** [comment]
写这个的时候 Kotlin 的 inline class 还未稳定, 所以没用

**Comment by Him188** [comment]
![image](https://user-images.githubusercontent.com/12100985/198826853-05650902-549c-4d32-bf6a-3bd7b1893e1e.png)

发现其实当时写的时候就有考虑了，现在我也在思考 atomicfu 编译器是否真的能优化 value class

**Comment by Him188** [comment]
![image](https://user-images.githubusercontent.com/12100985/198827013-fdc8f1f3-174c-4e3e-88e3-5354532edabf.png)

事实上 mirai 就没有开 atomicfu 编译器也就没有任何优化，应该是它一直编译失败就关掉了

**Comment by Him188** [comment]
![image](https://user-images.githubusercontent.com/12100985/198827448-af2bb007-20fd-443a-a520-818ece566975.png)

很不幸它仍然是不能编译的

**Comment by Him188** [comment]
https://github.com/mamoe/mirai/issues/2315

**Comment by Him188** [comment]
启用编译后出现了这个问题：
```
AbstractUser.kt: net.mamoe.mirai.internal.contact.AbstractUser::<init>: factory kotlinx.atomicfu.AtomicFU::atomic invocation must be followed by putfield
AbstractUser.kt:281: net.mamoe.mirai.internal.contact.AbstractUser::<init>: invocation of method net.mamoe.mirai.internal.utils.AtomicIntMaxSeq::constructor-impl on atomic types. Make the latter method 'inline' to use it
```
所以它的确是不能处理 value class 的
