### ISSUE TITLE
`Base64` 的 JVM 实现应当避免反复创建实例

### ISSUE THREAD

**Issue by Colerar** [mamoe/mirai#2288]
应将：

[Ref](https://github.com/mamoe/mirai/blob/fb3f39e328be713c5b4296f8889531b5afb08129/mirai-core-utils/src/jvmMain/kotlin/Actuals.kt#L18-L24)

```kotlin
public actual fun ByteArray.encodeBase64(): String {
    return Base64.getEncoder().encodeToString(this)
}

public actual fun String.decodeBase64(): ByteArray {
    return Base64.getDecoder().decode(this)
}
```

改为：

```kotlin
private val base64Encoder = Base64.getEncoder()

private val base64Decoder = Base64.getDecoder()

public actual fun ByteArray.encodeBase64(): String {
    return base64Encoder.encodeToString(this)
}

public actual fun String.decodeBase64(): ByteArray {
    return base64Decoder.decode(this)
}
```

> This class **consists exclusively of static methods** for obtaining encoders and decoders for the Base64 encoding scheme. The implementation of this class supports the following types of Base64 as specified in RFC 4648  and RFC 2045 .

**Comment by Karlatemp** [comment]
![](https://user-images.githubusercontent.com/30070303/196663800-4aebc07e-1d70-46bc-b70b-f8a4be4e02bd.png)

What are you meaning?

**Comment by Colerar** [comment]
[OpenJDK 8-b120 java/util/Base64.java](https://github.com/openjdk/jdk/blob/9a9add8825a040565051a09010b29b099c2e7d49/jdk/src/share/classes/java/util/Base64.java#L36-L41)

**Comment by Karlatemp** [comment]
为什么不看往未来 而是要停留在过去

**Comment by sandtechnology** [comment]
这玩意本来就是静态返回常量的 难道说你要论证一下单条INVOKENSTATIC指令对mirai运行的影响吗（
就算你要论证 如果方法调用频繁 会由JVM动态进行内联的 这种优化反而会带来可维护性和可读性的降低 属于没必要的优化
另外优化应该优化热点方法，做优化请带上二八定律的想法，把精力放到最有用的事情上，做完优化做下修改前后的benchmark，免得造成负优化（

**Comment by Colerar** [comment]
> 这玩意本来就是静态返回常量的 难道说你要论证一下单条INVOKENSTATIC指令对mirai运行的影响吗（

关于这点确实是我没看清楚。

> 这种优化反而会带来可维护性和可读性的降低 属于没必要的优化

Mirai 里面 `@JvmStatic` 还见得少吗？这是否属于「带来可维护性和可读性的降低 属于没必要的优化」。

> 另外优化应该优化热点方法，做优化请带上二八定律的想法，把精力放到最有用的事情上 这种优化反而会带来可维护性和可读性的降低 属于没必要的优化

你没有资格指责开源贡献者的精力所向，就算我每天开一百个 issue 修复或者甚至修复歪了，那也是我的乐趣所在。至于主分支是否愿意合并，那是 Maintainer 该考虑的。

另：Mirai 里面不可读的代码多了去了，就比如[这个三连 `.also`](https://github.com/mamoe/mirai/blob/7ebbff9f50d39833136069363628bdd3ab3155bd/mirai-core/src/commonMain/kotlin/contact/GroupImpl.kt#L255-L259)。

> 做完优化做下修改前后的benchmark，免得造成负优化

这是一个 issue，而不是 PR。在 benchmark 前先发个 issue prototype 是很正常的。不必在这点上纠结。

**Comment by Him188** [comment]
`@JvmStatic` 是必要的，它是 Kotlin 现阶段没有 namespace 等概念为类型定义静态方法的 workaround。在 Java 使用 `Image.Companion.fromId` 是不如 `Image.fromId` 的。

JvmStatic 并不是优化，它会生成额外的静态方法而并不会删除成员方法。
