### ISSUE TITLE
Java Maven下mirai-core-jvm-2.12.3引入报错

### ISSUE THREAD

**Issue by 781236208** [mamoe/mirai#2295]
![image](https://user-images.githubusercontent.com/17609283/197436959-cf801890-cf0f-4b9e-b910-59ee7d5bdf28.png)
在pom.xml中引入2.13.0-RC2版本时候，在lib下发现没有这个包mirai-core-api-jvm-2.13.0-RC2.jar，导致类无法import.
回退到2.12.3时候，则mirai-core-api-jvm-2.12.3.jar有对应版本的api包。
2.13.0-RC2时候
![image](https://user-images.githubusercontent.com/17609283/197436666-6bc26510-6d16-478e-afe9-5e4f4fe475f4.png)
![image](https://user-images.githubusercontent.com/17609283/197436704-b95fb960-372b-4f45-aa04-3521118935f5.png)
2.12.3时候
![image](https://user-images.githubusercontent.com/17609283/197436640-793ef68f-b42c-4c58-9356-7f02b493c17f.png)

### 复现

<dependency>
		  <groupId>net.mamoe</groupId>
		  <artifactId>mirai-core-jvm</artifactId>
		  <version>2.13.0-RC2</version>
</dependency>

### mirai-core 版本

2.13.0-RC2

### bot-protocol

ANDROID_PAD

**Comment by Him188** [comment]
2.13 项目架构复杂一些，依赖一些 Gradle Metadata。

可以再显式加一个对 mirai-core-api 的依赖

**Comment by 781236208** [comment]
![image](https://user-images.githubusercontent.com/17609283/197493156-2f4aa345-8217-498a-8e86-a5ae75abd6b9.png)
引入对mirai-core-api依赖，再把mirai-core-api、mirai-core-utils-jvm对应版本的jar包手动下载到本地仓库后，可以正常部署使用了

**Comment by icantever** [comment]
请问，如何手动下载RC2得jar包， 因为是kotlin项目，无法直接使用maven用源码打包，还有其他得什么办法呢

**Comment by 781236208** [comment]
kotlin不清除，Java Maven我是在这里下载的：https://mvnrepository.com/artifact/net.mamoe/mirai-core-jvm

**Comment by nannanness** [comment]
哈喽，我也遇到了这个问题，和你一样的版本，不过我的本地仓库有对应的三个jar包，但是还是import失败，请问有别的解决方法吗
