### ISSUE TITLE
申请戳一戳(Nudge)支持ANDROID_PAD协议

### ISSUE THREAD

**Issue by MrY-Cat** [mamoe/mirai#2296]
如题，希望戳一戳(Nudge)消息能支持ANDROID_PAD协议，以便使用该协议时，既能手机和机器人一起登录，也能解析戳一戳(Nudge)消息

**Comment by Him188** [comment]
如果使用 ANDROID_PAD 登录，服务器就不会发事件，所以没法做

**Comment by MrY-Cat** [comment]
> 如果使用 ANDROID_PAD 登录，服务器就不会发事件，所以没法做

那看来只有等腾讯啥时候更新平板支持戳一戳了，才能做了）悲）

**Comment by Him188** [comment]
mirai 没有写限制，如果什么时候服务器会发事件了那就直接支持了

**Comment by MrY-Cat** [comment]
> mirai 没有写限制，如果什么时候服务器会发事件了那就直接支持了

收到
