### ISSUE TITLE
mirai-console 应允许插件使用 ktor，以向下兼容

### ISSUE THREAD

**Issue by Him188** [mamoe/mirai#2297]
如果插件不自己定义依赖，就让他 resolve 到 Ktor 1.6.7

**Comment by cssxsh** [comment]
我觉得应该 弄个类似 plugin-shared-libraries 的配置项
指定为某个插件注入特定版本的依赖，这样子比较好

**Comment by Him188** [comment]
注入应该不好， @Karlatemp

**Comment by Karlatemp** [comment]
应该在 plugin system 到 system classloader 中间再加一层 classloader

**Comment by cssxsh** [comment]
> 注入应该不好， @Karlatemp

这还可能方便处理统一日志框架的问题，比如将 slf4j 统一到某个版本，而不是各自为政
