### ISSUE TITLE
基于 Clikt 基础，重写 Mirai Console 命令解析后端

### ISSUE THREAD

**Issue by Colerar** [mamoe/mirai#2300]
## 概要

[Clikt](https://github.com/ajalt/clikt) 是一个多平台的，用于解析通用命令行纯文本参数的 Kotlin 库。只需要删除其中 CLI 特定的部分（如环境变量解析、argfile 解析、文件输入等），即可用于 Mirai 的 IM 环境。

## 目的

提供简介易用、跨平台的命令行解析。

## 动机

现有 Console 命令解析基于反射构造，这不利于未来可能的 Kotlin Native 或 Kotlin JS 移殖。并且注解 API 在 Kotlin 中的使用体验不佳，无法充分利用 Kotlin 代理和拓展函数的优势。

Clikt API 已经经过广泛验证，具有 Kotlin 风格和无反射优势。[文档](https://ajalt.github.io/clikt/) 全面，支持多种参数风格。

支持 UNIX、JVM 等多种参数风格。而不是一个 args 从头解到尾，出现可选参数的棘手问题（ https://github.com/mamoe/mirai/issues/2128 ）。这些在文档中都可以看到。

当前 Console 命令也没有统一的命令帮助模板，help 命令聊胜于无。不支持诸如 `--help` 的参数查询。如：

```plaintext
/ip -h

用法: ip [选项] [LINK]

  /ip <IP>

选项:
  -l, --language 文本  要显示的语言
  -p, --position      是否显示经纬度
  -v, --verbose       是否显示详细信息
  -m, --metadata      输出元数据
  -h, --help          显示帮助信息

参数:
  LINK  IP 或域名
```

## 如何实现

我先前已经在别的项目中[尝试过](https://github.com/Sorapointa/Sorapointa/tree/master/sorapointa-core/src/main/kotlin/org/sorapointa/command)移殖 Clikt，流畅的 API 能够极大程度减少样板代码和反射异常：

```kotlin
class Version(private val sender: CommandSender) : Command(sender, Version) {

    companion object : Entry(
        name = "version",
        helpKey = "sora.cmd.version.desc",
    )

    override suspend fun run() {
        sender.sendMessage("Sorapointa v$VERSION-$BUILD_BRANCH+$COMMIT_HASH")
    }
}
```

```kotlin
class ConsoleUser(val sender: ConsoleCommandSender) : ConsoleCommand(
    sender,
    ConsoleUser,
    Option(printHelpOnEmptyArgs = true)
) {
    companion object : Entry(
        name = "consoleuser",
        helpKey = "sora.cmd.console.user.desc",
        alias = listOf("cslusr")
    )

    private val username by option(
        names = arrayOf("--username", "-u"),
        help = CoreBundle.message("sora.cmd.console.user.opt.user", locale = sender.locale)
    )

    private val password by option(
        names = arrayOf("--password", "--pwd", "-p"),
        help = CoreBundle.message("sora.cmd.console.user.opt.pwd", locale = sender.locale)
    )

    enum class Operation {
        ADD, UPDATE, DELETE, LIST
    }

    private val operation by option(
        help = CoreBundle.message("sora.cmd.console.user.opt.operation", locale = sender.locale)
    ).switchSet(
        setOf("--add", "-a") to Operation.ADD,
        setOf("--update", "--upd", "-U") to Operation.UPDATE,
        setOf("--delete", "--del", "-d") to Operation.DELETE,
        setOf("--list", "--ls", "-l") to Operation.LIST,
    ).default(Operation.ADD)

    override suspend fun run() {
      // 实现略
    }
}
```

如果暂时，不考虑兼容问题，实现并不难。只需要有一个 `CommandManager` 用于存储全局注册的命令，将每个命令实例存储于全局的 HashMap 中。并使用 `CommandSender` 映射 Mirai 的联系人等。

注册如此：

```kotlin
val defaultsCommand: List<AbstractCommandNode<*>> = listOf(
    CommandNode(Help) { sender -> Help(sender) },
    CommandNode(ListPlayer) { sender -> ListPlayer(sender) },
    CommandNode(LocaleCommand) { sender -> LocaleCommand(sender) },
    CommandNode(Version) { sender -> Version(sender) },
    ConsoleCommandNode(Quit) { sender -> Quit(sender) },
    ConsoleCommandNode(ConsoleUser) { sender -> ConsoleUser(sender) },
)
```

为何要存一组 `lambda` 呢？因为 Clikt API 是面向对象的，充分利用 Kotlin 面向对象风格，而不用死写静态方法，导致代码难以维护。

并且命令也冗长不利于使用，比如：

```plaintext
/lp group default permission set AdminPermission admin=true
/lp group default permission set OwnerPermission level=owner
/lp group default permission set OwnerPermission level=admin
/lp group default permission set PermissionInGroup group=1234567890
/lp group default permission set PermissionInGroup group=1234567890 admin=true
```

完全能够改造成 UNIX 式的，便于使用的前缀参数风格：

```plaintext
lp -Sgdp --property AdminPermission --value admin=true
```

这一点我已不必再说，几乎所有 CLI 都是这种风格，可见其优越性。

### 富文本解析

`Clikt`  不支持富文本解析，然而我觉得这不是一个大问题。因为图片和文本的分界本来就模棱两可，且解析过程异常复杂。这应该通过上下文对话，要求发送者输入对应的富文本消息。

如：

```plaintext
Sender > /imagesearch
Bot > 请发送图片以供搜索
Sender > [图片]
Bot > 查询结果: xxxx
```

或针对简单用例特殊优化，如只有一个参数的命令：

```plaintext
Sender > /search [图片]
Bot > 查询结果: xxxx
```

## 和旧命令接口的兼容性问题

应该可以维护两套 API，同时监听消息，如果新接口处理了命令，则老接口不再处理。

**Comment by Colerar** [comment]
~傻逼 GitHub 每次都是写一半按到 ctrl enter，待我写完……~

**Comment by Him188** [comment]
反射设计确实是有限制的，不过在现在架构基础上用你的想法扩展是可能的。

**Comment by Colerar** [comment]
如果可以，接下来几天我试试交个 PR。

**Comment by Him188** [comment]
实现上建议新开一个模块写，应该不需要改内部架构。

**Comment by Colerar** [comment]
是可以考虑新加 `mirai-clikt` 模块，可以完全不依赖任何 `mirai` 组件。仅提供 IM 环境下的参数解析功能。即只有 `String -> List<String>`、 `List<String>` 解析，让 `mirai-console` 负责提取纯文本消息（上文已经提到，`Clikt` 不能处理富文本）。

因此仅使用 `mirai-core` 也可以依赖 `mirai-clikt`，提供最大的便携性。

实际上我认为，其他很多 `mirai-console` 的模块也可以完全做到解耦，如 `net.mamoe.mirai.console.data`。可将解析功能分离。然而考虑到兼容性，现在再来抽一个模块并不容易。

`mirai-console` 应依赖 `mirai-clikt`，提供特定的 `Permission` 和 `Sender` 等实现。

涉及到旧命令兼容方面的问题可能比较多，我先初步移殖 `mirai-clikt`。

**Comment by Keyezi** [comment]
同意 另外现在命令命名规范还是不太行

**Comment by char-46** [comment]
新增命令解析器的权限应该被mirai-console管理……
mirai-console外挂plugin或者mirai-native各自进行的命令解析及处理不能简单的使用`/perm`管理，需找到各个插件提供的设置或根本无法管理权限。

**Comment by Colerar** [comment]
感觉实际上这个功能做成 out-of-tree 的，单独的插件或库会更好，不应和 `mirai-console` 绑定（也有不少机器人实现是仅依赖 `mirai-core` 的）。再加上腾讯风控导致开发和调试困难，精力有限，没有时间再维护单独的一个库。此 issue 和关连 PR 就先 close了。
