### ISSUE TITLE
提示 当前QQ版本过低，请升级至最新版本后再登录

### ISSUE THREAD

**Issue by yikus-tjq** [mamoe/mirai#2319]
### 问题描述

![image](https://user-images.githubusercontent.com/38431925/198939278-33db1a3b-9109-4c5e-aa1d-ccfffac6ae06.png)
这个怎么解决？

### 复现

登录

### mirai-core 版本

2.8.2

### bot-protocol

ANDROID_PHONE

**Comment by MrXiaoM** [comment]
重复 #2298

**Comment by qfys521** [comment]
[#2298]（https://github.com/mamoe/mirai/issues/2298）

**Comment by qfys521** [comment]
已有重复于 #2298
