### ISSUE TITLE
slf4j报错,这么难的东西都做出来了,不明白一个简单的日志打印老是能报错???

### ISSUE THREAD

**Issue by godhelpjun** [mamoe/mirai#2330]
### 问题描述

2022-11-08 00:01:48 I/main: Backend: version 2.13.0, built on 2022-11-01 10:47:11.
2022-11-08 00:01:48 I/main: Frontend Terminal: version 2.13.0, provided by Mamoe Technologies
2022-11-08 00:01:48 I/main: Welcome to visit https://mirai.mamoe.net/
2022-11-08 00:01:48 W/stderr: SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder"
2022-11-08 00:01:48 W/stderr: SLF4J: Defaulting to no-operation (NOP) logger implementation
2022-11-08 00:01:48 W/stderr: SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.

### 复现

启动就有了

### mirai-core 版本

2.13.0

### bot-protocol

ANDROID_PHONE

### 其他组件版本

MCL 已推出 2.1.0，更好的支持 Mirai 2.11 的插件系统，建议更新。

  00:01:45 [INFO] Verifying "net.mamoe:mirai-console" v2.13.0
  00:01:46 [INFO] Verifying "net.mamoe:mirai-console-terminal" v2.13.0
  00:01:46 [INFO] Verifying "net.mamoe:mirai-core-all" v2.13.0
  00:01:47 [INFO] Verifying "org.itxtech:mcl-addon" v2.0.2
  00:01:47 [INFO] Verifying "net.mamoe:mirai-api-http" v2.6.2
  00:01:47 [INFO] Verifying "xyz.cssxsh.mirai:mirai-device-generator" v1.1.3
2022-11-08 00:01:48 I/main: Starting mirai-console...
2022-11-08 00:01:48 I/main:

### 系统日志

```text
2022-11-08 00:01:48 I/main: Backend: version 2.13.0, built on 2022-11-01 10:47:11.
2022-11-08 00:01:48 I/main: Frontend Terminal: version 2.13.0, provided by Mamoe Technologies
2022-11-08 00:01:48 I/main: Welcome to visit https://mirai.mamoe.net/
2022-11-08 00:01:48 W/stderr: SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder"
2022-11-08 00:01:48 W/stderr: SLF4J: Defaulting to no-operation (NOP) logger implementation
2022-11-08 00:01:48 W/stderr: SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
```

### 网络日志

```text
2022-11-08 00:01:48 I/main: Backend: version 2.13.0, built on 2022-11-01 10:47:11.
2022-11-08 00:01:48 I/main: Frontend Terminal: version 2.13.0, provided by Mamoe Technologies
2022-11-08 00:01:48 I/main: Welcome to visit https://mirai.mamoe.net/
2022-11-08 00:01:48 W/stderr: SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder"
2022-11-08 00:01:48 W/stderr: SLF4J: Defaulting to no-operation (NOP) logger implementation
2022-11-08 00:01:48 W/stderr: SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
```

### 补充信息

2022-11-08 00:01:48 I/main: Backend: version 2.13.0, built on 2022-11-01 10:47:11.
2022-11-08 00:01:48 I/main: Frontend Terminal: version 2.13.0, provided by Mamoe Technologies
2022-11-08 00:01:48 I/main: Welcome to visit https://mirai.mamoe.net/
2022-11-08 00:01:48 W/stderr: SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder"
2022-11-08 00:01:48 W/stderr: SLF4J: Defaulting to no-operation (NOP) logger implementation
2022-11-08 00:01:48 W/stderr: SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.

**Comment by Nekoer** [comment]
？

**Comment by StageGuard** [comment]
？

**Comment by cssxsh** [comment]
welcome pr

**Comment by Nekoer** [comment]
不会真有人以为这是bug吧

**Comment by 4o4E** [comment]
不会真有人以为这是bug吧

**Comment by sandtechnology** [comment]
欢迎 PR，你看见的表层日志背后肯定有深层次的问题才一直没有解决

**Comment by LaoLittle** [comment]
slf4j报错,这么难的东西都做出来了,不明白一个简单的日志打印老是能报错???

**Comment by godhelpjun** [comment]
> 欢迎 PR，你看见的表层日志背后肯定有深层次的问题才一直没有解决

什么问题?

**Comment by KKW557** [comment]
你认真的吗

**Comment by Karlatemp** [comment]
虽然这确实是个问题

但

以我个人来说

你的语气能不能好点，你这是来报告问题的语气吗

**Comment by Keyezi** [comment]
首先不影响使用，其次你不是什么客户，对开源项目提建议请注意你的语气

**Comment by kagg886** [comment]
我的评价是，管好你的嘴

**Comment by kenvix** [comment]
> > 欢迎 PR，你看见的表层日志背后肯定有深层次的问题才一直没有解决
> 
> 什么问题?

😅所以你为什么不自己去解决这个“弱智”问题捏

**Comment by chuanwise** [comment]
建议管好你的嘴。

![](https://pic1.imgdb.cn/item/636b591b16f2c2beb1fbf681.png)

**Comment by godhelpjun** [comment]
> > > 欢迎 PR，你看见的表层日志背后肯定有深层次的问题才一直没有解决
> > 
> > 
> > 什么问题?
> 
> 😅所以你为什么不自己去解决这个“弱智”问题捏

这明显是打包的时候 没有加上一个默认实现,一个个嘴炮大神,只会在这里喷,看下代码都不会

**Comment by godhelpjun** [comment]
> 我的评价是，管好你的嘴

嘴炮大神,只说没去看代码

**Comment by godhelpjun** [comment]
> 建议管好你的嘴。
> 
> ![](https://camo.githubusercontent.com/895b7dad74cbc24d233dd7d7adab7bde95c42bcc170e23f28260e50720c630c5/68747470733a2f2f706963312e696d6764622e636e2f6974656d2f3633366235393162313666326332626562316662663638312e706e67)

评论区 这么多嘴炮大神 服了

**Comment by 4o4E** [comment]
> > 建议管好你的嘴。
> > ![](https://camo.githubusercontent.com/895b7dad74cbc24d233dd7d7adab7bde95c42bcc170e23f28260e50720c630c5/68747470733a2f2f706963312e696d6764622e636e2f6974656d2f3633366235393162313666326332626562316662663638312e706e67)
> 
> 评论区 这么多嘴炮大神 服了

> 你的语气能不能好点，你这是来报告问题的语气吗

> 首先不影响使用，其次你不是什么客户，对开源项目提建议请注意你的语气

**Comment by godhelpjun** [comment]
> > > 建议管好你的嘴。
> > > ![](https://camo.githubusercontent.com/895b7dad74cbc24d233dd7d7adab7bde95c42bcc170e23f28260e50720c630c5/68747470733a2f2f706963312e696d6764622e636e2f6974656d2f3633366235393162313666326332626562316662663638312e706e67)
> > 
> > 
> > 评论区 这么多嘴炮大神 服了
> 
> > 你的语气能不能好点，你这是来报告问题的语气吗
> 
> > 首先不影响使用，其次你不是什么客户，对开源项目提建议请注意你的语气

又一个 嘴炮大神 有本事提pr,不要在这里教育别人了,离开问题太远了,又有何用?

**Comment by 4o4E** [comment]
> > > > 建议管好你的嘴。
> > > > ![](https://camo.githubusercontent.com/895b7dad74cbc24d233dd7d7adab7bde95c42bcc170e23f28260e50720c630c5/68747470733a2f2f706963312e696d6764622e636e2f6974656d2f3633366235393162313666326332626562316662663638312e706e67)
> > > 
> > > 
> > > 评论区 这么多嘴炮大神 服了
> > 
> > 
> > > 你的语气能不能好点，你这是来报告问题的语气吗
> > 
> > 
> > > 首先不影响使用，其次你不是什么客户，对开源项目提建议请注意你的语气
> 
> 又一个 嘴炮大神 有本事提pr,不要在这里教育别人了,离开问题太远了,又有何用?

那你能注意你的态度吗？这不是你花钱定制的软件

**Comment by godhelpjun** [comment]
> > > > > 建议管好你的嘴。
> > > > > ![](https://camo.githubusercontent.com/895b7dad74cbc24d233dd7d7adab7bde95c42bcc170e23f28260e50720c630c5/68747470733a2f2f706963312e696d6764622e636e2f6974656d2f3633366235393162313666326332626562316662663638312e706e67)
> > > > 
> > > > 
> > > > 评论区 这么多嘴炮大神 服了
> > > 
> > > 
> > > > 你的语气能不能好点，你这是来报告问题的语气吗
> > > 
> > > 
> > > > 首先不影响使用，其次你不是什么客户，对开源项目提建议请注意你的语气
> > 
> > 
> > 又一个 嘴炮大神 有本事提pr,不要在这里教育别人了,离开问题太远了,又有何用?
> 
> 那你能注意你的态度吗？这不是你花钱定制的软件

我哪句说过,谁必须给我修复了?我只是听说这么一个软件,跑一下 发现了一个问题,报告一下
如你说的 不影响使用 是因为我根本都没用 我也不知道有没有真正影响使用,就是报告一下 
请指出 我哪句说过 必须马上修复??

**Comment by chuanwise** [comment]
> > > > > > 建议管好你的嘴。
> > > > > > ![](https://camo.githubusercontent.com/895b7dad74cbc24d233dd7d7adab7bde95c42bcc170e23f28260e50720c630c5/68747470733a2f2f706963312e696d6764622e636e2f6974656d2f3633366235393162313666326332626562316662663638312e706e67)
> > > > > 
> > > > > 
> > > > > 评论区 这么多嘴炮大神 服了
> > > > 
> > > > 
> > > > > 你的语气能不能好点，你这是来报告问题的语气吗
> > > > 
> > > > 
> > > > > 首先不影响使用，其次你不是什么客户，对开源项目提建议请注意你的语气
> > > 
> > > 
> > > 又一个 嘴炮大神 有本事提pr,不要在这里教育别人了,离开问题太远了,又有何用?
> > 
> > 
> > 那你能注意你的态度吗？这不是你花钱定制的软件
> 
> 我哪句说过,谁必须给我修复了?我只是听说这么一个软件,跑一下 发现了一个问题,报告一下 如你说的 不影响使用 是因为我根本都没用 我也不知道有没有真正影响使用,就是报告一下 请指出 我哪句说过 必须马上修复??

没有说「必须给我修复」就可以用这么恶劣的态度了？你看看有人关心你说没说「必须给我修复」吗？你到现在还没清楚你的问题在哪。

**Comment by 4o4E** [comment]
> > > > > > 建议管好你的嘴。
> > > > > > ![](https://camo.githubusercontent.com/895b7dad74cbc24d233dd7d7adab7bde95c42bcc170e23f28260e50720c630c5/68747470733a2f2f706963312e696d6764622e636e2f6974656d2f3633366235393162313666326332626562316662663638312e706e67)
> > > > > 
> > > > > 
> > > > > 评论区 这么多嘴炮大神 服了
> > > > 
> > > > 
> > > > > 你的语气能不能好点，你这是来报告问题的语气吗
> > > > 
> > > > 
> > > > > 首先不影响使用，其次你不是什么客户，对开源项目提建议请注意你的语气
> > > 
> > > 
> > > 又一个 嘴炮大神 有本事提pr,不要在这里教育别人了,离开问题太远了,又有何用?
> > 
> > 
> > 那你能注意你的态度吗？这不是你花钱定制的软件
> 
> 我哪句说过,谁必须给我修复了?我只是听说这么一个软件,跑一下 发现了一个问题,报告一下 如你说的 不影响使用 是因为我根本都没用 我也不知道有没有真正影响使用,就是报告一下 请指出 我哪句说过 必须马上修复??

> slf4j报错,这么难的东西都做出来了,不明白一个简单的日志打印老是能报错???

1. 那请问你这个标题的态度和好能沾上边吗？
2. 你说嘴炮，那能说明哪儿嘴炮你了吗？
3. 你说`有本事提pr`，那请问你pr了吗
4. 你从哪儿看出`教育`你了
5. 自始自终没有人说过修复的问题，都是在说你应该注意你的态度

**Comment by 4o4E** [comment]
建议看看别人怎么提的issue，你这可不是报告bug的态度

**Comment by Keyezi** [comment]
《很明显》
您要不自己看看源码在看看您说的什么？
另外我还教育你？你自己写过几个开源项目还以为自己已经独当一面了？

**Comment by StageGuard** [comment]
> > > > 欢迎 PR，你看见的表层日志背后肯定有深层次的问题才一直没有解决
> > > 
> > > 
> > > 什么问题?
> > 
> > 
> > 😅所以你为什么不自己去解决这个“弱智”问题捏
> 
> 这明显是打包的时候 没有加上一个默认实现,一个个嘴炮大神,只会在这里喷,看下代码都不会

插件系统比较复杂，涉及了多个 classloader 以及其依赖关系。另外据开发者描述，还有多平台适配问题。
所以如果真的简单加一个默认就能实现的话，这个问题早就不该存在了。
另外开发者已经在解决这个问题了

**Comment by Him188** [comment]
系统复杂是一个原因。我们不敢轻易动这些底层的东西，要动的时候也有更高优先级的任务要做，就不会处理这些小问题。

**Comment by qfys521** [comment]
乐

**Comment by qfys521** [comment]
[如果你发现自己是个精神病，你该怎么办？]（https://www.zhihu.com/question/441288506?utm_id=0）

**Comment by qfys521** [comment]
[如果你发现自己是个精神病，你该怎么办？](https://www.zhihu.com/question/441288506?utm_id=0)

**Comment by ThymeChen** [comment]
你这么厉害，为什么不自己解决捏

**Comment by Coloryr** [comment]
哦我的天啊，这可真的是一个重大bug我的好兄弟

**Comment by Huaxidesu** [comment]
前来围观

**Comment by KasumiNova** [comment]
前来吃瓜

**Comment by yelinlan** [comment]
前来围观

**Comment by Dawnwalker666** [comment]
前来围观，鉴定为妙

**Comment by Strelizia02** [comment]
这么难的问题你都分析出来了，不明白为什么不能直接提交一个简单的PR，反而过来提issue？？？？

**Comment by NoMathExpectation** [comment]
呵呵

**Comment by kenvix** [comment]
> > > > 欢迎 PR，你看见的表层日志背后肯定有深层次的问题才一直没有解决
> > > 
> > > 
> > > 什么问题?
> > 
> > 
> > 😅所以你为什么不自己去解决这个“弱智”问题捏
> 
> 这明显是打包的时候 没有加上一个默认实现,一个个嘴炮大神,只会在这里喷,看下代码都不会

@godhelpjun 那这边建议自己加个默认实现看看能不能跑通所有测试捏🥰

**Comment by MrY-Cat** [comment]
six

**Comment by WeSourceCode** [comment]
前来围观，鉴定为妙

**Comment by xtexx** [comment]
妙啊，PR welcome，哦我的天呐，这个漏洞可以让数千QQ机器人无法正常输出日志，可能导致大家的服务器被hack而不知情，快去发CVE然后提交CNNVD然后发PR吧或者去往linux kernel里面塞patch，检测到mirai就强行修补，嗷！天大的漏洞！

你说的对，但是《mirai》是由mamoe自主研发的一款全新开放世界MQQ协议实现。代码执行发生在一个被称作「JVM」的幻想世界，在这里，被神选中的人将被授予「Heap」，导引元素之力。你将扮演一位名为「JVMTI」的神秘角色，在自由的旅行中邂逅性格各异、能力独特的同伴们，和他们一起击败强敌，找回失散的亲人——同时，逐步发掘「mirai」的真相。

**Comment by std-microblock** [comment]
前来围观

**Comment by undefined-moe** [comment]
草 笑死

**Comment by ilharp** [comment]
前来围观，顺便背一下 2330 这个数字

**Comment by MirrorCY** [comment]
6

**Comment by pandadtdyy** [comment]
前来围观

**Comment by synodriver** [comment]
![C996E03B-EF64-4A03-805F-A17C8A6B8047](https://user-images.githubusercontent.com/50922489/201511199-39b687a7-5ab5-4a01-9da9-8f65775f2176.jpeg)

**Comment by Mahoo12138** [comment]
前来围观

**Comment by Lipraty** [comment]
![_189SURT7R)7$A`LA`}X%$9](https://user-images.githubusercontent.com/18106422/201511223-cc562cc2-0efb-48d3-8fe6-12a547eff5d0.jpg)

**Comment by zhanbao2000** [comment]
闻讯前来围观

**Comment by Walnut-233** [comment]
6

**Comment by KaRuichin** [comment]
mirai报错是怎么回事呢？mirai相信大家都很熟悉，但是mirai报错是怎么回事呢，下面就让小编带大家一起了解吧。
　　mirai报错，其实就是mirai报错了，大家可能会很惊讶mirai怎么会报错呢？但事实就是这样，小编也感到非常惊讶。
　　这就是关于mirai报错的事情了，大家有什么想法呢，欢迎在评论区告诉小编一起讨论哦！

**Comment by ghost** [comment]
前来围观（

**Comment by SakuraKoi** [comment]
(啃瓜

**Comment by Nobooooody** [comment]
我只是来表达我的乐,并没有别的意思,就是觉得好玩,希望不要误解我的意思;

**Comment by djkcyl** [comment]
乐

**Comment by Arispex** [comment]
前来吃瓜

**Comment by zhaodice** [comment]
咸来围观

**Comment by xm1014inDGP** [comment]
slf4j报错，到底需要如何做到，slf4j不报错，又会如何产生。 slf4j报错，到底应该如何实现。 了解清楚slf4j报错到底是一种怎么样的存在，是解决一切问题的关键。 我们不得不面对一个非常尴尬的事实，那就是， 一般来讲，我们都必须务必慎重的考虑考虑。 拉罗什福科在不经意间这样说过，我们唯一不会改正的缺点是软弱。这句话语虽然很短，但令我浮想联翩。 本人也是经过了深思熟虑，在每个日日夜夜思考这个问题。 我们一般认为，抓住了问题的关键，其他一切则会迎刃而解。 在这种困难的抉择下，本人思来想去，寝食难安。 了解清楚slf4j报错到底是一种怎么样的存在，是解决一切问题的关键。

**Comment by Mantou1233** [comment]
前来围观

**Comment by bin-tenkuu** [comment]
乐

**Comment by Alceatraz** [comment]
乐

**Comment by 4o3F** [comment]
太乐了，竟然到现在还open着

**Comment by KaRuichin** [comment]
![image](https://user-images.githubusercontent.com/69111766/205773056-c698ecd4-3253-44ca-8fc9-9d4b7b59b6fe.png)

**Comment by Myfanqie** [comment]
乐
