### ISSUE TITLE
MessageEvent添加已撤回属性

### ISSUE THREAD

**Issue by Keyezi** [mamoe/mirai#2335]
我的插件里添加了撤回消息功能，但是如果用户重复撤回同一条消息就会导致报错，除非我自行做检测。
而且我认为自己做检测还是有无法检测到消息被撤回的风险，所以请求添加此属性

**Comment by Him188** [comment]
你可以 try-catch 抛的异常

**Comment by NoMathExpectation** [comment]
我觉得可以加个方法，跟撤回消息一样，但是即使已经撤回了也不抛异常，直接返回

**Comment by Him188** [comment]
> 我觉得可以加个方法，跟撤回消息一样，但是即使已经撤回了也不抛异常，直接返回

撤回消息会抛出异常。应当组合 try-catch 或者自己写扩展解决，不然 mirai API 就不一致了，同时就也要考虑加禁言时不抛出异常的函数。
