### ISSUE TITLE
读取名片信息

### ISSUE THREAD

**Issue by uebian** [mamoe/mirai#234]
通过QQ号读取名片信息，比如点赞数

**Comment by Him188** [comment]
点赞数不重要, 而一些其他个人资料如性别倒是可以

**Comment by ketal178** [comment]
能更近一步支持修改名片吗
获取别人的名片数据以及上传这种自定义的名片数据
``` json
{
  "styleId":0,
  "bgId":3807,
  "cardId":3807,
  "renderInfo":{
    "v":1597733236,
    "bg":[
      {
        "type":"image_view",
        "scale_type":"center_crop",
        "content":"https:\/\/r.photo.store.qq.com\/psc?\/V12ccqw73f0HyQ\/ruAMsa53pVQWN7FLK88i5jHxgvhjD.gsIEAZdJIsR4H5G1iKXCVxbCWZbk2UI0JjosgPpBvHn0iRcL49Dl5GotWJRvi8jHQX8SC0aid18YI!\/o&bo=gAJqBe4CWAYREHg!"
      },
      {
        "type":"mask_view",
        "content":"#00000000"
      },
      {
        "type":"lottie_view",
        "loop":"1",
        "content":"https:\/\/imgcache.qq.com\/xydata\/card\/customProfileAnimation\/2029\/1c1e7ce53c6c8c2bbb7b02aa711e7764.zip"
      }
    ],
    "header":{
      "type":"layout",
      "width":"fill",
      "height":"fill",
      "order":0,
      "child":[
        {
          "id":"2001",
          "type":"image_view",
          "scale_type":"center_crop",
          "x":"0w",
          "y":"1365000h",
          "width":"10000w",
          "height":"6814w",
          "content":"",
          "positionLimit":{
            "bottom":"75px"
          },
          "stickerId":2063
        },
        {
          "content":"",
          "id":"2002",
          "scale_type":"center_crop",
          "stickerId":2068,
          "type":"image_view",
          "width":"4000w",
          "height":"4000w",
          "x":"3000w",
          "y":"3500000h",
          "gravity":"center_horizontal"
        },
        {
          "id":"1002",
          "type":"pf_avatar",
          "x":"3500w",
          "y":"3500000h",
          "positionLimit":{
            "top":"88px",
            "bottom":"88px"
          },
          "gravity":"center_horizontal",
          "border":"2002"
        },
        {
          "id":"1003",
          "type":"pf_name",
          "x":"4605w",
          "y":"6500000h",
          "width":"5395w",
          "height":"",
          "positionLimit":{
            "top":"88px",
            "bottom":"120px",
            "left":"32px",
            "right":"32px"
          },
          "f":0,
          "ft":1,
          "gravity":"center_horizontal",
          "bg":""
        },
        {
          "id":"1001",
          "type":"pf_like",
          "x":"3600w",
          "y":"4000h",
          "height":"1050w",
          "positionLimit":{
            "top":"88px",
            "bottom":"88px"
          },
          "style":1,
          "bg":"",
          "lpd":12,
          "rpd":12
        }
      ]
    },
    "body":{
      "id":22,
      "c":"#00000000",
      "f":"",
      "t_bg":"https:\/\/imgcache.qq.com\/xydata\/card\/item\/3807\/r\/dcc6ef2de2bd4853c3b10293678d54ff-t_bg.png2",
      "arr":"https:\/\/imgcache.qq.com\/xydata\/card\/item\/3807\/r\/dcc6ef2de2bd4853c3b10293678d54ff-arr.png2",
      "sbg":"https:\/\/imgcache.qq.com\/xydata\/card\/item\/3807\/r\/dcc6ef2de2bd4853c3b10293678d54ff-sbg.png2",
      "cbg":"https:\/\/imgcache.qq.com\/xydata\/card\/item\/3807\/r\/dcc6ef2de2bd4853c3b10293678d54ff-cbg.png2",
      "cpd":8,
      "line":"#00FFFFFF",
      "modules":[
        {
          "type":"info",
          "qq":"https:\/\/imgcache.qq.com\/xydata\/card\/item\/3807\/r\/dcc6ef2de2bd4853c3b10293678d54ff-qq.png2",
          "p":"https:\/\/imgcache.qq.com\/xydata\/card\/item\/3807\/r\/dcc6ef2de2bd4853c3b10293678d54ff-p.png2",
          "sign":"https:\/\/imgcache.qq.com\/xydata\/card\/item\/3807\/r\/dcc6ef2de2bd4853c3b10293678d54ff-sign.png2",
          "lv":"https:\/\/imgcache.qq.com\/xydata\/card\/item\/3807\/r\/dcc6ef2de2bd4853c3b10293678d54ff-lv.png2",
          "metal":"https:\/\/imgcache.qq.com\/xydata\/card\/item\/3807\/r\/dcc6ef2de2bd4853c3b10293678d54ff-metal.png2",
          "arr":"https:\/\/imgcache.qq.com\/xydata\/card\/item\/3807\/r\/dcc6ef2de2bd4853c3b10293678d54ff-info_arr.png2"
        },
        {
          "type":"state",
          "ph":""
        },
        {
          "type":"qz",
          "ph":""
        },
        {
          "type":"photo"
        },
        {
          "type":"tag"
        },
        {
          "type":"exp"
        }
      ],
      "ts":0
    }
  },
  "callback":"__MQQ_CALLBACK_AUTO_7"
}
```
![Screenshot_2020-09-21-08-40-12-218_com.tencent.mobileqq.jpg](https://user-images.githubusercontent.com/41381927/93726049-56785d00-fbe6-11ea-8ccf-6d20027a7c2b.jpg)![Screenshot_2020-09-21-08-42-50-713_com.tencent.mobileqq.jpg](https://user-images.githubusercontent.com/41381927/93726078-87f12880-fbe6-11ea-87e4-f5ab696b7297.jpg)

**Comment by Him188** [comment]
> 能更近一步支持修改名片吗
> 获取别人的名片数据以及上传这种自定义的名片数据
> 
> ```json
> {
>   "styleId":0,
>   "bgId":3807,
>   "cardId":3807,
>   "renderInfo":{
>     "v":1597733236,
>     "bg":[
>       {
>         "type":"image_view",
>         "scale_type":"center_crop",
>         "content":"https:\/\/r.photo.store.qq.com\/psc?\/V12ccqw73f0HyQ\/ruAMsa53pVQWN7FLK88i5jHxgvhjD.gsIEAZdJIsR4H5G1iKXCVxbCWZbk2UI0JjosgPpBvHn0iRcL49Dl5GotWJRvi8jHQX8SC0aid18YI!\/o&bo=gAJqBe4CWAYREHg!"
>       },
>       {
>         "type":"mask_view",
>         "content":"#00000000"
>       },
>       {
>         "type":"lottie_view",
>         "loop":"1",
>         "content":"https:\/\/imgcache.qq.com\/xydata\/card\/customProfileAnimation\/2029\/1c1e7ce53c6c8c2bbb7b02aa711e7764.zip"
>       }
>     ],
>     "header":{
>       "type":"layout",
>       "width":"fill",
>       "height":"fill",
>       "order":0,
>       "child":[
>         {
>           "id":"2001",
>           "type":"image_view",
>           "scale_type":"center_crop",
>           "x":"0w",
>           "y":"1365000h",
>           "width":"10000w",
>           "height":"6814w",
>           "content":"",
>           "positionLimit":{
>             "bottom":"75px"
>           },
>           "stickerId":2063
>         },
>         {
>           "content":"",
>           "id":"2002",
>           "scale_type":"center_crop",
>           "stickerId":2068,
>           "type":"image_view",
>           "width":"4000w",
>           "height":"4000w",
>           "x":"3000w",
>           "y":"3500000h",
>           "gravity":"center_horizontal"
>         },
>         {
>           "id":"1002",
>           "type":"pf_avatar",
>           "x":"3500w",
>           "y":"3500000h",
>           "positionLimit":{
>             "top":"88px",
>             "bottom":"88px"
>           },
>           "gravity":"center_horizontal",
>           "border":"2002"
>         },
>         {
>           "id":"1003",
>           "type":"pf_name",
>           "x":"4605w",
>           "y":"6500000h",
>           "width":"5395w",
>           "height":"",
>           "positionLimit":{
>             "top":"88px",
>             "bottom":"120px",
>             "left":"32px",
>             "right":"32px"
>           },
>           "f":0,
>           "ft":1,
>           "gravity":"center_horizontal",
>           "bg":""
>         },
>         {
>           "id":"1001",
>           "type":"pf_like",
>           "x":"3600w",
>           "y":"4000h",
>           "height":"1050w",
>           "positionLimit":{
>             "top":"88px",
>             "bottom":"88px"
>           },
>           "style":1,
>           "bg":"",
>           "lpd":12,
>           "rpd":12
>         }
>       ]
>     },
>     "body":{
>       "id":22,
>       "c":"#00000000",
>       "f":"",
>       "t_bg":"https:\/\/imgcache.qq.com\/xydata\/card\/item\/3807\/r\/dcc6ef2de2bd4853c3b10293678d54ff-t_bg.png2",
>       "arr":"https:\/\/imgcache.qq.com\/xydata\/card\/item\/3807\/r\/dcc6ef2de2bd4853c3b10293678d54ff-arr.png2",
>       "sbg":"https:\/\/imgcache.qq.com\/xydata\/card\/item\/3807\/r\/dcc6ef2de2bd4853c3b10293678d54ff-sbg.png2",
>       "cbg":"https:\/\/imgcache.qq.com\/xydata\/card\/item\/3807\/r\/dcc6ef2de2bd4853c3b10293678d54ff-cbg.png2",
>       "cpd":8,
>       "line":"#00FFFFFF",
>       "modules":[
>         {
>           "type":"info",
>           "qq":"https:\/\/imgcache.qq.com\/xydata\/card\/item\/3807\/r\/dcc6ef2de2bd4853c3b10293678d54ff-qq.png2",
>           "p":"https:\/\/imgcache.qq.com\/xydata\/card\/item\/3807\/r\/dcc6ef2de2bd4853c3b10293678d54ff-p.png2",
>           "sign":"https:\/\/imgcache.qq.com\/xydata\/card\/item\/3807\/r\/dcc6ef2de2bd4853c3b10293678d54ff-sign.png2",
>           "lv":"https:\/\/imgcache.qq.com\/xydata\/card\/item\/3807\/r\/dcc6ef2de2bd4853c3b10293678d54ff-lv.png2",
>           "metal":"https:\/\/imgcache.qq.com\/xydata\/card\/item\/3807\/r\/dcc6ef2de2bd4853c3b10293678d54ff-metal.png2",
>           "arr":"https:\/\/imgcache.qq.com\/xydata\/card\/item\/3807\/r\/dcc6ef2de2bd4853c3b10293678d54ff-info_arr.png2"
>         },
>         {
>           "type":"state",
>           "ph":""
>         },
>         {
>           "type":"qz",
>           "ph":""
>         },
>         {
>           "type":"photo"
>         },
>         {
>           "type":"tag"
>         },
>         {
>           "type":"exp"
>         }
>       ],
>       "ts":0
>     }
>   },
>   "callback":"__MQQ_CALLBACK_AUTO_7"
> }
> ```
> 
> ![Screenshot_2020-09-21-08-42-50-713_com.tencent.mobileqq.jpg](https://user-images.githubusercontent.com/41381927/93726078-87f12880-fbe6-11ea-87e4-f5ab696b7297.jpg)![Screenshot_2020-09-21-08-45-08-135_com.tencent.mobileqq.jpg](https://user-images.githubusercontent.com/41381927/93726156-f59d5480-fbe6-11ea-9cf3-5fd7b620530d.jpg)

这可能是一个新的问题，与这个 issue （读取名片）无关。如有需要请以“新特性”开一个 issue
