### ISSUE TITLE
按协议分配session保存位置

### ISSUE THREAD

**Issue by wyapx** [mamoe/mirai#2346]
在之前的测试和 #2345 中发现不同协议之间session并不通用，建议按协议类型重新分配保存位置（或删除原有session），避免互相影响的问题。

**Comment by Nambers** [comment]
确实 我试了下只要在之前能正常登录 MACOS 协议的 cache 和 device.json 下登录 android_phone 协议就会稳定复现报错
https://github.com/mamoe/mirai/issues/2345#issuecomment-1315523661
