### ISSUE TITLE
mirai-core 2.12.3 MessageChainBuilder对象的append()方法size不计数

### ISSUE THREAD

**Issue by Fndream** [mamoe/mirai#2350]
### 问题描述

append() 后 chainBuilder size依旧为0
![QQ图片20221117225216](https://user-images.githubusercontent.com/53517522/202479682-bb5f4d8f-adfe-46eb-8ce9-5fb4c7ea7774.jpg)

add后同样size不变
![QQ图片20221117225211](https://user-images.githubusercontent.com/53517522/202479614-9f8f8401-eacd-4021-bec9-ca235689a4c8.png)

实际消息链是有添加进去的，消息也可以发送出去，但是size计数没增加
之前是用Stringbuilder组装纯文本后用MessageBuilder加个at。现在组装face，与字符串混合组装，用MessageBuilder，删元素数组越界。
2.13.0okhttp找不到，测试不了

### 复现

完整代码
![QQ图片20221117225219](https://user-images.githubusercontent.com/53517522/202479692-66add00e-757f-4a9c-bfd3-b96a37c1c753.png)

### mirai-core 版本

2.12.3

### bot-protocol

ANDROID_PAD

**Comment by Fndream** [comment]
另外MessageChain不让remove，remove异常read-only。就完全没辙了qwq

**Comment by Fndream** [comment]
突然想到，MessageChainBuilder好像remove是直接删一个元素吧（
按道理来说似乎也并不能直接实现删尾换行符。嗯……
我还是StringBuilder和MessageBuilder混着组装好了

不过这个问题，size没有实现？

**Comment by Him188** [comment]
MCB 对连续字符串有缓存，会合并成一个 PlainText. 所以在缓存没有 flush 时 size 不变。

**Comment by Fndream** [comment]
好的，感谢解答
