### ISSUE TITLE
使用Java开发实现LoginSolver

### ISSUE THREAD

**Issue by xggz** [mamoe/mirai#2361]
### 问题描述

1、重写onSolveDeviceVerification方法时，不知道为什么传过来了第三个参数，然后发送requestSms时也需要传一个Continuation<? super Unit>对象，我看源代码里面没有；
![Snipaste_2022-11-25_09-46-30](https://user-images.githubusercontent.com/8168663/203884227-dcb9f507-31ff-4edd-8ab9-583cd92fc986.png)

2、使用短信登录验证后，可以接收到短信，但是程序出错了；
![image](https://user-images.githubusercontent.com/8168663/203884984-d469dd8a-73d7-4e6b-9ce7-7797dad46856.png)
![image](https://user-images.githubusercontent.com/8168663/203885061-2002185e-5c85-4149-baa0-2d9cde0d9429.png)
![image](https://user-images.githubusercontent.com/8168663/203885081-e08c59b0-7822-42c2-b422-807d5223b9d4.png)

### 复现

使用MACOS协议登录，第一次需要滑动验证吗，后面再短信登录

### mirai-core 版本

2.13.0-RC2

### bot-protocol

MACOS

**Comment by MrXiaoM** [comment]
这是暂停函数 (suspend)，更推荐在 kotlin 编写

**Comment by xggz** [comment]
> 这是暂停函数 (suspend)，更推荐在 kotlin 编写

整个程序都是java编写的。。。。这块有其他的解决办法吗

**Comment by MrXiaoM** [comment]
> > 这是暂停函数 (suspend)，更推荐在 kotlin 编写
> 
> 整个程序都是java编写的。。。。这块有其他的解决办法吗

java 和 kt 可以混写，你可以只有这部分用 kt 来写。如果那有什么只能用 java 的需求，目前我还没找到资料，~~你可以 kotlin 写一段编译再反编译看看。~~

**Comment by xggz** [comment]
> > > 这是暂停函数 (suspend)，更推荐在 kotlin 编写
> > 
> > 
> > 整个程序都是java编写的。。。。这块有其他的解决办法吗
> 
> java 和 kt 可以混写，你可以只有这部分用 kt 来写。如果那有什么只能用 java 的需求，目前我还没找到资料，~你可以 kotlin 写一段编译再反编译看看。~

谢谢解惑，我试试kt吧，不过还是希望后面这块能兼容java

**Comment by xggz** [comment]
已用kt修复此问题，但是 还是希望 开发者们能解决此问题，感谢

**Comment by sandtechnology** [comment]
看起来是缺了对Java的注解 加上应该就好（

**Comment by Karlatemp** [comment]
https://github.com/Kotlin-zh/KEEP/blob/master/proposals/coroutines.md

**Comment by xggz** [comment]
第一次写kt，不知道有没有问题，但是可以登录成功了，也没有报错：
![image](https://user-images.githubusercontent.com/8168663/203902345-90df5d1a-4a05-4918-b6ce-eb39bd4c6f56.png)

**Comment by Him188** [comment]
Kotlin 挂起协程属于语言级特性，不是很容易支持。mirai现阶段允许Java直接调用方法是写了一个Kotlin编译器插件在编译阶段生成额外方法实现的。

@xggz 看起来你在 suspend 函数里进行了阻塞调用，这在并发量不高时没有问题，但若并发高就会阻塞协程使用的线程池导致整个系统挂起。不过一般自己使用也不会太严重。

**Comment by Him188** [comment]
也可以为 Java 写一个覆盖了 suspend，转发到非挂起函数的“重载”实现。
