### ISSUE TITLE
java使用gradle构建项目，引入net.mamoe:mirai-console-terminal 报错

### ISSUE THREAD

**Issue by ShineAnthony** [mamoe/mirai#2366]
平时使用java和maven比较多，没接触过kotlin和gradle 。但是我希望使用java调用mirai做一个骰娘。
然后我使用gradle构建了一个项目，但是net.mamoe:mirai-console-terminal 报错
![image](https://user-images.githubusercontent.com/57893000/204326314-325da0e3-21a6-4128-8b20-fbb4339d04d7.png)
配置文件如上图所示，但是下图报错，感觉是不能下载
![image](https://user-images.githubusercontent.com/57893000/204326459-b99eb795-8ce0-4a29-b8f8-beb9e0eb6476.png)
希望请教下大家java 使用mirai做一个骰娘的解决方案，想调用骰娘去做qq部分，我这边做接收处理指令部分起码。

**Comment by ShineAnthony** [comment]
不知道是不是 console-terminal不支持 build.gradle 这个配置文件。但是我其实第一次用gradle平时使用的是maven

**Comment by ShineAnthony** [comment]
我是想用mirai把本地电脑上的qq变成骰子（通过java语言调用），是不是不一定需要console，有core就能实现了呢？

**Comment by sandtechnology** [comment]
RTFM https://docs.mirai.mamoe.net/

**Comment by Karlatemp** [comment]
为什么你要同时使用spring和console?
