### ISSUE TITLE
以mirai作为依赖开发时，参数-Dmirai.no-desktop无效

### ISSUE THREAD

**Issue by disymayufei** [mamoe/mirai#2368]
### 问题描述

在无桌面环境时，我试图添加参数-Dmirai.no-desktop，但仍会尝试弹出图形框并报错
我想知道有没有办法在开发时就可以设定阻止图形框弹出，或者默认无桌面模式，而非添加-Dmirai.no-desktop参数

### 复现

1.以mirai 2.13.0-RC2作为依赖开发Minecraft服务器插件
2.将插件装载于无桌面的环境
3.运行后Awt报错

### mirai-core 版本

2.13.0-RC2

### bot-protocol

ANDROID_PAD

### 系统日志

```text
[Server] [21:55:16] [main/INFO]: [STDOUT]: 2022-11-30 21:55:16 W/WindowHelperJvm: Failed to initialize module `java.desktop`
[Server] java.awt.AWTError: Can't connect to X11 window server using ':10.0' as the value of the DISPLAY variable.
[Server]        at java.desktop/sun.awt.X11GraphicsEnvironment.initDisplay(Native Method)
[Server]        at java.desktop/sun.awt.X11GraphicsEnvironment$1.run(X11GraphicsEnvironment.java:101)
[Server]        at java.base/java.security.AccessController.doPrivileged(AccessController.java:318)
[Server]        at java.desktop/sun.awt.X11GraphicsEnvironment.<clinit>(X11GraphicsEnvironment.java:60)
[Server]        at java.desktop/sun.awt.PlatformGraphicsInfo.createGE(PlatformGraphicsInfo.java:36)
[Server]        at java.desktop/java.awt.GraphicsEnvironment$LocalGE.createGE(GraphicsEnvironment.java:93)
[Server]        at java.desktop/java.awt.GraphicsEnvironment$LocalGE.<clinit>(GraphicsEnvironment.java:84)
[Server]        at java.desktop/java.awt.GraphicsEnvironment.getLocalGraphicsEnvironment(GraphicsEnvironment.java:106)
[Server]        at java.desktop/sun.awt.X11.XToolkit.<clinit>(XToolkit.java:224)
[Server]        at java.desktop/sun.awt.PlatformGraphicsInfo.createToolkit(PlatformGraphicsInfo.java:40)
[Server]        at java.desktop/java.awt.Toolkit.getDefaultToolkit(Toolkit.java:599)
[Server]        at net.mamoe.mirai.utils.WindowHelperJvm.<clinit>(SwingSolver.kt:248)
[Server]        at net.mamoe.mirai.utils.PlatformLoginSolverImplementations$default$2.invoke(LoginSolver.jvm.kt:34)
[Server]        at net.mamoe.mirai.utils.PlatformLoginSolverImplementations$default$2.invoke(LoginSolver.jvm.kt:33)
[Server]        at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
[Server]        at net.mamoe.mirai.utils.PlatformLoginSolverImplementations.getDefault(LoginSolver.jvm.kt:33)
[Server]        at net.mamoe.mirai.utils.LoginSolver.<clinit>(LoginSolver.kt:131)
[Server]        at net.mamoe.mirai.utils.BotConfiguration.<init>(BotConfiguration.kt:222)
[Server]        at net.mamoe.mirai.utils.BotConfiguration.<clinit>(BotConfiguration.kt:626)
[Server]        at cn.starlight.qbot.QBot.<init>(QBot.java:25)
[Server]        at cn.starlight.qbot.Main.onInitialize(Main.java:83)
[Server]        at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47)
[Server]        at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35)
[Server]        at net.fabricmc.loader.impl.game.minecraft.Hooks.startServer(Hooks.java:62)
[Server]        at net.minecraft.server.Main.main(Main.java:101)
[Server]        at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
[Server]        at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
[Server]        at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23)
[Server]        at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69)
[Server]        at net.fabricmc.installer.ServerLauncher.main(ServerLauncher.java:69)
```

**Comment by Karlatemp** [comment]
try `-Dmirai.no-desktop=true`

**Comment by disymayufei** [comment]
> 

尝试过这一方法，但是会转变为什么都不显示，机器人也无法正常登录

**Comment by cssxsh** [comment]
> java.awt.AWTError: Can't connect to X11 window server using ':10.0' as the value of the DISPLAY variable.

这个请尝试 把 ssh 客户端的 x11 转发关掉

**Comment by disymayufei** [comment]
那请问正常的使用-Dmirai.no-desktop=true后效果应该是怎样的呢？

**Comment by MrXiaoM** [comment]
> 那请问正常的使用-Dmirai.no-desktop=true后效果应该是怎样的呢？

所有应该弹出窗口的验证方法都改为在控制台完成

**Comment by disymayufei** [comment]
> > 那请问正常的使用-Dmirai.no-desktop=true后效果应该是怎样的呢？
> 
> 所有应该弹出窗口的验证方法都改为在控制台完成

但实际上我这边是无窗口弹出，控制台也一直卡住无任何显示

**Comment by disymayufei** [comment]
![image](https://user-images.githubusercontent.com/72013933/204948239-7547f5fe-fe0b-447f-b557-7a64064e98b5.png)
实际效果就是这样

> > > 那请问正常的使用-Dmirai.no-desktop=true后效果应该是怎样的呢？
> > 
> > 
> > 所有应该弹出窗口的验证方法都改为在控制台完成
> 
> 但实际上我这边是无窗口弹出，控制台也一直卡住无任何显示

![image](https://user-images.githubusercontent.com/72013933/204948288-a2e28c86-66ca-40ce-94ad-89c3c9a773e0.png)
实际效果就是这样

**Comment by disymayufei** [comment]
> > > 那请问正常的使用-Dmirai.no-desktop=true后效果应该是怎样的呢？
> > 
> > 
> > 所有应该弹出窗口的验证方法都改为在控制台完成
> 
> 但实际上我这边是无窗口弹出，控制台也一直卡住无任何显示

![image](https://user-images.githubusercontent.com/72013933/204948331-0e6a1421-3264-4690-808a-9a2d29fc4e49.png)
实际效果就是这样

**Comment by Karlatemp** [comment]
你stdin已经被你的啥服务器给用了

你得自己提供login solver

**Comment by disymayufei** [comment]
> 你stdin已经被你的啥服务器给用了
> 
> 你得自己提供login solver

我需要怎么创建一个login solver？

**Comment by MrXiaoM** [comment]
> 我需要怎么创建一个login solver？

抄[在 jvm 的默认实现](https://github.com/mamoe/mirai/blob/dev/mirai-core-api/src/jvmMain/kotlin/utils/LoginSolver.jvm.kt)，登录前修改机器人配置(BotConfiguration)的loginSolver

**Comment by Karlatemp** [comment]
https://docs.mirai.mamoe.net/Bots.html#%E9%87%8D%E8%A6%81%E9%85%8D%E7%BD%AE

你为什么不看看文档

**Comment by disymayufei** [comment]
> https://docs.mirai.mamoe.net/Bots.html#%E9%87%8D%E8%A6%81%E9%85%8D%E7%BD%AE
> 
> 你为什么不看看文档

有看过，但是在java下，继承LoginSolver类后，似乎无法重写onSolveDeviceVerification方法，导致无法处理手机验证码部分

![image](https://user-images.githubusercontent.com/72013933/205320376-37886cf7-876b-45f0-9e6d-6bc4908e3d44.png)

这是IDEA下能看到的所有方法，其中并没有onSolveDeviceVerification
