### ISSUE TITLE
建议Mirai Console 插件增加对 IDEA22.3 版本的支持

### ISSUE THREAD

**Issue by ShiinaKin** [mamoe/mirai#2372]
如图所示，只兼容22.2.x以下版本
![Snipaste_2022-12-02_23-39-20.jpg](https://s2.loli.net/2022/12/02/Q1Ac4F3qLgoypHk.jpg)

**Comment by Him188** [comment]
Fixed by eb0891fe24a80d46cfd241b8a0bad054f91f093e

新版本只支持 2022.3 + Kotlin 1.7.20 (因为 2022.3 捆绑 1.7.20)

**Comment by Him188** [comment]
https://plugins.jetbrains.com/plugin/15094-mirai-console/versions/stable/269682
