### ISSUE TITLE
文档中contentToString()的注释似乎有错误

### ISSUE THREAD

**Issue by MrY-Cat** [mamoe/mirai#2373]
### 问题描述

![image](https://user-images.githubusercontent.com/76583155/205418010-86709a2b-b0a0-4994-85c1-d745bfec3514.png)

如图，根据描述，At()调用contentToString()将被转化为"@群名片"，但经过test发现实际转化的是"@qq"，测试结果如下（测试代码贴在系统日志了）：
![image](https://user-images.githubusercontent.com/76583155/205418103-086513fc-78d6-401a-8dd9-4301518f64f4.png)

可见无论是At.contentToString()或者At.content，返回字符串均为"@qq"，要伪造假艾特字符串还是只能用"@"+group.getMember(MasterID)?.nameCardOrNick

### 复现

test一下就好

### mirai-core 版本

2.13.0-M1

### bot-protocol

ANDROID_PAD

### 系统日志

```text
suspend fun test5(group:Group,name:String="At(ID).content")
{
    group.sendMessage("测试${name}开始")
    group.sendMessage(At(MasterID))
    group.sendMessage(At(MasterID).content)
    group.sendMessage(At(MasterID).contentToString())
    group.sendMessage("@"+group.getMember(MasterID)?.nameCardOrNick)
    group.sendMessage("测试${name}完毕")
}
```

**Comment by MrXiaoM** [comment]
[At](https://github.com/mamoe/mirai/blob/dev/mirai-core-api/src/commonMain/kotlin/message/data/At.kt#L49-L49)本身就只存了被at的人的qq号，你还想 contentToString 能取到群名片就是奢望。

要获取与QQ客户端类似的格式应当用`At.getDisplay(Group)`

**Comment by MrY-Cat** [comment]
> 

我也觉得这不可能，所以才说这个注释有误

**Comment by cssxsh** [comment]
> [At](https://github.com/mamoe/mirai/blob/dev/mirai-core-api/src/commonMain/kotlin/message/data/At.kt#L49-L49)本身就只存了被at的人的qq号，你还想 contentToString 能取到群名片就是奢望。
> 
> 要获取与QQ客户端类似的格式应当用`At.getDisplay(Group)`

一定条件下是可以的
例如 `MessageChain` 里的 `At` 可以根据 `MessageSource` 获取上下文(群) 然后 转成群名片

单个 `At` 当然不行

**Comment by LaoLittle** [comment]
> [At](https://github.com/mamoe/mirai/blob/dev/mirai-core-api/src/commonMain/kotlin/message/data/At.kt#L49-L49)本身就只存了被at的人的qq号，你还想 contentToString 能取到群名片就是奢望。
> 
> 要获取与QQ客户端类似的格式应当用`At.getDisplay(Group)`

文档确实有问题
