### ISSUE TITLE
转发消息中出现`<>`时无法加载

### ISSUE THREAD

**Issue by 4o4E** [mamoe/mirai#2386]
### 问题描述

mirai构建并发送的转发消息包含`<>`时客户端无法正常加载

下图是用mirai发送的

![](https://user-images.githubusercontent.com/58851040/206835914-19d2a19d-e0e3-41fb-9cf1-d122904c4776.png)

下图是用客户端转发的

![](https://user-images.githubusercontent.com/58851040/206835775-5c420f84-5dc6-4c17-8d31-87a6b80ab509.png)

转发用qq客户端发送的包含`<>`的转发消息时，消息预览会变成

![](https://user-images.githubusercontent.com/58851040/206835800-42680fa1-83ad-45c4-9786-fd6ab42d1edd.png)

### 复现

构建包含`<>`的转发消息并发送

发送别人发送的转发消息

```kotlin
event.message.forEach {
    if (it is ForwardMessage) event.sendMessage(it)
}
```

### mirai-core 版本

2.13.2

### bot-protocol

IPAD

**Comment by cssxsh** [comment]
https://github.com/mamoe/mirai/issues/2241

这个问题我提过了
