### ISSUE TITLE
群聊中合并消息能发出但不被他人接收

### ISSUE THREAD

**Issue by MrY-Cat** [mamoe/mirai#2391]
### 问题描述

**1.风控表现**：机器人在任何群聊内发出合并消息（无论机器人发的还是手动上号发）可以发出，但其他人看不到，控制台也可以看到正常的发出消息的提示，持续约一小时整后自动解除。发送其他类型消息（文本、图片、表情等）不受影响。
**2.触发原因**：具体未知，触发前机器人曾有如下操作：
**改了密码**并删了device.json，更新后重新运行，**向往常一样**在所有群（20个左右）**随机间隔10-30秒广播合并转发的更新内容（修改了其summary）**。
但往常历次更新也是如此操作的，首次出现这种风控，唯一的区别是这次更新前修改了密码。间隔的更新广播后面大概几个群的合并消息已经看不见了，出现了风控。

### 复现

未知，下次更新前不改密码，再看看会不会发生。

### mirai-core 版本

2.13.0-M1

### bot-protocol

ANDROID_PAD

### 补充信息

重启bot、删除device.json后重启，暂停bot20分钟并删除device.json后重启 均无法提前结束该风控状态。

不知道有没有什么好办法可以提前结束该风控状态，或者退而求其次能检测出这种状态以便于下次发生时用文字提示等等

**Comment by MrY-Cat** [comment]
时隔一周，向往常一样在所有群（20个左右）随机间隔10-30秒广播合并转发的周结算（修改了其summary），又出现了，
依然没有什么办法解决，只能干等着一个小时，但至少排除了改密码是触发因素

**Comment by MrY-Cat** [comment]
这次是不足55分钟自动解除

**Comment by Him188** [comment]
这我们也没有办法

**Comment by MrY-Cat** [comment]
> 这我们也没有办法

群消息有没有那种回执，或许能判断消息是不是真正被发出

**Comment by Him188** [comment]
有，mirai目前是收到回执后 `sendMessage`才会返回的，也就是你这种情况是服务器发了回执

**Comment by MrY-Cat** [comment]
> 

这种情况的回执会不会和正常发出的有不同
