### ISSUE TITLE
控制台读到EOF后关闭，是特性还是BUG？

### ISSUE THREAD

**Issue by aleck099** [mamoe/mirai#2394]
在mirai-console按下Ctrl+D（在Windows下是Ctrl+Z）后控制台停止接收输入，但程序仍在运行
是刻意的设计还是bug？
改为退出程序或重新启动控制台是否会更好？

**Comment by Karlatemp** [comment]
因为有的用户会直接以服务启动，这种启动方式是没有input的

如果你需要中断运行请使用 Ctrl C
