### ISSUE TITLE
Android环境下gradle依赖mirai报错

### ISSUE THREAD

**Issue by kagg886** [mamoe/mirai#2402]
### 问题描述

引入并重新刷新项目并未被打断，只是报了一个黄
![image](https://user-images.githubusercontent.com/68730049/208857167-34302387-8648-4ad5-a52b-c7d55196156e.png)
但重新构建时报红
![image](https://user-images.githubusercontent.com/68730049/208857466-c6d06828-253f-4ef3-acb4-cac04d2ad154.png)

### 复现

    implementation("net.mamoe:mirai-core-android:2.13.2") {
        exclude module: "net.mamoe:mirai-core-api"
        exclude module: "net.mamoe:mirai-core-utils"

    }
    implementation("net.mamoe:mirai-core-api-android:2.13.2") {
        exclude module: "net.mamoe:mirai-core-utils"
    }
    implementation("net.mamoe:mirai-core-utils-android:2.13.2")

### mirai-core 版本

2.13.2

### bot-protocol

ANDROID_PHONE

### 系统日志

```text
在补充信息的 log.txt中
```

### 补充信息

[log.txt](https://github.com/mamoe/mirai/files/10275986/log.txt)

**Comment by cssxsh** [comment]
请检查 NDK 版本

**Comment by kagg886** [comment]
> 请检查 NDK 版本

问题是，我没配置过NDK
应该是我没装过NDK

**Comment by kagg886** [comment]
![image](https://user-images.githubusercontent.com/68730049/209074465-f406c751-768d-4dbf-8125-a04f59f84bad.png)

**Comment by Him188** [comment]
试试只添加依赖：
```kotlin
implementation("net.mamoe:mirai-core:2.13.2")
```
这个我测试过在我机器上是可以用

**Comment by kagg886** [comment]
> 试试只添加依赖：
> 
> ```kotlin
> implementation("net.mamoe:mirai-core:2.13.2")
> ```
> 
> 这个我测试过在我机器上是可以用

问题是，我就是如此引入不可以，然后查了issue后改成这样的x
![image](https://user-images.githubusercontent.com/68730049/209456652-e3e1f7a3-8829-4f03-bd16-fee43e0bab12.png)
[新建 文本文档.txt](https://github.com/mamoe/mirai/files/10299417/default.txt)

**Comment by StageGuard** [comment]
给你个参考
```kotlin
runtimeOnly("net.mamoe:mirai-core-android:$mirai_version") {
    exclude module: 'atomicfu', group: 'org.jetbrains.kotlinx'
}
api("net.mamoe:mirai-core-api-android:$mirai_version")
implementation("net.mamoe:mirai-core-utils-android:$mirai_version")
```

**Comment by Karlatemp** [comment]
添加 `org.jetbrains.kotlin.android` 插件 或

```gradle

configurations.all {
    attributes {
        attribute(Attribute.of("org.jetbrains.kotlin.platform.type", String.class), "android")
    }
}

```

**Comment by kagg886** [comment]
> 添加 `org.jetbrains.kotlin.android` 插件 或
> 
> ```groovy-gradle
> configurations.all {
>     attributes {
>         attribute(Attribute.of("org.jetbrains.kotlin.platform.type", String.class), "androidJvm")
>     }
> }
> ```

正解，解决了，谢谢qaq

**Comment by ObcbO** [comment]
有大佬能帮忙看下吗（
https://mirai.mamoe.net/topic/2233/gradle%E5%BC%95%E5%85%A5%E4%BE%9D%E8%B5%96%E9%94%99%E8%AF%AF/3

**Comment by Him188** [comment]
@ObcbO 试试 预览版本号: 2.15.0-dev-85 在 https://github.com/mamoe/mirai/blob/dev/docs/UsingSnapshots.md 查看如何使用预览版本

**Comment by ObcbO** [comment]
> @ObcbO 试试 预览版本号: 2.15.0-dev-85 在 https://github.com/mamoe/mirai/blob/dev/docs/UsingSnapshots.md 查看如何使用预览版本

最新版2.15.0-M1还是没有解决
