### ISSUE TITLE
群昵称/群名片修改后必须发言一次才能触发修改

### ISSUE THREAD

**Issue by LenorEric** [mamoe/mirai#2404]
### 问题描述

我使用的是 mirai-api-http v2.5.2，http 协议
有人在 issue 中提出，**当用户修改群名片后，需要发言一次，mirai 才能检测到这样的修改**
我也遇到了同样的问题。除此之外，当用户将群名片从 b 修改为 a 时，如果这次修改没有被检测到，那么此时再修改其群名片为 b，这次修改会被丢弃。
但是我看其他人的issue，他们**似乎均表示存在一种方法（除了重新登录 bot）可以强制检测这样的修改**（检测整个群的群员资料或群名片）（主要是 #1527 #563 #1570）
其中提到了 实现了查询成员资料 https://github.com/mamoe/mirai/issues/563#issuecomment-767486565
但我尝试了 mirai-api-http 中的
获取群成员列表 [GET] /memberList，也就是遍历读取所有群成员的信息
获取群成员资料 [GET] /memberProfile，也就是读取特定某个群成员的资料卡
获取群员资料 [GET] /memberInfo，也就是读取特定某个群成员的群信息（主要包括群名片和群头衔）
但最终结果是获得到的群名片依然是修改前的结果（同时也没有触发 Event: MemberCardChangeEvent）

此外我也留意到了，重启 bot 尽管不会触发 Event: MemberCardChangeEvent 但是的确能检测到群名片的更新（即便那个人没有发言）
我想询问的是，**是否有任何一种方法能够在某个人不发言的情况下，主动探测到特定的某个群的某个人的群名片的修改，代价（略）小于重新登录 bot？**
又或者是我 mirai-api-http 的配置有误？我看到某些 issue 中提到了清除缓存，但是我没有找到类似的操作，此外似乎这个缓存和这个问题无关。https://github.com/project-mirai/mirai-api-http/issues/487#issuecomment-950862254
又或者其实已经有这样的方法了，但是 mirai-api-http 中没有提供对应的操作？
又或者是 mirai-api-http 中某个方法的实现有误，我应当上报 mirai-api-http？

### 复现

群昵称/群名片修改后必须发言一次才能触发修改

### mirai-core 版本

2.12.1

### bot-protocol

ANDROID_PAD

### 其他组件版本

 mirai-api-http v2.5.2，http 协议

**Comment by LenorEric** [comment]
需要这个功能的场景是，在很多情况下，我希望 bot 可以维护群内的群昵称不发生改变或者符合某种格式
我希望 bot 可以及时探测到群昵称的变化，或者可以周期性地主动探测这种变化（如果开销比较大）

毕竟等某个人发言或者重启 bot，花费的时间肯定远超于向服务器索取刷新，当然更重要的是重启 bot 无法仅通过 MAH 操作，不然也是一种可接受的解决方案。

**Comment by Him188** [comment]
是这样的，服务器不会发改名事件，所以mirai也没法知道。

**Comment by Him188** [comment]
可以实现强制刷新群成员列表 ，参考
https://github.com/mamoe/mirai/issues/1527#issuecomment-950982484

**Comment by LenorEric** [comment]
如果我没有理解错的话，https://github.com/mamoe/mirai/issues/1527#issuecomment-950982484 的意思是，mirai-api-http（MAH） 的作者表示，是 mirai-core 没有提供强制刷新列表的 api
我不是很擅长 java/kotlin，但是我简单阅读了一下 MAH 的代码，发现它提供的 获取群成员列表 [GET] /memberList 方法调用的是 mirai-core api 中的 getGroupOrFail。它得到的群成员列表中，群成员的群名片仍然是需要发言一次才能触发修改的（与事件同步刷新），并非强制刷新。
请问 mirai-core 是否提供了别的某个 api 可以强制刷新群成员列表并读取相关信息，只是 MAH 没有提供对这个 api 的支持？
还是 mirai-core 中没有提供这样的 api？

我简单阅读了一下手册，它提供了 getRawGroupMemberList 这个 api，但是这似乎不是一个 bot api 而是一个底层 api（LowLevelApiAccessor)。
请问您指的强制刷新群成员列表 api 是否是这个？如果是的话，能否请求将它封装成 bot api？我不太了解 java/kotlin，不知道是否这样的底层 api 不方便插件支持。

**Comment by sandtechnology** [comment]
> 如果我没有理解错的话，[#1527 (comment)](https://github.com/mamoe/mirai/issues/1527#issuecomment-950982484) 的意思是，mirai-api-http（MAH） 的作者表示，是 mirai-core 没有提供强制刷新列表的 api 我不是很擅长 java/kotlin，但是我简单阅读了一下 MAH 的代码，发现它提供的 获取群成员列表 [GET] /memberList 方法调用的是 mirai-core api 中的 getGroupOrFail。它得到的群成员列表中，群成员的群名片仍然是需要发言一次才能触发修改的（与事件同步刷新），并非强制刷新。 请问 mirai-core 是否提供了别的某个 api 可以强制刷新群成员列表并读取相关信息，只是 MAH 没有提供对这个 api 的支持？ 还是 mirai-core 中没有提供这样的 api？
> 
> 我简单阅读了一下手册，它提供了 getRawGroupMemberList 这个 api，但是这似乎不是一个 bot api 而是一个底层 api（LowLevelApiAccessor)。 请问您指的强制刷新群成员列表 api 是否是这个？如果是的话，能否请求将它封装成 bot api？我不太了解 java/kotlin，不知道是否这样的底层 api 不方便插件支持。

事实上这应该是 mirai-api-http 插件的工作，之所以为底层api是因为api非常原始

**Comment by LenorEric** [comment]
> 

好的，我大概懂了。那我会转述 MAH。
