### ISSUE TITLE
提示QQ版本过低，无法登陆账号

### ISSUE THREAD

**Issue by blockman3063** [mamoe/mirai#2405]
### 问题描述

<img width="855" alt="image" src="https://user-images.githubusercontent.com/120381304/209254314-1f3673eb-fada-42ce-a07d-83050f962b88.png">

### 复现

不清楚如何复现，之前好好的，重启就不行了，手机登QQ也没有被冻结

### mirai-core 版本

2.1.2

### bot-protocol

ANDROID_PHONE

**Comment by kinhirozane** [comment]
复述问题，昨天还没事，今天提示QQ版本过低，mirai-core版本2.13.2

**Comment by blockman3063** [comment]
az我把mcl和core的版本搞混了

**Comment by 4o4E** [comment]
同样遇到了qq版本过低的问题，在使用[cssxsh/mirai-device-generator](https://github.com/cssxsh/mirai-device-generator)的情况下多次尝试删除并重新生成设备信息，仍然会提示`code=235, title=温馨提示, message=当前QQ版本过低，请升级至最新版本后再登录。点击进入下载页面`

core版本`2.13.2`

使用的协议是`IPAD`

心跳类型`STAT_HB`

**Comment by zhaodice** [comment]
> 同样遇到了qq版本过低的问题，在使用[cssxsh/mirai-device-generator](https://github.com/cssxsh/mirai-device-generator)的情况下多次尝试删除并重新生成设备信息，仍然会提示`code=235, title=温馨提示, message=当前QQ版本过低，请升级至最新版本后再登录。点击进入下载页面`
> 
> core版本`1.13.2`
> 
> 使用的协议是`IPAD`
> 
> 心跳类型`STAT_HB`

1.x版本早就不维护了

**Comment by 4o4E** [comment]
> > 同样遇到了qq版本过低的问题，在使用[cssxsh/mirai-device-generator](https://github.com/cssxsh/mirai-device-generator)的情况下多次尝试删除并重新生成设备信息，仍然会提示`code=235, title=温馨提示, message=当前QQ版本过低，请升级至最新版本后再登录。点击进入下载页面`
> > core版本`1.13.2`
> > 使用的协议是`IPAD`
> > 心跳类型`STAT_HB`
> 
> 1.x版本早就不维护了

写错了

**Comment by Him188** [comment]
@Karlatemp 2.14已经实现了登录失败删cache，确认？

**Comment by Karlatemp** [comment]
> @Karlatemp 2.14已经实现了登录失败删cache，确认？

不，我目前只写了配置变化删除cache，还没写登录失败删除cache

**Comment by wuhongzei** [comment]
一样的问题，换了Sakura Login Helper也不行,弹出链接复制到手机滑动验证完在复制上去就报版本过旧
`core-1.13.2` `protocal ANDROID_PAD/IPAD`换协议没用

**Comment by zhaodice** [comment]
> @Karlatemp 2.14已经实现了登录失败删cache，确认？

我记得我早就实现了删cache，也没用啊…

**Comment by MR-XieXuan** [comment]
同

**Comment by MR-XieXuan** [comment]
同

**Comment by MR-XieXuan** [comment]
我把登陆设备换成 IPAD 然后删除了登陆信息后重新登陆就好了

**Comment by wuhongzei** [comment]
> 我把登陆设备换成 IPAD 然后删除了登陆信息后重新登陆就好了

确实，换device.json登录过个验证码就好了

**Comment by liaozhangsheng** [comment]
问题已解决，删掉bot文件夹里的账号再重新登录一下就就行了

**Comment by MR-XieXuan** [comment]
所以为什么不close

**Comment by zhaodice** [comment]
怀疑可能是触发风控，有新的验证方式需要新版本?暂时不确定

**Comment by aaa-legend** [comment]
在登录失败几次后现在需要短信验证，怎么办？

**Comment by MR-XieXuan** [comment]
> 在登录失败几次后现在需要短信验证，怎么办？

那就验证咯 @aaa-legend

**Comment by aaa-legend** [comment]
短信验证显示短信发送失败

**Comment by Him188** [comment]
@aaa-legend 错误是什么

**Comment by aaa-legend** [comment]
@Him188 在发送界面没有显示手机号，但QQ号显然已经绑定了手机号，我换了个号以后在发送界面正常显示要发送号码的手机号并成功发送登录
![image](https://user-images.githubusercontent.com/65488242/209742158-5ea65aa9-ac2d-45b4-ab78-415c321ce797.png)

**Comment by 2404169797** [comment]
同样遇到了qq版本过低的问题，在使用[cssxsh/mirai-device-generator](https://github.com/cssxsh/mirai-device-generator)的情况下多次尝试删除并重新生成设备信息，仍然会提示code=235, title=温馨提示, message=当前QQ版本过低，请升级至最新版本后再登录。点击进入下载页面

core版本2.13.2

使用的协议是IPAD

心跳类型STAT_HB

**Comment by dragon0629** [comment]
不能关闭啊，这明显还是属于有一些情况下无法过滑块。而且是预期之外的。

**Comment by ieew** [comment]
遇到了同样的问题，提示版本过低，在手动删除 cache 和 device.json 之后就可以正常登录了。

核心版本：2.13.2
使用的协议是：IPAD
心跳类型：STAT_HB
