### ISSUE TITLE
无法连接到mirai。请检查mirai-api-http是否启动，地址与端口是否正确

### ISSUE THREAD

**Issue by FlyingMuyu** [mamoe/mirai#2406]
### 问题描述

无法连接到mirai。请检查mirai-api-http是否启动，地址与端口是否正确

### 复现

更改了端口重启了服务器，关闭了不必要的程序

### mirai-core 版本

2.8.2

### bot-protocol

ANDROID_PHONE

**Comment by Karlatemp** [comment]
防火墙，自己用 curl 检查连通性

**Comment by YuanyiZhezhi11** [comment]
> 防火墙，自己用 curl 检查连通性

请问2要怎么做，我不太会抱歉
