### ISSUE TITLE
替换 MessageSource 的 id 为 sequence id

### ISSUE THREAD

**Issue by jqqqqqqqqqq** [mamoe/mirai#241]
QQ 消息的 Sequence ID是连续值，可以用于定位消息（在解析quote的时候十分有用），例如希望定位到原始消息所处的位置，并进行关联操作（每条消息对应一个实体，包含相应属性，由插件管理，并在回复时提取被回复消息的属性），并且无论任何情况都不为0。

Random ID除了不能确定消息先后顺序基本与Sequence ID等价，但有时为0。

**Comment by Him188** [comment]
sequence id并不是连续值
并且sequence id并不一定能拿到
能拿到也不是立即能拿到

**Comment by jqqqqqqqqqq** [comment]
也可以生成mirai自己的seq id，不一定需要与服务器严格相同
