### ISSUE TITLE
升级2.13.x后类全部找不到

### ISSUE THREAD

**Issue by WutzuBert** [mamoe/mirai#2412]
### 问题描述

build.gradle将mirai-core版本升级至2.13.x后
更新索引IDEA显示所有关于Mirai-core的类全部找不到

### 复现

在build.gradle中升级Mirai-core版本至2.13.x
更新索引
IDEA问题检测  Mirai-core里的类全部没有
import找不到类

### mirai-core 版本

2.13.x

### bot-protocol

ANDROID_PHONE

**Comment by WutzuBert** [comment]
![image](https://user-images.githubusercontent.com/86144069/210287863-a95dc683-3099-4416-b086-9b961adcceed.png)

**Comment by cssxsh** [comment]
请给出具体的 `build.gradle` 内容

**Comment by cssxsh** [comment]
请给出具体的 `build.gradle` 内容

**Comment by Karlatemp** [comment]
你确定 gradle 已经完成依赖解析了吗
你的 idea 的 External Libraries 确定有 mirai-core-api 的依赖吗

是 java 项目还是 kotlin 项目

**Comment by WutzuBert** [comment]
![image](https://user-images.githubusercontent.com/86144069/210291216-e8bf1e6e-e1e8-4aa0-8bc4-04d519a9bc26.png)
以下为build.gradle
```
plugins {
    id 'org.jetbrains.kotlin.jvm' version '1.5.30' // 确保添加 Kotlin
    id 'com.github.johnrengelman.shadow' version '2.0.4'
}
apply plugin: 'java'

group = 'top.berthua'
version = '11.45.14'

repositories {
    mavenCentral()
    maven {
        name = 'sonatype'
        url = 'https://oss.sonatype.org/content/groups/public/'
    }
    maven { url "https://maven.aliyun.com/repository/public" }
    maven { url 'https://www.jitpack.io' }
}



dependencies {
    compileOnly 'net.md-5:bungeecord-api:1.16-R0.4'
    implementation 'net.mamoe:mirai-core:2.13.2'
    implementation 'com.alibaba:fastjson:2.0.17'
}

def targetJavaVersion = 8
java {
    def javaVersion = JavaVersion.toVersion(targetJavaVersion)
    sourceCompatibility = javaVersion
    targetCompatibility = javaVersion
    if (JavaVersion.current() < javaVersion) {
        toolchain.languageVersion = JavaLanguageVersion.of(targetJavaVersion)
    }
}

tasks.withType(JavaCompile).configureEach {
    if (targetJavaVersion >= 10 || JavaVersion.current().isJava10Compatible()) {
        options.release = targetJavaVersion
    }
    options.encoding = "UTF-8"
}

processResources {
    def props = [version: version]
    inputs.properties props
    expand props
    filteringCharset 'UTF-8'
    filesMatching('bungee.yml') {
        expand props
    }
}
shadowJar {
    manifest.attributes.put("Implementation-Version", archiveVersion)
    manifest.attributes.put("Main-Class", "com.transsion.hprofparse.main.HprofAgent")
}
```

**Comment by WutzuBert** [comment]
> 你确定 gradle 已经完成依赖解析了吗 你的 idea 的 External Libraries 确定有 mirai-core-api 的依赖吗
> 
> 是 java 项目还是 kotlin 项目

java项目

**Comment by Karlatemp** [comment]
尝试更新 idea 的 kotlin 插件 和 `IDEA 工具栏 > File > Invalidate Caches...`

**Comment by WutzuBert** [comment]
> 尝试更新 idea 的 kotlin 插件 和 `IDEA 工具栏 > File > Invalidate Caches...`

kotlin插件已为最新
Caches全清
但仍然找不到类

**Comment by cssxsh** [comment]
> id 'org.jetbrains.kotlin.jvm' version '1.5.30'

升级一下 kotlin 版本 你可以试试 1.7.10

**Comment by ywyself** [comment]
尝试升级一下idea的版本

**Comment by Him188** [comment]
Gradle 用的 Kotlin 版本太旧了, 2.13 需要 1.7.0 及以上

**Comment by wuhongzei** [comment]
> Gradle 用的 Kotlin 版本太旧了, 2.13 需要 1.7.0 及以上

希望能够更新一下mirai-helloworld的gradle.build
很多人(me)出这个问题是从那边复制的
