### ISSUE TITLE
bot 修改自己群名称时出错

### ISSUE THREAD

**Issue by wyapx** [mamoe/mirai#242]
## 如何复现

bot在修改自己的群名称时出错，http-api返回权限不足，如下图  
![II((9OZO$(2)JD2J@0FMO`B](https://user-images.githubusercontent.com/26220729/79638192-ee48c980-81b6-11ea-8351-bba417a9b5bc.png)  
console返回了一段信息：  
![2ESS{Q{K517X5V1 Z(GHQ@2](https://user-images.githubusercontent.com/26220729/79638205-fef93f80-81b6-11ea-97b8-b72c37b8c5c1.png)

**Comment by Him188** [comment]
经检查修改并没有问题. 不过可以支持一下这个事件
