### ISSUE TITLE
Http Adapter 群文件上传功能，每次上传两次

### ISSUE THREAD

**Issue by Apicer** [mamoe/mirai#2422]
### 问题描述

使用mcl搭配mirai-api-http-v2.7.1.mirai2.jar使用，java使用上传群文件功能时，http请求明明只发送了一次，但是群文件确上传了两次

### 复现

> 上传文件工具类

`import lombok.RequiredArgsConstructor;

import java.io.*;
import java.nio.charset.Charset;
import java.nio.charset.StandardCharsets;
import java.util.*;
import java.util.function.BiConsumer;

public class MultipartWriter {

    private static final Charset DEFAULT_CHARSET = StandardCharsets.UTF_8;
    private static final byte[] FIELD_SEP = ": ".getBytes(StandardCharsets.ISO_8859_1);
    private static final byte[] CR_LF = "\r\n".getBytes(StandardCharsets.ISO_8859_1);
    private static final String TWO_HYPHENS_TEXT = "--";
    private static final byte[] TWO_HYPHENS = TWO_HYPHENS_TEXT.getBytes(StandardCharsets.ISO_8859_1);
    private static final String CONTENT_DISPOSITION_KEY = "Content-Disposition";
    private static final String CONTENT_TYPE_KEY = "Content-Type";
    private static final String DEFAULT_CONTENT_TYPE = "multipart/form-data; boundary=";
    private static final String DEFAULT_BINARY_CONTENT_TYPE = "application/octet-stream";
    private static final String DEFAULT_TEXT_CONTENT_TYPE = "text/plain;charset=UTF-8";
    private static final String DEFAULT_CONTENT_DISPOSITION_VALUE = "form-data; name=\"%s\"";
    private static final String FILE_CONTENT_DISPOSITION_VALUE = "form-data; name=\"%s\"; filename=\"%s\"";

    private final Map<String, String> headers = new HashMap<>(8);
    private final List<AbstractMultipartPart> parts = new ArrayList<>();
    private final String boundary;

    private MultipartWriter(String boundary) {
        this.boundary = Objects.isNull(boundary) ? TWO_HYPHENS_TEXT +
                UUID.randomUUID().toString().replace("-", "") : boundary;
        this.headers.put(CONTENT_TYPE_KEY, DEFAULT_CONTENT_TYPE + this.boundary);
    }

    public static MultipartWriter newMultipartWriter(String boundary) {
        return new MultipartWriter(boundary);
    }

    public static MultipartWriter newMultipartWriter() {
        return new MultipartWriter(null);
    }

    public MultipartWriter addHeader(String key, String value) {
        if (!CONTENT_TYPE_KEY.equalsIgnoreCase(key)) {
            headers.put(key, value);
        }
        return this;
    }

    public MultipartWriter addTextPart(String name, String text) {
        parts.add(new TextPart(String.format(DEFAULT_CONTENT_DISPOSITION_VALUE, name), DEFAULT_TEXT_CONTENT_TYPE, this.boundary, text));
        return this;
    }

    public MultipartWriter addBinaryPart(String name, byte[] bytes) {
        parts.add(new BinaryPart(String.format(DEFAULT_CONTENT_DISPOSITION_VALUE, name), DEFAULT_BINARY_CONTENT_TYPE, this.boundary, bytes));
        return this;
    }

    public MultipartWriter addFilePart(String name, File file) {
        parts.add(new FilePart(String.format(FILE_CONTENT_DISPOSITION_VALUE, name, file.getName()), DEFAULT_BINARY_CONTENT_TYPE, this.boundary, file));
        return this;
    }

    private static void writeHeader(String key, String value, OutputStream out) throws IOException {
        writeBytes(key, out);
        writeBytes(FIELD_SEP, out);
        writeBytes(value, out);
        writeBytes(CR_LF, out);
    }

    private static void writeBytes(String text, OutputStream out) throws IOException {
        out.write(text.getBytes(DEFAULT_CHARSET));
    }

    private static void writeBytes(byte[] bytes, OutputStream out) throws IOException {
        out.write(bytes);
    }

    interface MultipartPart {

        void writeBody(OutputStream os) throws IOException;
    }

    @RequiredArgsConstructor
    public static abstract class AbstractMultipartPart implements MultipartPart {

        protected final String contentDispositionValue;
        protected final String contentTypeValue;
        protected final String boundary;

        protected String getContentDispositionValue() {
            return contentDispositionValue;
        }

        protected String getContentTypeValue() {
            return contentTypeValue;
        }

        protected String getBoundary() {
            return boundary;
        }

        public final void write(OutputStream out) throws IOException {
            writeBytes(TWO_HYPHENS, out);
            writeBytes(getBoundary(), out);
            writeBytes(CR_LF, out);
            writeHeader(CONTENT_DISPOSITION_KEY, getContentDispositionValue(), out);
            writeHeader(CONTENT_TYPE_KEY, getContentTypeValue(), out);
            writeBytes(CR_LF, out);
            writeBody(out);
            writeBytes(CR_LF, out);
        }
    }

    public static class TextPart extends AbstractMultipartPart {

            private final String text;

            public TextPart(String contentDispositionValue,
                            String contentTypeValue,
                            String boundary,
                            String text) {
                super(contentDispositionValue, contentTypeValue, boundary);
                this.text = text;
            }

        @Override
        public void writeBody(OutputStream os) throws IOException {
            os.write(text.getBytes(DEFAULT_CHARSET));
        }

        @Override
        protected String getContentDispositionValue() {
            return contentDispositionValue;
        }

        @Override
        protected String getContentTypeValue() {
            return contentTypeValue;
        }
    }

    public static class BinaryPart extends AbstractMultipartPart {

        private final byte[] content;

        public BinaryPart(String contentDispositionValue,
                          String contentTypeValue,
                          String boundary,
                          byte[] content) {
            super(contentDispositionValue, contentTypeValue, boundary);
            this.content = content;
        }

        @Override
        public void writeBody(OutputStream out) throws IOException {
            out.write(content);
        }
    }

    public static class FilePart extends AbstractMultipartPart {

        private final File file;

        public FilePart(String contentDispositionValue,
                        String contentTypeValue,
                        String boundary,
                        File file) {
            super(contentDispositionValue, contentTypeValue, boundary);
            this.file = file;
        }

        @Override
        public void writeBody(OutputStream out) throws IOException {
            try (InputStream in = new FileInputStream(file)) {
                final byte[] buffer = new byte[4096];
                int l;
                while ((l = in.read(buffer)) != -1) {
                    out.write(buffer, 0, l);
                }
                out.flush();
            }
        }
    }

    public void forEachHeader(BiConsumer<String, String> consumer) {
        headers.forEach(consumer);
    }

    public void write(OutputStream out) throws IOException {
        if (!parts.isEmpty()) {
            for (AbstractMultipartPart part : parts) {
                part.write(out);
            }
        }
        writeBytes(TWO_HYPHENS, out);
        writeBytes(this.boundary, out);
        writeBytes(TWO_HYPHENS, out);
        writeBytes(CR_LF, out);
    }
}`

> http工具类

`import com.alibaba.fastjson.JSON;
import com.winner.contentExtract.utils.constant.Constants;
import com.winner.contentExtract.utils.text.Convert;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import sun.net.www.protocol.http.HttpURLConnection;

import javax.net.ssl.*;
import java.io.*;
import java.net.*;
import java.nio.charset.StandardCharsets;
import java.security.cert.X509Certificate;
import java.util.Map;
import java.util.Objects;

public class HttpUtil {
    private static final Logger log = LoggerFactory.getLogger(HttpUtil.class);

public static String sendFilePost(String url, MultipartWriter multipartWriter) {
        System.out.println("请求开始发送=========================================================");
        StringBuilder result = new StringBuilder();
        try {
            // 打印文本内容
//            DataOutputStream requestPrinter = new DataOutputStream(System.out);
//            multipartWriter.write(requestPrinter);
            log.info("sendPost - {}", url);
            HttpURLConnection connection = (HttpURLConnection) new java.net.URL(url).openConnection();
            connection.setRequestMethod(BasicUtil.REQUEST_METHOD_POST);
            connection.addRequestProperty("Connection", "Keep-Alive");
            // 设置请求头
            multipartWriter.forEachHeader(connection::addRequestProperty);
            connection.setDoInput(true);
            connection.setDoOutput(true);
            connection.setConnectTimeout(10000);
            connection.setReadTimeout(10000);
            DataOutputStream out = new DataOutputStream(connection.getOutputStream());
            // 设置请求体
            multipartWriter.write(out);
            InputStreamReader inputStreamReader = new InputStreamReader(connection.getInputStream(), StandardCharsets.UTF_8);
            BufferedReader reader = new BufferedReader(inputStreamReader);
            String line;
            while (Objects.nonNull(line = reader.readLine())) {
                result.append(line);
            }
            log.info("recv - {}", result);
            reader.close();
            out.close();
            connection.disconnect();
        } catch (ConnectException e) {
            log.error("调用HttpUtils.sendFilePost ConnectException, url=" + url + ",MultipartWriter=" + multipartWriter, e);
        } catch (SocketTimeoutException e) {
            log.error("调用HttpUtils.sendFilePost SocketTimeoutException, url=" + url + ",MultipartWriter=" + multipartWriter, e);
        } catch (IOException e) {
            log.error("调用HttpUtils.sendFilePost IOException, url=" + url + ",MultipartWriter=" + multipartWriter, e);
        } catch (Exception e) {
            log.error("调用HttpsUtil.sendFilePost Exception, url=" + url + ",MultipartWriter=" + multipartWriter, e);
        }
        System.out.println("请求发送结束=========================================================");
        return result.toString();
    }
}`

> 调用方式

`MultipartWriter multipartWriter = MultipartWriter.newMultipartWriter();
        multipartWriter.addTextPart("sessionKey", Convert.toStr(CacheConfig.cache.opsForValue().get("session")))
                .addTextPart("target", Convert.toStr(sendGroup))
                .addTextPart("type", "group")
                .addTextPart("path", "")
                .addFilePart("file", new File(resultUrl));
        String url = MIRAI_API_HTTP.concat("/file/upload");
        String result = HttpUtil.sendFilePost(url, multipartWriter);
        Map<String, Object> resultData = (Map<String, Object>) JSON.parse(result);`

### mirai-core 版本

2.13.2

### bot-protocol

ANDROID_PHONE

### 其他组件版本

mirai-api-http: v2.7.1

**Comment by Apicer** [comment]
`{
    "code":0,
    "msg":"",
    "data":{
        "name":"有没有特别血腥恐怖文章？.txt",
        "id":"/c2737b3b-f1bd-4964-b3a5-b14f70a4b58c",
        "path":"/有没有特别血腥恐怖文章？.txt",
        "parent":{
            "name":"/",
            "id":"/",
            "path":"/",
            "parent":null,
            "contact":{
                "id":663903282,
                "name":"Mirai Robot",
                "permission":"MEMBER"
            },
            "isFile":false,
            "isDictionary":true,
            "isDirectory":true,
            "size":0,
            "sha1":null,
            "md5":null,
            "uploaderId":null,
            "uploadTime":null,
            "lastModifyTime":null,
            "downloadInfo":null
        },
        "contact":{
            "id":663903282,
            "name":"Mirai Robot",
            "permission":"MEMBER"
        },
        "isFile":true,
        "isDictionary":false,
        "isDirectory":false,
        "size":39090,
        "sha1":"ACAF7286F826F255B976923DF277996401229437",
        "md5":"F91A183B14B6A019256245477E3128B7",
        "uploaderId":1398783998,
        "uploadTime":1673318361,
        "lastModifyTime":1673318361,
        "downloadInfo":null
    }
}`


这个是我群文件上传后返回的参数，我看文档示例parent节点为null，而我的不知道为什么有值

**Comment by Him188** [comment]
这是 HTTP API 插件的问题  https://github.com/project-mirai/mirai-api-http/ 

CC @ryoii

**Comment by Apicer** [comment]
@Him188 那我是要把http api插件降版本吗？

**Comment by cssxsh** [comment]
https://github.com/project-mirai/mirai-api-http/pull/675

**Comment by Apicer** [comment]
@cssxsh 这个问题是已经处理好了吗？
