### ISSUE TITLE
安装mirai console gradle插件后的子模块依赖问题问题

### ISSUE THREAD

**Issue by BotarGoquri** [mamoe/mirai#2439]
### 问题描述

当我安装了mirai console的gradle插件以后
如果我在一个模块中像这样添加一个dependency：
```groovy
dependencies {
    implementation project(':somemodule')
}
```
后，无法导入里面的类，但如果是普通的通过maven仓库依赖就没问题，删掉过其他插件，只有安装mirai console插件后才有该问题

### 复现

1. 安装mirai console gradle插件
2. 通过implementation project(':xxx')或compileOnly project(':xxx')依赖一个子模块
3. 无法导入子模块中的类
4. 删去mirai console gradle插件
5. 可以正常的导入子模块之中的类

### mirai-core 版本

2.13.2

### bot-protocol

ANDROID_PHONE

### 系统日志

```text
gradle插件问题
```

### 网络日志

```text
gradle插件问题
```

### 补充信息

gradle插件问题

**Comment by Karlatemp** [comment]
提供 `gradle build --info` 的日志

**Comment by Karlatemp** [comment]
long time no reply
