### ISSUE TITLE
登录失败事件？

### ISSUE THREAD

**Issue by zhaodice** [mamoe/mirai#2445]
看了一下，没有登录失败的事件，因为我希望监听登录失败事件做一些必要的清理工作，目前有两处互相解偶的系统在调用登录接口，如果在两处都写登录失败处理会产生冗余代码

**Comment by zhaodice** [comment]
比如说，我的插件覆盖了
`BotConfiguration.Default.deviceInfo`
其他地方登录则可以直接
`deviceInfo = BotConfiguration.Default.deviceInfo`
但碍于deviceInfo回调限制，其他地方无法得知真实的设备文件路径，因此无法实现device.json文件的清理
而插件也无法得知登录失败事件，也无法清理。

**Comment by cssxsh** [comment]
我觉得为 `mirai-core` 加这个事件没必要

倒是可以考虑给 `mirai-console` 加个 `AutoLoginEvent { Success; Failure; }` 归属于 `ConsoleEvent`

**Comment by zhaodice** [comment]
> 我觉得为 `mirai-core` 加这个事件没必要
> 
> 倒是可以考虑给 `mirai-console` 加个 `AutoLoginEvent { Success; Failure; }` 归属于 `ConsoleEvent`

如果登录调用不是来自console，而是直接在程序主体调用login，也能捕获到吗？

**Comment by cssxsh** [comment]
> 直接在程序主体调用login，也能捕获到吗？

我觉得没必要捕获手动登录行为结果， 
因为如果当对失败的处理本身也有问题的时候，
可以手动登录避免影响

另外如果你觉得自带的手动登录不符合你的要求
你可以自己写一个新的登录指令

**Comment by zhaodice** [comment]
> 因为如果当对失败的处理本身也有问题的时候

我现在是这种结构：
1.A插件实现了`BotConfiguration.Default.deviceInfo`，所以A插件持有`device.json`的真实路径，A插件在调用login函数进行登录的时候，完全OK，失败了删除`device.json`文件就行了
2.另一个B插件（或者程序主体），也调用了login函数，它试图使用由A插件提供的`BotConfiguration.Default.deviceInfo`来设定设备信息，很不幸，登录失败了，但作为这个程序环境，B是无法知道`device.json`的真实路径的，所以无法在登录失败的情况下清理`device.json`文件。

所以解决方法有2个：
1.广播登录失败事件，这样A插件就知道了其他地方也有登录失败，自动帮忙删除`device.json`
2.想办法让B插件允许通过`BotConfiguration.Default.deviceInfo`获得真实的`device.json`路径

**Comment by cssxsh** [comment]
> A插件实现了BotConfiguration.Default.deviceInfo

我有点听不懂

**Comment by zhaodice** [comment]
> > A插件实现了BotConfiguration.Default.deviceInfo
> 
> 我有点听不懂

这么说吧，我实现了一个生成device信息的函数，这个函数会生成device信息并存储于文件之中。
`BotConfiguration.Default.deviceInfo`本质上是一个回调函数，输入一个Bot对象，返回一个device信息对象。
所以我在插件里覆盖了`BotConfiguration.Default.deviceInfo`
这样任何地方调用login函数，我都可以用
`deviceInfo = BotConfiguration.Default.deviceInfo`
来实现统一的设备文件生成逻辑

**Comment by zhaodice** [comment]
`BotConfiguration.Default.deviceInfo`有个问题就是，它只能返回文件内容，无法得知文件到底在哪个路径，导致在登录失败的时候没法干掉这个文件（如果在插件之外），插件虽然知道文件路径，但插件不知道登录失败这件事，插件也无法干掉这个文件。

**Comment by cssxsh** [comment]
首先，在插件里修改 `deviceInfo` 不需要也不应该修改 `BotConfiguration.Default.deviceInfo`
可以使用 `contributeBotConfigurationAlterer`

```
    override fun PluginComponentStorage.onLoad() {
        contributeBotConfigurationAlterer { botId, configuration ->
            configuration.deviceInfo = generator::load
            configuration
        }
    }
```

https://github.com/mamoe/mirai/blob/5232dc6953e0b3564cfc15082f3df70c22c7c562/mirai-console/backend/mirai-console/src/extensions/BotConfigurationAlterer.kt#L25-L37

**Comment by zhaodice** [comment]
> 首先，在插件里修改 `deviceInfo` 不需要也不应该修改 `BotConfiguration.Default.deviceInfo` 可以使用 `contributeBotConfigurationAlterer`
> 
> ```
>     override fun PluginComponentStorage.onLoad() {
>         contributeBotConfigurationAlterer { botId, configuration ->
>             configuration.deviceInfo = generator::load
>             configuration
>         }
>     }
> ```
> 
> https://github.com/mamoe/mirai/blob/5232dc6953e0b3564cfc15082f3df70c22c7c562/mirai-console/backend/mirai-console/src/extensions/BotConfigurationAlterer.kt#L25-L37

喔...但是，用了这种方式，其他地方还是没办法得知真实的设备文件路径吧，设备文件路径仍被`configuration.deviceInfo`内部屏蔽了，无从得知

**Comment by cssxsh** [comment]
> 喔...但是，用了这种方式，其他地方还是没办法得知真实的设备文件路径吧，设备文件路径仍被`configuration.deviceInfo`内部屏蔽了，无从得知

你这个问题是无解的，因为设备文件也不一定要会靠文件存储，他可能拓展有其他方式，
也没必要把 生成和删除 割裂到两个插件中去

设备信息生成和删除 本就应该由同一插件负责

**Comment by zhaodice** [comment]
> > 喔...但是，用了这种方式，其他地方还是没办法得知真实的设备文件路径吧，设备文件路径仍被`configuration.deviceInfo`内部屏蔽了，无从得知
> 
> 你这个问题是无解的，因为设备文件也不一定要会靠文件存储，他可能拓展有其他方式， 也没必要把 生成和删除 割裂到两个插件中去
> 
> 设备信息生成和删除 本就应该由同一插件负责

是啊，如果能广播登录失败事件的话，就可以实现设备的生成和删除由同一个插件负责了，插件只需要监听登录失败，发现有登录失败了，就删除自己生成的设备文件，不行就确实无解了
