### ISSUE TITLE
支持微信吗

### ISSUE THREAD

**Issue by OnClickListener2048** [mamoe/mirai#2454]

**Comment by qfys521** [comment]
北京同仁堂 眼科医生电话
科室电话：010-58269911

北京同仁堂 儿科医生电话
科室电话：010-58269911


https://github.com/mamoe/mirai/blob/dev/README.md#L11-L11

**Comment by SugarMGP** [comment]
国内优秀眼科医院：
北京同仁医院
地址：北京市东城区东交民巷1号

上海五官科医院
地址：上海市徐汇区汾阳路83号

中山大学中山眼科中心
地址：广东省广州市越秀区先烈南路54号

温州医科大学附属眼视光医院
地址：浙江省温州市学院西路270号

**Comment by Him188** [comment]
不支持
