### ISSUE TITLE
ForwardMessage发送后群内不显示

### ISSUE THREAD

**Issue by disymayufei** [mamoe/mirai#2456]
### 问题描述

我不确定这是不是由于我代码写错导致的还是一个bug，但是我确实参考了源码内文档，如果确实是我的错误还望大佬原谅：
我希望是在接收到指定消息后，可以向群内发送一个ForwardMessage，我的代码如下：
    ForwardMessageBuilder helpMesBuilder = new ForwardMessageBuilder(event.getGroup());
    helpMesBuilder.add(1481567451L, "Disy", new PlainText("test"));
    event.getGroup().sendMessage(helpMesBuilder.build());
然而在群内并未收到这条消息
其他的消息（比如单纯的一个PlainText）都是可以正常发送的，唯独这个ForwardMessage不行

### 复现

1. 使用java写出以下代码：
    ForwardMessageBuilder helpMesBuilder = new ForwardMessageBuilder(event.getGroup());
    helpMesBuilder.add(1481567451L, "Disy", new PlainText("test"));
    event.getGroup().sendMessage(helpMesBuilder.build());

2. 运行机器人，并触发以上代码
3. 无任何消息显示

### mirai-core 版本

2.13.4

### bot-protocol

MACOS

### 其他组件版本

None

### 系统日志

```text
日志中无任何显示与报错
```

### 网络日志

```text
日志中无任何显示与报错
```

### 补充信息

在日志中并没有任何报错，且其他类型的消息可以正常发送，唯独ForwardMessage是不行的

**Comment by cssxsh** [comment]
典型风控

**Comment by disymayufei** [comment]
> 典型风控

所以是只能通过换号或者换协议解决嘛？
