### ISSUE TITLE
ForwardMessage中的消息包含“<",">”这两个符号时，消息无法正常发送

### ISSUE THREAD

**Issue by disymayufei** [mamoe/mirai#2461]
### 问题描述

当ForwardMessage中包含大于号或者小于号时，会导致发出的消息直接无法在任何平台显示，其他文本则正常

示例代码如下：
ForwardMessageBuilder mesBuilder1 = new ForwardMessageBuilder(event.getGroup());
mesBuilder1.add(event.getSender(), new PlainText("<"));
event.getGroup().sendMessage(mesBuilder1.build());

ForwardMessageBuilder mesBuilder2 = new ForwardMessageBuilder(event.getGroup());
mesBuilder2.add(event.getSender(), new PlainText("&"));
event.getGroup().sendMessage(mesBuilder2.build());

此时群内只能显示一条转发消息：
![{~G~A6LPR362H))S 3)XGTD](https://user-images.githubusercontent.com/72013933/214754489-98c3120d-7c6e-4e5b-acd4-e349c5612065.png)

即使直接把接收到的ForwardMessage再次发送出去，一旦包含大于号或者小于号，也会发生显示异常：

示例代码如下：
for(Message mes : event.getMessage()){
    if(mes instanceof ForwardMessage){
        event.getGroup().sendMessage(mes);
        return;
    }
}

此时群内结果如下：
![8U5VZ6 `509EBO}WB5QE`MR](https://user-images.githubusercontent.com/72013933/214754754-546ae981-5eba-4d92-83c4-8ff7a7201772.png)

### 复现

复现方式已详细在问题描述中叙述

### mirai-core 版本

2.13.4

### bot-protocol

MACOS

### 其他组件版本

None

### 系统日志

```text
系统日志中无任何报错
```

### 网络日志

```text
网络日志中无任何报错
```

### 补充信息

任何日志中均无任何报错，怀疑是QQ自己的xml解析器在遇到大于号和小于号的时候解析出错，但不确定这一问题能不能从mirai core层面解决，如果这一问题不是mirai的bug，可以关闭我的这个issue

**Comment by Karlatemp** [comment]
#2241, already processed in 2.14.0
