### ISSUE TITLE
添加更多登录方式（如扫码登录），解决手表协议失效

### ISSUE THREAD

**Issue by alongw** [mamoe/mirai#2462]
我的需求非常特殊，
我同时使用着手机QQ、电脑QQ和安卓平板的QQ。但是我又希望我的QQ可以同时运行一个mirai。
mirai目前仅支持手机QQ、电脑QQ、平板QQ、手表QQ（已经失效）
ios手机QQ与安卓手机QQ冲突，windowsQQ、Tim、LinuxQQ、MACOSQQ互相冲突，ipad、AndroidPAD、旧版QQHD互相冲突
这些协议和我正常使用的设备全部冲突，除了手表，我翻阅其他issue的时候得知安卓手表这个协议已经不能使用账号密码登录了，那是否可以支持扫码或是其他方式登录？

**Comment by sandtechnology** [comment]
请自行尝试是否可以使用2.13.4或2.14-RC以手表协议登录 理论上应该是可以的

**Comment by Him188** [comment]
#1281
