### ISSUE TITLE
当访问的图片会301至其他地址的时候 无法发送图片

### ISSUE THREAD

**Issue by huajip** [mamoe/mirai#2469]
### 问题描述

如果访问的图片地址 会随机其他图片地址并301 或 填写的地址是http 但服务器会301至https地址时 图片无法发送

### 复现

发送会301跳转的图片url即可复现

### mirai-core 版本

2.14.0-RC

### bot-protocol

IPAD

### 其他组件版本

Running MiraiConsole v2.14.0-RC, built on 2023-01-18 20:32:50.
Frontend Terminal: version 2.14.0-RC, provided by Mamoe Technologies

Permission Service: Built In Permission Service

Plugins: mirai-device-generator v1.1.3, net.mamoe.mirai-api-http v2.6.2, Silk Converter v0.0.3, MCL Addon v2.1.1

Object Pending Finalization Count: 0
                 committed |  init   |   used   |  max  
    Heap Memory:  178.0MB  | 122.0MB | 128.5MB  | 1.89GB
Non-Heap Memory: 110.62MB  | 7.31MB  | 106.52MB |   -1  

### 系统日志

```text
java.lang.IllegalArgumentException: Unsupported image type (mirai) for ExternalResource net.mamoe.mirai.internal.utils.ExternalResourceImplByFile@34204173, considering use gif/png/bmp/jpg format
```

**Comment by cssxsh** [comment]
如果你是 mirai-api-http 使用者
那你应该先回复至
https://github.com/project-mirai/mirai-api-http/issues

另外建议使用 2.7.1 版本 mirai-api-http
https://github.com/project-mirai/mirai-api-http/releases/tag/v2.7.1

**Comment by huajip** [comment]
将mirai-api-http 从stable-v2 channel内目前最新的 2.6.2
更新至github 内最新的2.7.1后解决 抱歉打扰mirai这边了
