### ISSUE TITLE
mirai-console-intellij问题

### ISSUE THREAD

**Issue by erica-bing** [mamoe/mirai#2471]
### 问题描述

task执行期间发生错误，原因在于mirai-console-intellij被需要，我以为plugin是在idea市场中的Mirai Console插件，但是安装好没用啊,每次刷新都会去maven里面找那个插件，但是没找到就报错。
报错信息有多处
Could not find com.jetbrains.intellij.idea:ideaIC:222.3345-EAP-CANDIDATE-SNAPSHOT。
以及
Caused by: java.lang.NullPointerException: getHeaderField("Location") must not be null(这条错误一直在)

![image](https://user-images.githubusercontent.com/86713070/216093506-df601cac-28df-4eef-aad8-386640e24968.png)
看到这里有说明，但是理解不了。

### 复现

下载的mirai源码压缩包2.13.4，下载完依赖task编译期间发生错误

### mirai-core 版本

2.13.4

### bot-protocol

ANDROID_PHONE

### 系统日志

```text
https://gradle.com/s/d3u2q5rwobqbe
```

### 补充信息

idea是2022.3.2版本，java配置的是17

**Comment by cssxsh** [comment]
> Caused by: java.lang.NullPointerException: getHeaderField("Location") must not be null

说明你网不好，一直下载失败, 这是 mirai-console 子项目的需求，并不必要

你可以在 项目根目录 加一个文件 `local.properties`

内容取
```
projects.mirai-logging.enabled=false
projects.mirai-console.enabled=false
```
关掉不必要的项目加载
·

**Comment by erica-bing** [comment]
> > Caused by: java.lang.NullPointerException: getHeaderField("Location") must not be null
> 
> 说明你网不好，一直下载失败, 这是 mirai-console 子项目的需求，并不必要
> 
> 你可以在 项目根目录 加一个文件 `local.properties`
> 
> 内容取
> 
> ```
> projects.mirai-logging.enabled=false
> projects.mirai-console.enabled=false
> ```
> 
> 关掉不必要的项目加载 ·

感谢，使用此方式可以解决
