### ISSUE TITLE
v0.38.0仅尝试连接某个登录服务器

### ISSUE THREAD

**Issue by dynxer** [mamoe/mirai#248]
## 问题

v0.38.0 在部分特殊的网络环境下，由于无法连接腾讯位于国内的登录服务器并且不会尝试连接其他的服务器而导致登陆失败。

## 如何复现

v0.38.0版本登录时控制台会提示：
`[INFO] [NETWORK] No route to host (Mostly due to no Internet connection). Retrying in 3s...`
通过 tcpdump 可知 mirai 一直在试图连接 `114.221.148.59:14000`，在等待较长时间后（20min）也依然在尝试连接这个IP

而在v0.37.4版本中，在试图连接某个服务器并失败数次后，会尝试 [DefaultServerList](https://github.com/mamoe/mirai/blob/e1c1c35d701e61ab0286162adf496b1396df8e71/mirai-core-qqandroid/src/commonMain/kotlin/net/mamoe/mirai/qqandroid/network/QQAndroidClient.kt#L48) 中的其他服务器

可能与 https://github.com/mamoe/mirai/commit/fa211cab5c56c46cbba248fc01213fa5569c11c1 有关？

**Comment by Him188** [comment]
这...... 我实在不懂如何区分是服务器无法连接还是系统没有网络...他们都是 SocketException

**Comment by Him188** [comment]
目前临时解决办法是重启服务器，重启时会随机连接

**Comment by sandtechnology** [comment]
> 
> 
> 目前临时解决办法是重启服务器，重启时会随机连接

可以尝试以其他方式检测网络（比如靠204服务器）

**Comment by dynxer** [comment]
> 
> 
> 目前临时解决办法是重启服务器，重启时会随机连接

使用重启的方式连接上服务器后，在服务器断开连接的情况下（即 https://github.com/mamoe/mirai/issues/200#issuecomment-609362194 ） mirai-core 尝试重连时又会随机从 [DefaultServerList](https://github.com/mamoe/mirai/blob/e1c1c35d701e61ab0286162adf496b1396df8e71/mirai-core-qqandroid/src/commonMain/kotlin/net/mamoe/mirai/qqandroid/network/QQAndroidClient.kt#L48) 选择一个服务器
看来只能暂时回滚v0.37.4或者更换网络环境
