### ISSUE TITLE
Failed to decode BdhSession

### ISSUE THREAD

**Issue by BIWEA** [mamoe/mirai#2480]
### 问题描述

昨天还能用，今天重新登上qq，登录后一会就跳出java.lang.IllegalStateException: Failed to decode BdhSession

### 复现

因为昨天在本地已经运行过了。后面电脑断电了。

今天重新运行，第一步是.\mcl。第二步就是Login。Login后的状态是Bot login successful. 后面就会跳出java.lang.IllegalStateException: Failed to decode BdhSession

### mirai-core 版本

2.8.2

### bot-protocol

ANDROID_PHONE

**Comment by shenhuyong** [comment]
同样情况，上午10:45分后出现

**Comment by BIWEA** [comment]
当然，目前试了一下，暂时不影响我的使用，只是说存在这么一个问题

**Comment by Karlatemp** [comment]
在 QQ Service 中断期间的任何报错均不属于 mirai 问题, 请明天重启后重试
