### ISSUE TITLE
在某些情况下无法同步好友消息

### ISSUE THREAD

**Issue by nagame2036** [mamoe/mirai#249]
## 问题

![TIM截图20200421121924](https://user-images.githubusercontent.com/22796024/79825020-689d6780-83ca-11ea-8c39-142386aae57f.png)
如图，12:17:05发送的消息，此后12:17:06发送的自动回复，都能用subscribeFriendMessages正常处理。但之后这个qq发给bot的消息都接收不到。

## 如何复现

1. 手机端qq忙碌模式
2. 设置自动回复
3. 发送消息

**Comment by Him188** [comment]
这并不是自动回复导致的问题，是一个平常的无法同步好友消息问题。

**Comment by Him188** [comment]
这个问题非常难解决（接近边缘情况），目前没有计划详细研究它。

**Comment by Him188** [comment]
如果你可以确定这是由自动回复引起，可回复

**Comment by Him188** [comment]
#306 部分情况下发送消息后 syncCookie 时间错误因而无法同步新消息

**Comment by wuxianucw** [comment]
挂机较长时间也可能出现此问题，我的 log 如下：

```
Network(**********) 22:14:43 : Packet: net.mamoe.mirai.qqandroid.network.protocol.data.jce.RequestPushNotify@665707
Network(**********) 22:14:43 : Send: MessageSvc.PbGetMsg
Network(**********) 22:14:43 : Send: MessageSvc.PbDeleteMsg
```

**Comment by cyanray** [comment]
手机登录bot账号，把所有“QQ订阅号”（如腾讯新闻等）的消息都设置为“不再接收”似乎可以改善。

**Comment by wuxianucw** [comment]
> 手机登录bot账号，把所有“QQ订阅号”（如腾讯新闻等）的消息都设置为“不再接收”似乎可以改善。

并没有确切证据表明两者之间存在关联，我的 bot 号原本就已经取消接收所有订阅号消息，但长时间挂机仍然能够较频繁复现，且存在对特定好友无法同步消息的情况。

**Comment by Watanabe-Asa** [comment]
目前通过删除bot好友解决了没有回复的问题👍

**Comment by lmzqwer** [comment]
> 目前通过删除bot好友解决了没有回复的问题👍

删除好友后，会话变成了来自群内的临时会话，因为群内消息还是能正常接收的，就变相解决了这个问题。需要注意的是删除好友有时会移入屏蔽名单，记得移除。

**Comment by ryoii** [comment]
临时解决方法：用其他与当前Bot登录协议不冲突的客户端登录一次Bot，即可在不重启的情况下恢复消息同步

**Comment by ryoii** [comment]
> 临时解决方法：用其他与当前Bot登录协议不冲突的客户端登录一次Bot，即可在不重启的情况下恢复消息同步

如果仍无法同步，在客户端中随意发送一条好友消息即可

**Comment by HigherSY** [comment]
补充一个：在向 Bot 分享音乐卡片时高概率复现
目前这个问题还是比较严重的，吞消息之后重启一般能解决

**Comment by Mrs4s** [comment]
@Him188 @mzdluo123 此问题的根本原因是因为QQ服务器会直接转发客户端设置的seq，如果同一个好友使用不同客户端给Bot发送信息的话会导致seq不连续.
比如手机QQ的seq为 9100
PC QQ的seq为3000
如果先用手机给Bot发送信息再使用PC的话就会导致msg被过滤掉.
应该可以将msg seq放到CacheList解决.

**Comment by mzdluo123** [comment]
> @Him188 @mzdluo123 此问题的根本原因是因为QQ服务器会直接转发客户端设置的seq，如果同一个好友使用不同客户端给Bot发送信息的话会导致seq不连续.
> 比如手机QQ的seq为 9100
> PC QQ的seq为3000
> 如果先用手机给Bot发送信息再使用PC的话就会导致msg被过滤掉.
> 应该可以将msg seq放到CacheList解决.

目前已解决这个问题，只是开发过程中出了点问题所以提交看起来怪怪的

**Comment by Mrs4s** [comment]
> > @Him188 @mzdluo123 此问题的根本原因是因为QQ服务器会直接转发客户端设置的seq，如果同一个好友使用不同客户端给Bot发送信息的话会导致seq不连续.
> > 比如手机QQ的seq为 9100
> > PC QQ的seq为3000
> > 如果先用手机给Bot发送信息再使用PC的话就会导致msg被过滤掉.
> > 应该可以将msg seq放到CacheList解决.
> 
> 目前已解决这个问题，只是开发过程中出了点问题所以提交看起来怪怪的

我使用最新的dev分支似乎还能复现emmm

**Comment by mzdluo123** [comment]
> > > @Him188 @mzdluo123 此问题的根本原因是因为QQ服务器会直接转发客户端设置的seq，如果同一个好友使用不同客户端给Bot发送信息的话会导致seq不连续.
> > > 比如手机QQ的seq为 9100
> > > PC QQ的seq为3000
> > > 如果先用手机给Bot发送信息再使用PC的话就会导致msg被过滤掉.
> > > 应该可以将msg seq放到CacheList解决.
> > 
> > 
> > 目前已解决这个问题，只是开发过程中出了点问题所以提交看起来怪怪的
> 
> 我使用最新的dev分支似乎还能复现emmm

你说的问题是无法收到私聊消息吗？你的测试环境是什么样的

**Comment by Mrs4s** [comment]
> > > > @Him188 @mzdluo123 此问题的根本原因是因为QQ服务器会直接转发客户端设置的seq，如果同一个好友使用不同客户端给Bot发送信息的话会导致seq不连续.
> > > > 比如手机QQ的seq为 9100
> > > > PC QQ的seq为3000
> > > > 如果先用手机给Bot发送信息再使用PC的话就会导致msg被过滤掉.
> > > > 应该可以将msg seq放到CacheList解决.
> > > 
> > > 
> > > 目前已解决这个问题，只是开发过程中出了点问题所以提交看起来怪怪的
> > 
> > 
> > 我使用最新的dev分支似乎还能复现emmm
> 
> 你说的问题是无法收到私聊消息吗？你的测试环境是什么样的

先使用iOS v8.4.2.608给bot私聊任意信息 再使用PC v9.3.6 给bot私聊任意信息即可复现

**Comment by mzdluo123** [comment]
> > > > > @Him188 @mzdluo123 此问题的根本原因是因为QQ服务器会直接转发客户端设置的seq，如果同一个好友使用不同客户端给Bot发送信息的话会导致seq不连续.
> > > > > 比如手机QQ的seq为 9100
> > > > > PC QQ的seq为3000
> > > > > 如果先用手机给Bot发送信息再使用PC的话就会导致msg被过滤掉.
> > > > > 应该可以将msg seq放到CacheList解决.
> > > > 
> > > > 
> > > > 目前已解决这个问题，只是开发过程中出了点问题所以提交看起来怪怪的
> > > 
> > > 
> > > 我使用最新的dev分支似乎还能复现emmm
> > 
> > 
> > 你说的问题是无法收到私聊消息吗？你的测试环境是什么样的
> 
> 先使用iOS v8.4.2.608给bot私聊任意信息 再使用PC v9.3.6 给bot私聊任意信息即可复现
> 理论上任意跨平台客户端这么操作都能复现

我刚刚试了一下，使用pc tim和Android tim无法复现该问题。目前我没有ios设备无法进行测试，使用的账号为同一账号

**Comment by Mrs4s** [comment]
> > > > > > @Him188 @mzdluo123 此问题的根本原因是因为QQ服务器会直接转发客户端设置的seq，如果同一个好友使用不同客户端给Bot发送信息的话会导致seq不连续.
> > > > > > 比如手机QQ的seq为 9100
> > > > > > PC QQ的seq为3000
> > > > > > 如果先用手机给Bot发送信息再使用PC的话就会导致msg被过滤掉.
> > > > > > 应该可以将msg seq放到CacheList解决.
> > > > > 
> > > > > 
> > > > > 目前已解决这个问题，只是开发过程中出了点问题所以提交看起来怪怪的
> > > > 
> > > > 
> > > > 我使用最新的dev分支似乎还能复现emmm
> > > 
> > > 
> > > 你说的问题是无法收到私聊消息吗？你的测试环境是什么样的
> > 
> > 
> > 先使用iOS v8.4.2.608给bot私聊任意信息 再使用PC v9.3.6 给bot私聊任意信息即可复现
> > 理论上任意跨平台客户端这么操作都能复现
> 
> 我刚刚试了一下，使用pc tim和Android tim无法复现该问题。目前我没有ios设备无法进行测试，使用的账号为同一账号

我这边可以100%复现，检查了就是seq不连续的问题。
开发群同意一下？我可以帮忙测试emmm 🤔

**Comment by HigherSY** [comment]
> @Him188 @mzdluo123 此问题的根本原因是因为QQ服务器会直接转发客户端设置的seq，如果同一个好友使用不同客户端给Bot发送信息的话会导致seq不连续.
> 比如手机QQ的seq为 9100
> PC QQ的seq为3000
> 如果先用手机给Bot发送信息再使用PC的话就会导致msg被过滤掉.
> 应该可以将msg seq放到CacheList解决.

测试确认+1 好友seq可能不连续

**Comment by Him188** [comment]
此问题影响好友消息接收, 也同时严重影响群列表, 群员列表

**Comment by Him188** [comment]
似乎在最近的修改 (1.2~1.2.2之间某次更改) 后才出现群列表和好友列表失去同步的问题

**Comment by Him188** [comment]
### 相关衍生问题
以下问题最大的可能原因都是 sync 时丢失相关事件包.

- #482 无法正确处理大量群员同时退出
- #542 用户入群申请 MemberJoinRequestEvent 没有广播, 可能原因是
- #567 新成员入群后 member not found in group

以下问题可能是缓存未成功过滤重复事件 (issue 提交时大约为 `1.1.0` 版本). 
- #449 BotInvitedJoinGroupRequestEvent 重复执行两次

**Comment by Hieuzest** [comment]
> 似乎在最近的修改 (1.2~1.2.2之间某次更改) 后才出现群列表和好友列表失去同步的问题。
> 但在最近修改后消息接收得到改善

8e3fb15556c8afb217c709103ab788d1fbaa214b 中引入的 msgUidSet 对 msgUid 进行了去重，这直接导致了群/群成员列表的同步问题，因为MsgType=33的Uid极易重复
测试环境:bot作为普通旁观成员，在有不同用户主动加入不同群组时，uid均一致

**Comment by Him188** [comment]
> > 似乎在最近的修改 (1.2~1.2.2之间某次更改) 后才出现群列表和好友列表失去同步的问题。
> > 但在最近修改后消息接收得到改善
> 
> @Him188
> [8e3fb15](https://github.com/mamoe/mirai/commit/8e3fb15556c8afb217c709103ab788d1fbaa214b) 中引入的 msgUidSet 对 msgUid 进行了去重，这直接导致了群/群成员列表的同步问题，因为相关事件的Uid极易重复
> 测试: bot作为普通旁观成员，在有不同用户主动加入不同群组时，uid均一致； bot作为管理员时，不同用户申请入群的事件uid也一致
> 
> related: #580 #581 #590 #542

但好友消息需要这样的去重. 因为这个 commit 解决了好友消息重复和收不到的问题

**Comment by Hieuzest** [comment]
考虑对MsgHead实现某种hash（combine seq, time, uid)？

**Comment by Him188** [comment]
> 考虑对MsgHead实现某种hash（combine seq, time, uid)？

我认为不错
