### ISSUE TITLE
无法启动bot  QQ版本过低

### ISSUE THREAD

**Issue by DouxDertod** [mamoe/mirai#2492]
### 问题描述

问题描述：登录报错 code=235, title=温馨提示, message=当前QQ版本过低，请升级至最新版本后再登录。点击进入下载页面, errorInfo=)
 截图：
![image](https://user-images.githubusercontent.com/34690760/218193717-1c802759-6118-4ac2-9f71-c328587366b7.png)
版本信息：
 MCL: 2.1.2-61c8bd8
 JDK: 17
 mirai-core: 2.14.0
 系统：Ubuntu
 截图：
![image](https://user-images.githubusercontent.com/34690760/218193759-2e71cc8e-ad22-4b80-a5d1-31c8e6958b92.png)

### 复现

复现条件：启动mcl， 用SakuraLoginSolver 插件进行验证操作后，即出现该问题。

### mirai-core 版本

2.14.0

### bot-protocol

ANDROID_PHONE

### 其他组件版本

 MCL: 2.1.2-61c8bd8
 JDK: 17

### 系统日志

```text
2023-02-11 03:43:10 E/main: net.mamoe.mirai.network.WrongPasswordException: Error(bot=Bot(328046584), code=235, title=温馨提示, message=当前QQ版本过低，请升级
至最新版本后再登录。点击进入下载页面, errorInfo=)
net.mamoe.mirai.network.WrongPasswordException: Error(bot=Bot(328046584), code=235, title=温馨提示, message=当前QQ版本过低，请升级至最新版本后再登录。点击进入
下载页面, errorInfo=)
        at net.mamoe.mirai.internal.network.components.SsoProcessorImpl$SlowLoginImpl.doLogin(SsoProcessor.kt:331)
        at net.mamoe.mirai.internal.network.components.SsoProcessorImpl$SlowLoginImpl$doLogin$1.invokeSuspend(SsoProcessor.kt)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:33)
        at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
```

### 补充信息

已做尝试：
1、尝试更改mirai版本但已经是最新，未成功。
2、切换渠道为ANDROID_PHONE、ANDROID_PAD、ANDROID_WATCH、MACOS、IPAD
3、保持手机qq（android，ios版本均尝试过），pc端qq 在线。
4、手机qq安全设置删除所有登录设备
5、删除 bots/<对应qq账号> 下 device.json | device.json和 cache | 整个 bots/<对应qq账号>
6、在其他路径重新安装mirai 并导入原路径 plugins/下 除了 mcl-addon-2.2.1.jar 以外的插件，导入config/下除了Console 以外的配置文件夹

以上操作任意组合，任意顺序均未能解决问题

附加描述：
几小时前，Mirai bot 自动关闭，mcl未关闭，手动重启mcl后就这样了。
同时，pc端呈离线状态，无法重连。pc端退出后，仅bot用的这个账号在再登录时同样出现 版本过低无法登录 的报错，其他账号登录均无问题。 pc端卸载并重新安装qq客户端后，pc端问题修复。
在pc端修复前，ios端qq，未曾登录过的Android端qq 均可登录bot用的账号。

**Comment by SaithZhang** [comment]
+1,昨天更新之后不行的，前天还可以。
![image](https://user-images.githubusercontent.com/22760210/218234591-ff69b276-545f-444e-a344-3085de4343fd.png)

**Comment by vafyl** [comment]
同样遇到该问题

**Comment by Gouqiqiqi** [comment]
把bot/QQNum/device.json删除，重启mcl试试

**Comment by cssxsh** [comment]
https://github.com/mamoe/mirai/issues/2453

**Comment by yuejieyao** [comment]
同不行,昨天手机QQ崩了以后就没登上去过了,尝试过切换所有协议并删除bot文件夹,过了验证以后依旧提示这些,在手机上成功登录过后再执行这些操作也不行,感觉直接就被屏蔽了似的,已经登录的手机端那边甚至连其他设备登录的提示都不会有

**Comment by DouxDertod** [comment]
> #2453

您好，这个发送之前已经看过了。大部分方法都试过了。。其他就剩下干等几天会不会好了。。
对于风控，这个账号确实限制在其他设备都没问题啊。 pc也是重新下个最新的客户端登上去就好了。如果是账号问题不应该在其它设备都好用吧。

**Comment by gouxianyu123** [comment]
同问，尝试过切换以前登陆过的QQ，登陆后5s也不行了，在235和237稳定出现

**Comment by SaithZhang** [comment]
> > #2453
> 
> 您好，这个发送之前已经看过了。大部分方法都试过了。。其他就剩下干等几天会不会好了。。 对于风控，这个账号确实限制在其他设备都没问题啊。 pc也是重新下个最新的客户端登上去就好了。如果是账号问题不应该在其它设备都好用吧。

我刚注册个新Q号和用别人的号确实能登录，自己大号可以用ANDROID_WATCH登录，但是昨天注册的小号哪个协议都不行。
但是关键感觉这些号都活不了两天，每次都注册个新的也不是个办法

**Comment by MTmin** [comment]
这个问题,打腾讯人工客服电话,提交证据 让他们重置QQ密码 和绑定手机号后可以解决,但是不太建议;如果不是很大的号的话别费那个力气,人工客服大概需要陆续拨打半小时他们电话才能接入进去,提交证据流程大概12分钟 (前两天亲测)

**Comment by SakuraKoi** [comment]
测试2.14.0 ANDROID_PHONE和ANDROID_PAD均提示235版本过低, ANDROID_WATCH可用

**Comment by MadornC** [comment]
同样，无论大号小号，第二天或第三天必然出现code235 已经尝试了4个号了感觉还是协议的问题

**Comment by cssxsh** [comment]
> 同样，无论大号小号，第二天或第三天必然出现code235 已经尝试了4个号了感觉还是协议的问题

第二天或第三天？
mirai-console 登录成功后会有快速登录缓存

你是否保留了缓存

或者你是 mirai-core 项目，没有正常保存缓存

**Comment by MadornC** [comment]
正常保存了缓存，当天开关是没有问题的，一般到第二天如果再重新打开就会提示code235&nbsp;


466627701
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年2月12日(星期天) 下午4:26
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [mamoe/mirai] 无法启动bot  QQ版本过低 (Issue #2492)





  
同样，无论大号小号，第二天或第三天必然出现code235 已经尝试了4个号了感觉还是协议的问题
  
第二天或第三天？
 mirai-console 登录成功后会有快速登录缓存
 
你是否保留了缓存
 
或者你是 mirai-core 项目，没有正常保存缓存

**Comment by cssxsh** [comment]
> 正常保存了缓存，当天开关是没有问题的，一般到第二天如果再重新打开就会提示code235&nbsp; 466627701 ***@***.*** &nbsp;
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: ***@***.***&gt;; 发送时间: 2023年2月12日(星期天) 下午4:26 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; ***@***.***&gt;; 主题: Re: [mamoe/mirai] 无法启动bot QQ版本过低 (Issue #2492) 同样，无论大号小号，第二天或第三天必然出现code235 已经尝试了4个号了感觉还是协议的问题 第二天或第三天？ mirai-console 登录成功后会有快速登录缓存 你是否保留了缓存 或者你是 mirai-core 项目，没有正常保存缓存 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***&gt;

https://github.com/mamoe/mirai/issues/2475

**Comment by fly8888** [comment]
> 我刚注册个新Q号和用别人的号确实能登录，自己大号可以用ANDROID_WATCH登录，但是昨天注册的小号哪个协议都不行。
> 但是关键感觉这些号都活不了两天，每次都注册个新的也不是个办法

我也是同样问题。基本2天就提示版本低。手机电脑端登录都正常，但是mirai提示QQ版本低。

**Comment by HYYX** [comment]
同样的问题，前几天QQ大规模崩溃的时候服务器挂的bot下线了，现在只要一登录就提示QQ版本低。用家里的网络，PC登录和安卓都能正常登录的QQ号，换成mirai就不行。

**Comment by HYYX** [comment]
我也遇到这个问题，前几天QQ大规模崩溃的时候bot掉线了，再登录时提示QQ版本过低。

但今天才发现最新版本是2.14，而我这用mcl -u更新出来的是2.13。现在改用2.14就没问题了。

**Comment by dragon0629** [comment]
期待有大佬能给mirai提供一个主动验证设备或者身份验证的登录功能……
现在遇到环境稍微不稳定一点，可能就会长时间无法登录 _-_bb
换网，改协议，登录PCQQ挂，一顿操作，最后还是全看运气 OJZ

**Comment by MadornC** [comment]
非密码错误问题 换账号登陆的第一天是正常的 
我的操作步骤：1未做其他操作的情况下重新登陆，无需验证码报错235
2.删除bots下所有文件重新登陆该账号 网页打开验证，通过F12获取ticket返回后仍然是235状态
3.再次删除bots下所有文件登陆未使用过mirai的新账号 通过网页验证后成功登陆新账号
4.再次通过网页验证尝试旧帐号，仍然返回235
5.总结规律：新账号在1到2天内 仍然是可以登录的。到第二天或者第三天复现code235的情况 个人判断大概率是出现风控导致

> > 正常保存了缓存，当天开关是没有问题的，一般到第二天如果再重新打开就会提示code235  466627701 _**@**_.***  
> > […](#)
> > ------------------ 原始邮件 ------------------ 发件人: _**@**_._**>; 发送时间: 2023年2月12日(星期天) 下午4:26 收件人: _**@**_.**_>; 抄送: _**@**_._**>; _**@**_.**_>; 主题: Re: [mamoe/mirai] 无法启动bot QQ版本过低 (Issue #2492) 同样，无论大号小号，第二天或第三天必然出现code235 已经尝试了4个号了感觉还是协议的问题 第二天或第三天？ mirai-console 登录成功后会有快速登录缓存 你是否保留了缓存 或者你是 mirai-core 项目，没有正常保存缓存 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: _**@**_.***>
> 
> #2475

**Comment by RedIce007** [comment]
我也出现了同样的情况，不止机器人，全平台登录都是报qq版本过低的错误，手机端更新后才能正常登录

**Comment by SaithZhang** [comment]
> 这个问题,打腾讯人工客服电话,提交证据 让他们重置QQ密码 和绑定手机号后可以解决,但是不太建议;如果不是很大的号的话别费那个力气,人工客服大概需要陆续拨打半小时他们电话才能接入进去,提交证据流程大概12分钟 (前两天亲测)

老铁能问下你打的是哪个电话吗，怎么操作才能找到人工客服，我怎么也接不到人工客服，刚好有个号没绑定手机，一直都登录不上去了，十分感谢！

**Comment by dragon0629** [comment]
> 非密码错误问题 换账号登陆的第一天是正常的 我的操作步骤：1未做其他操作的情况下重新登陆，无需验证码报错235 2.删除bots下所有文件重新登陆该账号 网页打开验证，通过F12获取ticket返回后仍然是235状态 3.再次删除bots下所有文件登陆未使用过mirai的新账号 通过网页验证后成功登陆新账号 4.再次通过网页验证尝试旧帐号，仍然返回235 5.总结规律：新账号在1到2天内 仍然是可以登录的。到第二天或者第三天复现code235的情况 个人判断大概率是出现风控导致
> 
> > > 正常保存了缓存，当天开关是没有问题的，一般到第二天如果再重新打开就会提示code235  466627701 _**@**_.***  
> > > […](#)
> > > ------------------ 原始邮件 ------------------ 发件人: _**@**_._**>; 发送时间: 2023年2月12日(星期天) 下午4:26 收件人: _**@**_.**_>; 抄送: _**@**_._**>; _**@**_.**_>; 主题: Re: [mamoe/mirai] 无法启动bot QQ版本过低 (Issue #2492) 同样，无论大号小号，第二天或第三天必然出现code235 已经尝试了4个号了感觉还是协议的问题 第二天或第三天？ mirai-console 登录成功后会有快速登录缓存 你是否保留了缓存 或者你是 mirai-core 项目，没有正常保存缓存 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: _**@**_.***>
> > 
> > 
> > #2475

风控了就需要验证设备信息或者身份验证，但是mirai没有提供这个接口，所以就无法完成验证登录
囧昨天问了大哥半天，大哥说的，miraiGO因为实现了主动身份验证，所以通过扫码即可完成登录。
MIRAI没有这个处理，所以遇到这种情况就暂时寄了，什么时候能登完全看脸。
约等于号废了

**Comment by zyzbeier** [comment]
解决不了吗 好两天了 要疯了

**Comment by MadornC** [comment]
今天尝试了删除bots文件后 使用autologin改成android_watch属性并通过验证后暂时可以登陆了具体操作：1.直接删除bots文件夹下QQ号文件
2.mirai/config/Console/autologin.yml下设置账号密码&nbsp; &nbsp; &nbsp; 设置protocol: ANDROID_WATCH没有的话查看如下
&nbsp; &nbsp; # 账号配置. 可用配置列表 (注意大小写):
&nbsp; &nbsp; # "protocol": "ANDROID_PHONE" / "ANDROID_PAD" / "ANDROID_WATCH" / "MACOS" / "IPAD"
&nbsp; &nbsp; # "device": "device.json"
&nbsp; &nbsp; # "enable": true
&nbsp; &nbsp; # "heartbeatStrategy": "STAT_HB" / "REGISTER" / "NONE"

3.启动miraiconsole 通过验证成功登陆


对此本人有猜测，可能是androidwatch的qq协议与其他几个os的协议不是通用的，如果后续还会复现code235版本过低问题我会第一时间回来回复
&nbsp;


466627701
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年2月14日(星期二) 上午9:22
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [mamoe/mirai] 无法启动bot  QQ版本过低 (Issue #2492)





 
解决不了吗 好两天了 要疯了

**Comment by gouxianyu123** [comment]
已解决，用别的方法弄了个bot，打包后解决，谢谢



---原始邮件---
发件人: "Wu Yan ***@***.***&gt;
发送时间: 2023年2月15日(周三) 上午9:27
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [mamoe/mirai] 无法启动bot  QQ版本过低 (Issue #2492)




 今天尝试了删除bots文件后 使用autologin改成android_watch属性并通过验证后暂时可以登陆了具体操作：1.直接删除bots文件夹下QQ号文件 
 2.mirai/config/Console/autologin.yml下设置账号密码&amp;nbsp; &amp;nbsp; &amp;nbsp; 设置protocol: ANDROID_WATCH没有的话查看如下 
 &amp;nbsp; &amp;nbsp; # 账号配置. 可用配置列表 (注意大小写): 
 &amp;nbsp; &amp;nbsp; # "protocol": "ANDROID_PHONE" / "ANDROID_PAD" / "ANDROID_WATCH" / "MACOS" / "IPAD" 
 &amp;nbsp; &amp;nbsp; # "device": "device.json" 
 &amp;nbsp; &amp;nbsp; # "enable": true 
 &amp;nbsp; &amp;nbsp; # "heartbeatStrategy": "STAT_HB" / "REGISTER" / "NONE" 
 
 3.启动miraiconsole 通过验证成功登陆 
 
 
 对此本人有猜测，可能是androidwatch的qq协议与其他几个os的协议不是通用的，如果后续还会复现code235版本过低问题我会第一时间回来回复 
 &amp;nbsp; 
 
 
 466627701 
 ***@***.*** 
 
 
 
 &amp;nbsp; 
 
 
 
 
 ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------ 
 发件人: ***@***.***&amp;gt;;  
 发送时间: 2023年2月14日(星期二) 上午9:22 
 收件人: ***@***.***&amp;gt;;  
 抄送: ***@***.***&amp;gt;; ***@***.***&amp;gt;;  
 主题: Re: [mamoe/mirai] 无法启动bot  QQ版本过低 (Issue #2492) 
 
 
 
 
 
   
 解决不了吗 好两天了 要疯了

**Comment by gouxianyu123** [comment]
> 

https://mirai.mamoe.net/topic/223
用方案三解决了，详细步骤：
1，方法三下载安卓apk
2.在手机上用手表协议（其他的没能触发）触法验证码，然后在打包发给电脑
3.关闭控制台并删除bot里所有文件夹
4.编辑config/AutoLogin.yml 中协议为手表（与手机成功登陆协议中一致）、
5.控制台重新登陆。
补充：方案二：、
下载后放入plugins文件夹好像也可以但是本地访问是一个json，手机端没法访问，可能是防火墙问题，等欧克了写一个方法出来

**Comment by MadornC** [comment]
可能是由于watch的协议独立于android和桌面OS，所以可以用watch登陆 因为watch版本的QQ和移动端QQ是可以同时登陆不冲突的
&nbsp;


466627701
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年2月15日(星期三) 上午10:25
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [mamoe/mirai] 无法启动bot  QQ版本过低 (Issue #2492)





   
https://mirai.mamoe.net/topic/223
 用方案三解决了，详细步骤：
 1，方法三下载安卓apk
 2.在手机上用手表协议（其他的没能触发）触法验证码，然后在打包发给电脑
 3.关闭控制台并删除bot里所有文件夹
 4.编辑config/AutoLogin.yml 中协议为手表（与手机成功登陆协议中一致）、
 5.控制台重新登陆。
 补充：方案二：、
 下载后放入plugins文件夹好像也可以但是本地访问是一个json，手机端没法访问，可能是防火墙问题，等欧克了写一个方法出来

**Comment by pilgrim773** [comment]
code=45, title=禁止登录, message=登录失败，建议升级最新版本后重试，或通过问题反馈与我们联系

遇到了45怎么办……今天反复登录修改插件配置文件就这样了，现在只有WATCH协议能登录了，然后发现在WATCH协议下个别群的消息不捕获，个别群可以，功能不全了。


更新： 一晚上过后那个不处理消息事件的群也能处理了，不过还是想换回PHONE协议

**Comment by 2efPer** [comment]
这个问题好麻烦，我两个号都登不上去了，总不能天天新申请qq号

**Comment by 951043684** [comment]
> mcl -u

直接输入吗，具体怎么做

**Comment by ReanRelay** [comment]
我也是哎，一直登录不上 ，用手表协议倒是可以，手表貌似不知道 撤回事件 ，一直搞不定

**Comment by Lechave** [comment]
尝试了很多方法，刚刚用watch协议和sakura  login solver成功在服务器上登录
