### ISSUE TITLE
Java8无法运行

### ISSUE THREAD

**Issue by 1052915220** [mamoe/mirai#2499]
应该在安装教程哪儿备注运行环境的Java的版本，Java8就无法运行，我手动切换到Java17才能运行。

**Comment by cssxsh** [comment]
mirai 本体只需要 8

但是 [mirai-console-loader](https://github.com/iTXTech/mirai-console-loader) 需要 11

你大概没弄清楚

**Comment by Him188** [comment]
https://github.com/mamoe/mirai/blob/dev/docs/Preparations.md#jvm-%E7%8E%AF%E5%A2%83%E8%A6%81%E6%B1%82

文档里是有的

而如果你使用 MCL, MCL 会自动帮你下一个 17

**Comment by 1052915220** [comment]
哦，看到了。感谢回复
