### ISSUE TITLE
支持查询离线图片链接: 消息链中存在 3 个及以上图片时服务器没有提供 originalUrl

### ISSUE THREAD

**Issue by Hai-tun** [mamoe/mirai#250]
## 问题
当 Bot 收取消息时如果消息内有 3 个及以上的图片 OnlineImage 取出的 originUrl 将会变为 
`http://c2cpicdw.qpic.cn`

## 如何复现

```
    bot.subscribeAlways<FriendMessage> {
        for (message in it.message)
        {
            if (message is OnlineImage)
            {
                println(message.originUrl)
            }
        }
    }
```
## 附输出
![图片](https://user-images.githubusercontent.com/45594251/79828596-9aff9280-83d3-11ea-8341-386e33de66c2.png) 
4 个图片链接错误

![图片](https://user-images.githubusercontent.com/45594251/79828599-9f2bb000-83d3-11ea-9aa9-56284052d6be.png) 
3 个图片链接错误

![图片](https://user-images.githubusercontent.com/45594251/79828605-a2bf3700-83d3-11ea-9a15-7dc33118fa84.png) 
双图链接正常

**Comment by Him188** [comment]
服务器未发送此图连接, 垃圾服务器

**Comment by ryoii** [comment]
三个图片为长消息，检查长消息的图片结构和普通消息图片结构不同
