### ISSUE TITLE
Mirai Console docs 纰漏

### ISSUE THREAD

**Issue by 7aGiven** [mamoe/mirai#2503]
位于https://github.com/mamoe/mirai/blob/dev/mirai-console/docs/Commands.md
![Screenshot_20230215_142050](https://user-images.githubusercontent.com/77519196/218977828-b7224b41-a422-424d-bfd8-58727789f6b3.jpg)
PluginManager应改为CommandManager。

**Comment by StageGuard** [comment]
你可以顺手开个 pr 修复

**Comment by 7aGiven** [comment]
> 你可以顺手开个 pr 修复

好的，我看看PR文档

**Comment by 7aGiven** [comment]
> 你可以顺手开个 pr 修复

已经提交PR了
