### ISSUE TITLE
QuoteReply 处理错误

### ISSUE THREAD

**Issue by Karlatemp** [mamoe/mirai#2510]
## 私聊 QuoteReply

1. seq id 为  int16 (#2495)
2. rand id 为 ? (pending confirm)
3. MessageSource 缺少 msgUin 导致没法正确回复, 需要修改 MessageSource 携带 msgUin. (需要确定是添加新字段, 还是塞入现有的 ids/internalIds)
4. 需要确认 bot 回复自己信息时是否正确

**Comment by Him188** [comment]
ids internalIds 现在有个 contract是它们的size要一样
