### ISSUE TITLE
code=237错误

### ISSUE THREAD

**Issue by gnahz77** [mamoe/mirai#2526]
### 问题描述

登录出现**237错误**，切换了各个协议，删除缓存，设备信息，调整qq设置，修改密码等，都没解决。
还尝试了使用Aoki进行登录，也是出现237错误。
然后我进入qq设置将**全部登录设备删除**，然后使用**android客户端**登录qq，弹窗：网络不稳定，登录失败.......，然后经过qq弹出的**身份验证**（滑块验证码，发送短信，接收短信验证码）后才成功登录。
但是依旧无法使用mirai登录账号
![Image text](https://temp-mirai.oss-cn-beijing.aliyuncs.com/IMG20230223014451.jpg)

### 复现

1.linux服务器登录
1.windows使用idea登录
2.切换到linux服务器登录失败
3.然后windows，android端都无法登录了

### mirai-core 版本

2.14.0

### bot-protocol

ANDROID_PAD

**Comment by gnahz77** [comment]
隔了几个小时后，现在删除缓存，设备信息，切换到macOS协议登录上了

**Comment by Him188** [comment]
#2570
