### ISSUE TITLE
macOS 启动 mirai 报错: Cannot invoke .... $this$forEach is null

### ISSUE THREAD

**Issue by af913337456** [mamoe/mirai#2533]
### 问题描述

macOS 启动 mirai 报错: Cannot invoke .... $this$forEach is null。如图
![图片](https://user-images.githubusercontent.com/10436277/221333469-62b5ac8e-5a40-4d5b-8c50-d0e39aec3bd5.png)

### 复现

启动，输入密码，点击登录

### mirai-core 版本

1.1.5

### bot-protocol

ANDROID_PHONE

**Comment by af913337456** [comment]
@sonder-joker

**Comment by StageGuard** [comment]
mirai-compose 已经很久没有维护了，建议使用[控制台版本](https://github.com/mamoe/mirai/blob/dev/docs/ConsoleTerminal.md)

**Comment by Karlatemp** [comment]
请向 mirai-compose 报告此问题
