### ISSUE TITLE
运行“./mcl”后无法进入命令行

### ISSUE THREAD

**Issue by sakimidare** [mamoe/mirai#2534]
![Screenshot_20230225_202000.jpg](https://user-images.githubusercontent.com/69438785/221357318-e761af7f-d03c-4cd9-8a40-b6ce19efe3c8.jpg)

# 摘要

如图，在运行`./mcl`时，验证完包之后就直接结束了程序，没有进入命令行，也没有报错。

# 环境

Ubuntu 22.04.1 LTS x86_64

iTX Technologies Mirai Console Loader version 2.1.2-61c8bd8
Runtime: OpenJDK 64-Bit Server VM 11.0.17 (arch: 64)

**Comment by Karlatemp** [comment]
修改 config.json, 找到 log_level, 修改为 0

**Comment by sakimidare** [comment]
> 修改 config.json, 找到 log_level, 修改为 0

![Screenshot_20230225_205548.jpg](https://user-images.githubusercontent.com/69438785/221358022-c95a6c9c-d599-4fb2-a8b4-0defeffad105.jpg)

**Comment by Karlatemp** [comment]
执行下下面的命令看看, 以及确认一下命令是不是真的是 `./mcl`


```
ls -la ./libs
cat ./mcl
java -version
```

**Comment by Keyezi** [comment]
请将命令执行处进行截图，以确认你输入的内容
其次你可以尝试通过直接在java运行此包 不使用脚本"mcl"

**Comment by cssxsh** [comment]
> mirai-console-2.14.0.jar

mirai-console-2.14.0-all.jar
文件下错了

你需要删掉 mirai-console-2.14.0.jar
让他重新下载

**Comment by sakimidare** [comment]
> 执行下下面的命令看看, 以及确认一下命令是不是真的是 `./mcl`
> 
> 
> ```
> ls -la ./libs
> cat ./mcl
> java -version
> ```
> 

![Screenshot_20230225_212316.jpg](https://user-images.githubusercontent.com/69438785/221359249-df51a6bc-6680-4746-9c83-62d89c8ccee6.jpg)

**Comment by sakimidare** [comment]
> > mirai-console-2.14.0.jar
> 
> mirai-console-2.14.0-all.jar
> 文件下错了
> 
> 你需要删掉 mirai-console-2.14.0.jar
> 让他重新下载

问题解决了，谢谢！
