### ISSUE TITLE
似乎可以有可参考的TLV544协议开源实现

### ISSUE THREAD

**Issue by zhaodice** [mamoe/mirai#2553]
https://github.com/fuqiuluo/nativeqq/commit/0f07516dc60e8589e19d9fddba6a9f59dff82a0f
是否有价值呢QwQ

**Comment by zhaodice** [comment]
https://github.com/fuqiuluo/nativeqq/blob/fuqiuluo/tars/include/crypt/bytedata.h
算法里出现了大量人为设定的“密码”
应该是故意的
例如
```
        std::string data = "(kT7*@a$L?";
        data.insert(0, data.substr(data.size() - 2, 2));
        data = data.substr(0, data.size() - 2);

        std::string data2 = "9+>6X)&O@a";
        data2.insert(0, data2.substr(data2.size() - 2, 2));
        data2 = data2.substr(0, data2.size() - 2);
```

**Comment by fuqiuluo** [comment]
很显然这个是旧版TLV544的代码，所以说没有价值。

**Comment by zhaodice** [comment]
> 很显然这个是旧版TLV544的代码，所以说没有价值。

原来这玩意还能更新…学到了

**Comment by fuqiuluo** [comment]
其实我有API：http://api.xinrao.moe/v1/energy?version=6.0.0.2534&uin=1234567&guid=ABCDABCDABCDABCDABCDABCDABCDABCD&data=810_f&mode=v2&subCmd=15
