### ISSUE TITLE
复杂类算法接口

### ISSUE THREAD

**Issue by zhaodice** [mamoe/mirai#2562]
我想也许考虑添加一个统一的接口，用来由开发者自行实现目前暂时无法实现的复杂算法，毕竟我相信项目维护者不可能内置自己的http api的x（比如通过插件，想修算法盯了好久的登录流程头有点大X）

**Comment by NoMathExpectation** [comment]
写出来算法了为什么不提交pr呢（

**Comment by cssxsh** [comment]
> 写出来算法了为什么不提交pr呢（

给 mirai pr 就像上班

**Comment by zhaodice** [comment]
> 写出来算法了为什么不提交pr呢（

大哥我直接调用的so文件获取的计算结果，咋写出来啊草（在mirai里塞tx的so文件会很奇怪吧）

**Comment by zhaodice** [comment]
这种算法越来越多，写出源码的难度会越来越大，以后也许只能这样搞了，当然也可能我悲观了（x

**Comment by StageGuard** [comment]
你不直接用core调试吗？为什么用httpapi

**Comment by NoMathExpectation** [comment]
> > 写出来算法了为什么不提交pr呢（
> 
> 大哥我直接调用的so文件获取的计算结果，咋写出来啊草（在mirai里塞tx的so文件会很奇怪吧）

不能在kotlin上实现一个吗

**Comment by cssxsh** [comment]
> 你不直接用core调试吗？为什么用httpapi

他的意思是提供例如 SPI 之类的接口
然后可以第三方直接更新协议解析器

**Comment by zhaodice** [comment]
> > > 写出来算法了为什么不提交pr呢（
> > 
> > 
> > 大哥我直接调用的so文件获取的计算结果，咋写出来啊草（在mirai里塞tx的so文件会很奇怪吧）
> 
> 不能在kotlin上实现一个吗

混淆太严重了，很难搞，而且tx想更新算法也很快，如果不直接调用so，我们很被动

**Comment by cssxsh** [comment]
> > > 写出来算法了为什么不提交pr呢（
> > 
> > 
> > 大哥我直接调用的so文件获取的计算结果，咋写出来啊草（在mirai里塞tx的so文件会很奇怪吧）
> 
> 不能在kotlin上实现一个吗

他是直接从 APK 扣so出来调用

**Comment by sandtechnology** [comment]
这个需求太抽象了 你是需要整个mirai主动调用的adapter接口吗？

**Comment by zhaodice** [comment]
> 这个需求太抽象了 你是需要整个mirai主动调用的adapter接口吗？

登录验证有验证解决器。
那算法自然有关有算法解决器（因为TLV544肯定不是唯一也不是最后一个，以后出个TLV114514加密算法都可能x），只不过它是不稳定的，里面的接口随时要改变（算法如果出现变化或过时/加参数等等）

**Comment by Alceatraz** [comment]
> > > > 写出来算法了为什么不提交pr呢（
> > > 
> > > 
> > > 大哥我直接调用的so文件获取的计算结果，咋写出来啊草（在mirai里塞tx的so文件会很奇怪吧）
> > 
> > 
> > 不能在kotlin上实现一个吗
> 
> 混淆太严重了，很难搞，而且tx想更新算法也很快，如果不直接调用so，我们很被动

Windows是不是就寄了（

**Comment by zhaodice** [comment]
> Windows是不是就寄了（

本来就寄的差不多了，别忘了从滑块验证码开始出现后，win就不可能独立完成登录了，多个so文件又怎么了？

**Comment by Alceatraz** [comment]
> > Windows是不是就寄了（
> 
> 本来就寄的差不多了，别忘了从滑块验证码开始出现后，win就不可能独立完成登录了，多个so文件又怎么了？

windows不能独立登录但是可以独立运行，多个so，导致mirai本来JVM栈的跨平台变成了native绑定*。那直接来个 Aoki 2.0 就解决了，因为Aoki也在安卓上，so肯定通用，除非这个手机连qq都用不了。

而且2.15新添加了扫码登录，缓解了99.99%的问题。（至于说“只是缓解”“0.01%怎么办”“TX要是明天又把扫码改成滑块一样风控” 这种不可预知的未来是完全看TX心情，不应该作为决策的因素。）

而且说真的，虽然我希望mirai能像初号机一样永远存在下去，但是如果mirai简单到随便是个人都能用，那可不是啥好事。

*: 指默认solver

**Comment by jexjws** [comment]
与此issue相关的一个issue（也是关于QQ的加密算法的）：https://github.com/Mrs4s/go-cqhttp/issues/2183

**Comment by SuperKenVery** [comment]
大佬这方面有进展吗？调dll做的怎么样了？感觉可靠性/可持续性如何？

关于跨平台，因为反正qqnt已经跨了windows/macos/linux了，所以我觉得应该问题不大（？

个人感觉调dll会是一个非常有前景的做法（

**Comment by zhaodice** [comment]
> 大佬这方面有进展吗？调dll做的怎么样了？感觉可靠性/可持续性如何？
> 
> 关于跨平台，因为反正qqnt已经跨了windows/macos/linux了，所以我觉得应该问题不大（？
> 
> 个人感觉调dll会是一个非常有前景的做法（

以后可能会越来越麻烦，比如dll里加各种检测判断是否在非官方环境等

**Comment by StageGuard** [comment]
目前已经在 core/pkgsso 分支添加了对应算法的 SPI 接口。就目前的进度来看，接口大概不会有太大变化，可以尝试自己实现复杂算法 SPI。
