### ISSUE TITLE
2.14.0后如何操作滑动验证码

### ISSUE THREAD

**Issue by Deficuet** [mamoe/mirai#2574]
### 问题描述

登录时遇到滑动验证码，但没有GUI弹出，不知道在哪里提交ticket。然后就停在这步了
同时console输入也变得“迟钝”，需要长按键盘才能实现输入，十分费劲
我三个号遇到的验证基本全是滑动验证码

### 复现

我也不知道，但我这个号是这样的

### mirai-core 版本

2.14.0

### bot-protocol

IPAD

### 其他组件版本

fix-protocol-version-1.3.0
mirai-login-solver-sakura-0.0.9

### 系统日志

```text
[SliderCaptcha] 需要滑动验证码, 请按照以下链接的步骤完成滑动验证码, 然后输入获取到的 ticket
[SliderCaptcha] Slider captcha required. Please solve the captcha with following link. Type ticket here after completion.
[SliderCaptcha] @see https://github.com/project-mirai/mirai-login-solver-selenium
[SliderCaptcha] @see https://docs.mirai.mamoe.net/mirai-login-solver-selenium/
Recv: wtlogin.login
[SliderCaptcha] 或者输入 TxCaptchaHelper 来使用 TxCaptchaHelper 完成滑动验证码
[SliderCaptcha] Or type `TxCaptchaHelper` to resolve slider captcha with TxCaptchaHelper.apk
[SliderCaptcha] Captcha link: https://ssl.captcha.qq.com/template/wireless_mqq_captcha.html?[后略]
```
[完整登陆日志.txt](https://github.com/mamoe/mirai/files/10974967/default.txt)

**Comment by cssxsh** [comment]
https://github.com/KasukuSakura/mirai-login-solver-sakura

**Comment by Deficuet** [comment]
> https://github.com/KasukuSakura/mirai-login-solver-sakura

用了，见“其他组件版本”。放在plugins文件夹下，没有东西弹出来。需要加命令行参数吗？

**Comment by cssxsh** [comment]
> > https://github.com/KasukuSakura/mirai-login-solver-sakura
> 
> 用了，见“其他组件版本”。放在plugins文件夹下，没有东西弹出来。需要加命令行参数吗？

相反 ，如果你添加了 `-Dmirai.no-desktop=true`, 他就不会弹出窗口

**Comment by Deficuet** [comment]
> > > https://github.com/KasukuSakura/mirai-login-solver-sakura
> > 
> > 
> > 用了，见“其他组件版本”。放在plugins文件夹下，没有东西弹出来。需要加命令行参数吗？
> 
> 相反 ，如果你添加了 `-Dmirai.no-desktop=true`, 他就不会弹出窗口

啥都没加
java -cp "./libs/*" net.mamoe.mirai.console.terminal.MiraiConsoleTerminalLoader %*

**Comment by Karlatemp** [comment]
是否使用 login 命令登录

**Comment by Deficuet** [comment]
> 

Bot.login方法。刚才试了一下login命令可以正常进行滑动验证

**Comment by Karlatemp** [comment]
在plugin中直接登录bot是不建议并且不受支持的


如果你一定要在console中直接登录bot 请使用 MiraiConsole.addBot

**Comment by Deficuet** [comment]
> 在plugin中直接登录bot是不建议并且不受支持的 如果你一定要在console中直接登录bot 请使用 MiraiConsole.addBot

彳亍
