### ISSUE TITLE
群消息の私聊消息ID

### ISSUE THREAD

**Issue by lliioollcn** [mamoe/mirai#258]
无法在群消息事件或私聊消息事件中取得消息id，但是在消息撤回事件包含

**Comment by Him188** [comment]
可以。消息 id 属于 MesaageSource，是 MessageChain 的一个元素

可通过 `ContactMessage.message.sourceId` 获取

`ContactMesaage` 也可能有 `.id` 的扩展

**Comment by lliioollcn** [comment]
好的，感谢
