### ISSUE TITLE
报错刷屏，随后237

### ISSUE THREAD

**Issue by qfys521** [mamoe/mirai#2581]
### 问题描述

请具体看log

### 复现

在接受消息时突然报错

### mirai-core 版本

2.14.0

### bot-protocol

ANDROID_PHONE

### 其他组件版本

基于`mirai-core`、`mirai-api`等开发的`XiaoMingBot-4.8.6`
![log](https://user-images.githubusercontent.com/97349476/226182634-07593f71-73ca-404f-ae48-073cae5c537c.png)
请将.png更改为.log谢谢。

**Comment by qfys521** [comment]
稍等片刻，我找一个扔日志的平台

**Comment by qfys521** [comment]
https://qfys520.lanzoub.com/iexuU0qji4be

**Comment by cssxsh** [comment]
https://pastebin.com/

请

**Comment by qfys521** [comment]
> https://pastebin.com/
> 
> 请

输入法粘不完整

**Comment by sandtechnology** [comment]
看起来不是 mirai 问题，237是频繁登录所致 请在一段时间后删除device.json重试

**Comment by qfys521** [comment]
https://github.com/qfys521/otherLogs/blob/master/log.log

**Comment by qfys521** [comment]
> 看起来不是 mirai 问题，237是频繁登录所致 请在一段时间后删除device.json重试

但是我这个账号之前一直处于正常的登录状态
在出现这个问题后重启一下`XiaoMingHostTerminal`后出现了237

**Comment by sandtechnology** [comment]
> > 看起来不是 mirai 问题，237是频繁登录所致 请在一段时间后删除device.json重试
> 
> 但是我这个账号之前一直处于正常的登录状态 在出现这个问题后重启一下`XiaoMingHostTerminal`后出现了237

那我不知道了 反正 237 提示的就是当前网络不稳定，登录失败。推荐使用常用设备或通过手机号登录。
请自行 参考 #2570

**Comment by Him188** [comment]
#2570

**Comment by qfys521** [comment]
和服务商刚刚了解了一下，今天下午有点有点小问题，可能是这个导致的(具体还在进一步确认中)
