### ISSUE TITLE
originalAnnouncements.toList() 获取的公告数量为0

### ISSUE THREAD

**Issue by yujumpjump** [mamoe/mirai#2589]
### 问题描述

在使用originalAnnouncements.toList()获取群公告的数量的时候为0  （有时候是可以获取到的，有时候是获取不到）

### 复现

 MiraiAnnouncements announcements = miraiGroupMessageEvent.getGroup().getAnnouncements();
        Announcements originalAnnouncements = announcements.getOriginalAnnouncements();
        List<OnlineAnnouncement> onlineAnnouncements = originalAnnouncements.toList();
        log.info("公告数量{}",onlineAnnouncements.size());

### mirai-core 版本

2.15.0-dev-39

### bot-protocol

MACOS

### 补充信息

![image](https://user-images.githubusercontent.com/77835552/227273778-ad916358-e043-4703-bada-9bba9205f7f3.png)

**Comment by yujumpjump** [comment]
通过更换ANDROID_PHONE协议错误消失，我觉得可能是MACOS协议的问题

**Comment by Him188** [comment]
@cssxsh

**Comment by cssxsh** [comment]
> @cssxsh

复现不出来

**Comment by yujumpjump** [comment]
有时候是获取不到的 有时候是可以获取到的。昨天就是 我换了协议就立刻就能获取到了
