### ISSUE TITLE
支持机器人被邀入群事件及其处理

### ISSUE THREAD

**Issue by lliioollcn** [mamoe/mirai#259]
我查了事件列表，只有机器人入群事件，没有被邀事件。
是否可以让机器人接受/拒绝进群邀请呢XD

**Comment by Him188** [comment]
应该有，请搜索Invite

**Comment by lliioollcn** [comment]
事件列表包含Invite字段的我只搜索到了GroupAllowMemberInviteEvent(群 "允许群员邀请好友加群" 功能状态改)和MemberJoinEvent.Invite(成员被邀加入群事件)XD

**Comment by Him188** [comment]
目前有这个事件

```kotlin

/**
 * Bot 加入了一个新群
 */
@MiraiExperimentalAPI
data class BotJoinGroupEvent(
    override val group: Group
) : BotPassiveEvent, GroupEvent, Packet

```

收到事件时并不能判断是被邀请, 还是在 PC 端主动加入了这个群.

**Comment by lliioollcn** [comment]
您可能没有理解我的意思。
我的意思是机器人收到了一个入群邀请事件
通过这个来接受/拒绝这个入群邀请XD

**Comment by Him188** [comment]
你可以邀请一次，看log里的事件名

**Comment by Him188** [comment]
MemberJoinRequestEvent

**Comment by Him188** [comment]
机器人收到入群邀请不支持。
