### ISSUE TITLE
二维码登录的尺寸问题

### ISSUE THREAD

**Issue by CaiJingLong** [mamoe/mirai#2591]
### 问题描述

二维码的尺寸有点过于夸张了

### 复现

![](https://user-images.githubusercontent.com/14145407/227408608-e2a578b1-8370-4c7f-9456-27f604445b7b.png)

### mirai-core 版本

2.15.0-M1

### bot-protocol

ANDROID_WATCH

**Comment by Karlatemp** [comment]
这已经是能在控制台显示的最小尺寸了

**Comment by ghost** [comment]
请问二维码登陆需要打什么插件吗

**Comment by 7980963** [comment]
同问，怎么使用扫码登陆？

**Comment by CaiJingLong** [comment]
问怎么扫码登录的:
用版本号 2.15.0-M1 
看release里，有简单说明
使用的时候记得把有可能的账号风控先解除
然后记得用安卓watch协议
Macos协议在我这提示版本过低

**Comment by 7980963** [comment]
> 

看到了，感谢

**Comment by Him188** [comment]
这是在不依赖外部库（为了减小体积）的情况下，直接在控制台能打印的最小体积（用的是ANSI颜色+方块字符，而不是显示了图片）。既然你的屏幕能显示得下，那应该就没问题。如果你真的想要它变小，那可以自行实现 `LoginSolver`。
