### ISSUE TITLE
启动后出现了Process exited with -1073740791的报错无法正常启动

### ISSUE THREAD

**Issue by indexprohibitum** [mamoe/mirai#2595]
### 问题描述

启动后出现Process exited with -1073740791的错误并退出程序

### 复现

只要启动就会发生

### mirai-core 版本

2.14.0

### bot-protocol

ANDROID_PHONE

**Comment by sandtechnology** [comment]
![image](https://user-images.githubusercontent.com/20417547/227757734-c69998ad-7c1a-426f-8b90-7717f0fddba8.png)
鉴定为你的Java问题
EDIT:STATUS_FAIL_FAST_EXCEPTION(C0000409)

**Comment by indexprohibitum** [comment]
> 
该如何解决

**Comment by indexprohibitum** [comment]
> ![image](https://user-images.githubusercontent.com/20417547/227757734-c69998ad-7c1a-426f-8b90-7717f0fddba8.png) 鉴定为你的Java问题 EDIT:STATUS_FAIL_FAST_EXCEPTION(C0000409)
该如何解决
