### ISSUE TITLE
使用最新版mirai登录时出现"当前QQ版本过低，请升级至最新版本后再登录。点击进入下载页面"错误信息

### ISSUE THREAD

**Issue by htrskmiku** [mamoe/mirai#2596]
如题，估计是qq再次更新了版本限制

**Comment by Yuk-0v0** [comment]
请问解决了吗，今天咱也遇到了

**Comment by Hisir0909** [comment]
> 

你可以尝试把原来的bot数据删除了,重新登录一边

**Comment by Yuk-0v0** [comment]
> > 
> 
> 你可以尝试把原来的bot数据删除了,重新登录一边

已经解决了，用了这个插件就好https://github.com/cssxsh/fix-protocol-version
