### ISSUE TITLE
MessageRecallEvent 信息撤回事件没有响应

### ISSUE THREAD

**Issue by yujumpjump** [mamoe/mirai#2600]
### 问题描述

在群里面撤回一条信息MessageRecallEvent 不发生响应

### 复现

 @SneakyThrows
    @EventHandler
    public  void onMessage(MessageRecallEvent groupRecall) {
        System.out.println(groupRecall);
}

### mirai-core 版本

2.15.0-dev-39

### bot-protocol

MACOS

**Comment by Him188** [comment]
仔细阅读文档的 core 的事件部分
