### ISSUE TITLE
Mirai-Console Intellij 插件不支持 Intellij IDEA 2023.1

### ISSUE THREAD

**Issue by ArgonarioD** [mamoe/mirai#2606]
### 问题描述

如题。
![image](https://user-images.githubusercontent.com/15799382/229303749-9b33be0f-9a76-4d79-968a-4249dabcb67f.png)

### 其他组件版本

Mirai Console Intellij Plugin: 223-2.14.0-172-1

### 补充信息

About IntelliJ IDEA 2023.1
![image](https://user-images.githubusercontent.com/15799382/229304074-1cd73412-f82d-4c44-bd0b-59b871dba2d5.png)

**Comment by Him188** [comment]
[mirai-console-intellij-231-2.15.0-182-1.zip](https://github.com/mamoe/mirai/files/11130169/mirai-console-intellij-231-2.15.0-182-1.zip)

提交 JB 审核了, 下周一估计就有了, 也可以下载 zip 拖到 IDEA 里使用
