### ISSUE TITLE
每隔一段时间就timeout

### ISSUE THREAD

**Issue by huanmeng-qwq** [mamoe/mirai#2607]
### 问题描述

![image](https://user-images.githubusercontent.com/49704373/229347916-a19d4830-039f-4c52-b79d-ece55ac0a905.png)

### 复现

启动后过一段时间就会有，虽然会重连，但是会丢一些信息

### mirai-core 版本

2.14.0

### bot-protocol

MACOS

**Comment by Him188** [comment]
这也没有办法

**Comment by sandtechnology** [comment]
> 这也没有办法

可以试试重发心跳包？不知道目前逻辑有没有做（

**Comment by sandtechnology** [comment]
哦 目前有做的 那其实就是纯网络问题 没有办法（
