### ISSUE TITLE
获取群活跃数据失败(ActiveRankRecord)

### ISSUE THREAD

**Issue by wly20040415** [mamoe/mirai#2609]
### 问题描述

方式跟获取群聊数据一致，但是获取群活跃的数据报错，代码如下 | 报错信息如下:
![QQ图片20230403231507](https://user-images.githubusercontent.com/60537755/229553895-3b6f9a16-2829-4bd4-bc00-7a58572231c9.jpg)
![QQ图片20230403231511](https://user-images.githubusercontent.com/60537755/229553908-ed64572e-a896-4d74-8363-38fa31e142eb.jpg)

### 复现

调用方式与群数据信息一样:
群数据信息代码:
var group_queryChart = group.active.queryChart()
                    var msg= buildMessageChain {
                        +group_queryChart.actives.map { "活跃人数:${it.value}" }.toString()
                        +"\r\n"
                        +group.active.queryChart().members.map { "总群人数:${it.key}" }.toString()
                        +"\r\n"
                        +group.active.queryChart().exit.map { "每日退群人数: ${it.key}" }.toString()
                        +"\r\n"
                        +group.active.queryChart().join.map { "每日进群人数:${it.key}" }.toString()
                        +group.active.queryChart().sentences.map { "每日申请进群人数:${it.key}" }.toString()
                    }
                    group.sendMessage(msg)

活跃数据信息代码如下:
 var grou_rank : List<ActiveRankRecord> = group.active.queryActiveRank()
                    for(result in grou_rank){
                        val msg = buildMessageChain {
                            +"=======活跃数据========"
                            +"\r\n"
                            + "{QQ:${result.memberName}:${result.memberId}\r\n活跃度:${result.temperature}\r\n活跃积分:${result.score}}".toString()
                            +"\r\n"
                            +"======================"
                        }
                        group.sendMessage(msg)
}

都是相同调用方式，活跃数据信息报错

### mirai-core 版本

2.15.0-M1

### bot-protocol

ANDROID_PHONE

### 其他组件版本

mirai-api-http v2.6.0

### 补充信息

改变调用办法多次无解，求修复或解答 T_T

**Comment by cssxsh** [comment]
可能是数据结构变了
