### ISSUE TITLE
什么奇怪的输入流读取

### ISSUE THREAD

**Issue by kinhirozane** [mamoe/mirai#2612]
### 问题描述

使用`BufferedImage`创建一张图片，然后将任意一串字符以水印的方式绘制上去（无关紧要），调用`ImageIO.write`将创建的图片保存，然后使用`FileInputStream`读取那张图片，`uploadAsImage`后发送图片消息，就发生输入流异常。在此过程中尝试使用java-io，nio，kotlin-io分别读写图片文件，都会出现j`ava.io.EOFException: Premature end of stream: expected 2 bytes`。

### 复现

无论使用什么方式写入的图片都会反复出现这个异常，其中尝试使用过`Glide`库也没用。

### mirai-core 版本

2.15.0-M1

### bot-protocol

ANDROID_PHONE

### 其他组件版本

`chat-command: 0.6.0`
`mirai-login-solver-sakura: 0.0.10`

### 系统日志

```text
java.io.EOFException: Premature end of stream: expected 2 bytes
	at net.mamoe.mirai.internal.deps.io.ktor.utils.io.core.StringsKt.prematureEndOfStream(Strings.kt:453)
	at net.mamoe.mirai.internal.deps.io.ktor.utils.io.core.InputArraysKt.readFully(InputArrays.kt:240)
	at net.mamoe.mirai.internal.deps.io.ktor.utils.io.core.StringsKt.readBytesOf(Strings.kt:189)
	at net.mamoe.mirai.internal.deps.io.ktor.utils.io.core.StringsKt.readBytes(Strings.kt:175)
	at net.mamoe.mirai.internal.message.image.ImageDecoderKt.getJPGImageInfo(ImageDecoder.kt:29)
	at net.mamoe.mirai.internal.message.image.ImageDecoderKt.calculateImageInfo(ImageDecoder.kt:154)
	at net.mamoe.mirai.internal.contact.CommonGroupImpl$uploadImage$lambda$16$$inlined$runBIO$1.invoke(CoroutineUtils.kt:23)
	at kotlinx.coroutines.InterruptibleKt.runInterruptibleInExpectedContext(Interruptible.kt:51)
	at kotlinx.coroutines.InterruptibleKt.access$runInterruptibleInExpectedContext(Interruptible.kt:1)
	at kotlinx.coroutines.InterruptibleKt$runInterruptible$2.invokeSuspend(Interruptible.kt:43)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
```

**Comment by Him188** [comment]
你确定你write出去的文件的内容是正确的么，提供一下代码

**Comment by kinhirozane** [comment]
```kotlin
val width = 300
val height = 500
val image = BufferedImage(width, height, BufferedImage.TYPE_INT_RGB)
val font = Font.createFont(Font.TRUETYPE_FONT, this.javaClass.classLoader.getResourceAsStream("fonts/sakura.ttf"))
    .deriveFont(Font.PLAIN, 12f)
val color = Color.pink
val graphics = image.createGraphics()
graphics.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON)
graphics.font = font
graphics.color = color
graphics.fillRect(0, 0, width, height)
graphics.drawString("你好", 10, 10)
graphics.dispose()
ImageIO.write(image, "jpg", AobaChanPaths.data.resolve("image/output.jpg").outputStream())
sendMessage(FileInputStream(AobaChanPaths.data.resolve("image/output.jpg").toFile()).buffered(128).use {
    it.uploadAsImage(fromEvent.subject, "jpg")
})
```

**Comment by kinhirozane** [comment]
> ```kotlin
> val width = 300
> val height = 500
> val image = BufferedImage(width, height, BufferedImage.TYPE_INT_RGB)
> val font = Font.createFont(Font.TRUETYPE_FONT, this.javaClass.classLoader.getResourceAsStream("fonts/sakura.ttf"))
>     .deriveFont(Font.PLAIN, 12f)
> val color = Color.pink
> val graphics = image.createGraphics()
> graphics.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON)
> graphics.font = font
> graphics.color = color
> graphics.fillRect(0, 0, width, height)
> graphics.drawString("你好", 10, 10)
> graphics.dispose()
> ImageIO.write(image, "jpg", AobaChanPaths.data.resolve("image/output.jpg").outputStream())
> sendMessage(FileInputStream(AobaChanPaths.data.resolve("image/output.jpg").toFile()).buffered(128).use {
>     it.uploadAsImage(fromEvent.subject, "jpg")
> })
> ```

AobaChanPaths.data是一个nio的Path路径，基于`MiraiConsole.rootPath.toAbsolutePath().normalize()`使用resolve得到对应名称的路径。

**Comment by sandtechnology** [comment]
我觉得你resolve了一个空文件 请检查文件是否正确创建

**Comment by cssxsh** [comment]
建议 
```
java.io.File("image/output.jpg").toExternalResource().use { 
            
}
```

uploadAsImage 需要随机读取，套一层流反倒会需要把流写道临时文件，然后再二次读取

**Comment by kinhirozane** [comment]
> 建议
> 
> ```
> java.io.File("image/output.jpg").toExternalResource().use { 
>             
> }
> ```
> 
> uploadAsImage 需要随机读取，套一层流反倒会需要把流写道临时文件，然后再二次读取

了解了，经过又一轮测试，除了容易出现文件找不到和文件拒绝访问之外，报告的问题出现了一次，改写了BufferedImage的绘制后解决了EOF问题，考虑你说的外部资源解决另外两个容易报的异常。

**Comment by kinhirozane** [comment]
这个代码是我曾经在图片上绘制图片水印的代码，所以没考虑绘制的问题，因为是把曾经能跑的代码复制过来的，这个EOF经常遇到，但是这次“超出了两个字节”有点上头了。

**Comment by Karlatemp** [comment]
> `ImageIO.write(image, "jpg", AobaChanPaths.data.resolve("image/output.jpg").outputStream())`

What are you doing?

**Comment by kinhirozane** [comment]
write a image file, it work

**Comment by kinhirozane** [comment]
还是有点问题，nio，我是否应该这么写：
```kotlin
val path: Path = AobaChanPaths.data.resolve("image")
val file: File = File(path.toFile(), "img.jpg")
if (!file.exsits()) file.parentFile.mkdirs()
ImageIO.write(image, "jpg", file)
```

**Comment by kinhirozane** [comment]
这是AobaChanPaths的代码：
```kotlin
object AobaChanPaths {
    val root: Path = MiraiConsole.rootPath.toAbsolutePath().normalize()
    val aobachan: Path = root.resolve("aobachan")
    val config: Path = aobachan.resolve("config")
    val data: Path = aobachan.resolve("data")

    init {
        runCatching {
            Files.createDirectories(aobachan)
            Files.createDirectories(config)
            Files.createDirectories(data)
        }
    }
}
```

**Comment by sandtechnology** [comment]
> write a image file, it work

虽然说这是一个Java里代码编写的错误，但是还是有必要提一下 你的流需要关闭 不然状态是未确定的 这也是你遇见这些问题的原因 imageio不会帮你关闭流：
```
Writes an image using an arbitrary ImageWriter that supports the given format to an OutputStream.
This method does not close the provided OutputStream after the write operation has completed; it is the responsibility of the caller to close the stream, if desired.
The current cache settings from getUseCacheand getCacheDirectory will be used to control caching.
```
你遇见的问题应该都是因为这个原因
