### ISSUE TITLE
希望有“好友添加成功”的事件

### ISSUE THREAD

**Issue by fkxxyz** [mamoe/mirai#2616]
机器人进入了新群能收到事件。类似地，希望有“好友添加成功”的事件。

这样方便发送发送一些打招呼的消息。

**Comment by cssxsh** [comment]
https://github.com/mamoe/mirai/blob/dev/docs/EventList.md#%E5%A5%BD%E5%8F%8B

https://github.com/mamoe/mirai/blob/50d37c484a73f184b6d4ae4756ca4666324d2f66/docs/EventList.md?plain=1#L97-L104
