### ISSUE TITLE
Correct the classpath of your application so that it contains a single, compatible version of net.mamoe.mirai.internal.utils.MiraiProtocolInternal

### ISSUE THREAD

**Issue by JimmyAndZzZ** [mamoe/mirai#2632]
### 问题描述

Correct the classpath of your application so that it contains a single, compatible version of net.mamoe.mirai.internal.utils.MiraiProtocolInternal

从2.14.0升级到2.15.0-M1

### 复现

从2.14.0升级到2.15.0-M1

### mirai-core 版本

2.14.0

### bot-protocol

ANDROID_PHONE

**Comment by MrXiaoM** [comment]
- [ ] 使用的是 mirai-console 还是 mirai-core
- [ ] 依赖是否重复

**Comment by JimmyAndZzZ** [comment]
core-jvm，依赖目前看了没有重复
![image](https://user-images.githubusercontent.com/26839069/232456026-36f5a924-1ca5-455a-8350-e9c6dccfb448.png)

**Comment by cssxsh** [comment]
是否使用了 https://github.com/cssxsh/fix-protocol-version
如果是，请去掉这个依赖，它只在 2.14 下工作

**Comment by JimmyAndZzZ** [comment]
我试试看，感谢

**Comment by JimmyAndZzZ** [comment]
补充请教下，有java版本的扫码登录吗

**Comment by Him188** [comment]
问题解决了？

如果没有解决，提供日志，提供你错误的来源（是什么工具），提供你启动或使用 mirai 的方式
