### ISSUE TITLE
建议为 ProducerFailureException 添加 message

### ISSUE THREAD

**Issue by MrXiaoM** [mamoe/mirai#2634]
QQ群里应该不会有普通用户发一长串日志或者懂得使用 pastebin 的，他们向群友求助通常都是截图。我遇到过好几个用户在 2.15.0-M1 发登录失败的截图只截到 ProducerFailureException 没有截到 cause 的。避免向用户询问更详细的日志，产生不必要的麻烦，不如把异常消息放在前面。
建议把 cause 的类型和 cause.message 放到 ProducerFailureException 的 message 中。

**Comment by cssxsh** [comment]
https://github.com/mamoe/mirai/commit/578d1a9d48cd029e440ff7a5e4a9a62e28476635

**Comment by Him188** [comment]
这个异常是 internal bug, 不是正常情况会抛的
