### ISSUE TITLE
NudgeEvent和SignEvent似乎无法被正常触发

### ISSUE THREAD

**Issue by disymayufei** [mamoe/mirai#2637]
### 问题描述

我是依赖mirai-core 2.15.0-M1进行开发的，然后在尝试在通道中注册了SignEvent和NudgeEvent这两个事件的过程中，发现这两个事件似乎总无法被正常触发，不论是在群里戳机器人还是进行打卡，均无法正常执行监听器内的方法。后来我又尝试在全局信息通道中捕获并输出所有事件，但同样在戳机器人或者打卡后，没有任何输出，而其他的事件（比如群员权限改变，有人入群，群聊/私聊有消息被发送等）都是正常的。

### 复现

1. 依赖2.15.0-M1 JVM版本的mirai-core，使用AZul OpenJDK 17进行开发
2. 通过机器人的通道注册事件：botInstance.getEventChannel().subscribeAlways(NudgeEvent.class, event -> {// code});
3. // code 处的代码永远不会被执行
4. 通过全局通道注册所有事件：GlobalEventChannel.INSTANCE.subscribeAlways(Event.class, event -> System.out.println("触发事件：" + event.getClass()));
5. 在戳机器人，戳群员，群打卡后，不会有任何输出。

### mirai-core 版本

2.15.0-M1

### bot-protocol

MACOS

### 其他组件版本

无

### 系统日志

```text
被戳一戳/群打卡时，没有任何日志被输出
```

### 网络日志

```text
被戳一戳/群打卡时，没有任何日志被输出
```

### 补充信息

其他几乎所有事件都是正常的，唯独这两个事件完全不行，不知道是不是由于我的错误导致的。

**Comment by StageGuard** [comment]
用的什么协议

**Comment by disymayufei** [comment]
> 用的什么协议

![image](https://user-images.githubusercontent.com/72013933/232966276-22a3b6e0-0b70-427f-ab34-98759b5eae27.png)
MACOS

**Comment by StageGuard** [comment]
> > 用的什么协议
> 
> ![image](https://user-images.githubusercontent.com/72013933/232966276-22a3b6e0-0b70-427f-ab34-98759b5eae27.png) MACOS

换 ANDROID_PHONE, ANDROID_PAD 或 IPAD 试一下

**Comment by cssxsh** [comment]
`MACOS` 不支持 `NudgeEvent` 和 `SignEvent`
