### ISSUE TITLE
安装mcl时选择自动下载java会闪退

### ISSUE THREAD

**Issue by Testplayers** [mamoe/mirai#2638]
### 问题描述

[mcl-installer-ae9f946-windows-amd64.exe](https://github.com/iTXTech/mcl-installer/releases/download/ae9f946/mcl-installer-ae9f946-windows-amd64.exe)
选择自动下载java会闪退

### 复现

[mcl-installer-ae9f946-windows-amd64.exe](https://github.com/iTXTech/mcl-installer/releases/download/ae9f946/mcl-installer-ae9f946-windows-amd64.exe)
选择自动下载java会闪退

### mirai-core 版本

-

### bot-protocol

ANDROID_PHONE

**Comment by StageGuard** [comment]
在 mcl-installer 反馈即可
