### ISSUE TITLE
支持 mirai 码解析

### ISSUE THREAD

**Issue by lliioollcn** [mamoe/mirai#264]
建议添加mirai码，类似酷Q码那样，可以更简便的发送/处理比如图片、AT等等XD

**Comment by Him188** [comment]
码的效率十分低下. 应使用消息连接.

**Comment by Him188** [comment]
但考虑后还是可以为图片, 表情等简单的元素支持码的解析

**Comment by Karlatemp** [comment]
希望不要直接加到String.toMessage()去，不然可能引发许多问题

**Comment by Chenwe-i-lin** [comment]
不推荐加入该特性, 但可以转化为 xml/html 的形式表示

**Comment by takayama-lily** [comment]
码确实有必要，但不一定要放入core里。
希望core的功能越原始越好

**Comment by Him188** [comment]
码只需要非常小的体积，独立模块维护起来是一个麻烦

**Comment by Him188** [comment]
因此它一定会在core里。体积实际上没有考虑的必要，因为一多半的体积都是协议占的。

**Comment by Him188** [comment]
计划添加 `String.miraiCodeToMessage(): MessageChain`，Java使用 `MessageUtils` 中 `MessageChain miraiCodeToMessage(String code)`

支持单个或多个消息。

**Comment by Chenwe-i-lin** [comment]
*不可名状的叫声*

**Comment by takayama-lily** [comment]
我觉得放到console里也可以

**Comment by Him188** [comment]
已经实现为 `mirai-serialization`，与序列化放在同一个模块。1.1.0版本起同步 `mirai-core` 发布

**Comment by Him188** [comment]
https://github.com/mamoe/mirai/blob/dev/docs/mirai-code-specification.md
