### ISSUE TITLE
关于扫码登陆二维码

### ISSUE THREAD

**Issue by MrY-Cat** [mamoe/mirai#2641]
### 问题描述

扫码登陆的控制台字符画好像太大了，整个屏幕显示不完整，虽然太小了可能会不清楚，但是太大了也不方便，每次需要长截图扫或者去C:\Users\用户\AppData\Local\Temp里面找图片。感觉可以稍微变小一些（如果可以的话）

### 复现

使用扫码登陆即可

### mirai-core 版本

2.15.0-M1

### bot-protocol

ANDROID_WATCH

**Comment by MrY-Cat** [comment]
大约只能显示出来高的75%-80%
（我怎么评论上传不了图片(>д<)ﾉ）

**Comment by Karlatemp** [comment]
#2591
