### ISSUE TITLE
ANDROID_WATCH协议下GroupMessageEvent究竟什么情形下收不到

### ISSUE THREAD

**Issue by MrY-Cat** [mamoe/mirai#2643]
### 问题描述

如题，想讨论下ANDROID_WATCH协议下GroupMessageEvent究竟什么情形下收不到。
众所周知手机端群消息设置有4种，为方便表述分别用字母代替：
A-"接收消息并提醒"、B-"接收消息但不提醒"、C-"收进群助手且不提醒"、D-"屏蔽消息"

有人说为C/D设置的群不会收到消息，有人说为B/C/D设置的群不会收到消息，有人说B设置的群需要在手机端点开才能收到消息，有人说B设置的群需要主动发消息才能收到消息，等等

今天使用所有群消息设置均为B且长期未使用ANDROID_WATCH协议登录过的bot账号，用ANDROID_WATCH协议登录后的情况是：
1.刚登录上--->群1和群2都收不到消息。
2.随后打开手机端QQ停留在消息列表什么都没做（bot本身一直就在手机端挂着）--->群1可以收到消息了（也许是由于群1 是置顶），但群2依然收不到。
3.而后试了试在手机端点进群2--->群2也可以被收到消息了，此时群1也仍然可以收到。但除群1和群2外依然收不到。
4.而后在手机端QQ退出该账号--->群3群4群5等都可以收到消息了，此时群1群2依然也收得到。
5.而后再次登录上手机端QQ--->群1群2群3群4群5等仍然保持收得到消息。

那么可以确定的是，同样为B的群消息设置，不同的群，能不能收到消息，好像影响因素是多样且难以确定的，点开群聊/手机不在线/为置顶群聊，这些似乎都可能有影响但都不是能收到消息的必须条件。

再结合之前的经验，印象里似乎为C/D的群更难以收到消息。

那么ANDROID_WATCH协议下GroupMessageEvent到底啥时候能收到啥时候收不到呢.....((/- -)/

### 复现

使用ANDROID_WATCH协议登录bot即可

### mirai-core 版本

2.15.0-M1

### bot-protocol

ANDROID_WATCH

**Comment by MrY-Cat** [comment]
在上述状态持续1h没有管后，现在情况又变了，群1群3群4群5可以收到消息，群2不能了

更多信息：
bot在群1为群主，在群2群3群4为管理，在群5为普通成员，可见群2变为不能收到消息，和职位关系不大。
在前面1h内，群1群2断断续续有人发言，群3群4群5则已经没人发言了，可见群2变为不能收到消息，和是否一段时间冷群关系不大。
手机端并未进行任何操作，既没有更改群消息设置，也没有离线，也没有点开任何群会话，可见群2变为不能收到消息，和这些也关系不大。

那这...莫非是手表协议内的群消息设置并非和手机一样，还是说对B设置的群而言，手表随缘不接收消息，真就主打一个随缘（？）

**Comment by Lexcellent** [comment]
我也遇到了 目前的就是重启能好一段时间

**Comment by Him188** [comment]
可在论坛继续讨论这类问题
