### ISSUE TITLE
申请优化扫码二维码存储路径

### ISSUE THREAD

**Issue by MrY-Cat** [mamoe/mirai#2647]
由于码比较大经常需要去找那个保存的二维码图片，目前图片的存储位置是：
C:\Users\用户\AppData\Local\Temp\二维码.png
由于Temp文件夹经常有一堆乱七八糟的文件，但文件夹并不多，找文件可能不好找，是否可以优化存储位置为：
C:\Users\用户\AppData\Local\Temp\mirai\二维码.png
然后扫码成功删除二维码的话mirai文件夹可以不删除，这样的好处是比较好找甚至可以把文件夹拿出来生成快捷方式放在桌面或机器人目录。

**Comment by Him188** [comment]
在提示扫码时会打印文件精确路径（file://...），在IDEA内点击蓝色精确路径就能直接打开文件。在外部复制后放到资源管理器地址栏回车，或者在chrome内访问都能直接打开。

这个有可能在 2.15.0-M1 已经有了，但在dev肯定有

**Comment by Him188** [comment]
https://build.mirai.mamoe.net/v1/mirai-core/dev/indexes/latest

试试 2.15.0-dev-68

**Comment by MrY-Cat** [comment]
> 在提示扫码时会打印文件精确路径（file://...），在IDEA内点击蓝色精确路径就能直接打开文件。在外部复制后放到资源管理器地址栏回车，或者在chrome内访问都能直接打开。
> 
> 这个有可能在 2.15.0-M1 已经有了，但在dev肯定有

![image](https://github.com/mamoe/mirai/assets/76583155/aa609225-bd22-4c10-b9d1-b56bfd62aa7c)

2.15.0-M1的路径还是点击不了的

不过就算能点击，还是推荐在目录的C:\Users\用户\AppData\Local\Temp\后加个mirai文件夹再放这个二维码，一方面有很多时候是在后台挂机器人，复制路径需要去找log，另一方面对于应用程序来说，在C:\Users\用户\AppData\Local\Temp\下存放文件时，建立一个属于自己的文件夹是比较好的选择

**Comment by MrXiaoM** [comment]
感觉可以加一个 jvm 参数用来控制是否更改二维码保存目录？

**Comment by Karlatemp** [comment]
使用 file:// 是个坏的做法，不仅破坏了真正的文件路径表示，还导致不能直接在资源管理器打开，不能在搜索栏打开，也不能用作命令行参数

**Comment by Him188** [comment]
那是 URL, 浏览器是支持的, 要用资源管理器只需要少复制前面几个字就行

**Comment by Karlatemp** [comment]
你是不是忘了URL转义

**Comment by Him188** [comment]
那确实会是一个问题

但是我应该是直接往前面 append 了个 `"file://"`
