### ISSUE TITLE
支持群友请求机器人加入群聊事件的解析

### ISSUE THREAD

**Issue by wyapx** [mamoe/mirai#265]
![EHN73TET{ CAM7Y$M}ITWK1](https://user-images.githubusercontent.com/26220729/80206965-e5953f00-865f-11ea-9439-d4add563b3dc.png)
非bug，也无法复现

**Comment by wyapx** [comment]
已经确认包来源是来自群友请求机器人加入群聊

**Comment by Him188** [comment]
#259
