### ISSUE TITLE
添加修改协议信息的API

### ISSUE THREAD

**Issue by Alceatraz** [mamoe/mirai#2651]
起因：https://github.com/cssxsh/fix-protocol-version

建议：添加一个API，重构协议Enum，使用户可以动态的在BotConfig或专门的工具类覆盖掉发布时内置协议版本信息

论点：形似2.14.0的QQ强推更新导致登录情况是否会经常发生？

Off topic：mirai项目太复杂了 我kotlin太菜了 自己尝试改了下，不太行.jpg

**Comment by Him188** [comment]
已经改了
