### ISSUE TITLE
登录无限报 code=45 个人认为可能需要更新协议了

### ISSUE THREAD

**Issue by ieew** [mamoe/mirai#2655]
### 问题描述

已经尝试过的组合：
mirai 2.15 + ANDROID_PHONE / ANDROID_PAD / ANDROID_WATCH / MACOS / IPAD (五个协议都尝试过)
mirai 2.14 + ANDROID_PHONE / ANDROID_PAD / ANDROID_WATCH / MACOS / IPAD (五个协议都尝试过)
均会报 code=45 。
但是后面我拿一个大概1年多没有使用过的 qq 使用 mirai2.14 + ANDROID_PHONE 却意外的发现可以正常登录，只是首次登录需要过滑动验证+短信验证。从第二次登录开始，后续不管是第三次还是第四次还是更多次都必须过一次滑动验证但不要求短信验证。

网络环境：家庭网络 + nas 中的 docker

### 复现

空

### mirai-core 版本

2.15, 2.14

### bot-protocol

ANDROID_PHONE

### 其他组件版本

mirai-api-http: `2.7.1`
mirai-device-generator: `1.1.3`
fix-protocol-version: `1.5.0`

**Comment by qfys521** [comment]
乐

**Comment by Him188** [comment]
看置顶 issue，用最新测试版试试，如果不行就等更新，这种问题在持续处理
