### ISSUE TITLE
mirai的ba插件指令被拦截

### ISSUE THREAD

**Issue by DongGua-Jun** [mamoe/mirai#2656]
### 问题描述

2023-05-06 17:42:55 V/Bot.QQ号: [test(QQ群号)] 东瓜jun(QQ号) -> /活动
2023-05-06 17:42:55 W/main: 指令执行被拦截, 原因: InterceptedReasonData(message=非本插件消息)
 command owned by buildin with NormalMember(QQ号)
 
![QQ截图20230506174312](https://user-images.githubusercontent.com/75875483/236616675-6f69a549-0d08-420f-a71f-4ca30707bc13.png)

### 复现

使用插件相关指令
/活动
/攻略 红兔
/总力战

### mirai-core 版本

version 2.14.0, built on 2023-02-06 14:25:21

### bot-protocol

ANDROID_PHONE

### 其他组件版本

Verifying "net.mamoe:mirai-console" v2.14.0 
Verifying "net.mamoe:mirai-console-terminal" v2.14.0 
Verifying "net.mamoe:mirai-core-all" v2.14.0 
Verifying "org.itxtech:mcl-addon" v2.1.1

**Comment by MrXiaoM** [comment]
~~Invalid issue: 插件问题，非 mirai 框架自身问题~~

该消息是 chat-command 发出的，命令执行被拦截

**Comment by Him188** [comment]
chat command 有 InterceptedReasonData 么

**Comment by DongGua-Jun** [comment]
> ~Invalid issue: 插件问题，非 mirai 框架自身问题~
> 
> 该消息是 chat-command 发出的，命令执行被拦截

是我没给chat-command权限嘛？
ba插件我按照其作者的教程给了/permission add xxxxxx     mcl回了OK

**Comment by MrXiaoM** [comment]
别的插件可以在 onLoad 注册钩子拦截其他命令的执行。
> `CommandCallParserProvider`
> `CommandCallResolverProvider`

检查一下你有没有安装相关的会拦截命令的插件。

**Comment by DongGua-Jun** [comment]
> InterceptedReasonData

![image](https://user-images.githubusercontent.com/75875483/236617684-1e8dc65c-e96b-4abe-8782-6d4c2433bb46.png)
好像没有这个文件夹

**Comment by DongGua-Jun** [comment]
> 

![image](https://user-images.githubusercontent.com/75875483/236617775-2639abe5-16bd-42e8-92f3-302749c92e24.png)
插件列表都在这了，是它【mirai-console-jnr-plugin-1.4.0.mirai2】的问题？

**Comment by MrXiaoM** [comment]
否，是 arona 的问题，通过搜索代码找到了拦截命令相关部分，
https://github.com/diyigemt/arona/blob/1.0.13/arona-core/src/main/kotlin/net/diyigemt/arona/extension/CommandResolver.kt#L35-L37
你需要到它的配置文件设置机器人的qq号才能执行命令，安装这个插件后将限制你的 mirai 只能由一个机器人响应命令。
这段代码在 2.0.0 的分支被注释了，你也可以等更新。

**Comment by DongGua-Jun** [comment]
> ![image](https://user-images.githubusercontent.com/75875483/236617775-2639abe5-16bd-42e8-92f3-302749c92e24.png)
> 插件列表都在这了，是它【mirai-console-jnr-plugin-1.4.0.mirai2】的问题？



> 别的插件可以在 onLoad 注册钩子拦截其他命令的执行。
> 
> > `CommandCallParserProvider`
> > `CommandCallResolverProvider`
> 
> 检查一下你有没有安装相关的会拦截命令的插件。



> 否，是 arona 的问题，通过搜索代码找到了拦截命令相关部分， https://github.com/diyigemt/arona/blob/1.0.13/arona-core/src/main/kotlin/net/diyigemt/arona/extension/CommandResolver.kt#L35-L37 你需要到它的配置文件设置机器人的qq号才能执行命令，安装这个插件后将限制你的 mirai 只能由一个机器人响应命令。 这段代码在 2.0.0 的分支被注释了，你也可以等更新。

这个我装的时候配置了  arona.yml 怎么现在打开变默认模板了，我再配置一下

重启mcl会重置arona.yml内容。怪

**Comment by DongGua-Jun** [comment]
重启服务器之后
尽管还有拦截报错但是能说话了，真奇怪。（能跑就行
![image](https://user-images.githubusercontent.com/75875483/236620631-0ac290b7-ec3d-47be-872e-779bcf946da2.png)

![image](https://user-images.githubusercontent.com/75875483/236620634-cfffb97f-7a48-4f0e-872a-a2ccff5bddc4.png)
