### ISSUE TITLE
控制台没报错，code返回也是发送消息成功，控制台显示消息发送了，但是群里看不到消息

### ISSUE THREAD

**Issue by yuanshangyujingshierlou** [mamoe/mirai#2671]
### 问题描述

控制台没报错，code返回也是发送消息成功，控制台显示消息发送了，但是群里看不到消息

### 复现

突然bot发不出去消息了，看了下控制台没问题，代码调试了一遍也没问题，这是什么情况呢

### mirai-core 版本

2.1.5

### bot-protocol

ANDROID_WATCH

### 其他组件版本

mirai-api-http 2.9.1

### 系统日志

```text
2023-05-26 17:08:35 V/Bot.xxxxxxxxx: [Public Dayz(697785664)] qiyonghan(xxxxxxxxxx) -> [mirai:at:xxxxxxxxxx] 在线人数
2023-05-26 17:08:39 V/Bot.xxxxxxxxx: Group(xxxxxxxxx) <- [mirai:quote:[mirai:source:ids=[67623], internalIds=[1815397569], from group xxxxxxxxxto xxxxxxxxxat 1685092114], content=[mirai:at:xxxxxxxxx] 在线人数]服务器状态：在线，在线人数：13 / 127，服务器延迟：62.0ms, 游戏时间：03:43
```

### 补充信息

控制台显示消息发出去了，但是对应的群内没有消息

**Comment by wwjhc** [comment]
我也是这个问题

**Comment by TihPct** [comment]
我也是这个问题

**Comment by Xiaolangs** [comment]
我也是这个 问题

**Comment by 502milk** [comment]
2.15.0-M1
同样问题+1
我刚出现这个问题
只要是miria发出的，全部看不到

**Comment by TihPct** [comment]
> 2.15.0-M1 同样问题+1 我刚出现这个问题 只要是miria发出的，全部看不到

会不会是新的风控导致的?

**Comment by cssxsh** [comment]
风控

**Comment by 502milk** [comment]
> > 2.15.0-M1 同样问题+1 我刚出现这个问题 只要是miria发出的，全部看不到
> 
> 会不会是新的风控导致的?

不知道...我清了下缓存，然后等了一会重新扫码登陆又好了

**Comment by ghost** [comment]
今天才突然有的这个问题，清了bot缓存，登录了qq，试过所有方法bot都不能发送群消息，也是后台有显示但群里没有消息..

**Comment by TihPct** [comment]
> > > 2.15.0-M1 同样问题+1 我刚出现这个问题 只要是miria发出的，全部看不到
> > 
> > 
> > 会不会是新的风控导致的?
> 
> 不知道...我清了下缓存，然后等了一会重新扫码登陆又好了

今天早上突然又能发送消息了,但是过了5分钟又暴毙了

**Comment by 502milk** [comment]
> > > > 2.15.0-M1 同样问题+1 我刚出现这个问题 只要是miria发出的，全部看不到
> > > 
> > > 
> > > 会不会是新的风控导致的?
> > 
> > 不知道...我清了下缓存，然后等了一会重新扫码登陆又好了
> 
> 今天早上突然又能发送消息了,但是过了5分钟又暴毙了

我的还好，现在挺正常的

**Comment by jiashu1024** [comment]
ANDROID_WATCH 我也是，别的协议都45啥的登不上，只有扫码用watch能登。

**Comment by Yuk-0v0** [comment]
加一...

**Comment by fickle809** [comment]
一样的问题，清了缓存重新登陆也不行..

**Comment by Takeoff0518** [comment]
一样，直接用客户端发就行，用 ANDROID_WATCH 就不行

**Comment by miraiuser9528** [comment]
现在其他协议根本无法登录
扫码协议不能发消息
等于玩完……

**Comment by TihPct** [comment]
> 现在其他协议根本无法登录 扫码协议不能发消息 等于玩完……

是这样的

**Comment by TihPct** [comment]
是不是使用ANDROID_WATCH协议发出的消息都会看不到?

**Comment by surf08** [comment]
用其他协议也登不了啊

**Comment by eikyu721** [comment]
有相同的问题，扫码WATCH登录新账号5分钟后就看不到群消息，私聊可以正常回复。其他协议完全无法登录。
希望mirai的时代不会就此终结...

**Comment by RF-Tar-Railt** [comment]
我这边使用密码登录可用
mirai 2.14.0 + [`fix-protocol-version`](https://github.com/cssxsh/fix-protocol-version) 最新版本 + ANDROID_PAD
甚至没有弹出验证直接登录成功

**Comment by RF-Tar-Railt** [comment]
![BUF{~1UH2OJLM9(NIR%ODZW](https://github.com/mamoe/mirai/assets/42648639/e3b5bbd4-5491-45a7-a8bb-6e174d932142)

**Comment by TihPct** [comment]
> 我这边使用密码登录可用 mirai 2.14.0 + [`fix-protocol-version`](https://github.com/cssxsh/fix-protocol-version) 最新版本 + ANDROID_PAD 甚至没有弹出验证直接登录成功

这或许是一个办法

**Comment by TihPct** [comment]
> > 我这边使用密码登录可用 mirai 2.14.0 + [`fix-protocol-version`](https://github.com/cssxsh/fix-protocol-version) 最新版本 + ANDROID_PAD 甚至没有弹出验证直接登录成功
> 
> 这或许是一个办法

补充回复:使用[`fix-protocol-version`](https://github.com/cssxsh/fix-protocol-version) 最新版本 来进行`ANDROID_PAD`方式成功登录

**Comment by SongW-SW** [comment]
Mirai 2.15版本 + ANDROID_PAD 成功登录，用的方式是F12拿到滑动验证的ticket然后再短信验证。看看这样多久会被封

**Comment by xszqxszq** [comment]
+1，蹲WATCH协议解决方案

**Comment by SongW-SW** [comment]
> Mirai 2.15版本 + ANDROID_PAD 成功登录，用的方式是F12拿到滑动验证的ticket然后再短信验证。看看这样多久会被封

掉线一次后被代码45封锁。更换ANDROID_PHONE之后成功登录。看看再次多久会被封

**Comment by RF-Tar-Railt** [comment]
貌似手表的风控暂时解除了

**Comment by Torther** [comment]
> 貌似手表的风控暂时解除了

目前又开始风控了

**Comment by mckuhei** [comment]
应该和发的内容有关，我发了点阴阳怪气的内容就风控了，但是很快就解了

**Comment by echoidcf** [comment]
我也遇到同样的问题了。
不过说点题外话，能把详细的登录原理整理一下吗？
就不能用自己的设备抓个包啥的，一方面弄个跟自己设备完全一样的device.json，另一方面，既然45那就dump出来一个最新的版本号啥的问题不就解决了吗？
你们精力啥的有限可以发动社区的力量嘛。

**Comment by RF-Tar-Railt** [comment]
> 我也遇到同样的问题了。
> 
> 不过说点题外话，能把详细的登录原理整理一下吗？
> 
> 就不能用自己的设备抓个包啥的，一方面弄个跟自己设备完全一样的device.json，另一方面，既然45那就dump出来一个最新的版本号啥的问题不就解决了吗？
> 
> 你们精力啥的有限可以发动社区的力量嘛。

等2.15 stable

**Comment by MrXiaoM** [comment]
> 我也遇到同样的问题了。
> 不过说点题外话，能把详细的登录原理整理一下吗？
> 就不能用自己的设备抓个包啥的，一方面弄个跟自己设备完全一样的device.json，另一方面，既然45那就dump出来一个最新的版本号啥的问题不就解决了吗？
> 你们精力啥的有限可以发动社区的力量嘛。

1. MrXiaoM/Aoki 可以在 Android 生成设备信息。
2. 45不是单单更新个协议信息就完了，协议实现跟不上也没用。
3. 除了官方文档外，论坛有很多「野生文档」，交流群有群友口口相传的经验，社区力量一直都在。

**Comment by echoidcf** [comment]
> > 我也遇到同样的问题了。
> > 不过说点题外话，能把详细的登录原理整理一下吗？
> > 就不能用自己的设备抓个包啥的，一方面弄个跟自己设备完全一样的device.json，另一方面，既然45那就dump出来一个最新的版本号啥的问题不就解决了吗？
> > 你们精力啥的有限可以发动社区的力量嘛。
> 
> 1. MrXiaoM/Aoki 可以在 Android 生成设备信息。
> 2. 45不是单单更新个协议信息就完了，协议实现跟不上也没用。
> 3. 除了官方文档外，论坛有很多「野生文档」，交流群有群友口口相传的经验，社区力量一直都在。

Aoki我过后试一下。不过最好还是有协议的详细解析，方便抓包分析和增强社区力量。
至于协议信息至少值得试一试，至于实现应该很难大改，要不像现在这样一个月一个新版本腾讯自己也受不了。估计会加一些新东西，用不上也无所谓的那种。至于风险，反正也是我自己担着。
至于论坛，我再翻一翻吧，感觉社区力量十分薄弱。

**Comment by RF-Tar-Railt** [comment]
> 我也遇到同样的问题了。
> 
> 不过说点题外话，能把详细的登录原理整理一下吗？
> 
> 就不能用自己的设备抓个包啥的，一方面弄个跟自己设备完全一样的device.json，另一方面，既然45那就dump出来一个最新的版本号啥的问题不就解决了吗？
> 
> 你们精力啥的有限可以发动社区的力量嘛。

https://github.com/Mrs4s/go-cqhttp/issues/2183

**Comment by zhengyuelai** [comment]
go-cqhttp那边加了个临时方案，似乎能用了？https://github.com/Mrs4s/go-cqhttp/issues/2183

**Comment by StageGuard** [comment]
请尝试使用 [`60d360b`](https://github.com/mamoe/mirai/commit/60d360baada2ba4ac37835fc2b5710ee8ddf84df) 或之后的 snapshot 构建。

## 针对 `mirai-console` 使用者（通过 `mirai-console-loader` 或其他启动方式）
以最新构建为例，访问 mirai snapshot 仓库，下载 `mirai-core`, `mirai-core-api` 和 `mirai-core-utils` 的版本为 `2.15.0-dev-97` 的构建文件。

* 访问 https://repo.mirai.mamoe.net/snapshots/net/mamoe/mirai-core-jvm/2.15.0-dev-97
下载 `mirai-core-jvm-2.15.0-dev-97.jar`
* 访问 https://repo.mirai.mamoe.net/snapshots/net/mamoe/mirai-core-api-jvm/2.15.0-dev-97
下载 `mirai-core-api-jvm-2.15.0-dev-97.jar`
* 访问 https://repo.mirai.mamoe.net/snapshots/net/mamoe/mirai-core-utils-jvm/2.15.0-dev-97
下载 `mirai-core-utils-jvm-2.15.0-dev-97.jar`
* 访问 https://repo.mirai.mamoe.net/snapshots/net/mamoe/mirai-console/2.15.0-dev-97 
下载 `mirai-console-2.15.0-dev-97-all.jar`

下载好后，按照如下步骤操作：
* 首先删除 mirai-console 根目录下的 `libs` 目录的所有文件。
* 打开 `config.json`，将 `net.mamoe:mirai-core-all`，`net.mamoe:mirai-console-terminal` 和 `net.mamoe:mirai-console` 的版本改为 `2.15.0-M1`。
* 启动一次 mirai-console-loader，等待其下载库文件。
* 下载完成后（即已经出现 mirai 的 logo）立刻强制关闭 mirai-console-loader。
* 将在 snapshot 仓库下载好的 jar 放入 `libs` 目录中。
* 删除所有的 `sha1` 文件。
* 删除原先的 `mirai-console-2.15.0-M1-all.jar` 文件。
* 用任何压缩软件（如 Bandizip）打开原先的 `mirai-core-all-2.15.0-M1-all.jar`，删除其中的 `net/mamoe/mirai` 包文件夹。

操作完成后，`libs` 中的内容应该和如下图片相同：

![image](https://github.com/mamoe/mirai/assets/45701251/661b4923-9dd3-4934-97f2-8b0ed0b7658c)

* 删除 `bots` 下的登录缓存。
* 通过以下方式启动：
```bash
java -D"file.encoding=utf-8" -cp "./libs/*" net.mamoe.mirai.console.terminal.MiraiConsoleTerminalLoader
```

启动成功后尝试**使用 `ANDROID_PHONE` 协议**登录，其他协议与稳定版相同，仅更新了手机协议。

### 注意：
* 每一个 snapshot 版本仅保留一个月，若发现此评论中的构建已被删除，请自动替换为最新构建的版本号。
* mirai 构建的文件没有签名校验，所以可以直接删除 jar 中的类。
* snapshot 构建没有依赖，所以借用原先包含依赖的 `mirai-core-all` 中的依赖。 

## 针对基于 `mirai-core` 开发的开发者
查看 [UsingSnapshots.md](https://github.com/mamoe/mirai/blob/dev/docs/UsingSnapshots.md)

## 其他信息
mirai snapshot 构建仓库：https://repo.mirai.mamoe.net/
获取 dev 分支最新构建依赖版本号的方法：

![image](https://github.com/mamoe/mirai/assets/45701251/4151f653-720c-40cb-9e8b-9e7a174542f4)
![image](https://github.com/mamoe/mirai/assets/45701251/cfb92148-ea5d-4adb-a3b0-75c54b5c2d0a)
![image](https://github.com/mamoe/mirai/assets/45701251/d8cd2536-735f-4103-9981-717d0795aa1c)

**Comment by SongW-SW** [comment]
用了 [StageGuard] 的方法，完全按照每个步骤来，怎么还是45呀，乌乌

**Comment by Takeoff0518** [comment]
采用 StageGuard 的方法仍然抛出 45，但是手表好像不风控了，是不是 dev-97 的效果仍然未知。

upd: 手表又风控了。

**Comment by StageGuard** [comment]
> 采用 StageGuard 的方法仍然抛出 45，但是手表好像不风控了，是不是 dev-97 的效果仍然未知。
> 
> upd: 手表又风控了。

确认是 ANDROID_PHONE 协议吗

**Comment by Takeoff0518** [comment]
> > 采用 StageGuard 的方法仍然抛出 45，但是手表好像不风控了，是不是 dev-97 的效果仍然未知。
> > upd: 手表又风控了。
> 
> 确认是 ANDROID_PHONE 协议吗

是的

**Comment by StageGuard** [comment]
> > > 采用 StageGuard 的方法仍然抛出 45，但是手表好像不风控了，是不是 dev-97 的效果仍然未知。
> > > upd: 手表又风控了。
> > 
> > 
> > 确认是 ANDROID_PHONE 协议吗
> 
> 是的

那可能是 tx 又拉闸了一次，我在起草这个 pr 到 merge 之后的一天内是百分百可以登录的，测试了很多账号，merge 之后就拉闸了

**Comment by misakarinkon** [comment]
除了手表，同样各种协议都是 45

**Comment by bili-22** [comment]
同45

**Comment by MrY-Cat** [comment]
同45

**Comment by RF-Tar-Railt** [comment]
这个pr已经合了

https://github.com/mamoe/mirai/pull/2566

大抵rc版快发布了

**Comment by kotlinnut** [comment]
应该是最近敏感时期才搞的风控吧，我看别的平台现在id和签名都改不了，包括直播标题，过了这段时间应该会好点..

**Comment by Natsukage** [comment]
> 


> 应该是最近敏感时期才搞的风控吧，我看别的平台现在id和签名都改不了，包括直播标题，过了这段时间应该会好点..



> 应该是最近敏感时期才搞的风控吧，我看别的平台现在id和签名都改不了，包括直播标题，过了这段时间应该会好点..

你如果关注过就会发现235 238都是去年就有的了，45也是今年年初就开始了，并不是最近才有的问题。
已经实装的加密和协议更新总不可能还特地给你撤下来吧（

**Comment by kotlinnut** [comment]
> > 
> 
> > 应该是最近敏感时期才搞的风控吧，我看别的平台现在id和签名都改不了，包括直播标题，过了这段时间应该会好点..
> 
> > 应该是最近敏感时期才搞的风控吧，我看别的平台现在id和签名都改不了，包括直播标题，过了这段时间应该会好点..
> 
> 你如果关注过就会发现235 238都是去年就有的了，45也是今年年初就开始了，并不是最近才有的问题。 已经实装的加密和协议更新总不可能还特地给你撤下来吧（

确实，疼子对机器人的制裁就没停过

**Comment by gebederry** [comment]
[StageGuard 的方法也是 code 45](https://github.com/mamoe/mirai/issues/2671#issuecomment-1574606368)

所以目前我这边现在只有手表能登入，然而手表协议还风控，每天只有上午 8 时会暂时解除风控，过一两个小时之后再次被风控。每天如此。

**Comment by Takeoff0518** [comment]
[dev98](https://github.com/mamoe/mirai/pull/2566) 登录失败，昨天新的版本都不行（仍然是 ANDROID_PHONE code=45）

**Comment by kuronekonano** [comment]
我这边的表现是，登陆正常，部分插件文字回复功能正常，发图功能完全正常，但是一部分插件的文字回复在控制台显示成功了，也有内容，但是群聊里看不到消息。曾经怀疑过是 mirai-http-api 的问题，后来发现不是。
有部分插件正常，部分不正常的现象感觉是调用了不同的 package 导致的，也许是一些插件调用了某个坏掉的 package 所以导致发不出去，也不报错。环境如下
Running MiraiConsole v2.15.0-M1, built on 2023-03-21 22:16:35.
Frontend Terminal: version 2.15.0-M1, provided by Mamoe Technologies

Permission Service: Built In Permission Service

Plugins: ImagePlugins v0.1.0, nbnhhsh v1.0.2, Lolicon v6.0.8, Chat Command v0.5.0, MaimaiBot v1.3.6, SteamHelper v1.0.13, fix-protocol-version v1.5.0, mirai-api-http v2.9.1, mirai-device-generator v1.1.3, weibo-helper v1.6.1, mirai-skia-plugin v1.3.1, PetPet v5.4, BiliBili Dynamic v3.2.9, MCL Addon v2.1.1, mirai-hibernate-plugin v2.7.1, mirai-hibernate-http v1.1.1, meme-helper v1.2.0

举例来说回复不正常的插件：
weibo-helper v1.6.1,
SteamHelper v1.0.13, 
PetPet v5.4
BiliBili Dynamic v3.2.9
以上插件图片发送是正常的，文字回复基本都挂了，控制台显示发送了，也不报错，群聊里啥也没发生
以下插件是正常的，即文字回复完全没问题，群聊能正常收到内容
nbnhhsh v1.0.2
MaimaiBot v1.3.6

**Comment by xszqxszq** [comment]
> 我这边的表现是，登陆正常，部分插件文字回复功能正常，发图功能完全正常，但是一部分插件的文字回复在控制台显示成功了，也有内容，但是群聊里看不到消息。曾经怀疑过是 mirai-http-api 的问题，后来发现不是。 有部分插件正常，部分不正常的现象感觉是调用了不同的 package 导致的，也许是一些插件调用了某个坏掉的 package 所以导致发不出去，也不报错。环境如下 Running MiraiConsole v2.15.0-M1, built on 2023-03-21 22:16:35. Frontend Terminal: version 2.15.0-M1, provided by Mamoe Technologies
> 
> Permission Service: Built In Permission Service
> 
> Plugins: ImagePlugins v0.1.0, nbnhhsh v1.0.2, Lolicon v6.0.8, Chat Command v0.5.0, MaimaiBot v1.3.6, SteamHelper v1.0.13, fix-protocol-version v1.5.0, mirai-api-http v2.9.1, mirai-device-generator v1.1.3, weibo-helper v1.6.1, mirai-skia-plugin v1.3.1, PetPet v5.4, BiliBili Dynamic v3.2.9, MCL Addon v2.1.1, mirai-hibernate-plugin v2.7.1, mirai-hibernate-http v1.1.1, meme-helper v1.2.0
> 
> 举例来说回复不正常的插件： weibo-helper v1.6.1, SteamHelper v1.0.13, PetPet v5.4 BiliBili Dynamic v3.2.9 以上插件图片发送是正常的，文字回复基本都挂了，控制台显示发送了，也不报错，群聊里啥也没发生 以下插件是正常的，即文字回复完全没问题，群聊能正常收到内容 nbnhhsh v1.0.2 MaimaiBot v1.3.6

MaimaiBot构建时用的是v2.15.0-M1，上面几个不正常的是v2.14.0或者更老的版本，可能是这个原因？

不过没想到不同插件表现居然还不一样

**Comment by SongW-SW** [comment]
> > 我这边的表现是，登陆正常，部分插件文字回复功能正常，发图功能完全正常，但是一部分插件的文字回复在控制台显示成功了，也有内容，但是群聊里看不到消息。曾经怀疑过是 mirai-http-api 的问题，后来发现不是。 有部分插件正常，部分不正常的现象感觉是调用了不同的 package 导致的，也许是一些插件调用了某个坏掉的 package 所以导致发不出去，也不报错。环境如下 Running MiraiConsole v2.15.0-M1, built on 2023-03-21 22:16:35. Frontend Terminal: version 2.15.0-M1, provided by Mamoe Technologies
> > Permission Service: Built In Permission Service
> > Plugins: ImagePlugins v0.1.0, nbnhhsh v1.0.2, Lolicon v6.0.8, Chat Command v0.5.0, MaimaiBot v1.3.6, SteamHelper v1.0.13, fix-protocol-version v1.5.0, mirai-api-http v2.9.1, mirai-device-generator v1.1.3, weibo-helper v1.6.1, mirai-skia-plugin v1.3.1, PetPet v5.4, BiliBili Dynamic v3.2.9, MCL Addon v2.1.1, mirai-hibernate-plugin v2.7.1, mirai-hibernate-http v1.1.1, meme-helper v1.2.0
> > 举例来说回复不正常的插件： weibo-helper v1.6.1, SteamHelper v1.0.13, PetPet v5.4 BiliBili Dynamic v3.2.9 以上插件图片发送是正常的，文字回复基本都挂了，控制台显示发送了，也不报错，群聊里啥也没发生 以下插件是正常的，即文字回复完全没问题，群聊能正常收到内容 nbnhhsh v1.0.2 MaimaiBot v1.3.6
> 
> MaimaiBot构建时用的是v2.15.0-M1，上面几个不正常的是v2.14.0或者更老的版本，可能是这个原因？
> 
> 不过没想到不同插件表现居然还不一样

我不用插件，用的是Garia-Ariadne，也是2.15.0-M1但是还是发不出来。这么说应该等Ariadne更新嘛。

**Comment by RF-Tar-Railt** [comment]
> > > 我这边的表现是，登陆正常，部分插件文字回复功能正常，发图功能完全正常，但是一部分插件的文字回复在控制台显示成功了，也有内容，但是群聊里看不到消息。曾经怀疑过是 mirai-http-api 的问题，后来发现不是。 有部分插件正常，部分不正常的现象感觉是调用了不同的 package 导致的，也许是一些插件调用了某个坏掉的 package 所以导致发不出去，也不报错。环境如下 Running MiraiConsole v2.15.0-M1, built on 2023-03-21 22:16:35. Frontend Terminal: version 2.15.0-M1, provided by Mamoe Technologies
> 
> > > Permission Service: Built In Permission Service
> 
> > > Plugins: ImagePlugins v0.1.0, nbnhhsh v1.0.2, Lolicon v6.0.8, Chat Command v0.5.0, MaimaiBot v1.3.6, SteamHelper v1.0.13, fix-protocol-version v1.5.0, mirai-api-http v2.9.1, mirai-device-generator v1.1.3, weibo-helper v1.6.1, mirai-skia-plugin v1.3.1, PetPet v5.4, BiliBili Dynamic v3.2.9, MCL Addon v2.1.1, mirai-hibernate-plugin v2.7.1, mirai-hibernate-http v1.1.1, meme-helper v1.2.0
> 
> > > 举例来说回复不正常的插件： weibo-helper v1.6.1, SteamHelper v1.0.13, PetPet v5.4 BiliBili Dynamic v3.2.9 以上插件图片发送是正常的，文字回复基本都挂了，控制台显示发送了，也不报错，群聊里啥也没发生 以下插件是正常的，即文字回复完全没问题，群聊能正常收到内容 nbnhhsh v1.0.2 MaimaiBot v1.3.6
> 
> > 
> 
> > MaimaiBot构建时用的是v2.15.0-M1，上面几个不正常的是v2.14.0或者更老的版本，可能是这个原因？
> 
> > 
> 
> > 不过没想到不同插件表现居然还不一样
> 
> 
> 
> 我不用插件，用的是Garia-Ariadne，也是2.15.0-M1但是还是发不出来。这么说应该等Ariadne更新嘛。

发不出来大概还是风控的问题吧

**Comment by Lawaxi** [comment]
怎么搞都是45啊（恼

**Comment by FightingAction** [comment]
10个机器人，已经有4个触发code45 ， 太惨了，怎么都上不去

**Comment by Lawaxi** [comment]
> 10个机器人，已经有4个触发code45 ， 太惨了，怎么都上不去

刚才试了下扫码登录插件，能进了。https://github.com/MrXiaoM/mirai-console-dev-qrlogin

**Comment by Takeoff0518** [comment]
现在找到一种可能可行的 `45` 退化至 `237` 的方式，使用 Mirai 2.15.0-M1（非 rc、dev 版本）：

1. 删除（备份）`bots` 下文件，并将 `AutoLogin.yml` 中的协议改为 `ANDROID_PHONE`，注意禁用 fix-protocol-version。
2. 启动 MCL，触发登录并进行滑动验证，出现 `code=45` 后重启 MCL 登录（不要用 `login` 指令重新登录），注意不要删除配置文件。

3. 重复上面第 2 步步骤，直至出现 `code=237`（一般两次左右就能成功复现）。

现在只能努力到这了，暂时还没找到成功登录的方式。

upd: 
1. 貌似需要出现 `235` 才有登录希望。
2. 在出现 `237` 后间隔 6-7h 再次尝试登录会重新回到 `45` 状态。
3. 目前据我观察，手表协议发文字和带图片的消息链都触发风控概率小；但是发单张图片或者 json 卡片基本上 100% 触发风控。

**Comment by SongW-SW** [comment]
> 现在找到一种可能可行的 `45` 退化至 `237` 的方式，使用 Mirai 2.15.0-M1（非 rc、dev 版本）：
> 
> 1. 删除（备份）`bots` 下文件，并将 `AutoLogin.yml` 中的协议改为 `ANDROID_PHONE`，注意禁用 fix-protocol-version。
> 2. 启动 MCL，触发登录并进行滑动验证，出现 `code=45` 后重启 MCL 登录（不要用 `login` 指令重新登录），注意不要删除配置文件。
> 3. 重复上面第 2 步步骤，直至出现 `code=237`（一般两次左右就能成功复现）。
> 
> 现在只能努力到这了，暂时还没找到成功登录的方式。
> 
> upd:
> 
> 1. 貌似需要出现 `235` 才有登录希望。
> 2. 在出现 `237` 后间隔 6-7h 再次尝试登录会重新回到 `45` 状态。
> 3. 目前据我观察，手表协议发文字和带图片的消息链都触发风控概率小；但是发单张图片或者 json 卡片基本上 100% 触发风控。

我偶尔也达到237的状态，但是用任何方法都没法登陆。我的机器人确实经常发单张图片，所以导致手表登上去后几分钟内就被封控？我今天试试看不发图片

**Comment by Takeoff0518** [comment]
> 我偶尔也达到237的状态，但是用任何方法都没法登陆。我的机器人确实经常发单张图片，所以导致手表登上去后几分钟内就被封控？我今天试试看不发图片

隔壁群有大佬说用这种方式炸出来了 `235`，然后删除配置文件后登录成功，反正我现在一直 `237`，麻了。

**Comment by SongW-SW** [comment]
> > 我偶尔也达到237的状态，但是用任何方法都没法登陆。我的机器人确实经常发单张图片，所以导致手表登上去后几分钟内就被封控？我今天试试看不发图片
> 
> 隔壁群有大佬说用这种方式炸出来了 `235`，然后删除配置文件后登录成功，反正我现在一直 `237`，麻了。

好哥哥有没有什么交流群加个一起交流

**Comment by SongW-SW** [comment]
> > > > 我偶尔也达到237的状态，但是用任何方法都没法登陆。我的机器人确实经常发单张图片，所以导致手表登上去后几分钟内就被封控？我今天试试看不发图片
> > > 
> > > 
> > > 隔壁群有大佬说用这种方式炸出来了 `235`，然后删除配置文件后登录成功，反正我现在一直 `237`，麻了。
> > 
> > 
> > 好哥哥有没有什么交流群加个一起交流
> 
> 非官方的：780594692

谢谢好哥哥，加了

**Comment by Him188** [comment]
#2688
