### ISSUE TITLE
由于QQ版本过低导致无法登录

### ISSUE THREAD

**Issue by 0O0o0oOoO00** [mamoe/mirai#2673]
### 问题描述

由于QQ版本过低导致无法登录

### 复现

执行`login qq号 密码 ANDROID_PAD`

### mirai-core 版本

2.14.0

### bot-protocol

ANDROID_PAD

### 其他组件版本

Running MiraiConsole v2.14.0, built on 2023-02-06 14:25:21.
Frontend Terminal: version 2.14.0, provided by Mamoe Technologies

Permission Service: Built In Permission Service

Plugins: mirai-api-http v2.9.1, MCL Addon v2.1.1

Object Pending Finalization Count: 0
                 committed |  init   |  used   |  max
    Heap Memory:  108.0MB  | 222.0MB | 50.51MB | 3.46GB
Non-Heap Memory:  77.81MB  | 7.31MB  | 75.19MB |   -1

### 补充信息

[2023-05-27.log](https://github.com/mamoe/mirai/files/11581659/2023-05-27.log)
![123](https://github.com/mamoe/mirai/assets/11174151/edd73ebd-51e4-49c9-afff-1ac878570ba2)
[2023-05-26.log](https://github.com/mamoe/mirai/files/11581660/2023-05-26.log)

**Comment by 0O0o0oOoO00** [comment]
多次删除device.json并重新生成后依旧无法解决

**Comment by miraiuser9528** [comment]
现在其他协议根本无法登录啊
2.15M1 扫码能登，但是发不了几句消息就被风控无法发送群消息
除了老Q账号密码自动登录还能用，其他基本等于直接玩完……

**Comment by for3ever3** [comment]
我试了一下，我在我本地架设是直接能登上去的，但是在我的服务器，直接G，无论什么方法，都得过滑动验证，然后爆红

**Comment by for3ever3** [comment]
> 
完蛋，我本地也炸了

**Comment by RF-Tar-Railt** [comment]
装一个 [`fix-protocol-version`](https://github.com/cssxsh/fix-protocol-version) 最新版本

**Comment by RF-Tar-Railt** [comment]
> 现在其他协议根本无法登录啊 2.15M1 扫码能登，但是发不了几句消息就被风控无法发送群消息 除了老Q账号密码自动登录还能用，其他基本等于直接玩完……

2.14.0 + [`fix-protocol-version`](https://github.com/cssxsh/fix-protocol-version) 最新版本 + ANDROID_PAD 或 ANDROID_PHONE

**Comment by 0O0o0oOoO00** [comment]
> 装一个 [`fix-protocol-version`](https://github.com/cssxsh/fix-protocol-version) 最新版本

装了最新的`fix-protocol-version`依旧无法解决

![456](https://github.com/mamoe/mirai/assets/11174151/0929e1a7-b5d0-4b23-8ca2-2044098d2a2b)

**Comment by RF-Tar-Railt** [comment]
> > 装一个 [`fix-protocol-version`](https://github.com/cssxsh/fix-protocol-version) 最新版本
> 
> 
> 
> 装了最新的`fix-protocol-version`依旧无法解决
> 
> 
> 
> ![456](https://github.com/mamoe/mirai/assets/11174151/0929e1a7-b5d0-4b23-8ca2-2044098d2a2b)
> 
> 

删除了之前的bots了吗，然后两种协议都试过了吗

**Comment by RF-Tar-Railt** [comment]
> > 装一个 [`fix-protocol-version`](https://github.com/cssxsh/fix-protocol-version) 最新版本
> 
> 
> 
> 装了最新的`fix-protocol-version`依旧无法解决
> 
> 
> 
> ![456](https://github.com/mamoe/mirai/assets/11174151/0929e1a7-b5d0-4b23-8ca2-2044098d2a2b)
> 
> 

不用device-generator试试

**Comment by 0O0o0oOoO00** [comment]
> > > 装一个 [`fix-protocol-version`](https://github.com/cssxsh/fix-protocol-version) 最新版本
> > 
> > 
> > 
> > 装了最新的`fix-protocol-version`依旧无法解决
> > 
> > 
> > 
> > ![456](https://github.com/mamoe/mirai/assets/11174151/0929e1a7-b5d0-4b23-8ca2-2044098d2a2b)
> > 
> > 
> 
> 不用device-generator试试

还是没办法登录一直返回45

**Comment by RF-Tar-Railt** [comment]
> > > > 装一个 [`fix-protocol-version`](https://github.com/cssxsh/fix-protocol-version) 最新版本
> > > 
> > > 
> > > 
> > > 装了最新的`fix-protocol-version`依旧无法解决
> > > 
> > > 
> > > 
> > > ![456](https://github.com/mamoe/mirai/assets/11174151/0929e1a7-b5d0-4b23-8ca2-2044098d2a2b)
> > > 
> > > 
> > 
> > 不用device-generator试试
> 
> 还是没办法登录一直返回45

可能被tx盯上了（
要不先用真设备挂机几天看看

**Comment by 0O0o0oOoO00** [comment]
> > > > > 装一个 [`fix-protocol-version`](https://github.com/cssxsh/fix-protocol-version) 最新版本
> > > > 
> > > > 
> > > > 
> > > > 装了最新的`fix-protocol-version`依旧无法解决
> > > > 
> > > > 
> > > > 
> > > > ![456](https://github.com/mamoe/mirai/assets/11174151/0929e1a7-b5d0-4b23-8ca2-2044098d2a2b)
> > > > 
> > > > 
> > > 
> > > 不用device-generator试试
> > 
> > 还是没办法登录一直返回45
> 
> 可能被tx盯上了（
> 要不先用真设备挂机几天看看

这个QQ号就是我一直用的大号()

**Comment by RF-Tar-Railt** [comment]
> 看看

你试试去登录设备管理那里把设备清一下

**Comment by 0O0o0oOoO00** [comment]
> > 看看
> 
> 你试试去登录设备管理那里把设备清一下

还是不行，那我过几天再试试

**Comment by yuyuko233** [comment]
原因可能是这个 https://github.com/Mrs4s/go-cqhttp/issues/2183 ?

**Comment by 0O0o0oOoO00** [comment]
一周后观察发现依旧是code=45无法登陆，已经采用了[无法登录的临时处理方案](https://mirai.mamoe.net/topic/223/%E6%97%A0%E6%B3%95%E7%99%BB%E5%BD%95%E7%9A%84%E4%B8%B4%E6%97%B6%E5%A4%84%E7%90%86%E6%96%B9%E6%A1%88)该方案处理

**Comment by kartikzheng** [comment]
> 一周后观察发现依旧是code=45无法登陆，已经采用了[https://mirai.mamoe.net/topic/223/%E6%97%A0%E6%B3%95%E7%99%BB%E5%BD%95%E7%9A%84%E4%B8%B4%E6%97%B6%E5%A4%84%E7%90%86%E6%96%B9%E6%A1%88](url)该方案处理

请问这个具体链接是？打开后没有显示具体的问题链接

**Comment by Takeoff0518** [comment]
#2671

**Comment by Him188** [comment]
#2570
