### ISSUE TITLE
java中mirai机器人扫码登录，适应引用mirai-core-jvm包项目

### ISSUE THREAD

**Issue by sqd233** [mamoe/mirai#2676]
有参考mirai-console-dev-qrlogin-0.1.7.jar整合给使用java qq机器人的用户，希望能帮上忙
csdn地址：https://blog.csdn.net/u012930947/article/details/130927411?spm=1001.2014.3001.5502
jar包源码地址：https://github.com/sqd233/java-mirai-qrcode
-----------------
我这里再复述一遍我在csdn文章里的使用方法：
引用jar包后，创建新bot的时候使用 QRCodeBot.getQRCodeBot(你的qq号);
> Bot bot = QRCodeBot.getQRCodeBot(你的qq号);
> bot.login();

假如你用的是springboot启动，启动main方法修改成

> public static void main(String[] args) {
>         SpringApplicationBuilder builder = new SpringApplicationBuilder(BotApplication.class);
>         builder.headless(false).web(WebApplicationType.NONE).run(args);
> }

**Comment by Him188** [comment]
这不是 “issue”，请在论坛发布这类教程内容：
https://mirai.mamoe.net/
