### ISSUE TITLE
无法发出消息或发出消息后看不到的解决办法

### ISSUE THREAD

**Issue by Him188** [mamoe/mirai#2688]
尝试预览版本：
本 commit 的预览版本号: 2.15.0-dev-98 在 <https://github.com/mamoe/mirai/blob/dev/docs/UsingSnapshots.md> 查看如何使用预览版本

获得最新版本号：访问以下接口，`value` 的值就是最新dev 版本号。
https://build.mirai.mamoe.net/v1/mirai-core/dev/indexes/latest

**Comment by KKW557** [comment]
经测试dev-98手表扫码登录一段时间后还是会发消息看不到 3个号都这样

**Comment by bili-22** [comment]
`dev-98`下`ANDROID_WATCH`协议(扫码登录)使用一段时间后无法发出消息，其他协议无法登录

**Comment by Takeoff0518** [comment]
经测试 dev-98 手机、aPad 等协议均无法正常登录，报 `code=45` 错误。
手表协议登录后发送单张图片触发风控。

**Comment by huanmeng-qwq** [comment]
更换到最新dev版本后依旧报`code45`

**Comment by ghost** [comment]
mirai-core-jvm:2.15.0-dev-98
ANDROID_WATCH 测试登录成功

**Comment by a602017206** [comment]
发送群消息看日志已经发送，但是群里面看不到

**Comment by Takeoff0518** [comment]
ANDROID_WATCH 协议目前有风控放宽迹象，相当一部分账号的手表协议不再出现风控情况。（部分可能仍然发不出群消息）

**Comment by Kloping** [comment]
> ANDROID_WATCH 协议目前风控已全面解除。

?

**Comment by Takeoff0518** [comment]
> >ANDROID_WATCH 协议目前有风控放宽迹象，相当一部分账号的手表协议不再出现风控情况。（部分可能仍然发不出群消息）
> 
> ?

反正现在手表暂时不风控了（bot 活了一片），不知道过几天会怎么样。

其他协议仍然 `45`。

**Comment by Kloping** [comment]
> > > ANDROID_WATCH 协议目前风控已全面解除。
> > 
> > 
> > ?
> 
> 反正现在手表暂时不风控了（bot 活了一片），不知道过几天会怎么样。
> 
> 其他协议仍然 `45`。

大部分不带表全部

**Comment by Takeoff0518** [comment]
> > > > ANDROID_WATCH 协议目前有风控放宽迹象，相当一部分账号的手表协议不再出现风控情况。（部分可能仍然发不出群消息）
> > > 
> > > 
> > > ?
> > 
> > 
> > 反正现在手表暂时不风控了（bot 活了一片），不知道过几天会怎么样。
> > 其他协议仍然 `45`。
> 
> 大部分不带表全部

注意到了，已修改。

**Comment by KKW557** [comment]
手表貌似风控宽了 可以发出信息 但是还是有的群会接收不到信息

**Comment by tanfond** [comment]
QQ莫名弹出安全提醒：
![image](https://github.com/mamoe/mirai/assets/96032725/d9c44d97-3413-4f35-a540-105d5f4e6af5)
我账号基本都是自己人，哪来的多人举报？真实奇了怪了

**Comment by Takeoff0518** [comment]
ANDROID_WATCH 协议已于 19:21 左右重新开始严格风控，手表协议 bot 出现了大范围掉线情况。

**Comment by KKW557** [comment]
又开始风控了貌似

**Comment by Takeoff0518** [comment]
采用 [无法登录的临时处理方案](https://mirai.mamoe.net/topic/223/%E6%97%A0%E6%B3%95%E7%99%BB%E5%BD%95%E7%9A%84%E4%B8%B4%E6%97%B6%E5%A4%84%E7%90%86%E6%96%B9%E6%A1%88) 06 月 10 日的解决方案，平板协议直接报 `235`。

**Comment by SongW-SW** [comment]
风控再起

**Comment by xyber-nova** [comment]
2.15.0-M1 + fixprotocol + ANDROID_PHONE协议登录成功
最好想办法触发短信验证，我用下面这个device.json成功触发短信验证（最好别包含mirai字段）
```json
{
    "deviceInfoVersion": 2,
    "data": {
        "display": "GALAXY.222445.001",
        "product": "REDMI",
        "device": "REDMI_WATCH",
        "board": "Android",
        "brand": "Android",
        "model": "MT6735",
        "bootloader": "unknown",
        "fingerprint": "Android/Android/android:10/GALAXY.200122.001/8339099:user/release-keys",
        "bootId": "939C0316-C78D-A1E4-8F99-2B48CD3F8F74",
        "procVersion": "Linux version 3.0.31-2eufpQQr (android-build@xxx.xxx.xxx.xxx.com)",
        "baseBand": "",
        "version": {
            "incremental": "5891938",
            "release": "10",
            "codename": "REL"
        },
        "simInfo": "T-Mobile",
        "osType": "android",
        "macAddress": "02:00:00:00:00:00",
        "wifiBSSID": "02:00:00:00:00:00",
        "wifiSSID": "<unknown ssid>",
        "imsiMd5": "940b34fc8eff8f90169ce32a828bd3ca",
        "imei": "863764359788004",
        "apn": "wifi"
    }
}
```

**Comment by RF-Tar-Railt** [comment]
![image](https://github.com/mamoe/mirai/assets/42648639/0671cc6a-d6c8-41dc-8772-45954216b4e2)
**但是慎用，8.8.88 协议版本可能会让本来能正常登录的账号炸掉**

**Comment by SongW-SW** [comment]
> ![image](https://user-images.githubusercontent.com/42648639/244922615-0671cc6a-d6c8-41dc-8772-45954216b4e2.png) **但是慎用，8.8.88 协议版本可能会让本来能正常登录的账号炸掉**
<s>
有好哥哥知道为什么用这个整合包会出现注册服务失败嘛

2023-06-11 14:56:37 I/fix-protocol-version: 协议版本检查更新...
2023-06-11 14:56:37 I/fix-protocol-version: 注册服务...
2023-06-11 14:56:37 W/fix-protocol-version: 注册服务失败
java.lang.ExceptionInInitializerError
        at fix-protocol-version-1.7.0.mirai2.jar//xyz.cssxsh.mirai.tool.FixProtocolVersionPlugin.onLoad(FixProtocolVersionPlugin.kt:32)
        at net.mamoe.mirai.console.internal.plugin.JvmPluginInternal.internalOnLoad$mirai_console(JvmPluginInternal.kt:373)
        at net.mamoe.mirai.console.internal.plugin.BuiltInJvmPluginLoaderImpl.load(BuiltInJvmPluginLoaderImpl.kt:286)
        at net.mamoe.mirai.console.internal.plugin.BuiltInJvmPluginLoaderImpl.load(BuiltInJvmPluginLoaderImpl.kt:39)
        at net.mamoe.mirai.console.plugin.jvm.JvmPluginLoader$BuiltIn.load(JvmPluginLoader.kt)
        at net.mamoe.mirai.console.plugin.jvm.JvmPluginLoader$BuiltIn.load(JvmPluginLoader.kt:54)
        at net.mamoe.mirai.console.internal.plugin.PluginManagerImpl.loadPluginNoEnable(PluginManagerImpl.kt:96)
        at net.mamoe.mirai.console.internal.plugin.PluginManagerImpl.loadAllPluginsUsingBuiltInLoaders$mirai_console(PluginManagerImpl.kt:152)
        at net.mamoe.mirai.console.internal.MiraiConsoleImplementationBridge.doStart$mirai_console(MiraiConsoleImplementationBridge.kt:302)
        at net.mamoe.mirai.console.MiraiConsoleImplementation$Companion.start(MiraiConsoleImplementation.kt:512)
        at net.mamoe.mirai.console.terminal.MiraiConsoleTerminalLoader.startAsDaemon(MiraiConsoleTerminalLoader.kt:182)
        at net.mamoe.mirai.console.terminal.MiraiConsoleTerminalLoader.startAsDaemon$default(MiraiConsoleTerminalLoader.kt:181)
        at net.mamoe.mirai.console.terminal.MiraiConsoleTerminalLoader.main(MiraiConsoleTerminalLoader.kt:59)
Caused by: java.lang.RuntimeException: Unknown arch x86
        at fix-protocol-version-1.7.0.mirai2.jar//xyz.cssxsh.mirai.tool.TLV544Provider.<clinit>(TLV544Provider.kt:32)
        ... 13 more
2023-06-11 14:56:37 I/plugin: Successfully loaded plugin fix-protocol-version v1.7.0
2023-06-11 14:56:37 I/main: Prepared built-in commands: autoLogin, help, login, logout, permission, status, stop
2023-06-11 14:56:37 I/fix-protocol-version: 当前各协议版本日期:
ANDROID_PHONE  8.9.58.11170  2023-05-18T23:35-04:00
ANDROID_PAD    8.8.88.7083   2022-03-22T23:01:55-04:00
ANDROID_WATCH  2.0.8         2019-06-03T08:25:31-04:00
IPAD           8.9.33.614    2021-12-30T22:36:26-05:00
MACOS          6.7.9         1969-12-31T19:00-05:00

但还是能加载，只是出现code=235 登陆不了
</s>
Edited: 使用最新的1.7.1的fix-protocol包就可以了，这个支持win

**Comment by ghost** [comment]
2.15.0-dev-98 出现 ids = []  空数组，导致消息无法发送
```
11:10:08.306 [DefaultDispatcher-worker-3] com.tenfond.spring.controller.QqMessagePostSendEventListener(QqMessagePostSendEventListener.java:38)
[TRACE] MessagePostSendEvent...
MessageNode{
    bot=Bot(13••••06),
    botId=13••••06,
    subject=Group(72•••74),
    subjectId=72•••74,
    kind=GROUP,
    sender=Bot(13••••06),
    senderId=13••••06,
    target=Group(72•••74),
    targetId=72•••74,
    chain=[mirai:source:ids=[], internalIds=[13•••40], from 13••••06 to group 72•••74 at 16••••05]ForwardMessage(preview=[༺白虎༻: 球的面积怎么求？, 浅笑心柔: 球的面积可以用以下公式求解：], title=浅笑心柔的聊天记录, brief=[回复 @༺白虎༻], source=聊天记录, summary=查看9条回复消息, nodeList=[Node(senderId=24••••43, time=16••••94, senderName=༺白虎༻, messageChain=[mirai:source:ids=[3996], internalIds=[95•••60], from group 24••••43 to 72•••74 at 16••••94]在线问 球的面积怎么求？), Node(senderId=13••••06, time=16••••97, senderName=浅笑心柔, messageChain=球的面积可以用以下公式求解：), Node(senderId=13••••06, time=16••••97, senderName=浅笑心柔, messageChain=$S = 4πr^2$), Node(senderId=13••••06, time=16••••98, senderName=浅笑心柔, messageChain=其中，S表示球面积，π是圆周率（取近似值3.14），r是球的半径。), Node(senderId=13••••06, time=16••••99, senderName=浅笑心柔, messageChain=根据这个公式，计算球的面积的具体步骤如下：), Node(senderId=13••••06, time=16••••01, senderName=浅笑心柔, messageChain=1. 确定球的半径（r）；
2. 将半径带入公式 $S=4πr^2$ 中，进行计算；
3. 得出球的表面积（S）。), Node(senderId=13••••06, time=16••••03, senderName=浅笑心柔, messageChain=例如，如果一个球的半径为5厘米，那么它的表面积就可以通过如下计算得出：), Node(senderId=13••••06, time=16••••04, senderName=浅笑心柔, messageChain=$S=4πr^2$
$S=4×3.14×5^2$
$S=314cm^2$), Node(senderId=13••••06, time=16••••05, senderName=浅笑心柔, messageChain=因此，该球的面积为314平方厘米。)]),
    source=[mirai:source:ids=[], internalIds=[13•••40], from 13••••06 to group 72•••74 at 16••••05],
    ids=[0],
    internalIds=[13•••40],
    time=16••••05,
    hash=-14••••18
}
```

**Comment by a602017206** [comment]
> 2.15.0-M1 + fixprotocol + ANDROID_PHONE协议登录成功 最好想办法触发短信验证，我用下面这个device.json成功触发短信验证（最好别包含mirai字段）
> 
> ```json
> {
>     "deviceInfoVersion": 2,
>     "data": {
>         "display": "GALAXY.222445.001",
>         "product": "REDMI",
>         "device": "REDMI_WATCH",
>         "board": "Android",
>         "brand": "Android",
>         "model": "MT6735",
>         "bootloader": "unknown",
>         "fingerprint": "Android/Android/android:10/GALAXY.200122.001/8339099:user/release-keys",
>         "bootId": "939C0316-C78D-A1E4-8F99-2B48CD3F8F74",
>         "procVersion": "Linux version 3.0.31-2eufpQQr (android-build@xxx.xxx.xxx.xxx.com)",
>         "baseBand": "",
>         "version": {
>             "incremental": "5891938",
>             "release": "10",
>             "codename": "REL"
>         },
>         "simInfo": "T-Mobile",
>         "osType": "android",
>         "macAddress": "02:00:00:00:00:00",
>         "wifiBSSID": "02:00:00:00:00:00",
>         "wifiSSID": "<unknown ssid>",
>         "imsiMd5": "940b34fc8eff8f90169ce32a828bd3ca",
>         "imei": "863764359788004",
>         "apn": "wifi"
>     }
> }
> ```

这个好像也不行了。。。服务器满了导致掉线，这个就登不上了

**Comment by eikyu721** [comment]
> ![image](https://user-images.githubusercontent.com/42648639/244922615-0671cc6a-d6c8-41dc-8772-45954216b4e2.png) **但是慎用，8.8.88 协议版本可能会让本来能正常登录的账号炸掉**

使用一段时间后，发生了和ANDROID_WATCH一样的风控现象，发出的消息无法被看见。

**Comment by RF-Tar-Railt** [comment]
2.14+ fix-protocol-version 1.5 + APAD的情况下至少从今天0点起，私聊出现风控（mirai端正常发送，但是qq端无显示）
出现原因应该是tx最近要求消息强制签名导致私聊无法使用

**Comment by SongW-SW** [comment]
整合包+Android_PAD登陆使用一天后群聊风控

**Comment by RF-Tar-Railt** [comment]
> 2.15.0-dev-98 出现 ids = []  空数组，导致消息无法发送
> 
> ```
> 
> 11:10:08.306 [DefaultDispatcher-worker-3] com.tenfond.spring.controller.QqMessagePostSendEventListener(QqMessagePostSendEventListener.java:38)
> 
> [TRACE] MessagePostSendEvent...
> 
> MessageNode{
> 
>     bot=Bot(13••••06),
> 
>     botId=13••••06,
> 
>     subject=Group(72•••74),
> 
>     subjectId=72•••74,
> 
>     kind=GROUP,
> 
>     sender=Bot(13••••06),
> 
>     senderId=13••••06,
> 
>     target=Group(72•••74),
> 
>     targetId=72•••74,
> 
>     chain=[mirai:source:ids=[], internalIds=[13•••40], from 13••••06 to group 72•••74 at 16••••05]ForwardMessage(preview=[༺白虎༻: 球的面积怎么求？, 浅笑心柔: 球的面积可以用以下公式求解：], title=浅笑心柔的聊天记录, brief=[回复 @༺白虎༻], source=聊天记录, summary=查看9条回复消息, nodeList=[Node(senderId=24••••43, time=16••••94, senderName=༺白虎༻, messageChain=[mirai:source:ids=[3996], internalIds=[95•••60], from group 24••••43 to 72•••74 at 16••••94]在线问 球的面积怎么求？), Node(senderId=13••••06, time=16••••97, senderName=浅笑心柔, messageChain=球的面积可以用以下公式求解：), Node(senderId=13••••06, time=16••••97, senderName=浅笑心柔, messageChain=$S = 4πr^2$), Node(senderId=13••••06, time=16••••98, senderName=浅笑心柔, messageChain=其中，S表示球面积，π是圆周率（取近似值3.14），r是球的半径。), Node(senderId=13••••06, time=16••••99, senderName=浅笑心柔, messageChain=根据这个公式，计算球的面积的具体步骤如下：), Node(senderId=13••••06, time=16••••01, senderName=浅笑心柔, messageChain=1. 确定球的半径（r）；
> 
> 2. 将半径带入公式 $S=4πr^2$ 中，进行计算；
> 
> 3. 得出球的表面积（S）。), Node(senderId=13••••06, time=16••••03, senderName=浅笑心柔, messageChain=例如，如果一个球的半径为5厘米，那么它的表面积就可以通过如下计算得出：), Node(senderId=13••••06, time=16••••04, senderName=浅笑心柔, messageChain=$S=4πr^2$
> 
> $S=4×3.14×5^2$
> 
> $S=314cm^2$), Node(senderId=13••••06, time=16••••05, senderName=浅笑心柔, messageChain=因此，该球的面积为314平方厘米。)]),
> 
>     source=[mirai:source:ids=[], internalIds=[13•••40], from 13••••06 to group 72•••74 at 16••••05],
> 
>     ids=[0],
> 
>     internalIds=[13•••40],
> 
>     time=16••••05,
> 
>     hash=-14••••18
> 
> }
> 
> ```

建议新开一个issue报告此问题

**Comment by Takeoff0518** [comment]
ANDROID_PAD 第一次登录报 `code=235`，删除 `device.json` 并重新登录后 QQ 账号被临时冻结。

**Comment by AtaraxiaEta** [comment]
> 2.14+ fix-protocol-version 1.5 + APAD的情况下至少从今天0点起，私聊出现风控（mirai端正常发送，但是qq端无显示） 出现原因应该是tx最近要求消息强制签名导致私聊无法使用

请问这个目前有解决方案吗？

**Comment by RF-Tar-Railt** [comment]
> > 2.14+ fix-protocol-version 1.5 + APAD的情况下至少从今天0点起，私聊出现风控（mirai端正常发送，但是qq端无显示） 出现原因应该是tx最近要求消息强制签名导致私聊无法使用
> 
> 
> 
> 请问这个目前有解决方案吗？

只能等mirai实现签名
或者尝试现在推荐的协议回退

**Comment by Enderman-TPing** [comment]
手表扫码登还寄不寄

**Comment by RF-Tar-Railt** [comment]
> 手表扫码登还寄不寄

手表扫码还能用，稳定性未知

**Comment by RF-Tar-Railt** [comment]
补充，手表的风控依旧存在
