### ISSUE TITLE
重复发送群组消息

### ISSUE THREAD

**Issue by virink** [mamoe/mirai#269]
## 问题

重复发消息
![image](https://user-images.githubusercontent.com/15978207/80249476-7db51780-86a4-11ea-8e74-77cbad9d58f4.png)
![image](https://user-images.githubusercontent.com/15978207/80250765-0f258900-86a7-11ea-8470-625241d419f0.png)

## 如何复现

0.37.2

```kotlin
val miraiBot = Bot(config.qq, config.passwd).alsoLogin()
miraiBot.subscribeGroupMessages {
    sentFrom(config.group) {
        case("orz") {
            quoteReply("小朋友，你是否有很多？？？")
        }
    }
}
miraiBot.join()
```

0.39.2也这样

**Comment by Chenwe-i-lin** [comment]
能附上日志信息吗

**Comment by Him188** [comment]
DSL语句不能嵌套使用。
请更新Kotlin插件（这样IDE会报错）或使用普通的`subscribeAlways`
