### ISSUE TITLE
弃用 native target

### ISSUE THREAD

**Issue by StageGuard** [mamoe/mirai#2698]
kotlin native 目前非常难用，而且性能也不尽人意。
native 的维护难度很大，kotlin native 的 cinterop 很糟糕，写单元测试更是一坨。
大部分用户都使用 mirai-console-loader 或基于 mirai-core 开发 JVM 平台软件，没人用 native。

**Comment by aiden-leong** [comment]
非常遗憾在两个月后看到这个消息。我正打算将mirai继承到一个Swift项目中，于是搜索到Kotlin/Native interop的话题。

**Comment by StageGuard** [comment]
> 非常遗憾在两个月后看到这个消息。我正打算将mirai继承到一个Swift项目中，于是搜索到Kotlin/Native interop的话题。

实际上，mirai 的 native 支持只能说是“能编译”，许多平台特性并没有写 native 实现。
其次，native 目标对于使用 Kotlin/Native 的开发者还算能用，但是对于其他语言来说基本是残疾的，因为编译到 native 后导出的 C 函数非常难用（尤其是协程相关）。
因此十分不建议使用 native 目标，如果执意要尝试，可以克隆后 reset 到 [这个提交](https://github.com/mamoe/mirai/tree/9a6b9cc900896d50d16508df7f9bead9f91a646f)，然后阅读 doc 中 native 的编译步骤。

**Comment by Him188** [comment]
成本太高了，native 编译太复杂，大幅提高构建难度。现阶段 Kotlin 多平台开发难度也不低，提高维护难度。感觉三年内 KN 不太会稳定。我希望降低复杂度让以后有人能接手项目，所以不得不做这个取舍。
