### ISSUE TITLE
对部分群内群员的消息解析错误

### ISSUE THREAD

**Issue by ryoii** [mamoe/mirai#27]
版本： 0.8.2

对于QQ号码位10位数的消息无法获取。或出现
`java.util.NoSuchElementException: No such member whose id is xxxx in group xxxx`异常，
或出现`未知的messageType=0xC  后文=xxxxxxxxx`日志，且没有后续操作

对于QQ号码为9位数的消息解析正常，怀疑部分地方没有做无符号数兼容

**Comment by Him188** [comment]
`No such member whose id is xxxx ` 的 xxxx 是正确的id吗

**Comment by goldimax** [comment]
QQ号都快分满32位整数了 为啥不用long呢 @Him188

**Comment by Him188** [comment]
> QQ号都快分满32位整数了 为啥不用long呢 @Him188

因为协议里面仍然是 4 bytes 固定

**Comment by ryoii** [comment]
menber id 和 group id 都是正确的
