### ISSUE TITLE
instanceof判断不了Image类型了吗

### ISSUE THREAD

**Issue by pilgrim773** [mamoe/mirai#2705]
### 问题描述

就想对纯图片消息做一些处理，结果怎么都进不去判断
```
ctx.getLogger().info("**************** 消息：" + event.getMessage().serializeToMiraiCode() + "****************");
        for (SingleMessage s : event.getMessage()) {
            ctx.getLogger().info("**************** SingleMessage消息：" + s.toString() + "****************");
            if (s instanceof Image) {
                ctx.getLogger().info("**************** 图片消息：" + s.toString() + "****************");
                continue;
            } else {
                ctx.getLogger().info("**************** 非纯图片消息：" + s.toString() + "****************");
                return false;
            }
        }
```
我还在别的地方用来判断`PlainText`似乎都没问题的
日志输入：
![image](https://github.com/mamoe/mirai/assets/13644483/29670d59-8a89-4e05-aa61-9b3f6ebefd84)

### 复现

发送单张图片即可复现

### mirai-core 版本

2.14.0

### bot-protocol

ANDROID_PHONE

**Comment by 4o4E** [comment]
event中接收的消息链中会包含message source, 一般会在第一个

https://github.com/mamoe/mirai/blob/dev/mirai-core-api/src/commonMain/kotlin/message/data/MessageSource.kt

**Comment by Him188** [comment]
删掉 `return false`

**Comment by pilgrim773** [comment]
> event中接收的消息链中会包含message source, 一般会在第一个
> 
> https://github.com/mamoe/mirai/blob/dev/mirai-core-api/src/commonMain/kotlin/message/data/MessageSource.kt

[https://github.com/mamoe/mirai/blob/dev/docs/Messages.md#d-%E9%81%8D%E5%8E%86-list](url)
我看这里的D方法可以直接遍历消息链，因为实现了List接口，意思是这个只能针对不经过event接收的event才有效？
其实我也没明白为什么包含了一个MessageSource就会影响里面的List遍历，那里面应该都是SingleMessage，而SingleMessage应该不是MessageSource吧

**Comment by 4o4E** [comment]
> > event中接收的消息链中会包含message source, 一般会在第一个
> > https://github.com/mamoe/mirai/blob/dev/mirai-core-api/src/commonMain/kotlin/message/data/MessageSource.kt
> 
> [https://github.com/mamoe/mirai/blob/dev/docs/Messages.md#d-%E9%81%8D%E5%8E%86-list](url) 我看这里的D方法可以直接遍历消息链，因为实现了List接口，意思是这个只能针对不经过event接收的event才有效？ 其实我也没明白为什么包含了一个MessageSource就会影响里面的List遍历，那里面应该都是SingleMessage，而SingleMessage应该不是MessageSource吧

你遍历到非image元素直接return了，怎么会去遍历下一个

**Comment by cssxsh** [comment]
@hisou 首先
SingleMessage 是接口 
其次 SingleMessage -> MessageMetadata -> MessageSource

你所理解的 SingleMessage 可能是 指 MessageContent
SingleMessage -> MessageContent -> Image

**Comment by cssxsh** [comment]
你可以这样改
```
        for (SingleMessage s : event.getMessage()) {
             if (!(s instanceof MessageContent)) continue;
            ctx.getLogger().info("**************** MessageContent 消息：" + s.toString() + "****************");
            if (s instanceof Image) {
                ctx.getLogger().info("**************** 图片消息：" + s.toString() + "****************");
                continue;
            } else {
                ctx.getLogger().info("**************** 非纯图片消息：" + s.toString() + "****************");
                return false;
            }
        }
```

**Comment by pilgrim773** [comment]
多谢各位 已解决
