### ISSUE TITLE
2.15.0-RC和ANDROID_PAD 8.8.88协议下监听不到个别群的GroupMessageEvent但能主动发消息

### ISSUE THREAD

**Issue by MrY-Cat** [mamoe/mirai#2707]
### 问题描述

使用2.15.0-RC+c佬的fix-protocol-versionv1.8.0插件，ANDROID_PAD 8.8.88协议登录，无风控，能正常发消息，但个别群(mirai交流群)收不到消息，但能发消息（主动通知/定时结算消息）

### 复现

未知

### mirai-core 版本

2.15.0-RC

### bot-protocol

ANDROID_PAD

**Comment by StageGuard** [comment]
2.15.0-RC 相比于之前版本并没有更新 ANDROID_PAD 协议，请等 2.15.0 发布

**Comment by MrY-Cat** [comment]
> 2.15.0-RC 相比于之前版本并没有更新 ANDROID_PAD 协议，请等 2.15.0 发布

对，那问题的原因应该不在于是否是2.15.0-RC

**Comment by Matt-wzy** [comment]
(竟然还没寄（指被风控）？
