### ISSUE TITLE
登录超时

### ISSUE THREAD

**Issue by KKW557** [mamoe/mirai#2713]
昨天半夜到现在登录超时 其他人有这个问题吗
![IMG_20230627_064303.jpg](https://github.com/mamoe/mirai/assets/106515310/4b2708af-c252-469a-9943-d17c20b79dfa)

**Comment by KKW557** [comment]
经测试`ANDROID_PHONE`和`ANDROID_PAD`密码登录会超时
`ANDROID_WATCH`密码扫码都正常
其他没没试

**Comment by cssxsh** [comment]
把 t544-enc-windows-x64.dll/t544-enc-windows-x86.dll 删了重新生成试试看
