### ISSUE TITLE
mirai-console如何热更新插件？

### ISSUE THREAD

**Issue by 954L** [mamoe/mirai#2714]
比方说作者发布了新的插件版本，直接替换插件好像不会生效，要stop，然后重新打开才可以

**Comment by cssxsh** [comment]
不支持

**Comment by Karlatemp** [comment]
https://github.com/mamoe/mirai/blob/3ec8e552cda81f1e7f28a4c033c32557ab40e73d/mirai-console/docs/plugin/JVMPlugin.md?plain=1#L364-L370
