### ISSUE TITLE
device.json里生成的设备全是mirai是不是会导致全灭呀？

### ISSUE THREAD

**Issue by landall** [mamoe/mirai#2728]
### 问题描述

像这些部分都是一眼mirai，是不是会导致mirai机器人整体全灭啊？
是不是提供一个工具收集一下真实设备的这部分信息比较好？ 
cat device.json
{
    "deviceInfoVersion": 2,
    "data": {
        "display": "MIRAI.405963.001",
        "product": "mirai",
        "device": "mirai",
        "board": "mirai",
        "brand": "mamoe",
        "model": "mirai",
        "bootloader": "unknown",
        "fingerprint": "mamoe/mirai/mirai:10/MIRAI.200122.001/8469429:user/release-keys",
        "bootId": "1AD5D2C3-0856-68D1-8747-6D04694E0384",
        "procVersion": "Linux version 3.0.31-I440B8ET (android-build@xxx.xxx.xxx.xxx.com)",

### 复现

。

### mirai-core 版本

2.14.0

### bot-protocol

ANDROID_PAD

**Comment by cssxsh** [comment]
https://github.com/cssxsh/mirai-device-generator

**Comment by landall** [comment]
> https://github.com/cssxsh/mirai-device-generator

这个没有进入标准安装方案里，是因为法律风险原因么？

**Comment by StageGuard** [comment]
默认生成的设备信息是这样的，请自行使用其他工具生成真实的设备信息
