### ISSUE TITLE
二维码登录生成图片

### ISSUE THREAD

**Issue by Moyulingjiu** [mamoe/mirai#2729]
在一些低分辨率Linux机上，二维码登陆经常会无法显示完全。希望可以设置一个参数输出本地图片文件，或者通过某个方法能够传递出来，实现扫码。

**Comment by StageGuard** [comment]
本来就会输出到文件，在temp里，注意看log

**Comment by Moyulingjiu** [comment]
> 本来就会输出到文件，在temp里，注意看log

直接使用core并没有该东西

**Comment by StageGuard** [comment]
> 

core 请查看：
https://github.com/mamoe/mirai/blob/dev/mirai-core-api/src/commonMain/kotlin/utils/LoginSolver.kt#L65
https://github.com/mamoe/mirai/blob/dev/mirai-core-api/src/commonMain/kotlin/auth/QRCodeLoginListener.kt
