### ISSUE TITLE
ConsoleBuiltInPluginDataHolder篡改AutoLogin.yml

### ISSUE THREAD

**Issue by Lawaxi** [mamoe/mirai#2734]
### 问题描述

手动配置AutoLogin.yml后重新启动mirai会被ConsoleBuiltInPluginDataHolder所篡改回一个很久以前的配置版本

### 复现

手动配置AutoLogin.yml后重新启动mirai会被ConsoleBuiltInPluginDataHolder所篡改回一个很久以前的配置版本

### mirai-core 版本

2.8.2

### bot-protocol

ANDROID_PHONE

**Comment by StageGuard** [comment]
需要关闭 console 后才能修改 PluginData 和 PluginConfig

**Comment by Lawaxi** [comment]
> 需要关闭 console 后才能修改 PluginData 和 PluginConfig

确实是关闭后修改的，但在console启动和结束的时候都会篡改，主要是启动的时候，这样关闭时修改的就没用了

**Comment by cssxsh** [comment]
> > 需要关闭 console 后才能修改 PluginData 和 PluginConfig
> 
> 确实是关闭后修改的，但在console启动和结束的时候都会篡改，主要是启动的时候，这样关闭时修改的就没用了

检查同目录下是否有 `.bak` 结尾的备份文件，如果有，那就是你修改的格式有问题，导致触发了重新生成的机制

**Comment by Karlatemp** [comment]
Long time no reply

**Comment by Lawaxi** [comment]
1

**Comment by Lawaxi** [comment]
> > > 需要关闭 console 后才能修改 PluginData 和 PluginConfig
> > 
> > 
> > 确实是关闭后修改的，但在console启动和结束的时候都会篡改，主要是启动的时候，这样关闭时修改的就没用了
> 
> 检查同目录下是否有 `.bak` 结尾的备份文件，如果有，那就是你修改的格式有问题，导致触发了重新生成的机制

没有bak文件。配置全都是通过autologin指令自动生成的，格式有问题吗

重新生成的全都是我最先开始使用的qq号和密码，改过密码也改过账号，但动不动就会被强制篡改为最开始的qq号和密码。我在整个console的目录下搜索过包含此qq号和密码的文件，没有任何

**Comment by Lawaxi** [comment]
?
