### ISSUE TITLE
在一个 MessageChain 中取 PlainText 始终只会取到 At

### ISSUE THREAD

**Issue by Moyuyanli** [mamoe/mirai#2736]
### 问题描述

带引用消息 包含at消息  通过PlainText.key 取的时候，始终取到的都是At
![Snipaste_2023-07-15_22-46-52](https://github.com/mamoe/mirai/assets/79217875/a4b09007-8377-4e3c-9885-cb1a6d10ffa1)

### 复现

文本消息+图片消息
引用回复  at  文本消息

再取 回复的那个文本消息的时候，取不到

### mirai-core 版本

2.15.0

### bot-protocol

ANDROID_PAD

**Comment by StageGuard** [comment]
请提供最小复现代码

**Comment by Karlatemp** [comment]
#1363
