### ISSUE TITLE
添加强制性的最终用户须知

### ISSUE THREAD

**Issue by Karlatemp** [mamoe/mirai#2737]
总有用户下载整合包后不看 readme.txt

**Comment by cssxsh** [comment]
然后整合包制作者就吧已读 flag 也一起打包了

**Comment by Karlatemp** [comment]
自然是会有机器环境变化检查的

**Comment by YUCLing** [comment]
然后整合包带了个启动脚本用了 `mirai.console.skip-end-user-readme` 🤔

**Comment by Karlatemp** [comment]
这种只能看作者良心了
