### ISSUE TITLE
mirai-core申请增加Bot状态变动、心跳的Solver

### ISSUE THREAD

**Issue by wdvaini** [mamoe/mirai#2741]
在应用中，需要第一时间感知到Bot的状态变动（比如被挤下线了）、心跳是否成功。
当前，只能自己通过轮询的方式去获取相关信息。

**Comment by Him188** [comment]
被挤下线有事件，BotOfflineEvent
重连也有事件，忘了叫什么了可以在事件列表看一下

为什么需要知道心跳是否成功？目前没有接口可以知道这个
