### ISSUE TITLE
在MiraiConsoleTerminalLoader.startAsDaemon()前使用MiraiProtocol.isQRLoginSupported会导致StackOverflowError

### ISSUE THREAD

**Issue by MrY-Cat** [mamoe/mirai#2744]
### 问题描述

bot准备测试新版本时出现java.lang.StackOverflowError

经过排查提交记录，回退并逐个运行，发现：
![image](https://github.com/mamoe/mirai/assets/76583155/5b835d16-3ffe-4112-a0eb-a7fa11779e9b)

在该提交开始出现java.lang.StackOverflowError，而前一个提交并不会发生，表明是该提交的问题，而该提交仅做了使用2.15.0新增的MiraiProtocol.isQRLoginSupported进行判断是否扫码的一个改动：

![image](https://github.com/mamoe/mirai/assets/76583155/b1ac95b1-0eaa-4038-8727-494233c097c1)
![image](https://github.com/mamoe/mirai/assets/76583155/2cbd86d4-d3b5-4b26-af17-793fbec031d5)

且将改变量的引入撤销后可以正常测试bot新版本，表明该变量会引发java.lang.StackOverflowError

### 复现

在一个本来可以运行的插件中使用该变量判断协议是否支持扫码登录可复现

### mirai-core 版本

2.15.0

### bot-protocol

ANDROID_WATCH

### 系统日志

```text
已连接到目标 VM, 地址: ''127.0.0.1:58697'，传输: '套接字''

Exception: java.lang.StackOverflowError thrown from the UncaughtExceptionHandler in thread "main"
```

**Comment by MrY-Cat** [comment]
#2726  #2742

**Comment by MrY-Cat** [comment]
@Karlatemp 是不是哪里出死循环了☹☹

**Comment by Karlatemp** [comment]
![image](https://github.com/mamoe/mirai/assets/30070303/e4d7d68f-4ecf-45fb-8744-f231b0d4a0d7)

无法复现

**Comment by MrY-Cat** [comment]
> ![image](https://user-images.githubusercontent.com/30070303/255374515-e4d7d68f-4ecf-45fb-8744-f231b0d4a0d7.png)
> 
> 无法复现

ANDROID_WATCH能么

**Comment by Karlatemp** [comment]
判断哪个都是一样的

**Comment by MrY-Cat** [comment]
> 判断哪个都是一样的


莫非是因为我电脑只有8G内存，这个变量需要一定的空间导致溢出了（？），也没道理呀这一个量能要多少

**Comment by MrY-Cat** [comment]
![image](https://github.com/mamoe/mirai/assets/76583155/1b987859-b759-4883-b90b-8a411b6f3d17)

![image](https://github.com/mamoe/mirai/assets/76583155/e91c6c22-3340-484d-84cb-b19e2590c767)
可是确实是一用就溢出qaq

**Comment by Karlatemp** [comment]
提供debug步进堆栈

**Comment by MrY-Cat** [comment]
![image](https://github.com/mamoe/mirai/assets/76583155/3928d8f7-f38f-4764-b316-c866fe9cdfd5)
也不是protocolLocal的问题，换成ANDROID_WATCH也溢出

**Comment by MrY-Cat** [comment]
> 提供debug步进堆栈

我试试

**Comment by MrY-Cat** [comment]
试了一下那个值是能正常获取的
![image](https://github.com/mamoe/mirai/assets/76583155/135b6735-c047-4868-8017-6f1da53e184f)

但是如果换成用isQRLoginSupported，下一行的MiraiConsoleTerminalLoader.startAsDaemon()就会溢出
![image](https://github.com/mamoe/mirai/assets/76583155/82a4f742-ea3b-41e0-9ab8-9f7e3f98c3b4)

并且有了进一步的报错:
*** java.lang.instrument ASSERTION FAILED ***: "!errorOutstanding" with message transform method call failed at s\src\java.instrument\share\native\libinstrument\JPLISAgent.c line: 876
*** java.lang.instrument ASSERTION FAILED ***: "!errorOutstanding" with message transform method call failed at s\src\java.instrument\share\native\libinstrument\JPLISAgent.c line: 876

**Comment by MrY-Cat** [comment]
![image](https://github.com/mamoe/mirai/assets/76583155/2d578b73-361c-4c9a-8671-aa26a543b348)
更进一步是在MiraiConsoleImplementation.start()中溢出

**Comment by MrY-Cat** [comment]
![image](https://github.com/mamoe/mirai/assets/76583155/1c7e008d-6c06-4fe8-84bd-4255b3ee443a)

更进一步是在newBridge.doStart()中出现溢出

**Comment by MrY-Cat** [comment]
不然试试在使用.isQRLoginSupported后MiraiConsoleTerminalLoader.startAsDaemon()能不能复现

**Comment by Karlatemp** [comment]
你破坏了 mirai-console 的初始化, 日志输出死循环

**Comment by MrY-Cat** [comment]
> 你破坏了 mirai-console 的初始化, 日志输出死循环

我明白了，得把start放后面。但是MiraiProtocol.valueOf()就可以放在start前面，也就是说有的能有的不能，最好在start之后再用mirai相关东西对吧。
不过没有start不应该报错没启动嘛，这直接栈溢出有点突兀（×）

**Comment by Karlatemp** [comment]
修改mirai-console初始化顺序造成的错误不在支持范围内，而且直接idea启动mirai-console已经不受支持
