### ISSUE TITLE
mirai-core-android missing?

### ISSUE THREAD

**Issue by zhaodice** [mamoe/mirai#2746]
### 问题描述

请问`mirai-core-android` 已经deprecated了吗？无法从maven找到包，搜索相关issue和pr没有看见线索

### 复现

访问 https://repo1.maven.org/maven2/net/mamoe/mirai-core-android/ 找不到 `2.15.0-RC`
但是 https://repo1.maven.org/maven2/net/mamoe/mirai-core/ 有

### mirai-core 版本

2.15.0-RC

### bot-protocol

ANDROID_PHONE

**Comment by zhaodice** [comment]
好像`mirai-core-api-android`也没有最新的2.15.0-RC了

**Comment by StageGuard** [comment]
android 项目请直接导入 `net.mamoe:mirai-core-api` 和 `net.mamoe:mirai-core` 依赖

**Comment by Him188** [comment]
现在使用 Android SDK 构建了，有debug和release两个variant，所以它现在可能叫 mirai-core-androiddebug？
