### ISSUE TITLE
Java调用EncryptServiceContext ExtraArgs时提示无法访问TypeSafeMap

### ISSUE THREAD

**Issue by lngex** [mamoe/mirai#2747]
### 问题描述

在调用时提示：Cannot access net.mamoe.mirai.utils.TypeSafeMa；
无视错误编译提示：
java: 找不到符号
  符号:   类 TypeSafeMap
  位置: 程序包 net.mamoe.mirai.utils

### 复现

实现EncryptService ，重写initialize方法，方法中调用encryptServiceContext getExtraArgs方法
```

public class MyEncryptServiceImpl implements EncryptService {

    @Override
    public void initialize(@NotNull EncryptServiceContext encryptServiceContext) {
        net.mamoe.mirai.utils.TypeSafeMap extraArgs = encryptServiceContext.getExtraArgs();
    }
}
```

### mirai-core 版本

2.15.0

### bot-protocol

ANDROID_PHONE

### 其他组件版本

        <dependency>
            <groupId>net.mamoe</groupId>
            <artifactId>mirai-core-jvm</artifactId>
            <version>2.15.0</version>
         </dependency>

**Comment by StageGuard** [comment]
没导入 mirai-core-utils 依赖

**Comment by lngex** [comment]
> 没导入 mirai-core-utils 依赖

感谢，已成功解决

**Comment by zhaodice** [comment]
哈哈哈跟我犯的错误一样，我是在项目全局搜索“TypeSafeMap”，发现util 就自己导入了
