### ISSUE TITLE
当前Device设备版本信息建议做成常量

### ISSUE THREAD

**Issue by zhaodice** [mamoe/mirai#2757]
注意到 `DeviceInfoManager` 中这里硬编码了最新版设备信息为3，如果说这样搞的话，程序就很难判断当前的设备json文件是否为最新版了（因为插件也得硬编码为3），会增加维护负担，比如哪天这里变成4了，插件如果没更新还是以为3。

判断是否为最新版设备信息文件有一个好处，就是程序可以选择是否覆盖升级该json。
```
    fun serialize(info: DeviceInfo, format: Json = this.format): String {
        return format.encodeToString(
            Wrapper.serializer(V3.serializer()),
            Wrapper(3, info.toCurrentInfo())
        )
    }

    fun toJsonElement(info: DeviceInfo, format: Json = this.format): JsonElement {
        return format.encodeToJsonElement(
            Wrapper.serializer(V3.serializer()),
            Wrapper(3, info.toCurrentInfo())
        )
    }
```

**Comment by zhaodice** [comment]
比如这样，我想判断设备版本号，只能硬编码为3
```
val deviceStr = file.readText()
DeviceInfo.deserializeFromString (deviceStr).apply { 
    val version = JSONObject(deviceStr).optInt("deviceInfoVersion",1)
    if(version < 3){
        file.writeText(serializeToString())
    }
}
```
以后mirai更新了这就不一定是3了

**Comment by StageGuard** [comment]
判断版本号有什么意义吗？对于用户来说只需要修改设备信息内容即可。
另外 mirai 会在加载旧版设备信息后自动升级为最新版。

**Comment by zhaodice** [comment]
> 判断版本号有什么意义吗？对于用户来说只需要修改设备信息内容即可。 另外 mirai 会在加载旧版设备信息后自动升级为最新版。

这不是面向用户的，这是面向插件开发者的，而且我没有使用到mirai的自动登陆机制，我是file.readText()再反序列化形成设备信息，再new Bot()然后login()的，我这种方式设备信息文件肯定是只读态的，只能我判断版本来决定是否写出。。。（好吧我承认可能有点原始x）
有其他的可以升级设备文件方式？可以说一下吗

**Comment by Him188** [comment]
仔细阅读源码，mirai读取时会识别版本号，保存时也会保存版本号。
这是因为mirai升级需要兼容旧版本，必须做这种处理，不能删除。
如果你需要序列化，阅读 DeviceInfo 的注释，有一个 
 `serializeToString`，不要自己做序列化。

**Comment by StageGuard** [comment]
> > 判断版本号有什么意义吗？对于用户来说只需要修改设备信息内容即可。 另外 mirai 会在加载旧版设备信息后自动升级为最新版。
> 
> 这不是面向用户的，这是面向插件开发者的，而且我没有使用到mirai的自动登陆机制，我是file.readText()再反序列化形成设备信息，再new Bot()然后login()的，我这种方式设备信息文件肯定是只读态的，只能我判断版本来决定是否写出。。。（好吧我承认可能有点原始x） 有其他的可以升级设备文件方式？可以说一下吗

使用 `BotConfiguration.fileBasedDeviceInfo(File)` 并传入一个可读写的文件，mirai 会读取并在检测到旧版设备信息时再写入新版设备信息。

**Comment by zhaodice** [comment]
> > > 判断版本号有什么意义吗？对于用户来说只需要修改设备信息内容即可。 另外 mirai 会在加载旧版设备信息后自动升级为最新版。
> > 
> > 
> > 这不是面向用户的，这是面向插件开发者的，而且我没有使用到mirai的自动登陆机制，我是file.readText()再反序列化形成设备信息，再new Bot()然后login()的，我这种方式设备信息文件肯定是只读态的，只能我判断版本来决定是否写出。。。（好吧我承认可能有点原始x） 有其他的可以升级设备文件方式？可以说一下吗
> 
> 使用 `BotConfiguration.fileBasedDeviceInfo(File)` 并传入一个可读写的文件，mirai 会读取并在检测到旧版设备信息时再写入新版设备信息。

我是这样的：
BotConfiguration.Default.deviceInfo = ..
用这个方式，接管了device文件的管理...读json返回对象，没法直接用BotConfiguration.fileBasedDeviceInfo(File) （这方法是错误的吗？）

**Comment by zhaodice** [comment]
> 仔细阅读源码，mirai读取时会识别版本号，保存时也会保存版本号。 这是因为mirai升级需要兼容旧版本，必须做这种处理，不能删除。 如果你需要序列化，阅读 DeviceInfo 的注释，有一个 `serializeToString`，不要自己做序列化。

本来是想自己读deviceInfoVersion 然后判断是否升级设备文件，发现mirai没有给。。就直接自己搞序列化了，这样确实不好

**Comment by zhaodice** [comment]
啊，如果说，
    public final override var deviceInfo: ((Bot) -> DeviceInfo)? = deviceInfoStub // allows user to set `null` manually.

得到的是File，而不是DeviceInfo，便也可以做到? 或者在DeviceInfo中索引一下原始文件

**Comment by zhaodice** [comment]
用`file.loadAsDeviceInfo()` 解决了！
