### ISSUE TITLE
解决报错code=45的一个可能的办法

### ISSUE THREAD

**Issue by ghost** [mamoe/mirai#2766]
`头像→设置→账号安全→关闭“安全登录检查”`可能会解决登录时报错`code=45`的问题，但不总会生效
使用的登录协议是`IPAD`
希望对登录问题有所帮助，我就是这样登录成功的

**如果此方法有效请关闭此issue

**Comment by StageGuard** [comment]
此类问题请前往论坛发布，issue 只接受 BUG 回报和功能请求
