### ISSUE TITLE
关于纯Java使用的问题

### ISSUE THREAD

**Issue by zbwxtex** [mamoe/mirai#278]
> 我想部署到腾讯云Serverless, 定时运行, 每天检查内容并推送,
> 但是Serverless**只支持Java, 不支持Kotlin**

是不是导入`mirai-core-timpc-jvm`和`mirai-core-jvm`的依赖即可?

> 使用Maven管理依赖和编译

**Comment by zbwxtex** [comment]
还有, 问下, `JApt`是什么东西? 有什么用?

**Comment by Him188** [comment]
导入 net.mamoe  的 mirai-core 

可能还要导入相关 Kotlin 依赖. 详见 Kotlin 官方文档.
