### ISSUE TITLE
发送LightApp 控制台显示 消息不显示 跟ark签名有关 怎么解决

### ISSUE THREAD

**Issue by Xiaolangs** [mamoe/mirai#2781]
### 问题描述

发送LightApp 控制台显示 消息不显示 跟ark签名有关 怎么解决

### 复现

发送LightApp 控制台显示 消息不显示 跟ark签名有关 怎么解决

### mirai-core 版本

2.15.0

### bot-protocol

ANDROID_PHONE

**Comment by aleck099** [comment]
https://github.com/mamoe/mirai/issues/2279

**Comment by Xiaolangs** [comment]
> #2279

怎么用啊。要自己拉代码修改吗

**Comment by aleck099** [comment]
> > #2279
> 
> 怎么用啊。要自己拉代码修改吗

无公用接口
想用自己研究
这种属于没吊用但是很招人烦的技术
