### ISSUE TITLE
自定义替换MiraiLogger.Factory

### ISSUE THREAD

**Issue by Alceatraz** [mamoe/mirai#2782]
```kotlin
private class DefaultFactory : MiraiLogger.Factory {
    @OptIn(MiraiInternalApi::class)
    override fun create(requester: Class<*>, identity: String?): MiraiLogger {
        return PlatformLogger(identity ?: requester.kotlin.simpleName ?: requester.simpleName)
    }
}
```
默认情况下，MiraiLogger.Factory创建的都是PlatformLogger，虽然Bot配置中可以替换为自己的实现，但是其他组件如果使用`MiraiLogger.Factory.create(XXX::class)`则会导致日志仍然通过PlatformLogger输出。

比如，提供一种API，可以将默认日志提供者设置为自定义的类:
```
MiraiLogger.Factory.setDefaultprovider(T.class) // T extends MiraiLogger
```

**Comment by cssxsh** [comment]
https://github.com/mamoe/mirai/tree/dev/logging#%E8%87%AA%E8%A1%8C%E5%AE%9E%E7%8E%B0%E6%97%A5%E5%BF%97%E8%BD%AC%E6%8E%A5
