### ISSUE TITLE
2.14升级到2.15找不到mirai各种依赖

### ISSUE THREAD

**Issue by pilgrim773** [mamoe/mirai#2792]
### 问题描述

升级了一个2.14的项目到2.15，kotlin从1.7.10改到1.8.10
发现依赖报错了以后想着新建一个全新的2.15.0的JAVA项目测试对比一下，但是同样找不到依赖，`build.gradle.kts`如下：
```
plugins {
    val kotlinVersion = "1.8.10"
    kotlin("jvm") version kotlinVersion
    kotlin("plugin.serialization") version kotlinVersion

    id("net.mamoe.mirai-console") version "2.15.0"
}

group = "com.example"
version = "0.1.0"

repositories {
    maven("https://maven.aliyun.com/repository/public")
    mavenCentral()
}
```

情况如下，依赖库里找不到对应的类，不过点idea的构建却能success我也不知道为什么……
![image](https://github.com/mamoe/mirai/assets/13644483/d04c1c91-b0a2-459f-a346-a8b0fbacc67d)

### 复现

同上

### mirai-core 版本

2.15.0

### bot-protocol

ANDROID_PHONE

**Comment by cssxsh** [comment]
`IDEA 爆红` != `找不到依赖`

你这种情况是依赖无法解析
这种情况你需要尝试升级 idea 版本

**Comment by StageGuard** [comment]
升级 idea 版本
