### ISSUE TITLE
做一个图片生成的内置插件

### ISSUE THREAD

**Issue by LittleArray** [mamoe/mirai#2797]
## 为什么这么做
因为目前JVM平台没有一个特别好的原生生成图片的方式,需要自己想办法实现<br>
而现在很多机器人都需要根据需求去生成动态的图片
## 推荐方法
利用chrome-cli通过渲染html来生成图片

**Comment by NoMathExpectation** [comment]
我觉得这个不是这个项目应该考虑的范围

**Comment by StageGuard** [comment]
这是业务逻辑，而不是 mirai 框架应该有的功能

**Comment by MrXiaoM** [comment]
我的建议是，如果你需要，可以添加前置插件 [cssxsh/mirai-skia-plugin](https://github.com/cssxsh/mirai-skia-plugin)

**Comment by LittleArray** [comment]
> 我的建议是，如果你需要，可以添加前置插件 [cssxsh/mirai-skia-plugin](https://github.com/cssxsh/mirai-skia-plugin)

好的,有空去看看
