### ISSUE TITLE
请问一下IDEA maven依赖下载问题

### ISSUE THREAD

**Issue by DowneyJring** [mamoe/mirai#2818]
### 问题描述

![image](https://github.com/mamoe/mirai/assets/64281564/4eae7c52-ebe2-4272-9ae1-2b41893bc268)

![image](https://github.com/mamoe/mirai/assets/64281564/50d33151-1fbc-4ae2-85a4-760acec808ab)
图一是阿里云仓库搜到的
图二是IDEA
下载不下来怎么办啊

### 复现

![image](https://github.com/mamoe/mirai/assets/64281564/30d20551-c665-4332-9344-070e7c5c4a01)
配的这个

### mirai-core 版本

2.15.0

### bot-protocol

ANDROID_PHONE

**Comment by Him188** [comment]
读文档

group 是 net.mamoe

**Comment by DowneyJring** [comment]
最开始就是用的net.mamoe

**Comment by DowneyJring** [comment]
![image](https://github.com/mamoe/mirai/assets/64281564/f3c7ee67-f1c5-4248-b1b5-eee589921ffe)
2.9.0的也拉不下来
