### ISSUE TITLE
有的帐号即使是有sign也不能发送消息

### ISSUE THREAD

**Issue by zhaodice** [mamoe/mirai#2822]
### 问题描述

sign是8.9.88的，首先我在sendMessage之前打了个log，我又在算sign返回之前的地方打了个log，类似如下：
```
log(xxx)
sendMessage(
```
```
log(xxx)
return sign
```
log呈现了很离奇的顺序：
1.先输出sign返回之前的log
2.延迟3秒
3.输出sendMessage的log

已知sign已正确返回，且请求sign的cmd，seq，body等内容经过pb解包也验证是正确的

### 复现

难以复现，但是qq一旦发生可以`固定复现`，目前仅在少部分qq可以稳定复现
更离奇的是，`更换设备`后，本该可以稳定复现的qq也变得不能复现了。

### mirai-core 版本

1.15.0

### bot-protocol

ANDROID_PAD

### 补充信息

![QQ图片20231123232833](https://github.com/mamoe/mirai/assets/63996691/6a21d763-090b-4f7d-ac37-95da48a0527a)

可以很神奇的注意到，在`我在sendMessage之前打了个log，我又在算sign返回之前的地方打了个log`的情况下，居然神奇地，在收消息后，先输出了sign的请求，后来才输出发送请求，离奇的是
算完sign后 3秒后才输出 发送请求 
但事实上，经过验证buffer参数，**buffer就已经含有正常发送请求必要的字符串了。。。**
说明这个log的时序受到了某种bug的影响，没有按照真正的因果顺序输出，目前暂时没弄明白怎么回事
先把问题放在这里，因为实在难以确认问题，可以给点debug建议什么的。。

**Comment by dezhishen** [comment]
log的级别改成err,再观测下日志的输出情况?

**Comment by zhaodice** [comment]
> log的级别改成err,再观测下日志的输出情况?

我找到问题了
```
        //TODO NT, PROTOCOL MAY BROKEN
        bot.network.logger.info("[Type ${resp.msgRspType}] resp.syncCookie = ${resp.syncCookie?.toUHexString()},resp.pubAccountCookie = ${resp.pubAccountCookie.toUHexString()}")
        when (resp.msgRspType) {
            0 -> {
                /*
                bot.syncController.syncCookie = resp.syncCookie
                bot.syncController.pubAccountCookie = resp.pubAccountCookie
                */
            }
            1 -> {
                bot.syncController.syncCookie = resp.syncCookie
            }
            2 -> {
                //bot.syncController.pubAccountCookie = resp.pubAccountCookie
            }
        }
```
可能是因为协议变化，syncCookie被刷新成了不可描述的内容，直接导致发消息的时候使用syncCookie导致服务端听不懂mirai的鸟语

**Comment by zhaodice** [comment]
临时把sync屏蔽一下只留type 1暂时没有问题

**Comment by zhaodice** [comment]
问题已几乎完全解决
