### ISSUE TITLE
关于java的消息链判断消息类型问题

### ISSUE THREAD

**Issue by Moyuyanli** [mamoe/mirai#2847]
### 问题描述

![图片](https://github.com/mamoe/mirai/assets/79217875/ec17fd67-5b8b-4973-a76b-5e7d13c26b1d)
有一个PlainText的消息链，我通过`contains(At.Key)`,结果为true。

### 复现

在java中，通过miraicode构造一个消息链，然后判断at消息类型

### mirai-core 版本

2.16.0

### bot-protocol

ANDROID_WATCH

### 其他组件版本

Running MiraiConsole v2.16.0, built on 2023-10-20 06:28:10.
Frontend Terminal: version 2.16.0, provided by Mamoe Technologies

Permission Service: Built In Permission Service

Plugins: QRLogin v0.1.7, mirai-hibernate-plugin v2.7.1, HuYanSession3 v1.0.0

Object Pending Finalization Count: 0
                 committed |  init   |  used   |  max  
    Heap Memory:  254.0MB  | 254.0MB | 54.14MB | 3.94GB
Non-Heap Memory:  138.0MB  | 7.31MB  | 134.4MB |   -1

**Comment by Him188** [comment]
在群里解释过了，这个属于正常行为（Java问题）
At实际上没有Key，At.Key引用的是MessageContent.Key，所以会返回第一个MessageContent

或许我们应该怎么样做一些处理，让开发者使用 contains(MessageContent.Key) 的时候获得提示
