### ISSUE TITLE
kotlin疑问

### ISSUE THREAD

**Issue by tghjnjvg** [mamoe/mirai#285]
miraiBot.subscribeMessages {
        "你好" reply "你好!"
        case("at me") {
            reply(sender.at() + " 给爷爬 ")
        }

        (contains("舔") or contains("刘老板")) {
            "刘老板太强了".reply()
        }
    }
如果我在这里加个always怎么写呢，
我获取msg与kotlin的array比较如何决定是否禁言,给他禁言这样怎么写呢

这样的demo例子太少了,能不能具体一点 源码的话也没注释怎么用,太长了不好看得懂

**Comment by tghjnjvg** [comment]
mBot.subscribeGroupMessages {
                always {
                    Log.e("asdasdasd",message.contentToString())
                    val inputStream = assets.open("keyword.txt")
                    val size: Int = inputStream.available()
                    val buffer = ByteArray(size)
                    inputStream.read(buffer)
                    inputStream.read(buffer)
                    inputStream.close()
                    val text = String(buffer)
                    for( tline in text.split("\n")){
                        if(message.contentToString().contains(tline) ){
                            mCallback?.get()?.onMessage("hh禁言 +++"+tline+" +++ ")
                            mCallback?.get()?.onMessage("\n\n 禁言禁言禁言禁言禁言 ${sender.id} 的消息\n 名称 ${sender.nick} \n")
//                            if(group.botPermission == MemberPermission.OWNER){
//                                sender.mute(60)
//                                message.recall()
//                            }
                            Log.e("asdasdasd","hh禁言")
                            Log.e("asdasdasd",tline)
                            break
                        }else{
                            continue
                        }
                    }
                }

            }

**Comment by tghjnjvg** [comment]
比如我这么写 去禁言一些触发禁言关键词(关键词在assets里) 禁言语句我不会，然后这样也没反应

**Comment by Him188** [comment]
若不熟悉 Kotlin, 使用
```kotlin
bot.subscribeAlways<GroupMessage> {    }
```
而不要使用 DSL.

**Comment by tghjnjvg** [comment]
mBot.subscribeAlways<FriendMessage> {
                mCallback?.get()?.onMessage("\n\n 收到来自 ${sender.id} 的消息 \n 头像 ${sender.avatarUrl} \n 名称 ${sender.nick} \n 内容 $message. \n\n")
                if(message.equals(":help")){
                    reply("帮助手册:\n回复:help获取帮助\n回复:greet获取问候 \n")
                }else if (message.equals(":greet")){
                    reply("大佬您好,请接受我最虔诚的膜拜")
                }
            }

            mBot.subscribeAlways<GroupMessage> {
                mCallback?.get()?.onMessage("\n\n 收到来自 ${sender.id} 的消息 \n 头像 ${sender.avatarUrl} \n 名称 ${sender.nick} \n 内容 $message. \n\n")
                if(message.equals(":help")){
                    reply("帮助手册:\n回复:help获取帮助\n回复:greet获取问候 \n")
                }else if (message.equals(":greet")){
                    reply("大佬您好,请接受我最虔诚的膜拜")
                }
            }

**Comment by tghjnjvg** [comment]
这样写啥也没收到

**Comment by Him188** [comment]
这不是 mirai 问题
