### ISSUE TITLE
GroupSettings.isMuteAll 初始状态错误

### ISSUE THREAD

**Issue by y702332688** [mamoe/mirai#286]
//允许成员邀请 可关 不可开
isAllowMemberInvite
//公告 可用
entranceAnnouncement
//禁言 可关不可开
settings.isMuteAll
//坦白说 可开不可关
isConfessTalkEnabled

工具Android Studio 3.6.3
mirai版本0.39.5

不知道是不是我使用问题

**Comment by ryoii** [comment]
测试结果为可正常使用。
bug为 `group.settings` 初始值出现问题

**Comment by y702332688** [comment]
> 测试结果为可正常使用。
> bug为 `group.settings` 初始值出现问题

怎么写才能设置？mBot.getGroup(78472999).settings.isMuteAll  不是这样吗？

**Comment by ryoii** [comment]
> > 测试结果为可正常使用。
> > bug为 `group.settings` 初始值出现问题
> 
> 怎么写才能设置？mBot.getGroup(78472999).settings.isMuteAll 不是这样吗？

`bot.getGroup(xxx).settings.isMuteAll = true/false`

**Comment by y702332688** [comment]
> > > 测试结果为可正常使用。
> > > bug为 `group.settings` 初始值出现问题
> > 
> > 
> > 怎么写才能设置？mBot.getGroup(78472999).settings.isMuteAll 不是这样吗？
> 
> `bot.getGroup(xxx).settings.isMuteAll = true/false`

我后面写有 mBot.getGroup(78472999).settings.isMuteAll = true  但是无效

**Comment by ryoii** [comment]
初始值有问题，先设置`false`再设置`true`

**Comment by y702332688** [comment]
> 初始值有问题，先设置`false`再设置`true`

开启都得写两条？其他类似的也得这么写是吗？
mBot.getGroup(78472999).settings.isMuteAll = false
mBot.getGroup(78472999).settings.isMuteAll = true

**Comment by sandtechnology** [comment]
> 
> 
> 初始值有问题，先设置`false`再设置`true`

进行设置之后，显示为开启后关闭全员禁言 无法生效

**Comment by Him188** [comment]
正考虑删除坦白说和允许群员邀请的支持，保留全体禁言支持。

**Comment by Him188** [comment]
```kotlin
    override val muteAll: Boolean get() = delegate.shutupTimestamp != 0
```
