### ISSUE TITLE
字符串匹配contains匹配不到.

### ISSUE THREAD

**Issue by tghjnjvg** [mamoe/mirai#287]
mBot.subscribeAlways<GroupMessage> {
                mCallback?.get()?.onMessage("\n\n 收到来自 ${sender.id} 的消息 \n 头像 ${sender.avatarUrl} \n 名称 ${sender.nick} \n 内容 ${message.contentToString()} \n\n")
                if(message.contentToString().equals(":help")){
                    reply("帮助手册:\n回复:help获取帮助\n回复:greet获取问候 \n")
                }else if (message.contentToString().equals(":greet")){
                    reply("大佬您好,请接受我最虔诚的膜拜")
                }else if (message.contentToString().equals("网址")) {
                    Log.e("asdasdasd","hh禁言")
                    sender.mute(20)
                    message.recall()
                }else{
                    //Log.e("asdasdasd怕出错弄这个",text)
                    for(tline in keyword.split("\n")){
                        var tliner = tline.replace(" ","")
                        Log.e("asdasdasd",tliner)
                        Log.e("asdasdasd",tline)
                        Log.e("asdasdasd",message.toString())
                        Log.e("asdasdasd",message.toString().contains(tliner,true).toString())
                        if(message.toString().contains(tliner,true)){
                            //mCallback?.get()?.onMessage("\n\n 禁言禁言禁言禁言禁言 ${sender.id} 的消息\n 名称 ${sender.nick} \n")
                            Log.e("asdasdasd","hh禁言")
                            Log.e("asdasdasd",tliner)
                            //sender.mute(60)
                            //message.recall()
                            break
                        }else{
                            continue
                        }
                    }

                }

**Comment by tghjnjvg** [comment]
下面这段就是读取message判断是否有tline
但是一直是失败,就算有tline也返回false不知道为什么

**Comment by tghjnjvg** [comment]
04-29 21:25:51.276 3316-3582/net.mamoe.mirai.demo E/asdasdasd: 网址
04-29 21:25:51.276 3316-3582/net.mamoe.mirai.demo E/asdasdasd: 网址
04-29 21:25:51.276 3316-3582/net.mamoe.mirai.demo E/asdasdasd: [mirai:source:1912381953]有没有人有编程网站的网址啊
04-29 21:25:51.276 3316-3582/net.mamoe.mirai.demo E/asdasdasd: false

**Comment by tghjnjvg** [comment]
上面那个是log信息 按理说这个应该返回true的却返回false 太奇怪了 这是bug吧 因为 有没有人有编程网站的网址啊 里有网址呀  第一个网址是我没有replace空格的第二个有replace空格 应该不是空格的问题

**Comment by Him188** [comment]
这不是 mirai 问题

**Comment by tghjnjvg** [comment]
kotlin语法的问题？

**Comment by tghjnjvg** [comment]
就是mirai的问题呀

**Comment by tghjnjvg** [comment]
Log.e("asdasdasd",tline)
                        Log.e("asdasdasd",message.toString())
                        Log.e("asdasdasd",message.toString().contains(tliner,true).toString())
                        Log.e("asdasdasd","[mirai:source:979419476]我要网址".contains("网址",true).toString())

**Comment by tghjnjvg** [comment]
04-29 21:37:12.545 4717-4824/net.mamoe.mirai.demo E/asdasdasd: 网址
04-29 21:37:12.546 4717-4824/net.mamoe.mirai.demo E/asdasdasd: 网址
04-29 21:37:12.546 4717-4824/net.mamoe.mirai.demo E/asdasdasd: [mirai:source:1498456614]我要网址
04-29 21:37:12.546 4717-4824/net.mamoe.mirai.demo E/asdasdasd: false
04-29 21:37:12.546 4717-4824/net.mamoe.mirai.demo E/asdasdasd: true

**Comment by Him188** [comment]
不确定, 但这并不是 mirai 问题
