### ISSUE TITLE
群消息json发不出去

### ISSUE THREAD

**Issue by lliioollcn** [mamoe/mirai#292]
群消息json发不出去
这是我的json消息
{"app":"com.tencent.qqpay.qqmp.groupmsg","desc":"","view":"groupPushView","ver":"1.0.0.7","prompt":"菜单","appID":"","sourceName":"","actionData":"","actionData_A":"","sourceUrl":"","meta":{"groupPushData":{"bannerImg":"https://img.l.ctliccl.top/viewpicture.php?id=48b503","bannerLink":"http://qm.qq.com/cgi-bin/qm/qr?from=app&p=android&k=YCdcbs3lgpOOAkhdHIycNyM6u281Nx3s","bannerTxt":"菜单","cancel_url":"http://www.baidu.com","fromIcon":"","fromName":"name","item1Img":"","report_url":"","summaryTxt":"娱乐系统（待开发）\n\n群管系统（待开发）\n\n银行系统（待开发）\n\n玩家系统（待开发）\n\n便民系统（待开发）","time":""}},"config":{"forward":0,"showSender":1}}
这是我的代码
![图片](https://user-images.githubusercontent.com/44719954/80788518-ee37c900-8bbb-11ea-95de-c7753286f715.png)
发送显示
![图片](https://user-images.githubusercontent.com/44719954/80788655-54bce700-8bbc-11ea-9240-4a6c21b875f3.png)

**Comment by lliioollcn** [comment]
私聊正常，但是群会这样。

**Comment by Him188** [comment]
经测试可以发送
![Y@DZLQ Y3RA6EPPZ9%G_LEY](https://user-images.githubusercontent.com/12100985/80788947-2b508b00-8bbd-11ea-9bac-1bfb48cac8a8.jpg)

此消息类型应为 LightApp

**Comment by Him188** [comment]
![image](https://user-images.githubusercontent.com/12100985/80788987-4c18e080-8bbd-11ea-91fa-eabb6474c620.png)
