### ISSUE TITLE
[0.40]一段消息开头的at会出现两次

### ISSUE THREAD

**Issue by khjxiaogu** [mamoe/mirai#293]
## 问题
如果@出现在一段消息的开头，那么它会在messageChain中重复一遍，序列化的消息如下：
```
[mirai:source:2****5,4****3][mirai:at:1****2] [mirai:at:1****2] 在吗
```
并且，如果是回复他人消息的时候，会出现 at quote at的现象，序列化的消息如下：
```
[mirai:source:2****8,-2****8][mirai:at:3****8] [mirai:quote:2****3,1****2][mirai:at:3****8] 回复
```
实际消息是
@xxxxx 在吗
或者
[回复]
@xxxx 回复
## 如何复现
- 1. 在群内@一个成员然后输入一些文字   
   2. 后台就会表现为两个at   
- 1. 在电脑端回复一个成员然后输入一些文字
   2. 后台就会出现 at quote at的现象

**Comment by Him188** [comment]
![HNJM(`}`82O32)3P06O84{6](https://user-images.githubusercontent.com/12100985/80797052-5e057e00-8bd3-11ea-9a9e-a05633391267.png)
![CWX@SK SC605Z1%KAJU@}GS](https://user-images.githubusercontent.com/12100985/80797077-6eb5f400-8bd3-11ea-9149-0798d20cb0a0.png)

经测试正常

**Comment by Him188** [comment]
所有的quote都默认带一个 at, 这是官方客户端的行为.

在手机发送消息会默认再多一个at, 可以手动删除. 而在 PC 端不会自动添加第二个 at

**Comment by khjxiaogu** [comment]
手机的回复是quote at at 电脑的回复则是at quote at，比较神奇。
添加一些判断代码之后解决了。
