### ISSUE TITLE
不知道 为什么 kotlin 和jdk11 都没有运行起来...

### ISSUE THREAD

**Issue by myucxy** [mamoe/mirai#3]

**Comment by Him188** [comment]
有没有报错

**Comment by Him188** [comment]
还没有写构建的, 得依靠IDE来运行指定的 demo main 函数

**Comment by Him188** [comment]
可能是build没写好, 试试pull一下再运行mirai-demo-1里面的Main.kt

**Comment by lwh31415** [comment]
可以把部署步骤写详细一点吗，我本地也运行不起来，已经pull了

**Comment by Him188** [comment]
@lwh31415 
感谢你的支持，目前 console 还没做完，只能先依靠代码（提供账号参数）启动。
当然开发阶段也还不考虑构建jar或可执行

clone之后可在 mirai-demo/mirai-demo-1 中通过 IDE 运行 Main.kt 中的 main 函数。

**Comment by lwh31415** [comment]
代码启动发现构建失败，信息如下：
Gradle Daemon started in 2 s 140 ms

> Configure project :mirai-core
Kotlin Multiplatform Projects are an experimental feature.

FAILURE: Build failed with an exception.

* Where:
Build file 'D:\GIT\qq\mirai\mirai-core\build.gradle' line: 33

* What went wrong:
A problem occurred evaluating project ':mirai-core'.
> Project with path ':mirai-protocol-timpc' could not be found in project ':mirai-core'.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

CONFIGURE FAILED in 7s

另外，可否即使联系方式，比如QQ或者手机号码；QQ群也许是一个讨论问题的好方法。

**Comment by Him188** [comment]
@lwh31415 
感谢，刚刚修复了这个问题

**Comment by lwh31415** [comment]
谢谢，我更新后重新build，发现新的问题，我解决了这个问题，问题如下：
16:03:32: Executing tasks ':mirai-console:classes :mirai-console:testClasses :mirai-api:classes :mirai-api:testClasses :mirai-core:classes :mirai-core:testClasses :mirai-debug:classes :mirai-debug:testClasses :mirai-demos:mirai-demo-1:classes :mirai-demos:mirai-demo-1:testClasses :mirai-core:jvmTestClasses :mirai-core:jvmMainClasses :mirai-core:metadataMainClasses'...

Gradle Daemon started in 1 s 780 ms

> Configure project :mirai-core
Kotlin Multiplatform Projects are an experimental feature.

FAILURE: Build failed with an exception.

* Where:
Build file 'D:\GIT\qq\mirai\mirai-debug\build.gradle' line: 11

* What went wrong:
A problem occurred evaluating project ':mirai-debug'.
> Cannot get property 'protobuf_version' on extra properties extension as it does not exist

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 5s
16:03:40: Tasks execution finished ':mirai-console:classes :mirai-console:testClasses :mirai-api:classes :mirai-api:testClasses :mirai-core:classes :mirai-core:testClasses :mirai-debug:classes :mirai-debug:testClasses :mirai-demos:mirai-demo-1:classes :mirai-demos:mirai-demo-1:testClasses :mirai-core:jvmTestClasses :mirai-core:jvmMainClasses :mirai-core:metadataMainClasses'.
解决方法：
在项目根目录的build.gradle文件中，allprojects节点下增加ext.protobuf_version = "2.5.0"；版本2.5.0是我测试用的。
后续问题：
执行demo，控制台最后三行打印如下：
[Mirai] 10-09 16:07:39 #R0: Packet sent:                    ClientChangeOnlineStatusPacket(00 EC __ __){qq=2818339108, sessionKey=3D 78 33 B1 95 84 24 FB AE 81 3D D9 98 DE EC 7D, loginStatus=ONLINE}
[Mirai] 10-09 16:07:39 #R0: Packet received:                      ServerLoginSuccessPacket(00 EC C0 E2){}
Process finished with exit code 0
我的疑问：现在我本地环境搭建成功了吗，demo正常运行的状态是什么？

**Comment by Him188** [comment]
@lwh31415 
已修复这个问题, 请pull.
问题是timeout没控制好, 稍等一会

**Comment by lwh31415** [comment]
@Him188 我刚pull了，还是显示登陆成功并结束程序

**Comment by Him188** [comment]
我刚刚表述有问题, 是我修复了一个问题又发现了另一个问题...然后现在都修了
刚刚测试成功
@lwh31415

**Comment by lwh31415** [comment]
@Him188 谢谢你的热心回复，我结合了目前需求，我可能会转向酷Q插件开发，这可能有些酷Q平台的限制，你的项目有二次开发自由度方面的优势，我会持续支持你的项目的。再次感谢！！

**Comment by liujiahua123123** [comment]
请问您的需求是什么呢？

**Comment by lwh31415** [comment]
@liujiahua123123 我的需求很简单，能实现一个QQBot，接收消息能经过Python处理后返回。我查了很多github项目，基于网页api的都已经不能用了，目前安卓协议的没找到开源的，你们的项目是基于TIMPC协议的，这也是我努力寻找的，非常欣赏你们能把这个项目开源。我这几天在本地搭建这个项目过程中发现一些问题，建议你们能在主版本上保持可编译，测试后再合并。另外，对Him188说我转向酷Q，无意冒犯，无意冒犯。只是目前酷Q比较稳定，望见谅。

**Comment by Him188** [comment]
因为这个项目才刚开始2个月, 以后会越来越完善吧. 欢迎你之后转过来用mirai

**Comment by ice1000** [comment]
> 另外，可否即使联系方式，比如QQ或者手机号码；QQ群也许是一个讨论问题的好方法。

推荐 gitter
