### ISSUE TITLE
Windows 下 File 在 upload 之后不会被释放

### ISSUE THREAD

**Issue by IceCream-Open** [mamoe/mirai#302]
## 问题

Windows 下，使用 File 上传图片，图片文件并不会被正常释放，后续调用 file.delete() 无法正常删除文件。

而 macOS 下可以正常释放。

测试环境：
Windows：
Windows 10 x64 1909
Oracle JDK 1.8 x64

macOS：
macOS 10.14.6
Oracle JDK 1.8 x64

**Comment by Him188** [comment]
正在开发的1.0.0已经修复了这个问题，详见 1.0.0 分支
