### ISSUE TITLE
群员被邀请入群事件取操作管理和邀请人

### ISSUE THREAD

**Issue by lliioollcn** [mamoe/mirai#314]
群员被邀请入群事件取不到操作管理和邀请人咩？？
我没找到相应的方法...

**Comment by Him188** [comment]
服务器并未提供相关信息

**Comment by ryoii** [comment]
按道理是有“xxx"被”yyy“要求入群的通知的

**Comment by Him188** [comment]
然而我刚刚把这些进群事件全重新抓了一遍, 只看到一个 key 而没有其他信息.
可能需要通过某种接口查询
