### ISSUE TITLE
能不能像酷Q一样支持获取cookies以及CSRF Token？

### ISSUE THREAD

**Issue by Donge-ying** [mamoe/mirai#316]
提供获取cookies以及CSRF Token可以完成更多地操作！

**Comment by ryoii** [comment]
可以使用CQ

**Comment by Donge-ying** [comment]
> 可以使用CQ

为什么不提供支持呢，应该很容易做到吧，应该有很多人像我一样需要这个功能

**Comment by Him188** [comment]
不提供任何协议实现相关 API

**Comment by Him188** [comment]
请描述你需要实现的功能

**Comment by Him188** [comment]
如果需要功能, 请 PR. mirai 不暴露任何协议参数, 以避免被用于不正当的行为.

**Comment by Donge-ying** [comment]
> 请描述你需要实现的功能

例如：操作QQ空间，获取说说、点赞、评论等等

**Comment by jasonczc** [comment]
一切可能导致滥用的功能都不会被支持，主动操作的行为也不会被支持。
操作QQ空间这个特性可能会导致滥用，我个人认为不应该支持。

**Comment by Donge-ying** [comment]
> 一切可能导致滥用的功能都不会被支持，主动操作的行为也不会被支持。
> 操作QQ空间这个特性可能会导致滥用，我个人认为不应该支持。

操作QQ空间跟操作QQ没有什么区别，别人的bot也支持，我觉得可以考虑一下

**Comment by Him188** [comment]
可以考虑, 但它必须存在于 core 中向所有使用者开放. 而不能暴露协议.
