### ISSUE TITLE
Login failed with reason UNKNOWN

### ISSUE THREAD

**Issue by HandsomeXi** [mamoe/mirai#32]
Mirai 07:29:51 : login response packet size = 454, data=3F 01 09 00 93 00 01 D1 3C D3 0E C4 1F 15 EA 9B 8A DA D2 81 8F 65 05 00 38 6C 06 8A 70 DF AE 42 90 7F 44 51 48 F5 34 11 CD CB 8B 58 9E 07 04 4C 21 F1 26 9C 5C D1 4B 5F 64 D9 66 FB 2B 41 50 0A C5 47 81 72 16 F9 F7 D5 3E F0 0E 10 B0 4A 59 E2 C9 00 20 BA 42 D5 47 33 5F 3D BF 40 9C 7F CB 35 E9 0B E2 C5 1E 32 28 FE E2 D0 9D 62 A5 34 C8 0A 00 4A AB 00 23 02 00 20 B9 AE CC 3E 3D AE 37 78 69 8D 5D 3E A1 01 84 F5 A0 39 04 C2 EC 53 2B CD A5 9D A0 23 67 FA CA 35 00 29 00 30 23 3F 9C 86 60 9C 16 68 E6 9F 3D C2 D4 92 4A 90 D7 7A 2F 5A 37 10 8D 2E E7 92 20 A8 9B C2 92 2C BC A6 77 C3 F1 DA 1C 48 E2 7A DA 24 84 89 19 60 05 08 00 22 01 00 00 03 E8 00 1B 02 00 00 00 01 00 00 15 85 08 36 00 00 00 3F 00 00 00 00 03 79 89 A5 00 00 02 27 04 04 00 28 D1 41 3F 2A 93 08 26 1E F7 62 FF B7 48 2D A8 CA D8 06 DC 9A 9B 0D 91 AD C1 A6 E3 E9 F9 A0 37 73 DE D5 B2 45 6E 3E 97 25 01 00 00 6F 00 01 08 36 00 00 02 27 00 65 24 55 49 4E 24 E6 9C AC E6 AC A1 E7 99 BB E5 BD 95 E9 9C 80 E8 BF 9B E8 A1 8C E8 BA AB E4 BB BD E9 AA 8C E8 AF 81 EF BC 8C E8 AF B7 E7 82 B9 E5 87 BB E7 99 BB E5 BD 95 E7 AA 97 E5 8F A3 E5 8F B3 E4 B8 8B E6 96 B9 E4 BA 8C E7 BB B4 E7 A0 81 E5 9B BE E6 A0 87 E8 BF 9B E8 A1 8C E7 99 BB E5 BD 95 E3 80 82 04 02 00 08 2B 7A 65 5D 6B 24 59 3C 04 03 00 08 27 66 67 7B 21 6B 67 2B 04 06 00 05 01 00 00 00 00 01 15 00 10 FB 87 BF 1F 96 6D 15 29 97 27 22 4D DA 43 2B C7
Bot(453723464) 07:29:51 : Packet received: Failed(result=UNKNOWN)
Exception in thread "main" net.mamoe.mirai.utils.LoginFailedException: Login failed with reason UNKNOWN
	at net.mamoe.mirai.timpc.network.TIMPCBotNetworkHandler.login(TIMPCBotNetworkHandler.kt:73)
	at net.mamoe.mirai.timpc.network.TIMPCBotNetworkHandler$login$1.invokeSuspend(TIMPCBotNetworkHandler.kt)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)

**Comment by HandsomeXi** [comment]
已解决:设备锁原因.

**Comment by Him188** [comment]
安卓协议支持了设备锁登录. 过几天会发布第一个预览版本

**Comment by HandsomeXi** [comment]
谢谢

**Comment by thirstyzebra** [comment]
安卓 qq 相关协议可以查看 https://github.com/botmm/botmm  docs 目录
