### ISSUE TITLE
GIF 在 Android 客户端无法放大查看

### ISSUE THREAD

**Issue by Genanik** [mamoe/mirai#321]
使用官方客户端发出的GIF图可以在聊天界面预览GIF动画，而mirai发出的GIF图只能点进去看原图
### 如何复现
使用mirai发送任意GIF图片

### 版本
mirai: `1.0-RC"`

**Comment by Him188** [comment]
通过什么方式发送？

**Comment by Him188** [comment]
文件还是什么

**Comment by Genanik** [comment]
使用的是contact.uploadImage( File.toExternalImage() )

**Comment by Him188** [comment]
经测试没有问题

**Comment by Him188** [comment]
图片可以正常在消息中查看, 但不能放大查看.

**Comment by Genanik** [comment]
emmm刚刚用Android客户端测试了下  可以正常预览，但是在iOS端只可以放大查看
![IMG_5006](https://user-images.githubusercontent.com/27051834/82524946-c4dadf00-9b62-11ea-976f-00a2eaae0a74.PNG)
![IMG_5005](https://user-images.githubusercontent.com/27051834/82524953-cb695680-9b62-11ea-9122-9890cf4e5ad9.PNG)

**Comment by Him188** [comment]
目前还没有确定是协议问题，还是官方客户端问题。然而我也没有 iOS 设备和模拟器测试
