### ISSUE TITLE
在 parse SystemMsgNewGroup 时遇到了意料之中的问题

### ISSUE THREAD

**Issue by Him188** [mamoe/mirai#344]
![7AEG5$(UYCB00Z`X)%8UONK](https://user-images.githubusercontent.com/12100985/82746121-cc96bf80-9dbe-11ea-86b0-fece04965daf.png)

来自群内提交

**Comment by Him188** [comment]
邀请加群, 自动同意

**Comment by ryoii** [comment]
太难了
