### ISSUE TITLE
登陆需要验证时，服务部署在云服务器上，弹窗的交互方式不太好用

### ISSUE THREAD

**Issue by wdvaini** [mamoe/mirai#347]
将mirai作为服务器部署在云服务器上，希望通过远程接口（如http协议）实现登陆操作时，如果遇到登陆需要验证码等情况时，现在这种弹窗提示，不太好跟接口调用者进行交互。 希望能调整下
比如让Bot.login() 返回特定状态码和验证码的图片地址。

**Comment by ryoii** [comment]
服务器没有图像界面的时候不会用弹窗方式输入验证码

远程接口（如http协议）不支持登录操作

#### 如果你是`core`的使用者

自行设计和实现`LoginSolver`接口

#### 如果你是`console`使用者

请确保bot通过验证码登录成功后再进行插件操作。

**Comment by Him188** [comment]
查看
`net.mamoe.mirai.utils.LoginSolver`
`net.mamoe.mirai.utils.StandardCharImageLoginSolver`
`net.mamoe.mirai.utils.BotConfiguration.loginSolver`
