### ISSUE TITLE
机器人群备注后无法正常识别自己是否被At

### ISSUE THREAD

**Issue by Ace-Monster** [mamoe/mirai#350]
被备注的机器人会出现无法识别自身是否被At的问题

```



```

### 如何复现

1、开发脚本中使用
``` java
event.getMessage().contains(new At(event.getGroup().getBotAsMember())){

}
```
来判断机器人自身是否被At
2、在任何版本的QQ中At机器人，机器人都能正常做出相应逻辑
3、在群聊中修改机器人的备注
4、在电脑端（QQ for macOS）At机器人，机器人没有反应
5、在手机端（QQ for Andorid）At机器人，机器人会做出相应逻辑
### 版本
mirai: `0.5.2`

**Comment by Karlatemp** [comment]
这都1.0.0了还在用0.5.2

**Comment by Ace-Monster** [comment]
> 这都1.0.0了还在用0.5.2

诶...

**Comment by ryoii** [comment]
你问什么要用`contain`去判断一个你自己`new`的对象，这逻辑有问题

**Comment by Karlatemp** [comment]
java用户请考虑
`event.getMessage().stream().anyMatch(it -> it instanceof At && ((At) it).getTarget() == bot.getId())` 并更新到 1.0.1

**Comment by Ace-Monster** [comment]
> 你为什么要用`contains`去判断一个你自己`new`的对象，这逻辑有问题

我的想法是判断信息中是否包含At对象，因为没有找到对应的接口，因此用是否包含这种偷懒方法来检查了。
请教一下更好的解决方法是什么？

**Comment by Ace-Monster** [comment]
> java用户请考虑
> `event.getMessage().stream().anyMatch(it -> it instanceof At && ((At) it).getTarget() == bot.getId())` 并更新到 1.0.1

好的，我尝试一下

**Comment by Ace-Monster** [comment]
> 这都1.0.1了还在用0.5.2

不好意思，是我理解错了，0.5.2是在console中输入about后显示的v0.5.2（事实上我下载的是1.2.0），而core的版本是1.0.0😢

**Comment by Him188** [comment]
At是一个data class，`equals`判断时会判断引用目标的id和昵称。由于QQ官方客户端不统一，其At的昵称不同。

应判断 `At.target`
