### ISSUE TITLE
BOT被踢出群收到的事件类型错误

### ISSUE THREAD

**Issue by MatchaC** [mamoe/mirai#358]
应该是BotLeaveEventKick，但实际收到的是BotLeaveEventActive

![图片](https://user-images.githubusercontent.com/45539918/83307162-a21d8a00-a236-11ea-8399-991d4fc0b1ef.png)

**Comment by Him188** [comment]
使用的 mirai-core 版本是多少？

**Comment by MatchaC** [comment]
> 
> 
> 使用的 mirai-core 版本是多少？
Andriod1.0.1
![图片](https://user-images.githubusercontent.com/45539918/83353255-d0f54680-a383-11ea-801f-75d23016a9a2.png)

**Comment by Him188** [comment]
难搞

**Comment by Him188** [comment]
这个包只有群号码，没有其他任何信息，然而官方客户端却可以知道是否被踢出和操作人信息。

**Comment by Him188** [comment]
正考虑将主动和被动的区分临时删除，改为 mirai 内部区分，并在将来重新分析退群和被踢后再公开支持。

**Comment by SitaNya** [comment]
请求提升优先级，与一些非常重要的业务功能有关，如果方便的话能否略微提前一些，非常感谢！

**Comment by SitaNya** [comment]
请允许我做一些补充说明

首先，机器人被封禁的很大一部分原因是被踢出、禁言等，这是腾讯对是否冻结账号的一个很重要的检测标准
有些人基于恶意（无论是何种原因，哪怕只是自己开心），会对自己不喜欢的机器人进行反复踢出、禁言操作，迫使其封停

这时避免被同一个人踢出、禁言的功能就显得尤其重要，而判断是否被人踢出过，就完全取决于#358问题

可以说这个问题的解决与否，直接关系着机器人在刨除程序因素外，能否稳定运行，是否可用。因此希望您可以考虑一下，略微调高此问题的优先级，谢谢

**Comment by Him188** [comment]
我在看到这个 issue 就去检查调试过，目前无法解决这个问题。
设置 milestone 1.4.0 是为了在这段时间内等待更多的相关 issue 以帮助找出原因

**Comment by Him188** [comment]
另外，mirai 是一个开源项目，由贡献者自愿挤时间更新，且可能在任何时间停止更新，因此不应该作为商业依赖。可以使用酷Q Pro等商业应用。

**Comment by SitaNya** [comment]
了解，这不是商业软件，我也不准备强行要求您排期，这只是一个提议。如果能完成的话自然万分感谢

**Comment by ryoii** [comment]
不好解决，SubD4不论在什么情况下都会被触发，具体是主动退群还是。我也认为是忽略了某些包了。

**Comment by Mrs4s** [comment]
T出时会触发OnlinePush.Trans  MsgType为34 SubType为0x03
可参考 [https://github.com/Mrs4s/MiraiGo/blob/c6b4c61122f97dbbd0545912e1c45959b146a0c5/client/decoders.go#L425](url)
