### ISSUE TITLE
建议添加机器人触发图片验证码及登录验证时的事件

### ISSUE THREAD

**Issue by IceCream-Open** [mamoe/mirai#359]
建议添加机器人触发图片验证码及登录验证时的事件。

鉴于目前图片验证码等较为依赖图形界面。
可能会导致 无GUI的操作系统登录困难。
所以我准备采用 Web 填写验证码的操作。

希望能支持 遇到验证码时 的事件响应和主动填写 验证码 的相关 API。

**Comment by ryoii** [comment]
https://github.com/mamoe/mirai/issues/347#issuecomment-633357882
