### ISSUE TITLE
无法接收由TIM-PC端发出的语音消息

### ISSUE THREAD

**Issue by Executor-Cheng** [mamoe/mirai#360]
```
17:45:32 [INFO] [BOT] [For test()] 西井丶() -> [mirai:source:539,1183022367]收到语音消息，你需要升级到最新版QQ才能接收，升级地址https://im.qq.com
```
### 如何复现
使用TIM-PC端发条语音即可

### 版本
mirai: `1.0.1`

**Comment by ryoii** [comment]
```
ptt=Ptt#1545021774 {
                                            boolValid=true
                                            bytesPttUrls=[]
                                            fileMd5=C3 86 D9 DE 25 D8 05 A0 87 E3 81 FD 49 31 4D B3
                                            fileName=7B 43 33 38 36 44 39 44 45 2D 32 35 44 38 2D 30 35 41 30 2D 38 37 45 33 2D 38 31 46 44 34 39 33 31 34 44 42 33 7D 2E 61 6D 72
                                            format=0x00000001(1)
                                            reserve=16 36 20 39 32 6B 41 31 00 20 20 20 20 20 20 20 30 20 20 20 20 20 20 20 30 20 20 20 20 20 20 20 30 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 7B 43 33 38 36 44 39 44 45 2D 32 35 44 38 2D 30 35 41 30 2D 38 37 45 33 2D 38 31 46 44 34 39 33 31 34 44 42 33 7D 2E 61 6D 72 41
                                            srcUin=0x0000000000000000(0)
                                            time=0x00000004(4)
                                    }
```

**Comment by ryoii** [comment]
> ```
> ptt=Ptt#1545021774 {
>     boolValid=true
>     bytesPttUrls=[]
>     fileMd5=C3 86 D9 DE 25 D8 05 A0 87 E3 81 FD 49 31 4D B3
>     fileName=7B 43 33 38 36 44 39 44 45 2D 32 35 44 38 2D 30 35 41 30 2D 38 37 45 33 2D 38 31 46 44 34 39 33 31 34 44 42 33 7D 2E 61 6D 72
>     format=0x00000001(1)
>     reserve=16 36 20 39 32 6B 41 31 00 20 20 20 20 20 20 20 30 20 20 20 20 20 20 20 30 20 20 20 20 20 20 20 30 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 7B 43 33 38 36 44 39 44 45 2D 32 35 44 38 2D 30 35 41 30 2D 38 37 45 33 2D 38 31 46 44 34 39 33 31 34 44 42 33 7D 2E 61 6D 72 41
>     srcUin=0x0000000000000000(0)
>     time=0x00000004(4)
> }
> ```
TIM毒瘤完全不按剧本出牌
