### ISSUE TITLE
私聊bot却没有反应.

### ISSUE THREAD

**Issue by Watanabe-Asa** [mamoe/mirai#364]
我在249号issue里找到了类似的问题,但那里并没有解答.
只有我的账户向bot私聊发送指令会出现以下日志和没有回应.然而其他的非搭建者的私聊却依旧正常.
Network() : Send: MessageSvc.PbGetMsg
Network() : Send: MessageSvc.PbDeleteMsg
另外,在刚刚启动Mirai时没有这个问题.一旦经过5分钟左右私聊将再也没有反应.

**Comment by Him188** [comment]
See #249

**Comment by Him188** [comment]
> 我在249号issue里找到了类似的问题,但那里并没有解答.

因为这个问题很难解决, 目前没人研究它
