### ISSUE TITLE
Bot 在某个群 T 出某个人导致 Bot 终止

### ISSUE THREAD

**Issue by IceCream-Open** [mamoe/mirai#372]
Bot 在某个群 T 出某个人导致 Bot 终止。

 bot.groups[群号][QQ号].kick("")
 控制台无任何报错。
但机器人已经无法收到任何消息或者发出任何消息。

再次发送消息时提示：
`java.lang.IllegalStateException: network is dead therefore can't send any packet`

### 如何复现

在任何一个群 踢任何人

### 版本
mirai: `1.0.2`

**Comment by xbaimiao** [comment]
我也有同样的问题
