### ISSUE TITLE
稍微提一些功能和架构上的建议

### ISSUE THREAD

**Issue by graueneko** [mamoe/mirai#377]
感谢作者花这么大时间和精力写出来的框架，从工程量上看就能感觉到已经占用了作者很多的业余时间，更不用说协议解析的难度了。

我一直在用CoolQ的cqhttp框架，不得不说，cqhttp的设计很优秀，理念很精要。遗憾的是Linux+Docker+Wine+Cqhttp+Coolq的套娃实在是太占用资源了，于是来学习了一下Mirai框架。

这是我第三次打开这个Mirai的项目，前两次都因为找不到Quick Start而放弃，这次终于仔细把每个repo都看了一遍，运行了一下MiraiOK，搞一搞http插件。搞的过程中有了一些不太成熟的想法，希望对项目有所帮助。

### 功能上的一点建议

1. MiraiOK改为自动或者可选daemon模式：
在命令行交互完成后进入daemon模式；
验证码可以使用Golang的ServeFile方式提供，这样看起来清楚一些

2. HTTP Plugin希望能整合入MiraiOK：当一个非Java程序员发现要自己build jar包的时候……

3. 最好提供一个整合HTTP Plugin的Docker，对外暴露几个端口即可。（有这个上面的可以忽略了）

### 架构上的一点建议

现在组件太多了，有点眼花缭乱，其实可以精简为后端前端两部分，不需要自己忙于全部功能：

#### 后端
核心部分，包括core和协议base；

看TIM的情况，只保留Android协议就可以了，甚至不用拆开；

后端对外只通过HTTP通信，，方便各类语言的前端开发；一般来说使用JSON即可；

前面提到，希望能将后端整合入Docker，对外暴露HTTP Restful API。

#### 前端
只要后端稳定、功能齐全，前端会有很多人来做各种各样的实现，不同语言、不同模式，都会有的。

PS：我认为部分功能不提供支持是个很正确很优秀的决定。

**Comment by ryoii** [comment]
感谢提出宝贵的建议

1. MiraiOK属于社区产物，与本项目无关
2. 同上
3. console整合http-api的docker镜像据我所知在社区上有人已经实现
4. 目前Mirai的架构确实只有core和mirai-console两大模块，http-api也只属于官方支持的外围插件。没有所谓想前端后端之分
5.  #除core和mirai-console外其他项目，包括但不限于各种插件、SDK、一键包、集成项目等，都属于社区维护(~~出于好玩，官方确实以官方名义发布了几个SDK~~)

**Comment by Him188** [comment]
@ryoii 已经解释了部分内容，我现在补充说明项目架构。

<br/>
mirai 不只是一个框架。mirai-core 提供核心功能，让 mirai 能作为*可以嵌入的库*给 JVM 语言开发者使用。mirai-core 经过 10 个月的开发和测试，在 2020 年 6 月刚刚发布正式版本。


即使 TIM 协议支持早已停止开发，mirai-core 现有的 mirai-core 配合 mirai-core-qqandroid 的架构会一直保留，不会合并为同一个模块。mirai-core 更多地作为一个相对简单的 API 模块，而不需要把协议实现暴露给开发者。这样的设计虽不影响 Http 相关，但对于 JVM 平台是恰当的。

<br/>
mirai-console 主要支持 JVM 语言插件，允许JVM插件实现新的插件加载器以加载其他语言插件；以 mirai-api-http 作为支持其他语言的桥梁之一。console 并不就是设计于支持其他语言使用 mirai，而是为了创造让用户共享机器人功能实现的平台。

mirai-console 到目前为止仍处于***早期**开发状态*，各方面支持都非常不完善。'增强易用性' 已经提上日程，但这是一项长期的工作。

<br/>
现在回到你的问题。
你提出的后端实际上就是现在的 mirai-api-http，前端就是社区支持的其他语言 SDK。
有关 MiraiOK 问题，请前往其仓库提交 issue。
有关 mirai-api-http 问题，请前往[其仓库](https://github.com/project-mirai/mirai-api-http) 提交 issue。
