### ISSUE TITLE
在没有任何异常的情况下，机器人会掉线

### ISSUE THREAD

**Issue by xbaimiao** [mamoe/mirai#378]
![Screenshot_2020-06-19-05-58-47-824_com sonelli juicessh](https://user-images.githubusercontent.com/67080574/85078676-84b95b80-b1f7-11ea-86a7-328d5d5b139f.jpg)

掉线的不明不白，经历过很多次了
特别是在消息多的时候更容易掉线

**Comment by sandtechnology** [comment]
see #200

**Comment by xbaimiao** [comment]
> 参见#200

这个问题是还没解决吗

**Comment by sandtechnology** [comment]
> 
> 
> > 参见#200
> 
> 这个问题是还没解决吗

是的 请见#328 有说明
