### ISSUE TITLE
开源协议问题

### ISSUE THREAD

**Issue by crazywhalecc** [mamoe/mirai#391]
请问通过一个中间连接层来对接mirai与现有其他商业开发和个人学习用的两个后端项目，我需要开源中间连接层还是整个项目都需要开源？AGPL-3.0 项目上许多项目的解释方式不同，请问此项目对开源的要求是什么？此项目可以被用于对接商业项目吗？

**Comment by Him188** [comment]
需要，只要修改或者使用 mirai，无论是否通过网络分发，或者提供网络服务，都需要让使用者接触软件源码。

**Comment by Him188** [comment]
mirai 将来可能会放宽协议限制（使用其他协议），但在目前，mirai 使用 AGPLv3 并有上述约束。
