### ISSUE TITLE
将 FriendImage “转换” 成 GroupImage

### ISSUE THREAD

**Issue by MrXiaoM** [mamoe/mirai#392]
想让机器人转发我发送给机器人的图片到群，但我遇到问题了，转发到群的图片不会显示(废话)  

目前的思路是下载 FriendImage，然后用 group.uploadImage(image) 上传到群后发送  
但我不知道怎么将 FriendImage 下载为 InputStream 、 BufferedImage 之类的，头疼

**Comment by Him188** [comment]
#307
