### ISSUE TITLE
请问能否主动向用户发起临时会话

### ISSUE THREAD

**Issue by HHeyJ** [mamoe/mirai#401]

**Comment by Him188** [comment]
可能可以，可能不行

**Comment by sandtechnology** [comment]
向用户主动发起临时会话是黑产推送广告的常见方式，不建议实现

**Comment by Chenwe-i-lin** [comment]
就在刚才, 我就被这种临时对话ghs骑脸了, 不建议实现+1

**Comment by Him188** [comment]
赞成以上说法。目前可以被动回复临时会话消息

**Comment by libsgh** [comment]
我有个定时任务 每天会将任务执行的结果主动推送，这种不是正常的需求吗？

**Comment by Karlatemp** [comment]
> 我有个定时任务 每天会将任务执行的结果主动推送，这种不是正常的需求吗？

那为何需要通过临时会话. 向用户主动发起临时会话是黑产推送广告的常见方式, mirai不会实现

**Comment by libsgh** [comment]
> > 我有个定时任务 每天会将任务执行的结果主动推送，这种不是正常的需求吗？
> 
> 那为何需要通过临时会话. 向用户主动发起临时会话是黑产推送广告的常见方式, mirai不会实现

主要是因为大部分都不想加机器人好友，喜欢加群
