### ISSUE TITLE
支持好友列表缓存

### ISSUE THREAD

**Issue by 1523789353** [mamoe/mirai#408]
强制不检查更新：
某些连接不上github或ping过高的情况下启动不了mirai

本地好友列表：
在网络不良的时候采用缓存的好友列表
(好友多的时候启动要等蛮久，尤其是网络不良的时候)

**Comment by Him188** [comment]
强制不检查更新是 mirai-console-wrapper 的问题. mirai-console-wrapper 已停止维护, 请使用 https://github.com/LXY1226/miraiOK.

**Comment by Him188** [comment]
支持好友列表缓存并不重要. 要支持它需要额外做查询变化的协议.

**Comment by Him188** [comment]
现在服务器会直接不回复比较频繁的好友列表查询, 需要考虑缓存了
