### ISSUE TITLE
两消息连接后出现两个空格

### ISSUE THREAD

**Issue by Genanik** [mamoe/mirai#411]
reply(At + PlainText)，使用Android、Mac、iOS客户端均出现了两个空格，但是Mirai-console上显示只有一个空格（ logger.debug(At + PlainText)也是一个空格 )

```
11:56:07 [INFO] [BOT 3025657105] Group(609632487) <- [mirai:at:2704749081] ping  
```

### 如何复现

`reply(At + PlainText)`

### 版本
mirai: `1.0.2`

**Comment by Him188** [comment]
请确认右侧 `PlainText` 开头无空格

**Comment by Genanik** [comment]
`subscribeGroupMessages {
            atBot{
                reply( sender.at() + "test" )
            }
   }`
在iOS客户端内得到两个空格
![bug](https://user-images.githubusercontent.com/27051834/86089774-77e01600-badb-11ea-9fff-64b00e279f36.png)
