### ISSUE TITLE
Events.registerEvent: java.lang.IllegalArgumentException: argument type mismatch

### ISSUE THREAD

**Issue by daofeng2015** [mamoe/mirai#412]
![84902182-09fd1d00-b0df-11ea-9651-b8a6e8e96dc4](https://user-images.githubusercontent.com/14891398/86199152-ee3c5100-bb8b-11ea-8d16-e791de5ddb77.png)

```

demon中的java示例调用失败

```

### 版本
mirai: `` <!--在``中填写你正在使用的版本号，如0.40.0-->
1.1-EA

**Comment by Him188** [comment]
已在 1.0-EA2 修复
