### ISSUE TITLE
基于官方JavaDemo暂未维护并无法启动，自己写了个Demo供大家参考

### ISSUE THREAD

**Issue by HHeyJ** [mamoe/mirai#413]
https://github.com/HHeyJ/Mirai-Robot
基本的群聊，私聊，图片接收，图片发送可满足大部分使用场景
大佬们该补补文档了QAQ

**Comment by Him188** [comment]
感谢你的帮助。mirai 目前不希望将文档托付给第三方，但由于现在功能性问题（如加群无法同步）也较多，我们认为修复这些问题更重要。文档更新正在计划中。

**Comment by Him188** [comment]
#414

**Comment by HHeyJ** [comment]
> 感谢你的帮助。mirai 目前不希望将文档托付给第三方，但由于现在功能性问题（如加群无法同步）也较多，我们认为修复这些问题更重要。文档更新正在计划中。

好嘞，刚好学习学习kotlin ：）

**Comment by MQPearth** [comment]
mirai好高冷哦

**Comment by HHeyJ** [comment]
样🍐详见demo分支，
master将用来替换[https://github.com/HHeyJ/Jx3Robot](url)
