### ISSUE TITLE
发送大量图片导致内存占用不断增加

### ISSUE THREAD

**Issue by lindongbin** [mamoe/mirai#416]
早上看  #385  修复了，就更新了1.0.4测试
改成了普通的在群里发送图片
陆陆续续发送了估计有五十张左右，没有失败，日志是正常的发送成功的信息
通过观察，连续发送的时候不一定会增加，有时候是隔了一段时间，比如半个小时，给个指令发送一下，会异常增加二十M的样子
内存从正常的300左右增加到400左右
（两个同样环境下的机器人对比，在同一个群，唯一的区别是一个有发图功能）
正常的机器人内存基本没有变化，维持在300左右

增加前的内存占用 118.928M
![2](https://user-images.githubusercontent.com/3154109/86313760-79831880-bc58-11ea-946b-7a994920615e.png)

异常增加后的内存占用 238.680M
![1](https://user-images.githubusercontent.com/3154109/86313775-86077100-bc58-11ea-9f7c-39c97f2734a5.png)

没看到有类似的反馈，不知道是不是和系统有关
运行环境是
debian 10
openjdk version "11.0.6" 2020-01-14
OpenJDK Runtime Environment (build 11.0.6+10-post-Debian-1deb10u1)
OpenJDK 64-Bit Server VM (build 11.0.6+10-post-Debian-1deb10u1, mixed mode, sharing)

**Comment by Him188** [comment]
在我本机测试，发送大量大图片失败时内存都稳定，理论上发送成功不应该有问题

**Comment by lindongbin** [comment]
> 
> 
> 在我本机测试，发送大量大图片失败时内存都稳定，理论上发送成功不应该有问题

好的，估计是其它因素造成的
