### ISSUE TITLE
问个xml问题

### ISSUE THREAD

**Issue by ls148478** [mamoe/mirai#420]
先上代码

 `subscribeAlways<GroupMessageEvent> {
            reply(
                ServiceMessage(60, """
                        <?xml version='1.0' encoding='UTF-8' standalone='yes' ?><msg serviceID="1" templateID="1" action="" brief="欢迎新人入群" sourceMsgId="0" url="" flag="0" adverSign="0" multiMsgFlag="0"><item layout="0"><picture cover="http://imgsrc.baidu.com/forum/pic/item/cfb2693e6709c93d7a99a3ff9e3df8dcd00054f7.jpg" action="web" w="0" h="0" /><title size="null" style="null"></title></item><item layout="6"><hr hidden="false" style="0" /></item><source name="" icon="" action="" appid="-1" /></msg>
                    """.trimIndent()))
        }`
![6a5a29d57028fa86](https://user-images.githubusercontent.com/38435967/86472104-349ed500-bd71-11ea-87ef-6e2012360a38.png)
这么写 在QQ收不到这条消息 有时候又能收到 大概是1%的概率 是我写的不对吗

**Comment by Him188** [comment]
XML消息不保证能接受到，取决于你的 xml content。

qq 本身就没有公开 xml 消息相关信息，使用者应自己承担一切风险

**Comment by ls148478** [comment]
xml内容倒是没有问题 使用其他xml发送工具验证过 奇葩的是 有时候恰巧可以接收到 但是概率非常低

**Comment by ls148478** [comment]
> XML消息不保证能接受到，取决于你的xml内容。
> 
> qq本身就没有公开xml消息相关信息，使用者应自己承担一切风险

ServiceMessage对于Json的消息也是经常发不出来 使用LightApp则没有此问题

**Comment by Him188** [comment]
这并不是mirai问题，这是因为这个消息不属于Json类型，而是属于LightApp

mirai 从未声明过 ServiceMessage 相关的稳定性。
