### ISSUE TITLE
请求支持接收和发送讨论组消息

### ISSUE THREAD

**Issue by duament** [mamoe/mirai#424]
当前版本在收到讨论组消息后显示：
`[INFO] [NETWORK] Received unknown commandName: OnlinePush.PbPushDisMsg`

**Comment by Him188** [comment]
讨论组正在被 QQ 弃用，现在建群已经无法创建讨论组（最新 Android QQ, Android TIM, PC TIM 客户端测试）。

相比这样的用处较小的功能，mirai 更应该较先修复群申请等主要的问题。

可将讨论组转为群后即可正常使用。

**Comment by SitaNya** [comment]
酷Q目前经过测试还是有大量的讨论组内容，也不仅仅是旧群，我自己新拉群也会被归为Discuss内容
我不能肯定是酷Q设定的问题还是QQ关于讨论组还有别的设定，辛苦您了

**Comment by ryoii** [comment]
未上传群头像的新群不会分配群号，这时可能归为讨论组情况

**Comment by mzdluo123** [comment]
但是经过我的测试，就算是没有分配群号的讨论组也是群（有群号未显示）

**Comment by ryoii** [comment]
新建的群也是归为群，我已经创建不了讨论组了，测试不了

**Comment by Him188** [comment]
因此没有太大必要支持讨论组了
