### ISSUE TITLE
syncFromEvent 文档错误

### ISSUE THREAD

**Issue by ls148478** [mamoe/mirai#427]
![Uploading 7482d884036e415.jpg…]()

**Comment by mzdluo123** [comment]
？你的图片坏了

**Comment by ls148478** [comment]
> ？你的图片坏了

我好像发不了图片

**Comment by ls148478** [comment]
![24b65ac7249d3a11](https://user-images.githubusercontent.com/38435967/87024716-0fe0ac80-c20c-11ea-8527-2bd73066a99b.jpg)

**Comment by Him188** [comment]
应删除 KDoc 中的 "\`-1\` 为不限制"'
