### ISSUE TITLE
有时候出现异常

### ISSUE THREAD

**Issue by HappyOnion801** [mamoe/mirai#434]
[有时候收到消息后会报异常，不知道是什么原因]
![K{FRM%Q5TTWQ(M6(K_%CU)M](https://user-images.githubusercontent.com/53887690/87495558-41ca9680-c684-11ea-91a3-41c89d445217.png)

**Comment by ryoii** [comment]
请提供完整日志、异常堆栈

**Comment by HappyOnion801** [comment]
怎么查看完整日志解决饥饿😢

**Comment by mzdluo123** [comment]
请提供完整截图和引发异常的操作

**Comment by Him188** [comment]
请使用1.1.0版本，这是1.0版本的问题

**Comment by HappyOnion801** [comment]
![image](https://user-images.githubusercontent.com/53887690/87498949-a4736080-c68b-11ea-8344-b61a1475394b.png)
没有操作，一般都是收到消息后出现

**Comment by Him188** [comment]
请提供使用的版本号

**Comment by HappyOnion801** [comment]
都是1.1.1版本

**Comment by Him188** [comment]
请问是否有使用 `ListenerHost` 相关 API? 请提供相关代码.

**Comment by HappyOnion801** [comment]
我的就是项目上的那个demo，具体的我也不明白，而且我发现下边的那个消息事件并没有监听到

**Comment by Him188** [comment]
经检查, 此问题就是 #436 ,由于 #436 描述更详细, 故关闭这个 issue. 请跟踪 #436 以获取修复进度
