### ISSUE TITLE
支持好友消息撤回事件

### ISSUE THREAD

**Issue by KawaiiZapic** [mamoe/mirai#435]
按照`Mirai HTTP API`的文档,机器人应当可以收到好友撤回消息.  
今天在测试所有事件时,发现能够正常收到好友发送消息事件,群发送消息事件,以及群撤回事件.  
但是无法收到好友消息撤回事件.
在对Bot私聊并撤回消息时,HTTP API未返回任何事件,Mirai控制台无任何报错输出,也无事件输出.
~~向其他群友请求验证,可奈何世间人情冷漠~~

### 如何复现
1. 私聊Bot,发送一条消息
2. 撤回该消息

### 版本
`mirai-console-0.5.2`  
`mirai-core-qqandroid-1.0.3`

**Comment by ryoii** [comment]
Core尚未支持，http-api仅暴露了接口
