### ISSUE TITLE
JvmMethodListeners#registerEvent#bug

### ISSUE THREAD

**Issue by BOFA1ex** [mamoe/mirai#436]
1.0.3 升级到 1.1.1版本遇到的异常问题.
Events.registerEvents(bot, listenerHost);
error :> Kotlin event handlers cannot have nullable parameter type.

### 版本
mirai: `1.1.1` 

commit#9a57f35890622c2025aed9c70cae10a97aa493d8

JvmMethodListeners#registerEvent#line:298

require(kotlinFunction.parameters.any { it.type.isMarkedNullable }) {
          "Kotlin event handlers cannot have nullable parameter type."
}

这里应该是!kotlinFunction.parameters.any { it.type.isMarkedNullable }
否则@EventHandler修饰的方法入参, 如果声明为javax.annotation.NotNull会抛出异常.

#java-snippets#

    @NotNull
    @EventHandler
    public ListeningStatus listenFriendEvent( @javax.annotation.Nullable FriendEvent friendEvent){
        return ListeningStatus.LISTENING;
    }

**Comment by Him188** [comment]
感谢发现这个问题
