### ISSUE TITLE
支持解析分片信息

### ISSUE THREAD

**Issue by Mrs4s** [mamoe/mirai#440]
在某些情况下，超长消息会被QQ分片发送，mirai无法正常解析。 

### 版本
mirai: `1.1.1` 

可在`MsgOnlinePush.PbPushMsg.msg.contentHead`中找到 `pkgNum`  `pkgIndex` `divSeq` 用于构建fragmented message.

**Comment by Him188** [comment]
在2.0-M2考虑 MessageSource.originalMessage 是否需要改动
