### ISSUE TITLE
如何才能监听到消息

### ISSUE THREAD

**Issue by HappyOnion801** [mamoe/mirai#441]
我想在收到消息是进行自定义的回复，我参照了哪个java-Demo，但是并没有成功：
`final Bot bot = BotFactoryJvm.newBot(number, "password", new BotConfiguration() {
            {
                fileBasedDeviceInfo("deviceInfo.json");
            }
        });
        bot.login();
        Events.registerEvents(bot, new SimpleListenerHost() {
            public ListeningStatus listenFriendEvent(FriendEvent friendEvent){
                System.out.println("收到了消息");
                return ListeningStatus.LISTENING;
            }
        });
        bot.join();
`
感谢你们的帮助

**Comment by BOFA1ex** [comment]
LoginSolver#设备锁二维码或验证码验证是否通过? 
检查下控制台输出日志.

**Comment by sandtechnology** [comment]
请为监听方法加上`@EventHandler`注解 否则方法将不会被调用

**Comment by HappyOnion801** [comment]
我添加了@EventHandler的注解，但是发现并不行
```java
class Test {
    public static void main(String[] args) throws InterruptedException {
        final Bot bot = BotFactoryJvm.newBot(qq, password, new BotConfiguration() {
            {
                fileBasedDeviceInfo("deviceInfo.json");
            }
        });
        bot.login();
        Events.registerEvents(bot, new SimpleListenerHost() {
            @EventHandler
            public ListeningStatus listenFriendEvent(FriendEvent friendEvent){
                System.out.println("收到消息");
                return ListeningStatus.LISTENING;
            }
        });
        bot.join();
    }
    private static String toString(MessageChain chain) {
        return chain.contentToString();
    }
}
```````
这是我的代码，希望能得到演示成功地代码

**Comment by BOFA1ex** [comment]
> 我添加了@eventhandler的注解，但是发现并不行
> 
> ```java
> class Test {
>     public static void main(String[] args) throws InterruptedException {
>         final Bot bot = BotFactoryJvm.newBot(qq, password, new BotConfiguration() {
>             {
>                 fileBasedDeviceInfo("deviceInfo.json");
>             }
>         });
>         bot.login();
>         Events.registerEvents(bot, new SimpleListenerHost() {
>             @EventHandler
>             public ListeningStatus listenFriendEvent(FriendEvent friendEvent){
>                 System.out.println("收到消息");
>                 return ListeningStatus.LISTENING;
>             }
>         });
>         bot.join();
>     }
>     private static String toString(MessageChain chain) {
>         return chain.contentToString();
>     }
> }
> ```
> 
> 这是我的代码，希望能得到演示成功地代码

默认登录校验策略会检测你是否支持swing, 你演示的情况最好带上控制台日志输出.
DefaultLoginSolver#init

> ```java
> init {
>       if (WindowHelperJvm.isDesktopSupported) {
>            delegate = SwingSolver
>       } else {
>            delegate = StandardCharImageLoginSolver(input, overrideLogger)
>       }
>}
>
> ```

**Comment by HappyOnion801** [comment]
@BOFA1ex 
控制台的话的确显示接收到了消息，也输出了消息内容，但是哪个是由jar包内代码输出的，应该算是日志吧，我想实现自定义的回复消息，测试了java-demo中的完整代码，但是发现依然不能监听到消息事件。

**Comment by BOFA1ex** [comment]
> @BOFA1ex
> 控制台的话的确显示接收到了消息，也输出了消息内容，但是哪个是由jar包内代码输出的，应该算是日志吧，我想实现自定义的回复消息，测试了java-demo中的完整代码，但是发现依然不能监听到消息事件。

demo项目的示例没有问题, 我不太清楚你的描述.

这是我参考demo, ws接收事件上报.

![image](https://user-images.githubusercontent.com/30573693/87744707-bafdf100-c81e-11ea-8bbe-417b0da561c6.png)

 ``` java
@EventHandler
public void listen(@Nullable MessageEvent event) {
    final Bot bot = event.getBot();
    info(bot, "规则入口#事件上报 {}", event.getClass().getSimpleName());
    SessionManagerEx.getSessionDelegator(bot.getId()).getSharedSlots().forEach(session -> {
    	SessionPacketManager.sendMessage(session, ImmutableMap.of(
    	    "event", event.getMessage().contentToString()
    	));
    });
}
```

**Comment by HappyOnion801** [comment]
@BOFA1ex 
这段代码我不会添加，请原谅我是个小白。
我的意思就是说比如：你想收到一个好友消息后，回复一个“你好”，这个功能应该怎么实现？

**Comment by BOFA1ex** [comment]
> @BOFA1ex
> 这段代码我不会添加，请原谅我是个小白。
> 我的意思就是说比如：你想收到一个好友消息后，回复一个“你好”，这个功能应该怎么实现？

我发现了盲点.. FriendMessageEvent并不是FriendEvent的子类.
```java
@EventHandler
public void listenFriendMessageEvent(@Nullable FriendMessageEvent event){
    Optional.ofNullable(event).orElseThrow(() -> new IllegalArgumentException("event不可为空"))
        .getSender().sendMessage("你好");
}
```

**Comment by Him188** [comment]
> FriendMessageEvent并不是FriendEvent的子类.

这个问题可能需要独立解决，将会再开一个 issue

**Comment by Him188** [comment]
#444

**Comment by HappyOnion801** [comment]
好的，谢谢
