### ISSUE TITLE
强制使用botid区分deviceinfo

### ISSUE THREAD

**Issue by mzdluo123** [mamoe/mirai#442]
让不同的bot在任何情况都不会使用到相同的deviceinfo，防止出现离谱的事情

**Comment by Him188** [comment]
现在是第一次启动会随机一次，之后都使用同样的设备信息（如果启用 `fileBasedDeviceInfo()`）

但强制 bot 区分是否有必要？可能还需要继续考虑这个问题，因为官方客户端也是很多账号用同一个设备信息。

另外，如果要做出区分的修改，这将是一个 breaking change，需要考虑迁移周期，因此我将降低优先级。

**Comment by mzdluo123** [comment]
有必要，今早我在测试的时候不小心在服务器和本地使用了同一个deviceinfo导致两个账号都被封了

**Comment by BOFA1ex** [comment]
尝试分文件夹.
```java
setDeviceInfo(context -> SystemDeviceInfoKt.loadAsDeviceInfo(
	Paths.get(String.format(RobotProps.getDeviceInfoPath(), account))
		.resolve(deviceInfoName).toFile(), this.getJson(), context)
);
```
![image](https://user-images.githubusercontent.com/30573693/87753608-89445480-c835-11ea-9c7d-eff0a9b209a9.png)

**Comment by mzdluo123** [comment]
尝试区分文件夹算是可以的，但是强制区分之后可以有助于防止不小心误操作导致意外发生

**Comment by Him188** [comment]
进行改动需要一个迁移过程, 迁移方案有待讨论

**Comment by ryoii** [comment]
参照i18n的模式，使用`deviceinfo_botUin.json`命名方式，如果查找不到，默认使用`deviceinfo.json`

**Comment by Him188** [comment]
应该由用户自己区分设备名, 如 `fileBasedDeviceInfo("deviceInfo_${bot.id}.json")`. 根据现有 API, mirai 无法做默认行为修改.
