### ISSUE TITLE
BotInvitedJoinGroupRequestEvent重复执行两次

### ISSUE THREAD

**Issue by ls148478** [mamoe/mirai#449]
BotInvitedJoinGroupRequestEvent(机器人被邀请加入一个群)事件
这个事件 貌似会执行两次 我这里测试都是执行了两次 然后不管是accept()还是ignore()执行的时候都会报错
`Caused by: java.lang.IllegalStateException: Job UndispatchedCoroutine{Completed}@5e87c978 is already complete or completing, but is being completed with STOPPED`
我怀疑是执行了两次的原因导致发生以上报错

**Comment by Him188** [comment]
请提供版本号和相关日志

**Comment by ryoii** [comment]
> 请提供版本号和相关日志

确实存在的问题，req包发了两次，回来的包也解了两次，包含时间戳内容一模一样，两次发包应该是服务器行为

**Comment by ls148478** [comment]
> > 请提供版本号和相关日志
> 
> 确实存在的问题，req包发了两次，回来的包也解了两次，包含时间戳内容一模一样，两次发包应该是服务器行为

感谢测试 那我就不提供版本号和日志了
