### ISSUE TITLE
我的密码有十七个英文字母

### ISSUE THREAD

**Issue by WuZeyue** [mamoe/mirai#451]
`fun md5(stream: InputStream): ByteArray {
        val digest = MessageDigest.getInstance("md5")
        digest.reset()
        stream.use { input ->
            object : OutputStream() {
                override fun write(b: Int) {
                    digest.update(b.toByte())
                }
            }.use { output ->
                input.copyTo(output)
            }
        }
        return digest.digest()
    }`
这是mirai中关于MD5的源码。我一直登录不上。我是学Java的，kotlin看不太懂，但我还是看出源码中是将密码转化而成的ByteArray一个一个字节转化成MD5，不知道对17位的密码有没有影响。因为我所接触的MD5加密是先加密成字符串的。

**Comment by Him188** [comment]
你好, 不会有影响
