### ISSUE TITLE
群名片通知问题

### ISSUE THREAD

**Issue by ls148478** [mamoe/mirai#455]
群名片改动事件在群友刚加入群的时候会通知 还有群友在此群之前没有发言记录 然后刚好说话也会触发 以上两种 origin(修改前)都为空字符串
然后在某些时刻会有重复通知的问题 重复通知的复现办法还没找到

**Comment by Him188** [comment]
![image](https://user-images.githubusercontent.com/12100985/87962299-8d000180-cae9-11ea-85e1-a1653d83b575.png)
这个改动可能已经在 1.1.3 发布, 若没有, 则会在 1.2.0 发布

**Comment by ryoii** [comment]
官方客户端中，也是同样的行为，只有成员主动发言或者主动查看群员资料的时候，群名片才会被刷新
