### ISSUE TITLE
Json卡片消息

### ISSUE THREAD

**Issue by ls148478** [mamoe/mirai#457]
Json消息出现发送接收不到的情况
确定了没和谐！
`{"app":"com.tencent.mobileqq.reading","desc":"","view":"singleImg","ver":"1.0.0.70","prompt":"[色图]","appID":"","sourceName":"","actionData":"","actionData_A":"","sourceUrl":"","meta":{"singleImg":{"mainImage":"https://i.pixiv.cat/img-original/img/2018/11/01/20/44/02/71458025_p0.png","mainUrl":"https://i.pixiv.cat/img-original/img/2018/11/01/20/44/02/71458025_p0.png"}},"text":"","extraApps":[],"sourceAd":"","extra":""}`

**Comment by Him188** [comment]
这是JSON数据问题, 不是mirai问题

**Comment by devzwy** [comment]
怎么发送卡片信息啊大佬们
