### ISSUE TITLE
私聊引用回复

### ISSUE THREAD

**Issue by ls148478** [mamoe/mirai#462]
使用引用回复的时候 貌似会把引用回复的字数和准备发送的字数加在一起 导致消息过长 然后报错`java.lang.IllegalStateException: Send temp message failed: MessageSvcPbSendMsg.Response.Failed(resultType=10, errorCode=0, errorMessage=)`
只是私聊
版本是最新版本

**Comment by Him188** [comment]
此为正常现象, 请跟踪 #171 的修复进度
