### ISSUE TITLE
好友消息无法接受

### ISSUE THREAD

**Issue by xiaofentai** [mamoe/mirai#463]
有人能告诉我怎么解决长时间（其实也就几小时）挂mirai消息会被mirai吞了的问题吗，作为一个只会写点简单代码的小白来说实在是有点摸不着头脑
![976E4667751BEDCF083B2C628BAAB038](https://user-images.githubusercontent.com/62656473/87960239-9b005300-cae6-11ea-89e1-4ce78cf20174.png)（就是这里的MessageSvc.PbGetMsg和MessageSvc.PbDeleteMsg是为什么会发生的）

**Comment by Him188** [comment]
#249
