### ISSUE TITLE
打卡,一起听歌类型检测不到

### ISSUE THREAD

**Issue by daofeng2015** [mamoe/mirai#467]
- [x] 我已经对照 CHANGELOG ，相关问题未在近期更新中解决
- [x] 我已经搜索了已有的 Issues 列表中有没相关的信息
- [x] 我已经阅读了 Mirai 的相关文档

![QQ截图20200726005315](https://user-images.githubusercontent.com/14891398/88461975-d5009900-ceda-11ea-93f4-8c0c32984643.png)
![QQ截图20200726005513](https://user-images.githubusercontent.com/14891398/88461978-d6ca5c80-ceda-11ea-9295-526b2d73640e.png)

**Comment by Him188** [comment]
群签到：#326
