### ISSUE TITLE
怎么根据 MessageId 来获取某群的某条消息啊

### ISSUE THREAD

**Issue by MrXiaoM** [mamoe/mirai#483]
- [x] 我已经对照 CHANGELOG ，相关问题未在近期更新中解决
- [x] 我已经搜索了已有的 Issues 列表中有没相关的信息
- [x] 我已经阅读了 Mirai 的相关文档

想做一个“防撤回”的功能。不知道能不能通过 MessageId 获取到某群的某条消息  
不想通过储存近期消息内容到HashMap的方式然后需要的时候获取，所以在这里问一下  
如果不行就只能储存近期消息内容了，感谢  
目前机器人只为一个群服务，不需要考虑有多个群

**Comment by Him188** [comment]
mirai 不内建缓存，因此无法获取。
有计划支持消息的序列化，详见 #219
