### ISSUE TITLE
emmm....我闲着没事做了个社区....收录了一下近三个月更新过的bot插件....

### ISSUE THREAD

**Issue by sakurayun** [mamoe/mirai#486]
**emmm....我着没事做了个社区....收录了一下近三个月更新过的bot插件....**
https://yami.cat
**有兴趣的话可以来看看（**

**Comment by sakurayun** [comment]
[](https://yami.cat)

**Comment by sakurayun** [comment]
https://yami.cat

**Comment by sakurayun** [comment]
啊....忘了说了....需要登录才能看帖子的....

**Comment by Him188** [comment]
感谢你的工作，但我们近期不考虑（在项目中）推广第三方论坛（也没有计划建立官方论坛）。
