### ISSUE TITLE
消息字数上限达不到预想值

### ISSUE THREAD

**Issue by chi1216** [mamoe/mirai#490]
- [x] 我已经对照 CHANGELOG ，相关问题未在近期更新中解决
- [x] 我已经搜索了已有的 Issues 列表中有没相关的信息
- [x] 我已经阅读了 Mirai 的相关文档

在Java下，使用sendMessage字数一旦超过292汉字则必定报错。

```
Exception in thread "Thread-7" java.lang.IllegalStateException: Send temp message failed: MessageSvcPbSendMsg.Response.Failed(resultType=10, errorCode=0, errorMessage=)


```

#### 复现

发送好友消息，字数超过292。

#### 版本
mirai: ` 1.1.3`

**Comment by sandtechnology** [comment]
#171

**Comment by chi1216** [comment]
@sandtechnology 谢谢，我才看到这个，希望可以解决。现在版本的测试结果是群消息也没法发送大于292个字.

**Comment by sandtechnology** [comment]
> 
> 
> @sandtechnology 谢谢，我才看到这个，希望可以解决。现在版本的测试结果是群消息也没法发送大于292个字.

群消息可以的 应该是检测长消息时遇到了极限情况 带图呢？

**Comment by ryoii** [comment]
方便提供一下发送文本？

**Comment by chi1216** [comment]
> 群消息可以的 应该是检测长消息时遇到了极限情况 带图呢？

原来是这样，我又测试了一下，群消息的确可以达到504字，现在还没有测试带图片的消息。

**Comment by chi1216** [comment]
> 方便提供一下发送文本？
又重新去测试了一遍，来发截图了。

**以下截图都是可以发送的最大字数，再多一个字符就会报错**

群消息是这样的确实可以达到1008字符，多余的直接切掉。
![image](https://user-images.githubusercontent.com/46589416/90361121-5beb0080-e098-11ea-8edd-2be769fe9d91.png)

这个是私聊消息的情况：
如果是纯半角字符，则可以支持到876个字符
![image](https://user-images.githubusercontent.com/46589416/90361464-3dd1d000-e099-11ea-8071-74b382776df9.png)
如果是汉字，则只能584字符
![image](https://user-images.githubusercontent.com/46589416/90361540-72de2280-e099-11ea-8bf1-f52757d32888.png)
如果是汉字加半角，就会发生一些变化
![image](https://user-images.githubusercontent.com/46589416/90361652-b769be00-e099-11ea-9f17-f5afebad2dd8.png)

**Comment by ryoii** [comment]
@chi1216 请直接提供一个你会报错的文本

**Comment by chi1216** [comment]
> @chi1216 请直接提供一个你会报错的文本

私聊消息文本：

> 啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊

**Comment by ryoii** [comment]
私聊不做检查，提供群聊报错，谢谢

**Comment by chi1216** [comment]
> 私聊不做检查，提供群聊报错，谢谢

打扰了 群聊消息不会报错，多余消息直接切掉了，是我之前记错了。

**Comment by Him188** [comment]
#171
