### ISSUE TITLE
音乐分享 XML 消息在好友发送正常，但在群大概率不正常

### ISSUE THREAD

**Issue by BFvX** [mamoe/mirai#492]
_其实已有的Issues列表中有一类似情况，但感觉其情境不太明确，因此不能确定是否为同一问题，因此还是斗胆再次提出此疑问。_

借用cqhttp-mirai处理音乐分享为xml信息格式后发送时，若**发送对象为好友**时，可以**正常接收**到音乐分享信息；但是若为**发送到群内**，则**基本接收不到**音乐分享信息。但偶尔可以正常接收到，且似乎为：一段时间后，可以接收到一条分享信息，此后无法接收到分享信息，直到再次经过一段时间后可以再次接收到。（也可能只是随缘收到）

测试发送内容[INFO]如下：
` 14:06:39 [INFO] [BOT 123456789] Group(123456) <- [mirai:service:60,<?xml version='1.0' encoding='UTF-8' standalone='yes' ?><msg serviceID="2" templateID="1" action="web" brief="[分享] 夜奏花" sourceMsgId="0" url="https://i.y.qq.com/v8/playsong.html?_wv=1&amp;songid=217551140&amp;souce=qqshare&amp;source=qqshare&amp;ADTAG=qqshare" flag="0" adverSign="0" multiMsgFlag="0"><item layout="2"><audio cover="http://imgcache.qq.com/music/photo/album_500/70/500_albumpic_4690970_0.jpg" src="" /><title>夜奏花</title><summary>YURiKA</summary></item><source name="QQ音乐" icon="https://i.gtimg.cn/open/app_icon/01/07/98/56/1101079856_100_m.png" url="http://web.p.qq.com/qqmpmobile/aio/app.html?id=1101079856" action="app" a_actionData="com.tencent.qqmusic" i_actionData="tencent1101079856://" appid="1101079856" /></msg>]`
正常发送/接收的[DEBUG]如下：
` 14:06:20 [DEBUG] [CQHTTPMirai] {"status":"ok","retcode":0,"data":{"type":"MessageData","message_id":130},"echo":{"seq":32}}`
未能正常接收的[DEBUG]如下：
` 14:06:39 [DEBUG] [CQHTTPMirai] {"status":"ok","retcode":0,"data":{"type":"MessageData","message_id":-1},"echo":{"seq":36}}`
发现未正常接受的DEBUG中"message_id"为-1，不知是否有关。
_（看错了……这个DEBUG是CQHTTPMirai的……）_

此外，无论是个人或群均可正常接收到发送的文本及图片信息。

如果造成此问题同样是因为Mirai不具有ServiceMessage的稳定性，或该问题不属于Mirai的问题，则非常抱歉打扰……

**Comment by Him188** [comment]
经初步分析，这应该不是 mirai 的问题。请检查 CQHttpMirai。

mirai 会直接将消息 xml 发送，因此理应不会出现问题。但不能排除发送这些分享时是不是还需要带一些元数据（如一些 flags）。

我们可能会在将来进行这样的检查，但这项工作优先级会较低。

**Comment by ls148478** [comment]
可以发送 
![Screenshot_2020-08-17-16-29-43-28](https://user-images.githubusercontent.com/38435967/90374979-e63a6100-e0a6-11ea-90e2-acaa77bf86c6.png)

**Comment by Him188** [comment]
我看到你的日志中：

> "message_id":-1

请确认这表示什么（CQHttpMirai）

**Comment by BFvX** [comment]
> 可以发送
> ![Screenshot_2020-08-17-16-29-43-28](https://user-images.githubusercontent.com/38435967/90374979-e63a6100-e0a6-11ea-90e2-acaa77bf86c6.png)



> 可以发送
> ![Screenshot_2020-08-17-16-29-43-28](https://user-images.githubusercontent.com/38435967/90374979-e63a6100-e0a6-11ea-90e2-acaa77bf86c6.png)

能请问一下测试环境和方法吗

**Comment by ls148478** [comment]
> > 可以发送
> > ![Screenshot_2020-08-17-16-29-43-28](https://user-images.githubusercontent.com/38435967/90374979-e63a6100-e0a6-11ea-90e2-acaa77bf86c6.png)
> 
> 能请问一下测试环境和方法吗

我是用kt写的 我看了你的那个问题 原因是开头service不对 他不是60 他应该和下面的xml代码中的serviceID相同 所以他应该=2 我不清楚cqhttp应该怎么写 但是问题应该就是这个 因为当初我也遇到过 祝你能解决问题

**Comment by BFvX** [comment]
> 经初步分析，这应该不是 mirai 的问题。请检查 CQHttpMirai。
> 
> mirai 会直接将消息 xml 发送，因此理应不会出现问题。但不能排除发送这些分享时是不是还需要带一些元数据（如一些 flags）。
> 
> 我们可能会在将来进行这样的检查，但这项工作优先级会较低。

了解。
单论我提出的这个问题，最近的测试又趋于正常……目前正在寻找是否可以复现之前的问题。
有需要的话可以先Close了。

**Comment by yyuueexxiinngg** [comment]
测试正常, 发送`XML`消息易触发风控, 考虑是否因为风控造成的发送不正常


> 我看到你的日志中：
> 
> > "message_id":-1
> 
> 请确认这表示什么（CQHttpMirai）

`CQHTTPMirai`中此`message_id`即为`MessageSource.id`, 推测起因为TX方面的风控

**Comment by Him188** [comment]
音乐分享现在需要通过互联通道发送,  #682 , 已经在 2.1.0 完成
