### ISSUE TITLE
支持解析好友消息「对方正在输入」

### ISSUE THREAD

**Issue by qianjunakasumi** [mamoe/mirai#493]
如标题所示，最近我在查看 log 时发现如下信息

```
18:05:34 [INFO] [Command] 207******3 login successes
 18:05:35 [INFO] [NETWORK] Received unknown commandName: ConfigPushSvc.PushDomain
 18:05:36 [INFO] [NETWORK] Recv: ConfigPushSvc.PushReq.PushReqResponse.Success
 18:05:36 [INFO] [NETWORK] Send: ConfigPushSvc.PushResp
 18:05:36 [INFO] [NETWORK] ConfigPushSvc.PushReq: Success
 18:06:02 [INFO] [NETWORK] unknown group 528 type 0x0000000000000115, data: 08 FB CC D3 95 0C 10 B1 B0 97 DD 07 1A 29 08 00 10 05 18 8A AD E9 F9 05 20 01 28 FF FF FF FF 0F 32 15 E5 AF B9 E6 96 B9 E6 AD A3 E5 9C A8 E8 BE 93 E5 85 A5 2E 2E 2E
 18:06:02 [INFO] [NETWORK] Send: OnlinePush.RespPush
 18:06:11 [INFO] [NETWORK] Send: OnlinePush.RespPush
 18:06:14 [INFO] [NETWORK] unknown group 528 type 0x0000000000000115, data: 08 FB CC D3 95 0C 10 B1 B0 97 DD 07 1A 14 08 00 10 05 18 96 AD E9 F9 05 20 02 28 FF FF FF FF 0F 32 00
 18:06:14 [INFO] [NETWORK] Send: OnlinePush.RespPush
 18:06:23 [INFO] [NETWORK] Send: OnlinePush.RespPush
```

经过反复实验得知` 18:06:02 [INFO] [NETWORK] unknown group 528 type 0x0000000000000115, data: 08 FB CC D3 95 0C 10 B1 B0 97 DD 07 1A 29 08 00 10 05 18 8A AD E9 F9 05 20 01 28 FF FF FF FF 0F 32 15 E5 AF B9 E6 96 B9 E6 AD A3 E5 9C A8 E8 BE 93 E5 85 A5 2E 2E 2E` 为 `对方正在输入...` 的提示

` 18:06:14 [INFO] [NETWORK] unknown group 528 type 0x0000000000000115, data: 08 FB CC D3 95 0C 10 B1 B0 97 DD 07 1A 14 08 00 10 05 18 96 AD E9 F9 05 20 02 28 FF FF FF FF 0F 32 00` 为取消上述正在输入说明的提示

重现方法：打开与机器人好友聊天的会话窗口，输入任意文本出现第一条未知事件。将输入的文本全部删除出现第二条未知事件

截图：
![正在输入](https://s1.ax1x.com/2020/08/17/dmUVKO.png)
![取消正在输入](https://s1.ax1x.com/2020/08/17/dmUAxK.png)

**Comment by Him188** [comment]
请问有什么用例吗

**Comment by qianjunakasumi** [comment]
应用场景：作为智能AI聊天机器人时，可以获得场景信息。
例如：您在与机器人对话时，机器人可以通过该事件知晓您正在输入的状态，智能判断，面对第一次使用机器人的用户，机器人能够主动与用户产生对话，抛弃原设计只能一令一动主动查询菜单的理念，打造面向用户体验型、服务型机器人，满足用户的幸福感，同时将Mirai与其他同类产品加以区分

当然上面的描述只是设想而已，权且希望贵方能解决该 unknown 的提示，至于支持该(非大众需求)事件行为可以日后再议

谢谢您的答复
