### ISSUE TITLE
很多修改群名片的操作未能成功

### ISSUE THREAD

**Issue by yoonching** [mamoe/mirai#494]
开发团队，您好。
我正在制作一个通过考生号自动验证新生入群并修改名片的插件，通过marai native作为插件与mirai的桥梁。

我想讨论的问题是，近期在实际使用mirai过程中，发现修改名片的操作，很少能操作成功。既，机器人发出了修改名片操作，在手机用其他帐号查看效果，是没有看到修改名片的结果的，还是默认的群成员名片。

相关问题我也在mirai native的issue进行过反馈与讨论->https://github.com/iTXTech/mirai-native/issues/19

最后在mirai native那边探讨决定待这边开放issue后反馈。

相关日志如下。

```
18:03:53 [INFO] [NETWORK] Send: MessageSvc.PbGetMsg
18:03:53 [INFO] [NETWORK] Send: MessageSvc.PbDeleteMsg
18:03:53 [INFO] [NETWORK] Send: ProfileService.Pb.ReqSystemMsgNew.Group
18:03:53 [INFO] [BOT 715209226] Event: MemberJoinRequestEvent(bot=Bot(7*****), eventId=1597399433447470, message=问 题：请输入*****\n答案：*****12, fromId=*****44, groupId=*****49, groupName=*****新生 群, fromNick=***炎)
18:03:53 [DEBUG] [MiraiNative] [加群自动审批本地版2020 用户输入答案] *****12
18:03:54 [INFO] [NETWORK] Send: ProfileService.Pb.ReqSystemMsgAction.Group
18:03:54 [DEBUG] [MiraiNative] [加群自动审批本地版2020 设置用户群名片为：] 20-**学院-**希
**18:03:54 [INFO] [NETWORK] Send: friendlist.ModifyGroupCardReq**
18:03:54 [INFO] [NETWORK] Recv: TroopManagement.EditGroupNametag.Response
18:03:54 [INFO] [NETWORK] Send: MessageSvc.PbGetMsg
18:03:54 [INFO] [NETWORK] Received unknown commandName: ProfileService.Pb.ReqSystemMsgAction.Group
18:03:54 [INFO] [NETWORK] Send: OnlinePush.RespPush
18:03:54 [INFO] [NETWORK] Send: MessageSvc.PbDeleteMsg
18:04:03 [INFO] [NETWORK] Send: OnlinePush.RespPush
```

**Comment by Him188** [comment]
请在手机端主动点击被改群员的群资料, 查看是否有变化(服务器不会告知名片修改, 总是客户端主动查询修改)

**Comment by mzdluo123** [comment]
有更详细的关于什么情况下会成功，什么情况下会失败的信息吗？

**Comment by yoonching** [comment]
> 请在手机端主动点击被改群员的群资料, 查看是否有变化(服务器不会告知名片修改, 总是客户端主动查询修改)

您好，感谢回复。
对于确认名片有无修改成功，我是这样操作的：
1、新成员入群后，我看到控制台打印了Mirai发出修改群名片的网络包
2、拿出手机，找到这个群成员，看ta的资料
3、确认名片有无修改 -> 大多数情况没修改成功

我的插件是用易语言开发的coolQ dll。在触发_eventSystem_GroupMemberIncrease事件后，立即用代码操作群名片。

**Comment by yoonching** [comment]
> 有更详细的关于什么情况下会成功，什么情况下会失败的信息吗？

您好。目前还真的没有看出来规律。

只清楚在什么情况下修改名片。我是在mirai native触发了_eventSystem_GroupMemberIncrease事件（群人数增加）后立即修改群名片的。

**Comment by Him188** [comment]
For mamoe: 
检查 `ProfileService.Pb.ReqSystemMsgNew.Group` 使用的 groupCode/groupUin 是否正确

**Comment by ryoii** [comment]
`dwGroupCode = member.group.id,` 应该没有问题

**Comment by Him188** [comment]
请问在这之后 (群员入群成功一段时间后) 可以成功修改群员昵称吗?

**Comment by yoonching** [comment]
> @yoonching 请问在这之后 (群员入群成功一段时间后) 可以成功修改群员昵称吗?

您好，最近出远门刚到家。我在易语言代码里做了修改，触发群成员增加事件时，增加了一条类似sleep1秒的操作，这样的话修改名片的成功率特别高。目前是看到5条入群的记录，都成功修改了名片。还会继续观察的。

**Comment by Him188** [comment]
由于延迟可以解决问题, 故降低优先级

**Comment by Him188** [comment]
延迟可以解决, 是否说明这可能是服务器的限制? 因为在 QQ 官方客户端内不可能存在进群立即改群名的情况
