### ISSUE TITLE
关于cookie部分的获取

### ISSUE THREAD

**Issue by 2879597772** [mamoe/mirai#506]
通过阅读文档，确定可能不会增加cookies这个功能，也知晓获取cookie后被滥用的风险可能被增加
但是在腾讯的部分api中，必须携带一下cookie才能访问，例如这个可以获取等级的
vip.qq.com/pk/index?param=[QQ号]
需要携带uin=***; skey=***才能访问成功
uin，skey也是腾讯一些基础业务访问必须要的cookie
希望可以让我们获取到uin和skey（因为实在太常用了）
至于其他的如P_skey、M_skey，可能涉及到qq空间、支付等相关的cookie可以屏蔽

其实原来的*Q也有开放cookie，不过也仅给出了uin和skey，

**Comment by mzdluo123** [comment]
您可以将其整和到mirai-core内，这样既可以保证安全性也便于其他用户使用

**Comment by ryoii** [comment]
你有任何正当使用cookie的理由可以通过PR来给Mirai增加接口并通过审核，而不是期望直接暴露cookie来增加潜在风险。
酷Q是酷Q，Mirai是Mirai
