### ISSUE TITLE
AGPLv3 with Mamoe Exceptions 似乎不太合理

### ISSUE THREAD

**Issue by Moreonenight** [mamoe/mirai#510]
- [x] 我已经对照 CHANGELOG ，相关问题未在近期更新中解决
- [x] 我已经搜索了已有的 Issues 列表中有没相关的信息
- [ ] 我已经阅读了 Mirai 的相关文档

1. “衍生软件” (衍生软件: 间接或直接接触到 Mirai, 即使没有修改 Mirai 源码的软件) 似乎涵盖范围过大。例如，操作系统按照括号中的定义可能也算“衍生软件”。

2. AGPL第 7 款规定：

> All other non-permissive additional terms are considered "further
> restrictions" within the meaning of section 10.  If the Program as you
> received it, or any part of it, contains a notice stating that it is
> governed by this License along with a term that is a further
> restriction, you may remove that term.  If a license document contains
> a further restriction but permits relicensing or conveying under this
> License, you may add to a covered work material governed by the terms
> of that license document, provided that the further restriction does
> not survive such relicensing or conveying.

> Additional terms, permissive or non-permissive, may be stated in the
> form of a separately written license, or stated as exceptions;
> the above requirements apply either way.

也就是说，AGPL 本身不允许附加额外限制条款。如果附加了额外限制条款（包括 "stated as exceptions" 的情形），那么该限制条款就可以直接删去。"Mamoe Exceptions" 中的 "The following exceptions shall prevail if conflict with AGPLv3." 会产生逻辑上的死循环。即使认为 "Mamoe Exceptions" 确实 "prevail" 了，AGPL 第 12 款又规定：

> If conditions are imposed on you (whether by court order, agreement or
> otherwise) that contradict the conditions of this License, they do not
> excuse you from the conditions of this License.  If you cannot convey a
> covered work so as to satisfy simultaneously your obligations under this
> License and any other pertinent obligations, then as a consequence you may
> not convey it at all.  For example, if you agree to terms that obligate you
> to collect a royalty for further conveying from those to whom you convey
> the Program, the only way you could satisfy both those terms and this
> License would be to refrain entirely from conveying the Program.

换句话说，接收到 "Mamoe Exceptions" 的用户会丧失 AGPL 赋予其的大多数许可。

3. 在开源许可证上做文章对利用 Mirai 进行违法犯罪活动的人几乎毫无影响，对于规避法律风险似乎也意义有限（我在中国裁判文书网上用“开源许可证”做关键词没搜到案例），反而损害遵守开源许可证的用户的利益。

希望 Mirai 开发者可以考虑上述建议。如果一定要制定特殊的许可条款，个人建议直接移除 AGPL，并在 REAMDE 或/和 LICENSE 中简要地列明自己设定的许可条款。当然，如果可以改回 AGPL 的话自然再好不过。

**Comment by Him188** [comment]
这个协议确实有问题, 但趋于某种不可抗力因素制约, mirai 必须使用强约束的协议

**Comment by Him188** [comment]
我们会在近期修正协议

**Comment by Hagb** [comment]
另外 mirai 的贡献者都享有其贡献部分的版权。要更改 mirai 后续版本的许可证，是不是要得到所有版权持有者的同意？🤔

**Comment by 1354092549** [comment]
@Hagb 关于这个问题，我的建议是，要求每位贡献者在提交Pull Request时，明确声明放弃版权或给予某种授权

**Comment by 1354092549** [comment]
这也是大多数商业公司的开源项目所使用的方案：在合并前要求签署开源协议

**Comment by 1354092549** [comment]
@Him188 
根据GPL/AGPL协议要求，已经给出的许可无法撤销（但可以对旧版本给出其他许可，即多重许可，如大多数商业开源项目所使用的：商业闭源授权+GPL开源授权）
因此无论做何种修改，这些额外限制都仅可以限制新版本改变的部分代码
如果衍生产品仅使用旧版本代码，新增限制无效

**Comment by 1354092549** [comment]
> 对于规避法律风险似乎也意义有限（我在中国裁判文书网上用“开源许可证”做关键词没搜到案例）

以GPL为关键词搜索，可以搜到侵害计算机软件著作权纠纷的民事案件

**Comment by uebian** [comment]
如果弃用AGPLv3会有个问题，受GPL传染性影响，mirai将不再能引用GPL以发布的代码

**Comment by 1354092549** [comment]
@uebian 
目前的这种额外限制其实已经打破了 GPL兼容性

**Comment by 1354092549** [comment]
GPL系列是用于自由软件的
额外限制已经使得二次分发变得“不自由”，这就违反了GPL中禁止扩展许可证的要求

**Comment by 1354092549** [comment]
使用GPL系列条款，是必然不能限制商业使用的
当然，鉴于本项目的特殊性，可以要求用户在商业使用前取得腾讯公司的许可
因为本项目从开始到现在就一直不是纯AGPL授权的，协议部分版权归属腾讯，而学习交流豁免的那部分法律条文显然不适用于商业用途

**Comment by iiMemory** [comment]
> 我们会在近期修正协议

自从某Q倒了以后从事商业化运营的人开始转战mirai，修改协议对这群人没有任何的作用，而遵守协议的人不需要修改也一样

**Comment by PeratX** [comment]
mirai 将不再作为自由软件发行，而是严格限制的开源软件

> ，修改协议对这群人没有任何的作用

开源协议在中国大陆虽然不具有法律约束力

**Comment by 1354092549** [comment]
> 开源协议在中国大陆不具有法律约束力

开源协议在中国具有法律约束力
判决文书网有大量案例，明确承认开源协议属于合同法的范畴
但对于一些细节概念在中国法律下的解释，目前确实没有统一约定

**Comment by 1354092549** [comment]
> 从事商业化运营的人开始转战mirai

我觉得区分 商业化的聊天机器人 和 群发赌博等黑产 是有必要的

**Comment by Hagb** [comment]
> 开源协议在中国大陆不具有法律约束力

该判决书承认 GPL 的法律效力： [柚子（北京）移动技术有限公司等与数字天堂（北京）网络技术有限公司二审民事判决书](https://wenshu.court.gov.cn/website/wenshu/181107ANFZ0BXSK4/index.html?docId=3c0957c9b82e456eb6ceab0d002c50ba)

> mirai 将不再作为自由软件发行，而是严格限制的开源软件

顺带，禁止商用而源码公开的软件也不能称作开源软件：
[The Open Source Definition](https://opensource.org/osd#fields-of-endeavor)
> For example, it may not restrict the program from being used in a **business**, or from being used for genetic research.

**Comment by PeratX** [comment]
请问楼上两位，能免费为mirai提起诉讼吗？如果不能，请继续做美梦。

**Comment by 1354092549** [comment]
> 请问楼上两位，能免费为mirai提起诉讼吗？如果不能，请继续做美梦。

任何诉讼都是需要成本的，但这和能不能诉讼没有关系

**Comment by 1354092549** [comment]
就像微软容许洗白Win10的行为存在，不等于在法律上这些版本都合法了
至于是否提起诉讼，这是版权人的权利

**Comment by mzdluo123** [comment]
建议直接拉黑
