### ISSUE TITLE
语音方法无法调用

### ISSUE THREAD

**Issue by Lin-XCC** [mamoe/mirai#512]
发现更新1.2.0加了语音方法，但是在maven更新了版本之后，通过group无法调用uploadVoice。
![image](https://user-images.githubusercontent.com/52395718/90633951-8801af80-e259-11ea-81a4-a4e153b21ab7.png)
![image](https://user-images.githubusercontent.com/52395718/90633765-335e3480-e259-11ea-982e-1131aaaa3581.png)

**Comment by sandtechnology** [comment]
原因是没有为新方法创建JavaFriendlyAPI
Ktolin中应该能正常调用
