### ISSUE TITLE
多 Bot 监听事件时的自动 Bot 实例筛选方案

### ISSUE THREAD

**Issue by ForteScarlet** [mamoe/mirai#514]
我以如下方法登陆了两个Bot: 
```kotlin
val b1 = Bot(111111111111, "xxxxxxxx")
    b1.subscribeAlways<MessageEvent> {
        println("bot${this.bot.id}收到消息：${this.message}")
    }
    b1.login()


    val b2 = Bot(22222222222, "xxxxxxxx")
    b2.subscribeAlways<MessageEvent> {
        println("bot${this.bot.id}收到消息：${this.message}")
    }
    b2.login()

    b1.join()
    b2.join()
```

然后我通过私聊给账号为`111111111111`的bot发送**1次**消息，控制台会出现：
```
2020-08-19 20:50:44 V/Bot 3521361891: 法欧特斯卡雷特_offical(1149159218) -> [mirai:source:31863,1369724219]mua
bot111111111111收到消息：[mirai:source:31863,1369724219]mua
bot111111111111收到消息：[mirai:source:31863,1369724219]mua
```

即账号11111111的消息监听被触发了两次

我认为不应该出现这种情况，因此我认为这是一个BUG。

#### 版本
mirai: `1.0.2`，` 1.2.0`

**Comment by Him188** [comment]
这是正常结果. 

`CoroutineScope.subscribeAlways` 不会筛选 `Bot` 实例.

可以使用 `bot.subscribeAlways` 是因为 `Bot` 也实现接口 `CoroutineScope`

**Comment by ForteScarlet** [comment]
那么请问应该如何以区分bot的情况来注册监听呢

**Comment by Anders233** [comment]
开两个Mirai(bushi)

**Comment by Him188** [comment]
请手动筛选实例: 
```kotlin
val myBot: Bot
subscribeAlways<E> {  // this: E
    if (this.bot != myBot) return
```

**Comment by ForteScarlet** [comment]
了解了，感谢解答

**Comment by Him188** [comment]
这确实是一个不便之处. 但我们还没有想好如何设计自动筛选 bot 的 API.

**Comment by ForteScarlet** [comment]
那在想好之前我先使用手动筛选的方式了

**Comment by Him188** [comment]
考虑去除 Bot 实现的 CoroutineScope 接口，可以避免 CoroutineScope.subsribe 的调用

**Comment by Him188** [comment]
`Bot.eventChannel.subscribe<>` 来监听来自这个 Bot 的事件, `CoroutineScope.globalEventChannel.subscrib<>` 来监听全局事件

**Comment by Him188** [comment]
经过讨论, 解决方案已经确定: 引入 `EventChannel`, 弃用原 `CoroutineScope.subscribe` 系列方法.
