### ISSUE TITLE
群第一次获取isMuteAll时总是为true

### ISSUE THREAD

**Issue by ForteScarlet** [mamoe/mirai#515]
在使用的时候，我发现每次当我去第一次获取`Group.settings.isMuteAll`的时候总是会返回true值，只有当我设置过一次false的时候才会获取到false。

我又写了一个测试程序如下：
```kotlin
val bot = Bot(...)
    bot.login()

    bot.groups.forEach {
        println("group(${it.id}) muteAll: ${it.settings.isMuteAll}")
    }

    bot.closeAndJoin()
```

我也可以确定测试的群当时并不是全体禁言状态。

得到的结果为所群的`isMuteAll`都是true。

我认为这并不合理，因此提交了此bug。

#### 版本
mirai: ` 1.2.1`

**Comment by sandtechnology** [comment]
#286
