### ISSUE TITLE
添加邀请好友或者临时会话成员入群的方法

### ISSUE THREAD

**Issue by khjxiaogu** [mamoe/mirai#521]
- [x] 我已经对照 CHANGELOG ，相关问题未在近期更新中解决
  - [x] 我已经搜索了已有的 Issues 列表中有没相关的信息
  - [x] 我已经阅读了 Mirai 的相关文档
允许机器人邀请好友入群，并且添加获得入群链接的方法。

**Comment by ryoii** [comment]
## 不会支持的协议
+ 金钱相关，如点赞、收付款
+ 敏感操作，如主动添加好友、主动加入群、**主动邀请好友加群**
+ 安全相关，获取账号登录凭证(token，cookie等)
