### ISSUE TITLE
发送 QuoteReply 消息时无可避免的产生多余空格

### ISSUE THREAD

**Issue by Glavo** [mamoe/mirai#524]
当使用 `event.quoteReply` 回复（或者等效的，在消息最前面拼接 `QuoteReply` 并发送）时，发送出的消息内容前会出现一个空格。

将 `QuoteReply` 拼接到消息其他地方可以避免消息空格出现在消息前，但消息内容与 `QuoteReply` 的拼接处依然会产生空格，并且在 PC QQ 和安卓 QQ 中有不同的显示：

发送的消息（代码）：`event.reply(PlainText("Test") + event.message.quote())`
发送的消息（日志中的显示）： `Test[mirai:quote:388625,-681065281]`
PC QQ 中的显示（消息内容后有一个 `At`，并且有两个空格）：
```
Test@Glavo  
```
安卓 QQ 中的显示（最后有一个空格）：
```
Test 
```

#### 版本
mirai: ` 1.2.1`

**Comment by mrhso** [comment]
实际上 at（net/mamoe/mirai/qqandroid/message/conversions.kt#L116）也有同样的问题。

**Comment by Glavo** [comment]
> 实际上 at（net/mamoe/mirai/qqandroid/message/conversions.kt#L116）也有同样的问题。

看起来这是 #411 的根源？

**Comment by mrhso** [comment]
> > 实际上 at（net/mamoe/mirai/qqandroid/message/conversions.kt#L116）也有同样的问题。
> 
> 看起来这个是 #411 的根源？

我认为是的。
