### ISSUE TITLE
跑 Java demo 依赖1.2.2 版本 mirai-core 时报错 java.lang.NoClassDefFoundError: kotlin/KotlinNothingValueException

### ISSUE THREAD

**Issue by weekdragon** [mamoe/mirai#534]
Java版本：1.8
构建工具：maven
开发工具：sts

在我将项目中的 mirai-core-qqandroid 和 mirai-core 依赖版本由1.1.3 提升到 1.2.2 的时候发现启动报错了
为了排除其他影响，我跑了一遍官方 Demo，发现任然报错，但是用 1.1.3 就没有任何问题。
截图如下：
![image](https://user-images.githubusercontent.com/9250229/91017310-a7fdee00-e620-11ea-8062-f5b94f1c2645.png)

依赖如下

> 		<dependency>
> 			<groupId>net.mamoe</groupId>
> 			<artifactId>mirai-core-qqandroid</artifactId>
> 			<version>1.2.2</version> 
> 		</dependency>
> 				<dependency>
> 			<groupId>net.mamoe</groupId>
> 			<artifactId>mirai-core</artifactId>
> 			<version>1.2.2</version> 
> 		</dependency>

错误信息如下：

> Exception in thread "main" java.lang.NoClassDefFoundError: kotlin/KotlinNothingValueException
> 	at net.mamoe.mirai.qqandroid.QQAndroid.newBot(QQAndroid.kt:31)
> 	at net.mamoe.mirai.BotFactoryJvm.newBot(BotFactory.kt:83)
> 	at cn.weekdragon.datagrab.config.robot.MiraiDemo.main(MiraiDemo.java:36)
> Caused by: java.lang.ClassNotFoundException: kotlin.KotlinNothingValueException
> 	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
> 	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
> 	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:355)
> 	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
> 	... 3 more

**Comment by Him188** [comment]
请更新 Kotlin 依赖版本到 1.4.0

**Comment by weekdragon** [comment]
> 请更新 Kotlin 依赖版本到 1.4.0

显式的依赖 Kotlin 到 1.4.0 就好了，只是有点奇怪，为啥 maven 会给我自动下载 1.3.72 版本的 Kotlin
![image](https://user-images.githubusercontent.com/9250229/91034139-10f06080-e637-11ea-86a9-5f4ff0f3de58.png)

**Comment by Him188** [comment]
可能是你使用了其他的库，他们使用的是 1.3.72

**Comment by Myfanqie** [comment]
有用
