### ISSUE TITLE
请问作者，怎样发送一个xml呢，比如发送音乐分享的样式

### ISSUE THREAD

**Issue by lycstar** [mamoe/mirai#537]

**Comment by Him188** [comment]
阅读 https://github.com/mamoe/mirai/blob/master/docs/mirai.md
`ServiceMessage`

**Comment by lycstar** [comment]
> 阅读 https://github.com/mamoe/mirai/blob/master/docs/mirai.md
> `ServiceMessage`

谢谢帮助

**Comment by WDmarding** [comment]
> 阅读https://github.com/mamoe/mirai/blob/master/docs/mirai.md
> `ServiceMessage`

404了求指导
