### ISSUE TITLE
Quote引用bug

### ISSUE THREAD

**Issue by Cyenoch** [mamoe/mirai#54]
bot引用别人的内容，Tim PC看不见**引用的内容**，能看见**bot发出的消息内容**
Tim PC引用bot的引用回复，Tim PC显示的是 **一个引用**，但看不见**bot发出的消息内容**，手机端显示为At

**Comment by Him188** [comment]
时不时无法显示。
有时候at在引用前面（PC QQ）

**Comment by Him188** [comment]
是 At 问题. 已在 #73  修复
