### ISSUE TITLE
踢群人员后，报错！！

### ISSUE THREAD

**Issue by Andy-shi001** [mamoe/mirai#540]
![image](https://user-images.githubusercontent.com/68884928/91155692-c41f8f00-e6f5-11ea-99e4-a37afaf06a8a.png)

core版本：mirai-core-qqandroid-1.1.3.jar

**Comment by Him188** [comment]
你使用的版本不是 1.1.3, 而是 1.0.4 之前的版本. 

1.0.4 的部分更新记录:
> 修复 Bot 在某个群 T 出某个人导致 Bot 终止的问题 (#372)

**Comment by Andy-shi001** [comment]
如何获取新版本，我用的是miraiOK的

**Comment by Andy-shi001** [comment]
> 你使用的版本不是 1.1.3, 而是 1.0.4 之前的版本.
> 
> 1.0.4 的部分更新记录:
> 
> > 修复 Bot 在某个群 T 出某个人导致 Bot 终止的问题 (#372)
如何获取新版本，我用的是miraiOK的

**Comment by Him188** [comment]
miraiOK 在重启时会自动更新, 请等待维护者更新即可

**Comment by Andy-shi001** [comment]
> miraiOK 在重启时会自动更新, 请等待维护者更新即可
我如何切换到mirai-core-qqandroid-1.1.3 这个版本呢？需要修改mirai-console-wrapper-1.3.0.jar 升级吗？
![image](https://user-images.githubusercontent.com/68884928/91378093-31e0cd80-e852-11ea-8376-bb4e98d2d130.png)
![image](https://user-images.githubusercontent.com/68884928/91378037-0a8a0080-e852-11ea-9470-c2af7b5a2d78.png)
![image](https://user-images.githubusercontent.com/68884928/91378066-1bd30d00-e852-11ea-9eb5-d12d482d266e.png)

**Comment by daofeng2015** [comment]
@Andy-shi001 请去miraiok项目发issue.作者说了最近考试，等几天就更新支持新的console和core了
