### ISSUE TITLE
成员被踢出群 MemberLeaveEventKick 和 成员主动离群MemberLeaveEventQuit监听不到

### ISSUE THREAD

**Issue by Andy-shi001** [mamoe/mirai#541]
![image](https://user-images.githubusercontent.com/68884928/91156132-558f0100-e6f6-11ea-83a3-0487f06e356c.png)

重启服务会更新 mirai-core-qqandroid-1.1.3.jar，退群事件失效
使用Websocket
监听该接口，插件将推送Bot收到的事件 [ws] /event?sessionKey=YourSessionKey
监听该接口，插件将推送Bot收到的事件和消息 [ws] /all?sessionKey=YourSessionKey
成员主动退群后监听不到事件

**Comment by Him188** [comment]
请使用 1.2.2
