### ISSUE TITLE
关于消息的拼凑

### ISSUE THREAD

**Issue by 1847757288** [mamoe/mirai#544]
Message.plus(另一个Message) 操作后，返回的是一个Messagechain,然后Messagechain是不可变的，所以怎么将多个Message链接到一起呢？？

**Comment by Him188** [comment]
Java: `a.plus(a).plus(c).plus(d)`
Kotlin: `a + b + c + d`

**Comment by Him188** [comment]
当消息很多时, 可考虑使用 `MessageChainBuilder`
