### ISSUE TITLE
支持群成员入群时间和最后发言时间的功能

### ISSUE THREAD

**Issue by Steve-xmh** [mamoe/mirai#545]
正在做群成员的长期潜水踢出功能，但是没有和 CQ 类似的获取 cookies 的 API，所以得用数据库持续记录群员的发言时间，比较繁琐。

这个 API 不一定要提供 cookies，只要能获取到这类的时间就完全可以了。

如有冒犯请谅解，各位大大辛苦了 ！

**Comment by Him188** [comment]
已有相关问题
