### ISSUE TITLE
QuoteReply中messagechain消息里的图片会被替换成"[图片]"字符串

### ISSUE THREAD

**Issue by ls148478** [mamoe/mirai#546]
我在翻阅Issues看到过相关问题 但我经过各种实验 都是这种情况，所以我觉得应该是后续版本的问题导致 所以再提出一个Issues
先上代码
`subscribeAlways<MessageEvent> {
            if(message.anyIsInstance<QuoteReply>()) {
                reply(message.get(QuoteReply)!!.source.originalMessage)
            }
        }`
测试图
![-7008a9c9c8e4dcd](https://user-images.githubusercontent.com/38435967/91272844-f80abb00-e7ae-11ea-8aa6-6cceebf6d098.png)

**Comment by Him188** [comment]
这是正常情况. 服务器会将这些消息转换为 "[图片]" 再发送给客户端.

**Comment by Him188** [comment]
如要读取图片数据, 可考虑使用 `CustomMessageMetadata`

**Comment by ls148478** [comment]
> 如要读取图片数据, 可考虑使用 `CustomMessageMetadata`

请教一下：使用CustomMessageMetadata该如何操作

**Comment by Michael1015198808** [comment]
> 如要读取图片数据, 可考虑使用 `CustomMessageMetadata`

同问如何操作（
