### ISSUE TITLE
将MP3转码为silk并发送有尖锐噪音

### ISSUE THREAD

**Issue by golezi** [mamoe/mirai#548]
我目前的方案是，该方案在之前另一款bot软件上无此问题
ffmpeg -i {mp3_path} -f s16le -ar 24000 -ac 1 -acodec pcm_s16le {tmp_path}
encoder {tmp_path} {silk_path}  -tencent
其中encoder来自https://github.com/kn007/silk-v3-decoder
但是转码后的silk发送后有尖锐噪音，源文件128MP3和FLAC都有此问题
对于这方面不太了解，猜测或许是音频比特率不同

以下是我转码后的结果
[000hscqh1l8UlG.zip](https://github.com/mamoe/mirai/files/5132327/000hscqh1l8UlG.zip)

**Comment by Him188** [comment]
这是转码问题，不是 mirai 协议问题

**Comment by TheSnowfield** [comment]
> 我目前的方案是，该方案在之前另一款bot软件上无此问题
> ffmpeg -i {mp3_path} -f s16le -ar 24000 -ac 1 -acodec pcm_s16le {tmp_path}
> encoder {tmp_path} {silk_path} -tencent
> 其中encoder来自https://github.com/kn007/silk-v3-decoder
> 但是转码后的silk发送后有尖锐噪音，源文件128MP3和FLAC都有此问题
> 对于这方面不太了解，猜测或许是音频比特率不同
> 
> 以下是我转码后的结果
> [000hscqh1l8UlG.zip](https://github.com/mamoe/mirai/files/5132327/000hscqh1l8UlG.zip)

I guess it's a resample issue independent of the miai.
In my experience in ffmpeg, when target sample rate higher than original sample rate maybe cause this bug.
You could try to reduce your target sample rate or grab it from original.
BTW, could you please offer me a PCM? I want to check the wave and confirm my opinion. Thanks.

**Comment by golezi** [comment]
> > 我目前的方案是，该方案在之前另一款bot软件上无此问题
> > ffmpeg -i {mp3_path} -f s16le -ar 24000 -ac 1 -acodec pcm_s16le {tmp_path}
> > encoder {tmp_path} {silk_path} -tencent
> > 其中encoder来自https://github.com/kn007/silk-v3-decoder
> > 但是转码后的silk发送后有尖锐噪音，源文件128MP3和FLAC都有此问题
> > 对于这方面不太了解，猜测或许是音频比特率不同
> > 以下是我转码后的结果
> > [000hscqh1l8UlG.zip](https://github.com/mamoe/mirai/files/5132327/000hscqh1l8UlG.zip)
> 
> I guess it's a resample issue independent of the miai.
> In my experience in ffmpeg, when target sample rate higher than original sample rate maybe cause this bug.
> You could try to reduce your target sample rate or grab it from original.
> BTW, could you please offer me a PCM? I want to check the wave and confirm my opinion. Thanks.

I cant upload more than 10M file in issue,so I upload to https://github.com/golezi/silk.
I tryed to edit "-ar" parameters in command "ffmpeg -i {mp3_path} -f s16le -ar 24000 -ac 1 -acodec pcm_s16le {tmp_path}",but it's not useful.
thanks for you help

**Comment by TheSnowfield** [comment]
I have tested encoder and silk file, but I am not replay this issue. I just heard too many junk but no glitch. 
Mirai supports both amr and silk format, you could try convert to amr format instead.

**Comment by golezi** [comment]
I had convert to amr,still sounds not good but it's useful,I do it just for fun.
thanks

**Comment by golezi** [comment]
被项目成员close的issue无法reopen了

**Comment by golezi** [comment]
被项目成员close的issue无法reopen了
另一个相关issue也无下文
希望开发组能查看下该问题吧
