### ISSUE TITLE
添加“图片-文字”消息

### ISSUE THREAD

**Issue by Hutao6688** [mamoe/mirai#552]
请求官方 添加“图片-文字”消息（群和好友），就是一条消息里面，包含着一个或几个图片，下面是文字，这些东西包含在一条消息里面

**Comment by sandtechnology** [comment]
？这样的信息是可以直接构建的，请阅读demo和文档

Sent from Outlook Mobile<https://aka.ms/blhgte>

________________________________

**Comment by Hutao6688** [comment]
你好，能直接告诉我怎样做吗，你给的链接有问题，打开里面不是文档

**Comment by ls148478** [comment]
> 你好，能直接告诉我怎样做吗，你给的链接有问题，打开里面不是文档

按顺序添加就可以了 你想图片在前就先拼接图片 想字在前 就先拼接字即可
