### ISSUE TITLE
在config.txt中加login自动登录后，MiraiNative插件不能自动启用

### ISSUE THREAD

**Issue by nlpguyz** [mamoe/mirai#555]
如果不在config.txt自动登录，而是手动从控制台输入login命令，MiraiNative的插件可以自动启用（在config.json中enable即可）。但是，如果是config.txt自动登录的，在完全初始化好之后，MiraiNative载入的插件都是禁用的。需要在login完全完成后，打npm enable 0才能启用。

#### 复现
1. 安装MiraiNative插件，并在plugins中放一个酷Q的插件，并且在config.json中设置启用"enable"
2. 启动 mirai-console (我用的是miraiok)，输入 login <qq> <password> 登录，等待加载各种好友和群信息，直到能看到接收的消息，打 npm list 查看插件状态，为启用。
3. 修改config.txt加入login <qq> <password>
4. 重新启动mirai，在自动登录完成，看到消息后，打 npm list 看到插件被禁用了。需要输入 npm enable 0 才能启用插件。

#### 版本
mirai: `0.5.2 Pkmon` 
解压自miraiok的windows版

**Comment by Karlatemp** [comment]
mirai-core作为框架不应该提供这些逻辑，应该由使用者自己提供

**Comment by Him188** [comment]
此问题可能是 mirai-native 相关问题。由于 mirai-native 与 mirai 处于不同 organization，我无法将这个 issue 转换过去。请自行重新发起 issue。
