### ISSUE TITLE
Mirai堆内存溢出

### ISSUE THREAD

**Issue by nlpguyz** [mamoe/mirai#556]
miraiok运行机器人两天后，发生以下错误：

![image](https://user-images.githubusercontent.com/25698072/91634163-10dbc200-e9a3-11ea-9b53-643ba3bb6dd6.png)

#### 复现
1. 启动miraiok登录，机器人每分钟收到60条左右信息，2天后出现

#### 版本
mirai: ` ` 
0.5.8

**Comment by Him188** [comment]
请提供:
- mirai-core, mirai-console 版本号
- 所有你正在使用的插件
- 操作系统情况 (类型, 总内存)
- 完整的日志 (从启动到发生OOM)

**Comment by nlpguyz** [comment]
带0.5.2版本console的miraiok for Windows
操作系统 Win 10, 64GB, Intel i9-9900K
插件MiraiNative, cn.muxiaofei.cq_python27_sdk

**Comment by Him188** [comment]
我们目前还无法确定问题, 请提供 console 的日志和近期内存情况 (是在短时间内突然上升还是逐渐上升)

**Comment by rMuchan** [comment]
我也遇到了类似的问题。
版本：cqhttp-mirai-0.2.2 embedded版，基于mirai-console 0.5.2。
插件：embedded版携带的cqhttp-mirai，无其他插件。
操作系统：CentOS 7，2G内存。
出现OOM后，有一段时间系统几乎卡死，此时java堆直方图显示有15577个byte\[\]占用了400M空间（堆容量460M）。恢复响应后（可能已经发生过GC）获取到堆转储，发现协程调度器持有了大量包含byte\[65536\]的continuation，对应协程类为`net.mamoe.mirai.qqandroid.network.QQAndroidBotNetworkHandler$sendAndExpect$7`（反编译观察，大约是`doSendAndReceive`的位置）。
可能是网络原因，但即使加上两次重试，这个函数也应该在15秒内结束，尚未找到堆积了上千个continuation的原因。
![image](https://user-images.githubusercontent.com/13314764/91721152-dfddd600-ebca-11ea-8227-95509b1396c9.png)

**Comment by liushaocong** [comment]
版本：mirai-core-qqandroid-1.1.3.jar，mirai-console-0.5.2.jar
插件：Dice!-2.4.0,mirai-api-http-v1.6.5,mirai-native-1.7.0
CPU： 4核
内存： 8 GiB
实例类型： I/O优化
操作系统： Windows Server 2019 with ...


我在电脑上挂了9个mirai程序，有一个qq加了近500个群，登录时内存短时间内突然上升，挂了几个小时后会报Java.lang.outofmemoryerror错误，然后就卡住了

**Comment by Him188** [comment]
@liushaocong 请提供日志, 期间内存变化, 使用的插件等所有相关情况

**Comment by liushaocong** [comment]
日志文件没有写进去,是需要手动开启吗，我截了最后运行时的图

使用的插件：
 MiraiAPIHTTP vv1.6.5 by ryoii Mirai HTTP API Server Plugin
 MiraiNative v1.7.0 by iTX Technologies 
<img width="954" alt="屏幕快照 2020-09-02 下午2 03 19" src="https://user-images.githubusercontent.com/29514866/91939215-02393600-ed28-11ea-8b75-aa9ce787862e.png">
<img width="1193" alt="屏幕快照 2020-09-02 下午2 21 39" src="https://user-images.githubusercontent.com/29514866/91939224-082f1700-ed28-11ea-82b5-d186489183fa.png">

**Comment by 1523789353** [comment]
开久了cpu使用率有些高
![1](https://user-images.githubusercontent.com/39769643/93008743-f90f5b00-f5aa-11ea-995c-06dd812719a1.png)
估计与这个issue相关

**Comment by liushaocong** [comment]
> @liushaocong 请提供日志, 期间内存变化, 使用的插件等所有相关情况

[log.txt](https://github.com/mamoe/mirai/files/5213902/log.txt)
您好，日志发出来了，有时间帮忙看下

**Comment by liushaocong** [comment]
@Him188 您好，日志发出来了，有时间帮忙看下，谢谢
[log.txt](https://github.com/mamoe/mirai/files/5213906/log.txt)

**Comment by ryoii** [comment]
按上面日志看，新生区70M，老年区170M。对于使用了 mirai-console 和 mirai-api-http 的情况下，如果群数量较多，且 mirai-api-http 消息缓存设置得较大，确实堆空间是不太够的。0.5.2版本的 mirai-console 按照的以往加载 mirai-api-http 测试的经历，单个群的号启动占用到120M左右。

内存占用主要来源于成员信息和插件信息，OOM应该在短时间内爆发。

我自己的 core 程序，运行两周，启动时占用50M左右，两周后提升到80M。core 里应该不存在持续增加占用内存的逻辑，这块应该是产生内存泄漏了。

core版本：1.2.1

**Comment by baobao323** [comment]
不知道是不是同一个问题,大概25-30个小时就会崩一次
![9 D 6J13VMN2}CA3X9$N1MS](https://user-images.githubusercontent.com/59369343/93868718-75b5de00-fcfd-11ea-8105-422bf83ded17.png)
[hs_err_pid15092.log](https://github.com/mamoe/mirai/files/5260552/hs_err_pid15092.log)

**Comment by sandtechnology** [comment]
如果要排查这个问题，估计需要分析堆内存信息
建议在启动参数中加上`-XX:+HeapDumpOnOutOfMemoryError` 然后在崩溃的时候上传headdump进行分析
（因为一般大小比较大，建议传到微云）

**Comment by liushaocong** [comment]
怎么提高JVM虚拟机的内存呢?我在jre\lib\i386目录下的jvm.cfg文件下添加了以下参数
-Xms800m
-Xmx1024m
启动时提示
<img width="790" alt="屏幕快照 2020-10-12 下午5 23 34" src="https://user-images.githubusercontent.com/29514866/95730047-4f59e180-0cb0-11eb-98b8-d8e58009ca7f.png">

**Comment by way-zer** [comment]
我也遇到了OOM问题，仅使用Mirai Core，待会附上内存转储

**Comment by sandtechnology** [comment]
> 
> 
> 我也遇到了OOM问题，仅使用Mirai Core.
> 简单分析了内存转储，500M中，与mirai相关的问题接近400M. 与协程也有部分关联。
> 转储文件已上传到奶牛(有效期到12-09日) https://cowtransfer.com/s/922e6365019f46
> 
> EDIT:
> mirai core 版本 1.3.1

这是Mindustry加载库文件的问题 不是mirai问题：
![TIM截图20201203124621](https://user-images.githubusercontent.com/20417547/100965446-addf6580-3565-11eb-8261-f0fd2f8f4b4b.png)
![TIM截图20201203124650](https://user-images.githubusercontent.com/20417547/100965454-b041bf80-3565-11eb-8525-4068777c4092.png)

**Comment by Him188** [comment]
- For mamoe:
检查发送图片时使用的缓存机制 (看到上面 java.exe 打开了 747 个文件)

**Comment by Him188** [comment]
> For mamoe:
> 
> * [x]  检查发送图片时使用的缓存机制 (看到上面 java.exe 打开了 747 个文件)

上文打开文件没有被释放已经在 #675 解决, 将包含在 2.0-M1

**Comment by Him188** [comment]
如果使用 2.0-M1 仍然遇到问题，请及时反馈以便进行后续调查

**Comment by way-zer** [comment]
> > For mamoe:
> > 
> > * [x]   检查发送图片时使用的缓存机制 (看到上面 java.exe 打开了 747 个文件)
> 
> 上文打开文件没有被释放已经在 #675 解决, 将包含在 2.0-M1.
> 
> 在 2.0-M1 做了修复处理, 现将优先级降低并观察

感觉不像文件打开没有释放的原因,堆栈中发现上万协程，怀疑是协程泄漏。
![image](https://user-images.githubusercontent.com/15688938/102705665-f7011a80-42c4-11eb-856d-5e232093d423.png)
#675 问题确实有遇到过不少次，不过遇到只有报错，内存泄漏不太清楚。
整个内存泄漏是偶然事件，上次发生后，现在半个月还没有复发

**Comment by Him188** [comment]
经检查, 在发包时如果网络出问题, `PacketListener` 协程会泄露. 在重试时也没有处理 `CancellationException` 因此会导致更多的泄露.

**Comment by Him188** [comment]
现在不太可能再有泄露情况了. 一切资源都会在 `sendAndExpect` 结束时被关闭. 因此我将关闭这个 issue. 如果还有泄露情况可回复
