### ISSUE TITLE
消息积压，积压消息同时发送出去

### ISSUE THREAD

**Issue by YuuHomura** [mamoe/mirai#560]
发送指令后都没有得到bot的回复，进入服务器查看mirai控制台，突然就把所有指令的回复都推送了出去。这是什么原因？

**Comment by Him188** [comment]
很有可能你在 Kotlin 协程中运行阻塞任务, 因此没有足够的线程来运行协程. 请参考 Kotlin 协程 .

**Comment by sandtechnology** [comment]
**进入服务器查看mirai控制台**

目测是因为进入了选取模式导致了线程阻塞 应该视为invaild
