### ISSUE TITLE
支持重新读取群成员列表

### ISSUE THREAD

**Issue by MrTC1277** [mamoe/mirai#563]
前提：使用mirai-native插件加载酷Q的插件
已经向mirai-native作者反馈了这个问题，但表示不是插件的问题

描述这个Bug
第一次取群成员列表没有问题，即使进行了修改，之后的数据与第一次相同

![QQ截图20200823233756](https://user-images.githubusercontent.com/37472014/91725354-31895f00-ebd1-11ea-8382-b1d9c53233c4.png)
![QQ截图20200831212759](https://user-images.githubusercontent.com/37472014/91725366-377f4000-ebd1-11ea-9e93-3ecc1b0e0bff.png)

抱歉，截图更直观

#### 复现

发送指令触发取群成员列表

#### 版本
mirai: ` ` 

 - 操作系统：Windows 10 1909
 - `mirai core` 版本：：1.2.2
 - `mirai console` 版本：1.0-M3-1

**Comment by mzdluo123** [comment]
请描述一下进行了更改是什么样的更改，否则我们无法定位问题

**Comment by Him188** [comment]
请尽可能描述问题发生过程

**Comment by MrTC1277** [comment]
> 请尽可能描述问题发生过程
获取群成员列表后数据没有刷新（貌似使用了缓存），由第二张截图可以看到，临时机器人的昵称已经改为临时robot，性别改为女，但是重新获取到的昵称还是临时机器人，性别还是男，没有改变

**Comment by MrTC1277** [comment]
> 请尽可能描述问题发生过程

获取群成员列表后数据没有刷新（貌似使用了缓存），由第二张截图可以看到，临时机器人的昵称已经改为临时robot，性别改为女，但是重新获取到的昵称还是临时机器人，性别还是男，没有改变

**Comment by MrTC1277** [comment]
> 请描述一下进行了更改是什么样的更改，否则我们无法定位问题

获取群成员列表后数据没有刷新（貌似使用了缓存），由第二张截图可以看到，临时机器人的昵称已经改为临时robot，性别改为女，但是重新获取到的昵称还是临时机器人，性别还是男，没有改变

**Comment by Him188** [comment]
服务器不会广播这些信息, 无法获取修改. 
一次群成员列表查询耗时长达数秒, 最多只能提供刷新列表的处理方式.

**Comment by MrTC1277** [comment]
> 服务器不会广播这些信息, 无法获取修改.
> 一次群成员列表查询耗时长达数秒, 最多只能提供刷新列表的处理方式.

请问这个处理方式是什么？

**Comment by Him188** [comment]
没有处理方式. 只能主动重新查询群列表. 目前可重新登录 bot 实现 (但这不一定稳定)

**Comment by Him188** [comment]
2.1 实现了查询成员资料, 这个刷新应该不太需要了
