### ISSUE TITLE
是否考虑新增文件协议支持？

### ISSUE THREAD

**Issue by Night12138** [mamoe/mirai#568]
有时候希望利用bot当作一个文件处理的工具，例如处理一些excel表格解析信息，虽然也可以通过网页上传，但是其实直接通过bot的接口可能会更加方便。
本需求已经考虑过，受众面肯定不会很广，所以估计大概率不会接受吧。
所以想问问，作为框架底层该想法是否有可能实现？例如底层的一些与qq交互的接口是否支持文件信息类型以及接收离线文件传输？如果有可能的话我也许会fork下来后进行开发。没有的话我就不费时间读源码了【，另外感谢查看本issue。

**Comment by Him188** [comment]
QQ 自身是支持的，但这个实现起来会费时费力，不会给予高优先级

**Comment by Night12138** [comment]
了解了，感谢回复，那我找时间研究源码后尝试一下。

**Comment by Night12138** [comment]
> QQ 自身是支持的，但这个实现起来会费时费力，不会给予高优先级

了解了，感谢回复，那我找时间研究一下。
