### ISSUE TITLE
一条消息被拆分成多条的问题

### ISSUE THREAD

**Issue by apuded** [mamoe/mirai#569]
QQ群明明是收到一条文本消息，几百字这样，mirai控制台打印出来，会打印多条，每个文本长度150左右，消息ID间隔了1，这几个文本拼起来才是完整的QQ群内容。
对方发消息的也是个哪个平台的QQ机器人，我自己的QQ号在群里发消息，mirai机器人收到的倒是是完整的消息，又没问题。
请问有人遇到这种情况吗？谢谢！

**Comment by Him188** [comment]
已有相关问题

**Comment by apuded** [comment]
> 已有相关问题

搜了

> 已有相关问题

请问解决方案是？

**Comment by Him188** [comment]
你真的搜了吗

https://github.com/mamoe/mirai/issues/440

这个问题还没解决

请不要浪费我的时间

**Comment by apuded** [comment]
> 你真的搜了吗
> 
> #440
> 
> 这个问题还没解决

可能关键字搜的不对，感谢回复。期待解决。
