### ISSUE TITLE
群上传图片，代码编译报错

### ISSUE THREAD

**Issue by Hutao6688** [mamoe/mirai#573]
群上传图片时，使用java写的代码会报错，编译不通过，marai1.2.1，android studio 3.6
看见问题里面有一个和我一样的，可是照做了还是不行

代码：
        try {
            image = group.uploadImage(new URL("https://profile.csdnimg.cn/2/9/1/3_u011489043"));
        } catch (MalformedURLException e) {
            e.printStackTrace();
        }

编译：
E:\ProjectAnd\TestAndQQ\app\src\main\java\com\xelen\testandqq\Action.java:25: 错误: 无法访问BufferedImage
            image = group.uploadImage(new URL("https://profile.csdnimg.cn/2/9/1/3_u011489043"));
                                   ^

**Comment by Him188** [comment]
在 2.0 前，mirai不支持在android使用。

**Comment by Hutao6688** [comment]
不好意思，我好像描述有错误，实际上是这个 implementation("net.mamoe:mirai-core-qqandroid:1.2.1")

**Comment by Him188** [comment]
-qqandroid是包名，不是平台
