### ISSUE TITLE
疑问：自动重连时的离线消息

### ISSUE THREAD

**Issue by Hieuzest** [mamoe/mirai#574]
Mirai似乎不能够读取离线消息？
我的情况主要是这样的：
bot每隔20min左右会drop一次（虽然消息是很少啦），然后reconnect in 0.5s，正常重连无错
但是如果刚好在这0.5s里来了消息就收不到了。
以前是没太注意，今天刚好漏了条重要消息，按这个频率来看好像还蛮严重的样子
是我个人的问题吗

core=1.2.1, bot with DeviceLock

**Comment by sandtechnology** [comment]
确实如此，我也在苦恼这个问题，不知道什么时候可以解决这种未知
原因的掉线。
Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by mzdluo123** [comment]
我们可能会在后期改善重连机制

**Comment by Him188** [comment]
与 #382 是同类问题
