### ISSUE TITLE
发送图片到QQ群，手机上可以显示，在电脑上无法加载显示

### ISSUE THREAD

**Issue by 781236208** [mamoe/mirai#576]
mirai-core-qqandroid-jvm-1.2.2，通过机器人向QQ群发送文字+图片，在手机上的QQ群中正常显示，在电脑上的QQ群中，偶尔会无法加载显示。发送本地图片或者转发其他QQ群的图片，都偶尔会出现这种情况。
ps：有时候鼠标多点几次以后能加载出来，更多时候是一直加载不出来。

**Comment by mzdluo123** [comment]
请检查你的图片是否为违规图片，违规图片大概率会出现这个问题。
如果不是违规图片仅有小概率情况会出现这个问题。目前并没有有效解决方案

**Comment by Him188** [comment]
以前确实遇到过这个问题, 但未知原因

**Comment by yujincheng08** [comment]
同。而且是特定群会有这种问题，其他群正常。

**Comment by 781236208** [comment]
不是违规图片，大概有5%到10%的图片，会出现这种情况，有些群出现极少，一天可能只有一两张，有些群出现的概率会更大一些。我现在给这个号开通了会员，设置了消息漫游，后续再观察。

**Comment by DF-46** [comment]
兄弟解决了没，有解决方法么
