### ISSUE TITLE
[Question]请问消息发送支持emoji吗？

### ISSUE THREAD

**Issue by sandtechnology** [mamoe/mirai#58]
因为我之前使用的是酷Q的机器人，在酷Q内，emoji表情需要转换为CQ码发送：https://docs.cqp.im/manual/cqcode/#emoji%E8%A1%A8%E6%83%85

**Comment by Him188** [comment]
支持，直接将表情作为string发送即可。
```kotlin
sender.sendMessage("🍎")
```

但mirai还不支持原生qq表情。

**Comment by Chenwe-i-lin** [comment]
unicode都支持吧.
