### ISSUE TITLE
mirai 进群事件捕获失效，只能执行一次

### ISSUE THREAD

**Issue by m839336369** [mamoe/mirai#581]
一个成员进群事件，在不装载任何插件的情况下，只会反馈一次，退群没问题，我使用同一个QQ，退群进群，只有mirai启动的第一次进群有反应，后续就不行了。

```



```

#### 版本
mirai: `1.2.2 `

**Comment by Him188** [comment]
请提供版本号和日志

**Comment by m839336369** [comment]
> 请提供版本号和日志
![image](https://user-images.githubusercontent.com/30934916/92615142-6000eb80-f2ef-11ea-9e02-d4ed36edae15.png)
日志没啥，就没报错，就是获取不到。

**Comment by Him188** [comment]
在你觉得没用的日志对我们是莫大的帮助. 没有日志无法定位问题.

**Comment by m839336369** [comment]
> 在你觉得没用的日志对我们是莫大的帮助. 没有日志无法定位问题.

[2020-09-09.log](https://github.com/mamoe/mirai/files/5196208/2020-09-09.log)

**Comment by Him188** [comment]
属于接收不到好友消息 (MessageSvc) 的同类问题

**Comment by Him188** [comment]
#249
