### ISSUE TITLE
运行在服务器上无法回复消息

### ISSUE THREAD

**Issue by YougaKing** [mamoe/mirai#582]
1.在mac上正常
2.把在mac上运行得到的DEVICE_INFO.json，调用loadDeviceInfoJson()方法一切正常
3.运行在服务器上，获取消息日志正常，有回复消息日志，but其他设备上并没有看到回复的消息

```



```

#### 版本
mirai: ` `

**Comment by Him188** [comment]
请提供版本和日志

**Comment by mzdluo123** [comment]
启动初期在Windows平台上的客户端有概率看不到信息，但是在移动平台上的客户端是正常的

**Comment by Him188** [comment]
如果短时间内频繁登录, 可能导致消息看不到, 一般在几分钟后即可恢复

**Comment by Him188** [comment]
一般在调试阶段才会出现这样的问题. 如果几分钟后仍未恢复, 可让 Bot 离线一段时间后重试
