### ISSUE TITLE
添加重新连接到服务器功能

### ISSUE THREAD

**Issue by Hutao6688** [mamoe/mirai#586]
在测试阶段，我经常kill掉整个机器人的进程，下一次再使用的时候（间隔很短，官方显示还没掉线）还要重新登陆，其实效果就和断开网络又重新连上那样，间隔很短，没有几次，账号就异常了，请问能不能出一个新的方法（并且公开调用），在两次相近的登陆中，后一次 直接是连接服务器，而不是重新登陆

**Comment by Him188** [comment]
#119
