### ISSUE TITLE
sentby(id) 无法匹配对应对象

### ISSUE THREAD

**Issue by ZGarry** [mamoe/mirai#587]
## 问题
sentby id无法匹配，但always中可以

### 能匹配上
![image](https://user-images.githubusercontent.com/43488431/92761709-8775b800-f3c4-11ea-9fbc-596cab226981.png)

### 匹配不上
![image](https://user-images.githubusercontent.com/43488431/92761790-96f50100-f3c4-11ea-8270-b9bb01be28d1.png)

### 结果图
![image](https://user-images.githubusercontent.com/43488431/92761983-c4da4580-f3c4-11ea-874e-1fc019e1bd23.png)

## 希望结果
1. 希望告知是否是我个人使用错误
2. 希望开发人员尝试一下能否复现问题

**Comment by ryoii** [comment]
测试是基于群消息还是好友消息

**Comment by ZGarry** [comment]
> 测试是基于群消息还是好友消息

两个都有测试，您可以在自己电脑上尝试一下能否复现。今晚我再尝试下能否复现

**Comment by ryoii** [comment]
没有复现，请提供较完整代码

**Comment by ZGarry** [comment]
问题已解决。
case，sentby只在第一次确定，后续修改变量无效。

![image](https://user-images.githubusercontent.com/43488431/92932781-f233fb80-f477-11ea-8ce1-99744cd9774a.png)

建议：可以把这点加入FAQ

**Comment by Him188** [comment]
更新文档是解决这个问题的最好的方式

**Comment by ZGarry** [comment]
> 更新文档是解决这个问题的最好的方式

我会收集最近开发中遇到的比较典型的问题，后续一次性提交FAQ
