### ISSUE TITLE
Core-1.2.2开始机器人掉线非常频繁

### ISSUE THREAD

**Issue by KawaiiZapic** [mamoe/mirai#591]
*近期抽空把全家桶都升级了一遍,感觉问题很多*  
在从`1.0.2`升级到`1.2.2`之后,机器人掉线非常频繁,几乎每十几秒就掉线一次.  
出现此问题后尝试降级到`1.0.2`,并没有此问题.  
翻看日志发现`1.0.2`连接的服务器是114开头的某个IP地址,而`1.2.2`连接的是msfwifi的某个域名.  
可能是机器人所处的网络环境问题,但是频繁掉线导致消息接受有很大的延迟,是否有办法自行选择这个服务器或者有什么办法解决呢?

**Comment by mzdluo123** [comment]
#589
