### ISSUE TITLE
打印彩色日志后没有立刻恢复颜色，造成后续输出甚至整个终端都被染色

### ISSUE THREAD

**Issue by kenvix** [mamoe/mirai#593]
打印彩色日志后没有立刻恢复颜色，造成后续输出甚至整个终端都被染色

![image](https://user-images.githubusercontent.com/4546175/92985426-ea5e7080-f4e4-11ea-968e-68c7ba92eae3.png)

#### 复现

当输出彩色日志时打印一条消息，或者停止程序运行

#### 版本
mirai: 1.2.2

**Comment by KawaiiZapic** [comment]
这是console的bug,并不是core的

**Comment by Karlatemp** [comment]
For mamoe: `PlatformLogger.jvm.kt#printLog 输出时追加 RESET`

**Comment by kenvix** [comment]
我在我的项目直接使用core，而未用到console



在 Zapic <notifications@github.com>，2020年9月12日 12:11写道：

这是console的bug,并不是core的

**Comment by mzdluo123** [comment]
您可以提交pull request修复这个问题😃
