### ISSUE TITLE
Bot禁言的群成员被其他管理员用正常客户端解禁时无法获得Operator

### ISSUE THREAD

**Issue by KawaiiZapic** [mamoe/mirai#594]
用正常客户端去解禁Bot禁言的群成员时,Bot虽正常收到`MemberUnmute`事件,但无法获得Operator.  
用正常客户端禁言并解禁并不会发生这种情况,尚未测试由一个Bot禁言并由另一个Bot解禁的情况.  
使用`Core-1.2.3`+`Console-pure-1.0-M4-dev-3`+`HTTP API-1.8.1`,觉得不大可能是HTTP API的问题.  
  
控制台无报错.  

#### 复现

1. 通过HTTP API禁言某个群成员.  
2. 使用正常客户端去解禁该成员(无论解禁操作人是群主还是群管理员).  
3. Bot收到Unmute事件(Mirai-Console有日志输出),并通过HTTP API传给后端,后端收到的数据里`Operator`为`Null`.  

#### 版本
mirai: ` 1.2.3`

**Comment by sandtechnology** [comment]
这应该属于HTTP API的问题（

**Comment by Karlatemp** [comment]
请提供日志

**Comment by KawaiiZapic** [comment]
> 如果日志显示的event正常，应该属于HTTP API的问题（

不大可能.  
因为:  
> 用正常客户端禁言并解禁并不会发生这种情况
用正常客户端禁言并解禁后端是可以获取到Operator的,即使禁言和解禁的操作人并不是一个人.

**Comment by Him188** [comment]
当时研究禁言包就没有发现操作人

**Comment by ryoii** [comment]
没有的话证明它真的没有

**Comment by KawaiiZapic** [comment]
刚刚再次测试时发现问题消失,不知道是什么原因.  
可能有些玄学的成分在里面,就先暂时关闭吧.
