### ISSUE TITLE
请求新增查看群员最后发言，群员加群时间，群员等级判定功能

### ISSUE THREAD

**Issue by ColettaCoye** [mamoe/mirai#595]
想实现群人数满人自动清理最不活跃N个群员的功能，以及判断群员等级及申请词放人进来的功能。
  
  已查阅过issue列表，看到数月前有人提出这个issue，但是好像没有找到更新，想请问一下作者大大有这个开发计划吗？

  如有打扰多多见谅，顺带感谢作者的无偿付出。

**Comment by Him188** [comment]
群员等级: #501
加群时间未计划
群员最后发言: #394
