### ISSUE TITLE
咨询下是否违规

### ISSUE THREAD

**Issue by xiaoxu97** [mamoe/mirai#604]
你好，我是一名java开发者，由于一些生活娱乐方面的需求，接触到了mirai，但由于本人对kotlin的不精通，促使着开发了一款mirai-plus的java版简单扩展并开源，地址在https://github.com/xiaoxu97/mirai-plus
想问下是否有侵权方面的问题，如果有请及时联系我进行删除，另外想帮助mirai进行java方面的扩展以及对spring的支持，不知是否感兴趣。

**Comment by Him188** [comment]
你好, 使用 AGPL 开源并标注 mirai 项目地址即可

**Comment by xiaoxu97** [comment]
好的，已添加

**Comment by mzdluo123** [comment]
欢迎将项目地址添加到awesome-mirai
https://github.com/project-mirai/awesome-mirai

**Comment by xiaoxu97** [comment]
已提交 :>
