### ISSUE TITLE
引用回复还是有空格

### ISSUE THREAD

**Issue by ls148478** [mamoe/mirai#608]
![-5e9be29b67629e45](https://user-images.githubusercontent.com/38435967/93298157-4d257400-f825-11ea-8238-5d4b2be13ebd.png)
![34c09fc246082ed0](https://user-images.githubusercontent.com/38435967/93298160-4eef3780-f825-11ea-8225-f47586ae4e28.png)
`reply(message.quote() + "设置成功")`
Core `1.3.0`

**Comment by Him188** [comment]
检查依赖

**Comment by ls148478** [comment]
> 检查依赖

还是有此问题

**Comment by Him188** [comment]
请提供相关日志

**Comment by ls148478** [comment]
> 请提供相关日志

是我的问题 `mirai-core-qqandroid` 并没有更新
