### ISSUE TITLE
如何用 Java 调用 lowLevel API 方法

### ISSUE THREAD

**Issue by weekdragon** [mamoe/mirai#609]
想尝试新的 _lowLevelGetGroupHonorListData 方法，但是第三个参数 continuation 不知道传什么
![image](https://user-images.githubusercontent.com/9250229/93310037-d7c29f00-f836-11ea-8501-a4f4de09d819.png)

**Comment by mzdluo123** [comment]
这是kotlin协程自动生成的参数，目前还未支持JAVA调用，请使用kotlin调用这个方法

**Comment by Him188** [comment]
在 2.0.0 会全面支持 Java 调用, 但这不会包含在 1.x 中

**Comment by LittleTurtle2333** [comment]
> 在 2.0.0 会全面支持 Java 调用, 但这不会包含在 1.x 中

现在支持了吗？

**Comment by Karlatemp** [comment]
> > 在 2.0.0 会全面支持 Java 调用, 但这不会包含在 1.x 中
> 
> 现在支持了吗？

```java
IMirai.getInstance().*****
```
