### ISSUE TITLE
NewFriendRequestEvent 和 BotInvitedJoinGroupRequestEvent 没有被调用，单向好友无法收消息

### ISSUE THREAD

**Issue by zhaodice** [mamoe/mirai#610]
核心代码：
bot.subscribeAlways<NewFriendRequestEvent> {
                AwLog.Log("收到好友请求，正在自动同意...")
                accept()//自动同意好友
}
bot.subscribeAlways<BotInvitedJoinGroupRequestEvent> {
                AwLog.Log("收到群邀请请求，正在自动同意...")
                accept()//邀请自动同意进群
}
结果：
加好友/邀请入群，事件不执行
邀请bot进群，电脑版未收到入群邀请（但开mirai之前可以收，把mirai关闭一段时间后也能收，怀疑是被屏蔽了），BotInvitedJoinGroupRequestEvent没有执行
删除bot好友后重新添加，NewFriendRequestEvent没有执行，并打印了log
 23:47:03 [INFO] [NETWORK] Recv: net.mamoe.mirai.qqandroid.network.protocol.data.jce.RequestPushNotify@90fbc
 23:47:03 [INFO] [NETWORK] Send: MessageSvc.PbGetMsg
 23:47:03 [INFO] [NETWORK] Send: OnlinePush.RespPush
 23:47:03 [INFO] [NETWORK] Send: MessageSvc.PbDeleteMsg
 23:47:03 [INFO] [NETWORK] unknown PbGetMsg type 528, data=08 23 12 04 1A 02 08 01
 23:47:03 [INFO] [NETWORK] unknown PbGetMsg type 528, data=08 23 12 41 12 3F 08 F5 CD E9 D6 0C 10 CA B1 86 E7 01 18 09 20 F9 E6 88 FB 05 2A 0B E6 9D A5 E8 87 AA 51 51 E7 BE A4 3A 00 42 16 08 83 B0 AF D0 02 12 0C E9 9B BE E4 B8 AD E6 B6 88 E9 80 9D 1A 00 4A 00 52 00
 23:47:03 [INFO] [NETWORK] unknown PbGetMsg type 191, data=01 18 8D 5B D8 BF 82 4E 2D AA A7 86 F4 D3 A9 22 10 5B 2D 3D C2 55 0C 34 BB C5 00 06 00 00 00 00 00 4F 00 00 00 00 00 00 00 00 02 03 E8 00 16 08 83 B0 AF D0 02 12 0C E9 9B BE E4 B8 AD E6 B6 88 E9 80 9D 1A 00 03 ED 00 28 08 01 12 15 E7 BE A4 E8 B5 B5 E5 96 B5 E5 86 B3 E4 B8 8D E8 B0 A2 E7 BD AA 18 00 22 09 E8 B5 B5 E5 96 B5 E5 96 B5 28 01

如何复现：
登陆bot后直接使用
bot.subscribeAlways<NewFriendRequestEvent> {
                AwLog.Log("收到好友请求，正在自动同意...")
                accept()//自动同意好友
}
bot.subscribeAlways<BotInvitedJoinGroupRequestEvent> {
                AwLog.Log("收到群邀请请求，正在自动同意...")
                accept()//邀请自动同意进群
}
就可以发现这两个事件根本就不执行，NewFriendRequestEvent是上述的错误信息，无论是插件的形式还是直接运行的形式，都无法正常工作。

单向好友来消息时会产生报错信息从而无法正常接收：
 00:00:37 [INFO] [NETWORK] Recv: net.mamoe.mirai.qqandroid.network.protocol.data.jce.RequestPushNotify@1e608a5
 00:00:37 [INFO] [NETWORK] Send: MessageSvc.PbGetMsg
 00:00:38 [INFO] [NETWORK] Send: MessageSvc.PbDeleteMsg
 00:00:38 [INFO] [BOT *] Event: MessageSvcPbGetMsg.Response(syncFlagFromServer=CONTINUE, messages=<Iterable>))
 00:00:38 [INFO] [NETWORK] Send: MessageSvc.PbGetMsg
 00:00:38 [INFO] [NETWORK] Send: MessageSvc.PbDeleteMsg
 00:00:38 [INFO] [BOT *] Event: MessageSvcPbGetMsg.Response(syncFlagFromServer=CONTINUE, messages=<Iterable>))
 00:00:38 [INFO] [NETWORK] Send: MessageSvc.PbGetMsg
 00:00:38 [INFO] [NETWORK] Send: MessageSvc.PbDeleteMsg
 00:00:38 [INFO] [BOT *] Event: MessageSvcPbGetMsg.Response(syncFlagFromServer=CONTINUE, messages=<Iterable>))
 00:00:38 [INFO] [NETWORK] Send: MessageSvc.PbGetMsg
 00:00:38 [INFO] [NETWORK] Send: MessageSvc.PbDeleteMsg

#### 版本
mirai: 1.3.0

**Comment by Him188** [comment]
你确认使用的是1.3.0吗？

看来是又有一个新的包....

**Comment by zhaodice** [comment]
> 
> 
> 你确认使用的是1.3.0吗？
> 
> 看来是又有一个新的包....
确定，
implementation("net.mamoe:mirai-core-qqandroid:1.3.0")

**Comment by zhaodice** [comment]
> 
> 
> 你确认使用的是1.3.0吗？
> 
> 看来是又有一个新的包....

@Him188 
这个我可以肯定，
 implementation("net.mamoe:mirai-core-qqandroid:1.3.0")

**Comment by sandtechnology** [comment]
请问电脑版QQ是什么版本？

Sent from Outlook Mobile<https://aka.ms/blhgte>

________________________________

**Comment by zhaodice** [comment]
@sandtechnology QQ 9.3.5 我用的是绿化修改版，我觉得不可能影响数据包什么的

**Comment by Pika-Lee** [comment]
同遇到单向好友无法接收消息的问题，希望能解决一下
![QQ截图20200922150338](https://user-images.githubusercontent.com/23114990/93854617-a8091080-fce8-11ea-9dc0-11a7e82f1b2d.png)

Event: MessageSvcPbGetMsg.Response(syncFlagFromServer=CONTINUE, messages=<Iter&^able>）

#447

**Comment by Him188** [comment]
> 同遇到单向好友无法接收消息的问题，希望能解决一下
> 
> Event: MessageSvcPbGetMsg.Response(syncFlagFromServer=CONTINUE, messages=<Iter&^able>）
> 
> #447

确认版本

**Comment by Pika-Lee** [comment]
> > 同遇到单向好友无法接收消息的问题，希望能解决一下
> > Event: MessageSvcPbGetMsg.Response(syncFlagFromServer=CONTINUE, messages=<Iter&^able>）
> > #447
> 
> 确认版本

运行环境

操作系统：[例子：Windows Server 2016]
mirai core 版本：[例子：1.3.0]
mirai console 版本：[例子：1.0-M4]
mirai native 版本：[例子：1.9.2]
Java 运行时版本：[例子：1.8.0 261]

**Comment by sandtechnology** [comment]
请问在最新的 `2.1.0-dev-1` 中，该问题是否能重现？

**Comment by zhaodice** [comment]
> 请问在最新的 `2.1.0-dev-1` 中，该问题是否能重现？

最新的版本(2.4.0)里暂时没有问题了，至少目前无人反馈。
