### ISSUE TITLE
添加 FriendMessageEvent 和 TempMessageEvent 的公共父类 UserMessageEvent

### ISSUE THREAD

**Issue by infooer** [mamoe/mirai#612]
只看到subscribeFriendMessages和subscribeTempMessages，是要这两个分别实现吗，好像没有发现针对单聊（包括好友和临时）的函数

**Comment by sandtechnology** [comment]
可以选择直接订阅MessageEvent？

________________________________

**Comment by Him188** [comment]
由于目前设计限制, 不容易添加中间类型. 这会在 2.0.0 解决

**Comment by infooer** [comment]
sentByFriend() or sentByTemp()，我这样判断一下，在测试的时候发现好友聊天是可以回复的，但是临时会话无法回复，控制台显示
2020-09-17 13:12:13 V/Net : Send: MessageSvc.PbGetMsg
2020-09-17 13:12:13 V/Net : Send: MessageSvc.PbDeleteMsg

**Comment by Him188** [comment]
请使用 1.3.0 @infooer

**Comment by infooer** [comment]
更新到1.3.0还是一样无法回复临时会话的消息，控制台显示一样的内容 @Him188

**Comment by Him188** [comment]
陌生人临时会话不支持. 仅支持通过群聊发起的临时会话

**Comment by infooer** [comment]
后面会有支持吗，感觉陌生人的临时会话需求也是很多的。区别于主动发送垃圾营销信息，网页发起的客服号基本都是需要。

**Comment by Him188** [comment]
可能会支持, 目前我们重心不在支持更多的协议, 而是解决现有问题

**Comment by infooer** [comment]
感谢，辛苦啦！
框架很优秀，文档也很详细，新手入门无压力
