### ISSUE TITLE
Bot戳自己的时候同样会触发监听

### ISSUE THREAD

**Issue by ForteScarlet** [mamoe/mirai#613]
当bot nudge自己的时候也会触发BotNudgedEvent，这样有可能会导致bot一直不停的在戳自己。虽然可以通过加一层判断来解决，但是我认为应该不会有人希望bot自己戳自己还会触发事件。

不知道这是否在预期内，因此提出此疑问。

**Comment by sandtechnology** [comment]
nudge自己是由使用者决定的，这属于正常现象

Sent from Outlook Mobile<https://aka.ms/blhgte>

________________________________

**Comment by mzdluo123** [comment]
这是预期的，请自行判断
