### ISSUE TITLE
重构 MessageSource.id , 支持分片的多个源消息

### ISSUE THREAD

**Issue by sandtechnology** [mamoe/mirai#618]

**Comment by Him188** [comment]
请问具体是哪里发现了 id 变多个了? 比如是引用回复解析时, 发现引用的元素有多个值吗?

**Comment by sandtechnology** [comment]
是的 解析引用的分片信息回复时id出现了多个值，这点从包的数据类型也可以得出。
此外在撤回分片信息时会出现多个撤回信息的数据包的情况（每个数据包分别指向同一个分片信息内的一个id，推测需要撤回分片信息内的全部id才算真正撤回 ），也需要进行处理。

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
