### ISSUE TITLE
japt掉线重新连接后能发送信息，但不能触发好友消息事件，也不能进行heartbeat

### ISSUE THREAD

**Issue by PopSlime** [mamoe/mirai#62]

**Comment by PopSlime** [comment]
更新：
此bug应该是由于bot处于在线状态时再次login()而触发的。

**Comment by Him188** [comment]
login 前没有掉线?

**Comment by PopSlime** [comment]
第二次login后触发了BotOnlineEvent，然后触发了第一次login的BotOfflineEvent.Dropped。这应该是由同一平台不能同时登陆同一账号的机制导致的。

**Comment by PopSlime** [comment]
更新#2：意外的掉线重连后也不能发送心跳包
日志：
Network(/* uin */) 17:10:52 : Send: Heartbeat.Alive
Network(/* uin */) 17:10:52 : Received: Heartbeat.Alive.Response
Network(/* uin */) 17:11:52 : Send: Heartbeat.Alive
Network(/* uin */) 17:11:52 : Received: Heartbeat.Alive.Response
Network(/* uin */) 17:12:52 : Send: Heartbeat.Alive
Network(/* uin */) 17:12:52 : Received: Heartbeat.Alive.Response // 掉线前心跳包正常
Bot(/* uin */) 17:13:16 : Connection dropped or lost by server, retrying login
Network(/* uin */) 17:13:16 : Send: StatSvc.register
Network(/* uin */) 17:13:19 : Cannot do fast relogin. Trying slow relogin
Network(/* uin */) 17:13:19 : Send: wtlogin.login
Network(/* uin */) 17:13:19 : Received: LoginPacketResponse.Success
Network(/* uin */) 17:13:19 : Login successful
Network(/* uin */) 17:13:19 : Send: StatSvc.register
Network(/* uin */) 17:13:19 : Received: Response(StatSvc.register)
Bot(/* uin */) 17:13:19 : Reconnected successfully
Network(/* uin */) 17:13:22 : Received: PushReq(type=1, jcebuf=/* buffer */, seq=6197165547)
Network(/* uin */) 17:13:22 : Send: ConfigPushSvc.PushResp
[96mNetwork(/* uin */) 17:13:22 : Received commandName: ConfigPushSvc.PushDomain
Network(/* uin */) 17:13:22 : Received: PushReq(type=2, jcebuf=/* buffer */, seq=6197165943)
Network(/* uin */) 17:13:22 : Send: ConfigPushSvc.PushResp
Console input: exit // 掉线后持续56分钟没有发送心跳包，才注意到，就关闭了
Bot(/* uin */) 18:07:25 : Connection dropped or lost by server, retrying login
Network(/* uin */) 18:07:25 : Cannot do fast relogin. Trying slow relogin
Network(/* uin */) 18:07:25 : Send: wtlogin.login // 新BUG：dispose后bot仍会尝试重新登录。由于我输入exit结束了主进程而被打断
