### ISSUE TITLE
支持 ForwardMessage 解析

### ISSUE THREAD

**Issue by khjxiaogu** [mamoe/mirai#623]
mirai无法正常接收ForwardMessage，而是会出现ServiceMessage

#### 复现
1. 用其他账号向mirai转发转发信息。  
2. 查看后台出现[mirai:service:35,...]的信息。  
3. 在插件中用instanceof操作，表明对象类型为ServiceMessage。  
#### 版本
mirai: ` 1.3.0`

**Comment by Him188** [comment]
目前不支持 Forward 解析

**Comment by Him188** [comment]
Forward 解析涉及到长消息下载, 是一个大问题

**Comment by khjxiaogu** [comment]
可否提供一个接口，可以通过接口下载消息的真正内容。

**Comment by sandtechnology** [comment]
这等于提供Forward信息解析，请耐心等待功能实现

**Comment by Him188** [comment]
找到这样的接口就是实现长消息下载 #692
