### ISSUE TITLE
java里面使用1.3.0的mirai-core-qqandroid版本出现报错

### ISSUE THREAD

**Issue by hundunzhidian** [mamoe/mirai#625]
我的pom.xml：

```
        <dependency>
            <groupId>net.mamoe</groupId>
            <artifactId>mirai-core-qqandroid</artifactId>
            <version>1.3.0</version>
        </dependency>
```
我的启动代码：
```
BotConfiguration configuration=new BotConfiguration();
    configuration.fileBasedDeviceInfo();
    switch (globalConfig.getLogflag().toLowerCase()){
        case "all":
            log.info("已启动所有日志");
            break;
        case "net":
            log.info("已启动net日志");
            configuration.noBotLog();
            break;
        case "bot":
            log.info("已启动bot日志");
            configuration.noNetworkLog();
            break;
        default :
            log.info("已禁用所有日志信息");
            configuration.noNetworkLog();
            configuration.noBotLog();
    }
    bot=BotFactoryJvm.newBot(Long.parseLong(globalConfig.getQqnumber()),globalConfig.getQqpasswd(),configuration);
  
```
原来在1.0.2版本启动没问题，但是这几天提示要升级，我就把版本升级到了1.3.0的mirai-core-qqandroid，启动的时候报如下异常：
```
java.lang.NoSuchMethodError: kotlin.jvm.internal.MutablePropertyReference1Impl.<init>(Ljava/lang/Class;Ljava/lang/String;Ljava/lang/String;I)V
	at io.ktor.util.collections.ConcurrentMap.<clinit>(ConcurrentMap.kt) ~[ktor-utils-jvm-1.4.0.jar:1.4.0]
	at io.ktor.client.engine.cio.CIOEngine.<init>(CIOEngine.kt:31) ~[ktor-client-cio-jvm-1.4.0.jar:1.4.0]
	at io.ktor.client.engine.cio.CIO.create(CIOCommon.kt:23) ~[ktor-client-cio-jvm-1.4.0.jar:1.4.0]
	at io.ktor.client.HttpClientKt.HttpClient(HttpClient.kt:40) ~[ktor-client-core-jvm-1.4.0.jar:1.4.0]
	at io.ktor.client.HttpClientKt.HttpClient$default(HttpClient.kt:37) ~[ktor-client-core-jvm-1.4.0.jar:1.4.0]
	at net.mamoe.mirai.qqandroid.utils.MiraiPlatformUtils.<clinit>(MiraiPlatformUtils.kt:86) ~[mirai-core-qqandroid-1.3.0.jar:na]
	at net.mamoe.mirai.qqandroid.BotAccount.<init>(BotAccount.kt:26) ~[mirai-core-qqandroid-1.3.0.jar:na]
	at net.mamoe.mirai.qqandroid.QQAndroid.newBot(QQAndroid.kt:31) ~[mirai-core-qqandroid-1.3.0.jar:na]
	at net.mamoe.mirai.BotFactoryJvm.newBot(BotFactory.kt:99) ~[mirai-core-jvm-1.3.0.jar:na]
.....
```
请问如何解决？

**Comment by sandtechnology** [comment]
pom.xml中是否有其他依赖依赖了kt的库？
如果正在使用kt，请将版本升级到1.4.0

**Comment by hundunzhidian** [comment]
> pom.xml中是否有其他依赖依赖了kt的库？
> 如果正在使用kt，请将版本升级到1.4.0

没有，仅仅是个springboot小项目，而且左边依赖列表的kt也的确是1.4.0
![QQ截图20200922153732](https://user-images.githubusercontent.com/14959751/93855170-a7bd4500-fce9-11ea-9966-0cebfd87cd8a.png)

**Comment by sandtechnology** [comment]
尝试手动依赖kt的std库，添加：
```
        <dependency>
            <groupId>org.jetbrains.kotlin</groupId>
            <artifactId>kotlin-stdlib-common</artifactId>
            <version>1.4.0</version>
        </dependency>
```

**Comment by hundunzhidian** [comment]
>         <dependency>
>             <groupId>org.jetbrains.kotlin</groupId>
>             <artifactId>kotlin-stdlib-common</artifactId>
>             <version>1.4.0</version>
>         </dependency>

同样的错误，这个是依赖列表

Maven: ch.qos.logback:logback-classic:1.2.3
Maven: ch.qos.logback:logback-core:1.2.3
Maven: com.fasterxml.jackson.core:jackson-annotations:2.11.2
Maven: com.fasterxml.jackson.core:jackson-core:2.11.2
Maven: com.fasterxml.jackson.core:jackson-databind:2.11.2
Maven: io.ktor:ktor-client-cio-jvm:1.4.0
Maven: io.ktor:ktor-client-core-jvm:1.4.0
Maven: io.ktor:ktor-http-cio-jvm:1.4.0
Maven: io.ktor:ktor-http-jvm:1.4.0
Maven: io.ktor:ktor-io-jvm:1.4.0
Maven: io.ktor:ktor-network-jvm:1.4.0
Maven: io.ktor:ktor-network-tls-jvm:1.4.0
Maven: io.ktor:ktor-utils-jvm:1.4.0
Maven: jakarta.annotation:jakarta.annotation-api:1.3.5
Maven: net.mamoe:kotlin-jvm-blocking-bridge-jvm:1.0.5
Maven: net.mamoe:mirai-core-jvm:1.3.0
Maven: net.mamoe:mirai-core-qqandroid:1.3.0
Maven: org.apache.logging.log4j:log4j-api:2.13.2
Maven: org.apache.logging.log4j:log4j-to-slf4j:2.13.2
Maven: org.bouncycastle:bcprov-jdk15on:1.64
Maven: org.jetbrains.kotlin:kotlin-gradle-plugin-api:1.4.10
Maven: org.jetbrains.kotlin:kotlin-reflect:1.3.72
Maven: org.jetbrains.kotlin:kotlin-serialization:1.4.10
Maven: org.jetbrains.kotlin:kotlin-stdlib:1.3.72
Maven: org.jetbrains.kotlin:kotlin-stdlib-common:1.4.0
Maven: org.jetbrains.kotlin:kotlin-stdlib-jdk7:1.3.72
Maven: org.jetbrains.kotlinx:atomicfu:0.14.1
Maven: org.jetbrains.kotlinx:atomicfu-common:0.14.1
Maven: org.jetbrains.kotlinx:atomicfu-jvm:0.14.4
Maven: org.jetbrains.kotlinx:kotlinx-coroutines-core-jvm:1.3.9
Maven: org.jetbrains.kotlinx:kotlinx-coroutines-io:0.1.16
Maven: org.jetbrains.kotlinx:kotlinx-coroutines-io-jvm:0.1.16
Maven: org.jetbrains.kotlinx:kotlinx-io:0.1.16
Maven: org.jetbrains.kotlinx:kotlinx-io-jvm:0.1.16
Maven: org.jetbrains.kotlinx:kotlinx-serialization-core-jvm:1.0.0-RC
Maven: org.jetbrains.kotlinx:kotlinx-serialization-protobuf-jvm:1.0.0-RC

**Comment by sandtechnology** [comment]
> Maven: org.jetbrains.kotlin:kotlin-stdlib:1.3.72
Maven: org.jetbrains.kotlin:kotlin-stdlib-common:1.4.0
Maven: org.jetbrains.kotlin:kotlin-stdlib-jdk7:1.3.72
Maven: org.jetbrains.kotlin:kotlin-reflect:1.3.72

很奇怪 我这边的依赖明明都是1.4的 是maven出问题了？
试试
```
        <dependency>
            <groupId>net.mamoe</groupId>
            <artifactId>mirai-core-qqandroid</artifactId>
            <version>1.3.0</version>
            <exclusions>
                <exclusion>
                    <groupId>org.jetbrains.kotlin</groupId>
                    <artifactId>kotlin-stdlib</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>org.jetbrains.kotlin</groupId>
                    <artifactId>kotlin-stdlib-common</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <groupId>org.jetbrains.kotlin</groupId>
            <artifactId>kotlin-stdlib</artifactId>
            <version>1.4.10</version>
        </dependency>
```

**Comment by Him188** [comment]
需要显式依赖 kotlin-stdlib
或者更换gradle

**Comment by RootFive** [comment]
这个问题解决了没？
