### ISSUE TITLE
GroupMessageEvent 的 getGroup 并非获取到群号的字符串

### ISSUE THREAD

**Issue by HOKOORY** [mamoe/mirai#626]
问题1：
String group = event.getGroup().toString(); 
group 会是Sting类型的 “Group(123456789)”  
并且event.getGroup() 没有 contentToString 的方法，建议增加该方法直接获取到群号

---------------------------------------------------------------------------------------------------
问题2：
MessageReceipt sendMessage =bot.getGroup(123456L).sendMessage()
通过sendMessage的getSource()方法来获取到这个消息ID如何序列化成数据库可存类型？如何反序列成MessageSource对象？

感谢大佬们的解答

**Comment by Karlatemp** [comment]
1. `long id = event.getGroup().getId();`

2. #219
