### ISSUE TITLE
群成员列表在同一成员再次退群/进群不会更新

### ISSUE THREAD

**Issue by sam01101** [mamoe/mirai#629]
#### 事先声明: 
 1. 本人并不了解Java和Kt[初学者], 对于精确的问题并不能找到, 而且有可能会有错误
 2. 我已阅读mirai-core源码并确认问题所在, 尽管可能并不准确
 3. 我已查看现有issuse并找不到重复的issuse

#### 问题: 在群成员退出后(任意群, 但Bot必须在同一群), 机器人并不会在List移除该成员
并可能导致该成员再次加入群时(任意群, 但Bot必须在同一群), 不会发送MemberJoinEvent
反而只会发送`MessageSvcPbGetMsg.Response(syncFlagFromServer=CONTINUE, messages=<Iterable>)`两次

已确定的~~临时~~解决方案: 在群成员退出后重启Bot, 让实例再次生成, 此时群列表会更新(肯定的, 不然怎么获取群成员)

#### 代码: 
我看了下源码, 发现在MemberLeft时并没有移除该成员.
相反, 如果同一个成员再次加入, MemberJoinEvent不会触发(该成员已在退群前加入)

###### 前提 1:
1. 创建一个群(现有的也可以)
2. 确保测试对象在机器人的同一个群(测试目标可以在有机器人的任意一个群)
###### 前提 2:
1. 创建一个群(现有的也可以)
2. 确保机器人事先进群, 然后邀请测试对象进群 (此时Bot触发MemberJoinEvent并添加测试对象到member)
##### 开始复现:
3. 测试对象退群, Bot显示MemberLeftEvent (此时机器人的member里还在)
4. 测试对象加入有机器人的一个群(可以是任意, 但机器人必须在)
- 结果: Bot重复两次`CONTINUE`回复

*注意: `CONTINUE` 有可能是刚好回复, 但MemberJoinEvent一定没有触发*

个人感觉, 是没有处理这段的代码.
#### 版本
mirai:
`mirai-console-1.0-M4.jar`
`mirai-console-pure-1.0-M4.jar`
`mirai-core-qqandroid-1.3.0.jar`
 

P.S. 不熟悉Kt, 不会加这段, 不然早PR了. 哎...

**Comment by sam01101** [comment]
我是傻逼, 没看issuse

**Comment by sandtechnology** [comment]
请问能否给出在何处没有remove的代码片段吗？

**Comment by sam01101** [comment]
好问题, 我之前大概摸索了下, 不能确定是不是真的地方
这是MemberLeaveEvent
https://github.com/mamoe/mirai/blob/a774b8a7062fbd26742b7eb73896294fa6ab01b0/mirai-core/src/commonMain/kotlin/net.mamoe.mirai/event/events/group.kt#L293

**Comment by sandtechnology** [comment]
刚刚进行了检查，在每处fire MemberLeaveEvent时都进行了成员的移除操作
请问是如何察觉到群成员没有更新的情况呢？
能否提供复现的环境？（使用什么客户端进行管理操作和客户端版本）

**Comment by sam01101** [comment]
> 刚刚进行了检查，在每处fire MemberLeaveEvent时都进行了成员的移除操作
> 请问是如何察觉到群成员没有更新的情况呢？
> 能否提供复现的环境？（使用什么客户端进行管理操作和客户端版本）

是在测试对象重新加入机器人以有的群的时候发现没触发MemberJoinEvent

**Comment by sandtechnology** [comment]
请问是怎么加入的？
以什么客户端加入？
群的验证设置是？

**Comment by sam01101** [comment]
1. 手动/邀请 (目前测试了这两个)
2. QQ客户端(全部)
3. 需要验证

**Comment by sandtechnology** [comment]
> 
> 
>     1. 手动/邀请 (目前测试了这两个)
> 
>     2. QQ客户端(全部)
> 
>     3. 需要验证

全部QQ客户端和需要验证是指？请给出详细的信息（QQ客户端类型、版本、邀请入群/主动入群、群的设置是需要验证消息还是需要正确回答验证问题）

**Comment by sam01101** [comment]
我是从自己手机QQ登录Bot账号然后加入的, 然后就是切换到测试对象账号加入群
如果硬要说一个群验证设置的话...
![image](https://user-images.githubusercontent.com/25792361/94244454-7ba0fe80-ff4b-11ea-9b72-ebc7f2e76ea5.png)
Bot的客户端是linux, a平板协议

**Comment by sam01101** [comment]
已确认问题：平板QQ协议有时候并不会显示群成员进入
解决方法：切换到手机协议

如何切换，暂时未知。需要有人指导一下，谢谢。

**Comment by sam01101** [comment]
附送图片：进群信息对比
![-70bffdf2cb490356](https://user-images.githubusercontent.com/25792361/94389589-cf495d00-0182-11eb-9bda-d24980b5fed4.png)
![Screenshot_20200928-115937](https://user-images.githubusercontent.com/25792361/94389597-d53f3e00-0182-11eb-87f9-00bc66449fb1.png)

**Comment by Him188** [comment]
> 已确认问题：平板QQ协议有时候并不会显示群成员进入
> 解决方法：切换到手机协议
> 
> 如何切换，暂时未知。需要有人指导一下，谢谢。

感谢你的调查, 可以在构造 Bot 时切换协议:

```kotlin
val bot = Bot(...) {
    protocol = MiraiProtocol.ANDROID_PHONE
}
```

**Comment by Hieuzest** [comment]
不认为存在此问题，需要更多信息。从前面的讨论可以看到进群时确有进行消息同步。
另外 @Him188 
经测试，PbGetMsg::msgType == 34 为退群，补全此项应当可以缓解此问题

**Comment by Him188** [comment]
> 不认为存在此问题，需要更多信息。从前面的讨论可以看到进群时确有进行消息同步。
> 另外 @Him188
> 经测试，PbGetMsg::msgType == 34 为退群，补全此项应当可以缓解此问题

请开启有关的 issue 或者提交 PR.
任务都需要经过安排才能进行

**Comment by sam01101** [comment]
> 不认为存在此问题，需要更多信息。从前面的讨论可以看到进群时确有进行消息同步。
> 另外 @Him188
> 经测试，PbGetMsg::msgType == 34 为退群，补全此项应当可以缓解此问题

这个只是猜测。

有没有一个可能，平板协议其实收到的进群通知是另外一个包？
*依照前面进群后会自动发

**Comment by Him188** [comment]
> > 不认为存在此问题，需要更多信息。从前面的讨论可以看到进群时确有进行消息同步。
> > 另外 @Him188
> > 经测试，PbGetMsg::msgType == 34 为退群，补全此项应当可以缓解此问题
> 
> 这个只是猜测。
> 
> 有没有一个可能，平板协议其实收到的进群通知是另外一个包？
> _依照前面进群后会自动发两个`CONTIUE`包来猜测_

`CONTIUE` 似乎并不一定代表有新的包, 同步单个好友消息时服务器也有可能发 `CONTINUE`

**Comment by sam01101** [comment]
> > > 不认为存在此问题，需要更多信息。从前面的讨论可以看到进群时确有进行消息同步。
> > > 另外 @Him188
> > > 经测试，PbGetMsg::msgType == 34 为退群，补全此项应当可以缓解此问题
> > 
> > 
> > 这个只是猜测。
> > 有没有一个可能，平板协议其实收到的进群通知是另外一个包？
> > _依照前面进群后会自动发两个`CONTIUE`包来猜测_
> 
> `CONTIUE` 似乎并不一定代表有新的包, 同步单个好友消息时服务器也有可能发 `CONTINUE`

但可以确定的是当有人进群会发两个`CONTIUE`包, 而是还不触发Event
这个我试过几次了, 确实每次都会
