### ISSUE TITLE
默认使用 ANDROID_PHONE 协议

### ISSUE THREAD

**Issue by Him188** [mamoe/mirai#632]
因为平板协议不支持某些功能, 如戳一戳, 并且有新群员可能不通知的问题([#629](https://github.com/mamoe/mirai/issues/629#issuecomment-699757310))

**Comment by takayama-lily** [comment]
初次登陆用手机协议经常会遇到"禁止登陆，请使用QQ一键登录"的问题

**Comment by sam01101** [comment]
> 初次登陆用手机协议经常会遇到"禁止登陆，请使用QQ一键登录"的问题

临时解决方案: 先切换到其它协议登录, 然后切换回手机协议

**Comment by takayama-lily** [comment]
这个问题应该是手机协议已经不支持图片验证码导致的。记得几个月之前还是支持的。
mirai目前好像还不支持滑动验证码。

**Comment by sam01101** [comment]
> 这个问题应该是手机协议已经不支持图片验证码导致的。记得几个月之前还是支持的。
> mirai目前好像还不支持滑动验证码。

没错, 这个我觉得可以提issuse

**Comment by sam01101** [comment]
在#641 中，已确定此问题并不指出现在平板协议中
有几率是代码问题
