### ISSUE TITLE
我的QQ聊天记录图片文件夹里有一大堆扩展名为.mirai的文件

### ISSUE THREAD

**Issue by Cyl18** [mamoe/mirai#635]
![image](https://user-images.githubusercontent.com/14993992/94449640-e453d980-01de-11eb-8541-ba3cbcfe841c.png)
![image](https://user-images.githubusercontent.com/14993992/94449672-eddd4180-01de-11eb-8931-af11da222122.png)
想咨询一下原因, 并且这个feature会造成QQ下载多个相同的文件, 不知道可不可以有一些workaround

**Comment by Him188** [comment]
`.null`, `.mirai`, `.jpg`
目前是在 `ExternalImage` 根据文件头推断文件类型. 可能这种方法有某种兼容性问题
