### ISSUE TITLE
如何判断事件是否已注册

### ISSUE THREAD

**Issue by Moredistant** [mamoe/mirai#636]
是这样，我每登录一个QQ就会执行this.subscribeGroupMessages来监听消息
但是我发现登录第二个QQ的时候会重复注册，查看了源码才发现这个方法是监听所有BOT的群消息
查询了相关源码和文档也没发现有哪可以检测是否已注册此消息，请问如何解决？

**Comment by Karlatemp** [comment]
#514 `CoroutineScope.subscribeAlways` 是全局的
