### ISSUE TITLE
支持好友间和群间的文件收发

### ISSUE THREAD

**Issue by Lucky-fish** [mamoe/mirai#639]
你好
我在写插件的时候需要实现收发文件，但没有找到相关的api
在接受文件的时候出现了```Recv: net.mamoe.mirai.qqandroid.network.protocol.data.jce.RequestPushNotify@71163ff3```之类的东西，但似乎没有触发任何事件
这对于我的项目来说还是很关键的功能，因此来提个请求._. 但受众面毕竟不广，估计也不大可能会被接受
另感谢阅读这条issue

**Comment by Him188** [comment]
群文件下载是个不容易做出来的新功能，在现阶段不会支持

**Comment by Lucky-fish** [comment]
> 群文件下载是个不容易做出来的新功能，在现阶段不会支持

了解了，感谢回复。那我就再想另外一套方案吧._.
