### ISSUE TITLE
登陆异常问题

### ISSUE THREAD

**Issue by godblessme111** [mamoe/mirai#642]
我购买了个qq号已经在安卓手机和pc上登陆成功 手机上显示了个滑动验证码然后让我选了辅助申诉资料就给登陆了 但是mirai-console登陆点时候只会弹出文字验证码 输入正确后显示
Login failed: Error(title=禁止登录, message=当前上网环境异常，请更换网络环境或在常用设备上登录或稍后再试。, errorInfo=)
请问有办法支持吗或者有什么解决方案

**Comment by ryoii** [comment]
正常使用一段时间后再尝试使用 mirai 登录，关闭设备锁和其他验证信息。

尝试使用正常的QQ号进行测试，购买的QQ后容易产生各种风控问题
