### ISSUE TITLE
无法登录

### ISSUE THREAD

**Issue by CraftDream** [mamoe/mirai#643]
登录时报错
`Exception in thread "main" net.mamoe.mirai.network.WrongPasswordException: Error(title=温馨提示, message=当前版本过低， 请先升级到手机QQ最新版本。, errorInfo= )`
是什么原因，无法登录，之前都可以登录，就这两天突然不行了

**Comment by Him188** [comment]
关闭设备锁。
平板和手机协议各尝试几遍，就可以登录了。

**Comment by CraftDream** [comment]
> 关闭设备锁。
> 平板和手机协议各尝试几遍，就可以登录了。

怎么切换协议

**Comment by Karlatemp** [comment]
> > 关闭设备锁。
> > 平板和手机协议各尝试几遍，就可以登录了。
> 
> 怎么切换协议

Core: https://github.com/mamoe/mirai/issues/629#issuecomment-699766036

Console: mamoe/mirai-console#198
