### ISSUE TITLE
机器人接收其他手机终端的消息

### ISSUE THREAD

**Issue by zygzx** [mamoe/mirai#644]
手机终端，其他终端已机器人的账号发送消息的时候，mirai没有推送。

**Comment by Pai2Chen** [comment]
使用官方客户端也会有这个问题吧
pc和手q不同步

**Comment by zygzx** [comment]
有哦，只是慢一点而已，移动端都有的

**Comment by ryoii** [comment]
这个数据已经有解析了，但是涉及发送对象如何构建的问题，我认为和现有的框架不是特别兼容。目前 mirai 通过 qq id 区分不同的对象，但是其他客户端显然 id 是相同的，这意味着需要增加一个字段标识消息来源。这需要修改其他对象的实现或者在现有框架内再抽象出一个 OtherClient ？？

显然目前框架下哪种方法都是很好，鉴于这个功能的用途不是特别广（Bot一般使用专门的Bot QQ登录，而不是日常使用的账号），所以没有考虑支持。

如果你有特别好的想法，可以在 #630 里提出合理的建议，如果兼容情况良好，可以考虑在 mirai 2.0 中加入

**Comment by zygzx** [comment]
这个业务的应用其实就在于监控企业员工使用QQ的情况，以及各种群里的信息收集，做大数据的分析，这种情况下QQ机器人是业务安全的，不存在业务风险。但如果手机部分信息收集不到，这个应用就不能使用了。

**Comment by ProjectDimlight** [comment]
其实的话还有一些应用场景，比如一个机器学习任务，希望学习使用者自身的回答习惯；然后因为专用的QQbot账号没法把使用者加的所有群再加一遍（很多群禁止小号或bot号），所以就只好直接挂在大号上监听……然后就发现监听不了自己的发言了……


我有一点想法，既然mirai是能够收到这些消息的（而不是因为QQ协议的问题压根收不到），要不先不区分不同的设备，就只要发言了一律触发相同的事件（*MessageEvent），然后让二次开发者自行判断来源？

**Comment by ryoii** [comment]
> 其实的话还有一些应用场景，比如一个机器学习任务，希望学习使用者自身的回答习惯；然后因为专用的QQbot账号没法把使用者加的所有群再加一遍（很多群禁止小号或bot号），所以就只好直接挂在大号上监听……然后就发现监听不了自己的发言了……
> 
> 我有一点想法，既然mirai是能够收到这些消息的（而不是因为QQ协议的问题压根收不到），要不先不区分不同的设备，就只要发言了一律触发相同的事件（*MessageEvent），然后让二次开发者自行判断来源？

那你让现有的代码怎么办

**Comment by ProjectDimlight** [comment]
> > 其实的话还有一些应用场景，比如一个机器学习任务，希望学习使用者自身的回答习惯；然后因为专用的QQbot账号没法把使用者加的所有群再加一遍（很多群禁止小号或bot号），所以就只好直接挂在大号上监听……然后就发现监听不了自己的发言了……
> > 我有一点想法，既然mirai是能够收到这些消息的（而不是因为QQ协议的问题压根收不到），要不先不区分不同的设备，就只要发言了一律触发相同的事件（*MessageEvent），然后让二次开发者自行判断来源？
> 
> 那你让现有的代码怎么办

我寻思不影响啊，对于mirai代码来说只是增加了一个新的接口；对于用户代码来说，没有用到这个功能的代码不需要进行任何改动（实际上以前根本没有这个功能）？

**Comment by QingWenYe** [comment]
同意希望有这个特性。

**Comment by Him188** [comment]
我觉得添加一个 `interface OtherDevice : User`

**Comment by Him188** [comment]
`StatSvc.SvcReqMSFLoginNotify`: 其他客户端上线/离线

**Comment by Him188** [comment]
https://github.com/mamoe/mirai/commit/f613b7f7b741fe6812a948c77028bfb761a749bf 支持接收

**Comment by Him188** [comment]
```kotlin

/**
 * 机器人在其他客户端发送消息同步到这个客户端的事件.
 *
 * 本事件发生于**机器人账号**在另一个客户端向一个群或一个好友主动发送消息, 这条消息同步到机器人这个客户端上.
 *
 * @see MessageEvent
 */
public interface MessageSyncEvent : MessageEvent


/**
 * 机器人在其他客户端发送群消息同步到这个客户端的事件
 *
 * @see MessageSyncEvent
 */
public class GroupMessageSyncEvent(
    override val group: Group,
    override val message: MessageChain,
    override val sender: Member,
    override val senderName: String,
    override val time: Int
) : AbstractMessageEvent(), GroupAwareMessageEvent, MessageSyncEvent {
    init {
        val source = message[MessageSource] ?: error("Cannot find MessageSource from message")
        check(source is OnlineMessageSource.Incoming.FromGroup) { "source provided to a GroupMessage must be an instance of OnlineMessageSource.Incoming.FromGroup" }
    }

    override val bot: Bot get() = group.bot
    override val subject: Group get() = group
    override val source: OnlineMessageSource.Incoming.FromGroup get() = message.source as OnlineMessageSource.Incoming.FromGroup

    public override fun toString(): String =
        "GroupMessageSyncEvent(group=${group.id}, senderName=$senderName, sender=${sender.id}, message=$message)"
}

```

**Comment by sulinwork** [comment]
目前是只支持同步群消息的事件吗？因为我只看到GroupMessageSyncEvent这一个实现  那么私聊的消息同步是否可以后续支持？

**Comment by Him188** [comment]
> 目前是只支持同步群消息的事件吗？因为我只看到GroupMessageSyncEvent这一个实现 那么私聊的消息同步是否可以后续支持？

https://github.com/mamoe/mirai/pull/841

**Comment by ChanFeei** [comment]
这个功能最后一个可以工作的版本是2.7.1。从2.8.0之后不好使了，mirai收到PbC2CMsgSync的数据包，但是事件没有抛出来。
