### ISSUE TITLE
bot无法接收群聊消息“0”

### ISSUE THREAD

**Issue by Pika-Lee** [mamoe/mirai#646]
如题，群聊发送“0”，bot日志记录不到相应事件，发送“1”-“9”都没问题，只有“0”不行。

私聊发送“0”则可以正常接收。

#### 复现

在群里发送数字0，该消息没有出现在console的日志中

#### 版本

1.3.0

**Comment by ryoii** [comment]
恭喜你似乎发现了一个腾讯的bug，用安户端发送”0“到群消息，就是收不到消息。你可以使用两个客户端进行测试

**Comment by Pika-Lee** [comment]
> 恭喜你似乎发现了一个腾讯的bug，用客户端发送”0“到群消息，就是收不到消息。你可以使用两个客户端进行测试

试了一下，确实如此，不光bot收不到，其它群友也都看不到。

**Comment by Him188** [comment]
服务器已经修复问题
