### ISSUE TITLE
bot无法接收并处理陌生人/单向好友发来的消息

### ISSUE THREAD

**Issue by Pika-Lee** [mamoe/mirai#647]
需求理由：不是所有用户都会添加bot为好友的（同理，bot因为好友上限等原因也不会添加每个人），此时必然会产生陌生人/单向好友会话消息。而mirai目前无法处理此类私聊消息，日志中会直接下图所示的错误提示。

![22](https://user-images.githubusercontent.com/23114990/95853093-6c151880-0d87-11eb-8aff-372b53d19970.png)

该问题将会导致插件的私聊功能受限，希望后续版本能支持处理陌生人/单向好友发来的消息，谢谢~

**Comment by Him188** [comment]
#447
