### ISSUE TITLE
SystemDeviceInfo 序列化时保存默认值

### ISSUE THREAD

**Issue by Itsusinn** [mamoe/mirai#648]
kotlinx.serialization.MissingFieldException: Field 'version' is required, but it was missing
第一次登陆成功并生成了设备信息device.json
之后登陆都会产生MissingFieldException
查看device.json后发现
net.mamoe.mirai.utils.DeviceInfo version字段没有被正常序列化

#### 版本
mirai: `1.3.2 `

**Comment by Him188** [comment]
请不要覆盖 mirai 使用的 `kotlinx.serialization` 的版本

**Comment by Itsusinn** [comment]
即使是相同的版本？

**Comment by Him188** [comment]
mirai 使用的是 `1.0.0-RC`. `kotlinx.serialization` 在 `1.0.0-RC2` 有不兼容的改变. 请确保使用 `1.0.0-RC`

**Comment by Itsusinn** [comment]
已解决，是gradle的依赖传递导致的问题

**Comment by Karlatemp** [comment]
```kotlin

fun main() {
    val json = Json {
        prettyPrint = true
    }
    val test = SystemDeviceInfo(ContextImpl())
    val str = json.encodeToString(SystemDeviceInfo.serializer(), test)
    println(str)
}
```
经过试验，输出结果中 version 为 `"version": {}`,
推测是 `SystemDeviceInfo.Version` 为 `object` 所导致,
而此潜在错误潜伏如此之久一直无人发现的原因是反序列化时使用的为 `DeviceInfoData`

`DeviceInfoData.VersionData` 的构造器存在默认值

https://github.com/mamoe/mirai/blob/e6c90f0edfd08eef67ceec3e2e92071a0d961e5e/mirai-core/src/commonMain/kotlin/net.mamoe.mirai/utils/DeviceInfo.kt#L123-L129

此潜在错误应该得到修正

`kotlinx.serialization 1.0-RC2` 出现了 `MissingFieldException` 的原因可能就是 kxs 忽略了 object 导致

**Comment by Him188** [comment]
> ```kotlin
> fun main() {
>     val json = Json {
>         prettyPrint = true
>     }
>     val test = SystemDeviceInfo(ContextImpl())
>     val str = json.encodeToString(SystemDeviceInfo.serializer(), test)
>     println(str)
> }
> ```
> 
> 经过试验，输出结果中 version 为 `"version": {}`,
> 推测是 `SystemDeviceInfo.Version` 为 `object` 所导致,
> 而此潜在错误潜伏如此之久一直无人发现的原因是反序列化时使用的为 `DeviceInfoData`
> 
> `DeviceInfoData.VersionData` 的构造器存在默认值
> 
> https://github.com/mamoe/mirai/blob/e6c90f0edfd08eef67ceec3e2e92071a0d961e5e/mirai-core/src/commonMain/kotlin/net.mamoe.mirai/utils/DeviceInfo.kt#L123-L129
> 
> 此潜在错误应该得到修正
> 
> `kotlinx.serialization 1.0-RC2` 出现了 `MissingFieldException` 的原因可能就是 kxs 忽略了 object 导致

并不是, 原因是它默认不序列化默认值了. 只需要通过一个属性修改

**Comment by AdoptOSS** [comment]
> 并设置序列化默认值.

考虑到在大多数情况下，版本信息应该随着Mirai的升级自动改变（甚至禁止自定义以防协议版本不兼容？），建议仍然按原方式处理

**Comment by Him188** [comment]
> > 并设置序列化默认值.
> 
> 考虑到在大多数情况下，版本信息应该随着Mirai的升级自动改变（甚至禁止自定义以防协议版本不兼容？），建议仍然按原方式处理

这与 mirai 这个库无关, 是使用者自己覆盖了依赖
