### ISSUE TITLE
根据guide指南中的代码，无法判别bot在群中被at，不知是否是代码理解上的问题

### ISSUE THREAD

**Issue by Qianzh-Roy** [mamoe/mirai#649]
miraiBot.subscribeGroupMessages {
        "你好" reply "爬！"
        case("at me") {
            reply(At(sender as Member) + " 给爷爬 ")
        }
    }

**Comment by Him188** [comment]
若不熟悉 Kotlin 高阶函数等相关特性, 请不要使用 DSL. 使用 `subscribeAlways<GroupMessageEvent>` 或使用 `SimpleListenerHost` 替代.
