### ISSUE TITLE
对于小程序的解析

### ISSUE THREAD

**Issue by Grand-cocoa** [mamoe/mirai#653]
希望可以增加对于QQ小程序数据的解析，以便于拯救打不开小程序的PC用户，就像酷Q机器人插件[
receiver-meow](https://github.com/chenxuuu/receiver-meow-lua/blob/master/require/apps/13av.lua#L26)一样

**Comment by sandtechnology** [comment]
mirai早已支持小程序数据的接收，请自行完成解析
