### ISSUE TITLE
关于授权协议：使用HTTP API与Mirai交互的插件是否需要开源？

### ISSUE THREAD

**Issue by user670** [mamoe/mirai#657]
如题。
这个问题我也问过别的人，得到的回复是“不清楚”。
协议原文这个东西我有点读不下去……

Edit: 我所问的“是否需要开源”，指的是根据AGPL协议，是否法律上强制要求开源。贵项目readme里的“建议开源”不在此列。

Edit 2: 涉及的插件会免费/非商业地对第三方提供服务。

**Comment by Him188** [comment]
如果不修改 mirai，就可以不开源。但为了社区的良好发展，我们强烈建议您开源。
