### ISSUE TITLE
手Q 8.2.6 接收到的 mirai 消息第一个字被吞掉

### ISSUE THREAD

**Issue by JoinChang** [mamoe/mirai#658]
吞字例子（见最上面的一条消息）
![416ac51f6d0c91b1](https://user-images.githubusercontent.com/35451392/97101433-56351b00-16d8-11eb-8b29-e9179b830669.jpg)

新版本 8.4.10 截图
![Screenshot_20201025-154023_QQ](https://user-images.githubusercontent.com/35451392/97101452-7cf35180-16d8-11eb-9866-e018b5107fe8.jpg)

```



```

#### 复现

使用旧版本手机 QQ（如 8.2.6）接收到的消息少了第一个字。
经测试更新 QQ 版本可解决问题。

#### 版本
mirai: `1.1.3 `

**Comment by Him188** [comment]
升级客户端解决问题

**Comment by Him188** [comment]
mirai 第一个版本就是基于 8.2.0 开发
