### ISSUE TITLE
踢出群成员时出现错误kick failed: 255

### ISSUE THREAD

**Issue by abc55660745** [mamoe/mirai#659]
使用miraiok启动，mirai-core版本1.2.3，mirai-api-http，
编写了一个对照文件自动踢出群成员的脚本，在成功踢出部分成员后出现kick failed: 255，重新启动mirai，重新登陆，踢出其他人均出现该错误
![QQ截图20201026121640.png](https://i.loli.net/2020/10/26/pvOxN2SACfDEMHo.png)

**Comment by Him188** [comment]
很难确认错误原因

**Comment by Him188** [comment]
根据你说的自动踢出，可能是过于频繁？

**Comment by Him188** [comment]
频繁操作可能就是会被屏蔽
