### ISSUE TITLE
群临时会话事件收不到消息

### ISSUE THREAD

**Issue by libsgh** [mamoe/mirai#662]
群临时会话事件收不到消息，`mirai-core-qqandroid`版本`1.3.2`，不知道是姿势不对，还是BUG

```java
@NotNull
@EventHandler()
public ListeningStatus onReceive(@NotNull TempMessageEvent event) {
    System.out.println(event.getSender().getId()+event.getMessage().contentToString()+event.getSource().getId()); return 
    ListeningStatus.LISTENING;
}
```

**Comment by Him188** [comment]
请提供日志

**Comment by libsgh** [comment]
> 请提供日志和版本号
mirai-core-qqandroid版本1.3.2，日志：没有任何日志...
，在群里找到机器人进行私聊，双方都没有好友

**Comment by Pika-Lee** [comment]
老问题了，现在bot无法接收临时会话消息#246 #338 #401 
类似的问题还有单向好友（陌生人）发来的消息#647 #447 #610

**Comment by libsgh** [comment]
> 老问题了，现在mirai无法接收临时会话消息#246 #338 #401
> 类似的问题还有单向好友（陌生人）发来的消息#647 #447 #610

这好吧，这个问题有点严重啊，应该优先解决

**Comment by Him188** [comment]
> > 老问题了，现在mirai无法接收临时会话消息#246 #338 #401
> > 类似的问题还有单向好友（陌生人）发来的消息#647 #447 #610
> 
> 这好吧，这个问题有点严重啊，应该优先解决

- 这个问题尚未确定是你的使用问题还是 mirai 问题 (因为无日志无相关信息提供以确认问题), 优先级无法确认.
- 这个问题对你来说影响很大, 但对于其他使用者和 mirai 开发来说它很轻微, 因此短时间内不会安排解决.

**Comment by libsgh** [comment]
> > > 老问题了，现在mirai无法接收临时会话消息#246 #338 #401
> > > 类似的问题还有单向好友（陌生人）发来的消息#647 #447 #610
> > 
> > 
> > 这好吧，这个问题有点严重啊，应该优先解决
> 
> * 这个问题尚未确定是你的使用问题还是 mirai 问题 (因为无日志无相关信息提供以确认问题), 优先级无法确认.
> * 这个问题对你来说影响很大, 但对于其他使用者和 mirai 开发来说它很轻微, 因此短时间内不会安排解决.

不好意思 前一段时间在忙，没有回复

- 我在github上放了一份测试代码，可以用来测试[mirai_test](https://github.com/libsgh/mirai_test)，日志我附上了全部日志，后面打印了一条私聊消息，是有好友的。没有好友的群临时消息是没有日志的。如果是我使用问题，麻烦告知一下`TempMessageEvent`的真实用途。
[日志.log](https://github.com/mamoe/mirai/files/5580960/default.log)
- 我的使用场景：qq机器人定时推送结果消息给群成员（因为消息具有一定的隐私，没有办法改为群消息），大部分群友加群就不想再加机器人qq了。至于这个可能被用来发小广告等黑产，我确实也收到过这种广告，我都是直接屏蔽了。当然这种也有限制，如果官方因为安全原因禁止了这个功能，表示可以理解。

**Comment by libsgh** [comment]
> > > 老问题了，现在mirai无法接收临时会话消息#246 #338 #401
> > > 类似的问题还有单向好友（陌生人）发来的消息#647 #447 #610
> > 
> > 
> > 这好吧，这个问题有点严重啊，应该优先解决
> 
> * 这个问题尚未确定是你的使用问题还是 mirai 问题 (因为无日志无相关信息提供以确认问题), 优先级无法确认.
> * 这个问题对你来说影响很大, 但对于其他使用者和 mirai 开发来说它很轻微, 因此短时间内不会安排解决.

补充一下，版本我已经更新到了最新的1.3.3

**Comment by Pika-Lee** [comment]
> > > 老问题了，现在mirai无法接收临时会话消息#246 #338 #401
> > > 类似的问题还有单向好友（陌生人）发来的消息#647 #447 #610
> > 
> > 
> > 这好吧，这个问题有点严重啊，应该优先解决
> 
> * 这个问题尚未确定是你的使用问题还是 mirai 问题 (因为无日志无相关信息提供以确认问题), 优先级无法确认.
> * 这个问题对你来说影响很大, 但对于其他使用者和 mirai 开发来说它很轻微, 因此短时间内不会安排解决.

感觉这个问题的涉及面还是不小的，如果一个插件需要发送私聊消息的话，就需要对非bot好友的用户创建临时会话事件，mirai插件的适用场景应该不仅仅局限于群聊吧？希望以后有可能的话，还是能增加对于临时会话/单向好友消息的支持吧~

**Comment by Him188** [comment]
For mamoe: 直接测试 MessageSvc 能否正常接收事件

**Comment by Him188** [comment]
经测试可以正常接收, 可能是最近的一些修改把这个修复了
