### ISSUE TITLE
建议: 更换较为宽松的开源协议, 并提供Issue Template

### ISSUE THREAD

**Issue by Chenwe-i-lin** [mamoe/mirai#67]
目前看, 很多情况下, 都需要将机器人的账号密码硬编码进代码(虽然可以用配置文件), 但QQ机器人比较牵扯到一些账号安全的问题, 建议还是换用类似Apache License 2.0这种开源协议, 毕竟 GPLv3 **强制任何与其相关的代码以相同协议(即 GPLv3) 开源**:

> ...同 GPLv2 一样，GPLv3 是互惠的许可证。这意味着如果应用程序加入了 GPL 所监管的代码，或者，是使用了“基于 GPL 监管代码的产品”，并且因此而产生的应用程序是用于分发的，那么它必须在 GPL 下分发。GPL 本身规定，任何分发副本都必须包括其源代码和 GPL 许可证副本...
>    -- [IBM Developerworks](https://www.ibm.com/developerworks/cn/rational/edge/08/mar08/curran/index.html)

至于提供Issue Template, 我觉得这样能够帮助开发者更快的找到问题(可能现在并不合适...).

**Comment by Him188** [comment]
谢谢你的提议. 密码安全问题一定会被考虑, 但这不会让我们修改协议.

此项目最初只是我为学习 Kotlin 而发起, 随后决定做出一个优秀开源框架. 
我们的初心就是免费和开源, 因此希望在AGPLv3的强要求下尽可能地确保这个项目不会被恶意使用或成为不正当的收入来源.


在有必要时我们会添加 Issue Template.

**Comment by Chenwe-i-lin** [comment]
感谢你的回复.
