### ISSUE TITLE
OpenJDK Plaform binary已停止工作

### ISSUE THREAD

**Issue by Pika-Lee** [mamoe/mirai#670]
OpenJDK Platform binary已停止工作
出现了-一个问题,导致程序停止正常工作。如果有可用的解决
方案, Windows将关闭程序并通知你。

![ERROR123](https://user-images.githubusercontent.com/23114990/97954831-8c148680-1ddf-11eb-8425-14375eb9df71.png)

**Comment by Karlatemp** [comment]
请自行检查jre是否正常(更换java runtime(jre))，并自行检查是否mirai native问题(卸载mirai native或删除部分新加的dll)

**Comment by Him188** [comment]
不属于 mirai-core 问题, 请参考 @Karlatemp 的建议
