### ISSUE TITLE
mirai登录异常

### ISSUE THREAD

**Issue by TerraLian** [mamoe/mirai#672]
- 问题描述：在测试mirai时，卡在了登录上。更换版本，账号，及代码环境都不能解决。

- 异常提示：
   - 使用MiraiProtocol.ANDROID_PHONE 的情况
 报错
`Recv: Error(title=禁止登录, message=为了您的帐号安全，请使用QQ一键登录（通过手机QQ授权登录）。, errorInfo=)`

   - 使用MiraiProtocol.ANDROID_PAD 及 MiraiProtocol.ANDROID_WATCH 的情况
 输入验证码后报错：
`Recv: Error(title=禁止登录, message=当前上网环境异常，请更换网络环境或在常用设备上登录或稍后再试。, errorInfo=)`

- 测试过的版本：`1.3.3`，`1.3.2`， `1.2.2`

- 更换网络环境，使用有线，无线或者热点，均无变化。

- 更换执行环境，将代码部署至服务器 亦出现上述异常

- 更换账号，使用旧账号或新注册的账号结果一致，账号均关闭了设备锁。

- 通过旧issued的方案进行实践（反复尝试登录等方案）无效。

- 测试项目为maven项目，pom.xml 及测试代码

```xml
<dependency>
	<groupId>net.mamoe</groupId>
	<artifactId>mirai-core-qqandroid</artifactId>
	<version>1.3.3</version>
</dependency>
<dependency>
	<groupId>org.jetbrains.kotlin</groupId>
	<artifactId>kotlin-stdlib</artifactId>
	<version>1.4.0</version>
	<scope>compile</scope>
</dependency>
```
```java
BotConfiguration configuration = new BotConfiguration();
configuration.setProtocol(MiraiProtocol.ANDROID_PHONE);
configuration.fileBasedDeviceInfo("deviceInfo.json");
final Bot bot = BotFactoryJvm.newBot(QQ号, 密码, configuration);
bot.login();
bot.join();
 ```

没辙了，求大佬帮助。'ㅅ'

**Comment by sandtechnology** [comment]
解决这个问题非常简单，在目标机器上电脑QQ登录个几天挂着然后再试试就好
记得不要切换网络环境

**Comment by TerraLian** [comment]
使用在常用登录地的账号进行测试

- 若是MiraiProtocol.ANDROID_PAD 及 MiraiProtocol.ANDROID_WATCH ， 会报错：
`Recv: Error(title=温馨提示, message=当前版本过低，请先升级到手机QQ最新版本。, errorInfo=`

- 若是MiraiProtocol.ANDROID_PHONE，依旧是
`Recv: Error(title=禁止登录, message=为了您的帐号安全，请使用QQ一键登录（通过手机QQ授权登录）。, errorInfo=)`

测试版本为1.3.3，代码与上述一致。

**Comment by TerraLian** [comment]
阿懂了，是密码的关系。在常用登录地的账号若密码输入错误，也是提示版本过低。正确密码就正常了。
thanks

**Comment by Him188** [comment]
解决方法可以参考 
https://github.com/mamoe/mirai/issues/679#issuecomment-727134733
