### ISSUE TITLE
新账号无法登陆问题

### ISSUE THREAD

**Issue by mazehao** [mamoe/mirai#674]
新注册或者很久没登陆的账号登陆会报错 “当前上网环境异常，请更换网络环境或在常用设备上登录或稍后再试”
。这应该是apad 协议，本身的问题。但是现在又不能直接使用 “ANDROID_PHONE” 手机模式登陆，手机登录需要提示要使用 “禁止登陆，请使用QQ一键登录”  。临时解决方案先切到 pad 登录在用  “ANDROID_PHONE”  模式登陆。所以现在新注册的账号，或者类似的账号都无法登陆。请问如何绕过或者规避这种检测。

**Comment by Him188** [comment]
#672

**Comment by mazehao** [comment]
> #672

感谢，在测试一下。
