### ISSUE TITLE
Recv: LoginPacketResponse.Captcha.Picture

### ISSUE THREAD

**Issue by licaoshun** [mamoe/mirai#676]
2020-11-10 10:05:07 V/Net 1958963508: Send: wtlogin.login
2020-11-10 10:05:07 V/Net 1958963508: Recv: LoginPacketResponse.Captcha.Picture

然后就一直卡在这儿，没有任何动静。

系统环境：CentOS 8.2；
登录地点：跨省异地登录。

**Comment by Karlatemp** [comment]
Mirai 正在使用桌面环境,
如果你正在使用SSH, 或无法访问桌面等,
请将 `mirai.no-desktop` 添加到 JVM 系统属性中 (-Dmirai.no-desktop)
然后重启 Mirai
                            
Mirai using DesktopCaptcha System.
If you are running on SSH, cannot access desktop or more.
Please add `mirai.no-desktop` to JVM properties (-Dmirai.no-desktop)
Then restart mirai
