### ISSUE TITLE
为 MessageChain 添加时间获取

### ISSUE THREAD

**Issue by PopSlime** [mamoe/mirai#68]
可以给消息加上获取时间的API。

**Comment by Him188** [comment]
考虑在MessageSource添加然后在MessageChain添加扩展属性

**Comment by Chenwe-i-lin** [comment]
> 考虑在MessageSource添加然后在MessageChain添加扩展属性

关于HTTPAPI中的设计: 在SourceMessage中添加字段 `time`, 以 RFC2822 输出.

**Comment by Chenwe-i-lin** [comment]
关于为什么使用 RFC 2822: java的整数上限为 `2**31 - 1`.

**Comment by Him188** [comment]
在0.18.0支持
