### ISSUE TITLE
在本机编译运行jar包测试能发送富文本消息、xml分享和json小程序，功能均正常，但同样的jar包跑在阿里云上却无法正常使用分享功能。

### ISSUE THREAD

**Issue by applearound** [mamoe/mirai#681]
如题，在我个人PC编译运行jar包测试能发送富文本消息、xml分享和json小程序，功能均正常。
但同样的jar包跑在阿里云上却无法正常使用分享功能。
请问可能的原因是什么？分享功能的实现是否需要开启某些特定端口？

xml消息如图
![image](https://user-images.githubusercontent.com/12757496/98972001-d8cd2f80-254c-11eb-826a-369cbac9d386.png)
该消息在个人PC本机测试发送完全正常
但在云服务器上却没有任何效果
json的LightApp也是同样的情况

**Comment by applearound** [comment]
版本为mirai-core 1.3.3

**Comment by Him188** [comment]
应该是受qq服务器限制

**Comment by applearound** [comment]
> 应该是受qq服务器限制

你好，现在是否知道QQ服务器是通过什么信息进行限制的？可否进行伪装？

**Comment by sandtechnology** [comment]
此为QQ风控所致，请参见 #672

**Comment by applearound** [comment]
> 此为QQ风控所致，请参见 #672

所以只需要挂足够长时间等待就行了，是吗？谢谢！

**Comment by huhs1027** [comment]
> 如题，在我个人PC编译运行jar包测试能发送富文本消息、xml分享和json小程序，功能均正常。
> 但同样的jar包跑在阿里云上却无法正常使用分享功能。
> 请问可能的原因是什么？分享功能的实现是否需要开启某些特定端口？
> 
> xml消息如图
> ![image](https://user-images.githubusercontent.com/12757496/98972001-d8cd2f80-254c-11eb-826a-369cbac9d386.png)
> 该消息在个人PC本机测试发送完全正常
> 但在云服务器上却没有任何效果
> json的LightApp也是同样的情况

能否请教您的xml json卡片是如何拼接的? 我想实现分享qq音乐卡片到群里的功能,一直没有发送成功

**Comment by applearound** [comment]
> > 如题，在我个人PC编译运行jar包测试能发送富文本消息、xml分享和json小程序，功能均正常。
> > 但同样的jar包跑在阿里云上却无法正常使用分享功能。
> > 请问可能的原因是什么？分享功能的实现是否需要开启某些特定端口？
> > xml消息如图
> > ![image](https://user-images.githubusercontent.com/12757496/98972001-d8cd2f80-254c-11eb-826a-369cbac9d386.png)
> > 该消息在个人PC本机测试发送完全正常
> > 但在云服务器上却没有任何效果
> > json的LightApp也是同样的情况
> 
> 能否请教您的xml json卡片是如何拼接的? 我想实现分享qq音乐卡片到群里的功能,一直没有发送成功

https://github.com/khjxiaogu/MiraiSongPlugin，可以参考这个项目的源码。
