### ISSUE TITLE
支持使用QQ互联通道发送音乐分享

### ISSUE THREAD

**Issue by wdvxdr1123** [mamoe/mirai#682]
TX对音乐卡片进行了限制，导致自己拼的json 音乐卡片无法发送

可以使用 `OidbSvc.0xb77_9` 发送

**Comment by libsgh** [comment]
最近遇到了个问题 群里可以发音乐卡片不行，私聊的可以，请问，和这个有关系吗？

**Comment by huhs1027** [comment]
> TX对音乐卡片进行了限制，导致自己拼的json 音乐卡片无法发送
> 
> 可以使用 `OidbSvc.0xb77_9` 发送

请问OidbSvc.0xb77_9是什么? 
我也遇到自己造的卡片json数据无法发送的问题
往答疑 谢谢

**Comment by wdvxdr1123** [comment]
OidbSvc.0xb77_9 是包名，这个是需要发包实现的，我自己尝试了下，感觉mirai代码太抽象了，我没有那个能力改QAQ

**Comment by huhs1027** [comment]
> OidbSvc.0xb77_9 是包名，这个是需要发包实现的，我自己尝试了下，感觉mirai代码太抽象了，我没有那个能力改QAQ
是呀 网上的各种方法都试了. json怎么拼都发不出去
