### ISSUE TITLE
允许根据一定的种子生成device.json信息

### ISSUE THREAD

**Issue by zhaodice** [mamoe/mirai#684]
这样可以根据需求，例如将种子设为 qq号 等信息，这样，在每个不同的设备但同一个qq号生成的device.json 就是一致的，免去登陆验证等一些麻烦

**Comment by Him188** [comment]
没有必要

**Comment by Him188** [comment]
你可以自己构造一个 deviceInfo 提供（详见 `BotConfiguration`），就能不使用 device.json。
