### ISSUE TITLE
重新设计mirai码

### ISSUE THREAD

**Issue by zhaodice** [mamoe/mirai#685]
正常情况下：
测试文本[mirai:at:123456,@某人]。

而如果此人的群名片是
]嘿嘿[mirai:at:0,@A

那么就变成了
测试文本[mirai:at:123456,@]嘿嘿[mirai:at:0,@A]。

事实上如果群名片含有[]字符，也会造成mirai码的解析难度上升。

修改建议: 群名片进行base64编码

**Comment by sandtechnology** [comment]
mirai码在发送和转发中并不会被解析，除非主动进行解析（CodableMessage、MiraiCode），因此影响面其实非常小，解决方式可能是直接删除昵称输入。

**Comment by Him188** [comment]
我觉得去除群名片, 在发送时寻找成员获取名片

**Comment by landall** [comment]
> 我觉得去除群名片, 在发送时寻找成员获取名片

不使用群名片是对的。最好使用unique id来表示一个对象。就像twitter的at那样。微博那种at的逻辑真的太愚蠢了。。。。

另外mirai code最好不要具有二义性。换句话说，就是code自己的定界符，在任何其他情况下都要转义。
这个懒千万不要偷，否则后患无穷。

eg: 我在要QQ里向其他人讲解mirai code 的使用时，-w-

**Comment by Him188** [comment]
Note: 设计完后实现 `net.mamoe.mirai.message.data.ForwardMessage#contentToString`: message/data/ForwardMessage.kt:129
