### ISSUE TITLE
如何发送qq音乐卡片?

### ISSUE THREAD

**Issue by huhs1027** [mamoe/mirai#686]
我是java项目 maven依赖mirai-core来开发的

json:
{"app":"com.tencent.structmsg","config":{"forward":true,"ctime":1606315304143,"type":"normal","autosize":true,"token":"a8f1d1c8864c38d807b1b58a4f0772fe"},"desc":"音乐","extra":{"app_type":1,"appid":100497308,"uin":3522521295},"meta":{"music":{"preview":"http://y.gtimg.cn/music/photo_new/T002R180x180M0000035d3YW0wLc23_1.jpg","app_type":1,"musicUrl":"http://ws.stream.qqmusic.qq.com/C400004SFGlH4OzEIg.m4a?guid=358840384&vkey=5B3086CF25AA84AB500E1CC576E15543547E6251641DE9D323278C4801DAC1D365F0850997963279EB6655916423DB46FF6826BC99ED0A72&uin=0&fromtag=66","title":"粒子们","jumpUrl":"https://i.y.qq.com/v8/playsong.html?songtype=0&songmid=004SFGlH4OzEIg","source_url":"","android_pkg_name":"","source_icon":"","appid":100497308,"sourceMsgId":"0","action":"","tag":"QQ音乐","desc":"于贞"}},"prompt":"[分享]粒子们","ver":"0.0.0.1","view":"music"}

最后是返回的LightApp
现在我不知道是我的json对象有问题还是框架有问题

**Comment by takayama-lily** [comment]
这个json是你收到的，并且原封不动的发送吗？还是自己构造的

**Comment by huhs1027** [comment]
> 这个json是你收到的，并且原封不动的发送吗？还是自己构造的

自己构造的，昨晚我又试了下用收到的json原封不动的发送是可以发送的，怀疑是token的问题

**Comment by takayama-lily** [comment]
> > 这个json是你收到的，并且原封不动的发送吗？还是自己构造的
> 
> 自己构造的，昨晚我又试了下用收到的json原封不动的发送是可以发送的，怀疑是token的问题

我也这么想

**Comment by Him188** [comment]
原封不动的json可以发, 你自己构造的不能发, 有很大概率是你自己 json 有问题

**Comment by huhs1027** [comment]
求大佬来分享下token要怎么获取 - -

**Comment by stinaCN** [comment]
> 原封不动的json可以发, 你自己构造的不能发, 有很大概率是你自己 json 有问题

不是json有问题，你改动了json数据就得重新计算token值，因为json数据改动了，数据和token不匹配，验证过不去就发不出了

**Comment by xiwangly2** [comment]
> 

同问，我一直搞不明白token的算法
