### ISSUE TITLE
mirai发送的图片信息扩展名是mirai

### ISSUE THREAD

**Issue by meaningtree** [mamoe/mirai#689]
使用mirai发送的图片信息，收到的图片在本地的缓存后的扩展名是mirai，对于经常使用桌面QQ拖拽图片保存图片的用户，得到的图片是mirai的扩展名，使用起来有一些不方便。

希望能够正确的获取扩展名。

#### 复现
使用的是sendImage（InputStream）发送的图片
在QQ桌面端拖拽图片保存，获得的图片是xxxx.mirai,正常手动发送的图片应该是xxx.jpg xxx.png等

#### 版本
mirai: 1.3.3
QQ：9.4.0

**Comment by Karlatemp** [comment]
与 #635 重复
