### ISSUE TITLE
MessageChain.get 方法以 PlainText 等允许重复存在的元素使用时语义不明确

### ISSUE THREAD

**Issue by Him188** [mamoe/mirai#693]
### 问题
`chain[PlainText]` 语义不明确: 因为 `PlainText` 允许有多个存在, 而该表达式只返回第一个实例. 

而 `chain[MessageMetadata]` 这样的语法是有意义的: 因为 `MessageMetadata` 是 `ConstainSingle`, 每个 `MessageChain` 只允许出现一个实例.

### 处理方案
- 删除所有允许重复出现的元素 (如 `MessageContent`) 的 companion Key

**Comment by Him188** [comment]
@Karlatemp Waiting for your opinion.

**Comment by Karlatemp** [comment]
使用 [] 获取类似 PlainText 等可重复出现的元素可以考虑返回 List

**Comment by Him188** [comment]
> 使用 [] 获取类似 PlainText 等可重复出现的元素可以考虑返回 List

`MessageChain : List<SingleMessage>` 应该使用 `chain.filterIsInstance<PlainText>()` 得到 `List`

**Comment by Karlatemp** [comment]
那删除companion Key吧

**Comment by Him188** [comment]
正在进行:
- `ConstrainSingle` 父类型由 `MessageMetadata` 变为 `SingleMessage`
- `Message.Key` 移动到 `ConstainSingle.Key`
- 删除所有允许重复出现的类型的 `companion object Key`, 但保留默认名称的伴生对象
