### ISSUE TITLE
Mirai 留言板

### ISSUE THREAD

**Issue by Him188** [mamoe/mirai#696]
感谢你对 Mirai 的支持。

你可以在这里留下对 Mirai 的看法和未来的发展建议，请畅所欲言。

**Comment by takayama-lily** [comment]
好的

**Comment by TheSnowfield** [comment]
好的 (+1)

**Comment by Karlatemp** [comment]
嘤

**Comment by MikuNyanya** [comment]
不知道说啥
还是

\兔子万岁/

吧

感谢你们的努力

**Comment by Kininaru** [comment]
https://github.com/mamoe/mirai/blob/dev/docs/guide_quick_start.md 此页面下, "添加依赖"板块下, "直接导入Jar包"下, 有两个下载链接. 其中, 第二个链接的文字中有一个单词拼错了, "mirai-qqandriod" 应该为 "mirai-qqandroid"

**Comment by zhufree** [comment]
感谢

**Comment by Him188** [comment]
> 听说禁言匿名在测试了吗，进展如何

完成了，再等时机成熟就合并

**Comment by anaivebird** [comment]
请问禁言匿名的代码commit了吗
