### ISSUE TITLE
处理加群申请时获取加群问题的回答

### ISSUE THREAD

**Issue by developer-ken** [mamoe/mirai#697]
是否有办法在处理加群申请时获取加群问题的回答？

我通过Mirai-CSharp操作Mirai，现在希望能够在处理加群时获取用户对加群问题的回答，并以此判定是否同意。请问是否已经可行，或是否有可能在未来可行？

**Comment by Karlatemp** [comment]
`MemberJoinRequestEvent.message`, 若没有该字段很有可能是 Mirai-CSharp 问题
