### ISSUE TITLE
整理事件结构

### ISSUE THREAD

**Issue by Karlatemp** [mamoe/mirai#699]
### 问题

目前 mirai 事件系统的结构比较混乱, 比如与信息收发有关的事件放置于 `net.mamoe.mirai.message` 下,
而 mirai 又存在 `net.mamoe.mirai.event` 包, 故应该将全部事件放置于 `net.mamoe.mirai.event` 包(或其子包) 下

### 处理方案

- 移动全部事件至 `net.mamoe.mirai.event`
- 根据事件的核心主体在 `net.mamoe.mirai.event` 下进行再次分包 (如: `net.mamoe.mirai.event.message`)

**Comment by Him188** [comment]
事件本身只有一个 class, 分 package 处理可能没有必要, 分文件即可

**Comment by Karlatemp** [comment]
已没有更多event需要移动
