### ISSUE TITLE
建议添加HTTP API

### ISSUE THREAD

**Issue by sakurayang** [mamoe/mirai#7]
能不能添加一个支持使用http协议操作的api
`localhost:port/send?qq=qqid&group=groupid&message=text`之类的

**Comment by Him188** [comment]
谢谢，HTTP API正在计划中。最近我们学业都挺忙，更新慢。

**Comment by liujiahua123123** [comment]
已经开始添加

https://github.com/mamoe/mirai/tree/master/mirai-api-http
```php
:)
```

**Comment by liujiahua123123** [comment]
HTTP API 将以 Plugin 的形式被支持
