### ISSUE TITLE
/docs的一些链接跳转至404

### ISSUE THREAD

**Issue by awesomehhhhh** [mamoe/mirai#701]
https://github.com/mamoe/mirai/blob/dev/docs/mirai.md
内80%链接均跳转到404
貌似是更改文件夹导致的
如：https://github.com/mamoe/mirai/blob/dev/mirai-core/src/commonMain/kotlin/net.mamoe.mirai/utils/Annotations.kt#L41

**Comment by ryoii** [comment]
进入 `master` 分支阅读文档，`dev` 分支目前进行重构，文档是落后于实际代码的

https://github.com/mamoe/mirai/blob/master/docs/mirai.md

**Comment by Him188** [comment]
mirai 文档已经更新
