### ISSUE TITLE
手动踢下线,导致无法重新登录

### ISSUE THREAD

**Issue by sulinwork** [mamoe/mirai#702]
我主动打开手机QQ 显示ipad在线 然后我主动踢下线 
![image](https://user-images.githubusercontent.com/42666595/101469629-f476fa80-397f-11eb-82b3-47649c43d947.png)
从控制台看 显示重连成功，但是手机已经不会显示ipad在线了 也收不到任何消息了

**Comment by ketal178** [comment]
挤号也是这样

**Comment by Him188** [comment]
#835
