### ISSUE TITLE
在 BotConfiguration 添加多平台的检查并要求在 Android 目标时手动提供验证码解决器

### ISSUE THREAD

**Issue by adhyc520** [mamoe/mirai#703]
Bot bot1 = BotFactoryJvm.newBot(123, "", new BotConfiguration() {})
这样写的话会弹出登录验证码的界面，在android会报错。

**Comment by awesomehhhhh** [comment]
或许指定一个已经无需验证码登录的device.json可以解决，这样就无需验证码了。

**Comment by Karlatemp** [comment]
请提供报错内容以便于确定错误原因

**Comment by adhyc520** [comment]
> 请提供报错内容以便于确定错误原因

请问是否有android java的demo

**Comment by Karlatemp** [comment]
`Android 环境`, 指的是 在 Android 上运行 mirai 还是使用 `ANDROID_PHONE` 协议

若为 `Android 环境`, 必须覆盖其验证码解决器, (请参阅 `BotConfiguration` 源码), 在 [KT-37152](https://youtrack.jetbrains.com/issue/KT-37152) 解决之前 Mirai 无法直接提供可以在 Android 上运行的验证码解决器

若为 `ANDROID_PHONE` 协议, 请将相关报错信息提交到此 issue 中

目前没有 android java 的demo

**Comment by adhyc520** [comment]
> `Android 环境`, 指的是 在 Android 上运行 mirai 还是使用 `ANDROID_PHONE` 协议
> 
> 若为 `Android 环境`, 必须覆盖其验证码解决器, (请参阅 `BotConfiguration` 源码), 在 [KT-37152](https://youtrack.jetbrains.com/issue/KT-37152) 解决之前 Mirai 无法直接提供可以在 Android 上运行的验证码解决器
> 
> 若为 `ANDROID_PHONE` 协议, 请将相关报错信息提交到此 issue 中
> 
> 目前没有 android java 的demo

好的，谢谢大佬，我在学习一下，希望出一个Android 的demo 。

**Comment by awesomehhhhh** [comment]
> `Android 环境`, 指的是 在 Android 上运行 mirai 还是使用 `ANDROID_PHONE` 协议
> 
> 若为 `Android 环境`, 必须覆盖其验证码解决器, (请参阅 `BotConfiguration` 源码), 在 [KT-37152](https://youtrack.jetbrains.com/issue/KT-37152) 解决之前 Mirai 无法直接提供可以在 Android 上运行的验证码解决器
> 
> 若为 `ANDROID_PHONE` 协议, 请将相关报错信息提交到此 issue 中
> 
> 目前没有 android java 的demo

那么如果是把device.json（已无需验证码，之前登陆过且已经过风控期的）拷贝到*.apk中，这样是不是无需验证码且可以在Android中使用Mirai ？

**Comment by Karlatemp** [comment]
> 那么如果是把device.json（已无需验证码，之前登陆过且已经过风控期的）拷贝到*.apk中，这样是不是无需验证码且可以在Android中使用Mirai ？

取决于服务器，若服务器需要验证(如离开常用登录地)，还是会出现验证码，无法保证100%不会出现

**Comment by awesomehhhhh** [comment]
> > 那么如果是把device.json（已无需验证码，之前登陆过且已经过风控期的）拷贝到*.apk中，这样是不是无需验证码且可以在Android中使用Mirai ？
> 
> 取决于服务器，若服务器需要验证(如离开常用登录地)，还是会出现验证码，无法保证100%不会出现

所以其实mirai是支持Android环境的是吗

**Comment by adhyc520** [comment]
> > > 那么如果是把device.json（已无需验证码，之前登陆过且已经过风控期的）拷贝到*.apk中，这样是不是无需验证码且可以在Android中使用Mirai ？
> > 
> > 
> > 取决于服务器，若服务器需要验证(如离开常用登录地)，还是会出现验证码，无法保证100%不会出现
> 
> 所以其实mirai是支持Android环境的是吗
支持，我试过，但是这样很麻烦的，想换个QQ就很麻烦。

**Comment by Him188** [comment]
Android 没有标准输入和标准输出，似乎无法提供。

可以在 MPP Android 目标里 BotConfiguration 验证时要求提供验证码解决器

**Comment by awesomehhhhh** [comment]
> > > > 那么如果是把device.json（已无需验证码，之前登陆过且已经过风控期的）拷贝到*.apk中，这样是不是无需验证码且可以在Android中使用Mirai ？
> > > 
> > > 
> > > 取决于服务器，若服务器需要验证(如离开常用登录地)，还是会出现验证码，无法保证100%不会出现
> > 
> > 
> > 所以其实mirai是支持Android环境的是吗
> 支持，我试过，但是这样很麻烦的，想换个QQ就很麻烦。

ERROR: Unable to resolve dependency for ':app@debug/compileClasspath': Could not download mirai-core.jar (net.mamoe:mirai-core:1.3.3)
这是因为？

**Comment by awesomehhhhh** [comment]
> > > > > 那么如果是把device.json（已无需验证码，之前登陆过且已经过风控期的）拷贝到*.apk中，这样是不是无需验证码且可以在Android中使用Mirai ？
> > > > 
> > > > 
> > > > 取决于服务器，若服务器需要验证(如离开常用登录地)，还是会出现验证码，无法保证100%不会出现
> > > 
> > > 
> > > 所以其实mirai是支持Android环境的是吗
> > > 支持，我试过，但是这样很麻烦的，想换个QQ就很麻烦。
> 
> ERROR: Unable to resolve dependency for ':app@debug/compileClasspath': Could not download mirai-core.jar (net.mamoe:mirai-core:1.3.3)
> 这是因为？

已解决，非mirai问题，抱歉。

**Comment by Him188** [comment]
net.mamoe.mirai.utils.LoginSolver#Default

检测策略:
1. 检测 `android.util.Log`, 如果存在, 返回 `null`.
2. 检测 JVM 属性 `mirai.no-desktop`. 若存在, 返回 [StandardCharImageLoginSolver]
3. 检测 JVM 桌面环境, 若支持, 返回 [SwingSolver]
4. 返回 [StandardCharImageLoginSolver]
