### ISSUE TITLE
私聊消息撤回事件 FriendRecall 的 authorId 属性存在歧义

### ISSUE THREAD

**Issue by ForteScarlet** [mamoe/mirai#704]
`MessageRecallEvent.FriendRecall` 中的 `authorId` 属性，按照名称来讲似乎代表了 "作者ID"，那么我认为它应当指的是 "被撤回的这条消息的发送者ID"，但是实际表现中它的返回值为 `bot.id`，即 ”收到这个撤回事件的BOT的ID“。

版本：`v1.3.3`

我认为这样似乎与属性命名含义不同。

**Comment by Him188** [comment]
![image](https://user-images.githubusercontent.com/12100985/102702490-4b44d400-429e-11eb-8971-d5df28f64fc8.png)

经测试，authorId 是对方 id

**Comment by Him188** [comment]
哦.. authorId 不是
![image](https://user-images.githubusercontent.com/12100985/102702506-6a436600-429e-11eb-8617-4bf5c2405d30.png)

**Comment by ForteScarlet** [comment]
啊这
