### ISSUE TITLE
Bot资料信息修改功能/前端UI

### ISSUE THREAD

**Issue by chk141** [mamoe/mirai#707]
获取Bot自身资料信息,如账号,等级,Q龄,个性签名等等
修改Bot资料信息
简单的前端UI示例

**Comment by Him188** [comment]
前端 UI 与 bot 无关, 资料已经有相关 issue

**Comment by chk141** [comment]
> 前端 UI 与 bot 无关，资料已经有相关 issue

回复神速啊兄弟, 我指的示例UI,不然人家进来了一看一个一脸懵逼,没人愿意接着研究了呀

**Comment by Him188** [comment]
bot 也可以用于做人工智能的聊天语义分析, 但我并不需要写一个这种示例
