### ISSUE TITLE
Java对suspend函数的调用

### ISSUE THREAD

**Issue by Alceatraz** [mamoe/mirai#709]
我使用Java+Maven开发，安装了IDEA的KJBB插件

`Mamoe 为此开发了 Kotlin 编译器插件 Kotlin Jvm Blocking Bridge，通过 @JvmBlockingBridge 注解，在编译期额外生成一个供 Java 使用的方法，让 Java 用户可以使用拥有源码内相同的函数签名的方法。`

问题1：我阅读了KJBB的说明，貌似KJBB是给KT编写者使用的，将KT编译时生成可供Java调用的方法，而不是Java调用者使用的？
问题2：调用出错，比如关闭Bot：
```java
bot.closeAndJoin(null); // closeAndJoin画红线
bot.recall(xxxxx); // 正常不报错
```
但是看源码时
```
@JvmSynthetic
public suspend inline fun Bot.recall(message: MessageChain): Unit = this.recall(message.source)

@JvmSynthetic
public suspend inline fun Bot.closeAndJoin(cause: Throwable? = null) {
    close(cause)
    coroutineContext[Job]?.join()
}
```
都有JvmSynthetic但是closeAndJoin就不可调用
再比如
```
@JvmSynthetic
public abstract suspend fun acceptNewFriendRequest(event: NewFriendRequestEvent)
```
也不可调用

**Comment by Him188** [comment]
1.x 对 Java 支持不太完善，在 2.0-M1 就会解决
