### ISSUE TITLE
HTTP-API: Session 建立时返回了与文档不同的回复

### ISSUE THREAD

**Issue by Him188** [mamoe/mirai#71]
文档
![VC89@ZU(Q2$GF_PX(`9 F52](https://user-images.githubusercontent.com/12100985/74796238-f2658180-5302-11ea-81a4-5bedbd8e7328.png)

实际
![PL N@3PDV~YLB_~OEY39O88](https://user-images.githubusercontent.com/12100985/74796241-f42f4500-5302-11ea-9701-48f5b75301ce.png)

**Comment by Chenwe-i-lin** [comment]
我要不做个polyfill...?

**Comment by Chenwe-i-lin** [comment]
> 我要不做个polyfill...?

已经加上了
