### ISSUE TITLE
EventHandler有没有方法收到原始String的消息？

### ISSUE THREAD

**Issue by Alceatraz** [mamoe/mirai#711]
```java
@EventHandler
public void onEvent(Event event)
```

这样可以接受所有的事件，然后打印：

```
GroupMessageEvent(省略 message=[mirai:source:438,-1005286162]A)
GroupMessageEvent(省略 message=[mirai:source:439,1882739600]AA)
GroupMessageEvent(省略 message=[mirai:source:439,1882739600]BB)
GroupMessageEvent(省略 message=[mirai:source:440,-1607885146]C)
GroupMessageEvent(省略 message=[mirai:source:440,-1607885146]D)
```

即使监听最原始的event也是已经被处理成MessageChain的消息，这个行为实际上是意料之中的，因为根据代码，MessageEvent包含的就是MessageChain对象。

问题：因为此部分代码无法查看，QQ的消息协议中，消息是按照原始String传递还是本身有类似MessageChain的设计？
如果是按照String传递的，有没有办法获取？

Off Topic: 以前Jcq的时候有一个处理CQ码的步骤，我先判断是否是命令 再执行extractCQCode的操作，以避免无意义的开销。如果只能获取MessageChain，我只能先合并，因为我自己的解析规则不是全部按照空格拆开，类似数据库的使用了`` 所以必须从最基础的部分开始写。所以请问有没有办法获取到原始的String。

**Comment by Karlatemp** [comment]
原始数据就是messagechain
