### ISSUE TITLE
无法在回复一句话的代码中判断信息来自哪个群

### ISSUE THREAD

**Issue by LexieAlreadyTaken** [mamoe/mirai#714]
suspend fun main() {

        val miraiBot = Bot(qqId, password, configuration).alsoLogin()//新建Bot并登录

        miraiBot.subscribeMessages {

             (case("on")){

                //在这里怎么判断信息来自哪个群？

            }
    }
像这样的代码里，我不知道怎么获得这条信息来自的群号。
因为看discussion实在没人用所以放到了issue里，如果不妥请删除。

**Comment by sandtechnology** [comment]
`it`
不熟悉DSL建议使用普通监听的方式

**Comment by Him188** [comment]
discussion并不是没人用，是它才刚开几天

**Comment by Him188** [comment]
```kotlin
(case("on") and sentFrom(123456)) {

}
```

不熟悉DSL建议使用普通监听的方式

**Comment by LexieAlreadyTaken** [comment]
> `it`
> 不熟悉DSL建议使用普通监听的方式

谢谢！

**Comment by LexieAlreadyTaken** [comment]
> ```kotlin
> (case("on") and sentFrom(123456)) {
> 
> }
> ```
> 
> 不熟悉DSL建议使用普通监听的方式

谢谢！
（不过还是想问一下怎么用DSL监听……因为这样还是很不方便，比如当消息来自数据库中的某些群的时候执行一个操作，但case()在嵌套在循环里面的时候似乎不管用？）

**Comment by Him188** [comment]
使用 `SimpleListenerHost`，或者 `subscribeAlways`
