### ISSUE TITLE
更新协议版本

### ISSUE THREAD

**Issue by xel96naga** [mamoe/mirai#719]
12.16日夜间（不知道具体几点），许多mirai用户的程序崩溃了，当我们重启mirai程序时，总是获得如下信息：

![image](https://user-images.githubusercontent.com/43462675/102334730-fc5f1c00-3fc9-11eb-914e-0a2e029d0d1b.png)

我们尝试过各种方法，改了密码，换了QQ，换了电脑，改了device.json文件，都没有解决问题。

综上，我们推测，可能是QQ更新了什么。因为是一群人在同一时间一起断线的，而且有些人代码一直就没有改动过（比如我），所以这不可能是巧合。

我们一群小白拉了一个群也没有讨论出什么，网上的方法都试过了。

希望mirai能更新，我们很需要大佬们的帮助。

**Comment by ryoii** [comment]
尝试修改 `device.json` 文件中的各种名称后登录，使用正常客户端登录 bot 查看账号是否有异常

**Comment by xel96naga** [comment]
大佬能提供一个可以成功运行的device.json么，我们改来改去也没搞好，我们一群人可能都写的不对

**Comment by sandtechnology** [comment]
可以看出并没有指定本地存储的device.json 因此设备信息都是随机的，请查看文档进行指定后，用电脑QQ挂上几天后再试
另：版本过低为密码错误

**Comment by xel96naga** [comment]
> 可以看出并没有指定本地存储的device.json 因此设备信息都是随机的，请查看文档进行指定后，用电脑QQ挂上几天后再试
> 另：版本过低为密码错误

已经说过了，我们真的写不好device.json，查了设备配置，有些项也不会填，所以我需要一个已经管用的device.json作为参考

**Comment by sandtechnology** [comment]
> 
> 
> > 可以看出并没有指定本地存储的device.json 因此设备信息都是随机的，请查看文档进行指定后，用电脑QQ挂上几天后再试
> > 另：版本过低为密码错误
> 
> 已经说过了，我们真的写不好device.json，查了设备配置，有些项也不会填，所以我需要一个已经管用的device.json作为参考

设备信息是随机生成的 **不存在**管用的device.json
如果不指定存储的本地的device.json存储位置，每次启动都将会使用不同的设备信息

**Comment by xel96naga** [comment]
> > > 可以看出并没有指定本地存储的device.json 因此设备信息都是随机的，请查看文档进行指定后，用电脑QQ挂上几天后再试
> > > 另：版本过低为密码错误
> > 
> > 
> > 已经说过了，我们真的写不好device.json，查了设备配置，有些项也不会填，所以我需要一个已经管用的device.json作为参考
> 
> 设备信息是随机生成的 **不存在**管用的device.json
> 如果不指定存储的本地的device.json存储位置，每次启动都将会使用不同的设备信息

明白了，那么在服务器上挂上几天QQ，再用定义好的device.json就可以了连上了么

**Comment by xel96naga** [comment]
为什么换了台电脑，换了几个QQ号，都登陆不了呢，如果是设备问题，换电脑和QQ应该可以解决吧

**Comment by Him188** [comment]
修改密码可以解决问题

**Comment by xel96naga** [comment]
> 修改密码可以解决问题

我已经改过两次密码了

**Comment by shenhuyong** [comment]
修改密码实测4个账号均无效

**Comment by Him188** [comment]
@xel96naga @shenhuyong 尝试使用 PAD?

**Comment by xel96naga** [comment]
![image](https://user-images.githubusercontent.com/43462675/102354893-20c8f180-3fe6-11eb-914d-7de871942c44.png)
是这个pad协议么，没用

**Comment by xel96naga** [comment]
![image](https://user-images.githubusercontent.com/43462675/102355007-3b02cf80-3fe6-11eb-9764-35be6a09de49.png)
是 BotConfiguration.MiraiProtocol.ANDROID_PAD 这个pad协议么，没用啊

**Comment by xel96naga** [comment]
而且不少人都说是昨天夜里断开的，我挂了两个星期没事，也是昨晚睡觉的时候断开的。
代码未曾更改过

**Comment by shenhuyong** [comment]
1.3.3 默认是PAD吧 没改过

**Comment by Requiem4Eternity** [comment]
我这边情况倒是不一样，看日志是没有掉线，还在正常发送心跳，但却收不到任何消息

**Comment by xel96naga** [comment]
是不是什么东更新了，因为之前都是正常的，只有昨晚才断开，崩溃。中间没有任何改动

**Comment by Him188** [comment]
https://github.com/mamoe/mirai/commit/c478f24db085d88e6c1148dc32003e453cf70650 应该解决了这个问题, 2.0-M1

**Comment by xel96naga** [comment]
谢谢作者大大，明天等release了就试试

**Comment by jinxu577620** [comment]
我是直接pom文件中拉的包
 <dependency>
            <groupId>net.mamoe</groupId>
            <artifactId>mirai-core-qqandroid-jvm</artifactId>
            <version>1.3.3</version> 
        </dependency>
也出现了这个问题，应该如何解决呢

**Comment by JinxLbj** [comment]
> [c478f24](https://github.com/mamoe/mirai/commit/c478f24db085d88e6c1148dc32003e453cf70650) 应该解决了这个问题, 2.0-M1

请问MAVEN包有没有更新呢

**Comment by jinxu577620** [comment]
这个问题似乎没有解决吧

**Comment by Alanzhuo** [comment]
大佬，有打算什么时候更新maven包吗？

**Comment by notbucai** [comment]
大概还要多久更新maven包呢

**Comment by Him188** [comment]
发布版本要时间, 估计2-3天

**Comment by jinxu577620** [comment]
大佬，我看你已经修改了源代码，请问一下，我之前导的1.3.3的版本是要更新还是继续用之前的呢？
