### ISSUE TITLE
求支持禁匿名用户

### ISSUE THREAD

**Issue by anaivebird** [mamoe/mirai#722]
求尽快实现set_group_snonymous_ban

# 参数

字段名 | 数据类型 | 默认值 | 说明
-- | -- | -- | --
group_id | number | - | 群号
anonymous | object | - | 可选，要禁言的匿名用户对象（群消息上报的 anonymous 字段）
anonymous_flag 或 flag | string | - | 可选，要禁言的匿名用户的 flag（需从群消息上报的数据中获得）
duration | number | 30 * 60 | 禁言时长，单位秒，无法取消匿名用户禁言

上面的 anonymous 和 anonymous_flag 两者任选其一传入即可，若都传入，则使用 anonymous。

**Comment by Karlatemp** [comment]
#432
