### ISSUE TITLE
mirai无法登陆

### ISSUE THREAD

**Issue by f1253370816** [mamoe/mirai#723]
原先在linux服务器上运行的好好的，重启之后无法登陆，之前版本是1.3.2，目前升级版本到1.3.3也无法登陆。使用三种登陆方式都不行。
1.3.3版本 三种登陆方式报错：
ANDROID_PHONE：直接报错 Error(title=禁止登录, message=为了您的帐号安全，请使用QQ一键登录（通过手机QQ授权登录）。, errorInfo=)。
ANDROID_PAD ：可以输入验证码，输入后报错 Error(title=禁止登录, message=当前上网环境异常，请更换网络环境或在常用设备上登录或稍后再试。, errorInfo=)。
ANDROID_WATCH：可以输入验证码，输入后报错 Error(title=禁止登录, message=当前上网环境异常，请更换网络环境或在常用设备上登录或稍后再试。, errorInfo=)。
1.3.2版本 登陆报错：
老账号：Error(title=温馨提示, message=当前版本过低，请先升级到手机QQ最新版本。, errorInfo= )。
新账号：输入验证码之后，Error(title=禁止登录, message=当前上网环境异常，请更换网络环境或在常用设备上登录或稍后再试。, errorInfo=)。
账号密码核对过多次。
尝试过新申请QQ账号，老账号改密码，找朋友在他电脑上启动项目，电脑登陆账号在本地启动项目，手机登陆账号本地启动项目，电脑和手机同时登陆账号本地启动项目，或者是在linux服务器上启动项目。均是报错的，已经没辙了。求救救。。
![image](https://user-images.githubusercontent.com/76193140/102572466-2bd76b00-4127-11eb-9bea-c52b3451c8e4.png)
![image](https://user-images.githubusercontent.com/76193140/102572500-47427600-4127-11eb-8b39-ae436f01fd5f.png)

**Comment by f1253370816** [comment]
另外：设备锁也是打开关闭都尝试过了。没有用。。

**Comment by Zhengfourth** [comment]
`出现类似问题，之前一切正常，今天无法登录，错误信息是```Exception in thread "main" net.mamoe.mirai.network.WrongPasswordException: Error(title=温馨提示, message=当前版本过低，请先升级到手机QQ最新版本。, errorInfo= )```。推测为 QQ 安全验证机制，尝试各种方法均无效。账号的登录保护也未开启。

**Comment by shellljx** [comment]
我今天想登陆也遇到了提示当前版本过低的错误，难道是qq协议升级了吗

**Comment by zwl1998** [comment]
+1，希望有解决方法

**Comment by FeverKing** [comment]
同问

**Comment by LTZDLY** [comment]
重新重头开始搞，4个号有3个号无限提醒无法登陆，版本过低，而另一个号则能一直能正常弹出登陆验证和验证窗口，完全不明白。4个号设备保护设置完全一致，设备锁均为开启

**Comment by f1253370816** [comment]
> 重新重头开始搞，4个号有3个号无限提醒无法登陆，版本过低，而另一个号则能一直能正常投放登陆验证和验证窗口，完全不明白。4个号设备保护设置完全一致，设备锁开启

那是有解决方案嘛？好的那个号是什么情况。

**Comment by LTZDLY** [comment]
> > 重新重头开始搞，4个号有3个号无限提醒无法登陆，版本过低，而另一个号则能一直能正常投放登陆验证和验证窗口，完全不明白。4个号设备保护设置完全一致，设备锁开启
> 
> 那是有解决方案嘛？好的那个号是什么情况。

反正现在的感觉是我这边4个号加朋友几个号，曾经用过mirai登陆的都可以正常弹出验证窗口，而从没登录过的会直接无限提醒版本过低

**Comment by f1253370816** [comment]
> > > 重新重头开始搞，4个号有3个号无限提醒无法登陆，版本过低，而另一个号则能一直能正常投放登陆验证和验证窗口，完全不明白。4个号设备保护设置完全一致，设备锁开启
> > 
> > 
> > 那是有解决方案嘛？好的那个号是什么情况。
> 
> 反正现在的感觉是我这边4个号加朋友几个号，曾经用过mirai登陆的都可以正常弹出验证窗口，而从没登录过的会直接无限提醒版本过低

我老号也无法登陆。报版本过低。新号报网络异常。。

**Comment by f1253370816** [comment]
有没有万能的程序员救救孩子啊。。。。蹲一个解决方法。。

**Comment by Karlatemp** [comment]
会在 2.0-M1 解决这个问题

**Comment by Him188** [comment]
使用 2.0-M1

**Comment by tobywkr** [comment]
用了m1也一样啊喂

**Comment by Him188** [comment]
try 2.8.0
