### ISSUE TITLE
为了您的账号安全，请使用QQ一键登录? 2.0-M1

### ISSUE THREAD

**Issue by null-su** [mamoe/mirai#729]
确定密码正确

**Comment by Him188** [comment]
尝试切换 ANDROID 或 PAD 协议，并首先在常用地点登录

**Comment by null-su** [comment]
> 尝试切换 ANDROID 或 PAD 协议，并首先在常用地点登录

`2020-12-19 11:54:18 I/main: Starting mirai-console...`
`2020-12-19 11:54:19 I/main: Backend: version 2.0-M1, built on 2020-12-19 00:45:02.`
`2020-12-19 11:54:19 I/main: Frontend Terminal: version 2.0-M1, provided by Mamoe Technologies`
`2020-12-19 11:54:19 I/main: Prepared built-in commands: autoLogin, help, login, permission, status,stop`
`2020-12-19 11:54:19 I/main: 0 plugin(s) enabled.`
`2020-12-19 11:54:19 I/Mirai: Mirai 正在使用桌面环境. 如遇到验证码将会弹出对话框. 可添加 JVM 属性 `mirai.no-desktop` 以关闭.`
`2020-12-19 11:54:19 I/Mirai: Mirai is using desktop. Captcha will be thrown by window popup. You can add `mirai.no-desktop` to JVM properties (-Dmirai.no-desktop) to disable it.`
`2020-12-19 11:54:19 I/main: Auto-login *******`
`2020-12-19 11:54:20 I/Bot.*******: Logging in...`
`2020-12-19 11:54:20 E/main: Failed to init MiraiConsole.net.mamoe.mirai.network.WrongPasswordException: Error(title=温馨提示, message=当前版本过低，请先升级到手机QQ最新版本。, errorInfo=`

 ANDROID_PHONE 和  ANDROID_PAD 都试过了

`文件: libs\mirai-console-2.0-M1-all.jar`
`MD5: AED31DBF9B518CC7F30A928A232873D3`
`SHA1: C2A4508EEB87E2A8CE34760FF8279A59DDE19558`
``
`文件: libs\mirai-console-gradle-2.0-M1-all.jar`
`MD5: 0B3B2BA66E65071487CEF9A3430AB22D`
`SHA1: CE8ACAE9E49885D01444A72BDDA7EAA37F0EF948`
``
`文件: libs\mirai-console-intellij-2.0-M1-all.jar`
`MD5: 8B99DFD210E63FCFFD0E3A9C7C16AD9C`
`SHA1: B98014751FBDB97605F9D6D9608196B78B1D5C68`

`文件: libs\mirai-console-terminal-2.0-M1-all.jar`
`MD5: 78C7708F51FB98B63DE0875A8BD48B77`
`SHA1: 49386CBCF6A87A7C0F350ADCC5CD4BF5A4415A33`
``
`文件: libs\mirai-core-all-2.0-M1-all.jar`
`MD5: DFF810C07B1D6D74A35CAE3E8D0781C0`
`SHA1: 93C2461E087192906CB1578D54C5E9F125EED109`

**Comment by null-su** [comment]
密码没问题 能登录QQ邮箱

**Comment by Him188** [comment]
#717
