### ISSUE TITLE
2.0-M1 maven 导入问题

### ISSUE THREAD

**Issue by notbucai** [mamoe/mirai#730]
![image](https://user-images.githubusercontent.com/32786133/102681147-0d8e6f80-41fa-11eb-98db-fa2091d95b1d.png)

导入后包内为空
![image](https://user-images.githubusercontent.com/32786133/102681171-40386800-41fa-11eb-91b8-de016ec63177.png)

依赖也找不到

**Comment by Him188** [comment]
`2.0-M1`

**Comment by notbucai** [comment]
![image](https://user-images.githubusercontent.com/32786133/102681212-8c83a800-41fa-11eb-8c69-e8d2d5c44456.png)
![image](https://user-images.githubusercontent.com/32786133/102681214-90afc580-41fa-11eb-9588-36118eb8b796.png)

**Comment by notbucai** [comment]
![image](https://user-images.githubusercontent.com/32786133/102681220-a2916880-41fa-11eb-9787-3ab39585e133.png)

**Comment by Karlatemp** [comment]
使用gradle

使用maven需要 net.mamoe:mirai-core-api-jvm
