### ISSUE TITLE
java.lang.IllegalStateException: The provided plugin net.mamoe.kjbb.compiler.extensions.JvmBloc

### ISSUE THREAD

**Issue by Sabirjan** [mamoe/mirai#731]
java.lang.IllegalStateException: The provided plugin net.mamoe.kjbb.compiler.extensions.JvmBlockingBridgeComponentRegistrar is not compatible with this version of compiler

打包jar时出错

**Comment by Him188** [comment]
请使用 Gradle 打包

**Comment by Sabirjan** [comment]
以前的老版本没有这个问题的，请问有没有参考文档。谢谢

**Comment by Him188** [comment]
不支持使用 IntelliJ 编译系统，需要用 Gradle jar 和 shadowJar 打包

**Comment by Sabirjan** [comment]
已 解决
谢谢
