### ISSUE TITLE
MessageEvent.reply() 报错

### ISSUE THREAD

**Issue by StarWishsama** [mamoe/mirai#732]
使用 MessageEvent.reply() 报错
提示 java.lang.VerifyError: Bad invokespecial instruction: interface method reference is in an indirect superinterface.

https://paste.ubuntu.com/p/XGFQCMXvKy/

#### 复现

使用 MessageEvent.reply() 方法

#### 版本
mirai: `2.0-M1 ` 

出现在堆栈中可能相关的类 [CommandExecutor](https://github.com/StarWishsama/Comet-Bot/blob/hoshimati/src/main/kotlin/io/github/starwishsama/comet/api/command/CommandExecutor.kt) [BiliBiliCommand](https://github.com/StarWishsama/Comet-Bot/blob/hoshimati/src/main/kotlin/io/github/starwishsama/comet/commands/chats/BiliBiliCommand.kt#L40)

**Comment by Him188** [comment]
我也遇到了，这是个非常有趣的编译问题

**Comment by Karlatemp** [comment]
请临时使用 `subject.sendMessage` 来临时解决问题

**Comment by Him188** [comment]
经测试，这不是 KJBB 导致的问题（删除 JvmBlockingBridge）后没有解决
