### ISSUE TITLE
2.0-M1-1 Maven导入出现问题 无法解析项目

### ISSUE THREAD

**Issue by Lin-XCC** [mamoe/mirai#739]
使用idea maven导入最新版的jar包出现无法解析问题。

        <dependency>
            <groupId>net.mamoe</groupId>
            <artifactId>mirai-core</artifactId>
            <version>2.0-M1-1</version>
        </dependency>
        <dependency>
            <groupId>net.mamoe</groupId>
            <artifactId>mirai-core-api</artifactId>
            <version>2.0-M1-1</version>
        </dependency>

maven报错

无法解析 org.jetbrains.kotlinx:kotlinx-serialization-json:1.0.1
无法解析 org.jetbrains.kotlinx:kotlinx-serialization-core:1.0.1

代码中也无法使用正常的jar导入

**Comment by Karlatemp** [comment]
#730

**Comment by Him188** [comment]
看文档看文档看文档看文档看文档看文档看文档看文档看文档看文档看文档看文档看文档看文档

https://github.com/mamoe/mirai/blob/dev/docs/ConfiguringProjects.md#b-%E4%BD%BF%E7%94%A8-maven

**Comment by IceCream-Open** [comment]
maven 错误的解析了 kotlin mpp 生成的 pom，强行要求 packaging 为 pom 的项目的 jar 文件，因为没有，所以下载失败。
不知道是 kotlin mpp 的问题，还是 maven 的问题。
引入依赖手动在名字后面加上 -jvm

**Comment by Him188** [comment]
> maven 错误的解析了 kotlin mpp 生成的 pom，强行要求 packaging 为 pom 的项目的 jar 文件，因为没有，所以下载失败。
> 不知道是 kotlin mpp 的问题，还是 maven 的问题。
> 引入依赖手动在名字后面加上 -jvm

Maven 本身就不支持这样的解析。Kotlin 在 Gradle 生成了 Gradle Metadata 因此可以解析
