### ISSUE TITLE
疑似不能监听消息事件（是 console 0.5.2 的问题吗？）

### ISSUE THREAD

**Issue by zhaodice** [mamoe/mirai#740]
经测试
BotOnlineEvent
GroupMemberEvent
MemberJoinEvent
可以在监听后有消息事件，但
MessageEvent
在监听后完全没有反应，FriendMessageEvent和GroupMessageEvent也貌似没有任何反应
我使用的版本是
2.0-M1-dev-4
console 0.5.2

**Comment by Him188** [comment]
2.0-M1-dev-4 不可能与 console 0.5.2 一起使用，请检查

**Comment by Him188** [comment]
提供日志

**Comment by zhaodice** [comment]
> 
> 
> 提供日志
我确实是在安卓端使用的2.0-M1-dev-4和console 0.5.2
编译没有遇到问题，正常编译了
运行时也没有报错信息，只是MessageEvent监听后没反应了而已
看起来应该是代码结构变化导致的不兼容.

**Comment by zhaodice** [comment]
我这边换成console 2.0-M1-1 看一下
