### ISSUE TITLE
新版本图片发送与链接查询以及bot消息撤回

### ISSUE THREAD

**Issue by Lin-XCC** [mamoe/mirai#741]
版本：2.0-M1-1
平台：java
1.如何发送图片 原先的uploadimage()已经更改 无法支持url或者inputstream 但是新的参数 ExternalImage在使用上遇到了困难。
2.如何撤回机器人的消息。根据messagesource.kt的描述。通过sendmessage()的返回值MessageReceipt可以撤回 但是java端的MessageReceipt无法调用recall方法
3.如何查看消息中的image链接，旧的用法bot.queryImageUrl()已经无法使用。在 变更说明中并未提到。
<!-- Mirai 已开通 Discussions, 请在 https://github.com/mamoe/mirai/discussions 提交问题>

**Comment by Him188** [comment]
变更说明有提到所有协议接口移动到了 IMirai，发送图片查看 net.mamoe.mirai.utils.SendMessageJvmKt （类似名称）
