### ISSUE TITLE
Unknown login result type: 239”

### ISSUE THREAD

**Issue by zhaodice** [mamoe/mirai#744]
报错信息：
[92m2020-12-20 18:17:05 I/Net 3403310837: Connected to server 42.81.169.46:8080[0m
 [0m2020-12-20 18:17:05 V/Net 3403310837: Send: wtlogin.login[0m
 [31m2020-12-20 18:17:05 E/Net 3403310837: Exception in NetworkHandler
 java.lang.IllegalStateException: Cannot find error message, unknown login result type: 239, TLVMap = {0x00000104(260)=41 6C 49 37 32 36 32 6A 72 31 6B 4B 31 66 53 7A 2B 63 6D 70 51 4E 74 6C 4A 79 37 61 42 6A 35 72 35 41 3D 3D, 0x00000174(372)=45 65 38 51 36 4C 71 68 62 4D 44 6F 63 6A 70 65 44 31 4A 56 77 48 7A 38 79 59 39 61 78 4D 38 35 73 71 53 69 30 6F 39 4A 78 37 4C 7A 36 75 76 53 75 4D 70 6C 43 4B 6C 72 36 72 78 78 76 75 6E 41 37 52 56 4A 6B 4C 4D 44 70 71 6C 6D 54 4C 56 32 48 63 37 32 54 4A 6F 7A 45 75 53 6D 72 61 48 42 67, 0x00000178(376)=00 00 00 0B 31 38 33 2A 2A 2A 2A 2A 2A 37 36 00 00 00 01 00 00 00 00, 0x00000179(377)=00 00, 0x0000017D(381)=00 02 00 00 00 01 00 33 68 74 74 70 73 3A 2F 2F 61 71 2E 71 71 2E 63 6F 6D 2F 63 6E 32 2F 6D 61 6E 61 67 65 2F 6D 6F 62 69 6C 65 5F 68 35 2F 6D 6F 62 69 6C 65 5F 69 6E 64 65 78, 0x00000402(1026)=71 71 59 70 3B 68 56 57, 0x00000403(1027)=55 55 40 50 40 62 2C 7D, 0x00000204(516)=68 74 74 70 73 3A 2F 2F 74 69 2E 71 71 2E 63 6F 6D 2F 73 61 66 65 2F 76 65 72 69 66 79 3F 5F 77 76 3D 32 26 5F 77 77 76 3D 31 32 38 26 75 69 6E 3D 33 34 30 33 33 31 30 38 33 37 26 73 69 67 3D 65 41 61 35 73 6A 73 5A 49 6A 55 47 34 70 51 6B 58 44 33 6D 63 6D 25 32 46 47 74 57 55 41 6D 49 74 6B 66 4F 35 79 30 69 42 31 70 6B 6B 78 44 77 44 41 41 4B 55 69 53 67 53 35 44 25 32 46 37 32 57 6A 4A 68 77 75 6A 6D 72 59 74 53 68 39 4D 55 79 65 6B 51 37 31 62 55 66 54 4F 4B 51 4B 33 57 38 59 58 63 63 31 56 55 75 25 32 42 63 70 4C 58 54 38 44 5A 37 77 59 39 49 41 6C 68 75 63 75 53 39 66 58 77 6D 45, 0x0000017E(382)=E4 BD A0 E6 AD A3 E5 9C A8 E4 B8 80 E5 8F B0 E6 96 B0 E8 AE BE E5 A4 87 E7 99 BB E5 BD 95 51 51 EF BC 8C E9 9C 80 E8 A6 81 E8 BF 9B E8 A1 8C E5 AE 89 E5 85 A8 E9 AA 8C E8 AF 81 0A E9 80 9A E8 BF 87 E5 90 8E E4 B8 8B E6 AC A1 E6 97 A0 E9 9C 80 E9 AA 8C E8 AF 81}
     at net.mamoe.mirai.internal.network.protocol.packet.login.WtLogin$Login.decode(WtLogin.kt:325)
     at net.mamoe.mirai.internal.network.protocol.packet.KnownPacketFactories.parseOicqResponse(PacketFactory.kt:609)
     at net.mamoe.mirai.internal.network.protocol.packet.KnownPacketFactories.handleIncomingPacket$mirai_core(PacketFactory.kt:280)
     at net.mamoe.mirai.internal.network.protocol.packet.KnownPacketFactories.parseIncomingPacket(PacketFactory.kt:232)
     at net.mamoe.mirai.internal.network.QQAndroidBotNetworkHandler.generifiedParsePacket(QQAndroidBotNetworkHandler.kt:467)
     at net.mamoe.mirai.internal.network.QQAndroidBotNetworkHandler.parsePacket(QQAndroidBotNetworkHandler.kt:462)
     at net.mamoe.mirai.internal.network.QQAndroidBotNetworkHandler$parsePacketAsync$1.invokeSuspend(QQAndroidBotNetworkHandler.kt:445)
     at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
     at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
     at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
     at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:738)
     at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
     at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
 [0m
版本：2.0-M1-dev-4
平台：android 5.1

**Comment by zhaodice** [comment]
然后这个log会不停反复刷，间隔几秒

**Comment by Karlatemp** [comment]
Use `2.0-M1-1`

**Comment by zhaodice** [comment]
@Karlatemp 
我又改成了
def CORE_VERSION = "2.0-M1-1"
重新编译运行后依然是
Cannot find error message, unknown login result type: 239


12-20 18:26:55.292 24622-24738/org.mirai.zhao.dice I/System.out: [92m2020-12-20 18:26:55 I/Net 3403310837: Connected to server 42.81.169.46:8080[0m
12-20 18:26:55.351 24622-24739/org.mirai.zhao.dice I/System.out: [0m2020-12-20 18:26:55 V/Net 3403310837: Send: wtlogin.login[0m
12-20 18:26:55.890 24622-24739/org.mirai.zhao.dice I/System.out: [31m2020-12-20 18:26:55 E/Net 3403310837: Exception in NetworkHandler
12-20 18:26:55.891 24622-24739/org.mirai.zhao.dice I/System.out: java.lang.IllegalStateException: Cannot find error message, unknown login result type: 239, TLVMap = {0x00000104(260)=41 72 79 4A 4D 37 78 72 54 54 31 31 70 47 46 72 4B 37 47 36 4F 30 6C 55 36 34 55 6F 37 6D 35 77 53 77 3D 3D, 0x00000174(372)=45 41 7A 70 72 36 64 31 6E 69 35 73 5A 5A 47 7A 4E 74 32 6B 2D 54 57 54 75 57 53 66 59 53 63 55 5A 48 42 41 6F 65 4E 6F 61 62 32 53 5F 39 36 37 56 79 38 44 67 74 74 51 72 49 76 43 71 52 79 4E 75 57 57 42 4B 6F 70 71 69 31 5F 52 50 63 50 79 72 34 57 64 34 30 38 35 43 5F 34 39 71 63 58 48 47, 0x00000178(376)=00 00 00 0B 31 38 33 2A 2A 2A 2A 2A 2A 37 36 00 00 00 01 00 00 00 00, 0x00000179(377)=00 00, 0x0000017D(381)=00 02 00 00 00 01 00 33 68 74 74 70 73 3A 2F 2F 61 71 2E 71 71 2E 63 6F 6D 2F 63 6E 32 2F 6D 61 6E 61 67 65 2F 6D 6F 62 69 6C 65 5F 68 35 2F 6D 6F 62 69 6C 65 5F 69 6E 64 65 78, 0x00000402(1026)=38 36 54 37 6A 46 6E 37, 0x00000403(1027)=78 28 28 78 7D 75 62 36, 0x00000204(516)=68 74 74 70 73 3A 2F 2F 74 69 2E 71 71 2E 63 6F 6D 2F 73 61 66 65 2F 76 65 72 69 66 79 3F 5F 77 76 3D 32 26 5F 77 77 76 3D 31 32 38 26 75 69 6E 3D 33 34 30 33 33 31 30 38 33 37 26 73 69 67 3D 4E 4A 4C 6D 4E 57 6A 57 55 32 37 45 7A 71 4B 51 45 56 30 6B 46 4E 79 39 72 53 25 32 42 4A 6B 30 49 6E 56 37 67 61 6D 75 6D 77 4E 6A 6C 33 61 54 50 57 65 66 25 32 42 4D 55 39 6B 55 57 52 6F 6B 25 32 46 57 4C 77 66 44 56 69 52 76 64 49 70 73 35 47 44 25 32 46 76 4E 66 39 48 79 75 4D 55 74 63 67 36 4B 52 67 67 46 30 33 71 79 50 65 42 4C 63 58 6E 34 59 63 6D 66 4B 25 32 46 39 44 51 65 4D 59 54 50 66 75 34 48 4A 52, 0x0000017E(382)=E4 BD A0 E6 AD A3 E5 9C A8 E4 B8 80 E5 8F B0 E6 96 B0 E8 AE BE E5 A4 87 E7 99 BB E5 BD 95 51 51 EF BC 8C E9 9C 80 E8 A6 81 E8 BF 9B E8 A1 8C E5 AE 89 E5 85 A8 E9 AA 8C E8 AF 81 0A E9 80 9A E8 BF 87 E5 90 8E E4 B8 8B E6 AC A1 E6 97 A0 E9 9C 80 E9 AA 8C E8 AF 81}
12-20 18:26:55.891 24622-24739/org.mirai.zhao.dice I/System.out:     at net.mamoe.mirai.internal.network.protocol.packet.login.WtLogin$Login.decode(WtLogin.kt:331)
12-20 18:26:55.891 24622-24739/org.mirai.zhao.dice I/System.out:     at net.mamoe.mirai.internal.network.protocol.packet.KnownPacketFactories.parseOicqResponse(PacketFactory.kt:609)
12-20 18:26:55.891 24622-24739/org.mirai.zhao.dice I/System.out:     at net.mamoe.mirai.internal.network.protocol.packet.KnownPacketFactories.handleIncomingPacket$mirai_core(PacketFactory.kt:280)
12-20 18:26:55.891 24622-24739/org.mirai.zhao.dice I/System.out:     at net.mamoe.mirai.internal.network.protocol.packet.KnownPacketFactories.parseIncomingPacket(PacketFactory.kt:232)
12-20 18:26:55.891 24622-24739/org.mirai.zhao.dice I/System.out:     at net.mamoe.mirai.internal.network.QQAndroidBotNetworkHandler.generifiedParsePacket(QQAndroidBotNetworkHandler.kt:467)
12-20 18:26:55.891 24622-24739/org.mirai.zhao.dice I/System.out:     at net.mamoe.mirai.internal.network.QQAndroidBotNetworkHandler.parsePacket(QQAndroidBotNetworkHandler.kt:462)
12-20 18:26:55.891 24622-24739/org.mirai.zhao.dice I/System.out:     at net.mamoe.mirai.internal.network.QQAndroidBotNetworkHandler$parsePacketAsync$1.invokeSuspend(QQAndroidBotNetworkHandler.kt:445)
12-20 18:26:55.891 24622-24739/org.mirai.zhao.dice I/System.out:     at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
12-20 18:26:55.891 24622-24739/org.mirai.zhao.dice I/System.out:     at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
12-20 18:26:55.891 24622-24739/org.mirai.zhao.dice I/System.out:     at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
12-20 18:26:55.891 24622-24739/org.mirai.zhao.dice I/System.out:     at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:738)
12-20 18:26:55.891 24622-24739/org.mirai.zhao.dice I/System.out:     at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
12-20 18:26:55.891 24622-24739/org.mirai.zhao.dice I/System.out:     at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
12-20 18:26:55.891 24622-24739/org.mirai.zhao.dice I/System.out: [0m

**Comment by Him188** [comment]
41 72 79 4A 4D 37 78 72 54 54 31 31 70 47 46 72 4B 37 47 36 4F 30 6C 55 36 34 55 6F 37 6D 35 77 53 77 3D 3D 45 41 7A 70 72 36 64 31 6E 69 35 73 5A 5A 47 7A 4E 74 32 6B 2D 54 57 54 75 57 53 66 59 53 63 55 5A 48 42 41 6F 65 4E 6F 61 62 32 53 5F 39 36 37 56 79 38 44 67 74 74 51 72 49 76 43 71 52 79 4E 75 57 57 42 4B 6F 70 71 69 31 5F 52 50 63 50 79 72 34 57 64 34 30 38 35 43 5F 34 39 71 63 58 48 47 00 00 00 0B 31 38 33 2A 2A 2A 2A 2A 2A 37 36 00 00 00 01 00 00 00 00 00 02 00 00 00 01 00 33 68 74 74 70 73 3A 2F 2F 61 71 2E 71 71 2E 63 6F 6D 2F 63 6E 32 2F 6D 61 6E 61 67 65 2F 6D 6F 62 69 6C 65 5F 68 35 2F 6D 6F 62 69 6C 65 5F 69 6E 64 65 78 38 36 54 37 6A 46 6E 37 78 28 28 78 7D 75 62 36 68 74 74 70 73 3A 2F 2F 74 69 2E 71 71 2E 63 6F 6D 2F 73 61 66 65 2F 76 65 72 69 66 79 3F 5F 77 76 3D 32 26 5F 77 77 76 3D 31 32 38 26 75 69 6E 3D 33 34 30 33 33 31 30 38 33 37 26 73 69 67 3D 4E 4A 4C 6D 4E 57 6A 57 55 32 37 45 7A 71 4B 51 45 56 30 6B 46 4E 79 39 72 53 25 32 42 4A 6B 30 49 6E 56 37 67 61 6D 75 6D 77 4E 6A 6C 33 61 54 50 57 65 66 25 32 42 4D 55 39 6B 55 57 52 6F 6B 25 32 46 57 4C 77 66 44 56 69 52 76 64 49 70 73 35 47 44 25 32 46 76 4E 66 39 48 79 75 4D 55 74 63 67 36 4B 52 67 67 46 30 33 71 79 50 65 42 4C 63 58 6E 34 59 63 6D 66 4B 25 32 46 39 44 51 65 4D 59 54 50 66 75 34 48 4A 52 E4 BD A0 E6 AD A3 E5 9C A8 E4 B8 80 E5 8F B0 E6 96 B0 E8 AE BE E5 A4 87 E7 99 BB E5 BD 95 51 51 EF BC 8C E9 9C 80 E8 A6 81 E8 BF 9B E8 A1 8C E5 AE 89 E5 85 A8 E9 AA 8C E8 AF 81 0A E9 80 9A E8 BF 87 E5 90 8E E4 B8 8B E6 AC A1 E6 97 A0 E9 9C 80 E9 AA 8C E8 AF 81

**Comment by Him188** [comment]
AryJM7xrTT11pGFrK7G6O0lU64Uo7m5wSw==EAzpr6d1ni5sZZGzNt2k-TWTuWSfYScUZHBAoeNoab2S_967Vy8DgttQrIvCqRyNuWWBKopqi1_RPcPyr4Wd4085C_49qcXHG183******763https://aq.qq.com/cn2/manage/mobile_h5/mobile_index86T7jFn7x((x}ub6https://ti.qq.com/safe/verify?_wv=2&_wwv=128&uin=3403310837&sig=NJLmNWjWU27EzqKQEV0kFNy9rS%2BJk0InV7gamumwNjl3aTPWef%2BMU9kUWRok%2FWLwfDViRvdIps5GD%2FvNf9HyuMUtcg6KRggF03qyPeBLcXn4YcmfK%2F9DQeMYTPfu4HJR你正在一台新设备登录QQ，需要进行安全验证
通过后下次无需验证

**Comment by Him188** [comment]
备注：PAD 协议

**Comment by lc6a** [comment]
我也出现过这种报错，在手机上手动登录该账号并关掉设备验证后，再运行就没有问题了。
