### ISSUE TITLE
TimeoutCancellationException?

### ISSUE THREAD

**Issue by null-su** [mamoe/mirai#747]
openJDK12 使用 2.0m1-1 TimeoutCancellationException

`2020-12-21 14:44:37 I/main: Starting mirai-console...`
`2020-12-21 14:44:37 I/main: Backend: version 2.0-M1-1, built on 2020-12-19 23:26:13.`
`2020-12-21 14:44:37 I/main: Frontend Terminal: version 2.0-M1-1, provided by Mamoe Technologies`
`2020-12-21 14:44:37 I/main: Prepared built-in commands: autoLogin, help, login, permission, status, stop`
`2020-12-21 14:44:37 I/main: 0 plugin(s) enabled.`
`2020-12-21 14:44:37 I/Mirai: Mirai 正在使用桌面环境. 如遇到验证码将会弹出对话框. 可添加 JVM 属性 `mirai.no-desktop` 以关闭.`
`2020-12-21 14:44:37 I/Mirai: Mirai is using desktop. Captcha will be thrown by window popup. You can add `mirai.no-desktop` to JVM properties (-Dmirai.no-desktop) to disable it.`
`2020-12-21 14:44:37 I/main: Auto-login ******`
`2020-12-21 14:44:38 I/Bot.******: Logging in...`
`2020-12-21 14:44:53 W/Bot.******: kotlinx.coroutines.TimeoutCancellationException: Timed out waiting for 5000 ms`
`kotlinx.coroutines.TimeoutCancellationException: Timed out waiting for 5000 ms`
`        at kotlinx.coroutines.TimeoutKt.TimeoutCancellationException(Timeout.kt:186)`
`        at kotlinx.coroutines.TimeoutCoroutine.run(Timeout.kt:156)`
`        at kotlinx.coroutines.EventLoopImplBase$DelayedRunnableTask.run(EventLoop.common.kt:497)`
`        at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:274)`
`        at kotlinx.coroutines.DefaultExecutor.run(DefaultExecutor.kt:69)`
`        at java.base/java.lang.Thread.run(Thread.java:835)`
` `
`2020-12-21 14:44:53 I/Bot.******: Connection lost, retrying login`
`2020-12-21 14:44:53 W/Bot.******: java.lang.IllegalStateException: network channel is closed`
`java.lang.IllegalStateException: network channel is closed`
`        at net.mamoe.mirai.internal.network.QQAndroidBotNetworkHandler.sendAndExpect(QQAndroidBotNetworkHandler.kt:632)`
`        at net.mamoe.mirai.internal.network.QQAndroidBotNetworkHandler.sendAndExpect$default(QQAndroidBotNetworkHandler.kt:626)`
`        at net.mamoe.mirai.internal.network.QQAndroidBotNetworkHandler.closeEverythingAndRelogin(QQAndroidBotNetworkHandler.kt:155)`
`        at net.mamoe.mirai.internal.network.QQAndroidBotNetworkHandler$closeEverythingAndRelogin$1.invokeSuspend(QQAndroidBotNetworkHandler.kt)`
`        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)`
`        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)`
`        at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:274)`
`        at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:84)`
`        at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)`
`        at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)`
`        at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38)`
`        at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)`
`        at net.mamoe.mirai.console.internal.MiraiConsoleImplementationBridge.doStart$mirai_console(MiraiConsoleImplementationBridge.kt:215)`
`        at net.mamoe.mirai.console.MiraiConsoleImplementation$Companion.start(MiraiConsoleImplementation.kt:209)`
`        at net.mamoe.mirai.console.terminal.MiraiConsoleTerminalLoader.startAsDaemon(MiraiConsoleTerminalLoader.kt:153)`
`        at net.mamoe.mirai.console.terminal.MiraiConsoleTerminalLoader.startAsDaemon$default(MiraiConsoleTerminalLoader.kt:152)`
`        at net.mamoe.mirai.console.terminal.MiraiConsoleTerminalLoader.main(MiraiConsoleTerminalLoader.kt:48)`

**Comment by null-su** [comment]
`文件: libs\mirai-console-2.0-M1-1-all.jar`
`MD5: 830D1BA6B52DDC333FEAB74C01512F25`
` `
`文件: libs\mirai-console-compiler-common-2.0-M1-1-all.jar`
`MD5: CAA3993D6172546E627EF61BD19D66D8`
` `
`文件: libs\mirai-console-gradle-2.0-M1-1-all.jar`
`MD5: DBC5960D1938BD8C8C1BBF0824EECDBB`
` `
`文件: libs\mirai-console-intellij-2.0-M1-1-all.jar`
`大小: 3621591 字节`
`修改时间: 2020年12月21日, 14:33:46`
`MD5: 70DA588547848D6B886ECBC9177551FB`
` `
`文件: libs\mirai-console-terminal-2.0-M1-1-all.jar`
`MD5: B96C051F1DC296380637CD57434F933D`
` `
`文件: libs\mirai-core-all-2.0-M1-1-all.jar`
`MD5: ABD92FFDCD4A7C9F61E4D233CC1E6C10`
` `

**Comment by null-su** [comment]
用旧版 2.0m1 提示一键登录 应该不是我网不好吧

**Comment by Him188** [comment]
尝试多次重启

**Comment by null-su** [comment]
> 尝试多次重启

无效，问题依旧

**Comment by null-su** [comment]
[#717#issuecomment-748632170](https://github.com/mamoe/mirai/issues/717#issuecomment-748632170) 和我遇到相同问题

**Comment by null-su** [comment]
> 尝试多次重启

使用常用QQ登录超时异常，随意输入一个9位QQ，提示需要滑动验证码
