### ISSUE TITLE
Miraiqq机器人接受到的企业QQ发来的消息会分段

### ISSUE THREAD

**Issue by jinxu577620** [mamoe/mirai#750]
![image](https://user-images.githubusercontent.com/39151653/102842595-491b7a80-4442-11eb-9ade-cf5dbce9de5a.png)

<!-- Mirai 已开通 Discussions, 请在 https://github.com/mamoe/mirai/discussions 提交问题>

**Comment by Him188** [comment]
2.0-M2 已支持分片消息

**Comment by Him188** [comment]
#440

**Comment by jinxu577620** [comment]
你好，大佬，我这个普通qq发送长消息没问题，但是企业QQ会出现分片问题，另外麻烦问一下，大佬那个12.16号出现的更新协议版本的那个问题，啥时候可以打一个maven包呢，我现在本地新账号等录不成功
