### ISSUE TITLE
图片上传的 Java API

### ISSUE THREAD

**Issue by sumuqiu222** [mamoe/mirai#751]
之前的版本 Image image = group.uploadImage(new URL(“url地址”));

现在的版本？Image image = group.uploadImage(new ExternalImage(new DeferredReusableInput()));
我没搞明白啊 有人能解答下吗

**Comment by sandtechnology** [comment]
`ExternalImageJvmKt.toExternalImage(???)`
详细用例可见：https://github.com/sandtechnology/DantuiHelper/blob/0f84a5e36841b29bfc264ed6a996cd1ac67b5ab2/src/main/java/sandtechnology/holder/WriteOnlyMessage.java#L189
当然你可以传inputstream，见IDE提示
