### ISSUE TITLE
新版本的定时撤回接口有实现么？如何调用？

### ISSUE THREAD

**Issue by Lin-XCC** [mamoe/mirai#755]
原先的group().sendmessage().recallin()已经无法使用。
新的撤回MessageSource.recall(source);或者MiraiImpl.INSTANCE.recallMessage()好像都不支持定时撤回。

<!-- Mirai 已开通 Discussions, 请在 https://github.com/mamoe/mirai/discussions 提交问题>

**Comment by Karlatemp** [comment]
可以异步撤回，并非必须马上撤回，建议搜索java延时任务

**Comment by Lin-XCC** [comment]
> 可以异步撤回，并非必须马上撤回，建议搜索java延时任务
我的意思是目前版本有内部实现的接口么

**Comment by Him188** [comment]
已经添加在 2.0-M2-dev-2
