### ISSUE TITLE
有没有可能支持PCQQ

### ISSUE THREAD

**Issue by ZQiu233** [mamoe/mirai#76]
以后有没有可能支持PCQQ的协议呢？
或者现在有没有这样的计划呢？

**Comment by uebian** [comment]
目前已经支持过了，于timpc分支中

**Comment by Him188** [comment]
PC功能少，分析耗时，不划算

**Comment by thirstyzebra** [comment]
安卓 qq 相关协议可以查看 https://github.com/botmm/botmm  docs 目录

**Comment by cxy654849388** [comment]
后续是否有考虑重新支持pc协议？毕竟pc协议有些功能是android协议没有的，比如群名片修改通知

**Comment by Him188** [comment]
没有
