### ISSUE TITLE
无法登录

### ISSUE THREAD

**Issue by 2659494057** [mamoe/mirai#772]
mirai-console-terminal:2.0-M2-dev-4-all
mirai-console:2.0-M2-dev-4-all
mirai-core-all:2.0-M2-dev-4-all
mirai-core-qqandroid-1.3.3

在AutoLogin.yml中添加账户并设置ANDROID_PAD，登录bot不会提示滑动验证失败了。会提示输入验证码，验证码提交后报错，前几次报错环境异常，之后一直报错版本过低，无法完成登录

**Comment by lliioollcn** [comment]
请在宿主机使用旧版（1.3.3及以下）登录一段时间后复制device.json到新版重新登录

**Comment by 2659494057** [comment]
> 请在宿主机使用旧版（1.3.3及以下）登录一段时间后复制device.json到新版重新登录

在宿主机上使用MiraiAndroid登录，会提示版本过低，MiraiAndroid是最新的，无法获取device.json

**Comment by Him188** [comment]
登录有问题是因为服务器正在大力推广滑块验证码而这很难处理。

现在遇到滑块验证码 1.x 和 2.0-M1 都不能正确回复，会导致登录失败。

部分账号可以跳过滑块验证码直接重新登录，服务器就会要求图片验证码。于是 mirai 现在默认直接跳过滑块验证码 （2.0-M2-dev-4）。

现在 mirai 已经实现了滑块的处理，使用 2.0-M2-dev-9 和 https://github.com/project-mirai/mirai-login-solver-selenium 。由于步骤复杂，文档还在编写中，2.0-M2 会提供方案。

**Comment by 2659494057** [comment]
> 登录有问题是因为服务器正在大力推广滑块验证码而这很难处理。
> 
> 现在遇到滑块验证码 1.x 和 2.0-M1 都不能正确回复，会导致登录失败。
> 
> 部分账号可以跳过滑块验证码直接重新登录，服务器就会要求图片验证码。于是 mirai 现在默认直接跳过滑块验证码 （2.0-M2-dev-4）。
> 
> 现在 mirai 已经实现了滑块的处理，使用 2.0-M2-dev-9 和 https://github.com/project-mirai/mirai-login-solver-selenium 。由于步骤复杂，文档还在编写中，2.0-M2 会提供方案。

OK

**Comment by Him188** [comment]
https://github.com/project-mirai/mirai-login-solver-selenium 文档已更新。更详细的文档会在今日 2.0-M2 发布后更新

**Comment by dragon0629** [comment]
emmmm ttps://bintray.com/karlatemp/mirai/mirai-login-solver-selenium/1.0-dev-6  这边下载失败，提示404？？

**Comment by Him188** [comment]
> emmmm ttps://bintray.com/karlatemp/mirai/mirai-login-solver-selenium/1.0-dev-6 这边下载失败，提示404？？

https://bintray.com/beta/#/karlatemp/mirai/mirai-login-solver-selenium/1.0-dev-6?tab=overview

**Comment by She-yh** [comment]
cmd运行mcl时提示Error: Unable to access jarfile mcl.jar，T T
