### ISSUE TITLE
HTTP API的QuoteMessage序列化为JSON失败

### ISSUE THREAD

**Issue by ryoii** [mamoe/mirai#79]

**Comment by Chenwe-i-lin** [comment]
是不是遇上了回复就出Error的问题? 文档里缺一个叫 `Unknown` 的 Message, 自己实现一个就好:

``` python
class UnknownMessage(BaseMessage):
    __express_fields__ = ["type", "text"]
    __static_fields__ = ["type", "text"]

    type = "Unknown"
    text: str = "未知消息类型"

    def toString(self):
        return ""
```

**Comment by Chenwe-i-lin** [comment]
#54

**Comment by ryoii** [comment]
> 是不是遇上了回复就出Error的问题? 文档里缺一个叫 `Unknown` 的 Message, 自己实现一个就好:
> 
> ```python
> class UnknownMessage(BaseMessage):
>     __express_fields__ = ["type", "text"]
>     __static_fields__ = ["type", "text"]
> 
>     type = "Unknown"
>     text: str = "未知消息类型"
> 
>     def toString(self):
>         return ""
> ```

可以自己实现，基本不会出现type为Unknown的情况
