### ISSUE TITLE
掉线重连时闪退，并且无提示信息

### ISSUE THREAD

**Issue by lc6a** [mamoe/mirai#796]
登录后大概10几分钟会掉线重连，重连时会**毫无提示**的退出，退出代码0。
经过仔细调试，退出时运行到mirai-core-jvm-2.0-M1-1.jar的internal/utils/PlatformSocket.kt的94行，socket.getInputStream()。
此时socket的参数是42.81.172.81:80。

```
2020-12-31 18:09:57 I/Bot xxx: Connection lost, retrying login
2020-12-31 18:09:57 I/Bot xxx: Connected to server 42.81.172.81:80
2020-12-31 18:09:57 I/Bot xxx: Send: Wtlogin.login

Process finished with exit code 0
```

#### 复现

使用ANDROID_PAD协议登录后挂超过10分钟掉线重连。

#### 版本
mirai: ` 2.0-M1-1` 

由于没有输出提示信息，程序也没有运行结束，我无法理解是什么原因能够导致毫无异常提示直接在运行中途结束程序，以下是我的猜想：
1. socket连接失败，但应该会抛出异常，在调试步进下不可能无法得知异常信息。
2. withContext(Dispatchers.IO) 这个导致退出，协程我不清楚，但不抛出异常，退出代码0也太不合常理了。

我尝试过测试代码使用反射单独调用这个connect方法，传入相同的参数，却能够正常运行，以下是测试代码：
```
    val clazz = Class.forName("net.mamoe.mirai.internal.utils.PlatformSocket").kotlin  //找到这个类
    val obj = clazz.createInstance()                            //new一个实例对象
    val connect = clazz.declaredFunctions.filter { it.name == "connect" }[0]  //找到connect成员函数
    connect.callSuspend(obj, "42.81.172.81", 80)     // obj.connect("42.81.172.81", 80)
    delay(1000)
    println("ok")
```
输出以下内容（看起来应该没有出现机器人运行时出现的问题）：
```
ok

Process finished with exit code 0
```

**Comment by Him188** [comment]
请问是每次重连都一定发生吗？
尝试更新 2.0-M2

**Comment by tianhan1998** [comment]
有同问题+1

**Comment by lc6a** [comment]
> 请问是每次重连都一定发生吗？
> 尝试更新 2.0-M2
在2.0-M2-2仍然发生，重连必定发生

**Comment by Him188** [comment]
请提供完整代码

**Comment by Him188** [comment]
我这里测试正常

**Comment by lc6a** [comment]
这是测试代码：
```
    val bot= BotFactory.newBot(qqId, password){
        fileBasedDeviceInfo("dev${qqId}.json")
        protocol = BotConfiguration.MiraiProtocol.ANDROID_PAD
    }.alsoLogin()
    bot.eventChannel.subscribeAlways<GroupMessageEvent> {
        println(it.message.content)
    }
```

这是日志：
```
2021-01-01 19:51:56 V/Net xxx: Send: Heartbeat.Alive
2021-01-01 19:51:56 V/Net xxx Recv: Heartbeat.Alive.Response
2021-01-01 19:55:12 I/Bot xxx: Connection lost, retrying login
2021-01-01 19:55:12 I/Net xxx: Connected to server 42.81.172.81:80
2021-01-01 19:55:12 V/Net xxx: Send: wtlogin.login

Process finished with exit code 0
```

这是gradle kts:
```
import org.jetbrains.kotlin.gradle.tasks.KotlinCompile

plugins {
    kotlin("jvm") version "1.4.21"
    kotlin("kapt") version "1.4.21"
    id("org.springframework.boot") version "2.3.6.RELEASE"
    id("io.spring.dependency-management") version "1.0.10.RELEASE"
    java
}

group = "com.lc"
version = "1.0"

repositories {
    mavenLocal()
    mavenCentral()
    jcenter()
}

dependencies {
    testImplementation(kotlin("test-junit"))
    implementation("net.mamoe:mirai-core:2.0-M2-2")
    implementation("org.jetbrains.kotlin:kotlin-reflect:1.4.10")
    implementation("com.github.salomonbrys.kotson:kotson:2.5.0")
    implementation("org.mybatis.spring.boot:mybatis-spring-boot-starter:2.1.4")
    runtimeOnly("mysql:mysql-connector-java")
}


tasks.withType<KotlinCompile>() {
    kotlinOptions.jvmTarget = "1.8"
}

tasks.withType<JavaCompile> {
    options.encoding = "UTF-8"
}
```

**Comment by sandtechnology** [comment]
> 
> 
> 这是测试代码：
> 
> ```
>     val bot= BotFactory.newBot(qqId, password){
>         fileBasedDeviceInfo("dev${qqId}.json")
>         protocol = BotConfiguration.MiraiProtocol.ANDROID_PAD
>     }.alsoLogin()
>     bot.eventChannel.subscribeAlways<GroupMessageEvent> {
>         println(it.message.content)
>     }
> ```
> 
> 这是日志：
> 
> ```
> 2021-01-01 19:51:56 V/Net xxx: Send: Heartbeat.Alive
> 2021-01-01 19:51:56 V/Net xxx Recv: Heartbeat.Alive.Response
> 2021-01-01 19:55:12 I/Bot xxx: Connection lost, retrying login
> 2021-01-01 19:55:12 I/Net xxx: Connected to server 42.81.172.81:80
> 2021-01-01 19:55:12 V/Net xxx: Send: wtlogin.login
> 
> Process finished with exit code 0
> ```
> 
> 这是gradle kts:
> 
> ```
> import org.jetbrains.kotlin.gradle.tasks.KotlinCompile
> 
> plugins {
>     kotlin("jvm") version "1.4.21"
>     kotlin("kapt") version "1.4.21"
>     id("org.springframework.boot") version "2.3.6.RELEASE"
>     id("io.spring.dependency-management") version "1.0.10.RELEASE"
>     java
> }
> 
> group = "com.lc"
> version = "1.0"
> 
> repositories {
>     mavenLocal()
>     mavenCentral()
>     jcenter()
> }
> 
> dependencies {
>     testImplementation(kotlin("test-junit"))
>     implementation("net.mamoe:mirai-core:2.0-M2-2")
>     implementation("org.jetbrains.kotlin:kotlin-reflect:1.4.10")
>     implementation("com.github.salomonbrys.kotson:kotson:2.5.0")
>     implementation("org.mybatis.spring.boot:mybatis-spring-boot-starter:2.1.4")
>     runtimeOnly("mysql:mysql-connector-java")
> }
> 
> 
> tasks.withType<KotlinCompile>() {
>     kotlinOptions.jvmTarget = "1.8"
> }
> 
> tasks.withType<JavaCompile> {
>     options.encoding = "UTF-8"
> }
> ```
bot.join()?

**Comment by Karlatemp** [comment]
在程序末尾添加 `bot.join()`

**Comment by lc6a** [comment]
原来是主线程趁机退出了，谢谢各位，是我大意了
