### ISSUE TITLE
图片一些发出图裂

### ISSUE THREAD

**Issue by lliioollcn** [mamoe/mirai#797]
一些图片可以发送，一些发出来图裂
在本地查看图片没问题
![Screenshot_20201231_212326_com tencent mobileqq](https://user-images.githubusercontent.com/44719954/103412194-e8f9a680-4bae-11eb-882d-30ec9cd1959b.jpg)

**Comment by lliioollcn** [comment]
补充：在刚登录时可以正常发出第一张图片，其他的就会图裂
![图片](https://user-images.githubusercontent.com/44719954/103412323-8a80f800-4baf-11eb-8195-f0b29a7f7e10.png)

**Comment by lliioollcn** [comment]
估计是上传失败，因为在大号发出去之后小号就可以正常显示了

**Comment by tianhan1998** [comment]
有同问题+1 2.0-M2 我把图片缩小到20Kb左右就可以一次成功

**Comment by Him188** [comment]
请提供版本号，并尝试 2.0-M1 和 2.0-M2

**Comment by I-love-study** [comment]
我在使用mirai 2.0-M2-2的时候这个问题仍然存在(使用mirai-api-http 1.9.5+graia(python sdk))
并且我发现机器人发送的图片下载地址(http://gchat.qpic.cn/gchatpic_new/...)的连接会显示404Not found

**Comment by I-love-study** [comment]
![a](https://user-images.githubusercontent.com/39652142/103625556-1c08b500-4f76-11eb-8aea-cf15f5232d03.jpg)
使用Python的PIL绘制
不知道是mah的问题还是mirai的问题

**Comment by I-love-study** [comment]
> > 我在使用mirai 2.0-M2-2的时候这个问题仍然存在(使用mirai-api-http 1.9.5+graia(python sdk))
> > 并且我发现机器人发送的图片下载地址([http://gchat.qpic.cn/gchatpic_new/...)的连接会显示404Not](http://gchat.qpic.cn/gchatpic_new/...)%E7%9A%84%E8%BF%9E%E6%8E%A5%E4%BC%9A%E6%98%BE%E7%A4%BA404Not) found
> 
> 经测试大图已经可以发送了，请提供原图片以供测试

突然发现在使用2.0-RC-dev-1解决了这个问题
我谢罪没看到发了dev版本😂，sorry
