### ISSUE TITLE
无法登录

### ISSUE THREAD

**Issue by lvyitian** [mamoe/mirai#799]
见：[https://github.com/mamoe/mirai/issues/798](https://github.com/mamoe/mirai/issues/798)

**Comment by lvyitian** [comment]
我不加qqandroid的话它会找不到BotFactory，在maven仓库qqandroid最新只有1.3.3

**Comment by Him188** [comment]
看文档看文档看文档看文档看文档看文档看文档看文档看文档看文档看文档看文档看文档看文档看文档看文档看文档看文档看文档看文档看文档看文档看文档看文档看文档看文档看文档看文档看文档看文档看文档看文档看文档看文档看文档看文档看文档看文档看文档看文档看文档看文档看文档看文档看文档看文档看文档看文档看文档看文档看文档看文档看文档看文档看文档看文档看文档看文档看文档看文档看文档看文档看文档看文档看文档看文档看文档看文档看文档看文档看文档看文档看文档看文档看文档看文档看文档看文档看文档看文档看文档看文档看文档看文档看文档看文档看文档看文档看文档看文档看文档看文档看文档看文档看文档看文档看文档看文档看文档看文档看文档看文档看文档看文档看文档看文档看文档看文档看文档看文档看文档看文档看文档看文档看文档看文档看文档看文档看文档看文档看文档看文档看文档看文档看文档看文档看文档看文档看文档看文档


我为什么要写那么文档啊，你为什么不看啊

**Comment by lvyitian** [comment]
> 看文档看文档看文档看文档看文档看文档看文档看文档看文档看文档看文档看文档看文档看文档看文档看文档看文档看文档看文档看文档看文档看文档看文档看文档看文档看文档看文档看文档看文档看文档看文档看文档看文档看文档看文档看文档看文档看文档看文档看文档看文档看文档看文档看文档看文档看文档看文档看文档看文档看文档看文档看文档看文档看文档看文档看文档看文档看文档看文档看文档看文档看文档看文档看文档看文档看文档看文档看文档看文档看文档看文档看文档看文档看文档看文档看文档看文档看文档看文档看文档看文档看文档看文档看文档看文档看文档看文档看文档看文档看文档看文档看文档看文档看文档看文档看文档看文档看文档看文档看文档看文档看文档看文档看文档看文档看文档看文档看文档看文档看文档看文档看文档看文档看文档看文档看文档看文档看文档看文档看文档看文档看文档看文档看文档看文档看文档看文档看文档看文档看文档
> 
> 我为什么要写那么文档啊，你为什么不看啊

您让我看哪呢

**Comment by lvyitian** [comment]
> 看文档看文档看文档看文档看文档看文档看文档看文档看文档看文档看文档看文档看文档看文档看文档看文档看文档看文档看文档看文档看文档看文档看文档看文档看文档看文档看文档看文档看文档看文档看文档看文档看文档看文档看文档看文档看文档看文档看文档看文档看文档看文档看文档看文档看文档看文档看文档看文档看文档看文档看文档看文档看文档看文档看文档看文档看文档看文档看文档看文档看文档看文档看文档看文档看文档看文档看文档看文档看文档看文档看文档看文档看文档看文档看文档看文档看文档看文档看文档看文档看文档看文档看文档看文档看文档看文档看文档看文档看文档看文档看文档看文档看文档看文档看文档看文档看文档看文档看文档看文档看文档看文档看文档看文档看文档看文档看文档看文档看文档看文档看文档看文档看文档看文档看文档看文档看文档看文档看文档看文档看文档看文档看文档看文档看文档看文档看文档看文档看文档看文档
> 
> 我为什么要写那么文档啊，你为什么不看啊

我看了啊，有个什么用，我完全按照上面操作也没有任何用，您看了我的描述了没

**Comment by Him188** [comment]
我来教你如何阅读文档

**Comment by Him188** [comment]
但凡你稍微看一下文档：
![Screenshot_2021-01-01-14-02-24-340_com android chrome](https://user-images.githubusercontent.com/12100985/103434306-7e8e4800-4c3a-11eb-9614-45d521a60a50.jpg)
![Screenshot_2021-01-01-14-02-41-040_com android chrome](https://user-images.githubusercontent.com/12100985/103434307-83eb9280-4c3a-11eb-8477-4fbca162393f.jpg)

你也会知道 maven 依赖如何配置，版本号如何选择，你用的是不是最新版本：
![Screenshot_2021-01-01-14-02-49-742_com android chrome](https://user-images.githubusercontent.com/12100985/103434314-bb5a3f00-4c3a-11eb-8eb6-69826a45149d.jpg)

**Comment by Him188** [comment]
如果你去查阅了历史issues，你也会知道登录失败的原因：
![Screenshot_2021-01-01-14-04-52-888_com android chrome](https://user-images.githubusercontent.com/12100985/103434327-eb094700-4c3a-11eb-80b5-ae772eca80d2.jpg)

**Comment by Him188** [comment]
如果你稍微仔细一点看文档，看了第一个章节 Bots 你还会知道登录错误的原因列表

![Screenshot_2021-01-01-14-03-18-993_com android chrome](https://user-images.githubusercontent.com/12100985/103434339-0aa06f80-4c3b-11eb-9fff-232ccdc802ec.jpg)

**Comment by Him188** [comment]
又或是你去了 Discussions，第一个问题就是登录失败，你也能看到文档链接
![Screenstitch_20210101-140345](https://user-images.githubusercontent.com/12100985/103434346-286dd480-4c3b-11eb-9298-1fc35dc4350d.png)

**Comment by Him188** [comment]
因此我认为你什么都没有查阅就来开issue告诉我我文档没有提及，历史issue也没有解决办法。我没有耐心每天处理几个这样的issue。
