### ISSUE TITLE
一个mirai可能无法处理的字符

### ISSUE THREAD

**Issue by liergazi** [mamoe/mirai#801]
在群内发送带有“⑩”这个字符的消息时，mirai日志里检测不到。
同样的，让mirai-bot在群内发送带有“⑩”这个字符的消息，也不会正常显示(群里看不到但mirai日志会显示)
mirai-core-all-2.0-M2-all.jar
mirai-console-terminal-2.0-M2-all
mirai-console-2.0-M2-all
⑨⑪这两个却正常。
辛苦你们啦

**Comment by sandtechnology** [comment]
此为腾讯服务器bug 官方客户端可复现 请向腾讯方反馈

**Comment by StageGuard** [comment]
![4)EBN@Y0566AX55UIOT_)I9](https://user-images.githubusercontent.com/45701251/103439547-cdf36900-4c78-11eb-8045-cbf56c8bca4f.jpg)

**Comment by mzdluo123** [comment]
刚刚试了一下，在Android和iOS客户端发送的符号是可以收到的。但是在Windows客户端的不行。。。。。
