### ISSUE TITLE
支持语音电话API

### ISSUE THREAD

**Issue by jacktang** [mamoe/mirai#802]
Mirai已经支持语音消息，不知道能不能支持语音电话(voip)层面。应用场景支持比如：一些比较紧急的报警情况，需要语音电话给对方播报当时的情况。

**Comment by StageGuard** [comment]
语音电话并不是处理你所说的紧急情况的唯一方式

**Comment by sandtechnology** [comment]
感觉应用性不强，如果遇到紧急情况这类，并不会通过voip方式进行沟通，而是更为直接的电话短信等通讯方式。
还有其他的应用场景吗？

**Comment by mzdluo123** [comment]
紧急情况直接购买一个GSM模块打电话不好吗？QQ电话需要联网，GSM模块直接通过运营商打电话不是更方便吗
