### ISSUE TITLE
支持文件消息

### ISSUE THREAD

**Issue by jacktang** [mamoe/mirai#805]
目前协议未支持文件消息。

相关: 
1) https://github.com/project-mirai/mirai-api-http/issues/193

**Comment by Him188** [comment]
可能会在2.3/2.4支持，在2.2实现语音highway时也会顺手研究一下文件

**Comment by talosu** [comment]
> 可能会在2.3/2.4支持，在2.2实现语音highway时也会顺手研究一下文件

辛苦了

**Comment by Him188** [comment]
现在已经实现基本协议, 待 https://github.com/mamoe/mirai/actions/runs/610060151 完成后可以尝试 `2.5-M2-dev-2`
