### ISSUE TITLE
MessageChain.get(PlainText.Key)会取到at的对象

### ISSUE THREAD

**Issue by Lin-XCC** [mamoe/mirai#806]
通过event.getMessage().get()方法取消息链中的元素时，如果是 at+文本内容 的消息，通过PlainText.key会取到at的对象内容，而不是at之后的文本内容。
  另外这个方法貌似取到的是第一个出现的key元素，个人觉得方法命名有些不妥，改成getFirst（）之类是否更加明确？

#### 复现

1.发送一条at+文本类型的消息
2.事件中获取消息链
3.消息链调用.get(At.Key)与.get(PlainText.Key)
4.输出后发现两者相同 都为at信息

#### 版本
mirai: `2.0-M2-1 `

**Comment by Him188** [comment]
2.0 已经没有这样的获取方式了，请更新 2.0-M2
