### ISSUE TITLE
[bug]at消息在QQ手机端无法正常显示,却在tim客户端正常显示

### ISSUE THREAD

**Issue by I-love-study** [mamoe/mirai#816]
当机器人发送的消息带有at的时候
在QQ手机端不会显示"@"
![image](https://user-images.githubusercontent.com/39652142/103626749-9d147c00-4f77-11eb-9115-7d51356382fb.png)
但是在tim电脑端却显示了"@"
![image](https://user-images.githubusercontent.com/39652142/103626942-df3dbd80-4f77-11eb-91ba-b8702ad926ef.png)

控制台显示的是带有at的mirai码
![image](https://user-images.githubusercontent.com/39652142/103627064-101df280-4f78-11eb-99c7-026174a5c912.png)

#### 复现

发送一个带at的消息

#### 版本
mirai: `20.-M2-2 ` 
QQ:`8.5.0.5025(Android)`
Tim:`3.3.0(21970)(Windows)`

**Comment by sandtechnology** [comment]
该问题已被https://github.com/mamoe/mirai/commit/9c6096127115896f92494106505ce1d456c4c30b修复
