### ISSUE TITLE
Bot 加群和退出群无法触发BotLeaveEvent和BotJoinGroupEvent事件

### ISSUE THREAD

**Issue by sulinwork** [mamoe/mirai#826]
我使用的版本是2.0-M2-2
bot 自己加入一个新的群无法触发BotJoinGroupEvent事件 也无法接受到这个新加入的群消息
同理：bot主动退出群聊也无法触发BotLeaveEvent事件

`
          @EventHandler
            public void botLeaveEvent(BotLeaveEvent event) {
                System.out.println("退出群聊：" + event.getGroup().getName());
            }
            @EventHandler
            public void botJoinGroupEvent(BotJoinGroupEvent event) {
                System.out.println("加入群聊：" + event.getGroup().getName());
            }`

**Comment by Him188** [comment]
是在其他客户端操作？

**Comment by sulinwork** [comment]
> 是在其他客户端操作？

是的 我在PC端退了一个群

**Comment by sandtechnology** [comment]
此为官方客户端也有的问题，与Mirai无关，是服务器没有发送相关的退群和进群消息：
PC客户端退群无法同步
而对于需要管理员验证的群也无法同步入群消息
