### ISSUE TITLE
请问新版本是不是去掉了修改群员名片的方法

### ISSUE THREAD

**Issue by baihuagongshlei** [mamoe/mirai#827]
请问新版本是不是去掉了修改群员名片的方法，源码中没找到！

**Comment by sandtechnology** [comment]
您好，没有的！
请贴出仔细代码哦！

**Comment by baihuagongshlei** [comment]
@NotNull
    @EventHandler
    public ListeningStatus onGroupMessageEvent(@NotNull GroupMessageEvent event) throws Exception { // 可以抛出任何异常, 将在 handleException 处理
        String msgString = event.getMessage().contentToString();
        log.debug("接收群"+event.getGroup().getId()+"消息：" + msgString);

        event.getSender().

        就是这地方，原来可以直接使用 member.setNameCard(server.getServer_name()+"-"+newPlayers.getPlayer_name());
        现在没有这个方法了；

**Comment by sandtechnology** [comment]
您好！你的版本呢！

**Comment by baihuagongshlei** [comment]
<dependency>
            <groupId>net.mamoe</groupId>
            <artifactId>mirai-core-all</artifactId>
            <version>2.0-M2-2</version>
            <type>pom</type>
        </dependency>
        <dependency>
            <groupId>org.jetbrains.kotlin</groupId>
            <artifactId>kotlin-stdlib-jdk8</artifactId>
            <version>1.4.20</version>
        </dependency>

因为用
<dependency>
            <groupId>net.mamoe</groupId>
            <artifactId>mirai-core</artifactId>
            <version>2.0-M2-2</version>
            <type>pom</type>
        </dependency>
这个依赖包报错，所以换成了-all这个

**Comment by Karlatemp** [comment]
Member由于匿名成员（`AnonymousMember`）的存在，设置群昵称的接口搬迁至正常群成员（`NormalMember`）中，请自行判断sender是否为 `NormalMember`
```java
Member member = event.getSender();
if (member instanceof NormalMember) {
    ((NormalMember) member).setNameCard("custom");
}
```
若问题解决， 请关闭此 issue

**Comment by baihuagongshlei** [comment]
哦，谢谢，明白了

**Comment by Karlatemp** [comment]
> ```
>     <dependency>
>         <groupId>net.mamoe</groupId>
>         <artifactId>mirai-core-all</artifactId>
>         <version>2.0-M2-2</version>
>         <type>pom</type>
>     </dependency>
>     <dependency>
>         <groupId>org.jetbrains.kotlin</groupId>
>         <artifactId>kotlin-stdlib-jdk8</artifactId>
>         <version>1.4.20</version>
>     </dependency>
> ```
> 
> 因为用
> 
> net.mamoe
> mirai-core
> 2.0-M2-2
> pom
> 
> 这个依赖包报错，所以换成了-all这个

请详细阅读文档

https://github.com/mamoe/mirai/blob/dev/docs/ConfiguringProjects.md#b-%E4%BD%BF%E7%94%A8-maven

**Comment by baihuagongshlei** [comment]
我的错，没仔细看，以为只改了版本号，原来是 <artifactId>mirai-core-jvm</artifactId> ，多了个-jvm，谢谢了。我刚才都放弃直接集成了，搞http-api了。
