### ISSUE TITLE
私聊图片图裂

### ISSUE THREAD

**Issue by lliioollcn** [mamoe/mirai#830]
#797 
如上，群图片现在正常，但私聊图片仍然图裂

```
无
```

#### 复现

私聊发送图片

#### 版本
mirai: ` 2.0-RC-dev-5`

**Comment by Him188** [comment]
![G)WFHOSKM 0XJN`BVCEJF5](https://user-images.githubusercontent.com/12100985/104086317-d27bdb00-5291-11eb-8213-1b490cbd378e.png)
经测试, 好友图片正常上传发送

**Comment by Him188** [comment]
请提供其他一切环境信息和复现方式

**Comment by lliioollcn** [comment]
https://lliiooll.lanzous.com/b0103kqri
密码:1234
环境linux
ps: 可以私聊我qq向我索要当前环境的vps
3483706632

**Comment by Him188** [comment]
私聊图片上传通道是 HTTP，会有不稳定的情况，需要通过 #194 解决

**Comment by Him188** [comment]
请查看 #194 获取修复进度
