### ISSUE TITLE
2.0 RC 更新后无法启动

### ISSUE THREAD

**Issue by WindLeaf233** [mamoe/mirai#851]
我在测试代码的时候，重启了一下 mirai-console-loader，提示说有更新下载
下载完成后，Windows(7 x64) 端报错并闪退，Linux(Ubuntu) 端报错没有闪退

似乎 Win 与 Linux 端遇到的问题不一样...

```
Windows(7 x64)：https://pastebin.ubuntu.com/p/2cKmppdzXX/
Linux(Ubuntu)：https://pastebin.ubuntu.com/p/7YN468q9b7/
```

#### 复现

1. 重启前 mcl 一切正常，没有报错
2. 重新启动 mcl
3. mcl 提示有更新，下载了 2.0 RC
4. 启动报错，并闪退
5. 尝试使用 linux 启动 mcl 时，更新后也报错，但没有闪退

#### 版本
- mirai-core: `1.3.0` 
mirai-core 2.0 RC
mirai-console-loader 1.0.3

**Comment by PeratX** [comment]
core和console 必须都为2.0-RC版本，如果最近没有更新计划，可以降级回去用。
大部分插件暂时还没有适配2.0-RC版本，将在近期跟进。
