### ISSUE TITLE
获取其他在线的设备

### ISSUE THREAD

**Issue by MrXiaoM** [mamoe/mirai#877]
是这样的，我现在需要一个功能，获取当前qq在线的设备，比如手机QQ在线，APAD在线，Android Watch在线等。
这对我在多台服务器开启机器人有非常大的帮助，我需要用于判断某台服务器是否在线，那台服务器上有个单独的机器人功能

**Comment by sandtechnology** [comment]
该功能已实现，请查看OtherClient相关API

**Comment by Him188** [comment]
bot.otherClients
