### ISSUE TITLE
掉线后无法重连

### ISSUE THREAD

**Issue by wangzheooo** [mamoe/mirai#900]
环境是openjdk8,springboot+Mirai 
然后2021年1月25日晚上换的2.1.0版本,到了今早上8:00还能往群里主动发内容,然后到了8:48的时候,就阻塞了
![image](https://user-images.githubusercontent.com/55420071/105653129-f546fa00-5ef5-11eb-9e38-071263802541.png)
然后在控制台ctrl+c,手机上给机器人发消息试一下触发事件,还是阻塞,又ctrl+c了两次,然后就能正常触发事件了,不过控制台报了两个错误
![image](https://user-images.githubusercontent.com/55420071/105653271-553da080-5ef6-11eb-8dc7-474b8431a35b.png)
![image](https://user-images.githubusercontent.com/55420071/105653291-65558000-5ef6-11eb-91f2-0565c69066e5.png)

**Comment by Him188** [comment]
是因为在cmd 选定内容后导致阻塞么

**Comment by wangzheooo** [comment]
> 是因为在cmd 选定内容后导致阻塞么

没有选定cmd中的内容,当时在群里发送一个天气的命令,然后机器人没有回复信息,我打开服务器后,看到控制台没有我发送的内容,怀疑是阻塞了,然后就ctrl+c按了几下,就恢复正常功能了

**Comment by Karlatemp** [comment]
属于 chat-command 执行错误, chat-command 没有使用异步导致 mirai 卡死

**Comment by Karlatemp** [comment]
猜测是接入代码执行时间过长导致事件系统等待执行完成，然后超时

**Comment by Karlatemp** [comment]
请在需要长时间处理的事件中 launch 一个新的协程脱离事件协程, 就不会堵住 mirai

**Comment by wangzheooo** [comment]
> 请在需要长时间处理的事件中 launch 一个新的协程脱离事件协程, 就不会堵住 mirai

明白了,确实有个事件触发后执行时间有点长,我改进一下看看情况

**Comment by Him188** [comment]
可尝试 2.2.0-dev-1

**Comment by wangzheooo** [comment]
> 可尝试 2.2.0-dev-1

好滴

**Comment by Him188** [comment]
在我这里测试和群友测试结果表明改善了一些, 我会发布 2.1.1 包含这些修复
