### ISSUE TITLE
FriendMessageSyncEvent事件无法触发

### ISSUE THREAD

**Issue by sulinwork** [mamoe/mirai#904]
我使用的是mirai-core:2.1.0版本
`
GlobalEventChannel.INSTANCE.subscribeAlways(GroupMessageSyncEvent.class, event -> {
            System.out.println("*******GroupMessageSyncEvent*********");
        });
GlobalEventChannel.INSTANCE.subscribeAlways(FriendMessageSyncEvent.class, event -> {
            System.out.println("___________FriendMessageSyncEvent______________");
        });
`
我在其他客户端发送群消息 这边可以出发事件GroupMessageSyncEvent
但是在其他客户端私聊 无法触发FriendMessageSyncEvent事件

**Comment by sandtechnology** [comment]
1.请提供网络日志，后台是否打印出好友信息？
2.请提供使用的其他客户端的类型和版本

**Comment by sulinwork** [comment]
> 1.此时没有任何网络日志的输出 并且能打印好友的信息
> 2.其他客户端使用的是android  V8.1.18.4945版本和windos9.4.2版本， Bot使用PAD协议登录

**Comment by sandtechnology** [comment]
> 
> 
> > 1.此时没有任何网络日志的输出 并且能打印好友的信息
> > 2.其他客户端使用的是android  V8.1.18.4945版本和windos9.4.2版本， Bot使用PAD协议登录

好友消息是指其他客户端发送的信息还是好友发送的信息？

**Comment by sulinwork** [comment]
我在其他客户端（安卓QQ）给 一个好友发送消息 并不是好友给我发送消息

**Comment by sandtechnology** [comment]
> 
> 
> 我在其他客户端（安卓QQ）给 一个好友发送消息 并不是好友给我发送消息

所以是安卓QQ和windows客户端均可复现吗？
如果切换到phone协议呢？

**Comment by sulinwork** [comment]
我这边安卓QQ和windows均可复现 
我把Bot切换成phone协议依然存在这个问题

**Comment by sandtechnology** [comment]
For remark: type=6

**Comment by sulinwork** [comment]
> For remark: type=6

**Comment by sulinwork** [comment]
> For remark: type=6

什么意思

**Comment by Karlatemp** [comment]
同时登陆 QQ PC, QQ Android, 对某位好友发送私聊, 官方客户端也会出现这种情况, 所以推测可能根本无法支持

**Comment by sulinwork** [comment]
> 同时登陆 QQ PC, QQ Android, 对某位好友发送私聊, 官方客户端也会出现这种情况, 所以推测可能根本无法支持

我去试了下  官方私聊确实它本身就存在同步问题  感谢！
