### ISSUE TITLE
MiraiCode.deserializeMiraiCode()无法转换包含不止mirai码的文本

### ISSUE THREAD

**Issue by moemoli** [mamoe/mirai#905]
![图片](https://user-images.githubusercontent.com/44719954/105684068-6951c400-5f2f-11eb-9ea3-b5303c6bc17c.png)

第一、三条为转换之后的
第二、四条为原消息

**Comment by Him188** [comment]
请问版本号

**Comment by Karlatemp** [comment]
提供复现代码

**Comment by moemoli** [comment]
> 
> 
> 请问版本号

2.1.0

**Comment by moemoli** [comment]
> 
> 
> 提供复现代码

Friend.sendMessage(MiraiCode.deserializeMiraiCode("这是一个测试消息 [mirai:face:4] asfddasfaewfrewadsfs"));

**Comment by Karlatemp** [comment]
经测试， MiraiCode 解析没有问题，可能问题出在发送

**Comment by Karlatemp** [comment]
![image](https://user-images.githubusercontent.com/30070303/105858350-2e7e8780-6026-11eb-9d0b-b73282f9713e.png)
无法复现

**Comment by sandtechnology** [comment]
> 
> 
> > 请问版本号
> 
> 2.1.0

Java环境下同样无法复现，请确认mirai-core版本：
![TIM截图20210126234328](https://user-images.githubusercontent.com/20417547/105867665-4f4bda80-6030-11eb-8776-5eeb2fb35b85.png)

**Comment by moemoli** [comment]
new Thread(()->{
            for (int i=0;i<4;i++){
                try {
                    Thread.sleep(1000L);
                } catch (InterruptedException e) {
                    e.printStackTrace();
                }
                b.getFriend(3483706632L).sendMessage("这是一个测试消息 [mirai:face:4] asfddasfaewfrewadsfs");
            }
        }).start();

这样会有问题......

**Comment by sandtechnology** [comment]
> 
> 
> new Thread(()->{
> for (int i=0;i<4;i++){
> try {
> Thread.sleep(1000L);
> } catch (InterruptedException e) {
> e.printStackTrace();
> }
> b.getFriend(3483706632L).sendMessage("这是一个测试消息 [mirai:face:4] asfddasfaewfrewadsfs");
> }
> }).start();
> 
> 这样会有问题......

你并没有进行deserializeMiraiCode的操作 而且异步进行访问并没有问题

**Comment by moemoli** [comment]
> 
> 
> > new Thread(()->{
> > for (int i=0;i<4;i++){
> > try {
> > Thread.sleep(1000L);
> > } catch (InterruptedException e) {
> > e.printStackTrace();
> > }
> > b.getFriend(3483706632L).sendMessage("这是一个测试消息 [mirai:face:4] asfddasfaewfrewadsfs");
> > }
> > }).start();
> > 这样会有问题......
> 
> 你并没有进行deserializeMiraiCode的操作 而且异步进行访问并没有问题

抱歉，是我傻逼了
