### ISSUE TITLE
部分图片无法发送

### ISSUE THREAD

**Issue by eli-zhai** [mamoe/mirai#906]
Java代码：
 InputStream inputStream = new URL(s).openConnection().getInputStream();
ExternalResource.sendAsImage(ExternalResource.create(inputStream),contact);

当url为http://tiebapic.baidu.com/forum/w%3D580/sign=a69e69513af5e0feee1889096c6134e5/fcbf4890f603738dfff66a6aa41bb051f919ec7c.jpg?qq-pf-to=pcqq.c2c
时图片发送之后，收到的图片无法加载

#### 版本
- mirai-core: `2.0.0`

**Comment by mzdluo123** [comment]
使用官方QQ客户端能够发送并正常显示这张图片吗？
