### ISSUE TITLE
2.1.1在平板模式登录，给好友发消息后，TIM显示在线图标变为手机。

### ISSUE THREAD

**Issue by RrrrLin** [mamoe/mirai#929]
登录之后在群内发消息，机器人的在线方式不会改变。
但是在给好友发消息后，在PC端TIM中，机器人头像右下角在线方式会变为手机。再过一段时间后，又会变为平板在线。
这种变化貌似没有功能上的影响。群消息和好友消息的收发均一切正常。

#### 复现

1.使用平板协议登录机器人QQ。
2.向好友发送一条消息
3.观察机器人在线图标情况。

#### 版本
- mirai-core: `2.1.1`

**Comment by mzdluo123** [comment]
确认一下是否只有一个平板协议的mirai在线；此外，如果使用切换账号的形式退出该账号或是和另一个账号关联也会提示正在使用手机登录

**Comment by Karlatemp** [comment]
对 mirai 的运行并没有什么影响

**Comment by Him188** [comment]
应该是qq客户端问题

**Comment by RrrrLin** [comment]
> 应该是qq客户端问题

明白了，只是稍微有些疑问而已。目前发现PC端的tim会这样 手机端TIM就不会。
