### ISSUE TITLE
新版本语音被压缩

### ISSUE THREAD

**Issue by wyapx** [mamoe/mirai#940]
```

```

#### 复现

使用新版本mirai(2.2.1)发送语音时语音会被二压
使用旧版本mirai(2.1.0)发送语音则不会出现这种情况

#### 版本
- mirai-core: `2.2.1`

**Comment by wyapx** [comment]
版本号错了...是2.2.0-dev-4

**Comment by Him188** [comment]
经测试, TIM PC 接收到的文件是原文件 silk
![image](https://user-images.githubusercontent.com/12100985/106379560-d362e100-63e7-11eb-9f0f-51d37e025bb5.png)

**Comment by Him188** [comment]
在我这里测试音质是正常的，可能需要更多人反馈才能确定

**Comment by JoinChang** [comment]
经测试2.3.2仍然压缩

**Comment by Him188** [comment]
> 经测试2.3.2仍然压缩

请提供语音源文件

**Comment by JoinChang** [comment]
> 请提供语音源文件

所有silk后缀的语音格式都会被压缩，没有不压缩的个例。在个人开发机与服务器测试均会压缩，难不成是我编译问题 `gradlew shadowJar` 。

**Comment by Him188** [comment]
> > 请提供语音源文件
> 
> 所有silk后缀的语音格式都会被压缩，没有不压缩的个例。在个人开发机与服务器测试均会压缩，难不成是我编译问题 `gradlew shadowJar` 。

请任意提供一个会被压缩的语音文件

**Comment by dragon0629** [comment]
请问2.4现在发送语音的话，是否还需要自己单独写方法调用ffmpeg进行转码，以支持PC端的正常收听？
还是说已经实现了自动转码。

**Comment by sandtechnology** [comment]
> 
> 
> > 请提供语音源文件
> 
> 所有silk后缀的语音格式都会被压缩，没有不压缩的个例。在个人开发机与服务器测试均会压缩，难不成是我编译问题 `gradlew shadowJar` 。

更多怀疑的是编码过程中自身的问题，目前是需要自己提供转换为silk的方式，但是可以试试这个项目：https://github.com/mzdluo123/silk4j

**Comment by mzdluo123** [comment]
> 请问2.4现在发送语音的话，是否还需要自己单独写方法调用ffmpeg进行转码，以支持PC端的正常收听？
> 还是说已经实现了自动转码。

目前需要手动转码，不过我的这个项目可能能帮到你
https://github.com/mzdluo123/silk4j

**Comment by Him188** [comment]
经测试语音音质是正常的, 可能是在转码时有音质损失导致听起来差
