### ISSUE TITLE
机器人发送语音成功，QQ也能收到了语音，但收到的语音不能播放，提示是空的

### ISSUE THREAD

**Issue by jinghailun** [mamoe/mirai#946]
机器人发送语音成功，QQ也能收到了语音，但收到的语音不能播放，提示是空的。

2021-02-02 20:15:39 V/Net 281773638: [Highway] Uploading group voice to 123.150.76.170:8080, size=26.58 KiB
2021-02-02 20:15:39 V/Net 281773638: [Highway] Uploading group voice: succeed at 92 KiB/s
2021-02-02 20:15:39 V/Net 281773638: Send: MessageSvc.PbSendMsg

```

```

#### 版本
- mirai-core: `2.2.2`

**Comment by jinghailun** [comment]
![Uploading image.png…]()

**Comment by Karlatemp** [comment]
请提供语音源文件，并且确认语音源文件正常，并提供发送使用的代码

**Comment by jinghailun** [comment]
@Karlatemp  音频我是从网上下载到本地然后再发送的
音频文件地址：
https://ai-tts.datealive.com/f7b44f8eb207b8147e7920cab5bfd3c0.amr

以下是我的代码：
 File voiceFile = new File(voiceFilePath);
            if (!voiceFile.exists()) {
                System.out.println("音频文件不存在");
                return;
            }
            Voice voice = event.getGroup().uploadVoice(ExternalResource.create(voiceFile));
            event.getGroup().sendMessage(voice);


控制台对应的日志：
2021-02-03 10:54:02 V/Net 281773638: [Highway] Uploading group voice to 123.151.190.210:8080, size=162.84 KiB
2021-02-03 10:54:02 V/Net 281773638: [Highway] Uploading group voice: succeed at 273 KiB/s
2021-02-03 10:54:02 V/Net 281773638: Send: MessageSvc.PbSendMsg
2021-02-03 10:54:03 V/Net 281773638: Recv: MessageSvcPbSendMsg.Response.SUCCESS
2021-02-03 10:54:03 V/Bot 281773638: Group(810224403) <- [mirai:voice:A287368D5195D922892396AB3BC107FB.amr]

**Comment by Karlatemp** [comment]
mp3float, only amr/silk support now
```
[滤镜使用列表]
  (1) Built-in Async Reader
  (2) Built-in MP3 Parser
  (3) Built-in Audio Codec/Transform
  (4) DirectSound Audio Renderer

[音频信息]
  音频编码： MPEG Audio Layer 3(0x55) - 内置 FFmpeg 解码器(mp3float)
  采样率： 16000 -> 16000 Hz
  位率： 0 -> 16 位
  声道数： 1 -> 2 声道
  Bitrate: 96 kbps

General
Complete name                  : f7b44f8eb207b8147e7920cab5bfd3c0.amr
Format                         : MPEG Audio
File size                      : 163 KiB
Duration                       : 13 s 896 ms
Overall bit rate mode          : Constant
Overall bit rate               : 96.0 kb/s
Writing library                : LAME3.98UUUUUUUUUU
FileExtension_Invalid          : m1a mpa mpa1 mp1 m2a mpa2 mp2 mp3

Audio
Format                         : MPEG Audio
Format version                 : Version 2
Format profile                 : Layer 3
Duration                       : 13 s 896 ms
Bit rate mode                  : Constant
Bit rate                       : 96.0 kb/s
Channel(s)                     : 1 channel
Sampling rate                  : 16.0 kHz
Frame rate                     : 27.778 FPS (576 SPF)
Compression mode               : Lossy
Stream size                    : 163 KiB (100%)
Writing library                : LAME3.98UUUUUUUUUU


```

**Comment by Karlatemp** [comment]
https://github.com/mamoe/mirai/blob/3a8003057a593601dfe5a6dac3477503e29fc8a7/mirai-core-api/src/commonMain/kotlin/contact/Group.kt#L155-L167

**请使用 amr 或 silk 格式**
