### ISSUE TITLE
一个机器人close之后，其他机器人都会被close

### ISSUE THREAD

**Issue by eli-zhai** [mamoe/mirai#956]
一个机器人close之后，其他机器人都会被close

```

```

#### 复现

登录4个qq，挤掉其中一个qq，其他qq都会close，并重新login

#### 版本
- mirai-core: `2.3.0`

**Comment by Him188** [comment]
很奇怪, 理论上已经修复了

**Comment by eli-zhai** [comment]
[0m2021-02-03 17:02:10 V/Net 2765887760: Channel closed.[0m
[92m2021-02-03 17:02:10 I/Net 2765887760: Connected to server 183.232.95.151:80[0m
这个是机器人结束与重连日志
