### ISSUE TITLE
支持自动抢红包吗

### ISSUE THREAD

**Issue by weixinbao** [mamoe/mirai#96]

**Comment by Chenwe-i-lin** [comment]
这个不会做.

**Comment by uebian** [comment]
不支持

**Comment by Chenwe-i-lin** [comment]
@Him188 把这个问题 Close 掉吧

**Comment by Him188** [comment]
![image](https://user-images.githubusercontent.com/12100985/75208462-b4f76d00-57b6-11ea-82b1-9954fce74a12.png)

**Comment by Him188** [comment]
同时声明: [LICENSE](https://github.com/mamoe/mirai#%E8%AE%B8%E5%8F%AF%E8%AF%81)
如有冒犯请谅解
