### ISSUE TITLE
支持QQ咨询类型消息

### ISSUE THREAD

**Issue by CHFreezer** [mamoe/mirai#964]
腾讯已经把群临时会话全部设置成默认关闭了
目前寻找到的办法就是用类似PC端tencent://或移动端mqqwpa://的协议发起临时对话
*开启途径https://shang.qq.com/v3/widget.html
给机器人qq开始这项功能后，使用官方客户端（目前测试过PC、iOS）是可以接受到临时会话的消息
但是mirai console就和没反应一样，收不到咨询类型的信息。
可惜本人没系统学习过JAVA，看不懂所以放弃了

![5Y3){A$8U0 GVN}~3BG0J07](https://user-images.githubusercontent.com/28268343/106821882-ff68b580-66b8-11eb-9848-79c9f065c3ae.png)

**Comment by mzdluo123** [comment]
https://github.com/mamoe/mirai/issues/429
