### ISSUE TITLE
能否考虑增加一个获取某群成员QQ等级的接口

### ISSUE THREAD

**Issue by zxin8580** [mamoe/mirai#967]
在了解了mirai项目对于cookies等敏感信息的重视和保护后，球球加一个built in的获取等级接口用于初步审核拒绝入群的小号T。T

**Comment by Him188** [comment]
user.queryProfile().qLevel

**Comment by Karlatemp** [comment]
看描述是在入群申请的时候查询，执行的时候没有user，请使用 low level的 Mirai.queryProfile



---原始邮件---


 
user.queryProfile().qLevel
