### ISSUE TITLE
Github的Wiki页面中，“新的文档: mirai.md”打开为404

### ISSUE THREAD

**Issue by gclintj** [mamoe/mirai#968]
Github的Wiki页面中，“新的文档: mirai.md”打开为404.
不知可以从哪里入手了解学习这个项目？或加入相关社群？谢谢！

```

```

#### 版本
- mirai-core: `1.3.0`

**Comment by Him188** [comment]
仔细阅读项目主页

**Comment by Him188** [comment]
https://github.com/mamoe/mirai/blob/dev/docs/README.md
