### ISSUE TITLE
间断性消息内容无法发送

### ISSUE THREAD

**Issue by zmdyy0318** [mamoe/mirai#969]
使用版本：
mirai 2.3.2
http 1.9.8

问题描述：
自从最近升级到2.3.X版本后（版本号不确定，升级前没有问题），经常性控制台有输出群内却收不到任何类型的消息，其他群员也看不到，不去管他过段时间又好了，不去管他过段时间又不行了，这是腾讯风控吗？还是我操作不当？目前机器人只会发送正常聊天文字、emoji表情、语音、一些英文指令，没有发送其他类型消息。

问题出现时log：
因为出现问题时没有输出错误信息，上下文都是问题无关的群聊天记录，故没有截图全
![QQ图片20210205094226](https://user-images.githubusercontent.com/16699676/106978373-1ed61000-6797-11eb-8285-db168862ad93.png)

**Comment by Him188** [comment]
是登录过于频繁被风控了，或者是 PC 客户端问题，正常用户不会像测试机器人这样一分钟可以重启几次。一般登录完成等待几分钟或者先离线几分钟再登录可以解决

**Comment by Him188** [comment]
注：与 mirai 版本无关
