### ISSUE TITLE
请问QuoteReply要如何获取原消息的id?

### ISSUE THREAD

**Issue by LainNetWork** [mamoe/mirai#973]
版本：mirai-core-jvm: 2.3.2
您好，我在mirai 1.x版本时，通过消息Id缓存消息中的图片，然后在之后通过回复带有图片的消息来将图片发送到图片服务器，但升级到2.0之后，消息id变成了ids，QuoteReply也找不到获取源消息id的api了。。不知道是不是我姿势不正确？

**Comment by Him188** [comment]
可以使用 `ids ` 第一个元素来定位消息
