### ISSUE TITLE
每17分钟会断连一次，然后马上重连

### ISSUE THREAD

**Issue by CharlieYu4994** [mamoe/mirai#977]
平台：树莓派4B Debian10
JDK：openjdk11
网络环境：网线连接
mirai版本：2.3.2
mirai-console版本：2.3.2
问题：大约每17分钟会断连一次，然后马上重连
![Screenshot_20210204-104347_JuiceSSH](https://user-images.githubusercontent.com/29250409/106838163-b7588b80-66d6-11eb-86e5-e42c563d8a72.png)

**Comment by Him188** [comment]
目前来说断线重连是正常现象
