### ISSUE TITLE
请问一下，NormalMember 的 isMuted 和 isActive 属性分别是什么含义？

### ISSUE THREAD

**Issue by pandolia** [mamoe/mirai#978]
或者有没有完整的 Contact 的属性的中文说明文档？

**Comment by Him188** [comment]
![image](https://user-images.githubusercontent.com/12100985/107037589-427c7300-67f6-11eb-8315-d168b5e84a14.png)

**Comment by Him188** [comment]
![image](https://user-images.githubusercontent.com/12100985/107037676-5e801480-67f6-11eb-9329-fa42f9686017.png)

**Comment by Him188** [comment]
学会查看源码

Ctrl B

**Comment by pandolia** [comment]
好的，非常感谢！
