### ISSUE TITLE
终端验证码使用富文本或者使用特殊字符显示□■▓▒ 以方便查看(不计字体)

### ISSUE THREAD

**Issue by YuMu233** [mamoe/mirai#98]

**Comment by Him188** [comment]
有测试使用这些字符会效果更好吗

**Comment by liujiahua123123** [comment]
1: 此功能可以由插件提供
    by providing new LoginSolver
2: 目前显示状态辨别度中等较好, 且目前情况来看, 登陆验证码只会每个账号出现一次, 使用富文本需要考虑到windows用户, 并且目前Console提供了tempFile查看验证码的方式, 这不是一个在当前开发阶段有意义的enhancement
